### ISSUE TITLE
Can't Sandbox Sequel Ace

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#10]
Sequel Ace is all set up to be sandboxed, but enabling sandboxing breaks ssh connections to databases.

The error arises from the inability to register the connection on line 97 of SPSSHTunnel.m
`[tunnelConnection registerName:tunnelConnectionName]` returns `NO`

The app must be sandboxed to be releasable on the macOS App Store

**Comment by Jason-Morcos** [comment]
@jamesstout I don't know if you have any ideas about this one - I beat my head against a wall and at least could find where it couldn't connect but not why the sandbox would be prohibiting it.

**Comment by jamesstout** [comment]
OK, I can replicate, but I'm really an iOS dev. Mac sandboxing is a bit new to me. I'll spend some time on it.

**Comment by gboudreau** [comment]
I found the issue. I'll send a PR with the details in a few minutes.
