### ISSUE TITLE
Missing Query Editor themes

### ISSUE THREAD

**Issue by gboudreau** [Sequel-Ace/Sequel-Ace#100]
- Sequel Ace Version: 2.1.0 beta 4
- macOS Version: 10.15
- MySQL Version: N/A

**Description**
I see no themes available in Preferences > Query Editor.

**Steps To Reproduce**
![image](https://user-images.githubusercontent.com/370329/85627414-71b1eb80-b63c-11ea-8aea-d202270b1d0f.png)

**Expected Behaviour**
There should be a few themes there... Not sure how many.

**Comment by gboudreau** [comment]
Can people please vote up or down this comment, to indicate if you do have this problem (vote up), or you do see themes (vote down)?
Thx.

**Comment by jamesstout** [comment]
I have some, but only because I copied them to the container manually...
