### ISSUE TITLE
Disable skip-show-database warning

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#1000]
Would be nice if there was an preference to disable this warning:

"The skip-show-database variable of the database server is set to ON. Thus, you won't be able to list databases unless you have the SHOW DATABASES privilege.
However, the databases are still accessible directly through SQL queries depending on your privileges."

Pretty annoying to get this on every DB connection I make (a lot per day)

**Comment by Jason-Morcos** [comment]
@gduh Do you want to take a look at this? Perhaps in the popup just add a button to "Never show this again for this connection" or something?

**Comment by gduh** [comment]
@Jason-Morcos Ok, I take it. 
Just a check box to disable the message box. Nothing to reactivate it ?

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos Ok, I take it. 
> Just a check box to disable the message box. Nothing to reactivate it ?

Yeah, sounds fine to me. Or could have an option in preferences paired to it (so that checkbox in prefs can be toggled to re-enable)

**Comment by gduh** [comment]
> > @Jason-Morcos Ok, I take it. 
> > Just a check box to disable the message box. Nothing to reactivate it ?
> 
> Yeah, sounds fine to me. Or could have an option in preferences paired to it (so that checkbox in prefs can be toggled to re-enable)

Yes, that's what I thought.
