### ISSUE TITLE
Improve the connection coloring system to color the main window somehow, if only one tab is open

### ISSUE THREAD

**Issue by indreka** [Sequel-Ace/Sequel-Ace#1001]
When opening a new window with only one tab, the tab bar is not shown (which is ok and was same before 3.3).
But after latest change to only color a small dot on the tab in 3.3, the window itself does not have any colors anymore (because tab bar is hidden). Makes it quite hard to differentiate between dev test prod environments when multiple one-tab windows are open side-by-side.

Is it possible to apply active tab color to the overall window somehow?

**Comment by ATM-NET** [comment]
+1
Tiny colored circles on tabs (favorite connect colors) are very unsafe. With hard work, I can easily overlook, what database I am in edit now and send a test update there or delete the request.
How can I set the color for the whole tab right now?

**Comment by ATM-NET** [comment]
Sorry, but

http://radikal.ru/fp/zfcppyp48mxex

**Comment by Kaspik** [comment]
You are talking about circles, I'm talking about "single tab colorized", Your issue is handled in separate thread - https://github.com/Sequel-Ace/Sequel-Ace/issues/1013

**Comment by samuelbradshaw** [comment]
I think part of the reason it's easy to miss which database you're editing is because of the long title that shows as the tab title, and is repeated for each tab. In particular, I'm wondering if it would be a good idea to get rid of the MySQL version from the title of the tab.

**Comment by ATM-NET** [comment]
@Kaspik It doesn't matter what the problem's name. Matters, that problem exists.
Now it is difficult for me to identify where I work: with prod or with dev. Small colored dots do not allow you to do this without straining my eyes.
In your screenshot, a compromise, although worse than the original, but has the right to live. How can I to get coloring like yours?

![_screenshot 2021-04-07 в 19 38 00](https://user-images.githubusercontent.com/42110592/113889173-67806880-97dc-11eb-890e-cae76571d337.jpg)

**Comment by Kaspik** [comment]
The dots are already changed to my screenshots and will be released in 3.3.1.

This issue is not about the dot or coloring. It's about coloring single tab. Both issues are now fixed.

**Comment by ATM-NET** [comment]
Uff, I'll wait for 3.3.1.
Thanks for your efforts. This project is the best for working with databases under Mac OS.

**Comment by Kaspik** [comment]
We will ship beta in couple of hours definitely so you will be able to try that one. :) Thanks!
