### ISSUE TITLE
Filteroption is missing after first use v 3.3.0

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#1002]
- Sequel Ace Version (including build number): 3.3.0
- Sequel Ace Source (App Store/GitHub/Homebrew):GitHub
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.5.9
- macOS Localization: 

* Install 3.3.0 via github (replace 3.2)
* Open DB connection
* Go to content tab

=> There is no default filter active
=> cmd + F does not work
=> there is no [+] to activate a filter somewhere
=> I had to click the small filter icon in the footer of the content to activate it

Now a filter is always there, also after restart.

**Comment by Jason-Morcos** [comment]
Cmd+F will be fixed in next patch release, beta available now - https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.3.1-3027

Fixed by: https://github.com/Sequel-Ace/Sequel-Ace/pull/1017

Please try the beta and let us know if these issues are fully resolved
