### ISSUE TITLE
`open table in new tab` not work

### ISSUE THREAD

**Issue by zhifeifu** [Sequel-Ace/Sequel-Ace#1003]
![image](https://user-images.githubusercontent.com/30519864/113703612-a2679b00-970d-11eb-9376-179d36dfd631.png)

**Comment by zhifeifu** [comment]
version: 3.3.0

**Comment by Kaspik** [comment]
Hmm, that should be removed completely iirc. Let me double check that.

**Comment by LiamKearn** [comment]
@zhifeifu Workaround for now is just pressing cmd + t to open a new tab and reconnecting to your current host.

@Kaspik Why is the feature being remove if I may ask?

**Comment by Kaspik** [comment]
I said it wrong - this was removed from the "File" menu as there is already the same shortcut / menu doing the same - CMD+SHIFT+T (or in File - Duplicate connection tab). I just forgot to remove / rename it here when right clicking on the table. :)
