### ISSUE TITLE
Save connection doesn't appear to do anything?

### ISSUE THREAD

**Issue by seanr** [Sequel-Ace/Sequel-Ace#1005]
- Sequel Ace Version (including build number): 3.3.0 (build 3026)
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: Big Sur (11.2.2)
- Processor Type (Intel/Apple): Intel
- MySQL Version: N/A
- macOS Localization: none

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Current release is latest.

**Description**

**Steps To Reproduce**
1. Connect to a server from a CLI tool, for example how Terminus's Pancakes plugin does this here: https://github.com/terminus-plugin-project/terminus-pancakes-plugin/blob/master/src/Apps/SequelProApp.php
2. File -> Save connection
3. Does nothing, no indication of what it was supposed to do, whether that failed, etc. Nothing added to the saved connections when opening a new window.

**Expected Behaviour**
Either add it to the saved connections or give me a prompt to fill in a name, etc., and save it.

**Additional Context**
I use a command line tool called Terminus for managing sites on my hosting provider (Pantheon). Among the many useful plugins is one called Pancakes that will fire up a SQL connection to the specified site and environment (`terminus pc example.live`). I'd like to then save this into my saved connections so I don't have to type the command each time. Copying the connection info manually from the host's dashboard is possible but a little painful.

If the current "save connection" feature is just saving it back wherever it got the connection info from, we need a "save as" feature.

**Comment by Kaspik** [comment]
Does that plugin actually work? There is no Sequel Ace version, so not sure how it's opening connections. Opening connection manually, "File - Save Connection" opens save panel as it should for me...

**Comment by seanr** [comment]
Yes, it actually does work. I think it just opens in whichever application is set to open for that on the system, so it opened Sequel Pro when I had that, but after uninstalling that and installing Sequel Ace in its place, it now opens Ace as one would hope. :)
