### ISSUE TITLE
Users tab not clickable at all

### ISSUE THREAD

**Issue by mfehr94** [Sequel-Ace/Sequel-Ace#1011]
- Sequel Ace Version (including build number): 3.3.0 (3026)
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: german

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes

**Description**
It is not possible to click the Users Icon. It is allways disabled. 

**Steps To Reproduce**
1. Connect to any DB.
2. Try to open Users Tab.

![image](https://user-images.githubusercontent.com/14167832/113828800-13966500-9785-11eb-925e-cf9697543405.png)

**Expected Behaviour**

Users tab should be clickable and users overview should show up.

**Related Issues**

**Additional Context**

**Comment by FaimMedia** [comment]
Sometimes I do can click it, but it makes SA crash immediately...
