### ISSUE TITLE
Cmnd + F doesn't focus on filter input field anymore

### ISSUE THREAD

**Issue by Maikel-Koek** [Sequel-Ace/Sequel-Ace#1014]
- Sequel Ace Version (including build number): 3.3.0 Build 3026
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version: Big Sur 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7 + 8.0
- macOS Localization: Dutch

**Description**
Pressing <kbd>Command</kbd> + <kbd>F</kbd> doesn't focus the cursor on the filter input field anymore in the 'Content' tab, for searching through a table, while this was possible in 3.2.3.

**Steps To Reproduce**
1. Select a table
2. Open 'Content' tab
3. Hit <kbd>Command</kbd> + <kbd>F</kbd>
4. Nothing happens

**Expected Behaviour**
1. Select a table
2. Open 'Content' tab
3. Hit <kbd>Command</kbd> + <kbd>F</kbd>
4. Cursor focusses on filter input field

**Comment by Kaspik** [comment]
I'm on the fence here. I know it was possible to open the filter with CMD+F, but that if (generally) for Find (which is what it is now - Edit -> Find -> Find has CMD+F). I'm not sure if we should revert back to CMD+F for filter, or find a new shortcut for filter...

**Comment by Maikel-Koek** [comment]
@Kaspik I know, that makes sense, it seems in previous versions CMD+F was also used for Find, but just in tabs other than the 'Content' tab.
When hitting CMD+F in the Query tab for instance, Find is actually opened, so I guess there was an exception made here on the Content tab? Which I actually really used a lot, no other use for Find on that tab anyway.

**Comment by Kaspik** [comment]
Interesting, didn't think about it that way. Pushed to the PR, will merge soon!
