### ISSUE TITLE
SSH tunnel with jump host: Operation not permitted

### ISSUE THREAD

**Issue by sfdye** [Sequel-Ace/Sequel-Ace#1016]
- Sequel Ace Version (including build number): Version 3.3.0 Build 3026
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 11.2.3 (20D91)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: en_US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

No beta, already latest version 

**Description**

```
debug1: Authentication succeeded (publickey).
Authenticated to jumpbox.xxx.com ([xx.xx.xx.xx]:22).
debug1: setting up multiplex master socket
unix_listener: cannot bind to path /Users/xxx/.ssh/cm-XXXXXXX (very long random hash) : Operation not permitted
kex_exchange_identification: Connection closed by remote host
The SSH Tunnel has unexpectedly closed.
```

**Steps To Reproduce**
1. Create new connection with SSH using jumphost
2. Test connection

**Expected Behaviour**

It should be able to connect. Same config works on Sequel Pro.

**Related Issues**

**Additional Context**

**Comment by Kaspik** [comment]
You need to give Sequel Ace access to that ssh file. See https://sequel-ace.com/get-started/ about SSH config. Is that your issue?

**Comment by sfdye** [comment]
Already did, given Sequel Ace access to

- ssh_config
- id_rsa
- known_hosts
and the directory .ssh itself

**Comment by Jason-Morcos** [comment]
Can you share an obfuscated screenshot of your connection settings screen and Sequel Ace network and files preferences tabs?
Did you select the actual ssh key in the connection settings and select your ssh config file in the network tab of Ace's preferences? I know you granted Sequel Ace access to these files, but it still has to know to explicitly use them

**Comment by sfdye** [comment]
Connection setting

![image](https://user-images.githubusercontent.com/1016390/114018990-74ff2680-98a0-11eb-904e-0cb57fb38988.png)


Network tab
![image](https://user-images.githubusercontent.com/1016390/114018835-408b6a80-98a0-11eb-9d50-4369dc1e130c.png)

Files tab
![image](https://user-images.githubusercontent.com/1016390/114018889-5436d100-98a0-11eb-992a-10aecd13ab63.png)

**Comment by mfehr94** [comment]
@sfdye you missing your ssh password see https://user-images.githubusercontent.com/14167832/110969402-ef4b9200-8358-11eb-8148-b110d4e22c35.png

**Comment by sfdye** [comment]
I use ssh config + ssh agent so don't think this is needed.

Anyway I tried and it's the same error with or without specifying the ssh key.

**Comment by sfdye** [comment]
![image](https://user-images.githubusercontent.com/1016390/114029528-2e172e00-98ac-11eb-8379-d8ea67103ec4.png)
After changing the known hosts to `~/.ssh/known_hosts`, I got this:

![image](https://user-images.githubusercontent.com/1016390/114029460-1a6bc780-98ac-11eb-88a8-875ad88d0f97.png)

**Comment by sfdye** [comment]
Should I try my luck with an older build?

**Comment by Kaspik** [comment]
Can you remove and select the files that Sequel has access to again please?

**Comment by sfdye** [comment]
Believe it or not, I tried that yesterday already

**Comment by sfdye** [comment]
I just tried again, still could not connect after I downgraded to Sequel Ace `2.3.1`, but works on Sequel Pro `1.1.2` with the exact same creds 🤔

**Comment by Jason-Morcos** [comment]
Sequel Ace and Sequel Pro are quite different functionally. Sequel Pro was unsanboxed, it could read and write files anywhere in your file system at will.
Sequel Ace embraces the sandbox, which means it can't randomly read and write files. The sandbox is probably intervening here
