### ISSUE TITLE
Brazilian Portuguese localization

### ISSUE THREAD

**Issue by Giuliano-sn** [Sequel-Ace/Sequel-Ace#1018]
Hello @Kaspik !
I would like to contribute with Portuguese (Brazilian) localization.
May you add that in crowdin?

**Comment by Kaspik** [comment]
Added, you can start! Thanks! :)

**Comment by Giuliano-sn** [comment]
Thanks!
I'm working on it!
Don't forget to update credits ok?
;-)

**Comment by Kaspik** [comment]
Haha, feel free to open a PR with that 😄

**Comment by Giuliano-sn** [comment]
Done!
