### ISSUE TITLE
Preferences window is disabled with a new unconnected tab

### ISSUE THREAD

**Issue by Phennim** [Sequel-Ace/Sequel-Ace#1025]
- Sequel Ace Version (including build number): Version 3.3.0 Build 3026
- Sequel Ace Source GitHub
- macOS Version: Catalina 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: -
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
The Preferences window is disabled when the active tab is unconnected.

**Steps To Reproduce**
1. Open a new connection window or a new tab
2. Try to open Preferences either through the menu or keyboard shortcut

**Expected Behaviour**
The Preferences window should open.

**Comment by Kaspik** [comment]
Fixed in https://github.com/Sequel-Ace/Sequel-Ace/commit/bc90f72dad6b2097904fd719bd836010ee0100be
