### ISSUE TITLE
Shortcuts to navigate between tabs doesn't work

### ISSUE THREAD

**Issue by RodolfoGS** [Sequel-Ace/Sequel-Ace#1031]
- Sequel Ace Version (including build number): 3.3.0 (3026)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): Apple
- MySQL Version: x
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** I don't know

**Description**
The latest version doesn't support shortcuts to navigate between tabs.
Ex:

![image](https://user-images.githubusercontent.com/870365/114096162-f72d2200-9883-11eb-8d52-888062d431f9.png)

**Steps To Reproduce**
1. Hit shortcuts to change navigate to the next or previous tab (`option + tab` or `option + shift + tab`)
2. Doesn't work

**Expected Behaviour**
-

**Related Issues**
-

**Additional Context**
-

**Comment by Kaspik** [comment]
The shortcuts are now the same as on system - `CMD`+`OPTION`+`ARROW` (left or right). Not sure why they are not visible, will check.

**Comment by Kaspik** [comment]
Got it, collision with our custom options in menu. Fixed.

**Comment by samuelbradshaw** [comment]
Along similar lines, I noticed that the shortcut to switch between windows wasn't working (Command + ` and Command + Shift + `) – is it related, or should I open a separate issue?

**Comment by Kaspik** [comment]
Fixed in the same PR.
