### ISSUE TITLE
Menu items not clickable if not connected to DB

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#1035]
3.3.0

After opening the app, the About/Updates/Preferences etc menu links are disabled.

I have to connect to a DB to activate.

<img width="255" alt="Screenshot 2021-04-09 at 08 42 32" src="https://user-images.githubusercontent.com/25279400/114139691-a531de00-990f-11eb-9ebe-e1e52d1daa21.png">

**Comment by Jason-Morcos** [comment]
Should be fixed in the latest 3.3.1 beta.

Please use the issue format when submitting bugs, including version info and all those questions (which includes checking the latest beta) :)

**Comment by cappadaan** [comment]
If you would provide the option to use my favorites out of the box for the Beta version, I would.
but now it simply costs way too much time to check something in the beta version.

Also this problem was not marked as fixed in the release notes of the beta version.

**Comment by mfehr94** [comment]
@cappadaan you can use the export and import methods. That are 2 clicks.

**Comment by cappadaan** [comment]
Its not (as far as I know), passwords are not imported, and are not easy accessible for me.

**Comment by mfehr94** [comment]
yea true but security is always first.
