### ISSUE TITLE
Password fields get cleared if Host or Username field changes.

### ISSUE THREAD

**Issue by CodeBrauer** [Sequel-Ace/Sequel-Ace#1037]
- Sequel Ace Version (including build number): 3.1.1 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: -
- macOS Localization: -

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes tested in 3.3.1 Build 3028 (Github), but I think this was also an issue in Sequel Pro.

**Description**
The Password field get cleared if Host or Username field changes. 

**Steps To Reproduce**
1. Go to QUICK CONNECT _or_ create a new favorite
2. Write/Paste a password first
3. Write/Paste a host or username afterwards
4. The password field gets cleared

**Expected Behaviour**

The password should stay in this input field and should not reset if I change host or username.

**Related Issues**

-

**Additional Context**
![screencast](https://user-images.githubusercontent.com/2059754/114153489-a4a14380-991f-11eb-89b2-7e24ed789197.gif)

**Comment by Kaspik** [comment]
IIRC, this is not an issue, but security thing and works as expected - that's why it's in latest version, previous versions as well as was in Sequel Pro. :)

**Comment by CodeBrauer** [comment]
When I read your comment, I just realized why this is a security feature. While a somewhat annoying one, it is still understandable. Not seen/noticed so far with FTP clients or similar programs.

**Comment by Kaspik** [comment]
Yeah, usually people have favorites saved, so this is not a problem, OR when connecting via quick connect you just go and fill the details from top to bottom - so this doesn't happen either. :)

Not sure about the username, but I do feel strong about the host - someone could change host to their own, and read your credentials on their end when trying to log in...

**Comment by frees11** [comment]
Is it possible to add checkbox in settings where we can turn off this security feature? It's super annoying when it occurs.

**Comment by Kaspik** [comment]
It's not really possible if we don't want to start handling password by ourself.

Password is stored in the keychain as a combo of the provided details - changing the details means loosing the ability to load the password (the password is not in the password field in Sequel Ace, it's just a placeholder, we get the password during the connection).
