### ISSUE TITLE
SP_SELECTED_TABLES seems to not be populated when running bundle

### ISSUE THREAD

**Issue by dave470003** [Sequel-Ace/Sequel-Ace#1038]
- Sequel Ace Version (including build number): 3.3.0, Build 3026
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): Intel core i5
- MySQL Version: 8.0.23
- macOS Localization: English UK

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Issue seems to be present in 3.3.1

**Description**
I am using a third party bundle, https://github.com/cviebrock/sequel-pro-laravel-export .  Recently this has stopped working with the error message "No table selected.". After some digging I found that this happens when the Bundle shell variable (https://sequelpro.com/docs/bundles/bundle-editor) SP_SELECTED_TABLES is empty. Echoing out this shell variable seems to result in an empty string.

Nothing has changed on my end but I assume that Sequel Ace updated itself automatically and it seems to be broken. This works fine in version number 3.2.3

**Steps To Reproduce**
1. Install https://github.com/cviebrock/sequel-pro-laravel-export, or create a bundle which does `echo $SP_SELECTED TABLES`
2. Try to run the bundle (which is to click on a table, click on Bundles>Export>Export To Laravel Migration)

**Expected Behaviour**
I expect the bundle to run as expected, I expect $SP_SELECTED_TABLES to be populated.

**Comment by Kaspik** [comment]
This is great catch! Fixed in https://github.com/Sequel-Ace/Sequel-Ace/pulls (I hope).

Let's keep an eye on merging this and releasing another beta, or next version release. :)
