### ISSUE TITLE
Windows menu shows entry for every tab, instead of for every window

### ISSUE THREAD

**Issue by djkgamc** [Sequel-Ace/Sequel-Ace#1040]
The OS windows menu shows a new entry for every tab. Is that intentional?  It breaks some of organization behavior to combine the two.  For example, 3 windows can equal 3 environments, with say 3 tabs in each window within each environment.    Now one can't use the windows menu to switch between environments anymore, but you have to wade through 9 tabs with no grouping.

This is a moot point of shortcut keys to cycle windows worked in Sequel Ace (and cycled by window instead of tab), but for some reason they don't.

**Comment by Kaspik** [comment]
Please search through issues before opening a new one, check releases here on Github and install latest 3.3.1. Cycling between window now works as expected! :)

Re: Windows in Window menu - I have no idea what it _should_ do. Safari does something else, Finder and other system apps do what Sequel Ace does now.... really confusing.

**Comment by djkgamc** [comment]
Wow, good point about Safari vs. Finder, had no idea.  The cycling update solves the problem :)
