### ISSUE TITLE
Generated columns are included during export, causing issues when importing.

### ISSUE THREAD

**Issue by natbentley** [Sequel-Ace/Sequel-Ace#1041]
- Sequel Ace Version (including build number): 3.3.0 (Build 3026)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.0.1 (20B29)
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 8.0.19
- macOS Localization: English (British)

**Description**
When a table containing a generated column (https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html) is exported, the INSERTs include the data from the generated column, causing problems upon import.  This effectively makes any exports containing generated unusable without lots of manual work

**Steps To Reproduce**
1. Select a database and table with a generated column
2. Export the table
3. Import the table (or open the sql file) and observe issues importing.

**Expected Behaviour**
mysqldump excludes generated columns from the export INSERTS (so they are created in the CREATE TABLE segment of the export).  Ideally this behaviour could be mimicked, or an option to exclude generated columns could be added.

**Additional Context**

Example export with a generated column:

```
DROP TABLE IF EXISTS `customers`;

CREATE TABLE `customers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `full_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (concat(`first_name`,_utf8mb4' ',`last_name`)) VIRTUAL,
  `email` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `customers_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

LOCK TABLES `customers` WRITE;
/*!40000 ALTER TABLE `customers` DISABLE KEYS */;

INSERT INTO `customers` (`id`, `first_name`, `last_name`, `full_name`, `email`)
VALUES
	(1,'Nathan','Bentley','Nathan Bentley','test@example.org');

/*!40000 ALTER TABLE `customers` ENABLE KEYS */;
UNLOCK TABLES;

```

Issue upon import:

![image](https://user-images.githubusercontent.com/37216142/114189669-5d787a00-9942-11eb-8b88-c24e772e1313.png)

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos, I can try to have a look if you need help for this issue ?

That would be great! I'm pretty slammed right now
