### ISSUE TITLE
Window should open at last position

### ISSUE THREAD

**Issue by nofue** [Sequel-Ace/Sequel-Ace#1044]
The main window (with the favourites list on the left) re-appears always on the same position. This is getting cumbersome working with two monitors: Cmd+N for a new window, which appears on the lower left of the left monitor. Shifting the window over to the right monitor, and doing what has to be done, Cmd+W with the window on the right, Cmd+N openes the main window on the lower left-left again. Quite strange in this context: when the windows is on the lower-left-left, messages pop-up at the place where the  earlier window had been shifted to, middle - center - right monitor. I was sitting for about a minute, waiting for the message to appear. Staring onto the active window I didn't notice the message had already popped up at the far right ….

**Comment by Kaspik** [comment]
I _think_ this is related to the fact we don't support restoration (https://github.com/Sequel-Ace/Sequel-Ace/issues/729) yet - but we are on a good way!
