### ISSUE TITLE
Tab coloring

### ISSUE THREAD

**Issue by mharney** [Sequel-Ace/Sequel-Ace#1046]
I upgraded to 3.3.1 after I saw the release note that the tab coloring was improved. However, it is only similar to older behavior if you have multiple tabs open. If you have only one tab open, there is no coloring at all. At our company, we use coloring to distinguish between local and production databases, so having coloring even when there is only one tab open is important to us. 
I'm asking that you please restore this stripe!
![image](https://user-images.githubusercontent.com/8187198/114424531-11f5e400-9b6d-11eb-800a-db946677421c.png)
I am running Big Sur on a MacBook Pro with extended displays.

**Comment by Kaspik** [comment]
"View" - "Show tab bar" even for single tab. Then the coloring will be visible.

**Comment by michaelklopf** [comment]
I can't see that setting on Catalina, is it somehow only available for newer OSX versions?

**Comment by Kaspik** [comment]
https://developer.apple.com/documentation/appkit/nswindow/1644517-toggletabbar - should be macOS 10.13+

The dot was only 3.3.0, that changed for 3.3.1.

**Comment by michaelklopf** [comment]
Found it, working with German OS and the setting is system wide and translated, the location is

"Window" - "Show tab bar"

**Comment by PanMan** [comment]
While this works, it doesn't seem to be persistent, and before the whole title bar of the window had a color - which was more clear than a thin line. I also use colors to differ between PROD and DEV.
