### ISSUE TITLE
Double click to open same connection in new tab

### ISSUE THREAD

**Issue by Axel29** [Sequel-Ace/Sequel-Ace#1047]
It would be great to have the same feature as Sequel Pro (or maybe it was only on the nightly build? I can't remember how it was like on the official release) that when a double click is made on the tab bar, a new connection is opened to the same database with the same SQL query tab filled.

It's a really nice feature when working on multiple tables of the same database.

Thank you.

**Comment by Kaspik** [comment]
Unfortunately we now use native tabbing and I don§t think _any_ native app supports this. There is a shortcut "duplicate connection to new tab" tho. :)

**Comment by Axel29** [comment]
> Unfortunately we now use native tabbing and I don't think _any_ native app supports this. There is a shortcut "duplicate connection to new tab" tho. :)

Good to know, thanks for the answer :) 
I didn't find the shortcut in the list (https://sequel-ace.com/shortcuts.html), could you please help me with it?

Also I'm guessing coloring the whole tab as Sequel Pro used to do is not possible then? :)

**Comment by Kaspik** [comment]
Yeah, it was changed two weeks ago in 3.3.0, but is now improved in 3.3.1 :)

If you open Sequel Ace, connect, then in menu select "File", i believe there will be this with shortcut CMD+SHIFT+T :)

**Comment by Axel29** [comment]
Great thanks found it!
