### ISSUE TITLE
Shortcuts to filter tables not working

### ISSUE THREAD

**Issue by bobo52310** [Sequel-Ace/Sequel-Ace#1049]
- Sequel Ace Version (including build number): 3.3.1 Build 3028
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Big Sur 11.2.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: Traditional Chinese

**Description**
Pressing `⌃⌥⌘F` doesn't focus the cursor on the filter tables input field anymore.
In the toolbar, the Filter Tables button is also disabled.  (Table > Filter Tables)
![image](https://user-images.githubusercontent.com/1137675/114503700-4bf3e280-9c60-11eb-9980-0a6c7a8437c3.png)

**Steps To Reproduce**
1.Select a table
2.Open 'Content' tab
3.Hit `⌃⌥⌘F`
4.Nothing happens

**Expected Behaviour**
1.Select a table
2.Open 'Content' tab
3.Hit `⌃⌥⌘F`
4.The cursor focuses on the filter tables input field

**Comment by Kaspik** [comment]
Isn't CMD+F the same thing?

**Comment by bobo52310** [comment]
@Kaspik Yes, I mean "filtering the list of the tables".

**Comment by JonLaliberte** [comment]
I noticed in the latest release (Version 3.3.0, Build 3026), Filter Content doesn't have a shortcut assigned and Filter Tables seems to always be disabled:
<img width="315" alt="Screen Shot 2021-04-13 at 3 05 39 PM" src="https://user-images.githubusercontent.com/5403662/114606772-b6f5e700-9c69-11eb-91de-f201c366f253.png">

**Comment by Kaspik** [comment]
3.3.1 is the latest one.

**Comment by JonLaliberte** [comment]
Thanks! 3.3.1 fixes the Filter Content issue.
The Filter Tables menu item is still disabled at all times (as far as I can tell)

**Comment by Kaspik** [comment]
Yeah filter tables does not work properly, will fix. :)

**Comment by prabowomurti** [comment]
I have this issue in version 3.4.0 Mac OSX (I installed it from App Store). Should I open a new issue ?
<img width="286" alt="Screen Shot 2021-08-25 at 10 59 29" src="https://user-images.githubusercontent.com/38052/130724321-be9dc9ec-a286-487f-a2ec-ffddfb1858f7.png">

Thank you.
