### ISSUE TITLE
Add the ability to change tab title

### ISSUE THREAD

**Issue by nadrooJ** [Sequel-Ace/Sequel-Ace#1050]
The current format seems to be `<server-version> <favourite-name>`  

Certain servers (\*cough\* mariadb \*cough\*) have insanely long versions which makes it impossible to see which database each tab is connected to via the tab bar (see screenshot). The only way to see which tab is which is by opening said tab and expanding the title at the top.

![image](https://user-images.githubusercontent.com/13659818/114703817-b7e85080-9d1d-11eb-9b9d-a52e3492b47c.png)

A couple of ways to achieve this off the top of my head:

1. Allow custom tab titles (set default per-favourite?)
1. Have a variety of options specify which format we'd like to use, eg:
   - Default
   - Reverse `<favourite-name> <server-version>`
   - Only favourite name
   - Only server name (for sake of completeness I suppose)

Thanks!

**Comment by Kaspik** [comment]
This has been changed in 3.3.1 and fixed to previous title.

**Comment by nadrooJ** [comment]
My apologies, thanks!

**Comment by nadrooJ** [comment]
Sorry to pester...

Having updated to 3.3.1 now it looks like the tab name is simply `database/table` (sans favourite name, which was present within Sequel Pro, albeit only on inactive tabs).  

We currently have 3 production shards, for each I have a favourite named after the shard. The problem still stands whereby we can't see which tab corresponds to which server/ shard.

![image](https://user-images.githubusercontent.com/13659818/114706063-69888100-9d20-11eb-8a68-dcb5589bb5e0.png)


(PS: Big fan of the reworked colouring)

**Comment by Kaspik** [comment]
Hmm, could you drop here a screenshot how it looks in Sequel Pro or how it looked before 3.3.0 please? Thanks!

**Comment by nadrooJ** [comment]
Of course! (blanked out most of the names)

![image](https://user-images.githubusercontent.com/13659818/114708963-ed903800-9d23-11eb-9844-21a879edb6bd.png)
