### ISSUE TITLE
Choosing ‘Export’ selects the last table in the list

### ISSUE THREAD

**Issue by ricklecoat** [Sequel-Ace/Sequel-Ace#1051]
- Sequel Ace Version (including build number): 3.3.1 (Build 3028
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.26
- macOS Localization: UK British

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** There doesn't appear to be a version later than this, even in beta.

**Description**
When I go to export a database (in order to import it on a remote server) I use either Cmd-Shift-E or File > Export. In either case the export panel opens as expected — but behind it, in addition, the last table in the table list is also selected. This means, I think, that the export will only be exporting that table, not the entire DB. While the export panel is open I cannot interact with the table list to deselect the erroneously-selected table. As a result, I am unable to export a database. This is a big deal, as it utterly kills my workflow.

**Steps To Reproduce**
1. Open a database connection
2. Select Export, either from the menu bar or via keyboard shortcut

**Expected Behaviour**
I expect the export panel to open **without** selecting any individual tables, so that the entire DB can be exported.

**Related Issues**
None found
 

**Additional Context**
I've attached 4 screenshots; the first shows the Db freshly opened. In that screenshot I've scrolled down to the bottom of the table list, but have **not** selected any tables. The second screenshot shows the window after I activate Export. You can see that the last table in the list has been selected in the background, behind the export panel. The selected table is also noted in the app's title bar. The third shot shows the window just after I cancel the export. The table is clearly selected. And the fourth show the window after I manually deselect the table in the sidebar by cmd-clicking on it. The table is still named in the app's title bar.

![1-DB_freshly_opened](https://user-images.githubusercontent.com/13526883/114704554-a3f11e80-9d1e-11eb-91e8-d4daf6a0bf76.png)
![2-Export_activated](https://user-images.githubusercontent.com/13526883/114704565-a784a580-9d1e-11eb-9925-f360c0a1074c.png)
![3-export_cancelled](https://user-images.githubusercontent.com/13526883/114704581-ac495980-9d1e-11eb-95b3-711760ae0ad5.png)
![4-Table_manually_deseletcted](https://user-images.githubusercontent.com/13526883/114704585-ae131d00-9d1e-11eb-82bf-fb02bd669e98.png)

**Comment by ricklecoat** [comment]
Ugh, cancel this. I think it's pilot error. Looks like somehow the setting got changed to CSV export rather than SQL and I just didn't notice. Sorry.

**Comment by Kaspik** [comment]
Do you remember if there was always SQL as a default option previously?

**Comment by ricklecoat** [comment]
As far as I know SQL was always the default export option. However, that said, I don’t think that I ever chose any of the other options — so it probably just defaulted to whatever option was chosen the previous time.

I don’t know if there are keyboard shortcuts to switch between the export options, but if there are then what most likely happened is I accidentally touched a key and switched it without realising.

--
Rick Lecoat
