### ISSUE TITLE
Feature Request: Ability to Edit columns in multiple rows at once

### ISSUE THREAD

**Issue by exiva** [Sequel-Ace/Sequel-Ace#1052]
There should be the ability to select multiple rows in a table, and update the values in a column of the selected rows at once

**Comment by Jason-Morcos** [comment]
I understand this would be a nice feature, but what's the use case? What's wrong with editing one row at a time?

**Comment by exiva** [comment]
@Jason-Morcos I have times where I need to update 50+ rows with the same value in a specific column. Setting it one at a time is obviously time consuming.

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos I have times where I need to update 50+ rows with the same value in a specific column. Setting it one at a time is obviously time consuming.

Hmmmm definitely makes sense, but also sounds like a specialized use case which I learn towards suggesting a simple SQL insert query.

**Comment by Behinder** [comment]
That feature would be nice.

**Comment by bitzip** [comment]
+1
