### ISSUE TITLE
Possible cause of failing SSH connections?

### ISSUE THREAD

**Issue by nofue** [Sequel-Ace/Sequel-Ace#1053]
- Sequel Ace Version (including build number): 3.3.1. 3028
- Sequel Ace Source App Store/
- macOS Version: 11.2.3
- Processor Type (Intel)
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- macOS Localization: en

**Description**
Connecting to Host in LAN fails, connecting to remote host through WAN works perfectly fine. As I reported this already, I won't repeat myself. Here are my today's findings regarding the issue:

The connection string as shown by the error message from Sequel Ace reads:

/usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/nofue/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 22 nf@192.168.1.231 -L 55066:localhost:3306
OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019

However, there’s a blank in between ‚Sequel' and ‚Ace‘ at the -F parameter. Quoting the string like this:

/usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/nofue/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F '/Applications/Sequel Ace.app/Contents/Resources/ssh_config' -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 22 nf@192.168.1.231 -L 55066:localhost:3306
OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019

works perfectly fine. I have no idea if this will solve the issue within Sequel Ace, but from the CLI I’d say this should be looked into.

**Comment by Jason-Morcos** [comment]
I don't believe this is the cause of the issue. This would mean that no ssh connections would work for anyone. Issues with quoting the name of the application itself would be global.

Tested with the latest Ace and macOS and SSH connections are indeed working, meaning the issue isn't something to do with -F arg not being quoted.
