### ISSUE TITLE
deleting all rows when selecting the only row

### ISSUE THREAD

**Issue by birsoz** [Sequel-Ace/Sequel-Ace#1054]
There is an active table. If there is only one row in that table if i select and delete that row, the command executed is delete all i think. So after i opened the table if there are new rows sent and saved that i dont see because of not refreshing, all the new data will be gone with the one i have selected. Instead of deelete all command we can have delete the first row command ot sth.

**Comment by Jason-Morcos** [comment]
The latest beta includes this feature (the option to only delete the selected rows even when all rows in the table are selected) and it should be included in the next release! https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.3.3-3032
