### ISSUE TITLE
Can't Connect via TCP/IP

### ISSUE THREAD

**Issue by wayne0332** [Sequel-Ace/Sequel-Ace#1057]
- Sequel Ace Version (including build number):3.3.1
- Sequel Ace Source (App Store/GitHub/Homebrew):APP Store
- macOS Version:11.2 (20D64)
- Processor Type (Intel/Apple):Intel
- MySQL Version:5.7.14
- macOS Localization:zh-CN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
I am using the last version.

**Description**
hi,all,when i try to connect mysql,it is fail.And i can connect in Mysql Workbench/Sequel Pro/DBeaver.
And here is my screenshot:
![image](https://user-images.githubusercontent.com/5112427/115332373-43ecf300-a1ca-11eb-8f58-fddd815e309b.png)
Or how i can find the log?
Thanks very much.

**Steps To Reproduce**
1.enter the mysql info
2.click connect

**Additional Context**
And i had try to import the db info from the Sequel Pro,it is also fail.

**Comment by Jason-Morcos** [comment]
Can you show a screenshot of your connection configuration?

Are you relying on any magic from your ssh config or otherwise? Sequel Ace is sandboxed unlike other DB tools, meaning it can't magically use your ssh config or known hosts or keys. The FAQ on our website https://sequel-ace.com may be helpful

**Comment by wayne0332** [comment]
I think i am using the stander connect way,and here is my conf.
![image](https://user-images.githubusercontent.com/5112427/115544963-d62ded80-a2d5-11eb-927d-e02281b2419b.png)
Also with the Sequel Pro conf:
![image](https://user-images.githubusercontent.com/5112427/115545069-f5c51600-a2d5-11eb-8925-ee045db12d73.png)

**Comment by Jason-Morcos** [comment]
> I think i am using the stander connect way connect to the mysql proxy,and here is my configuration.
> 
> ![image](https://user-images.githubusercontent.com/5112427/115544963-d62ded80-a2d5-11eb-927d-e02281b2419b.png)
> 
> Also with the Sequel Pro configuration:
> 
> ![image](https://user-images.githubusercontent.com/5112427/115545069-f5c51600-a2d5-11eb-8925-ee045db12d73.png)
> 
> 

It looks like the password field is blank in sequel Ace? If you go to the quick connect view and fill in all the info, does it work then?

**Comment by wayne0332** [comment]
> > I think i am using the stander connect way connect to the mysql proxy,and here is my configuration.
> > ![image](https://user-images.githubusercontent.com/5112427/115544963-d62ded80-a2d5-11eb-927d-e02281b2419b.png)
> > Also with the Sequel Pro configuration:
> > ![image](https://user-images.githubusercontent.com/5112427/115545069-f5c51600-a2d5-11eb-8925-ee045db12d73.png)
> 
> It looks like the password field is blank in sequel Ace? If you go to the quick connect view and fill in all the info, does it work then?

I had try yet,but the error is same.I find that fully manual enter the info(include password) or import from sequel pro is same.

**Comment by Jason-Morcos** [comment]
Very weird. When importing from Sequel Pro, passwords aren't migrated over. I'm still inclined to believe it's something funky about your password. TCP/IP is definitely working for me right now.
