### ISSUE TITLE
Keyboard shortcut to duplicate database

### ISSUE THREAD

**Issue by MiguelMike** [Sequel-Ace/Sequel-Ace#1058]
I often need to drop a database, select another one and duplicate it.

Most of this can be done using keyboard only, except for the database duplication, for which no keyboard shortcut is defined.

Apparently `⌘D` is still unused.

**Comment by Jason-Morcos** [comment]
PR is definitely welcome on this one, but we'll need to be sure to not "conflict" with shortcuts users may be familiar with from other apps/tools.

As a workaround, you can use Better Touch Tool or similar to set up custom key shortcuts for menu items in any app. BTT is pretty solid software

**Comment by MiguelMike** [comment]
Using extra software as workaround seemed an overkill to me. Turns out `Ctrl+F2` places focus on the menu. Takes several key presses to duplicate a database, but it's still possible without using the mouse or trackpad.

Not ideal, but that'll do for now. I still hope that some day the shortcut will be added.
