### ISSUE TITLE
Password with some symbols doesn't work

### ISSUE THREAD

**Issue by jbvsmo** [Sequel-Ace/Sequel-Ace#1059]
- Sequel Ace Version (including build number): 3.3.1 Build 3028
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.14 Mojave
- Processor Type (Intel/Apple): Intel
- MySQL Version: Aurora compatible with Mysql 5.7
- macOS Localization: en-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, using latest 

**Description**
I tried to narrow down this problem and seems it is struggling with special chars in the password because passing exactly same parameters, I can connect to the MySQL DB using the CLI as such:

     mysql -u dbuser --port 13306 -h 127.0.0.1 -p
     
I will paste a long password that has `!`  and `.` symbols in it.

The host is 127.0.0.1 but this is actually an ssh tunnel, and the error message from Sequel Ace shows the real IP I redacted.

When I try the same thing on Sequel Ace, I get:

```
Unable to connect to host 127.0.0.1 because access was denied.

Double-check your username and password and ensure that access from your current location is permitted.

MySQL said: Access denied for user 'dbuser'@'redacted-ip' (using password: YES)
Access denied for user 'dbuser'@'redacted-ip' (using password: YES)
```

**Steps To Reproduce**
1. Set a password with special chars.
2. Try to use it.

**Expected Behaviour**
Connection to DB works

**Related Issues**
None that I could find

**Additional Context**

![Screen Shot 2021-04-20 at 14 14 54](https://user-images.githubusercontent.com/1024423/115438046-4e67b680-a1e3-11eb-982f-6ab3d0a0a157.png)

**Comment by Kaspik** [comment]
Based on the screenshot - you are editing favorite, is that right?

If so, did you try the Quick Connect option instead?

**Comment by jbvsmo** [comment]
@Kaspik You got to be kidding me! That works!
What is the problem with editing a favorite?

**Comment by Kaspik** [comment]
I believe you need to hit "Save changes" for that otherwise it ses password from Keychain? 😄

**Comment by jbvsmo** [comment]
That must be it then. I will close this issue
