### ISSUE TITLE
Crash while editing value of table in DEBUG build

### ISSUE THREAD

**Issue by mtgto** [Sequel-Ace/Sequel-Ace#1061]
- Sequel Ace Version (including build number): https://github.com/Sequel-Ace/Sequel-Ace/blob/207a05a4871b178e993ef687342d0c33f57a9f4a
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: ja-jp

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** No

**Description**

In DEBUG build, app crashes when try to edit NULL value in content view.

**Steps To Reproduce**
1. Launch Sequel Ace Local Testing from Xcode
2. Connect database && open Content tool bar item
3. Double Click NULL value to edit

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/1213991/115717739-6bec7a00-a3b5-11eb-98af-63078675318a.png">

**Expected Behaviour**

Can edit NULL value

**Related Issues**

I can't find it.

**Additional Context**

Sequel Ace does not checks whether cellValue is NSNull before logging (SPLog).

https://github.com/Sequel-Ace/Sequel-Ace/blob/207a05a4871b178e993ef687342d0c33f57a9f4a/Source/Views/TableViews/SPCopyTable.m#L1295

NOTE: SPLog is disabled in release build.

**Comment by Jason-Morcos** [comment]
@mtgto Good catch! Would you feel comfortable writing a small null-guard fix to this issue and submitting a PR?

**Comment by mtgto** [comment]
@Jason-Morcos submitted first PR 😃
