### ISSUE TITLE
viewStatus button does not work from #969

### ISSUE THREAD

**Issue by mtgto** [Sequel-Ace/Sequel-Ace#1062]
- Sequel Ace Version (including build number): 3.3.1
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.14.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: ja-jp

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**

Since v3.3.0, viewStatus button does not work (see below image).

**Steps To Reproduce**
1. Show table Structure view
2. Click `viewStatus:` button

<img width="948" alt="image" src="https://user-images.githubusercontent.com/1213991/115722829-588fdd80-a3ba-11eb-982c-bd67fa82d965.png">

**Expected Behaviour**

Jump to table info view.

**Related Issues**

I can't find it.

**Additional Context**

#969 renames the method `viewStatus:` in DBDatabaseDocument to `viewStatus`, but DBView.xib has still IBAction `viewStatus:`.
https://github.com/Sequel-Ace/Sequel-Ace/pull/969/files#diff-f7c77a01ff6a4ae160e9a454898d9219c948bf1e602a254fe058489449d026aeL5690

**Comment by Kaspik** [comment]
🤦🏼‍♂️  Thanks, will fix on Sunday!

**Comment by Jason-Morcos** [comment]
This should be fixed in the latest beta and will be included in the next bug fix release (likely next week)!

https://github.com/Sequel-Ace/Sequel-Ace/releases
