### ISSUE TITLE
Take into account the GENERATED Column feature more deeply 

### ISSUE THREAD

**Issue by gduh** [Sequel-Ace/Sequel-Ace#1065]
The issue #1041 reports an export behavior which does not take into account the GENERATED column. This feature first appeared with MySQL 5.7.

I suggest going further, but it's not as simple as it sounds.

For example : 

```
CREATE TABLE `customers` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(191) NOT NULL,
  `last_name` varchar(191) DEFAULT NULL,
  `full_name` varchar(255) GENERATED ALWAYS AS (concat(`first_name`,' ',`last_name`)) VIRTUAL,
  `email` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `customers_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;
```

The tab Structure displays the following : 
![SequelACE_GENERATEDColumn](https://user-images.githubusercontent.com/15440947/116361517-5cc85a80-a801-11eb-807b-ac0e88c4ba82.png)

With the following command (Tab Query) : `SHOW COLUMNS FROM customers`

![SequelACE_GENERATEDColumn_2](https://user-images.githubusercontent.com/15440947/116361784-a2852300-a801-11eb-996e-fb3c674f96b4.png)

In the `SPTableData.m` class, the following `parseFieldDefinitionStringParts` method does not parse `GENERATED ALWAYS AS (concat(`first_name`,' ',`last_name`)) VIRTUAL` of the `CREATE TABLE`syntax, so, this string remains in the field `unparsed`.

Therefore to solve the issue #1041 I had to use the `unparsed` field to check if the column is of type GENERATED or not.

I think it might be nice if the `parseFieldDefinitionStringParts` method could parse this king of information. At least to check if the column is of type GENERATED. Parsing the part `(concat(first_name,' ',last_name))` is is bit more complexe. 

So :
- in the tab Structure it will be possible to display `VIRTUAL GENERATED` in the `extra` field.
- about the pull request #1060 it will be possible to check directly a new boolean field to check if column is GENERATED or not instead of check the `unparsed` field.
- And at the end, but more complicated, and maybe not the priority either, in the `Structure` tab the possibility to set this type of column by selecting `VIRTUAL GENERATED` in the `extra` field and filling in the parameters in another field (?) with or without input help (?).

**Comment by Kaspik** [comment]
Agree we should be showing this in the tab structure and we should start parsing it. Go for it!

**Comment by gduh** [comment]
@Kaspik 
Just to inform you, Ive not forgotten the change. I had personal problems to deal with.

**Comment by Kaspik** [comment]
No problem at all, no one is forcing you :)

**Comment by Jason-Morcos** [comment]
Related to #1090 as well now
