### ISSUE TITLE
»Display Binary Data as Hex« isn't respected in Run Query tab

### ISSUE THREAD

**Issue by Xjs** [Sequel-Ace/Sequel-Ace#1068]
- Sequel Ace Version (including build number): 3.3.1 (3028)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.3
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7
- macOS Localization: English

**Description**
I appreciate the »Display Binary Data as Hex« feature. However, in the query response display of the Run Query tab the preference doesn't apply, binary data is still displayed as string.

**Steps To Reproduce**
1. Create a table with a BINARY column and fill in some data in that column
2. Select View » Display Binary Data as Hex
3. Observe that in the Table Content tab, the binary data is displayed as hexadecimal number
4. Run a SELECT query in the Run Query tab that returns a row containing data in the aforementioned BINARY column
5. Observe that the binary data is still interpreted as string, not as hexadecimal number

**Expected Behaviour**
I would expect the preference to apply to the query results as well.

**Additional Context**

Binary data is displayed as Hex in Table Content tab:

![Screenshot 2021-04-28 at 11 42 04](https://user-images.githubusercontent.com/58270/116383028-c737c580-a816-11eb-9577-c9c317c47da3.png)

Binary data is displayed as binary in Run Query tab:

![Screenshot 2021-04-28 at 11 42 07](https://user-images.githubusercontent.com/58270/116383104-d74fa500-a816-11eb-854f-2d0bff5a0d13.png)

**Comment by jdelaune** [comment]
Was just about to report the same thing :) I wonder if its because the column type is known to be BINARY in the table content view.

**Comment by Xjs** [comment]
I don't want this to go stale, but upon having a quick look I couldn't manage to find the place where the query result data is displayed in the results view. Any pointers?

**Comment by Xjs** [comment]
I don't want this to go stale, but upon having a quick look I couldn't manage to find the place where the query result data is displayed in the results view. Any pointers?

**Comment by Jason-Morcos** [comment]
> I don't want this to go stale, but upon having a quick look I couldn't manage to find the place where the query result data is displayed in the results view. Any pointers?

What do you mean "I couldn't manage to find the place where the query result data is displayed in the results view."? The results view _is_ displaying the query result data. It's synonymous. Perhaps a screenshot would help indicate what you're asking?

**Comment by Xjs** [comment]
I meant I couldn't find the place in the source code where the query result data is displayed.

**Comment by Jason-Morcos** [comment]
> I meant I couldn't find the place in the source code where the query result data is displayed.

Ahh SPCustomQuery.m does much of the work of running custom queries
Line 815 might be meaningful `cqColumnDefinition = [resultStore fieldDefinitions];`, and notice the customQueryView init on line 834.
