### ISSUE TITLE
Table Info Create Syntax Modifying Font does not working?

### ISSUE THREAD

**Issue by yadgen** [Sequel-Ace/Sequel-Ace#1069]
- Sequel Ace Version (including build number): Version 3.3.1/Build 3028
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: macOS Big Sur 11.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: MySQL 5.6.48
- macOS Localization:  zh_CN

**Description**
Table Info Create Syntax Modifying Font does not working.

**Steps To Reproduce**
1. After modified font, it works.
![1](https://user-images.githubusercontent.com/1206012/116488190-53ec8d00-a8c4-11eb-907b-5b5f0dc9d36e.png)

2. But when I changed another table, the font change default.
![2](https://user-images.githubusercontent.com/1206012/116488205-5f3fb880-a8c4-11eb-835e-e3bfa9bffacd.png)

**Comment by Jason-Morcos** [comment]
Duplicates #976

**Comment by yadgen** [comment]
> Duplicates #976
> Please don't open duplicate issues for bugs which have already been reported and have open issues.

Ok, I'm sorry.
It is uncomfortable to use at present.
