### ISSUE TITLE
Program crashes when choosing one of my databases; others connect fine

### ISSUE THREAD

**Issue by felix822** [Sequel-Ace/Sequel-Ace#107]
- What version of Sequel-Ace are you using?  **2.0.2, Build 2033**
- What version of macOS are you running on?  **10.15.5 (19F101)**
- What device(s) are you using Sequel-Ace on?  **local dev, MariaDB (mySQL 5.5.5-10.0.31-MariaDB)**

I have several databases on my local dev, and when I choose this certain one, the program crashes and closes. It opens and works fine in Sequel Pro. Not sure what other info I need to provide; any input is greatly appreciated. Thanks.

**Comment by Jason-Morcos** [comment]
Will be fixed in 2.1.0! Please try the latest beta and let us know if the issue persists.

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by Jason-Morcos** [comment]
Duplicates #83

**Comment by felix822** [comment]
Thanks Jason! Definitely works in latest beta.
