### ISSUE TITLE
Not able to export on fresh boot/restart without revoking and reinstating folder access

### ISSUE THREAD

**Issue by HtSpJustinMcFawn** [Sequel-Ace/Sequel-Ace#1070]
- Sequel Ace Version: Version 3.3.1 Build 3028
- Sequel Ace Source: App Store
- macOS Version: macOS Big Sur Version 11.3
- Processor Type (Intel/Apple): 1.8 GHz Dual-Core Intel i5
- MySQL Version: 5.7.26

**Description**
When I first open Sequel Ace after I boot up my computer, I generally export my database scripts with table structure only. However, when I try to export, I get there error stating the export folder is not writable. When I check Preferences>Files, it shows I have access to the location I wish to export to. In this case, Desktop; However, the error occurs when I try using the Downloads or Documents folders as well. A workaround I have to do is revoke access, then reinstate access to these locations in order to do my exports. I have tried other things like making sure Sequel Ace has full disk access, and changing permissions of the folders I export to, but it seems the only thing that fixes this, is revoking and reinstating folder access.

![Screen Shot 2021-04-30 at 8 50 06 AM](https://user-images.githubusercontent.com/82532824/116695250-b44bff00-a996-11eb-8d2d-805123f1ca2b.png)

![Screen Shot 2021-04-30 at 8 50 47 AM](https://user-images.githubusercontent.com/82532824/116695221-ac8c5a80-a996-11eb-8863-1fb6bd94e03f.png)

-image is before revoking access, as you can see it looks like it should be able to write to those locations.

**Steps To Reproduce**
1. Launch Sequel Ace after a boot up / restart. 
2. Click File, and Export.
3. Select all tables *be sure structure is checked, and drop and content is unchecked.
4. Click Export. 
5. *error occurs*

**Expected Behaviour**
Export to location without error.

*EDIT*
I have tried removing Sequel Ace and reinstalling, then rebooted. Issue still occurs. Also, I have just discovered this isn't just on laptop restart or fresh boot up. I opened Sequel Ace on a fresh boot, and the error occurred. I did my workaround and got the export working again. I then quit out of Sequel Ace and reopened it, and the error came back. So this seems to be on launch of the program and has nothing to do with the computer shutting down or not.

**Comment by Jason-Morcos** [comment]
Very weird. @jamesstout do you have any ideas why this might be happening?

**Comment by chinanderm** [comment]
Been running into this issue for a few months now and it's pretty frustrating.

**Comment by Jason-Morcos** [comment]
I made an attempt at a fix in the latest beta, but haven't been able to reproduce the issue so sorta shooting in the dark until our colleague James gets back (he's the sandbox bookmarks expert). Can one/all of you please try this latest beta and let me know if it works now?

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.3.3-3032

**Comment by chinanderm** [comment]
@Jason-Morcos Just tried and it's nice to get prompted to re-authorize access on app start-up. Seems to work great!

Is there a way to persist that without prompting? If the disk path is in the "Accessible files" list it would be great if the app always had access to that and the authorization persisted between app quits and launches.

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos Just tried and it's nice to get prompted to re-authorize access on app start-up. Seems to work great!
> 
> 
> 
> Is there a way to persist that without prompting? If the disk path is in the "Accessible files" list it would be great if the app always had access to that and the authorization persisted between app quits and launches.

It should persist between launches! I wonder if it's asking just because it's your first time opening the beta. Does it ask you again if you quit and re-open the beta (and does it still work even if it doesn't prompt you on launch)?

**Comment by chinanderm** [comment]
> > @Jason-Morcos Just tried and it's nice to get prompted to re-authorize access on app start-up. Seems to work great!
> > Is there a way to persist that without prompting? If the disk path is in the "Accessible files" list it would be great if the app always had access to that and the authorization persisted between app quits and launches.
> 
> It should persist between launches! I wonder if it's asking just because it's your first time opening the beta. Does it ask you again if you quit and re-open the beta (and does it still work even if it doesn't prompt you on launch)?

Good point about first launch. I quit, launched again, I see the approved disk location in the Accessible Files list but exporting a DB to that location still yields the error message popup :(

**Comment by Jason-Morcos** [comment]
Okay I'm 99% sure I fixed the issue!
Unfortunately, you _will_ have to revoke and re-grant access to the desktop/other folders one last time, but after that it should work again. Basically manually granted folders were only getting readonly access 🤦 
Please try this latest beta and let me know!
https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.3.3-3033
