### ISSUE TITLE
Query Editor exremely laggy when a few dozen or more queries are present

### ISSUE THREAD

**Issue by MikeTodd** [Sequel-Ace/Sequel-Ace#1071]
- Sequel Ace Version: Version 3.3.1m Build 3028
- Sequel Ace Source: App Store
- macOS Version: 11.3 (20E232)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.12
- macOS Localization: English

**Description**
When I have only a few queries in the editor, key presses become sluggish. The more queries I have, the slower keypresses are registered until it becomes nearly unusable. Even with just this in the editor window, I am typing faster than the editor can keep up:

```
########### LIVE SERVER ############
show variables like '%version';

SELECT * FROM dtrpg_data d
WHERE d.`dtrpg_data_key` = 'login_30_not_logged_in'
   OR d.`dtrpg_data_key` = 'login_not_logged_in_but_was'
   OR d.`dtrpg_data_key` LIKE 'login_%_hits'
   OR d.`dtrpg_data_key` LIKE 'login_%_misses'
   ;
   
DELETE FROM dtrpg_data
WHERE `dtrpg_data_key` = 'login_30_not_logged_in'
   OR `dtrpg_data_key` = 'login_not_logged_in_but_was'
   OR `dtrpg_data_key` LIKE 'login_%_hits'
   OR `dtrpg_data_key` LIKE 'login_%_misses'
   ;

UPDATE products_attributes_pod
SET
  lsi_setup_status = 8
  , lsi_setup_message = '.'
WHERE products_attributes_id IN (1394623);
```

This appears to be caused by slow processing for syntax highlighting.

**Steps To Reproduce**
1. Insert above text.
2. Just type in a bunch of random characters on they keyboard.
3. Note that the editor does not keep up with your typing.
4. Turn off syntax highlighting and repeat.
5. Note that there is no lag now.

**Expected Behaviour**
Keypresses should register immediately.

Here is a video showing this in action: https://youtu.be/UxvHNs_VDHo I pressed all of those keys in under 1 second, and note that it took several seconds for the characters to appear. The more queries you have in the editor, the worse this gets until each individual keypress takes 10 seconds or more to register.

**Comment by mfehr94** [comment]
Sound like this is related to the processing of the syntax highlighting.

**Comment by MikeTodd** [comment]
@mfehr94 confirmed, when I turn off syntax highlighting, the problem goes away. So it seems that there's some optimization needed for syntax highlighting.

**Comment by dtklein7** [comment]
This has affected me since mojave on Sequel Pro! I'd bet there's an existing issue for this

**Comment by xhs345** [comment]
Experiencing the same. Turning off syntax highlighting helped a bit, but didn't fully fix it.

**Comment by MikeTodd** [comment]
> This has affected me since mojave on Sequel Pro! I'd bet there's an existing issue for this

I looked as extensively as I could in the issues listed here, but couldn't find another report of it. So I thought I'd create one.

**Comment by Jason-Morcos** [comment]
We've taken several stabs at trying to optimize syntax highlighting. I think, unfortunately, many queries and syntax highlighting being efficient are pseudo-antithetical to one another. If someone has some ideas and wants to take a stab at optimizing further that would be awesome, but I'm not quite sure what else to try other than a total rewrite from scratch of the query editor.

**Comment by timo002** [comment]
Same issue here, almost impossible to work with. Switched of syntax highlighting, see if it helps a bit. I appriciate the work you guys are doing! 👍

**Comment by Lenitr** [comment]
Still have the same issue, tried toggling several options (Highlight current query, bracket highlighting etc.) but can confirm that unfortunately only turning off "Syntax highlighting" has any noticeable effect (after restarting the application after toggling off the option).

**Comment by rickkln** [comment]
Both me and a colleague experienced issues with syntax highlighting after upgrading to M1 macs (though based on this thread assuming it is probably related OS updates and not the hardware that made the difference). It is extremely slow even with a single query of 50 lines or so.

**Comment by Lenitr** [comment]
Can confirm this is not M1 related, I'm running an Intel in my macbook

**Comment by Lenitr** [comment]
@MikeTodd Since I've been following a couple of different issues around this, someone has found a seeming workaround for this issue you might be able to test as well: https://github.com/Sequel-Ace/Sequel-Ace/issues/638#issuecomment-920491274 Their suggestion (changing the font to `menlo`) seems to work for me so far, might be good if more people can test it to see if it solves multiple use cases?

**Comment by rickkln** [comment]
Fixed it for me, thanks @Lenitr! Monaco + Syntax Highlighting ON causes the issue for me.

**Comment by bsiver** [comment]
I bumped into this issue as well after updating my OS to Big Sur (Intel CPU).  Switching the font to `menlo` as @Lenitr recommended also helped me.  Thanks!

**Comment by MikeTodd** [comment]
@Lenitr thank you! Changing to Menlo did indeed seem to fix most of the lagginess. There's still just a bit, but it is easily bearable now.

**Comment by Jason-Morcos** [comment]
Very interesting observations here. I'm glad to hear people have found that changing the font makes such a big difference! 
@Sequel-Ace/all maybe we should consider changing the default font for the query editor? I'd be more than happy to review a PR that does so

**Comment by rickkln** [comment]
Just a note in case it helps, a colleague of mine also had this issue and for him it went away on its own, he still has Monaco + Syntax Highlighting on without any issues. Very strange one 😅

**Comment by isopropylcyanide** [comment]
Just bumped into this thread. The workaround works but it beats me how a font setting can bring the query editor to a screeching halt. Appreciate all the work you've done. And I agree with @Jason-Morcos on updating the default font setting.

**Comment by mjaggard** [comment]
@dland Changing the touchbar settings made no difference for me but switching to a different fixed-width font solved the problem completely.
