### ISSUE TITLE
Application slow

### ISSUE THREAD

**Issue by Norgul** [Sequel-Ace/Sequel-Ace#1078]
- Sequel Ace Version (including build number): 3.3.1.3028
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Big Sur 11.2.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: /
- macOS Localization: /

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
It is hard to quantify the slow experience, but I know how it behaved before I installed the App store version. I love the app and it has been really enjoyable, however the last major update seems to work pretty slow. 

The system overall works fine, and no other app lags like that. When I open it and maximize the window, it's not natural, takes that extra time. Connecting to a local docker environment as well. It wasn't like that before.

**Steps To Reproduce**
1. Open the app
2. Do anything

**Expected Behaviour**

Not being slow

**Related Issues**

**Additional Context**

**Comment by Kaspik** [comment]
That is... really hard to debug. 😄

**Comment by Norgul** [comment]
Yeah, unfortunately I'm aware of it :/

**Comment by LeeMendelowitz** [comment]
For me, the app has become impossibly slow whenever I am trying to edit a long query in the query editor. Whenever I try to type into the query editor, my CPU fan starts to spin and the app freezes up. This behavior is relatively new and wasn't always the case.

I am also using Version 3.3.1 Build 3028.

**Comment by Jason-Morcos** [comment]
Closing in favor of #1071 and other, more specific and actionable issues
