### ISSUE TITLE
An error occurred when reading the file, as it could not be read in the encoding you selected (Autodetect - Unicode (UTF-8)).

### ISSUE THREAD

**Issue by simplenotezy** [Sequel-Ace/Sequel-Ace#1080]
- Sequel Ace Version (including build number): 3.3.1
- Sequel Ace Source (App Store/GitHub/Homebrew): 3028 (appstore)
- macOS Version: 11.2 (20D64)
- Processor Type (Intel/Apple): ARM
- MySQL Version: mysql  Ver 15.1 Distrib 10.5.9-MariaDB, for osx10.16 (x86_64) using readline 5.1
- MySQL Version on server: mysql  Ver 15.1 Distrib 10.4.18-MariaDB, for Linux (x86_64) using readline 5.1
- macOS Localization: English

**Description**
I've had troubles, for quite a long while now, with exports from production server, when importing into my local environment using Sequel Ace. I am not sure this is an issue specifically related to Sequel Ace, but I think it is.

When finished I get error:

    An error occurred when reading the file, as it could not be read in the encoding you selected (Autodetect - Unicode (UTF-8)).

This prevents me from importing all tables.

**Steps To Reproduce**
1. Export production database, using `mysqldump`: `mysqldump -u user -p --default-character-set=utf8 database > proddatabase.sql`
2. Import this using Sequel Ace with File -> Import

**Expected Behaviour**
The database should be imported without issues.

**Additional Context**
When running: `
SELECT default_character_set_name FROM information_schema.SCHEMATA 
WHERE schema_name = "database"` I get these results:

Locally: utf8mb4
Production: utf8

![image](https://user-images.githubusercontent.com/3786627/117135298-09c54900-ada7-11eb-99fd-d0557435fe2d.png)

**Comment by simplenotezy** [comment]
I've successfully imported it manually using `mysql` on the terminal.

    mysql
    > use DATABASE;
    > set names 'utf8'
    > source mydumpfile.sql
    
It executed without any issues

**Comment by Jason-Morcos** [comment]
Are you certain that the production export is _actually_ utf8 and not utf8mb4? My hunch is something about that export is funny and includes some sort of utf8 mb character (as the db is multi-byte) which is breaking import.

If you do an export from your local database itself, are you able to import that export back into the same db? In other words, is the issue only when you're exporting from a utf8mb4 db and importing into a utf8 db, or is it affecting you for utf8-only import/export too?

**Comment by jack-fdrv** [comment]
I have had the same issue.

**Comment by qstainless** [comment]
A little late to this party, but I also recently had this issue. To fix it, I set the encoding to 'Western: Mac OS Roman' as suggested [here](https://www.bramvandenbulcke.be/en/kb/sequel-pro-file-read-error-when-uploading-database).

**Comment by markpanado** [comment]
> A little late to this party, but I also recently had this issue, but without setting the default character set when exporting the production database.
> 
> `mysqldump proddatabase | bzip2 > proddatabase.sql.bz2`
> 
> To fix it, I set the encoding to 'Western: Mac OS Roman' as suggested [here](https://www.bramvandenbulcke.be/en/kb/sequel-pro-file-read-error-when-uploading-database).

This solution works! Thanks

**Comment by limsocheat** [comment]
> set the encoding to 'Western: Mac OS Roman'

set the encoding to 'Western: Mac OS Roman' fixed the issue.
