### ISSUE TITLE
同时打开多个tab时，窗口所对应的数据库存在切换bug

### ISSUE THREAD

**Issue by baoyou** [Sequel-Ace/Sequel-Ace#1082]
- Sequel Ace Version (including build number):
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version:
- Processor Type (Intel/Apple):
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by baoyou** [comment]
Sequel Ace Version (including build number): Version 3.3.1 Build 3028
Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
macOS Version: Big Sur 11.3
MySQL Version: 5.6

**Comment by Jason-Morcos** [comment]
Please fully fill out the issue description template if you would like us to dig into an issue.

Additionally, unfortunately we can only accept issue submissions in English.

Please re-submit your issue following the two above criteria.
