### ISSUE TITLE
macOS Big Sur truncates window titles, and Sequel Ace puts useless server information before the connection name

### ISSUE THREAD

**Issue by gotnate** [Sequel-Ace/Sequel-Ace#1083]
When I specify a custom connection name in Sequel Ace:
![image](https://user-images.githubusercontent.com/69241/117327741-ca026e00-ae47-11eb-954b-f3b8f0d861ff.png)

The resulting window only shows me the remote server information. This is pretty useless when all my remote servers use the same server version. I can't simply at a glance see which tab I'm looking at:
![image](https://user-images.githubusercontent.com/69241/117327978-0635ce80-ae48-11eb-9a4e-3db32abe3748.png)

If I interact with this truncated string the truncation "scratches off" and i can see the connection name specified. This is an annoying extra step that would not be needed if I could just at a glance see which window I'm on.
![image](https://user-images.githubusercontent.com/69241/117328264-4eed8780-ae48-11eb-9fc9-79a930f63816.png)

**Comment by Kaspik** [comment]
That's expected if there is not enough space. The name without connection/DB details is visible on the tab title - you just need to enable it via "View" -> "Show tab bar"

**Comment by gotnate** [comment]
I'm seeing no server name in the tab bar. only the database name - WHEN SELECTED.

**Comment by Kaspik** [comment]
That's correct, it's redundant to show both on both places. Window shows full title, tab bar connection title without DB details.

Not sure what is your complaint - if there is no space, you will see truncated window title. If you need full title, you can tap on it. If you want connection name, you have the tab title for that.

**Comment by gotnate** [comment]
I'm asking for a reformat of the window title so that the most important information comes first. Truncate the server version. Don't truncate the user specified connection name.

When I open the tab bar, I only see the name of the database that I picked in the Select Database picker. I do not see the connection name here. If I pick no database name, then the tab is blank. The only workaround I have is to get out my mouse and point at the truncated text.

**Comment by gotnate** [comment]
3.3.1 Build 3028 from the Mac App Store. I didn't see a bug report form, so I came here.

**Comment by Kaspik** [comment]
All right, you found a bug - the connection name was missing in the title - fixed in https://github.com/Sequel-Ace/Sequel-Ace/commit/167ef7e7707d3a816018ccaf2eeac2ba2884095f

But otherwise it works as expected:
- window title has MySQL database version + connection name + table
- tab title has connection name (didn't have in 3.3.1) + table
