### ISSUE TITLE
Cant import session

### ISSUE THREAD

**Issue by wildshaman** [Sequel-Ace/Sequel-Ace#1085]
**Sequel Ace Version (including build number):**
Sequel Ace 3.3.1 build 3028**

**Sequel Ace Source (App Store/GitHub/Homebrew):**
GitHub release .zip for mac

**macOS Version:**
MacOs Big Sur 11.4 beta

**Processor Type (Intel/Apple):**
Intel

**MySQL Version:**
MariaDB 10.5.*

**macOS Localization:**
Ru

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
yes

**Description**
I have saved session file (connections, queries in code editor and anything else) from SequelAce 3.2.3. I can easily use this file in this old version with just these steps:
Open an app - File - Open Recent - my.spfs

But i cant do it in 3.3.1 - app just crashes with errors after the same .spfs selection.

log file attached.
[sequel_log_file.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/6442584/sequel_log_file.txt)

**Comment by SBerkovic** [comment]
may be same as #1019 
The last version that lets me import my spfs file is also 3.2.3
