### ISSUE TITLE
slow to connect via proxysql

### ISSUE THREAD

**Issue by bugi** [Sequel-Ace/Sequel-Ace#1086]
- Sequel Ace Version (including build number): Version 3.3.1 Build 3028
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: proxysql 2.1.1, mariadb 10.4.12
- macOS Localization: US English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

There is no beta beyond the release I'm using.

**Description**

Sequel Ace doesn't connect to the schema before looking at variables.

Proxysql doesn't support no-schema.  It can't, because the variables could be different on the different DBs it talks to on the backend.

**Steps To Reproduce**

1. Connect to a schema through proxysql 2.1.1.
2. Look at the console in Sequel Ace.  See the time after "SHOW VARIABLES" and "SELECT @@global.max_allowed_packet".

**Expected Behaviour**

Connect directly to the schema requested instead of connect with no schema, run queries, then enter the requested schema.

**Related Issues**

none

**Additional Context**

Example from Sequel Ace Console.  Notice the 16s then 17s then 16s after the first three commands.  Those are timeouts because they aren't valid to Proxysql without a schema.
```
/* 13:15:20 my_connection_name */ SHOW VARIABLES;
/* 13:15:36 my_connection_name */ SELECT @@global.max_allowed_packet;
/* 13:15:53 my_connection_name */ SHOW VARIABLES LIKE 'max_allowed_packet';
/* 13:16:09 my_connection_name */ USE `my_schema_name`;
/* 13:16:09 my_connection_name my_schema_name */ SHOW VARIABLES LIKE 'skip_show_database';
/* 13:16:09 my_connection_name my_schema_name */ SHOW DATABASES;
/* 13:16:09 my_connection_name my_schema_name */ SHOW FULL TABLES;
/* 13:16:09 my_connection_name my_schema_name */ SELECT * FROM information_schema.routines WHERE routine_schema = 'my_schema_name' ORDER BY routine_name;
/* 13:16:09 my_connection_name my_schema_name */ SHOW VARIABLES LIKE 'character_set_database';
```

I also noticed that for Sequel Ace talking to proxysql 1.4.16, connection simply never completes.  For Sequel Pro talking to proxysql 1.4.16, it connected but slowly like described here for Sequel Ace talking to proxysql 2.1.1.

**Comment by Jason-Morcos** [comment]
We don't officially support proxysql. I'd gladly review a PR that tweaks this functionality to work with proxysql without breaking MySQL/MariaDB support, but this will have to come from the community and be a minimal/light change.
