### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by yadgen** [Sequel-Ace/Sequel-Ace#1088]
Hi, When will the new version be released?

**Comment by Jason-Morcos** [comment]
Is there something critical you're waiting for? I wasn't thinking there was anything currently in main that wasn't released that was urgent. 

I was planning on pushing a new beta early this week and a new release maybe end of the week?

**Comment by yadgen** [comment]
> Is there something critical you're waiting for? I wasn't thinking there was anything currently in main that wasn't released that was urgent.
> 
> I was planning on pushing a new beta early this week and a new release maybe end of the week?

There is nothing important, only the UI, which is troublesome to use. I look forward to the release of the new version. Thank you very much.

**Comment by Jason-Morcos** [comment]
> > Is there something critical you're waiting for? I wasn't thinking there was anything currently in main that wasn't released that was urgent.
> 
> > 
> 
> > I was planning on pushing a new beta early this week and a new release maybe end of the week?
> 
> 
> 
> There is nothing important, only the UI, which is troublesome to use. I look forward to the release of the new version. Thank you very much.

Hmmm what are you referring to about the UI?

**Comment by yadgen** [comment]
> > > Is there something critical you're waiting for? I wasn't thinking there was anything currently in main that wasn't released that was urgent.
> > 
> > 
> > > 
> > 
> > 
> > > I was planning on pushing a new beta early this week and a new release maybe end of the week?
> > 
> > 
> > There is nothing important, only the UI, which is troublesome to use. I look forward to the release of the new version. Thank you very much.
> 
> Hmmm what are you referring to about the UI?

yes.

**Comment by Jason-Morcos** [comment]
There are no UI changes that I'm aware of that are not in the latest released version of the app already.

**Comment by yadgen** [comment]
Are there any updates to these two UI issues?
https://github.com/Sequel-Ace/Sequel-Ace/issues/1069
https://github.com/Sequel-Ace/Sequel-Ace/issues/1066

**Comment by Jason-Morcos** [comment]
> Are there any updates to these two UI issues?
> 
> https://github.com/Sequel-Ace/Sequel-Ace/issues/1069
> 
> https://github.com/Sequel-Ace/Sequel-Ace/issues/1066

No
The first one has a linked issue (it was a duplicate) that is low priority and has no progress.
The second one is just the way Big Sur is.

**Comment by Jason-Morcos** [comment]
The font issue will not be addressed by the core team. I don't know how else to say it - it's a low priority issue which you or anyone in the community can address, but harassing us won't get this issue addressed.

https://github.com/Sequel-Ace/Sequel-Ace/issues/976#issuecomment-828488273
