### ISSUE TITLE
Cannot insert rows to table with generated column

### ISSUE THREAD

**Issue by guvenakcoban** [Sequel-Ace/Sequel-Ace#1090]
- Sequel Ace Version (including build number): 3.3.1

**Description**
My table has a JSON column and generated column that is from JSON's content.

```
CREATE TABLE `stage_types` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` json NOT NULL,
  `title_en` varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (json_unquote(json_extract(`title`,_utf8mb4'$.en'))) STORED,
  PRIMARY KEY (`id`),
  FULLTEXT KEY `title_en_fulltext_index` (`title_en`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

If I try to add new rows inside of **Content** tab, then I get `The value specified for generated column 'title_en' in table 'stage_types' is not allowed.` error because the insert statement has the title_en column:

From console: `INSERT INTO stage_types (`id`, `title`, `title_en`) VALUES (NULL, '{\"en\": \"en\"}', NULL);`

Insert statement should exclude generated columns.

Thanks.

**Comment by gduh** [comment]
@Jason-Morcos I don't have a lot of time these last few days. I think next week I could take a look along with #1065.

**Comment by Jason-Morcos** [comment]
Any updates @gduh? No worries if no time yet, just checkin' in!

**Comment by gduh** [comment]
> Any updates @gduh? No worries if no time yet, just checkin' in!

@Jason-Morcos I hope I have some time for the start of next week for both issues!

**Comment by gduh** [comment]
@Jason-Morcos, What do you prefer:
- I create 2 branches: one for #1065 and another one for #1090 after merging the first one in main branch (I think it will be in that order necessarily) ?
- I create only branch with both ?

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos, What do you prefer:
> 
> - I create 2 branches: one for #1065 and another one for #1090 after merging the first one in main branch (I think it will be in that order necessarily) ?
> 
> - I create only branch with both ?

Totally up to you! Whatever you think will be simpler. I don't have any issue with combining things into a single PR when they are closely related and likely will impact one another. If I was writing the fix, I would probably do both in the same PR.
