### ISSUE TITLE
在查询界面添加删除行和新增行的功能

### ISSUE THREAD

**Issue by quyixiao** [Sequel-Ace/Sequel-Ace#1095]
在查询视图界面添加一个增加和删除行的功能
![image](https://user-images.githubusercontent.com/7455924/118217162-7cb97880-b4a7-11eb-8698-03b86b6bb1c2.png)

比如下面的
![image](https://user-images.githubusercontent.com/7455924/118217369-e6d21d80-b4a7-11eb-95e1-307d8b5b72a9.png)
一般我们都是先查询出来内容，对数据进行删除，不然就需要写sql 了，但是navicat是有这个功能的。
如下图

![image](https://user-images.githubusercontent.com/7455924/118217508-2ef14000-b4a8-11eb-9d33-7b0929533b83.png)

**Comment by Jason-Morcos** [comment]
Unfortunately, we only address issues in English due to language limitations of our team. Please submit this issue in English if possible.
