### ISSUE TITLE
Spreadsheet Mode Not Working

### ISSUE THREAD

**Issue by olimortimer** [Sequel-Ace/Sequel-Ace#1096]
- Sequel Ace Version (including build number): Version 3.3.2 / Build 3030
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Big Sur 11.3.1 
- Processor Type (Intel/Apple): 2.2 GHz Quad-Core Intel Core i7
- MySQL Version: MySQL 5.5.5-10.3.22-MariaDB-1:10.3.22+maria~xenial

**Description**
Editing cells in 'spreadsheet mode' doesn't always work - 9/10 times it won't work correctly, and resorts back to editing in a pop-up

**Steps To Reproduce**
1. Browse a table
2. Switch on spreadsheet mode
3. Try and edit a cell

**Expected Behaviour**
I would expect it to edit the cell like a spreadsheet, like Sequel Pro allowed you to do, and remember the setting for future connections

**Comment by Jason-Morcos** [comment]
@olimortimer That is likely due to a new preference introduced in https://github.com/Sequel-Ace/Sequel-Ace/pull/912 by @jamesstout 
Does changing that setting fix it for you?
The UI is a little confusing now that I look at it (the checkbox and the number field parts are a little unclear)

**Comment by Jason-Morcos** [comment]
Based on other discussions (ex. https://github.com/Sequel-Ace/Sequel-Ace/pull/912#issuecomment-845940180) there does appear to be some sort of bug with the spreadsheet mode/inline mode editing prefs.
