### ISSUE TITLE
All views except Query are disabled

### ISSUE THREAD

**Issue by dizeee** [Sequel-Ace/Sequel-Ace#1097]
- Sequel Ace Version (including build number): 3.3.1, 3.3.2
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store, Homebrew
- macOS Version: 11.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes

**Description**
`Structure`, `Content`, `Relations`, `Triggers` and `Table Info` view buttons are disabled/inactive, so I'm stuck with just `Query` view. When one of the views except Query is set as default in preferences, all buttons are active and the selected view is displayed after connecting, but without any data, and clicking anywhere inside the window makes them disabled again.

Tried reinstalling from App Store and Homebrew and upgrading 3.3.1 to 3.3.2, didn't help.

**Additional Context**

<img width="1111" alt="Fullscreen_14_05_21__18_54" src="https://user-images.githubusercontent.com/845698/118304012-67177380-b4e6-11eb-9c4d-8bfa03d62064.png">

**Comment by Jason-Morcos** [comment]
Did you select a table in the side bar? You have to have a table selected for those other views to be available - they don't make sense without a table selected

**Comment by dizeee** [comment]
@Jason-Morcos Makes sense, and I would absolutely love to do this, but the thing is, there's no sidebar...

**Comment by dizeee** [comment]
Just realized that the sidebar had 0 width somehow and I was able to expand it. Thanks for the hint!

**Comment by tomobFR** [comment]
> Just realized that the sidebar had 0 width somehow and I was able to expand it. Thanks for the hint!

@dizeee but how did you expand it?

**Comment by tinzog** [comment]
This saved my day - I had exactly the same issue. Thank you!

**Comment by mukotso** [comment]
You saved my day

Thank you

**Comment by jnlmyz** [comment]
You saved my day. Thank you.

**Comment by magicHatOfTYPO3** [comment]
run into the same issue. Thanks!

**Comment by armankirakosyan** [comment]
I had same issue. Thanks!

**Comment by blankbro** [comment]
> Just realized that the sidebar had 0 width somehow and I was able to expand it. Thanks for the hint!

how to set it?
