### ISSUE TITLE
Sequel Ace won't connect via SSH

### ISSUE THREAD

**Issue by neokio** [Sequel-Ace/Sequel-Ace#1108]
- Sequel Ace Version: 3.3.2 build 3030
- Sequel Ace Source: Homebrew
- macOS Version: 10.13.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.26
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

    Yes (downloaded from github instead of Homebrew, same issue)

**Description**
```
- Sequel Ace can connect to a local MySQL server via sockets (MAMP).
- Sequel Ace can connect to a remote MySQL server via TCP/IP.
- I can SSH (via terminal/bash) to a remote server.
- Sequel Ace **can NOT** connect to a remote MySQL server via SSH.
```

**Steps To Reproduce**

    Initiate an SSH connection ...

![Screen Shot 2021-05-18 at 10 39 02 AM](https://user-images.githubusercontent.com/146623/118690763-5e6cb900-b7d6-11eb-9ad2-9a302e749350.png)

**Expected Behaviour**

    Connection, instead of the error:

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/n/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -i /Users/n/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 devuser@dev.myservername.com -L 54231:localhost:3306

OpenSSH_7.8p1, LibreSSL 2.6.2
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Connecting to dev.myservername.com [192.249.127.133] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
load pubkey "/Users/n/.ssh/id_rsa": Operation not permitted
debug1: identity file /Users/n/.ssh/id_rsa type -1
debug1: identity file /Users/n/.ssh/id_rsa-cert type -1
debug1: identity file /Users/n/.keys/id_rsa type -1
debug1: identity file /Users/n/.keys/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to dev.myservername.com:22 as 'devuser'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:oiATibAFQjcQZf5VouCHE7A/P8dp04ayj/TgjhiQIso
debug1: read_passphrase: can't open /dev/tty: Device not configured
dyld: Library not loaded: @rpath/libswiftCore.dylib
Referenced from: /Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant
Reason: image not found
Host key verification failed.
The SSH Tunnel has unexpectedly closed.
The SSH Tunnel has unexpectedly closed.
```

**Related Issues**

https://github.com/Sequel-Ace/Sequel-Ace/issues/159 (The error is similar, though running `cp ~/.ssh/known_hosts ~/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict` doesn't fix the problem.)

**Comment by Jason-Morcos** [comment]
Have you tried purging both your system known hosts and the Sequel Ace built in known hosts files, quitting ace, and trying again? Have you tried tweaking Ace's network settings to use your main known_hosts file?

**Comment by neokio** [comment]
@Jason-Morcos Thank you! I hadn't even considered deleting my system known hosts. Deleting `~/.ssh/known_hosts`, connecting in terminal via SSH, and then copying it with a `cp ~/.ssh/known_hosts ~/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict` got Sequel Ace to work. 

Is this just something one has to do every time they add an SSH connection?
Or is it something that happens in specific environments?

More importantly, how do I tweak Ace's network settings to use my main `known_hosts` file?

**Comment by neokio** [comment]
Probably unrelated to the above, when I delete `~/.ssh/known_hosts`, the first host I connect to (via using SSH) adds this to the new `known_hosts`:

```
mysite1.com ssh-ed25519 AXAAAC3NzaC1lZDI1NTE5AAAAIKSEKO7s/Sf03vl+7JdlWGD6UQyDg145rJF2RZ0c78YSI
mysite1.com ssh-rsa AAAAB3NzaC1yc2EAXAAADAQABAAABAQD1pXF4LIzoBm3P8MzT9az1UscN50NxvESrIC+2yiOz004GI7+luz5SfPiXjxuopYKWoSJ5J+Z8p0alS0qwgvLRRgORUnokO6QwVXdhYipf8NhPxSwKYeS2QMyGNjHDheXIiXWKtJ7sA6rrM7kTvPcQLL3c6M11l+sSuNmuGolHJ1i7eloNKUpE8AkVUpfh0jRLuUtYZFi+fTD0H+wNkRODbzkkDlyf8bHPnO76vIXfAlgvk9FV0umv9fzw5hFt5H0qzFpVU78bfjwSVvxNObzFnKEmBnhDWJspYQ5O7USMAMGhxS46ql3ZFBu7EQcq/NnV2ag0Jwt/pA+Y/CFI2qtw8r
mysite1.com ecdsa-sha2-nistp256 AXAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBH5v1MS/gqx+7dQ2OM9g6kQbzZMl69X4z7uu8eP0ZST+Hm5MV3bRjC6xKHqqC/7FykDaN5UTH4s7F7xCLKy0YXjI=
```

The second host I connect to (via using SSH) is MUCH shorter. It looks like this:

```
mysite2.com ssh-ed25519 AXAAAC3NzaC1lZDI1NTE5AAAAIKSEKO7s/Sf03vl+7JdlWGD6UQyDg145rJF2RZ0c78YSI
```

With Sequel Ace, I can connect to the first one (mysite1.com), but NOT the second one (mysite2.com). However, if I delete `known_hosts`, SSH to the first host, rename the file, SSH to the second host, and then merge both files, it works. I can connect to both via Sequal Ace.

WHY would only the very first SSH connection create a `known_hosts` file with full hashes, and any subsequent SHH connections add incomplete hashes, jacking up Sequel Ace?

I'm using OpenSSH_8.6p1, OpenSSL 1.1.1k  (25 Mar 2021).

**Comment by Jason-Morcos** [comment]
Glad you got it working!

Yeah, unfortunately you probably do have to re-authorize it every time known_hosts changes. Or you could give Ace full file and folder access via privacy settings and that may work.

**Comment by hokadiri** [comment]
I'm having this issue and the workaround isn't working

Version 3.4.0 Build 3038
MacOS BigSur 11.6
@Jason-Morcos  do you have any ideas?

**Comment by Jason-Morcos** [comment]
Do you have anything funky with your known hosts file? Does your ssh config reference your known hosts file by chance?
@hokadiri If you can't get it figured out, open a new issue and fully fill out the template. It's tough to investigate anything without all the deets :)

**Comment by hokadiri** [comment]
Hi @Jason-Morcos , I got it working it was my mistake. 

Thanks

**Comment by maximehuran** [comment]
Hi,

I still cannot connect throw SSH on Sequel Ace with a connection working on Sequel Pro.

Sequel Ace - Version 3.4.3 - Build 20019
Mac OS Monterey 12.0 (21A344) - M1 Max Chip

Here is my network config : 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/11380627/147077546-3c9edf6b-b16e-48bc-be07-91eccf60e21c.png">

And the files config : 

<img width="529" alt="image" src="https://user-images.githubusercontent.com/11380627/147077562-4062275f-0736-4983-a723-89e23b94a643.png">

In my connection config I added the ssh key : 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/11380627/147077774-499b4675-3313-45ff-90bd-b920fdaddaa8.png">

And cannot connect with SSH : 

<img width="320" alt="image" src="https://user-images.githubusercontent.com/11380627/147077835-e6b436e7-efbe-4ff7-ae8b-9e439d267fab.png">


Logs : 
```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/mhuran/.ssh/known_hosts -F /Users/mhuran/.ssh/config -i /Users/mhuran/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 maximehuran -L 49657:127.0.0.1:3306

OpenSSH_8.6p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/mhuran/.ssh/config
debug1: /Users/mhuran/.ssh/config line 20: Applying options for maximehuran
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to maximehuran.fr [91.121.149.201] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/mhuran/.ssh/id_rsa type 0
debug1: identity file /Users/mhuran/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u2
debug1: compat_banner: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to maximehuran.fr:22 as '****'
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:uC8ACumekiB/mLDXPvOUzihGOLubrFmgT0NeYsE+aZQ
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'maximehuran.fr' is known and matches the ECDSA host key.
debug1: Found key in /Users/mhuran/.ssh/known_hosts:150
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: Operation not permitted
debug1: Will attempt key: /Users/mhuran/.ssh/id_rsa RSA ***************************************
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/mhuran/.ssh/id_rsa RSA ***************************************
debug1: Server accepts key: /Users/mhuran/.ssh/id_rsa RSA ***************************************
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: Device not configured
2021-12-22 11:19:16.581 SequelAceTunnelAssistant[3369:25703] SSH Tunnel: keychain authentication specified but insufficient internal details supplied
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
2021-12-22 11:19:16.609 SequelAceTunnelAssistant[3370:25705] SSH Tunnel: keychain authentication specified but insufficient internal details supplied
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
2021-12-22 11:19:16.637 SequelAceTunnelAssistant[3371:25707] SSH Tunnel: keychain authentication specified but insufficient internal details supplied
debug1: Authentications that can continue: publickey,password
debug1: No more authentication methods to try.
****@maximehuran.fr: Permission denied (publickey,password).
The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.
```

I would like to migrate all my connections from Sequel Pro to Sequel Ace but I am hitting a wall with this 😞

**Comment by Jason-Morcos** [comment]
> Hi,
> 
> 
> 
> I still cannot connect throw SSH on Sequel Ace with a connection working on Sequel Pro.
> 
> 
> 
> Sequel Ace - Version 3.4.3 - Build 20019
> 
> Mac OS Monterey 12.0 (21A344) - M1 Max Chip
> 
> 
> 
> Here is my network config : 
> 
> 
> 
> <img width="648" alt="image" src="https://user-images.githubusercontent.com/11380627/147077546-3c9edf6b-b16e-48bc-be07-91eccf60e21c.png">
> 
> 
> 
> And the files config : 
> 
> 
> 
> <img width="529" alt="image" src="https://user-images.githubusercontent.com/11380627/147077562-4062275f-0736-4983-a723-89e23b94a643.png">
> 
> 
> 
> In my connection config I added the ssh key : 
> 
> 
> 
> <img width="383" alt="image" src="https://user-images.githubusercontent.com/11380627/147077774-499b4675-3313-45ff-90bd-b920fdaddaa8.png">
> 
> 
> 
> And cannot connect with SSH : 
> 
> 
> 
> <img width="320" alt="image" src="https://user-images.githubusercontent.com/11380627/147077835-e6b436e7-efbe-4ff7-ae8b-9e439d267fab.png">
> 
> 
> 
> 
> 
> Logs : 
> 
> ```
> 
> Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/mhuran/.ssh/known_hosts -F /Users/mhuran/.ssh/config -i /Users/mhuran/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 maximehuran -L 49657:127.0.0.1:3306
> 
> 
> 
> OpenSSH_8.6p1, LibreSSL 2.7.3
> 
> debug1: Reading configuration data /Users/mhuran/.ssh/config
> 
> debug1: /Users/mhuran/.ssh/config line 20: Applying options for maximehuran
> 
> debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
> 
> debug1: Connecting to maximehuran.fr [91.121.149.201] port 22.
> 
> debug1: fd 5 clearing O_NONBLOCK
> 
> debug1: Connection established.
> 
> debug1: identity file /Users/mhuran/.ssh/id_rsa type 0
> 
> debug1: identity file /Users/mhuran/.ssh/id_rsa-cert type -1
> 
> debug1: Local version string SSH-2.0-OpenSSH_8.6
> 
> debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u2
> 
> debug1: compat_banner: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
> 
> debug1: Authenticating to maximehuran.fr:22 as '****'
> 
> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
> 
> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
> 
> debug1: SSH2_MSG_KEXINIT sent
> 
> debug1: SSH2_MSG_KEXINIT received
> 
> debug1: kex: algorithm: curve25519-sha256
> 
> debug1: kex: host key algorithm: ecdsa-sha2-nistp256
> 
> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> 
> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
> 
> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
> 
> debug1: SSH2_MSG_KEX_ECDH_REPLY received
> 
> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:uC8ACumekiB/mLDXPvOUzihGOLubrFmgT0NeYsE+aZQ
> 
> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
> 
> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
> 
> debug1: Host 'maximehuran.fr' is known and matches the ECDSA host key.
> 
> debug1: Found key in /Users/mhuran/.ssh/known_hosts:150
> 
> debug1: rekey out after 134217728 blocks
> 
> debug1: SSH2_MSG_NEWKEYS sent
> 
> debug1: expecting SSH2_MSG_NEWKEYS
> 
> debug1: SSH2_MSG_NEWKEYS received
> 
> debug1: rekey in after 134217728 blocks
> 
> debug1: pubkey_prepare: ssh_get_authentication_socket: Operation not permitted
> 
> debug1: Will attempt key: /Users/mhuran/.ssh/id_rsa RSA ***************************************
> 
> debug1: SSH2_MSG_EXT_INFO received
> 
> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
> 
> debug1: SSH2_MSG_SERVICE_ACCEPT received
> 
> debug1: Authentications that can continue: publickey,password
> 
> debug1: Next authentication method: publickey
> 
> debug1: Offering public key: /Users/mhuran/.ssh/id_rsa RSA ***************************************
> 
> debug1: Server accepts key: /Users/mhuran/.ssh/id_rsa RSA ***************************************
> 
> debug1: read_passphrase: can't open /dev/tty: Device not configured
> 
> debug1: read_passphrase: can't open /dev/tty: Device not configured
> 
> debug1: read_passphrase: can't open /dev/tty: Device not configured
> 
> debug1: Next authentication method: password
> 
> debug1: read_passphrase: can't open /dev/tty: Device not configured
> 
> 2021-12-22 11:19:16.581 SequelAceTunnelAssistant[3369:25703] SSH Tunnel: keychain authentication specified but insufficient internal details supplied
> 
> debug1: Authentications that can continue: publickey,password
> 
> Permission denied, please try again.
> 
> debug1: read_passphrase: can't open /dev/tty: Device not configured
> 
> 2021-12-22 11:19:16.609 SequelAceTunnelAssistant[3370:25705] SSH Tunnel: keychain authentication specified but insufficient internal details supplied
> 
> debug1: Authentications that can continue: publickey,password
> 
> Permission denied, please try again.
> 
> debug1: read_passphrase: can't open /dev/tty: Device not configured
> 
> 2021-12-22 11:19:16.637 SequelAceTunnelAssistant[3371:25707] SSH Tunnel: keychain authentication specified but insufficient internal details supplied
> 
> debug1: Authentications that can continue: publickey,password
> 
> debug1: No more authentication methods to try.
> 
> ****@maximehuran.fr: Permission denied (publickey,password).
> 
> The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.
> 
> ```
> 
> 
> 
> I would like to migrate all my connections from Sequel Pro to Sequel Ace but I am hitting a wall with this 😞 

Can you please share the contents of your ssh config itself (anonymized as needed)? Looking at the error, it appears you might specify a known hosts file and a few other things in your .ssh/config file that aren't in the granted files list so Sequel Ace can't access them which would prevent you from connecting

**Comment by maximehuran** [comment]
The used SSH config from line 20 to 22 for this server is : 

```
Host maximehuran
    Hostname maximehuran.fr
    User ****
```

**Comment by Jason-Morcos** [comment]
Couple questions - do you have anything defined globally in your ssh config? If so, can you share that?

Second, did you grant Sequel Ace access to that key file in Sequel Ace's Preferences (files tab)? Our website may be useful - https://sequel-ace.com

**Comment by maximehuran** [comment]
I have this at the beginning of the file: 

```
ServerAliveInterval 120
ServerAliveCountMax 2
```

But if I remove it I have the same issue.
Here are the allowed files : 

<img width="565" alt="image" src="https://user-images.githubusercontent.com/11380627/148982306-85ba0a76-bec7-4f43-80a9-1c0bbdbee7f8.png">

So my key file is granted.

**Comment by Jason-Morcos** [comment]
Does it work if you fill out the SSH User field in Sequel Ace? I'm curious if it doesn't like not getting the ssh user name directly specified in the form

**Comment by maximehuran** [comment]
Same error.
I think the SSH user is getted correctly because according to the the logs of my [previous message](https://github.com/Sequel-Ace/Sequel-Ace/issues/1108#issuecomment-999461593), I see it : 

```
debug1: Authenticating to maximehuran.fr:22 as '****'
```

**Comment by htuzel** [comment]
why this issue is closed, it is still not working

**Comment by smithyj** [comment]
> why this issue is closed, it is still not working

same error.

my macbookpro installed `openssh 9.0`，but online server `openssh` version is `5.0`，so connection failed

![image](https://user-images.githubusercontent.com/9820142/184087783-03b1510f-5eae-4227-95e7-2ffc8205fdf9.png)

**Comment by Jason-Morcos** [comment]
> > why this issue is closed, it is still not working
> 
> same error.
> 
> my macbookpro installed `openssh 9.0`，but online server `openssh` version is `5.0`，so connection failed
> 
> ![image](https://user-images.githubusercontent.com/9820142/184087783-03b1510f-5eae-4227-95e7-2ffc8205fdf9.png)

Isn't OpenSSH 5 like 10+ years old? I'm not really surprised that modern SSH is incompatible with so old a version it's most certainly insecure. Would it be possible to upgrade that remote OpenSSH install?


In general, please open new issues as opposed to commenting on closed ones. Closed issues aren't monitored.

**Comment by maximehuran** [comment]
Tried with `3.5.3` and still have `The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.`

**Comment by maximehuran** [comment]
The command is 

```
 /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/mhuran/.ssh/known_hosts" -F /Users/mhuran/.ssh/config -i /Users/mhuran/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 maximehuran -L 59746:127.0.0.1:3306
```

I removed completely the app, cleaned it with AppCleaner.
And also remove it with brew `brew remove --cask sequel-ace`
I reinstalled it from the App Store and configured the Accessible Files.

The command changed and now if I put my credential I have this prompt : 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/11380627/185187886-7a4f1d01-a145-41d6-94d4-ef286a70129d.png">

**Comment by maximehuran** [comment]
I managed my SSH key password in the system so now I can connect with SSH 🎉 
I just cannot use my ssh config to simplify the connection but it does not matter.

**Comment by maximehuran** [comment]
With this command I've now my ssh_config works !

```
sudo mv "/Applications/Sequel Ace.app/Contents/Resources/ssh_config" "/Applications/Sequel Ace.app/Contents/Resources/ssh_config.bak"
sudo ln -s /Users/mhuran/.ssh/config "/Applications/Sequel Ace.app/Contents/Resources/ssh_config"
```

**Comment by Jason-Morcos** [comment]
> With this command I've now my ssh_config works !
> 
> ```
> sudo mv "/Applications/Sequel Ace.app/Contents/Resources/ssh_config" "/Applications/Sequel Ace.app/Contents/Resources/ssh_config.bak"
> sudo ln -s /Users/mhuran/.ssh/config "/Applications/Sequel Ace.app/Contents/Resources/ssh_config"
> ```

This is generally a bad idea. Are you saying that selecting your custom SSH config is Sequel Ace's preferences doesn't work? Selecting your own SSH config in Sequel Ace's preferences is the recommended way to customize your SSH config. What you're doing here is overwriting the Sequel Ace internal SSH config which means that if we update the default config your changes will be overwritten.

**Comment by maximehuran** [comment]
I restore the file and selected the ssh config in the preferences and it works !

![image](https://user-images.githubusercontent.com/11380627/200848326-2e3f5001-827a-4036-83a0-f4ff64cffff2.png)

I don't know why I had many issues before
Thank you for your help

**Comment by Vladishev** [comment]
For me, the issue was with known_hosts file.
I had also this error
`Offending ECDSA key in /Users/vlad/.ssh/known_hosts:5
Host key for [127.0.0.1]:2222 has changed and you have requested strict checking.`
I had to remove broken hosts using
`ssh-keygen -R '[127.0.0.1]:2222'`
And then I was able to connect to the DB

**Comment by 0-Sony** [comment]
Hey guys, i managed to fix the issue by removing the host in this file 
`/Users/myusername/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict`
hope it helps.
I am now able to connect to my DB again.

**Comment by cy-aleksandr-kupriianov** [comment]
I tried all the solutions mentioned above, but none of them worked. In my case, the passphrase for the private key stored in the keychain was incorrect. When adding a new DB connection to Sequel Ace for the first time, it requests the passphrase for the private key. If you enter the wrong password there and check the "Save password" checkbox, even reinstalling Sequel Ace or deleting configuration files will not resolve the issue
Open Keychain Access, select the "Login" tab, then search for "SSH:" and either delete or modify the entry corresponding to the key in question. This should resolve the issue.

**Comment by rich3po** [comment]
I also have this issue - the fix in https://github.com/Sequel-Ace/Sequel-Ace/issues/1108#issuecomment-1308801349 resolved this for me.

(ie setting the ssh/config path correctly in preferences)

**Comment by alexunivar** [comment]
Same error, no need to fix it, I just uninstall SequelAce, 
I can use SequelPro for now.

**Comment by chuyihuang** [comment]
same error here, I've tried everything...

**Comment by Rany-yilian** [comment]
same error here，and i tried it like [https://github.com/Sequel-Ace/Sequel-Ace/issues/1108#issuecomment-1308801349](url),but i failed

**Comment by GauravChinavle** [comment]
To connect via SSH in Sequel Ace, add your SSH private key by going to Sequel Ace > Settings > Preferences > Files > Add Files and selecting your private key. 
This worked for me.

Please note: **DO NOT DELETE** your known_hosts directly like suggested [here](https://github.com/Sequel-Ace/Sequel-Ace/issues/1108#issuecomment-844292482). It can contain your other hosts to which are using SSH connection.

**Comment by GauravChinavle** [comment]
To connect via SSH in Sequel Ace, add your SSH private key by going to Sequel Ace > Settings > Preferences > Files > Add Files and selecting your private key. 
This worked for me.

Please note: **DO NOT DELETE** your ~/.ssh/known_hosts directly like suggested [here](https://github.com/Sequel-Ace/Sequel-Ace/issues/1108#issuecomment-844292482). It can contain your other hosts to which are using SSH connection.
