### ISSUE TITLE
Query results pane: select all should get headers

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#1109]
In the query results pane you can click and select all / copy.

That's how I quickly get stuff into Excel.

But in this situation it would be nice if the headers were copied too.

**Comment by Jason-Morcos** [comment]
Once you select all, instead of clicking copy or cmd+c, right click and click `copy with column names`. That will do what you're trying to do

**Comment by Jason-Morcos** [comment]
There also is a keyboard shortcut for this functionality - alt+cmd+c
<img width="668" alt="Screen Shot 2021-05-18 at 15 58 31" src="https://user-images.githubusercontent.com/10710367/118733810-e7451e00-b7f1-11eb-97f9-178f93d84715.png">
