### ISSUE TITLE
The "+" icon for adding a new tab is too dark in Dark Mode

### ISSUE THREAD

**Issue by coredumperror** [Sequel-Ace/Sequel-Ace#111]
- Sequel Ace Version: 2.0.2
- macOS Version: Mojave

It's nearly the same shade of grey as its own background, which makes it very difficult to distinguish that there's even a UI control there at all. If you brighten it up a tad, I'm sure it'll be fine.

**Comment by gboudreau** [comment]
Same for the `x` icon on the left, to close a tab. Even worse if the tab is the selected one.

Plus:
![image](https://user-images.githubusercontent.com/370329/85811355-e9ab0f00-b72b-11ea-9e51-81b17f3bbafd.png)

`x` on other tabs:
![image](https://user-images.githubusercontent.com/370329/85811377-fd567580-b72b-11ea-9eee-dd82a2bf7e21.png)

`x` on selected tab:
![image](https://user-images.githubusercontent.com/370329/85811369-f4fe3a80-b72b-11ea-99e0-bccc5de914dc.png)

**Comment by Jason-Morcos** [comment]
Fixed in 3.0

**Comment by coredumperror** [comment]
Except it's not. I have 3.0.1, and the `+` still looks exactly the same: "nearly invisible".
<img width="977" alt="Screen Shot 2020-12-21 at 1 59 06 PM" src="https://user-images.githubusercontent.com/413571/102826051-cc7e9280-4394-11eb-9e03-a5ba397b005e.png">

Oddly, this isn't a problem when there are *two* tabs (regardless of which is selected). Only when there's one.
<img width="1589" alt="Screen Shot 2020-12-21 at 2 00 57 PM" src="https://user-images.githubusercontent.com/413571/102826176-0354a880-4395-11eb-92cc-dedb4ae243ee.png">

The X is quite visible now, though it's a bit off-center, vertically. 
<img width="930" alt="Screen Shot 2020-12-21 at 2 06 32 PM" src="https://user-images.githubusercontent.com/413571/102826561-c937d680-4395-11eb-98e4-f683851c71e8.png">

**Comment by Jason-Morcos** [comment]
Ahhh icons are better but color contrast is still not great. Will reopen

**Comment by Kaspik** [comment]
Yeah I'll fix it tomorrow together with the close one. It's updated for Big Sur but seems like a lot of users is still on lower macOS version...

**Comment by coredumperror** [comment]
Ah, yeah I'm on Catalina still. I didn't realize that'd make a difference.

**Comment by Kaspik** [comment]
Yeah we use SF Symbols for Big Sur with fallback to native icons for lower macOS. SF Symbols are rendered little bit differently, but it shouldn't matter for you as a user - we ned to fix it anyways. :)

**Comment by Jason-Morcos** [comment]
I believe this is now fixed!

As we have received no reports of this issue in version 3.1+ of Sequel ace, I'm gonna close this issue. If you experience this issue again in the latest release of Sequel Ace, please create a new issue and reference this issue number in your description.
