### ISSUE TITLE
Fullscreen / Mission Control Creates Unusable Spaces for New Tabs

### ISSUE THREAD

**Issue by 9ae8sdf76** [Sequel-Ace/Sequel-Ace#1114]
- Sequel Ace Version: 3.3.2 [build: 3030]
- Sequel Ace Source: App Store
- macOS Version: 11.2.3 (20D91)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.29
- macOS Localization: en_US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes. The issue still exists as of the 3.3.2 [build: 3030] RC1 release.

**Description**
Opening a new tab while in fullscreen opens a new fullscreen space, and causes the unfocused space to become a blank, black screen when using mission control to switch spaces. When switching tabs via the tab bar in-app, macOS will switch spaces and cause the old tab to become blank and black, while the new tab becomes usable again.

Note: if multiple spaces (tabs) exist when exiting fullscreen mode, the blank/black space remains until pressing the exit icon from mission control. If multiple tabs exist before entering fullscreen mode, everything looks and works as expected. This only happens when creating new tabs while in fullscreen mode.

**Steps To Reproduce**
1. Fullscreen the app
2. Open as many new tabs as you desire
3. Switch tabs in-app or via mission control

**Expected Behaviour**
Opening new tabs should not create new spaces, nor should unfocused tabs create blank/black spaces. 

**Related Issues**
Could not find any. 

**Additional Context**
![mission-control-blank-black-space](https://user-images.githubusercontent.com/2528463/119724688-0882bb80-be3d-11eb-9451-406234bbcda9.png)
![mission-control-settings](https://user-images.githubusercontent.com/2528463/119724691-09b3e880-be3d-11eb-927a-3261859a4596.png)

**Comment by Kaspik** [comment]
Just curious - does it happen with this setup as well?

<img width="665" alt="Screenshot 2021-05-26 at 22 28 52" src="https://user-images.githubusercontent.com/7204168/119726759-c162ed80-be71-11eb-92d4-4c77414f2666.png">

**Comment by 9ae8sdf76** [comment]
@Kaspik Yes, it still happens.

**Comment by 9ae8sdf76** [comment]
Okay, because I presume you asked because it's not happening for you, I decided to poke around a few other preferences and under General I have set Prefer Tabs to never. If I change that to in full screen (or always) then everything works as expected. Changing it back to never gives me the described behavior.

**Comment by Kaspik** [comment]
Ohhh interesting. Might need to try that and see how other apps behave - but we don't do anything custom now and rely on system... weird.
