### ISSUE TITLE
Query Editor: Undo/Redo doesn't work properly - random data inserted?

### ISSUE THREAD

**Issue by JonLaliberte** [Sequel-Ace/Sequel-Ace#1117]
- Sequel Ace Version (including build number): Version 3.3.2 Build 3030
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7 (19H1030)
- Processor Type (Intel/Apple): Intel
- MySQL Version: NA
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Running most recent release...

**Description**
Undo/Redo do not work properly in the query editor.

**Steps To Reproduce**
1. Edit a query, at some point copy/cut some text
2. Undo changes

**Expected Behaviour**
It would undo/redo what was typed/cut/pasted/etc.

**Related Issues**

**Additional Context**
Video attached here.

The "accessible" text here is not something I had copied, pasted, or typed - it just showed up when undid/redid something I had previously cut.

I've seen variations of this happening often. In the video I end up undoing over and over, then redoing. Most of what you see in the video, typos, random characters in the middle of words, etc - isn't what actually happened while editing the query.

https://user-images.githubusercontent.com/5403662/119888802-d1c3a880-bf03-11eb-9e94-1285c276f119.mp4

**Comment by dalikimail** [comment]
I can confirm that also happened to me
Because of this bug it is difficult to work with query editor

**Comment by pushchris** [comment]
Can also confirm this is happening. Makes working with the query editor hair pulling sometimes
