### ISSUE TITLE
Longtext cannot be edited in popup if binary is enabled

### ISSUE THREAD

**Issue by markBerlin** [Sequel-Ace/Sequel-Ace#1118]
- Sequel Ace Version (including build number): 3.3.2 3030
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.4
- Processor Type (Intel/Apple): Intel
- MySQL Version: Mysql 8.0.23, Maria 10.4.15
- macOS Localization: DE

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
As far as I can see: yes

**Description**
I have enabled "Edit inline or popup" with intelligent switching at 25. If I now click on field settings (see table SQL below) it will always edit in inline mode regardless of the number of characters in it. 

**Steps To Reproduce**
1. Create table and content as described in Additional Context
2. Try to edit "settings" - only inline mode is available

**Expected Behaviour**
It would be nice to edit fields according to the setting in "Edit inline or popup" regardless if it is binary or not.

**Additional Context**
```
// TABLE

CREATE TABLE `format` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `settings` longtext CHARACTER SET utf8 COLLATE utf8_bin,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```
// CONTENT

INSERT INTO `format` (`id`, `name`, `settings`)
VALUES
	(1, 'Convert to PDF', X'7B0A2020202266696C6574797065223A22706466222C0A20202022706172616D6574657273223A7B0A09226F7074696D697A65223A20747275650A2020207D2C0A20202022616C6C6F776564506172616D6574657273223A5B0A20202020207B0A20202020202020202022636F6D6D616E64223A226F7074696D697A65222C0A202020202020202020227265676578223A225E28747275657C66616C73652924222C0A202020202020202020226D656469615479706573223A5B0A20202020202020202020202022646F63756D656E74220A2020202020202020205D0A2020202020207D0A2020205D2C0A202020226D656469615479706573223A5B0A20202020202022646F63756D656E74220A2020205D2C0A20202022757365496E506C61796572223A66616C73650A7D');
```

**Comment by Jason-Morcos** [comment]
This may duplicate #1096
