### ISSUE TITLE
Visually highlight production connections

### ISSUE THREAD

**Issue by salamwaddah** [Sequel-Ace/Sequel-Ace#1120]
I use Ace to connect to my development databases as well as manage some production ones.

## The problem
When running operations on a table you don't know if you're working on a production connection or not. Especially after few hours of work and switching between tabs you'll forget or not notice you're writing in the production connection tab.

## Suggest
When working on a tab that belongs to a production connection - highlight it in red or something. Production or sensitive connection can be configure when connecting via a checkbox or something.

![image](https://user-images.githubusercontent.com/26627088/120102430-05007480-c15c-11eb-82c3-29047eaab9b0.png)

**Comment by Kaspik** [comment]
You can set color for you favorite connections based on what you like, I suggest you do it that way. We are not gonna bring another over-complicating stuff by checking if the DB is production or what, I believe user's choice is the best way. :)
