### ISSUE TITLE
Search everywhere (All tables, All Rows, All Columns; Universal Search)

### ISSUE THREAD

**Issue by thore-hph** [Sequel-Ace/Sequel-Ace#1123]
The only thing missing from this very useful software is the search across the whole database, like it is possible in phpmyadmin.

![phpmyadmin-search-database](https://user-images.githubusercontent.com/61868432/120197921-da78ef00-c221-11eb-88cf-52cc1646ed73.png)

Was requested before (#152), but closed by a bot...

**Therefor I'd like to re-open this issue as a feature request.**
**How to keep this feature request open?**

#260 is "only" searching the current selected table,
#400 has been linked to the #152 feature request,
#322 marked as duplicate of #152 ...

Best regards!

**Comment by attheshow** [comment]
I'm interested in this feature as well.
