### ISSUE TITLE
AD auth using auth_pam via dialog.so

### ISSUE THREAD

**Issue by mlcpap** [Sequel-Ace/Sequel-Ace#1140]
Wondering if there is a known but not by me solution for integrating a third party dialog.so to get around the issue seen when connecting to a mysql server using auth_pam to handle AD authentication.

Or, are there any plans to add this and other libraries to the build?

**Comment by Jason-Morcos** [comment]
I don't believe there is a way I know of to do this today. A PR is welcome if this feature if someone in the community would like to further develop this functionality.
