### ISSUE TITLE
Importing connections from Sequel Pro

### ISSUE THREAD

**Issue by frob** [Sequel-Ace/Sequel-Ace#1141]
I have been a long time user of Sequel Pro but there hasn't been a release since 2016 and I don't want to bother constantly building a nightly myself. So I am trying Sequel Ace. 

It would be nice (since Ace forked from Pro) to be able to import my list of Sequel Pro connections directly to Ace.

**Comment by Jason-Morcos** [comment]
We have an FAQ on how to migrate :)
https://sequel-ace.com/get-started/migrating-from-sequel-pro.html
