### ISSUE TITLE
Relations editor does not allow editing relations for ndbcluster engine type

### ISSUE THREAD

**Issue by mindnever** [Sequel-Ace/Sequel-Ace#1142]
- Sequel Ace Version (including build number):Version 3.3.3 Build 3034
- macOS Version: big sur 11.2
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.25-cluster

**Description**
The relations editor apparently only allows editing for tables created with innodb engine. It even claims:

"This table currently does not support relations. Only tables that use the InnoDB storage engine support them."

Which is not really true. NDB (aka NDBCLUSTER) engine also supports relations, which can be manually created - and even more so, those relations / foreign key constraints are visible in that very same editor.

<img width="734" alt="Screenshot 2021-06-13 at 19 35 54" src="https://user-images.githubusercontent.com/3058993/121817111-9a812580-cc7f-11eb-8852-7420d6b60387.png">

**Comment by Jason-Morcos** [comment]
Does NDB support all the same relations as InnoDB and follow the same syntax?
