### ISSUE TITLE
4+ tabs getting wrong labels and clicking one opens different tab

### ISSUE THREAD

**Issue by jajajaime** [Sequel-Ace/Sequel-Ace#1143]
- Sequel Ace Version (including build number): Version 3.3.3 Build 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 11.4
- Processor Type (Intel/Apple): Intel
- MySQL Version: MySQL 5.5.5-10.2.32-MariaDB-1:10.2.32+maria~bionic
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

No Betas after 3034 as of this writing.

**Description**
Sequel Ace gets confused between tabs and tab label when 4+ tabs are open, especially when the connection is made to the same database.

**Steps To Reproduce**
1. Open one tab and load a database table
2. Open another tab and load a different table
3. Repeat 1 and 2 until you have 4+ tabs
4. Switch between tabs
5. Clicking on a tab selects a different tab
6. Tab labels might be incorrect on what table is loaded

**Expected Behaviour**
For tabs to switch and display the correct label that they have loaded at the time.

**Related Issues**

Could not find.

**Additional Context**

**Comment by Jason-Morcos** [comment]
Duplicates #1056
