### ISSUE TITLE
Favorite and placeholder display bug in query editor

### ISSUE THREAD

**Issue by yanncoupin** [Sequel-Ace/Sequel-Ace#1145]
- Sequel Ace Version (including build number): Version 3.3.3 Build 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.4
- Processor Type (Intel/Apple): Intel
- MySQL Version:
- macOS Localization: fr_FR

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No beta currently available

**Description**
When using favorites with a keyword in the query editor, the keyword text is not replaced. Instead the favorite is simply appended and the selection and visual cue which highlights the placeholder(s) is not located in the right place. This used to work in SP.

**Steps To Reproduce**
1. Create a favorite and set a keyword, e.g. `aa` (see first capture)
2. In the query editor, type `aa<TAB>`. The text `aa` is still visible and the highlight for _default_value_ is wrong.
3. Type actual value, and part of the text before the placeholder will be deleted

**Expected Behaviour**
Text `aa` should be replaced and highlight placed where the text is.

**Related Issues**
Could not find any

**Additional Context**
![sql-ace-bug-1](https://user-images.githubusercontent.com/209176/122183666-c07b1580-ce8b-11eb-92a7-3378455e4022.png)
![sql-ace-bug-2](https://user-images.githubusercontent.com/209176/122183947-06d07480-ce8c-11eb-9331-12e0b28f7aea.png)

**Comment by TomZhuPlanetart** [comment]
Similar issue. 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/52988271/129998231-ca7f149d-a338-46e0-98d4-749c4d0bc70a.png">
<img width="552" alt="image" src="https://user-images.githubusercontent.com/52988271/129998266-fe9e8e8d-51da-4c19-8464-af2874c1487f.png">

**Comment by dafplant** [comment]
Same issue on 3.4.1, unfortunately it's totally unusable for me as I rely on them so frequently.
<img width="376" alt="Screenshot 2021-09-24 at 15 11 04" src="https://user-images.githubusercontent.com/15911274/134689366-f62dd941-063f-44f2-b43f-eaa46960c406.png">

**Comment by Jason-Morcos** [comment]
A PR that aims to fix this issue is very welcome! :)

**Comment by gduh** [comment]
@Jason-Morcos can not reproduce with SA 3.4.2, has this issue been fixed ?
