### ISSUE TITLE
Pop-up sheet shows up for single-line varchar fields

### ISSUE THREAD

**Issue by milosivanovic** [Sequel-Ace/Sequel-Ace#1148]
- Sequel Ace Version (including build number): 3.3.3
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.4
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 5.7.34
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
Double-clicking on field to copy it opens the pop-up sheet even though it isn't warranted. Also, "Edit All Fields in Pop-up Sheet" is not selected.

**Steps To Reproduce**
1. Create VARCHAR(255)
2. Double-click on a field to edit the value
<img width="741" alt="Screen Shot 2021-06-20 at 8 01 10 PM" src="https://user-images.githubusercontent.com/1274505/122701520-45ef2480-d202-11eb-9797-67fde8a9ad0d.png">

**Expected Behaviour**
It should turn the field into a fully-selected input field, ready for copying or overwriting, without invasive pop-ups, like this:
<img width="190" alt="Screen Shot 2021-06-20 at 7 44 15 PM" src="https://user-images.githubusercontent.com/1274505/122700349-f90a4e80-d1ff-11eb-9bf8-8be8936f2666.png">

**Related Issues**
#1149

**Comment by Jason-Morcos** [comment]
I believe this duplicates #1096
