### ISSUE TITLE
Once pop-up sheet is closed, field turns into editable input field

### ISSUE THREAD

**Issue by milosivanovic** [Sequel-Ace/Sequel-Ace#1149]
- Sequel Ace Version (including build number): 3.3.3
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.4
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 5.7.34
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
Closing a pop-up sheet with "OK"  or "Cancel" results in the field remaining to be editable by turning the relevant cell into an editable input field. As the editing was already prompted with the pop-up sheet, the user is expecting their action to be complete. To make things even more confusing, pressing any additional key at this point would result in the pop-up sheet being re-prompted despite the existing field appearing to be editable already.

**Steps To Reproduce**
1. Create VARCHAR(255)
2. Double-click on a field to edit the value
3. OK or Cancel
4. Notice that the selected field now becomes an editable input field
5. Clicking out or pressing ESC is required to fully complete or revert the change

**Expected Behaviour**
Completing the edit, cancelling or pressing the ESC key should commit or revert any edit action, in other words, it the result of the field should look like this, with no edit capability:
<img width="189" alt="Screen Shot 2021-06-20 at 7 49 21 PM" src="https://user-images.githubusercontent.com/1274505/122700694-9cf3fa00-d200-11eb-8f8b-52b855e36eb8.png">

**Related issues**
#1148

**Comment by Jason-Morcos** [comment]
Re-reading this, this is actually on purpose. Often, you don't want to edit just one field on the table so after editing that one text column, you may want to change other columns before your changes are committed. Imagine inserting a new row into a table with multiple required big text columns - that insert wouldn't be possible with a behavior different to this one. Simply click outside of the edited cell to commit the changes. Does that make sense? Happy to discuss further.
