### ISSUE TITLE
Status bar Console shows text in the icon area

### ISSUE THREAD

**Issue by helptiger** [Sequel-Ace/Sequel-Ace#115]
- Sequel Ace Version: 2.1.0 Beta 6
- macOS Version: 10.14.6
- MySQL Version: mariadb

**Description**
Status bar Console shows text in the icon area

![Bildschirmfoto_2020-06-26_um_13_45_02](https://user-images.githubusercontent.com/10258902/85854286-67b2f880-b7b4-11ea-937f-161b1ae2c499.jpg)

**Comment by Jason-Morcos** [comment]
Indeed can replicate. Looks like the filter icon is getting a weird non-image

**Comment by Jason-Morcos** [comment]
Fixed it, will be fixed in 2.1.0 release!
