### ISSUE TITLE
layout glitch in import screen

### ISSUE THREAD

**Issue by frumbert** [Sequel-Ace/Sequel-Ace#1150]
- Sequel Ace Version (including build number): Version 3.3.3 Build 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): Probably homebrew iirc
- macOS Version: 10.14.6 (18G9028)
- Processor Type (Intel/Apple): Intel
- MySQL Version: mariadb 10.3 (docker)
- macOS Localization: en-au

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Hitting import puts the controls over the top of the browsable content area
![Screen Shot 2021-06-21 at 4 39 25 pm](https://user-images.githubusercontent.com/592257/122717918-9cff0300-d2af-11eb-9b73-b7bc0b41494a.png)

**Steps To Reproduce**
1. make a database
2. file > import

**Expected Behaviour**

position of select boxes should be in its own area that is underneath the browsable field area

**Related Issues**

**Additional Context**

**Comment by Kaspik** [comment]
Really sorry to hear this but I'm not sure if we are gonna focus on fixing macOS 10.14.6... (not that we don't want to, but there is just not enough resources/people here to fix things like this)

**Comment by Kaspik** [comment]
Newer issue opened, cross-linked, closing for dupp.
