### ISSUE TITLE
Allow to disable the translation and use sequel ace in native english.

### ISSUE THREAD

**Issue by apermo** [Sequel-Ace/Sequel-Ace#1151]
The german translation of Sequel Ace is super bad...

the technical term "truncate" for example is translated, while it is commonly used as it is part of mysql and not part of english.
This is just one example, but there is a lot more.

Please either fix the translation, or simply allow to use sequel ace without localization.

**Comment by Jason-Morcos** [comment]
Hi,

I'm sorry to hear the German translation isn't so great yet.

First, MacOS lets you choose which language to use for the app. https://support.apple.com/guide/mac-help/change-the-system-language-mh26684/mac (see "Choose the language you use for individual apps"). You should very easily be able to choose the English version via that method.

Second, translation is being done by the community by (in theory) native speakers who choose to do so. That means anyone can join our Crowdin project and fix translation strings that are incorrect. You can join that project here if you would like to contribute fixes: https://crowdin.com/project/sequel-ace

**Comment by apermo** [comment]
Thanks for the reply. I'll just change the language. 

The translation is still bad, look either like translated with google translate, or by someone who might be native but is not a developer.

**Comment by Kaspik** [comment]
... which still means you can go to crowding and imrove it. :)

**Comment by apermo** [comment]
I could... but I don't have the time for that atm.

**Comment by markuspoerschke** [comment]
@Kaspik 

> ... which still means you can go to Crowdin and imrove it. :)

I’ve updated the translations in Crowdin for "truncate", but the corrected translations are not yet available:

![image](https://user-images.githubusercontent.com/1222377/129349048-b9bcc4ee-8fe5-4e4c-ac41-3289f92922f4.png)

Is there a way to get these translations into the Software?

**Comment by Kaspik** [comment]
Once you fiy Crowdin, it will get into next submit - so they should be ready as soon as we release :)

**Comment by weranda** [comment]
I have the same thing but with the Russian language. I want to use the full English version. And I can't change that in the settings.

**Comment by Jason-Morcos** [comment]
> I have the same thing but with the Russian language. I want to use the full English version. And I can't change that in the settings.

Are you saying [this](https://github.com/Sequel-Ace/Sequel-Ace/issues/1151#issuecomment-866595006) doesn't work?

**Comment by weranda** [comment]
> Are you saying this doesn't work?
It works. Thanks.

**Comment by cnscud** [comment]
really good suggestion, The translation is bad, some english some chinese for me, I really need use english for this app.

>>  I can switch language by Macos settings now.

**Comment by Kaspik** [comment]
Sorry, fix for all translations is running, so this shouldn't be an issue anymore.
