### ISSUE TITLE
when use open table in new tab the Ace crashed

### ISSUE THREAD

**Issue by morakabi** [Sequel-Ace/Sequel-Ace#1154]
- Sequel Ace Version: 3.3.3 build 3034
- Sequel Ace Source: App Store
- macOS Version: 11.4 (20F71)
- Processor Type: Intel
- MySQL Version: MariaDB 10.3

**Description**
When i right click on table name and use "Open table in new tab" new tab created then Ace freeze!

**Related Issues**

I think when i use ssh tunnel for connection this error occurred
https://github.com/Sequel-Ace/Sequel-Ace/issues/658#issuecomment-853108286

**Additional Context**

I have to use ssh tunnel for all connections and this option is very useful and i don't ignore it

**Comment by Jason-Morcos** [comment]
Please upload the crash log for this crash so we can debug it
