### ISSUE TITLE
Are there any plans to integrate PostgreSQL in the future?

### ISSUE THREAD

**Issue by grafxflow** [Sequel-Ace/Sequel-Ace#1157]
**Feature request.**

Are there any plans to integrate PostgreSQL in the future?

**Comment by Kaspik** [comment]
Short answer: Not in near future.

Longs answer: Possibly, but I don't think it would be this year. Core connection stuff is not happy right now and needs to be rewritten, and introducing new stuff into it would cause huuuuuge problems.

**Comment by grafxflow** [comment]
Thanks for the quick reply @Kaspik 

One thing for sure its nice to finally be able to access mysql 8. So thanks for reviving this application :)

**Comment by Kaspik** [comment]
Haha, happy to hear that. I hope we will be able to find more time for SA, but it's currently not that easy.
