### ISSUE TITLE
slow typing in query editor

### ISSUE THREAD

**Issue by mmbenjamin** [Sequel-Ace/Sequel-Ace#1160]
- Sequel Ace Version (including build number): 3.3.3 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): AppStore
- macOS Version: macOS BigSur 11.4
- Processor Type (Intel/Apple): Apple M1 2020
- MySQL Version: 8.0.17
- macOS Localization: English (UK)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
Very slow typing in query editor. Typing speed decreases with query being longer. It takes about one second per key to be typed in. Even with code completion off.

https://user-images.githubusercontent.com/5840746/124587191-a4014600-de57-11eb-809c-0f77937e4c8d.mov

**Steps To Reproduce**
1. Open any connection to any server
2. Type in some query, by some time, query typing will lag significantly comparing to what is being typed on keyboard. Any other app or OS function properly, only sequel ace query editor has this problem. 

**Expected Behaviour**
To have editor in same speed as I type.

**Related Issues**
None found

**Additional Context**

**Comment by Jason-Morcos** [comment]
Duplicates https://github.com/Sequel-Ace/Sequel-Ace/issues/1071
Turning off syntax highlighting appears to be a workaround.
