### ISSUE TITLE
Unable to create text column without default value

### ISSUE THREAD

**Issue by jakubboucek** [Sequel-Ace/Sequel-Ace#1163]
- Sequel Ace Version: 3.3.3 (3034)
- Sequel Ace Source: App Store
- macOS Version: 10.15.7
- Processor Type: Intel
- MySQL Version: MariaDB 10.3.27
- macOS Localization: EN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, 3.4.0 (3035) Beta 1 same result

**Description**
When I create new column with text type (`CHAR`, `VARCHAR`, `TEXT`, etc.), here is no way to create it without `DEFAULT VALUE` set to empty string or NULL.

**Steps To Reproduce**
1. Open or create any table.
2. Switch to `Structure` tab.
3.  Click to `+` sign to add new Column.
4. Fill `Field`.
5. Change `Type` to `VARCHAR`.
6. Define `Length` to any number.
7. Press `Enter`.

Now is created Column with `DEFAULT NULL`.

**Steps To Reproduce**
1. Open or create any table.
2. Switch to `Structure` tab.
3.  Click to `+` sign to add new Column.
4. Fill `Field`.
5. Change `Type` to `VARCHAR`.
6. Define `Length` to any number.
7. Uncheck `Allow Null`
8. Press `Enter`.

Now is created Column with `DEFAULT ''`.

Here is no way to create column without default value.

**Expected Behaviour**
No default value until user explicitly fill it. Maybe add any way (small `×` button to `Default` parameter field, or at least right-click) option to remove default value from column.

**Related Issues**
Searched, nut no related issue found.

**Additional Context**
![image](https://user-images.githubusercontent.com/1657322/124985247-7a544480-e03a-11eb-94f1-23af7d8c9cca.png)

**Comment by Jason-Morcos** [comment]
Hmm this is a tough one to handle as there are certainly valid use cases for a default value of null, and some people make the _interesting_ choice of having fields default to an empty string.
An opinionated approach could be to treat blank string input as no default value, but that would block people from doing blank-string-defaults.

Ideas, @Kaspik? Little button like suggested? A popup if they enter a blank string prompting to choose a default value (None, NULL, or "")? Or perhaps a new magic input (NO DEFAULT) or something?

**Comment by jakubboucek** [comment]
Maybe you can be inspired by MariaDB `information_schema.COLUMNS` table where was in [version 10.2.7](https://mariadb.com/kb/en/mariadb-1027-release-notes/) changed format of `COLUMN_DEFAULT` where literals are quoted to distinguish them from expressions.

**Comment by Jason-Morcos** [comment]
> Maybe you can be inspired by MariaDB `information_schema.COLUMNS` table where was in [version 10.2.7](https://mariadb.com/kb/en/mariadb-1027-release-notes/) changed format of `COLUMN_DEFAULT` where literals are quoted to distinguish them from expressions.

I think this is a great solution, @jakubboucek. Would gladly accept a PR that makes this change and maybe one of us from @Sequel-Ace/all can work on it if time allows

**Comment by gduh** [comment]
@Jason-Morcos Do you want me to work on it ?
If yes and if I resume, the different values accepted for the `column_default` : 
- empty --> will be now `default null`
- null --> `default null`
- '' --> for empty string
- 'expresion'

Ok with that ?

**Comment by Jason-Morcos** [comment]
You can totally work on it, @gduh!
My thought would be this:
- Empty -> no default value at all
- null -> default null
- "" or '' -> empty string
- "STRING" or 'string' is a string
- Anything else is a mysql expression and should _not_ be wrapped in any quotes. Thoughts?

**Comment by gduh** [comment]
@Jason-Morcos, just 3 comments so far : 
- At least for MariaDB (from 10.2.7 ?, Not checked for others versions for the moment) if no default value is specified for the current field, then MariaDB consider it as `default null`. But I need to explore documentation further if it's ok for older version too and for MySQL in general.
- A mysql expression must be enclose within parentheses to distinguish them from literal. The only one exception is for the  CURRENT_TIMESTAMP function. Moreover, expressions are not allowed for older versions, I have to check which ones exactly.
- This change has a global impact for users on how the default value is used. The release notes will be important.

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos, just 3 comments so far :
> 
> * At least for MariaDB (from 10.2.7 ?, Not checked for others versions for the moment) if no default value is specified for the current field, then MariaDB consider it as `default null`. But I need to explore documentation further if it's ok for older version too and for MySQL in general.

It should very much be possible to have fields with no default value! I know I have some in MySQL 5.7.x that have no default value and are not nullable. The DB throws an error if you try to insert a row without the value specified.


> * A mysql expression must be enclose within parentheses to distinguish them from literal. The only one exception is for the  CURRENT_TIMESTAMP function. Moreover, expressions are not allowed for older versions, I have to check which ones exactly.


Interesting! I didn't realize that, good to know

> * This change has a global impact for users on how the default value is used. The release notes will be important.

Absolutely! We can also pop up a notice the first time the user opens the update. I don't recall where that gets placed, but we've done it before. There's some sort of version check that occurs that looks at the previous version opened and writes it into defaults and displays any special alerts.

**Comment by gduh** [comment]
@Jason-Morcos 
> * Anything else is a mysql expression and should _not_ be wrapped in any quotes.

If we consider an expression is always surrounded by parenthesis, what about a default value with no parenthesis, single or double quotes ? 

So, I suggest :

- Empty -> no default value at all
- null -> default null
- "" or '' -> empty string
- "some string" or 'some string' is a string (double or single quotes to wrap a string)
- (some_expression) -> expression
- Anything else is considered a string and will be wrapped by single quotes.

Are you ok with this ?

**Comment by Jason-Morcos** [comment]
That sounds good to me! We'll need to make sure we test default current timestamp stuff fairly extensively to make sure it's not broken by these changes, but sounds good (ex. DEFAULT CURRENT... should be an expression).
Maybe there's a way we can get the default value back always wrapped in quotes if it's a string?

**Comment by gduh** [comment]
@Jason-Morcos, I set a warning the first time the user selects the Structure tab.

![image](https://user-images.githubusercontent.com/15440947/133147988-ae10eb82-122e-43b6-8809-25b5b97dab43.png)

    The use of the "default" column has changed since the last version of Sequel ACE:

    - No default value : Leave it blank.
    - String value : Use single '' or double quotes "" if you want an empty string or to wrap a string
    - Expression : Use parentheses (). Except for the TIMESTAMP and DATETIME columns where you can specify the CURRENT_TIMESTAMP function without enclosing parentheses.

But I'm not sure about the content. Moreover, with a clean installation, the warning will be displayed and for a new user the interest is limited. 
Finally, I am not completely convinced of the usefulness of this message.
So, what do you prefer ?

**Comment by Jason-Morcos** [comment]
I like the message! And I'm not too worried about showing it to new users.

@Sequel-Ace/all does anyone else have any thoughts here?

I was thinking in general for date-type fields we can _always_ assume the default is either none, null, or an expression, right? In other words, since it can never be a string we don't even have to have any special logic for CURRENT_TIMESTAMP and can fallback on assuming it's always an expression?

**Comment by gduh** [comment]
> I was thinking in general for date-type fields we can _always_ assume the default is either none, null, or an expression, right? In other words, since it can never be a string we don't even have to have any special logic for CURRENT_TIMESTAMP and can fallback on assuming it's always an expression?

Yes, a piece of code already exists for CURRENT_TIMESTAMP. I didn't need to update it. Finally, the main update concerns the string type (varchar, text,...). I think the change is ok now after testing a lot of cases.

I'm waiting for comments about the warning to know if I let it or modify it before committing my change.

**Comment by samuelbradshaw** [comment]
> I was thinking in general for date-type fields we can _always_ assume the default is either none, null, or an expression, right? In other words, since it can never be a string we don't even have to have any special logic for CURRENT_TIMESTAMP and can fallback on assuming it's always an expression?

Couldn't the default for a date field also be a date? (2021-01-01, for example?) Or am I misunderstanding?

**Comment by gduh** [comment]
If default value is none (Default column left empty), the default value inserted will be null or 0000-00-00 00:00:00 depending on whether "allow null" is checked or not.
In that case, the SQL engine will produce a "create table" with `myFieldName timestamp NULL DEFAULT NULL` or `myFieldName timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'`.
