### ISSUE TITLE
Invalid text length limit in UI

### ISSUE THREAD

**Issue by jakubboucek** [Sequel-Ace/Sequel-Ace#1164]
- Sequel Ace Version: 3.3.3.(3034)
- Sequel Ace Source: App Store
- macOS Version: 10.15.7
- Processor Type: Intel
- MySQL Version: MariaDB 10.3.27
- macOS Localization: EN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, 3.4.0 (3035) Beta 1 same result

**Description**
Limit length of text column has wrong limitation in UI during insert or edit the row in case is used multibyte encoding.

**Steps To Reproduce**
1. Open or create any table.
2. Switch to `Structure` tab.
3.  Click to `+` sign to add new Column.
4. Fill `Field`.
5. Change `Type` to `CHAR` or `VARCHAR`.
6. Define `Length` to `1`.
7. Set `Encoding` to `UTF-8 Unicode (utf8mb4)`
8. Press `Enter`.
9. Switch to `Content` tab.
10. Add new row or edit one, to created `CHAR(1)` column try to write/paste any multibyte char (`🉐` for example).
11. 🐞 Bug: No text is entered, but is showed small label `Maximum text length is set to 1.`

**Proof of bug**

12. Switch to `Query` tab.
13. Put the SQL:

```sql
    INSERT INTO `utf8mb4_test` (`your_column`) VALUES ('🉐');
```

🎉 It works! 

**Example table**

```sql
CREATE TABLE `utf8mb4_test` (
  `your_column` char(1) NOT NULL,
  PRIMARY KEY (`your_column`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
 
**Expected Behaviour**
For the columns with multibyte charset compute limited length of string by multibyte functions.

**Related Issues**
Searched, but no related issue found.

**Additional Context**

Unable to paste char `🉐` to table via UI.
![image](https://user-images.githubusercontent.com/1657322/124990070-2cdad600-e040-11eb-9377-b0ce28a5cd92.png)

No bug insert same input directly via SQL query:
![image](https://user-images.githubusercontent.com/1657322/124990633-eafe5f80-e040-11eb-9303-d1ad200a2566.png)

**Comment by Jason-Morcos** [comment]
Thanks for the bug report, @jakubboucek! This issue should be fixed in the next release of Sequel Ace. We expect to have an updated beta available later this week or beginning of next.

**Comment by jakubboucek** [comment]
Thanks @Jason-Morcos, awesome fast job 👍

**Comment by jakubboucek** [comment]
It works in Release 3.4.0, I confirm. Thanks!
