### ISSUE TITLE
Website needed?

### ISSUE THREAD

**Issue by ChrisGitIt** [Sequel-Ace/Sequel-Ace#117]
I personaly like the SequelPro Website. Are there any plans for something similar? If so, I would happily offer my workforce!

Also: GREAT WORK SO FAR!

**Comment by Jason-Morcos** [comment]
Hey, @ChrisGitIt! Right now we have a GitHub Pages site that's available at https://sequel-ace.com/
The pages site is automatically hosted from the /docs folder of this repo
Not dead set on it having to stay this way, but that's how it currently is! We'd definitely love contributions!

#95 #96

**Comment by stychos** [comment]
Hi @ChrisGitIt and everyone reading this. I "grabbed" this as mine task, but, unfortunately, having big troubles IRL right now. Anyway, I think I'll be able to return to this in few days and will push documentation sections that are left on Sequel Pro website (if someone won't pick up what's I started).
But, also, I wanted to ask if we need some "front page" for the website, or will it be just a documentation site? Please place your votes and opinions here.

**Comment by trss** [comment]
My two cents. Added this to AlternativeTo: https://alternativeto.net/software/sequel-ace/

Changed official website from this GitHub repo's homepage to https://sequel-ace.com/ on learning about it here. Do keep the info there updated.

**Comment by Jason-Morcos** [comment]
My two cents, I think having a front-page would be good. Not necessarily a totally separate site, just a good landing page on the GitHub Pages site would probably go a long way.

**Comment by Jason-Morcos** [comment]
Closing this as duplicate
Please continue conversation on #96
