### ISSUE TITLE
No + button to add new tab

### ISSUE THREAD

**Issue by mcinp** [Sequel-Ace/Sequel-Ace#1172]
When you opem Sequel Ace and make the first connection, there's no "+" button to add new tab (connection). The button appears only after you have at least 2 tabs. I know that you can do this with cmd-T or from menu and that other mac software (e.g. iTerm) behaves this way. Still this is a bit illogical, that you have to add 2nd tab in order to have button to add further ones.

**Comment by Kaspik** [comment]
Duplicated issue. Go to View - Show tab bar and it will be there.
