### ISSUE TITLE
Connecting to MariaDB Xpand currently not possible

### ISSUE THREAD

**Issue by boywijnmaalen** [Sequel-Ace/Sequel-Ace#1175]
I'd like to connect to [MariaDB Xpand solution](https://mariadb.com/products/mariadb-platform/xpand/). We're currently running an on-premise cluster. 

It should be compatible with MariaDB and MySQL connectors, even got a response from the Xpand support team saying "Xpand is a drop-in replacement for MariaDB Enterprise Server (The OS version)". However I'm getting an error while connecting to the Xpand cluster; 

"MySQL said: [26630] Unsupported encoding: client requested charset 255"

Does anyone have an idea on how I should go about this? is support for Xpand currently on the roadmap?

Thanks in advance!

**Comment by Jason-Morcos** [comment]
What version is the database? What version of Sequel Ace are you using? We really need you to fill out the full set of questions it should ask you when trying to submit an issue in order to try to understand what's going on.

**Comment by Jason-Morcos** [comment]
Here's the full set of questions if you need them:

```
<!-- Please search existing issues to avoid creating duplicates. -->
<!-- Please fill out ALL ITEMS in the bug report. We simply can't fix bugs if we don't have all the information -->

- Sequel Ace Version (including build number):
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version:
- Processor Type (Intel/Apple):
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
<!-- Please try the [latest beta](https://github.com/Sequel-Ace/Sequel-Ace/releases). If the latest beta works, we've fixed the issue already and will get the fix out soon. There's no need to open a new issue for a bug already fixed in the latest beta. -->

**Description**
A clear and concise description of what the bug is.

**Steps To Reproduce**
1.
2.

**Expected Behaviour**
<!-- A clear and concise description of what you expected to happen. -->

**Related Issues**
<!-- Please search [Issues on GitHub](https://github.com/Sequel-Ace/Sequel-Ace/issues?q=is%3Aissue), including Closed Issues, for the bug. If the bug has been fixed and is pending release, there may already be a closed issue for it. If an existing report of your issue already exists, please don't open a new issue and refer to the existing issue. -->

**Additional Context**
<!-- Add any other context about the problem here. -->
<!-- Please ATTACH any SCREENSHOTS AND CRASH LOGS that might help investigating and addressing the issue. -->
<!-- Please please please attach crash logs (as zip files if needed) and don't paste the content of the crash itself, it's much easier for us to work with files than massive text blocks -->
```

**Comment by boywijnmaalen** [comment]
@Jason-Morcos ,

apologies, all valid questions, here goes;

Sequel Ace Version (including build number): **Version 3.3.3 Build 3034**
Sequel Ace Source (App Store/GitHub/Homebrew): **App store**
macOS Version: **Mac OS Big Sur 11.4**
Processor Type (Intel/Apple): **Intel**
MySQL Version: **Server version: 5.0.45-Xpand-5.3.14**
macOS Localization: **en-GB**

**Description**
We're currently investigating the possibility to invest in MariaDB Xpand, supposedly a drop-in replacement for the current solution we're using; MariaDB Enterprise Server.

While trying to connect to this newly created Xpand instance (using Sequel Ace) I ran into an error. If I try to connect to the server via command-line interface, it works as expected.

**Expected Behaviour**
Being able to connect to our Xpand instance using Sequel Ace.

**Related Issues**
Couldn't find any related issues in the issue tracker when searching for 'Xpand'

**Additional Context**
I tried different clients (on my Mac) to connect to Xpand. DBeaver was able to connect using their MariaDB driver.
I tried (more or less) debugging the connection (failure), I noticed when connecting successfully to another MariaDB Enterprise instance we're using that Sequel Ace by default runs a couple of queries on the server while establishing the connection.

(I pulled these from the console tab after successfully connecting to a MariaDB Enterprise instance)
```
SHOW VARIABLES;
SELECT @@global.max_allowed_packet;
SET NAMES 'utf8mb4';
SHOW VARIABLES LIKE 'skip_show_database';
SHOW DATABASES;
```

I then ran the above queries one-by-one on the Xpand instance using the CLI connection. all of the queries ran successfully, working theory was that one these queries somehow failed on the Xpand instance, but this was not the case.

Please let me know if you require anything else

**Comment by Jason-Morcos** [comment]
I'm sorry for the late reply! Thank you for providing that information

It appears that the version of MySQL (equivalent) reported may be very old, what result do you get to the query `SELECT VERSION();` run against the Xpand database (via DBeaver or other)?

This appears to be some sort of charset issue, but I'm not sure what exactly the issue may be. I'm wondering if perhaps this is an older version under the hood which we may not fully support (we only support MySQL equivalent version >= 5.6)

**Comment by Jason-Morcos** [comment]
After digging a little more, my best hunch is that for some reason the server doesn't support utf8mb4 but advertises as if it does. Very odd

**Comment by boywijnmaalen** [comment]
run the query you requested;

```
MySQL [(none)]> SELECT VERSION();
+---------------------+
| VERSION()           |
+---------------------+
| 5.0.45-Xpand-5.3.14 |
+---------------------+
1 row in set (0.00 sec)
```

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all anyone have any ideas here? I'm pretty stumped. 

I also don't get the Xpand versioning scheme but my hunch is it may be that reporting that weird version is what's screwing with Ace. That version looks like MySQL 5.0 and we only support 5.6+. Based on the utf8mb4 collation support though, it can't actually be MySQL 5.0 under the hood.
This honestly may be an Xpand bug with the way it reports version imo. It should report an accurate MySQL equivalent version in response to that query

**Comment by vkick** [comment]
For anyone who is interested, you can enter "OPT_CHARSET_NAME=utf8" in the "Others:" text box so WorkBench 8.0.X can connect to Xpand.

Go to "Manage Server Connections" -> "Connection" (Default Tab)-> "Advanced" (Sub-Tab) -> "Others:" (Text Box)
