### ISSUE TITLE
Feature Request: Run a bash script before connecting

### ISSUE THREAD

**Issue by tiaanwillemse** [Sequel-Ace/Sequel-Ace#1178]
When working with Kubernetes and other containerisation tools you often need to run a bash command to port forward to the container and then connect to the database via Sequel Ace.

i.e.: `kubectl port-forward my-mysql-pod 33061:3306`

If Sequel Ace as the ability to run a pre-connection script and have this as part of the connection details page, it would remove the need to have a terminal window running in the background to keep that connection open and also provide visibility  if that connection breaks.

Another usecase: Users that need to have a VPN connection before connecting to a remote databases could also use it to check if the VPN is connected or auto-connect to the VPN before trying to connect to the database. In this instance having a post-connection script might be useful to restore the system to its pre-connection state (i.e.: disconnect from the VPN)

**Comment by Jason-Morcos** [comment]
This is a cool idea, but I highly doubt we can do this with the sandbox. I bet Apple won't let us just execute a random bash script prior to connection.

I would experiment with using ProxyCommand in your ssh config without any changes to sequel Ace (other than giving Sequel Ace full disk access and switching to your system ssh config in Ace's settings).
https://unix.stackexchange.com/questions/44307/can-ssh-configs-proxycommand-run-a-local-command-before-connecting-to-a-remote/44343#44343
