### ISSUE TITLE
when i use client connect occurred error with "[DAL]Empty or illegal schema for user:dal_user",  but connect by ssh cmd succeed

### ISSUE THREAD

**Issue by lanshipeng** [Sequel-Ace/Sequel-Ace#1182]
- Sequel Ace Version (including build number):
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version:
- Processor Type (Intel/Apple):
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by lanshipeng** [comment]
@schmurfy @mtvee need your help, thanks!

**Comment by Jason-Morcos** [comment]
Please completely fill out the form when submitting a bug report. Blank issue reports will be closed.

**Comment by lanshipeng** [comment]
> Please completely fill out the form when submitting a bug report. Blank issue reports will be [closed.]

![image](https://user-images.githubusercontent.com/21244175/127800242-0ce5aa70-fb1b-496e-ba86-e484735d2c27.png)
see the picture。use mysql cmd connect succeed , i check the ace sql code can't find this bug. @Jason-Morcos

**Comment by lanshipeng** [comment]
> Please completely fill out the form when submitting a bug report. Blank issue reports will be closed.

See the picture.But use mysql cmd connect succeed, I can't solve this bug by check the Sequel-Ace code. @Jason-Morcos 

![20210802112033](https://user-images.githubusercontent.com/21244175/127800626-82d10b97-10aa-4e57-827b-5c8eaf7845a7.jpg)

**Comment by Jason-Morcos** [comment]
Please fill out the full issue form, including important info like your MySQL version.

Additionally, when you use the mysql command, are you connecting dal_user to that specific database (infra_cloudpaas...), or are you just connecting to the general instance? In other words, can you actually access the infra... db via the command line with the same user account?

**Comment by lanshipeng** [comment]
ok, thank you very much . i check the MySQL version . my local mysql version is the latest(MySQL 8.0.26), then i use the user (root) and same  specific database (infra_cloudpaas...) can access the infra... db. the screenshot mysql version is MySQL 5.6.51 . so i think sql ace is not support the old mysql version with specific database ?

**Comment by Jason-Morcos** [comment]
We do support MySQL 5.6. But I think you just pointed out the problem - in the command line you're connecting as root but you're trying to connect as dal_user in Sequel Ace. I bet dal_user doesn't actually have permission to access that database that you're trying to access. Connecting as root via Sequel Ace would probably work, or you can fix the permissions on dal_user.
https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql

**Comment by lanshipeng** [comment]
Thanks reply . dal_user is indeed  has the only permissions of database (infra_cloudpaas...).   Actually the command line as dal_user connect must fill the database (infra_cloudpaass..) can be succeed.  So i have a idea that Sequel Ace client doashboard check all database permissions ,  it's cased connected error even if i fill the database (infra_cloudpaas...) item. Because the database item is  optional. Is my idea correct ?
