### ISSUE TITLE
Cursor waiting a long time before run a query(After updated MacOS)

### ISSUE THREAD

**Issue by xiangbohua** [Sequel-Ace/Sequel-Ace#1183]
- Sequel Ace Version (including build number):Version 3.3.3 Build 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version:11.5.1(20G80)
- Processor Type (Intel/Apple):Intel
- MySQL Version:5.6/5.7 
- macOS Localization:English

**Description**
Cursor will wait a long time(10-20s) before run a query.
See the video for detail.

**Steps To Reproduce**
1.open any database 
2.run any query for example : select 1

**Expected Behaviour**
After click Run Previous the cursor will get into waiting mode (chrysanthemum) and keep that state for 10-20 seconds.
The query should be execute after the long time waiting.
That was terrible for work.

(After review the screen record I have found the waiting mode of the cursor can not be captured but that should can be redone)

**Related Issues**
No found

https://user-images.githubusercontent.com/10529889/127592850-6c5a4293-45fc-4c12-9074-b8ad31409a85.mov

**Comment by Jason-Morcos** [comment]
Hmmm this is very strange. I can't seem to reproduce this, it works every time for me immediately without hanging. Are you connected locally or via SSH?

**Comment by xiangbohua** [comment]
I have tried connect server in my VM or
 company’s server in local network.
The problem was the same.
I don’t use ssh

**Comment by Jason-Morcos** [comment]
Very strange
I cannot reproduce against my local databases nor SSH ones.
@Sequel-Ace/all can anyone else reproduce this?
If nobody can repro it's very tough to fix

**Comment by xiangbohua** [comment]
Maybe I should try this in XCode

**Comment by xiangbohua** [comment]
After reboot system this problem was no longer reproduce.
