### ISSUE TITLE
Font size changes on auto-indentation

### ISSUE THREAD

**Issue by origamifreak2** [Sequel-Ace/Sequel-Ace#1190]
- Sequel Ace Version (including build number): Version 3.4.0 Build 3038
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.0.1 (20B50)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.5.8-MariaDB-log
- macOS Localization: USA

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
The font size in the query editor seems to change when being auto-indented

**Steps To Reproduce**
1. write a query with indentation
2. Auto indentation on new lines will use a smaller font size

**Expected Behaviour**
Auto-indented new lines should use the same font-size as all the other text

**Related Issues**
https://github.com/Sequel-Ace/Sequel-Ace/issues/1153

**Additional Context**

https://user-images.githubusercontent.com/2578041/128739636-18c47d7d-270f-4464-bbf7-eed47a593af0.mov

![sequel_ace_settings_indentation_issue](https://user-images.githubusercontent.com/2578041/128739638-caadb7f4-899e-44ec-b2ae-8531958570a9.png)

**Comment by luis-** [comment]
I believe this can be close, fixed by #1333 but I hadn't linked it properly to this before it was merge.
