### ISSUE TITLE
Add possibility to create and manage user without super privileges for Google SQL Cloud support

### ISSUE THREAD

**Issue by alexander-schranz** [Sequel-Ace/Sequel-Ace#1191]
Currently when trying to connect to Google CLOUD SQL and try to add a new user it errors that you  need super privileges.

> Access denied; you need (at least one of) the SUPER privilege(s) for this operation 

But when using raw SQL a user can be created and granted:

```sql
CREATE USER 'my_user'@'%' IDENTIFIED BY 'my_password';

GRANT ALL ON my_database.* TO  'my_user'@'%'

-- FLUSH PRIVILEGES
```

So I think there is something specially happening in Sequel ACE / Sequel Pro so the User managing is not working on Google SQL Cloud.

**Comment by Jason-Morcos** [comment]
That message isn't coming from Sequel Ace, it's coming from the SQL database. Not exactly sure why it works in raw SQL though. Does the generated SQL statement in your query history look the same as the CREATE USER you manually generated or are there differences?

**Comment by alexander-schranz** [comment]
Thx for the response, didnt know the sql log is also available there i checked it out and it seem it tries to directly manipulate the mysql database which is not allowed by google mysql server:

```
SELECT user FROM mysql.user LIMIT 1;
SELECT * FROM mysql.user ORDER BY user;
SELECT * FROM mysql.db;
SHOW PRIVILEGES;
CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'test141hfq3r3r3af';
UPDATE mysql.user SET max_questions = 0, max_updates = 0, max_connections = 0 WHERE User = 'testuser' AND Host = 'localhost'; -- this SQL seems to provide the error
FLUSH PRIVILEGES;
```

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos
> 
> > Access denied; you need (at least one of) the SUPER privilege(s) for this operation
> 
> > SHOW VARIABLES LIKE ‘%version%’
> 
> Does not return anything:
> 
> > You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '‘%version%’' at line 1
> 
> If you want: `SELECT @@VERSION`
> 
> Its: `5.7.34-google-log`

Thank you for sending the version. What's strange is despite claiming to support everything of MySQL 5.7, Google Cloud clearly takes issue with something that other 5.7 variants don't.

@Sequel-Ace/all Any ideas, folks? Maybe we change the `UPDATE mysql.user SET max_questions...` stuff to still be executed but not to fail out the attempt? In other words, we still run the statement but if it fails we throw up a warning and keep going letting the user know they can't customize connection settings for some reason?

**Comment by alexander-schranz** [comment]
Not sure if it helps here I found something in the docs about this: https://cloud.google.com/sql/docs/troubleshooting?hl=en#access-denied

**Comment by Jason-Morcos** [comment]
> https://cloud.google.com/sql/docs/troubleshooting?hl=en#access-denied

Hmmm I don't see us using `super user@localhost` anywhere, although it's unclear to me if that's saying that that's used somewhere else in the db or in the specific command that's the problem

**Comment by alexander-schranz** [comment]
@Jason-Morcos I think that its not the a `super` statement. I think the problem is that Google Cloud SQL does not allow to manipulate the `mysql.` tables. And seems like then the same error is shown.
