### ISSUE TITLE
Sequel Ace window is not showing when closed with top left minimize button

### ISSUE THREAD

**Issue by ianpea** [Sequel-Ace/Sequel-Ace#1193]
This problem will happen when the window is closed using the minimize button.

Once minimized, clicking on the app icon in dock does not inflate the window back, but the context is changed to Sequal Ace. Work around is to invoke App Exposé while in Sequel Ace context to open the original window, which currently resides in the bottom panel of App Exposé.

<img width="1280" alt="Screenshot 2021-08-12 at 1 46 42 PM" src="https://user-images.githubusercontent.com/38518431/129144444-4a518530-3c96-4575-a91a-8e661ec827d1.png">

**Comment by Jason-Morcos** [comment]
Please fill out the full issue template when creating issues including particularly the version of Sequel Ace being used, version of MySQL/MariaDB, and any logs that may be applicable.

We try to be as helpful as possible, but the volume of issues reported requires us to only have time to dig into those that include all the details needed. I encourage you to open a new issue with all the details provided.
