### ISSUE TITLE
Display connected server in window title

### ISSUE THREAD

**Issue by ryantxr** [Sequel-Ace/Sequel-Ace#1195]
Hello. First, I would like to commend the team for taking over this project. I am very happy with your work.
I typically have multiple Sequel Ace windows open on various database servers. What I found is that it isn't easy to tell at a glance which server it is connected to. 

I am wondering if you can make it so that the connected database server (or shortcut name) appeared first in the window title. This is far more important that seeing the version of MySQL I am connected to.

![Screen Shot 2021-08-13 at 11 52 30 AM](https://user-images.githubusercontent.com/12485311/129386556-c9fa8bb8-2706-4cd6-a8df-06cf2ea278d1.png)

**Comment by Kaspik** [comment]
Hey, if you enable tab bar (View => Show tab bar), it should show it there :)
