### ISSUE TITLE
UI becomes slow after program is open for a while

### ISSUE THREAD

**Issue by origamifreak2** [Sequel-Ace/Sequel-Ace#1197]
- Sequel Ace Version (including build number): Version 3.4.0 Build 3038
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.0.1 (20B50)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.5.8-MariaDB-log
- macOS Localization: USA

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
After sequelAce is open for a while, opening new tabs and connecting to servers seems to take a while. This behavior disappears after the program is closed and re-opened

**Steps To Reproduce**
1. leave sequel ace open for a few days, using it's features as normal
2. opening tabs and connecting to dbs becomes slow until program is restarted

**Expected Behaviour**
Sequel Ace should not become noticeably slower the longer it's open

**Related Issues**

**Additional Context**

https://user-images.githubusercontent.com/2578041/129460705-e4725d91-4e61-4b9f-b1d2-32b0dfcfc645.mov

![sequel_ace_undo_bug_settings](https://user-images.githubusercontent.com/2578041/129460484-4bc860ce-1167-45ab-9cce-d63ed8698ab7.png)

**Comment by cristianovalenca** [comment]
Having the same problem, Mac M1 here

**Comment by Jason-Morcos** [comment]
Does it become faster again if you close all the windows and open a new window (without quitting the app)?

@Kaspik maybe a memory leak even with ARC?

**Comment by origamifreak2** [comment]
> Does it become faster again if you close all the windows and open a new window (without quitting the app)?
> 
> @Kaspik maybe a memory leak even with ARC?

The slowness doesn't seem to go away if I just close the window without quitting the app, but I only tested it when it was moderately slow. I'll wait and test again once the app gets a bit slower.

**Comment by Lenitr** [comment]
@origamifreak2 I see you have syntax highlighting enabled, could you try it without that turned on? 
Your issue might be related to https://github.com/Sequel-Ace/Sequel-Ace/issues/1071

**Comment by origamifreak2** [comment]
> @origamifreak2 I see you have syntax highlighting enabled, could you try it without that turned on?
> Your issue might be related to #1071

I turned syntax highlighting off and tried closing the program window without completely closing the program. It still remains slow until you completely restart.


00:00 - speed after being open for a little while
00:26 - speed after closing and re-opening window without restarting program
01:10 - speed after completely restarting

https://user-images.githubusercontent.com/2578041/131703001-4e4fa799-60ac-463d-b0e8-ce9e7ef50bfc.mp4

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all  This seems pretty memory-leaky. Does anyone have any tricks to try to figure out the root cause of a memory leak?

**Comment by clayreimann** [comment]
Can you connect instrumentation to a non-Xcode build? Otherwise, maybe just run a debug build to see what objects get allocated?

**Comment by origamifreak2** [comment]
> Can you connect instrumentation to a non-Xcode build? Otherwise, maybe just run a debug build to see what objects get allocated?

I don't know if you were specifically asking me, but I'm not very experienced with xcode or native mac program development (I'm mainly a web dev). I'm happy to try and get more debugging info though, so let me know if there's some more information I can give that would help.

**Comment by mfehr94** [comment]
I just changed default font to others, it becomes normal and very quick,  also We don't need to turn off syntax hightlighting

env:
Mac OS Big Sur v.11.5.2
sequal ace :v.3.4.0 build 3038
Apple cpu Intel
DB : Mysql

> > _Originally posted by @NeilSiao in https://github.com/Sequel-Ace/Sequel-Ace/issues/638#issuecomment-918657031_

**Comment by origamifreak2** [comment]
> I just changed default font to others, it becomes normal and very quick, also We don't need to turn off syntax hightlighting
> 
> env:
> Mac OS Big Sur v.11.5.2
> sequal ace :v.3.4.0 build 3038
> Apple cpu Intel
> DB : Mysql
> 
> > _Originally posted by @NeilSiao in [#638 (comment)](https://github.com/Sequel-Ace/Sequel-Ace/issues/638#issuecomment-918657031)_

The issue you quoted was about the query editor. The issue I'm having is with the overall UI getting slow. I don't know if they're related.

**Comment by origamifreak2** [comment]
> uncheck the syntax highlighting will solve the problem

I already tried this and it did not get rid of the problem. See my post here https://github.com/Sequel-Ace/Sequel-Ace/issues/1197#issuecomment-910418791

**Comment by waleed-dawood** [comment]
I had my SequelAce open for a couple of days and it was pretty slow and was using around 1GB of memory. I exited the program and reopened the tabs I wanted. The memory usage is under 200 MB. There seems to be a memory leak.

**Comment by robinkunde** [comment]
Just in general, please be aware that macOS Monterey is currently suffering from some memory that could be affecting you as well, especially the first one on this list: https://eclecticlight.co/2021/11/22/more-memory-leaks-in-monterey-12-0-1-how-to-avoid-them/

**Comment by verstratenbram** [comment]
> <img alt="sequel memory" width="288" src="https://user-images.githubusercontent.com/29309992/138281452-74d115d2-fd20-4651-b4b7-a608eb09d104.png">
> 
> I performed the same actions on 4 open tabs with connections to different databases.

Fyi, this was tested on macOS Big Sur.

**Comment by jordanade** [comment]
Oof
<img width="524" alt="Screen Shot 2022-06-27 at 1 05 27 AM" src="https://user-images.githubusercontent.com/2799445/175863900-0dd8bbbf-625e-44e0-aec2-36c7a951d0b2.png">
