### ISSUE TITLE
Wrong syntax used to change generated column

### ISSUE THREAD

**Issue by Synchro** [Sequel-Ace/Sequel-Ace#1198]
- Sequel Ace Version (including build number): 3.4.0 3038
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.5.2
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.26
- macOS Localization: en_GB

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
When changing a generated column, the generated SQL is incorrect, and the change fails.

**Steps To Reproduce**
1. Create a database with  table containing a generated field (in this example, the field contains the difference between two timestamps, in seconds):
```sql
CREATE DATABASE `sa`;
USE `sa`;
CREATE TABLE `a` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT), `created_at` timestamp NULL DEFAULT NULL, `added` timestamp NULL DEFAULT NULL, `duration` int unsigned GENERATED ALWAYS AS (timestampdiff(SECOND,`added`,`created_at`)) VIRTUAL;
```
2. Using Sequel Ace, make a change to the generated field, such as unchecking the nullable checkbox.

**Expected Behaviour**
The edit is accepted

**Actual Behaviour**
This is the query generated by Sequel Ace:
    ALTER TABLE `a` CHANGE `duration` `duration` INT  UNSIGNED  NOT NULL  VIRTUAL GENERATED   (timestampdiff(SECOND,`added`,`created_at`));

This results in an error:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VIRTUAL GENERATED   (timestampdiff(SECOND,`added`,`created_at`))' at line 1

I'm not entirely sure what the correct syntax is, but I think it should be:

    ALTER TABLE `a` CHANGE `duration` `duration` int unsigned GENERATED ALWAYS AS (timestampdiff(SECOND,`added`,`created_at`)) VIRTUAL;

**Comment by Jason-Morcos** [comment]
@gduh Do you want to look into this one? I know you've been tackling the generated column things :)

**Comment by gduh** [comment]
@Jason-Morcos Ok, I take it !
