### ISSUE TITLE
Switching tabs can be non-sequential

### ISSUE THREAD

**Issue by dnicolson** [Sequel-Ace/Sequel-Ace#1201]
- Sequel Ace Version (including build number): 3.4.0 (Build 3038)
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 11.5.2 (20G95)
- Processor Type (Intel/Apple): Intel
- MySQL Version: n/a
- macOS Localization: English

**Description**
Adding a new tab when the active tab is not in the last position results in the tabs switching out of order.

**Steps To Reproduce**
1. Add two tabs.
2. Select the first tab.
3. Add an additional tab.

**Expected Behaviour**

The tabs to be selected sequentially when using Option-Command-→.

![Screen Recording 2021-08-16 at 02 54 29 (3)](https://user-images.githubusercontent.com/2276355/129498491-0326410b-e519-4edf-8822-9f62f3704ac9.gif)

**Comment by Jason-Morcos** [comment]
This may be a weird macOS stabbing quirk. @Kaspik any idea here?
