### ISSUE TITLE
Feature request: Foreign key links in Query output

### ISSUE THREAD

**Issue by mscuthbert** [Sequel-Ace/Sequel-Ace#1204]
Where possible, it would be amazing to have the results table from a query include the arrow mark for jumping to a foreign key relation's table as it does in the Content tab.

For instance, here is the content page, with "composer_id" as a foreign key marked with an arrow:
<img width="597" alt="Screen Shot 2021-08-19 at 14 47 32" src="https://user-images.githubusercontent.com/3521479/130161857-28a1d557-d7b6-42f4-9cfa-5027e56ba123.png">

And a simple query on the same table with the results not including the foreign key link:
<img width="600" alt="Screen Shot 2021-08-19 at 14 48 05" src="https://user-images.githubusercontent.com/3521479/130161866-cda71d2e-bca9-4b40-8c04-b0c2929c341b.png">

I understand that there are innumerable query types that could make this not possible in all cases, but the straightforward cases of a single table or simple join being returned are what occupy 95% of the time spent copying a foreign key and looking it up in another table, etc.

Thanks! And thanks so much for continuing the Sequel Pro legacy in the project -- just learned about it today and I'm so happy about it!

**Comment by Jason-Morcos** [comment]
Interesting idea! I'm not sure how much of this is easily possible (I guess we'd need to query back the table create statements for any tables involved in the query? Could get wonky) but is a cool idea and I would definitely review a PR with this functionality if someone wants to explore this further.
