### ISSUE TITLE
Auto Increment field in Table Info Not Updated After Resetting Auto-Increment in MySQL 8.x

### ISSUE THREAD

**Issue by 9ae8sdf76** [Sequel-Ace/Sequel-Ace#1206]
- Sequel Ace Version: 3.4.0 (3038)
- Sequel Ace Source: Homebrew
- macOS Version: 11.5.1 (20G80)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.26
- macOS Localization: en_US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
N/A

**Description**
After emptying a table using a DELETE statement, switching to the Table Info tab and selecting the gear icon for Reset AUTO_INCREMENT, the value for Auto Increment does not update to the expected `0`. Number of Rows changes in that its value is prefixed with a tilde (`~`).

When creating new rows, the new row does seem to start over. So it seems localized to only the Table Info tab. The issue also persists between app restarts.

**Steps To Reproduce**
1. `DELETE FROM <table>;`
2. Switch to Table Info tab
3. Click the gear icon beside Auto Increment
4. Click on Reset AUTO_INCREMENT

**Expected Behaviour**
The Auto Increment field should be reset to `0` under Table Info.

**Related Issues**
Could not find any.

**Additional Context**
N/A

**Comment by Jason-Morcos** [comment]
@9ae8sdf76 If you run `SHOW VARIABLES` in the query editor, is information_schema_stats_expiry in the results anywhere?

**Comment by Jason-Morcos** [comment]
I believe I have this working in the latest release candidate (it's setting the value information_schema_stats_expiry=0 when initializing a connection). Please let me know if it does/doesn't work!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F3.4.1-3041
