### ISSUE TITLE
No response for the latest version

### ISSUE THREAD

**Issue by njuzss** [Sequel-Ace/Sequel-Ace#1208]
- Sequel Ace Version (including build number): 3.4.0 build 3038
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store&Homebrew
- macOS Version: big sur 11.4 (20F71)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.6.25
- macOS Localization: zh_CN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Y

**Description**
No Response

**Steps To Reproduce**
1.  Connected to a database
2. Open a table to browse, click the content tab
3. about 10s later, No response
![image](https://user-images.githubusercontent.com/9482171/130580617-d6f40592-7417-4af7-a9b9-f029b792277c.png)

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Very strange, @njuzss. Is there _any_ previous version of Ace that actually works? Which previous versions did you try?

**Comment by Jason-Morcos** [comment]
@njuzss Can you please try the latest beta and let us know if this issue is still present?
I might try using app cleaner to completely remove Sequel Ace and re-install just to give it a good clean chance. Thanks!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by Kaspik** [comment]
Any update here? If not, let's close it.
