### ISSUE TITLE
Connecting to Snowflake

### ISSUE THREAD

**Issue by taiwoayanleye** [Sequel-Ace/Sequel-Ace#1218]
Please add support for Snowflake.com databases.

Thank you.

**Comment by Jason-Morcos** [comment]
This probably isn't going to happen. We support MariaDB and MySQL, the two most popular relational databases. Snowflake is pretty different connection-wise and with such a small user base is not a priority at this time.
If someone is interested in adding this support personally as a PR, reach out and we'd be happy to try to help you do so.
