### ISSUE TITLE
Scrolling Horizontally on a table content

### ISSUE THREAD

**Issue by tomjamon** [Sequel-Ace/Sequel-Ace#1228]
- Sequel Ace Version (including build number): 3.4.0 3038
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.5.2
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.34
- macOS Localization: N/A

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes.

**Description**

Hi, i'm sorry if this bug has already been notified but i couldn't find any issue related to this problem, even if it should occure to a lot of people ?
I can't scroll horizontally on macOS, on a table with 15-20 columns. I can only see the first 8-10 columns.
I have a vertical scrollbar but not a horizontal one.
I tried shortcut + mouse moving, arrows key, move mouse to the right, nothing seem to work for me.
I miss something maybe ?

Thank for your time.
Tom.

**Steps To Reproduce**
1. Install on macOS
2. Open a table with at least 15 columns
3. Try to scroll right, to see the next columns

**Expected Behaviour**
Be able to scroll left/right to see the other columns

**Related Issues**
None.

**Additional Context**
None.

**Comment by Jason-Morcos** [comment]
I can't reproduce this! I have no issues horizontally scrolling with my trackpad. I don't have a mouse to test with though. Are you able to horizontally scroll in other apps like Safari (on a zoomed in webpage)?

**Comment by TiDJ** [comment]
The only way for me is to click on an empty space, and then move the mouse on a side (while keeping left click down).
Otherway the Scrollbar won't show up and i couldn't see the remaining columns on the right.

That's why i can see all columns only on a table with not to much entries.

**Comment by MACscr** [comment]
I have have the same issue on my mac desktop as well. I use a windows keyboard and mouse, so no trackpad option. Horizontal scrollbar never shows.

**Comment by samuelbradshaw** [comment]
I don't have a mouse to test, but from reading a few places online, you might be able to scroll horizontally by holding shift while using the scroll wheel on your mouse. Does that work?

**Comment by MACscr** [comment]
Awesome, shift does work. Odd that its needed, but good enough for now. Thanks!

- Mark

**Comment by jjcsinke** [comment]
Same issue here, was 'scrolling' by selecting a field and tabbing to out-of-screen fields.
Scrolling with shift does work (thanks for that comment!) but a horizontal scrollbar that does not hide would be nice.
Scrollbar pops up when shift-scrolling so maybe it just needs an always-show toggle.

**Comment by Jason-Morcos** [comment]
PR welcome to try to address the scroll bar showing up! I think most users use macOS with a trackpad

**Comment by Kaspik** [comment]
> Same issue here, was 'scrolling' by selecting a field and tabbing to out-of-screen fields. Scrolling with shift does work (thanks for that comment!) but a horizontal scrollbar that does not hide would be nice. Scrollbar pops up when shift-scrolling so maybe it just needs an always-show toggle.
> 
> ---edit: It is related to this setting in system preferences, but I guess most content and screens are designed for responsive and vertical scroll only so I don't notice other than my in my large tables.
> 
> <img alt="Screenshot 2022-11-21 at 13 17 37" width="711" src="https://user-images.githubusercontent.com/19775698/203052963-716a2ec4-6195-4d03-a55e-996c19de3603.png">

Exactly this settings is where you need to change the "Show scroll bars" to the first option. I don't think any PR is needed here, we use native components that behave how native API tells them to, so in this case there is nothing we can do really imo.

**Comment by axelf** [comment]
Hi, it's not working again. After changing the settings for "Show scroll bars" nothing happend. There is no horizontal scrollbar.

OS: Sequoia 15.2.
Sequel Ace: Version 4.1.7

In older versions i used horizontal scrolling
