### ISSUE TITLE
MySQL said: Malformed packet

### ISSUE THREAD

**Issue by outer199** [Sequel-Ace/Sequel-Ace#123]
- Sequel Ace Version: 2.1.0 Build 2042
- macOS Version: 10.15.5 (19F101)
- MySQL Version: 5.7.28

Connect to mysql via SSH

**Description**
![image](https://user-images.githubusercontent.com/23118182/85917525-4b36bf00-b88d-11ea-8ee3-cbbaecc6e723.png)

**Comment by ouer1994** [comment]
Connect to mysql via SSH

**Comment by jamesstout** [comment]
Can you connect ok with workbench?

**Comment by gboudreau** [comment]
When exactly do you get that error? When you connect, or when you select a table?

**Comment by gboudreau** [comment]
Try other tables, try other clients (command-line or MySQL Workbench, execute `SHOW CREATE TABLE table_name_here;`).

**Comment by ouer1994** [comment]
when i select a table, it happended. local mysql tables is fine, but online table report errors! 
Sequel Pro is fine. it worked well.

**Comment by ouer1994** [comment]
@jamesstout 
Sequel Pro worked well. only Sequel Ace reported errors.

**Comment by Jason-Morcos** [comment]
Hi @ouer1994, I understand the issue occurs when you select a table. Does it happen for all tables, or just a specific table(s)? If just specific tables, are there any special characters or things things that make the crashing tables special? 
What happens if you go to the query editor and run `SHOW CREATE TABLE table_name_here;` replacing table_name_here with the name of one of your tables that is crashing when you select it? If this doesn't error, could you share the result of what this returns?

**Comment by ouer1994** [comment]
@Jason-Morcos 
Hi, 
 just a specific table(s) reports error. there are two errors: 
1. Malformed packet
2. Unknown MySQL error

local tables is fine. but remote tables appear error.
 
![image](https://user-images.githubusercontent.com/23118182/85935517-6f91aa80-b924-11ea-9571-ac801732b4fe.png)
![image](https://user-images.githubusercontent.com/23118182/85935530-90f29680-b924-11ea-973d-8b3e804ee9cb.png)

**Comment by Jason-Morcos** [comment]
I really wish we logged out the error code itself too... Future addition there I guess
What do you mean by "local" and "remote" tables? I'm unfamiliar with this concept. Are you saying it works when connected to your local _database_ but not for a remote _database_? Or are these different types of tables in the same database somehow?

**Comment by ouer1994** [comment]
@Jason-Morcos 
> Are you saying it works when connected to your local database but not for a remote database? 


Yes

**Comment by Jason-Morcos** [comment]
@ouer1994 Is there any chance your local database and remote databases are different versions or MySQL or anything of the sort? Perhaps your local database is standard MySQL and your remote in Aurora DB?

**Comment by ouer1994** [comment]
@Jason-Morcos 

No, local database version is 5.7.21 , remote database version is 5.7.28. they are both standard MySQL installed by myself. 
this is the mysql error log :
`Aborted connection 21452 to db: 'XXX' user: 'XXX' host: '127.0.0.1' (Got an error reading communication packets) `

**Comment by Jason-Morcos** [comment]
@ouer1994 What happens if you run `SHOW CREATE TABLE migrations;` on your remote DB in a tool like MySQL Workbench? Does it error there too?
https://www.mysql.com/products/workbench/

**Comment by ouer1994** [comment]
@Jason-Morcos 

No error. Everything is fine.

**Comment by stychos** [comment]
I have these entries in the log caused by the replica which is located at another side of the Earth and its connection is wrapped into VPN. Looks like connectivity issues, but then it's strange that other tools works fine.

**Comment by jamesstout** [comment]
What are encodings for the database and the table? The app uses utf8 as default, but if a table has a different encoding it reconnects. could be a cause of networks issues?

**Comment by outer199** [comment]
@jamesstout 
utf8mb4

**Comment by outer199** [comment]
version 2.1.1 fixed.

**Comment by mpyw** [comment]
Version 2.1.7 still reproduces
