### ISSUE TITLE
"View Tab Bar" option not preserved between window restarts

### ISSUE THREAD

**Issue by brandoningli** [Sequel-Ace/Sequel-Ace#1231]
- Sequel Ace Version (including build number): 3.4.1 build 3041
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: n/a
- macOS Localization: US English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No beta since this release.

**Description**
Tab bar appears on app start when "View Tab Bar" was selected and app was quit, but doesn't show when it was selected and a new window is launched of a running app.

**Steps To Reproduce**
1. Open App
2. `View` > `Show Tab Bar`
3. Verify that the tab bar shows.
3. `File` > `New Connection Window`
4. Verify that tab bar does not show on the new window.
5. Close all windows, but don't quit app.
6. Open new window.
7. Verify that tab bar does not show.
8. Quit app.
9. Open new window.
10. Verify that tab bar shows.

**Expected Behaviour**

Tab bar should show whenever a new window is created if that setting was selected.

**Related Issues**

N/A

**Additional Context**

![image](https://user-images.githubusercontent.com/6826623/135378688-acc8e8e1-6495-4c81-a711-846a80ada015.png)

**Comment by Jason-Morcos** [comment]
I believe that that's standard behavior for a macOS app to not preserve one window's "View Tab Bar" setting when a new window is opened. I think the option you're thinking of is "Always Show Tab Bar". @Kaspik is this menu option a simple add with modern tabbing or is it more complex?

**Comment by Kaspik** [comment]
I guess it would be easy to add, or to check latest window's settings, but not actually sure.

**Comment by brandoningli** [comment]
(Adding a comment to keep this thread alive.)
