### ISSUE TITLE
"Dark" theme shows Query Editor and Table Info textfields as BRIGHT WHITE backgrounds

### ISSUE THREAD

**Issue by briantully** [Sequel-Ace/Sequel-Ace#1232]
- Sequel Ace Version (including build number): 3.4.1 Build 3041
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.14.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.3
- macOS Localization: US English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
 Yes issue is present in latest beta

**Description**

When dark theme is selected there are still important tabs (Query Editor, Table Info) that contain large text fields with bright white backgrounds, which are very uncomfortable to the eye in relation to the rest of the dark UI. Sequel Pro's dark theme does not have this problem so I'm wondering why a decision was made to change the field backgrounds to bright white?

**Steps To Reproduce**
1. Open Sequel Ace
2. In Sequel Ace's Preferences, change to Appearance to "Dark" theme
3. Connect to a DB and click on the "Query" tab 
4. Note that the Query Editor has a LARGE BRIGHT WHITE BACKGROUND!
5. Select a table and click on "Table Info" tab
6. Note the "Create syntax" field has a LARGE WHITE BACKGROUND!

**Expected Behaviour**

I expect that the Dark appearance theme would show all aspects of the UI, including text fields, with dark backgrounds. Some text fields do have dark backgrounds. Perhaps it is only the text fields that have syntax highlighting that are affected?
Sequel Pro has dark backgrounds even on the fields with syntax highlighting. I was under the impression that Sequel Ace was a "fork" of Sequel Pro -- if that's the case, why change those text fields? If that's not the case, do you have any plans on updating the syntax highlighted field library so that it is compatible with dark backgrounds?

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
See https://github.com/Sequel-Ace/Sequel-Ace/issues/145, https://github.com/Sequel-Ace/Sequel-Ace/issues/312

**Comment by briantully** [comment]
Thank you! Sorry I didn't notice that the Query Editor had themes at the bottom left of the window. Switched from default to Monokai and now my eyes are relieved.

Thank you so much for all you do! :D
