### ISSUE TITLE
Import Global Query Favorites from Sequel Pro

### ISSUE THREAD

**Issue by briantully** [Sequel-Ace/Sequel-Ace#1234]
I've seen plenty of Google results for importing connection favorites from Sequel Pro to Sequel Ace, but nothing on how to import global "query favorites" from Sequel Pro to Sequel Ace.

https://sequel-ace.com/favorites.html is great documentation for why query favorites are useful and how to create one, but it doesn't demonstrate how to import all global query favorites from Sequel Pro to Sequel Ace. Is this possible?

Query favorites was probably my most used feature in Sequel Pro, and over the years I've compiled a ton of my most used queries and saved them as global query favorites. There are probably over a hundred.

Upon upgrading/migrating from Sequel Pro to Sequel Ace, it's unclear on how I can migrate/import all of those global query favorites, as they do not appear to be stored on disk, i.e., within ~/Library/Application Support/Sequel Pro/. Any idea where these are stored?

I can see that in both Sequel Pro and Sequel Ace I can edit Query Favorites and then export a single query favorite, but I'm hoping/praying that there is an easier/faster way to export/import ALL global query favorites.

Any ideas?

At the very least it might be helpful to document and explain the query favorites import/export process for those migrating from Sequel Pro to Sequel Ace, much like in how you've done for Connection Favorites.

Thanks!

**Comment by Kaspik** [comment]
We have migration docu here - https://sequel-ace.com/get-started/migrating-from-sequel-pro.html

It doesn't talk about the query favorites tho - so could be improved. :)

**Comment by clayreimann** [comment]
Does point `5` not address this?
> Copy ~/Library/Application\ Support/Sequel\ Pro/Data/Favorites.plist to ~/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application\ Support/Sequel\ Ace/Data/Favorites.plist
