### ISSUE TITLE
Sequel-Ace 3.4.1 keeps randomly freezing while browsing content or query results.

### ISSUE THREAD

**Issue by kozie** [Sequel-Ace/Sequel-Ace#1235]
- Sequel Ace Version (including build number): 3.4.1 build 3041
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 11.4
- Processor Type (Intel/Apple): Quad-core Intel Core I5
- MySQL Version: Various
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

No newer beta available.

**Description**
Application keeps freezing randomly while trying to browse any query results. Both from the 'content' and 'query' tabs.
The steps aren't really precise as i couldn't find a pattern but just browsing, scrolling and selecting different rows or cells will result in the freeze.

Eventually i have to force quit the application and restart again which makes the application unbearable to work with. Going back a version isn't an option since it has allot of (re)connection issues.

**Expected Behaviour**

Clearly that would be for the application to not freeze so often and randomly.

**Related Issues**

Couldn't find one.

**Additional Context**

No crash logs to be found. Instruct me where to possibly find those if possible and needed.

**Comment by Jason-Morcos** [comment]
I think the freezing is likely related to reconnecting to your SSH connections. While we were able to significantly improve the reconnection ability in 3.4.1, it's probably trying to reconnect just as often and going through quite a bit of overhead to do the actual reconnection. PRs aimed at improving this are very much welcome!

**Comment by eduo** [comment]
A note here which may be useful: I hadn't migrated to Sequel Ace from Sequel Pro. I decided to do it today because this started happening importantly around a week or so ago there.

Whatever is causing it exists since the original codebase and seems to have been triggered by a MacOS update.

I have noticed it mostly when I'm in the query editor and queries start getting long (it never happened before) but also to a lesser degree in the table content browser.

Copying a few hundred rows as insert and pasting that into the query editor causes this freezing immediately.

**Comment by Jason-Morcos** [comment]
> A note here which may be useful: I hadn't migrated to Sequel Ace from Sequel Pro. I decided to do it today because this started happening importantly around a week or so ago there.
> 
> Whatever is causing it exists since the original codebase and seems to have been triggered by a MacOS update.
> 
> I have noticed it mostly when I'm in the query editor and queries start getting long (it never happened before) but also to a lesser degree in the table content browser.
> 
> Copying a few hundred rows as insert and pasting that into the query editor causes this freezing immediately.

Thanks for the info!
Regarding the query editor slowness, see https://github.com/Sequel-Ace/Sequel-Ace/issues/1071. Some people have had success changing the font.

**Comment by Kaspik** [comment]
Still having issues on new 4.0.0?
