### ISSUE TITLE
Add Files button does not work with red bookmarks

### ISSUE THREAD

**Issue by dnicolson** [Sequel-Ace/Sequel-Ace#1239]
- Sequel Ace Version (including build number): 3.4.1 (build 3041)
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 11.6 (20G165)
- Processor Type (Intel/Apple): Intel
- MySQL Version: n/a
- macOS Localization: English

**Description**
The "Add Files" button does not work until the bookmarks in red are removed.

![Sequel Ace add files doesn't work when red](https://user-images.githubusercontent.com/2276355/136268111-190e99af-951e-4f87-9f2c-2846932c4193.gif)

**Steps To Reproduce**
1. Add directory in Preferences > Files
2. Remove directory
3. Open Sequel Ace
4. Click Add Files

**Expected Behaviour**
For the button to work, the red bookmark needs to be removed first.

**Comment by dnicolson** [comment]
I'm not sure I fully understand, I just did a small test building from Xcode and I added three directories, removed them in Finder, built the app again and I was able to invoke the modal.

Also, you can invoke the modal if a red bookmark is selected. Unless there is something else I'm missing, wouldn't disabling the "Add Files" button in such a case be a better option?

As an aside, I made similar changes to the previously mentioned test and it resulted in duplicated entires but maybe that is related to #1238.

**Comment by Jason-Morcos** [comment]
Maybe we could tweak the add files button to pop up an alert explaining the behavior at least? "Please remove or restore (double click) expired bookmarks before creating new ones" or something?

**Comment by dnicolson** [comment]
The problem here is that the “Add Files” button duplicates the functionality of double-clicking a stale bookmark, but only if there is at least one stale bookmark. It was added [here](https://github.com/Sequel-Ace/Sequel-Ace/commit/8afb2cf049cd500649342fd2859033aad8736e8b#diff-03aac764327ea88af64909ab6409bfdca43e091521ced365699365fc3b4dfbf1R385-R391) amongst other changes.

This changes the functionality of the "Add Files" button depending on the state of the bookmarks, and also allows the use of the "Add Files" button but not after clicking on the table, which doesn't seem intentional.
