### ISSUE TITLE
Better overview of the shortcuts

### ISSUE THREAD

**Issue by cafferata** [Sequel-Ace/Sequel-Ace#124]
I would suggest putting the shortcuts in a Markdown table for a better overview.

|Before|After|
|---|---|
|<img width="544" alt="before" src="https://user-images.githubusercontent.com/1150425/85929978-04f75500-b8b9-11ea-8057-d49f87cacfdf.png">|<img width="544" alt="after" src="https://user-images.githubusercontent.com/1150425/85929977-0294fb00-b8b9-11ea-9e01-41d967cb6110.png">|

**Comment by Jason-Morcos** [comment]
Love it! Deployed @cafferata https://sequel-ace.com/shortcuts.html

**Comment by cafferata** [comment]
Personally, I don't like the fact that Github pages align them centered tables. See the next merge request https://github.com/Sequel-Ace/Sequel-Ace/pull/126 that fixes that problem.
