### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by UlrichThomasGabor** [Sequel-Ace/Sequel-Ace#1240]
- Sequel Ace Version (including build number): Version 3.4.1 Build 3041
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.35
- macOS Localization: German

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Crash

**Steps To Reproduce**
Unsure. I guess something connected to the ssh reconnection issue. This was a window open for a long time, where I wanted to do something.

**Additional Context**
[crashlog.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/7300905/crashlog.txt)

**Comment by Kaspik** [comment]
I'm gonna close this, a lot has changed since then.
