### ISSUE TITLE
3.4.1 introduces a SET command that can not be disabled (incompatible with ProxySQL)

### ISSUE THREAD

**Issue by kattlynn777** [Sequel-Ace/Sequel-Ace#1241]
When trying to use 3.4.1 with ProxySQL we are now getting:
ProxySQL Error: connection is locked to hostgroup 1 but trying to reach hostgroup 2

Believe it is related to SET commands that are not possible to be disabled:
[self queryString:@"SET information_schema_stats_expiry=0"];

Can these be built into a setting so this GUI is compatible with ProxySQL?

**Comment by Jason-Morcos** [comment]
> ... and perhaps generally have visibility and control of the commands getting sent to the server.

Also, you can view all commands sent to the server in the console in Sequel Ace.

**Comment by kattlynn777** [comment]
![Screen Shot 2021-10-13 at 1 30 47 PM](https://user-images.githubusercontent.com/3434669/137192697-5c9c22bb-e9c0-47b4-9d4c-654a5d9b597c.png)

Confirmed I could see the SET command running in the console.

**Comment by Jason-Morcos** [comment]
> Does this screenshot work, or do you need to see more of the application?

Hi, I would like to see a little more if possible, at least to see the full window so I can tell what view the error is being thrown from
