### ISSUE TITLE
Resetting to default DB after five minutes

### ISSUE THREAD

**Issue by JonasEklundh** [Sequel-Ace/Sequel-Ace#1254]
- Sequel Ace Version (including build number): Version 3.4.1 Build 3041
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Big Sur 11.6
- Processor Type (Intel/Apple): M1
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- macOS Localization: English (Swedish keyboard)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
I'm running the AppStore version though...

**Description**
Sequel Ace is resetting to the default database when idle, or intemittingly when using the app. In the console, I see - without user interaction:
/* 10:29:33 Glesys log */ SHOW COLUMNS FROM `post_data`;
/* 10:34:00 Glesys log */ SHOW VARIABLES;
/* 10:34:00 Glesys log */ SELECT @@global.max_allowed_packet;
/* 10:34:00 Glesys log */ USE `atlas`;

The first log entry is me selecting the db/table log.post_data, then five minutes later, Sequel Ace issues a reset and "USE atlas" without user interaction but still log it as "log" being the active DB.

**Comment by JonasEklundh** [comment]
I'll try to explain, from the Sequel Ace console log:

10:29:33 Glesys log SHOW COLUMNS FROM post_data;

This is me selecting the log.post_data table, via the UI

10:34:00 Glesys log SHOW VARIABLES;
10:34:00 Glesys log SELECT @@global.max_allowed_packet;
10:34:00 Glesys log USE atlas;

About five minutes later without any UI/user interaction, this happens in the console, where Sequel Ace have run these three commands while idle, which resets the DB used, so when I come back to the app to list posts, I will get a dialog saying "there is no 'post_data' table in 'atlas'" even though the UI still shows the "log" db to be selected

**Comment by jtylr** [comment]
I've seen a similar thing happen whilst being connected via a proxy. If the proxy loses connection and then reconnects, I occasionally get set back to the default database.

**Comment by JonasEklundh** [comment]
> I've seen a similar thing happen whilst being connected via a proxy. If the proxy loses connection and then reconnects, I occasionally get set back to the default database.

No proxy here though, and this happens all the time, sometimes I have to reselect the DB for every action I'm doing almost, it's quite irritating

**Comment by Kaspik** [comment]
Is this still happening?

**Comment by JonasEklundh** [comment]
> Is this still happening?

Yup
