### ISSUE TITLE
Migrating from Sequel Pro: Couldn't connect via ssh (fixed)

### ISSUE THREAD

**Issue by onassar** [Sequel-Ace/Sequel-Ace#1264]
Hi all -
Since we all naturally search google / issues to see who has one similar to their own, I've decided to submit this and close it right away. Prob not the right place, but hopefully it helps other people.

I was switching over (because of a MySQL server upgrade that was out of my hands). I kept running intro strange prompts for my ssh password. In the end, here's what fixed my problem:

``` bash
touch ~/.ssh/config
```

Yeh.. that's it. I'm working on a new machine, which didn't have a config file in the `~/.ssh` directory. Creating an empty one fixed the issue for me.

🤷

**Comment by geoidesic** [comment]
Didn't work for me. I was also missing a `~/.ssh/config` after an OS re-install... but adding an empty one didn't help any.
