### ISSUE TITLE
Connect via SSH using socket on remote machine

### ISSUE THREAD

**Issue by alexkuc** [Sequel-Ace/Sequel-Ace#1266]
This is rather a question than a request specifically. I would like to connect via socket on remote SSH machine. Is this supported? When choosing `SSH` tab for connection type, I can see user/password fields but I believe it is not possible to specify socket?

**Comment by e-gaulue** [comment]
👍 

Google shows more and more requests on it and it is supported by more and more clients (sequel pro).

As far as I've seen, doesn't look hard to do: create a kind of port forwarding but working with sockets instead of ports (so you need to provide the path to the remote sock): 
```
ssh -L /tmp/local-mysql.sock:/var/run/mysqld/remote-mysqld.sock sshuser@remotehost
mysql -h localhost --protocol=SOCKET -S /tmp/local-mysql.sock -u'username' -p'mypassword'
``` 
Should be even easier than connect to a local server socket (due to sandbox limitation).

Sorry, I've have strictly no time to spend on it, I already work on too much projects.

Regards,

**Comment by e-gaulue** [comment]
Just tried from the command line, with the brew mariadb client and it works:
```
$ mariadb -h localhost --protocol=SOCKET -S /tmp/mysql.sock -u'pipo'
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 97
Server version: 10.5.12-MariaDB-0+deb11u1 Debian 11

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye
``` 

If I try through sequel while ssh unix socket tunnel is still active and giving the path of the socket: it doesn't work.
![Capture d’écran 2021-11-03 à 15 00 42](https://user-images.githubusercontent.com/4291874/140074533-0c4b9631-c459-4ea3-a503-ba8460220c95.png)
![Capture d’écran 2021-11-03 à 15 03 24](https://user-images.githubusercontent.com/4291874/140074744-fc4a68fc-3021-4e2f-841f-09bc444ccc68.png)

Shame...

**Comment by Jason-Morcos** [comment]
> Just tried from the command line, with the brew mariadb client and it works:
> 
> ```
> 
> $ mariadb -h localhost --protocol=SOCKET -S /tmp/mysql.sock -u'pipo'
> 
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> 
> Your MariaDB connection id is 97
> 
> Server version: 10.5.12-MariaDB-0+deb11u1 Debian 11
> 
> 
> 
> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
> 
> 
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> 
> 
> MariaDB [(none)]> exit
> 
> Bye
> 
> ``` 
> 
> 
> 
> If I try through sequel while ssh unix socket tunnel is still active and giving the path of the socket: it doesn't work.
> 
> ![Capture d’écran 2021-11-03 à 15 00 42](https://user-images.githubusercontent.com/4291874/140074533-0c4b9631-c459-4ea3-a503-ba8460220c95.png)
> 
> ![Capture d’écran 2021-11-03 à 15 03 24](https://user-images.githubusercontent.com/4291874/140074744-fc4a68fc-3021-4e2f-841f-09bc444ccc68.png)
> 
> 
> 
> Shame...

This comment isn't related to connecting via SSH and hence is not relevant to this issue. Please see the more general socket issue instead https://github.com/Sequel-Ace/Sequel-Ace/issues/113. _This_ issue is a feature request for _remote_ socket support.

**Comment by e-gaulue** [comment]
Yes it may. I read #113 too fast and thought it was a file access trouble when trying to access a local mysql server instance socket. As I though I was in another context, I gave it a try. Indeed, it looks to be a larger access trouble.

As I said, I'm really not specialised in Xcode devs, but it would look strange to me a process can't access a socket it  creates himself. As far as I understand in #113, people tries to access an existant socket. But maybe, in this context: "Sequel create itself the socket as a remote ssh socket and then consume it", it would work. I don't know exactly what sandboxes imply.

Regards,
