### ISSUE TITLE
Sort by Descending first

### ISSUE THREAD

**Issue by djmarland** [Sequel-Ace/Sequel-Ace#1267]
When I click a column header to sort, it sorts ASC first, then I click again to sort DESC. For big tables this can be slow as you have to wait for the ASC to finish (or cancel it) before you can switch to DESC.

For the overwhelming majority of cases I'm sorting I need to use DESC, most often to find the latest entries from a date field.

Would it be possible for there to be a setting to sort DESC first, then ASC on second click?

Thanks

**Comment by Undo1** [comment]
If you hold shift while clicking the column sort, it'll go to DESC immediately.

**Comment by djmarland** [comment]
You've just changed my life. Problem solved. Thank you.

**Comment by salvor-hardin** [comment]
> If you hold shift while clicking the column header, it'll go to DESC immediately.

Nice, that’s a great solution, definitely a fix.

If the implementation effort to toggle the default were to be low , I think this still would help anyway for people not aware of this.
