### ISSUE TITLE
Too bright when the background of tag is yellow or green

### ISSUE THREAD

**Issue by chenxinlong** [Sequel-Ace/Sequel-Ace#127]
Hi, I think it's too bright when the background of the tag is yellow or green. Like the pics below :

![image](https://user-images.githubusercontent.com/9261954/85938778-bbebe300-b942-11ea-9c25-2cfd55837000.png)

![image](https://user-images.githubusercontent.com/9261954/85938802-ee95db80-b942-11ea-805f-f5a441e01fe7.png)

I can hardly read the text on it.

**Comment by Jason-Morcos** [comment]
How does this look @chenxinlong?
https://github.com/Sequel-Ace/Sequel-Ace/pull/132

**Comment by chenxinlong** [comment]
It is much better. 👍
