### ISSUE TITLE
I need the who query time, not only the first row get time...

### ISSUE THREAD

**Issue by zwszwszws** [Sequel-Ace/Sequel-Ace#1270]
This version only display the first row get time, not the whole query time.
expect 6s,thanks.
![image](https://user-images.githubusercontent.com/27600135/139531783-efc97d53-baa5-4618-899d-e28973f2f798.png)

**Comment by Jason-Morcos** [comment]
Please fill out the full issue template when submitting a bug. Incomplete issues are closed as we simply don't have the bandwidth to investigate them.

Additionally, Sequel Ace is currently capable of only showing the _results_ from _one_ query at a time, but those results can be multiple rows.
