### ISSUE TITLE
MariaDB 10.5.12: cannot grant db privileges: View 'mysql.user' references invalid table

### ISSUE THREAD

**Issue by robertoschwald** [Sequel-Ace/Sequel-Ace#1278]
- Sequel Ace Version (including build number): 3.4.2 Build 3043
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store and GitHub tried. Same error.
- macOS Version: 11.6.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.5.12
- macOS Localization: de

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** 
It is latest version.

**Description**
In MariaDB 10.5.12 (in my case Galera Cluster with 3 nodes), it is impossible to grant db privileges.
I get error:
View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them

**Steps To Reproduce**
1. Create a db user
2. Try to grant all rights to any db 

**Expected Behaviour**
Grants are stored

**Additional Context**
SQL Log for the operation:
UPDATE mysql.user SET max_questions = 0, max_updates = 0, max_connections = 0 WHERE User = 'myuser' AND Host = '%';
FLUSH PRIVILEGES;

mysql.user is a view since 10.4, not a table.

**Comment by Jason-Morcos** [comment]
Do you have any idea what the proper way to grant someone DB privileges in 10.4+ is? We can try to tweak Ace to work in a more compatible way but only if we know what the _proper_ way now is

**Comment by robertoschwald** [comment]
Using GRANT is the proper way. It always was.

https://mariadb.com/kb/en/grant/
