### ISSUE TITLE
sytax highlighing make bad performance

### ISSUE THREAD

**Issue by vitock** [Sequel-Ace/Sequel-Ace#1281]
- Sequel Ace Version (including build number):Version 3.4.2Build 3043
- Sequel Ace Source (App Store/GitHub/Homebrew):APP store
- macOS Version:11.3.1
- Processor Type (Intel/Apple): intel
- MySQL Version: 
- macOS Localization:Chinese

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
YES

**Description**
**Steps To Reproduce**
1. type in   about 10 sql in query editor . 
2. edit sql ,you will find that it taks nearly 0.5s to show the charactars after your tying.
3. turn sytax hilighling off, it  performs good .

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Duplicates #1071
Please try the workaround. https://github.com/Sequel-Ace/Sequel-Ace/issues/1071#issuecomment-920715675
