### ISSUE TITLE
"Copy as SQL INSERT" includes generated columns

### ISSUE THREAD

**Issue by fubar** [Sequel-Ace/Sequel-Ace#1282]
- Sequel Ace Version (including build number): 3.4.2, Build 20016
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.12
- macOS Localization:

**Description**
When exporting entire tables, the "Include GENERATED columns" option works fine. However, when using the "Copy as SQL INSERT" feature on individually selected rows, it still includes generated columns.

**Steps To Reproduce**
1. Create a table with a generated column
2. Create a record
3. Right click the record and select "Copy as SQL INSERT"
4. Run the copied SQL

**Related Issues**
https://github.com/Sequel-Ace/Sequel-Ace/pull/1155

**Comment by gduh** [comment]
@Jason-Morcos The context menu includes these 2 elements :
- "Copy as SQL INSERT"
- "Copy as SQL INSERT (no aut inc)"
Should we add a new element with "Copy as SQL INSERT (no generated columns)"
I think this is not the right way, maybe we should keep only one element but then we should display a new window on which it will be possible to select zero, one or severals options : no but inc, no generated columns, others....
What do you think ?

**Comment by gduh** [comment]
Agree with that. I make the change !

**Comment by fubar** [comment]
That was my expectation as well. Thanks all!

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now! @gduh did some great work on this one!

https://github.com/Sequel-Ace/Sequel-Ace/releases
