### ISSUE TITLE
发生错误 “Format SQL”: /bin/bash: /usr/bin/php: No such file or directory

### ISSUE THREAD

**Issue by h3idan** [Sequel-Ace/Sequel-Ace#1285]
- Sequel Ace Version (including build number):Version 3.4.2 Build 3043
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 12.0.1 
- Processor Type (Intel/Apple): Inter
- MySQL Version: mysql 8.0.26
- macOS Localization: Chinese

**Description**
发生错误 “Format SQL”: /bin/bash: /usr/bin/php: No such file or directory

**Comment by Kaspik** [comment]
Duplicate - https://github.com/Sequel-Ace/Sequel-Ace/issues/1227
