### ISSUE TITLE
timestamp tooltips are not visible completely

### ISSUE THREAD

**Issue by albertborsos** [Sequel-Ace/Sequel-Ace#1290]
- Sequel Ace Version (including build number):  Version 3.4.2 Build 20016
- Sequel Ace Source (App Store/GitHub/Homebrew): AppStore
- macOS Version: 12.0.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: mariadb 10.4.13
- macOS Localization: english

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes

**Description**

Tooltip content over timestamps are not always visible:
![Képernyőfotó 2021-11-19 - 13 01 29](https://user-images.githubusercontent.com/7307145/142621682-4255cbfd-8992-43cc-9ac2-251bcec3b566.png)
Hours, minutes and seconds are missing. Sometimes. Sometimes are OK.

**Steps To Reproduce**
1. find a timestamp column
2. hover your cursor over a timestamp

**Expected Behaviour**
DateTimes should be visible completely.

**Comment by Jason-Morcos** [comment]
Does this only happen when MacOS Dark Mode is enabled or is it not color-scheme dependent?

**Comment by gduh** [comment]
Same issue.
It does not occur only for timestamp but also for others types. Perhaps, because of the space character (?). But not always, it's quite strange.
I'll try to take a look !

**Comment by albertborsos** [comment]
I can reproduce it with the light theme too:
![Képernyőfotó 2021-11-23 - 15 38 37](https://user-images.githubusercontent.com/7307145/143044540-3a1c766c-625b-4582-bed0-d2ff0aa0ee14.png)
