### ISSUE TITLE
Incorrectly displaying data on table's charset vs column collation charset

### ISSUE THREAD

**Issue by salvor-hardin** [Sequel-Ace/Sequel-Ace#130]
- Sequel Ace Version: 2.1.0
- macOS Version: 10.15.5
- MySQL Version: 5.7.30

Description
Data displayed on a table should be using character set by collation of the column, not by the table charset.

Steps To Reproduce
CREATE TABLE t_utf8_utf8 (
value varchar(128) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO t_utf8_utf8 (value)
VALUES
('Apple iPhone アクセサリ');

t_utf8_utf8
![image](https://user-images.githubusercontent.com/40695717/85948859-0a04e480-b94b-11ea-8b23-20892f97f607.png)
CREATE TABLE t_utf8_latin (
value varchar(128) CHARACTER SET utf8 NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO t_utf8_latin (value)
VALUES
('Apple iPhone アクセサリ');

t_utf8_latin
![image](https://user-images.githubusercontent.com/40695717/85948861-0d986b80-b94b-11ea-8e61-ce99dadcbe83.png)

You should see the same on both tables, as the table or the column is defined as uft8, however the client prints ??? for the Japanese characters (probably using the table charset for all the contents vs the COLLATED charset) when utf8 is the collation of the column but latin1 the charset of the table.

Expected Behaviour
I expect to see the same info on both tables.

Additional Context

Including screenshots.

**Comment by jamesstout** [comment]
Got something working. But I need to learn a lot more about connection encoding before releasing it.

![Screenshot 2020-06-30 at 2 25 08 PM](https://user-images.githubusercontent.com/1576190/86091031-c42c5580-badd-11ea-818d-7d298d392574.png)
Note the table encoding is still latin1.

Testing a few other encodings...

![Screenshot 2020-06-30 at 2 25 12 PM](https://user-images.githubusercontent.com/1576190/86091089-e1612400-badd-11ea-8d2e-8c7de7b76abe.png)
![Screenshot 2020-06-30 at 2 25 16 PM](https://user-images.githubusercontent.com/1576190/86091100-e45c1480-badd-11ea-8799-2bed5adbfe71.png)
![Screenshot 2020-06-30 at 2 25 19 PM](https://user-images.githubusercontent.com/1576190/86091104-e4f4ab00-badd-11ea-8449-55d17e8a9d5f.png)

**Comment by jamesstout** [comment]
**Key Question:** What connection encoding should you use if the table you are querying uses multiple CHARACTER SETs?

As I understood it, charset is the legal characters allowed in the table./column, collation is how to compare values with the same charset?

**Comment by salvor-hardin** [comment]
I would say is up to the user to know what they are doing when comparing , right?

Comparisons between different encodings from different tables might need a common cast written in the query.

The issue here is that the app only uses the encoding the table has globally to display characters, but that’s not right as some fields can be described with other encodings and that is what should be used when displaying. 
This is the same issue as the upper forked app for Sequel Ace, so just trying to get this sorted here specially helpful for content with non latin or utf8 encodings.

Thanks!

**Comment by salvor-hardin** [comment]
Quick note, example that might help : you don't need to go too far with japanese/chinese characters.

Same combo of latin table where you insert: "İLETIŞIM"
(that is "Contact" in Turkish) on a UTF8 field, Sequel Ace will put the ? over the nonlatin characters, however, reading with other client will read the nonlatin character ok.

**Comment by gboudreau** [comment]
> **Key Question:** What connection encoding should you use if the table you are querying uses multiple CHARACTER SETs?

I have the same question, and I'm not sure I have an answer... I'm not sure we can get from MySQL all the data in a format that we could use to convert the various columns into the correct characters to display to the end-user. I think we might need to execute a SELECT query for each different encoding type, and merge the results!

I'd be curious to know how others might have solved this issue...
Maybe we could look into the PHPMyAdmin codebase..?

**Comment by gboudreau** [comment]
Maybe we could `SELECT CAST(column_name AS BINARY)`, and handle the conversion from the binary data we receive, using the column charset..?

**Comment by jamesstout** [comment]
> I think we might need to execute a SELECT query for each different encoding type, and merge the results!
 
Before every query, SA refreshes table data, I added:

```objc
tableStatusResult2 = [mySQLConnection queryString:[NSString stringWithFormat:@"SELECT character_set_name FROM information_schema.`COLUMNS` WHERE table_schema = '%@' and TABLE_NAME = '%@'", escapedDatabaseName, escapedTableName ]];
```
To get the array of `character_set_name` used by that table. On a huge table with many character_set_names it would be a nightmare.

casting might be a better solution.

**Comment by gboudreau** [comment]
I think if we set the connection charset to `utf8mb4`, MySQL is able to convert all other encodings correctly, and return all texts in their equivalent UTF-8 representation.

```
CREATE TABLE `test_charsets` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `test_latin1` tinytext CHARACTER SET latin1 DEFAULT NULL,
  `test_utf8` tinytext CHARACTER SET utf8 DEFAULT NULL,
  `test_utf8mb4` tinytext DEFAULT NULL,
  `test_big5` tinytext CHARACTER SET big5 DEFAULT NULL,
  `test_eucjp` tinytext CHARACTER SET ujis DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET character_set_results = latin1;
INSERT INTO `test_charsets` (`id`, `test_latin1`) VALUES (1, '¢ £ Ç');

SET character_set_results = utf8;
UPDATE `test_charsets` SET `test_utf8` = 'ᚠᛇᚻ᛫ᛒᛦᚦ᛫ᚠᚱᚩᚠᚢᚱ᛫ᚠᛁᚱᚪ᛫ᚷᛖᚻᚹᛦᛚᚳᚢᛗ';

SET character_set_results = utf8mb4;
UPDATE `test_charsets` SET `test_utf8mb4` = '👍';

SET character_set_results = big5;
UPDATE `test_charsets` SET `test_big5` = '民國69年9月行政院國家科學';

SET character_set_results = ujis;
UPDATE `test_charsets` SET `test_eucjp` = '本格的なネットショップを';
```

![image](https://user-images.githubusercontent.com/370329/86533137-e5ee5980-be9c-11ea-8af0-e46a22e457fb.png)

The same data, when the table (and thus the connection) uses different charsets:
![image](https://user-images.githubusercontent.com/370329/86533195-539a8580-be9d-11ea-8938-36bdd2e9fb52.png)
![image](https://user-images.githubusercontent.com/370329/86533199-5a28fd00-be9d-11ea-90b4-753015d3d71c.png)
![image](https://user-images.githubusercontent.com/370329/86533201-5eedb100-be9d-11ea-9f65-12ddf35b00ea.png)
![image](https://user-images.githubusercontent.com/370329/86533202-644afb80-be9d-11ea-9774-543999571d67.png)
![image](https://user-images.githubusercontent.com/370329/86533205-69a84600-be9d-11ea-8d87-60e63655580f.png)

So the quick fix would be to always use utf8mb4, when loading data, instead of using the table's charset.

**Comment by Jason-Morcos** [comment]
@salvor-hardin Please check out the latest 2.1.2 beta and let us know if it's working for you!
https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by salvor-hardin** [comment]
Thanks Jason, it looks is working as expected! :)
