### ISSUE TITLE
Is it possible to import of connections programmatically?

### ISSUE THREAD

**Issue by RckMrkr** [Sequel-Ace/Sequel-Ace#1300]
I am trying to improve my workflow and would like to know if it's programmatically possible to add connections to Sequel Ace.

Preferably all the information, but I gathered from the questions around import from Sequel Pro that the passwords may be difficult.

Is there a way, currently to accomplish this?

**Comment by Jason-Morcos** [comment]
You could try using mysql:// URLs and opening those in Sequel Ace? Those would pass most of the connection settings. Other than that, I don't know of an easy way to do this currently
