### ISSUE TITLE
Inline or popup: Add option for when content contains a newline

### ISSUE THREAD

**Issue by milosivanovic** [Sequel-Ace/Sequel-Ace#1302]
Right now, it's impossible to edit fields with multiple lines inline as only one line is shown while in edit mode:
**Viewing:**
<img width="184" alt="Screen Shot 2021-11-28 at 1 27 33 PM" src="https://user-images.githubusercontent.com/1274505/143786666-dc6655c4-b3ae-45bb-bf02-e08ca7bf4ce4.png">
(This newline character is currently visible in the UI with the paragraph mark (¶) which is fantastic.)
**After double-clicking:**
<img width="193" alt="Screen Shot 2021-11-28 at 1 34 22 PM" src="https://user-images.githubusercontent.com/1274505/143786912-6f0d2753-82cf-416e-8bc7-89b15c8de2e4.png">
In inline edit mode, only one line is shown and you have to use arrow keys to get to the other lines. If you reach the last line and mistakenly press the down arrow one more time, it automatically disables edit mode and goes to the next row, making this very frustrating to use.

A solution to this would be to add another option (enabled by default), here:
<img width="359" alt="Screen Shot 2021-11-28 at 1 25 56 PM" src="https://user-images.githubusercontent.com/1274505/143786962-6a9bddaa-1cc8-4e07-870b-92764103cd6e.png">
called something like:
- [x] **_Force popup when editing content spanning multiple lines_**
which will override the "Intelligently switch at length" check and force a popup when a newline character is present in the content being edited.

I would also suggest improvine inline editing to make it possible to edit multiline content without a popup. This can be done by expanding the textarea (pushing the rest of the rows down temporarily) when multiple line are detected in inline edit mode.

**Comment by Jason-Morcos** [comment]
There are also some known bugs with the popup editor already, this would be a good thing to tackle at the same time as addressing those like https://github.com/Sequel-Ace/Sequel-Ace/issues/1118 


Also related to https://github.com/Sequel-Ace/Sequel-Ace/discussions/1134
