### ISSUE TITLE
Bring back the search ribbon from Sequel Pro

### ISSUE THREAD

**Issue by methnen** [Sequel-Ace/Sequel-Ace#1308]
It's possible this is there and I'm just not sure how to bring it up, but I found the search ribbon in the Sequel Pro's Content view very handy at times.

It's the only thing I really find myself missing when using Sequel Ace.

Hopefully I'm not the only one missing this feature.

**Comment by Kaspik** [comment]
Can you screenshot what u talking about please?

**Comment by methnen** [comment]
Sure, see the green highlighted area of this screenshot of Sequel Pro:

![Sequel Pro Search Ribbon](https://methnen-dropshare.s3.amazonaws.com/pb-lcH7USGNa9.png)

**Comment by Kaspik** [comment]
Isn't that simple CMD+F shortcut? 🤔

**Comment by methnen** [comment]
Haha... 

So it is. In Sequel Pro it's always visible, so I was looking under View for the option.

OK, so disregard this then. Is there a way to make it always show up when on the content view?

**Comment by Kaspik** [comment]
Hmm, not sure about that. Keep playing with that and you will find out definitely. 😅 It might stay until some action happens. We migrated to Auto Layout but with old storyboards for some stuff, so things are bit harder now.

**Comment by methnen** [comment]
Yeah, it definitely doesn't stay around when I open a new window, so I'll just have to adjust my habits a bit. At least it's there. :)
