### ISSUE TITLE
Sequel Ace using false ssh key

### ISSUE THREAD

**Issue by alexander-schranz** [Sequel-Ace/Sequel-Ace#1309]
- Sequel Ace Version (including build number):  3.4.2
- Sequel Ace Source (App Store/GitHub/Homebrew): Brew
- macOS Version: Monterey
- Processor Type (Intel/Apple): arm64
- MySQL Version: 5.7 / 8.0
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1. Try to connect to server over ssh
2. Fails with ssh didnt work .. ssh ... 

At the end I found out that i needed to edit the:

```
/Applications/Sequel Ace.app/Contents/Resources/ssh_config
```

To change there:

```diff
-    IdentityFile ~/.keys/id_rsa
+    IdentityFile ~/.ssh/id_rsa
```

**Expected Behaviour**

Use the selected ssh key or error with a nice error message when the configured ssh key is not found anywhere. Insead of some cryptical ssh command output.

**Comment by Jason-Morcos** [comment]
You shouldn't need to (nor should) edit the internal ssh config file of sequel Ace. If you want to customize ssh configuration, just select your own ssh config file in Ace's settings.

Are you trying to connect via ssh+key or ssh+password? I can assure you this isn't a global issue with ssh connections, I personally use them all the time.

The reason for that fake key was to work around some issues with sandboxing (ssh otherwise tried to use your id_rsa key which was inaccessible). This patch to try the fake key has been in place for more than a year with no complaints since about ssh connections being broken.

**Comment by alexander-schranz** [comment]
> Are you trying to connect via ssh+key or ssh+password?

ssh+key

> If connecting with a key, did you select the key for the connection and save?

I selected the key, save the connection. It saved also correctly restart of sequel ace shows still the file. But if i try to connnect it fails with:

<details>
<summary>Detail error Log</summary>

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/alexanderschranz/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 deployuser@web03.someserver.de -L 49426:127.0.0.1:3306

OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to web03.someserver.de [93.184.216.34] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/alexander/.ssh/id_rsa type -1
debug1: identity file /Users/alexander/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
debug1: compat_banner: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to web03.someserver.de:22 as 'deployuser'
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:iscjQXuyAoqUBp9Kidld4zaIDqupIbuQAtrFsj+3eag
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'web03.someserver.de' is known and matches the ED25519 host key.
debug1: Found key in /Users/alexander/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict:2
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: Operation not permitted
debug1: Will attempt key: /Users/alexander/.ssh/id_rsa  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /Users/alexander/.ssh/id_rsa
debug1: Authentication succeeded (publickey).
Authenticated to web03.someserver.de ([93.184.216.34]:22).
debug1: Local connections to LOCALHOST:49426 forwarded to remote address 127.0.0.1:3306
debug1: Local forwarding listening on ::1 port 49426.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 49426.
debug1: channel 1: new [port listener]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: Connection to port 49426 forwarding to 127.0.0.1 port 3306 requested.
debug1: channel 2: new [direct-tcpip]
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /home/deployuser/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
channel 2: open failed: connect failed: Connection refused
debug1: channel 2: free: direct-tcpip: listening port 49426 for 127.0.0.1 port 3306, connect from 127.0.0.1 port 49428 to 127.0.0.1 port 49426, nchannels 3
Es konnte keine Verbindung mit dem Host  2.143347e-314rgestellt werden, da die Portverbindung über SSH verweigert wurde. . Wenn Sie die Fehlerdetails überprüfen möchten, wird das SSH-Debugprotokoll angezeigt, das möglicherweise weitere Details enthält. @
```

</details>

I also never had any issues before I only get this error on my new machine on MacOS "Monterey". The ssh key file is the correct one in the log. If I configure that manually in the ssh_config file it works. If I select it in the UI under "Connect using SSL" it does not work.

And yeah its strange when I change the `ssh_config` of Sequel Ace (not selecting then any ssh key) all works like expected. The system is has not a lot of other things installed so ist mostly a basic installation SequelAce, PHP over brew, PHPStorm.

**Comment by Jason-Morcos** [comment]
Hmmm interestingly enough this looks like the server you're trying to connect to is actually the side rejecting the connection, not Sequel Ace. What keys do you have in your ssh config that the built-in Sequel Ace ssh config does not? My hunch is you have something in yours about forwarding keys/agents?

**Comment by Jason-Morcos** [comment]
If you could post a properly-sanitized (no private info) version of your ssh config file that could be useful for debugging this issue as well

**Comment by alexander-schranz** [comment]
@Jason-Morcos I have a lot of keys in my `.ssh` directory the default one is `id_rsa`:

```
config
config.backup
id_b********
id_ed25519
id_ed25519.pub
id_rsa
id_rsa.bak
id_rsa.bak_new
id_rsa.pub
id_rsa.pub.bak
id_rsa_b******
id_rsa_test
id_rsa_test.pub
known_hosts
known_hosts.old
r********_dev.pem
```

The config:

```
ServerAliveInterval 10

Host g*****
  Preferredauthentications publickey
  IdentityFile ~/.ssh/id_rsa

Host g*****e
  Preferredauthentications publickey
  IdentityFile ~/.ssh/id_rsa_b*****

#Host g*****
#  Preferredauthentications publickey
#  IdentityFile ~/.ssh/id_rsa
#  IdentityFile ~/.ssh/id_rsa_test

Host v*****.de
    ForwardAgent yes
Host s*****.de
    ForwardAgent yes
Host s*****.de
    ForwardAgent yes
Host p*****.de
    ForwardAgent yes
Host d*****.at
    ForwardAgent yes
Host r*****
    hostname *****
    user ec2-user
    identityfile ~/.ssh/r********_dev.pem
```

**Comment by Jason-Morcos** [comment]
You mentioned this is new on this computer/Montery, is your ssh config any different from the previous machine to this one?
Can you share a screenshot (also anonymized as needed) of the "files" tab of Sequel Ace's Preferences?

As a couple things to try, if the host you're trying to connect to doesn't already have it, could you try adding ForwardAgent to that host?

I still think it's something funky about the server itself. Just to be sure, can you SSH into the host from the command line without issue?

These couple lines from your debug log still jump out to me - it really looks like you get connected and then the server aborts for some reason
```
debug1: Connection to port 49426 forwarding to 127.0.0.1 port 3306 requested.
debug1: channel 2: new [direct-tcpip]
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /home/deployuser/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
channel 2: open failed: connect failed: Connection refused
debug1: channel 2: free: direct-tcpip: listening port 49426 for 127.0.0.1 port 3306, connect from 127.0.0.1 port 49428 to 127.0.0.1 port 49426, nchannels 3
Es konnte keine Verbindung mit dem Host  2.143347e-314rgestellt werden, da die Portverbindung über SSH verweigert wurde. . Wenn Sie die Fehlerdetails überprüfen möchten, wird das SSH-Debugprotokoll angezeigt, das möglicherweise weitere Details enthält. @
```

**Comment by alexander-schranz** [comment]
@Jason-Morcos 

> You mentioned this is new on this computer/Montery, is your ssh config any different from the previous machine to this one?

Nothing different I copied my ssh config from old the new system.

> I still think it's something funky about the server itself. Just to be sure, can you SSH into the host from the command line without issue?

Yes ssh work without any problems from any terminal I tried.
And I still use the above hack with changing the ssh_config of SequelAce directory, so I can use SequelAce. 

> As a couple things to try, if the host you're trying to connect to doesn't already have it, could you try adding ForwardAgent to that host?

There are one file and one directory listed:

```
/Users/me/.ssh/id_rsa
/Users/me/Downloads/Databases/
```

The second one is my export directory.

**Comment by Jason-Morcos** [comment]
Does Sequel Ace's Preferences' "Network" tab match between the new and old machine? If so, can you post a screenshot of that?

Same question for the connection screen for the connection setup screen itself.

Did you see the first paragraph of this earlier comment? I think this may still be applicable too
https://github.com/Sequel-Ace/Sequel-Ace/issues/1309#issuecomment-985640342

**Comment by alexander-schranz** [comment]
I do not longer have access to the old machine files.

But I found out something the network tab did look like this:

<img width="675" alt="Bildschirmfoto 2022-01-13 um 10 24 49" src="https://user-images.githubusercontent.com/1698337/149307134-06a0728c-7336-44cf-bc6d-95abec4f6c01.png">

Changed it to:

<img width="680" alt="Bildschirmfoto 2022-01-13 um 10 53 12" src="https://user-images.githubusercontent.com/1698337/149307305-d3782aeb-4488-42ba-aa31-97b50ab57add.png">

Removed my changes from the `ssh_config` and it seems to work still now with the default `~/.keys/id_rsa` file.
