### ISSUE TITLE
Removing filters with minus icon

### ISSUE THREAD

**Issue by onurkose** [Sequel-Ace/Sequel-Ace#131]
- Sequel Ace Version: 2.1.0
- macOS Version: 10.15.5
- MySQL Version: 8 something

**Description**
Hi guys, thank you very much to continue working on this.
There's a minus icon next to the plus icon at the right hand side on the filter bar. Right now it's only visible when there are more than one filter row. On legacy Sequel Pro, it was visible even there's only one filter because when we click the minus icon/button, it would remove the filters/refresh the table and close the filter bar. But it's not possible to do the same on Sequel Ace. We should click the filter icon at the bottom of the table to have the same result, and believe me guys, it's very very long way.

**Steps To Reproduce**
1. Ctrl+F to open up filter bar,
2. See there's no minus icon,
3. Click to the plus icon to add a second filter row,
4. See there are two minus icons now,
5. Delete one of the filter rows,
6. See the only minus icon left is disappeared now,
7. Now go to waaay back down to bottom footer,
8. Click to tiny filter icon to hide and clear the filters,
9. Click to the refresh icon next to it to refresh table for unfiltered content,
10. Open up a beer and take the rest of your day off after this exhausting experience.

**Expected Behaviour**
Just give our precious one and only minus icon back. Make the Sequel great again.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No it's not.

**Additional Context**
Here are some nice pictures:

![one filter](https://user-images.githubusercontent.com/139073/85951322-1e58d980-b96b-11ea-8283-6e71d959a857.png)
![two filters](https://user-images.githubusercontent.com/139073/85951324-20bb3380-b96b-11ea-8d4b-b594699377d1.png)

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by onurkose** [comment]
> Please try the latest beta and let us know if it's fixed now!
> 
> https://github.com/Sequel-Ace/Sequel-Ace/releases

Yes it's fixed! Thank you a lot.
