### ISSUE TITLE
Sequel Ace unable to access to SSH key passphrase

### ISSUE THREAD

**Issue by jakubboucek** [Sequel-Ace/Sequel-Ace#1310]
- Sequel Ace Version (including build number): Version 10.5 (55270.0.1)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store, but last update by Sequel Ace's dialog (from ZIP file)
- macOS Version: 10.15.7 (19H1519)
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.3
- macOS Localization: en_US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Maybe yes, maybe no… Beta version has individual ID, and Seques Ace Beta prompt me to put new passphrase for SSH key. Stable release don't.

**Description**
I have my SSH key protected by passphrase and I am using Sequel Ace installed by App Store.

When I today start Sequel Ace, it notify me about App Update and I was follow instructions. That just downloaded new release app to my Downloads folder – no automated reinstall, just only downloaded ZIP. I was open zip and drag&drop new app to Applications and choose Replace. 

After upgrade from 3.4.1 to 3.4.2 Sequel Ace is requested refresh Stale Bookmarks, I was followed [instructions](https://sequel-ace.com/ref/bookmarks.html#stale-security-scoped-bookmarks). 

When I tried Sequel Ace to connect my server through SSH, Sequel Ace produced error which notice lost access to passphrase for my SSH key in Keychain Access.

I tried delete passphrase from Keychain Access with hope the Sequel Ape will re-prompt me for passphrase again, but it still produce error message.

<details>
  <summary>Detailed error message (redacted)</summary>
<pre>
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Connecting to my-server [12.34.56.78] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
load pubkey "/Users/me/.ssh/id_ed25519": Operation not permitted
debug1: identity file /Users/me/.ssh/id_ed25519 type -1
debug1: identity file /Users/me/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/me/.keys/id_rsa type -1
debug1: identity file /Users/me/.keys/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u2
debug1: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to my-server:22 as 'user'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:oFqf9jcO+Q4WF8w20hRtSzbFoOSg7OKjtVaHcsKNM7A
debug1: Host 'my-server' is known and matches the ECDSA host key.
debug1: Found key in /Users/me/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: Operation not permitted
debug1: Will attempt key: /Users/me/.ssh/id_ed25519  explicit
debug1: Will attempt key: /Users/me/.keys/id_rsa  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /Users/me/.ssh/id_ed25519
debug1: read_passphrase: can't open /dev/tty: Device not configured
ssh_askpass: exec(/Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant): Operation not permitted
debug1: Trying private key: /Users/me/.keys/id_rsa
no such identity: /Users/me/.keys/id_rsa: No such file or directory
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: Device not configured
ssh_askpass: exec(/Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant): Operation not permitted
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
ssh_askpass: exec(/Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant): Operation not permitted
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
ssh_askpass: exec(/Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant): Operation not permitted
debug1: Authentications that can continue: publickey,password
debug1: No more authentication methods to try.
user@my-server: Permission denied (publickey,password).
The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.
</pre>
</details>

I was also tried to Sequel Ace allow to access to passphrase in Keychain Access which was created by Beta version, not helped.

How I can fix that?

**Comment by Jason-Morcos** [comment]
Can you try something and see if it fixes it?
1. Quit Sequel Ace
2. Open Keychain Assistant and delete ALL entries related to sequel from ALL the different types of keychains
3. Reopen Sequel Ace
Does that fix it? 

By chance, did the key password change at some point or change in any way?

**Comment by jakubboucek** [comment]
Aah, thanks for ping.

I identified the core of problem: Keychain correctly works with app version from App Store. But as I described above, app noticed me about **new version downloaded directly through ZIP file**.  When I reinstalled the same version from App Store, Keychain access stars work fine.

Please thing about app update notification and remove link to ZIP file – all updates should be done via App Store only.

**Comment by Jason-Morcos** [comment]
Only the GitHub release version should be prompting you to update from downloaded zip file. Are you certain you had the App Store release version installed and it prompted you to do the GitHub download?
That whole system is supposed to be disabled for App Store release

**Comment by jakubboucek** [comment]
@Jason-Morcos No, I am not sure, but I was convinced of that. I can't prove it now. 

As I said, after updating to 10.5 ZIP version the app was unable to access to Keychain stored items. It was fixed after re-installing by App Store version. Currently I have no more info for you. This issue is maybe candidate to close.

**Comment by Jason-Morcos** [comment]
Will close for now! If it is confirmed to happen, though, let's definitely dig into it. Thank you!
