### ISSUE TITLE
It would be better with restoring SQL Editor content!

### ISSUE THREAD

**Issue by xtuer** [Sequel-Ace/Sequel-Ace#1311]
Currently we need manually save and open the SQLs in SQL Editor.
I think it would be better if automatically saving SQL Editor content and restoring them after restart the App, as well as the Tabs.

**Comment by Jason-Morcos** [comment]
Kinda duplicates #1289 and #773

**Comment by Jason-Morcos** [comment]
One thing is the query history saves all past queries so using that can get back things you ran previously

Closing this issue in favor of the other two issues
