### ISSUE TITLE
Add support for serialised PHP fields or allow for more serializers.

### ISSUE THREAD

**Issue by gheydon** [Sequel-Ace/Sequel-Ace#1315]
ATM there is support for Text, Image, Hex and JSON, but there are more types. In Drupal (like most PHP projects) have serialized PHP arrays/objects. Being able to unserialize these blobs would be so handy and make this an even better tool. Maybe also add other things like yaml, would also be helpfull.

![image](https://user-images.githubusercontent.com/70891/145910137-1d616e53-7f8b-4e27-b4cd-390b0b84966e.png)

**Comment by GoranSoce** [comment]
Don't think this will ever happen. I can't even preview JSON in blob fields although there is a <json> button, just shows a blank box.

**Comment by Jason-Morcos** [comment]
> Don't think this will ever happen. I can't even preview JSON in blob fields although there is a <json> button, just shows a blank box.

PRs are always welcome 😃

**Comment by fulldecent** [comment]
Recommending to close issue as there is no action to track and this is not a priority for the next 5 years.

**Comment by Jason-Morcos** [comment]
Closing this issue as requested - this all sounds like a great feature for a "bundle" which someone can develop independently of the core team.

**Comment by joehoyle** [comment]
AFAIK A bundle can not add table previews for columns or additional viewer formats?

**Comment by digitaldonkey** [comment]
@Jason-Morcos  Is there any documentation on what a "bundle" is and how you could develop one? 

IMHO this is a legitimate Feature request. Even if it's may not be a prio 1. Why close it?

**Comment by Jason-Morcos** [comment]
We have a placeholder area in our docs for bundles info - that could be contributed to the /docs folder in our repo - https://sequel-ace.com/bundles/

But fundamentally Ace's bundles are just like it's predecessor Sequel Pro - https://sequelpro.com/docs/bundles
