### ISSUE TITLE
Trouble displaying JSONs

### ISSUE THREAD

**Issue by rauven** [Sequel-Ace/Sequel-Ace#1317]
- Sequel Ace Version:  3.4.3 - 20019
- macOS Version: 12.0.1
- Processor Type: Intel
- MySQL Version: 5.5.5 (maria db 10.3.31)

I just updated from a old version (2.*) and noticed right away that the latest version of the app is having troubles showing JSONs:

In some cases, there's a formatting issue with the "{" going out of the window:
<img width="814" alt="Screenshot 2021-12-17 at 11 57 50" src="https://user-images.githubusercontent.com/28288283/146542344-bf26655d-70dc-4ea1-b780-8d31f447b45e.png">
<img width="781" alt="Screenshot 2021-12-17 at 11 57 55" src="https://user-images.githubusercontent.com/28288283/146542343-e0007b5e-2909-45fd-99c6-90476f44fb59.png">

In other cases, it says the json is invalid even though it definitely is valid:
<img width="820" alt="Screenshot 2021-12-17 at 11 58 08" src="https://user-images.githubusercontent.com/28288283/146542342-9f90bde5-e82d-4db2-9414-41212d3ddaba.png">
<img width="808" alt="Screenshot 2021-12-17 at 11 58 13" src="https://user-images.githubusercontent.com/28288283/146542334-d1d7ecbc-95d5-4bb2-b02a-e755a1ba5f7c.png">

That view worked fine at least on that old 2.* version (i don't remember the full version)

**Comment by Jason-Morcos** [comment]
Look at the bottom of the editor in each of your screenshots - you're comparing text mode in the 2.x release with json mode in the 3.x release. There may be some issues with the json validator, but you're comparing apples and oranges :)

**Comment by rauven** [comment]
Im sorry, I don’t understand what you’re saying, im comparing apples with apples, those screenshots all came from the same 3.x version and im literally showing the content in text and then how the json has formatting issue or fails completely, again, same version.

I store single line jsons in the database and that view is really important if you work with bigger jsons, right now im forced to copy and paste the content on jsonlint so i can make them “human readable”

**Comment by Jason-Morcos** [comment]
Ahhh I see, I thought you were showing screenshots of v2 versus v3, my bad. In any case, I fixed the overlapping issue on the top and can't seem to find an exact pattern for the failure to parse issues (literally clicking the same json again sometimes works) but the PR I made switches to a more resilient parsing approach which may fix these issues

**Comment by rauven** [comment]
Nope, they are all from the version 3.xx …
