### ISSUE TITLE
Sequel Ace Beta can connect but not Sequel Ace non-beta

### ISSUE THREAD

**Issue by sm131313** [Sequel-Ace/Sequel-Ace#1318]
- Sequel Ace Version (including build number): Latest 3.4.3 (20019)
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 12.1
- Processor Type (Intel/Apple): Apple

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
After update from latest beta can not connect to database receiving below error. However rolling back to beta works fine again.  

`Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/x/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 20038 user@host.domain -L 63241:mysql:3306

OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to domain [IP] port 20038.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/x/.keys/id_rsa type -1
debug1: identity file /Users/x/.keys/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.4p1 Debian-5
debug1: compat_banner: match: OpenSSH_8.4p1 Debian-5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to domain:20038 as 'user'
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:4Mq7xhTeFKTyvUY7enlC2o3oeUCLlgzd/ynBoEYKd8I
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: checking without port identifier
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts does not exist
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts2 does not exist
debug1: read_passphrase: can't open /dev/tty: Device not configured
ssh_askpass: exec(/Applications/Sequel Ace.app/Contents/MacOS/SequelAceTunnelAssistant): Operation not permitted
Host key verification failed.
The SSH Tunnel has unexpectedly closed.`

**Steps To Reproduce**
1. Update to latest version 3.4.3 (20019) from 3045. 
2. Try to connect to database and can not connect. Roll back to beta version and it can connect. 

**Expected Behaviour**

Updating Sequel Ace from one version to another should not lose all bookmarks. Even after re-adding them it should work to connect promptly and not require further changes.

**Comment by mfehr94** [comment]
@sm131313 as far as I know, you can install the beta and the full version in parallel, because they use different installation folders. My recommendation would be to remove the app once completely with a tool like [AppCleaner](https://freemacsoft.net/appcleaner/).

**Comment by Jason-Morcos** [comment]
"hostkeys file /etc/ssh/ssh_known_hosts2 does not exist" 

Are you using a custom ssh config file? Are you trying to use a known hosts file that you didn't give Ace beta access to?

**Comment by sm131313** [comment]
> "hostkeys file /etc/ssh/ssh_known_hosts2 does not exist"
> 
> Are you using a custom ssh config file? Are you trying to use a known hosts file that you didn't give Ace beta access to?

I have a factory new Macbook pro M1 with new installation and no migration done. At the time I was going to install Sequel Ace the Beta version was the latest version, this was the version I installed and used. No issues! 
When I started the Beta version a week ago it asked me to update to newer version which I did. Upon launching this new version I noticed that my saved bookmarks are not there anymore even though they were in keychain. So I understood that the installations are ran parallell and they don't read eachothers config. However after entering the new bookmarks again I am receiving the errors as the topic states. I have tried many things but cant connect with the non-beta version. 

The latest beta version works fine at the same time. 

So currently I rolled back to the latest beta version because the non-beta is not able to connect anywhere and gives error.

**Comment by Jason-Morcos** [comment]
Did you try re-granting bookmarks to everything in the non-beta variant?

Unfortunately bookmarks cannot really be shared between the beta and release variants because they're different apps. The way they can be installed side-by-side means they can't actually share resources.

**Comment by sm131313** [comment]
> Did you try re-granting bookmarks to everything in the non-beta variant?
> 
> Unfortunately bookmarks cannot really be shared between the beta and release variants because they're different apps. The way they can be installed side-by-side means they can't actually share resources.

My issue is not the bookmark, I understand they can not be shared. 
The issue is it is not possible to connect with the non-beta. While it can connect with beta.

**Comment by Jason-Morcos** [comment]
I understand that; that's why I'm trying to figure out why.

Please try the following steps in the non-beta version:
- open the app's preferences and select the default ssh config and known hosts files that are built into sequel Ace. If you use custom ones, _after_ selecting the defaults you can change back
- delete the connection you're trying to use a re-create it from scratch

Let me know if those steps work or don't.
The latest beta and release are really the same code so the only reason one works and not the other is that they are configured differently.

**Comment by sm131313** [comment]
> I understand that; that's why I'm trying to figure out why.
> 
> Please try the following steps in the non-beta version:
> 
> * open the app's preferences and select the default ssh config and known hosts files that are built into sequel Ace. If you use custom ones, _after_ selecting the defaults you can change back
> * delete the connection you're trying to use a re-create it from scratch
> 
> Let me know if those steps work or don't. The latest beta and release are really the same code so the only reason one works and not the other is that they are configured differently.

I tried this at first and it didnt work. I then decided to reboot the computer and then it worked by itself.
Please note that I did make reboots prior to this also. 

So now both are working side by side, both beta and non beta :) 

Unsure if you wish to investigate this further but from my end this can be closed now. Thank you so much for your help and effort!

**Comment by Jason-Morcos** [comment]
Odd! Glad it's working now! :)
