### ISSUE TITLE
Database -> User Accounts -> Unexpectedly crashes 3.4.3 on MySQL 5.7.x 

### ISSUE THREAD

**Issue by salvor-hardin** [Sequel-Ace/Sequel-Ace#1321]
- Sequel Ace Version (including build number): 3.4.3
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 12.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.36
- macOS Localization: English

**Description**
This happens on 3.4.3 (confirmed is not happening in 3.4.2) against various MySQL 5.7.36 instances.
With MariaDB 10.6.5 doesn't happen with any version

**Steps To Reproduce**
1.Database -> User Accounts
2. Crashes

**Expected Behaviour**
Crash

**Comment by Jason-Morcos** [comment]
Super weird. We literally made no changes to this entire part of the app with 3.4.3 but I think I found a fix - https://github.com/Sequel-Ace/Sequel-Ace/pull/1322
I'm wondering if there was some change in the latest Xcode about how things get compiled regarding case sensitivity in data model keys. Super odd

**Comment by emileblume** [comment]
I'm experiencing the same issue since a couple of days.

- Sequel Ace Version 3.4.3 / Build 20019
- MySQL 5.7.34
- MacOS 12.0.1

Beta version 3.4.5 solves my issues

**Comment by salvor-hardin** [comment]
Version 3.4.4 released 3 days ago indeed fixed the issue.
Thanks Jason, Kaspik and team.
