### ISSUE TITLE
Spaces are not escaped correctly in ssh config path

### ISSUE THREAD

**Issue by stevelacey** [Sequel-Ace/Sequel-Ace#1331]
- Sequel Ace Version (including build number):
Version 3.4.4 Build 20021
- Sequel Ace Source (App Store/GitHub/Homebrew):
GitHub
- macOS Version:
Monterey
- Processor Type (Intel/Apple):
Apple

**Description**
Spaces in the ssh config path are escaped with `%20` instead of `\ ` when the command is executed.

**Steps To Reproduce**
1. Move your ssh config to a path with a space in it
2. Try to connect to something, `SSH connection failed!`, used command will show `%20` in path
3. Same likely applies for known_hosts though I didn't test it

**Expected Behaviour**
Spaces should be escaped with a `\` not `%20`, or wrap the path in quotes and don't escape it.

**Related Issues**
I didn't need to setup ssh on Sequel Pro, I already symlink this directory to `~/.ssh`, and I expect that to be used by default.

Seems that Sequel Ace doesn't use `~/.ssh/config` by default, perhaps that was a design choice, but that's a bit irritating, or maybe it doesn't support symlinks here, either way Sequel Pro supported this and parity with Pro would be a great addition here. Seems odd that Ace would deliberately sidestep the ssh defaults the user has already configured for bash.

My ssh config in `~/.ssh` describes how to resolve hosts in my favorites (bypassing CloudFlare, mostly), and I expected my default ssh key to be used by default, instead of it just working after migrating my favorites I'm fumbling over obstacles.

**Comment by Jason-Morcos** [comment]
> I didn't need to setup ssh on Sequel Pro, I already symlink this directory to `~/.ssh`, and I expect that to be used by default.

Sequel Pro and Sequel Ace are _different apps_. When we modernized Sequel Pro, we moved into the Sandbox. While Sequel Pro can arbitrarily access and run any files on your computer, Ace cannot. This is a _good_ thing for the principle of minimal permissions/minimal access. We built in the ability to select a custom SSH file and grant access to files to allow _advanced_ users to use these more advanced used cases, still maintaining maximum security.


> Seems that Sequel Ace doesn't use `~/.ssh/config` by default, perhaps that was a design choice, but that's a bit irritating, or maybe it doesn't support symlinks here, either way Sequel Pro supported this and parity with Pro would be a great addition here. Seems odd that Ace would deliberately sidestep the ssh defaults the user has already configured for bash.

These are all limitations/features of the macOS sandbox. We do have parity with Sequel Pro here for advanced users and we clearly document them on our website (https://sequel-ace.com/get-started/ - see "Sequel Ace doesn’t read my ~/.ssh/config parameters.").


> My ssh config in `~/.ssh` describes how to resolve hosts in my favorites (bypassing CloudFlare, mostly), and I expected my default ssh key to be used by default, instead of it just working after migrating my favorites I'm fumbling over obstacles.

That works, you just need to make sure that Sequel Ace has access to all the SSH keys (or the directory that contains them) in the files tab of Sequel Ace's settings.
