### ISSUE TITLE
Require Menu and Dialog Localization

### ISSUE THREAD

**Issue by hmatsuok** [Sequel-Ace/Sequel-Ace#1340]
Separate menu and dialog resources for localization.

**Comment by Jason-Morcos** [comment]
Please fill out the full issue template when creating issues including particularly the version of Sequel Ace being used, version of MySQL/MariaDB, and any logs that may be applicable. In the case of a feature request, please be sure to clearly explain what you're trying to accomplish (the root issue) and if any workarounds currently exist.

We try to be as helpful as possible, but the volume of issues reported limits us to only have time to dig into those that include all the details needed. I encourage you to open a new issue with all the details provided.
