### ISSUE TITLE
Issues connecting to a Mysql 8.0.25-15.1 database

### ISSUE THREAD

**Issue by bomas13** [Sequel-Ace/Sequel-Ace#1343]
Hi,

I'm facing issues connecting to a Mysql 8.0.25-15.1 database and don't know what to do about it because the error popup isn't really helpful. Connection to this database with different software like TablePlus works like a charm, so I'm wondering what the problem is with Sequel-Ace.

Sequel-Ace Version I'm using is: Version 3.4.4 Built 20021 (Mac App Store)
MacOS Version I'm using is: Big Sur 11.6.2 (20G314)
Device I'm using is a MacBook Pro (16 Zoll, 2019)

![Bildschirmfoto 2022-01-06 um 09 55 13](https://user-images.githubusercontent.com/4661591/148356950-cf687556-a9bc-410a-bf4a-c3fd2de28827.png)

The error message translates to:
```
Access denied!

Could not connect to host 6.365988e-314r because access was denied. . @
```

But as I mentioned before: Credentials are correct using a different application for connecting to the database.

thanks in advance,
Thomas

**Comment by Jason-Morcos** [comment]
Looks like you figured this out! You did catch an error in the translations though which was causing the error message not to display - I believe I've fixed it for the next release!
