### ISSUE TITLE
Crash when editing POINT data

### ISSUE THREAD

**Issue by mdriessen** [Sequel-Ace/Sequel-Ace#1348]
- Sequel Ace Version (including build number): Version 3.4.4 Build 20021
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.1
- Processor Type (Intel/Apple): Both
- MySQL Version: MariaDB 10.6.4
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
When editing a field of type POINT in the content view the program crashes.

**Steps To Reproduce**
1. Edit a POINT field which contains data in content view.

**Expected Behaviour**
No program crash.

**Additional Context**
<img width="936" alt="Xcode" src="https://user-images.githubusercontent.com/1208433/149019485-ff95f16d-f262-4f57-8786-244da5d7cc58.png">
I did some debugging with Xcode. The crash seems to be related to a new feature that detects newlines and opens the content in a windows instead of editing it inline when the value contains a newline. However in this case the value is Geometry data and the newline detection crashes the program.

**Comment by Jason-Morcos** [comment]
Oh no! Taking a look at this now - hopefully for now the crash doesn't occur if you turn off the automatic editing for fields with newlines option?

**Comment by Jason-Morcos** [comment]
Thank you for the debugging effort! This helps a ton. Any chance you could test a fix and let me know if it fixes the issue?
https://github.com/Sequel-Ace/Sequel-Ace/pull/1350

**Comment by mdriessen** [comment]
I can confirm #1350 does indeed fix the issue. Thanks!
