### ISSUE TITLE
Views renamed as lowercase in SQL dump

### ISSUE THREAD

**Issue by henryli17** [Sequel-Ace/Sequel-Ace#1349]
- Sequel Ace Version (including build number): 3.4.5 Build 20025
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 11.6
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.26
- macOS Localization: en-GB

**Description**
Exporting a database that includes a view causes the view to be renamed to lowercase in the `.sql` dump.

**Steps To Reproduce**
1. Create a database with a view that includes uppercase characters e.g. `testTable`.
2. Export the database as a SQL dump.
3. Import the database, the view is imported as `testtable` instead of `testTable`.

**Expected Behaviour**
The view name should not change to lowercase, it should stay exactly the same.

**Comment by henryli17** [comment]
It seems like an exporting issue. In the `.sql` dump see the following lines:

```sql
# Replace placeholder table for albumDetails with correct view syntax
# ------------------------------------------------------------

DROP TABLE `albumDetails`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `albumdetails`
AS SELECT
   `song-album`.`albumId` AS `albumId`,count(0) AS `length`,sum(`songs`.`duration`) AS `duration`
FROM (`songs` join `song-album` on((`songs`.`id` = `song-album`.`songId`))) group by `song-album`.`albumId`;
```
Manually changing `albumdetails` to `albumDetails` (as it should be) fixes the issue when importing the `.sql` dump.

**Comment by Jason-Morcos** [comment]
@henryli17 I believe this is actually a MySQL issue and not a Sequel Ace issue.
Testing locally, running a `SHOW CREATE VIEW albumDetails` statement locally directly against the database was lowercasing the table name, even before that info made it to Sequel Ace.
I found a relevant MySQL thread. It appears you actually have to set a database setting to allow for non-lowercase table/view names - https://bugs.mysql.com/bug.php?id=20356

**Comment by Jason-Morcos** [comment]
Running the statement `show variables like '%case%'` should show your current case setting.
The docs have some info on this - https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

**Comment by Jason-Morcos** [comment]
After more extensive testing and investigating, I've concluded that this isn't an issue with Sequel Ace indeed and is a "feature" of MySQL (yes, it's weird). I suggest you change the variable setting for your database if you wish to use mixed-case views/tables, in which case Ace should work all happy with those :)
