### ISSUE TITLE
Import CSV file INSERT ON DUPLICATE

### ISSUE THREAD

**Issue by marionfromfrance** [Sequel-Ace/Sequel-Ace#1352]
Hi everyone,

I have to import a CSV file to INSERT/UPDATE data in my table. I found in "advanced" section the "ON DUPLICATE KEY UPDATE" option and checked it, but I don't know and haven't found what is expected in the textarea. I tried the field name, and the string "myfield=VALUES(myfield)" but I always have the following message in the console, and the update doesn't work (I have a unique key on 4 fields) : 

[ERROR in row 1] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2

I tried with one row in the file, and with more, and I have the same message for each row.
Has anyone an idea?

Thanks a lot

Marion

**Comment by Jason-Morcos** [comment]
Please fill out the full issue template when creating issues including particularly the version of Sequel Ace being used, version of MySQL/MariaDB, and any logs that may be applicable. In the case of a feature request, please be sure to clearly explain what you're trying to accomplish (the root issue) and if any workarounds currently exist.

We try to be as helpful as possible, but the volume of issues reported limits us to only have time to dig into those that include all the details needed. I encourage you to open a new issue with all the details provided.

Please fill out a new issue report containing all that info and we'd be happy to investigate. Without even the version of MySQL though, this isn't something we can dig into adequately.

https://github.com/Sequel-Ace/Sequel-Ace/issues/new?assignees=&labels=&template=bug_report.md

**Comment by Jason-Morcos** [comment]
I think I know your issue though. On duplicate key update isn't just a check box, it's also a text field because on duplicate key update requires some more info. See the MySQL documentation - https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html


If you want to replace existing things, change the dropdown for "Import Method" from "Insert" to "Replace". That should do what you want, I think
