### ISSUE TITLE
Export database

### ISSUE THREAD

**Issue by liushang231** [Sequel-Ace/Sequel-Ace#1356]
![image](https://user-images.githubusercontent.com/32698965/149714254-e1768f81-275f-4814-a6eb-b5ffdc437188.png)

Clicking S, C and D cannot select the corresponding column

**Comment by Jason-Morcos** [comment]
Can you please explain a little more? I don't really understand what you're saying.

**Comment by ktwbc** [comment]
I think he means he expects clicking on the column header acts as a Select All for all the checkboxes in that column, which now that behavior is reached by clicking the Checkmark on the bottom which is a bit less intuitive.

**Comment by liushang231** [comment]
I mean: I want to select the "s" column of all data tables without exporting data. Now there are only "select all" and "deselect all" at the bottom

**Comment by liushang231** [comment]
Only the table structure is exported. I can only manually select each table. There is no option to select all "s" columns

**Comment by liushang231** [comment]
> Can you please explain a little more? I don't really understand what you're saying.

Only the table structure is exported. I can only manually select each table. There is no option to select all "s" columns

**Comment by liushang231** [comment]
Clicking "s" is invalid

**Comment by liushang231** [comment]
> I think he means he expects clicking on the column header acts as a Select All for all the checkboxes in that column, which now that behavior is reached by clicking the Checkmark on the bottom which is a bit less intuitive.

Thank you very much for finding a solution. I didn't seriously see the description on the right
