### ISSUE TITLE
Color of tabs

### ISSUE THREAD

**Issue by PrzemekTkaczyk** [Sequel-Ace/Sequel-Ace#1359]
Hi, 
First of all - VERY THANKS for that great tool !!!

ok, now I have question, what happened with the color of tabs ? :)
now it is hard to see the difference when you have few tabs opened - like on image:
![image](https://user-images.githubusercontent.com/11367987/149923018-08dbbe43-a63b-4cb5-a9fe-0dcc90161515.png)

is there any option to change the colors to be like on "open connection" window ?

--
Sequel Ace
Version 3.4.5
Build 20025

**Comment by Kaspik** [comment]
Hmmm, good catch, I wonder why it's a different color, maybe it has something to do with tabs not being active == darker, active == lighter.

**Comment by Kaspik** [comment]
Might be fixed in 3.5.0 but needs confirmation once its out :!

**Comment by PrzemekTkaczyk** [comment]
Hi, sorry, I didn't notice your response, but I saw that is fixed!!
Very thanks for it!
