### ISSUE TITLE
Crash on tables with invisible columns

### ISSUE THREAD

**Issue by aaronjheng** [Sequel-Ace/Sequel-Ace#1360]
- Sequel Ace Version (including build number):
  Version 3.4.5
  Build 20025

- Sequel Ace Source (App Store/GitHub/Homebrew):
  App Store

- macOS Version:
  11.6.2

- Processor Type (Intel/Apple):

  Intel

- MySQL Version:

  8.0.27

- macOS Localization:

  zh-CN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Crashes when loading data from tables with invisible columns.

**Steps To Reproduce**

1. Open a table with invisible columns.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Can you please upload the crash log (which you can get via the console.app) for this crash? Please attach the file as a comment on this issue (please don't paste the text of the log file)

**Comment by aaronjheng** [comment]
Sorry for the late reply.
[Sequel Ace_2022-01-31-084851_Aarons-2.crash.log](https://github.com/Sequel-Ace/Sequel-Ace/files/7967336/Sequel.Ace_2022-01-31-084851_Aarons-2.crash.log)

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all is someone set up with an up-to-date MySQL 8 and able to investigate this issue? We'll probably need to replace our `select *` uses with `select * [and a comma-separated list of invisible columns]`, which means we'll have to parse the invisible info in the extra column of the table information response, and we'll probably want to display that in front end and handle in create statement generation as needed too.

https://dev.mysql.com/doc/refman/8.0/en/invisible-columns.html

**Comment by Jason-Morcos** [comment]
My hunch is the crash is occurring because we know the columns exist because they show up in the create statement/table info but they don't come back in a select * so we explode when trying to index them out of the data response.

**Comment by Jason-Morcos** [comment]
The fix for this crash is going to be included in Sequel Ace 3.5.2, a release candidate of which should be available today!
