### ISSUE TITLE
Long query, editor becomes unbearably. slow

### ISSUE THREAD

**Issue by n9yty** [Sequel-Ace/Sequel-Ace#1366]
- Sequel Ace Version (including build number): 3.4.5 (20025)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.2 (21D48)
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.6.4
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
 Beta will not launch.

**Description**

When working on a long query, the editor becomes unusably slow.  Current query document is 7,022 characters on 184 lines.

I have the following options set:
Auto uppercase keywords
Highlight currentquery
Syntax highlighting
Bracket highlighting
Auto-Completion (delay by 1.5 seconds)

**Steps To Reproduce**
1. Create a long query
2. Note slow performance in editor

**Expected Behaviour**

I would expect the editor to be responsive even for long queries.

**Additional Context**

If I turn of Syntax highlighting performance improves considerably, but visually it is not as pleasant of an experience. It still feels a bit slower but it could be just perception.

**Comment by Kaspik** [comment]
There are already open Prs. Did you check them? Did you try to change font?

**Comment by n9yty** [comment]
No, I am not able at this time to set up dev environment and try pull requests. It is not the font. Turning syntax highlighting off makes it mostly responsive.

**Comment by Kaspik** [comment]
Sorry, open issues, not PRs. :)

I meant mostly convo in https://github.com/Sequel-Ace/Sequel-Ace/issues/1071 - but if you tried that, then allrighty. We are aware of _some_ issues but we were not able to improve them drastically.

**Comment by Kaspik** [comment]
Not saying it's gonna fully fix that, but pretty high chance it will improve that.
