### ISSUE TITLE
Replace deprecated 'beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:'

### ISSUE THREAD

**Issue by Kaspik** [Sequel-Ace/Sequel-Ace#137]
In whole project (almost everywhere) we use old 'beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:'. This has been deprecated in 10.10 (our minimum deployment target), so we should replace it with `-beginSheetModalForWindow:completionHandler:`.

The main reason for this is that 'beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:' uses `contextInfo` which is problematic for ARC and will block us soon in conversion to ARC enabled project.

### TODO:
- replace: 'beginSheetModalForWindow:modalDelegate:didEndSelector:contextInfo:'
- replace with: `-beginSheetModalForWindow:completionHandler:`

### NOTES:
- ideally make multiple smaller PRs for different files and places so more people can work on this together without conflicts and also so we have smaller changes in our project that we can test.

**Comment by Jason-Morcos** [comment]
duplicates #15  
@Kaspik You have some good notes though if you want to add those to #15!
