### ISSUE TITLE
Tab title display twice?

### ISSUE THREAD

**Issue by chihchanglin** [Sequel-Ace/Sequel-Ace#1372]
- Sequel Ace Version (including build number): 3.4.5 Build 20025, 3.5.0 (20028) Beta 2
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store, GitHub
- macOS Version: 10.14.6 (Mojave)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
Tab title display twice.

![image](https://user-images.githubusercontent.com/82863500/151498730-23ccb160-d39c-4df4-bdaa-afd8b5a41816.png)
![image](https://user-images.githubusercontent.com/82863500/151498755-213dc8f4-ef9a-4bc0-903c-69c9d0a693d0.png)
![image](https://user-images.githubusercontent.com/82863500/151499154-913fdc61-9f78-4023-9e41-cafc7be5afe2.png)

**Comment by chihchanglin** [comment]
I have tried some versions.
### Not OK:
3.4.1
3.3.3
3.3.2
### OK
3.2.3
3.0.2 

![image](https://user-images.githubusercontent.com/82863500/151502598-acbbe880-0b2c-43c7-8de3-60958f415587.png)

**Comment by Jason-Morcos** [comment]
@Kaspik something with older macOS and the big tab improvements you made, perhaps?

**Comment by Kaspik** [comment]
Is that still an issue with 4.0.0?

**Comment by Kaspik** [comment]
Assuming not, closing.
