### ISSUE TITLE
Not seeing existing global grants under USERs tab.

### ISSUE THREAD

**Issue by cphares** [Sequel-Ace/Sequel-Ace#1380]
- Sequel Ace Version (including build number): 3.4.5 build 20025
- Sequel Ace Source (App Store/GitHub/Homebrew):App Store
- macOS Version: 12.2 Monterey
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.33-log (AWS RDS MySQL)
- macOS Localization: En-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**
No granted privileges are shown under the user tab global privileges pane.  It appears like no privs are granted but executing show grants <username> shows that privileges have been granted.

**Steps To Reproduce**
1. Click on Users
2. Click on Global Privileges

**Expected Behaviour**
See granted priv boxes checked.

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Already fixed in code base, will be fixed in next release :)
https://github.com/Sequel-Ace/Sequel-Ace/pull/1376
https://github.com/Sequel-Ace/Sequel-Ace/issues/1370
