### ISSUE TITLE
Sequel Ace can't connect with SSH - returns `SSH connection failed`

### ISSUE THREAD

**Issue by commadelimited** [Sequel-Ace/Sequel-Ace#1387]
- Sequel Ace Version (including build number): 3.4.5 Build 20025
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: Unsure
- macOS Localization: English / USA

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes.

**Description**
I'm attempting to connect to the RDS instance of our database via an SSH connection. Connection setup is below.
![Screen_Shot_2022-02-10_at_3_18_56_PM](https://user-images.githubusercontent.com/563460/153498321-142d4d78-0793-4e39-8301-519d3b14d8ea.png)

When I click Connect Sequel Ace thinks for a few seconds then displays an error message with the following text (redacted)
```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/andymatthews/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict" -F /Users/andymatthews/.ssh/config -i /Users/andymatthews/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 3306 <username>@<sshhost> -L 62899:<mysql-host>:3306

OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/andymatthews/.ssh/config
debug1: /Users/andymatthews/.ssh/config line 16: Applying options for *
debug1: /Users/andymatthews/.ssh/config line 21: Applying options for *
debug1: Connecting to <sshhost> [52.0.25.45] port 3306.
debug1: connect to address 52.0.25.45 port 3306: Operation timed out
ssh: connect to host <sshhost> port 3306: Operation timed out
The SSH Tunnel was unable to connect to host <sshhost>, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).
```

I read through #437 which appears to have some good information about fixing a similar issue, but unfortunately that didn't fix it for me.

While debugging my connection I added my `id_rsa` and `.ssh/config` to the Files tab, and tried using my custom SSH config to connect. Neither modification resolved the issue. 

Note that this SSH connection works with all the same information using MySQL Workbench, I just don't want to use that app. I reviewed the SSH settings for MySQL Workbench and it's using my custom config at `/Users/andymatthews/.ssh/config` so I made sure to double check Sequel Ace with those settings and still no joy.

**Expected Behaviour**
Given that MySQL Workbench can open this connection, I expect the Sequel Ace can do the same.

**Related Issues**
#437

**Comment by Jason-Morcos** [comment]
Three things! 
1. Can you run the query `SELECT VERSION();` and share the result so we know what version of MySQL this is?
2. Can you double check the `SSH Port` number? The SSH port of 3306 is very unusual - perhaps try 22 there and 3306 for the MySQL port (higher up in the connection settings)
3. Can you please try the new beta (just released) and let us know if it's working there? https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by commadelimited** [comment]
Thanks for getting back to me @Jason-Morcos.

1) Good catch. I doubled checked my working MySQLWorkbench connection it doesn't to be using an explicit port number. So I cleared out the SSH port value and tested with an empty string **AND** port 22 and got a different error:
```
Unable to connect to host <HOST>, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: SSL connection error: Unable to get certificate
```
2) Remote MySQL version is `5.6.10-log`
3) Hot damn, using `3.5.1 (20030) Beta 1` did the trick!

**Comment by Jason-Morcos** [comment]
Woot! Yeah 3.5.1 has an SSL fix
