### ISSUE TITLE
App crashes when trying to export table

### ISSUE THREAD

**Issue by SermonB** [Sequel-Ace/Sequel-Ace#1393]
When I want to export tables the path is empty and when I select export the app crashes. I updated today to the latest version from the App Store

**Comment by Jason-Morcos** [comment]
Can you upload the crash log from console.app?

Additionally, does it work if you select a path using the file browser and then try to export?

**Comment by SermonB** [comment]
For some reason when I started my Mac today the path for export is filled in and I can export without crashing.

**Comment by Jason-Morcos** [comment]
Very odd! If you can get it to crash again, share the crash log and we'll reopen this - thanks!
