### ISSUE TITLE
Format SQL error.

### ISSUE THREAD

**Issue by xtuer** [Sequel-Ace/Sequel-Ace#1394]
- Sequel Ace Version (including build number): 3.4.5
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.2.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7.6
- macOS Localization: En

**Description**
BASH Error
Error for "Format SQL":
/bin/bash: /usr/bin/php: No such file
or directory

**Steps To Reproduce**
1. Input SQL such as "SELECT * FROM product" in SQL Editor
2. Bundles > Input Field > Format > Format SQL
3. It prompt errors as above description
4. Then install php 8.1.2 using brew: `brew install php`
5. `which php` get result **/opt/homebrew/bin/php**, `php -version` does work
6. Retry from step 1 again, and get the same error
7. `sudo cp /opt/homebrew/bin/php /usr/bin/php`: Operation not permission, this means:
    * We can not copy anything to folder **/usr/bin**
    * Result in Sequel Ace cannot use "Format SQL"

**Expected Behaviour**
Can use php from other location so that can use "Format SQL" feature.

**Comment by Jason-Morcos** [comment]
Duplicate #1265 
We haven't found a workaround yet. macOS Sandbox doesn't let us select a different version of PHP
