### ISSUE TITLE
bug: Error changing field

### ISSUE THREAD

**Issue by fifsky** [Sequel-Ace/Sequel-Ace#1397]
- Sequel Ace Version (including build number): 3.5.0

![image](https://user-images.githubusercontent.com/280967/155055587-16e86534-c158-42b0-8e08-171ee98a1c74.png)

Correct SQL syntax:

```
ALTER TABLE `app` CHANGE `name` `app_name` VARCHAR(32)
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
NOT NULL
DEFAULT ''   // <------ Look at me
COMMENT '应用名称'
```

**Comment by Jason-Morcos** [comment]
Please fill out the full issue template when creating issues including particularly the version of Sequel Ace being used, version of MySQL/MariaDB, and any logs that may be applicable. In the case of a feature request, please be sure to clearly explain what you're trying to accomplish (the root issue) and if any workarounds currently exist.

We try to be as helpful as possible, but the volume of issues reported limits us to only have time to dig into those that include all the details needed. I encourage you to open a new issue with all the details provided.
