### ISSUE TITLE
Can't add new field - Wrong sql when default is setted empty string

### ISSUE THREAD

**Issue by muarifer** [Sequel-Ace/Sequel-Ace#1402]
- Sequel Ace Version (including build number):
Version 3.5.0 Build 20029

- Sequel Ace Source (App Store/GitHub/Homebrew):
Homebrew

- macOS Version:
macOS Big Sur 11.6.1 (20G224)

- Processor Type (Intel/Apple):
Intel

- MySQL Version:
5.6.7

- macOS Localization:
en/en

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
When adding new "not null" field and set default value to empty, created sql is incorrect.

Created sql:

```sql
ALTER TABLE `products` ADD `barcode` VARCHAR(50)
NOT NULL
DEFAULT;
```

Correct sql:

```ruby
ALTER TABLE `products` ADD `barcode` VARCHAR(50)
NOT NULL
DEFAULT '';
```

**Steps To Reproduce**
1. Select some table
2. Go to "Structure"
3. Click plus button to add new field
4. set name to barcode, set field type to varchar and length 50, deselect allow null and set default to empty string.

**Expected Behaviour**
Created sql must be contains DEFAULT '';

**Related Issues**
#1397 

**Additional Context**

**Comment by cyberrrr** [comment]
Having this issue as well.

For now, set the default value as ``''`` on Sequel Ace and it should produce the intended result.

**Comment by Jason-Morcos** [comment]
If I understand the issue correctly, this was actually an intentional change in Sequel Ace 3.5. Per the message that showed up when 3.5 was first launched:
> The use of the "default" column has changed since the last version of Sequel ACE:
>
> - No default value : Leave it blank.
> - String value : Use single '' or double quotes "" if you want an empty string or to wrap a string
> - Expression : Use parentheses (). Except for the TIMESTAMP and DATETIME columns where you can specify the CURRENT_TIMESTAMP function without enclosing parentheses.

See https://github.com/Sequel-Ace/Sequel-Ace/pull/1250
And https://github.com/Sequel-Ace/Sequel-Ace/issues/1163

@gduh Please chime in here if you have anything to add!

**Comment by Jason-Morcos** [comment]
@gduh The one thing I might look into is if that created SQL statement should have had a `DEFAULT` with nothing after it or if the default should have been completely excluded from the create column statement?

If there's something here I missed, we can absolutely reopen this issue

**Comment by gduh** [comment]
> @gduh The one thing I might look into is if that created SQL statement should have had a `DEFAULT` with nothing after it or if the default should have been completely excluded from the create column statement?
> 
> If there's something here I missed, we can absolutely reopen this issue

@Jason-Morcos I look at this. If there is a need to make a change (Exclude the default if required or else!), I will apply it.
