### ISSUE TITLE
Tab color when only 1 tab is opend

### ISSUE THREAD

**Issue by pnkram** [Sequel-Ace/Sequel-Ace#1405]
Is it possibile to have the same behaviour on Sequel Pro about coloring the upper part of the window when there is only 1 tab opened? On Sequel Ace with only 1 tab there is no color on the upper part of the tab and it is needed to open another tab to see the color of the first tab.
This feature is useful in case you have multiple mysql host with different colors and when you have only 1 tab opened. It is quicker to know which host im connected to and there is no need to read on the upper part of the window.

Sequel Pro
![sequel_pro](https://user-images.githubusercontent.com/40732271/156618508-9dc76d2b-79d6-4643-8628-60e50c24c52a.png)

Sequel Ace
![sequel_ace](https://user-images.githubusercontent.com/40732271/156618544-73030c68-a674-46e4-b073-12fb84011673.png)

Thanks

**Comment by Kaspik** [comment]
Yes - see https://github.com/Sequel-Ace/Sequel-Ace/issues/1046#issuecomment-817933963

Duplicate, closing.

**Comment by pnkram** [comment]
Didn't see it (－‸ლ)
Thanks!
