### ISSUE TITLE
non empty table field problem

### ISSUE THREAD

**Issue by dujiecn** [Sequel-Ace/Sequel-Ace#1406]
- Sequel Ace Version (including build number): Version 3.5.0 Build 20029
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version: 11.6
- Processor Type (Intel/Apple):
- MySQL Version: 8.0
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
If a field is not empty, an error will be reported when modifying the field property. Or moving the field order will also report an error.
![image](https://user-images.githubusercontent.com/10645118/156704157-88bb0b86-c9e1-49fe-9a33-7e1e027a5260.png)

**Steps To Reproduce**
1.set Non empty table field
2.change table field sort

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Hi, I don't think I quite understand your bug report. Do you feel like it's the same issue as #1407?

**Comment by dujiecn** [comment]
> Hi, I don't think I quite understand your bug report. Do you feel like it's the same issue as #1407?

yeah like that，you can move the table field（not null） sort，also report the bug

**Comment by Jason-Morcos** [comment]
Perfect, if this issue and the other are the same I'll close this one and leave the other open!

**Comment by dujiecn** [comment]
> 

When will the repair be completed? Before the repair is completed, I will use other software instead

**Comment by Jason-Morcos** [comment]
The fix will be included in the next update of Sequel Ace - there is a working beta already available and a release candidate will likely be pushed up today, with a release coming when Apple approves it.
