### ISSUE TITLE
Cannot alter table with varchar, not null, default '' by Structure.

### ISSUE THREAD

**Issue by kzthrk** [Sequel-Ace/Sequel-Ace#1407]
Hi, folks

I found a minor bug.
(I have checked the existing issues with the keywords, "is:issue is:open alter table")

**Environments**
- Sequel Ace Version (including build number):Version 3.5.0 build 20029
- Sequel Ace Source (App Store/GitHub/Homebrew):App Store
- macOS Version: 12.2.1（21D62）
- Processor Type (Intel/Apple):intel
- MySQL Version:5.7.37
- macOS Localization: Japanese

**Description**
We cannot alter table with varchar, not null, default '' by Structure.

Sequel Ace produced the following SQL,
ALTER TABLE `users` CHANGE `username` `username` VARCHAR(255)  CHARACTER SET utf8  COLLATE utf8_general_ci  NOT NULL  DEFAULT   COMMENT 'xxxx';

However it's not correct. Blank spaces must be enclosed in quotation marks.
ALTER TABLE `users` CHANGE `username` `username` VARCHAR(255)  CHARACTER SET utf8  COLLATE utf8_general_ci  NOT NULL  DEFAULT  '' COMMENT 'xxxx';

If we have the some value of DEFAULT, Sequel Ace works fine.
ALTER TABLE `users` CHANGE `username` `username` VARCHAR(255)  CHARACTER SET utf8  COLLATE utf8_general_ci  NOT NULL  DEFAULT 'xxx'  COMMENT 'xxx';

**Comment by mdriessen** [comment]
I encountered a similar problem when renaming columns without a default value. The default option should be omitted in this case.

`ALTER TABLE tablename CHANGE old_name new_name VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT`

**Comment by Jason-Morcos** [comment]
@gduh This seems related to https://github.com/Sequel-Ace/Sequel-Ace/issues/1397. Looks like there is a little bit of a bug in the behavior - we should try to get a fix out in the next bug fix of Sequel Ace soon :)

**Comment by gduh** [comment]
@Jason-Morcos Something has changed in the project setup since the last time I worked on it.
When I try to build the project I get the following error message : 
<img width="848" alt="xcode_team" src="https://user-images.githubusercontent.com/15440947/157317702-7e13956b-cbd7-4032-b684-1e29c5fbde81.png">

Until now to build the project, I had to switch to my own team. But it seems it's no longer possible ? Any help would be appreciated.

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos Something has changed in the project setup since the last time I worked on it.
> 
> When I try to build the project I get the following error message : 
> 
> <img width="848" alt="xcode_team" src="https://user-images.githubusercontent.com/15440947/157317702-7e13956b-cbd7-4032-b684-1e29c5fbde81.png">
> 
> 
> 
> Until now to build the project, I had to switch to my own team. But it seems it's no longer possible ? Any help would be appreciated.
> 
> 

I know @Kaspik made some recent changes?
Are you using the .xcworkspace or the .xcproj? I think we switched to proj from workspace
And I might also try using XCode 13.1 - 13.2 is super duper buggy
@Kaspik any other tips?

**Comment by Kaspik** [comment]
Yeah, no xcworkspace anymore (check the files here), you need to cleanup your local repo. :)

**Comment by gduh** [comment]
@Jason-Morcos @Kaspik I saw that .xcworkspace was no longer used.
At the end, FYI, I solved my issue by changing the team value in the target (SPMySQLFramework) "Build Settings" --> "Signing" --> "Development Team"  too. Usually I  only make this change in "Signing & Capabilities".

**Comment by xiangbohua** [comment]
I got the same problem.

**Comment by dujiecn** [comment]
> > @Jason-Morcos Something has changed in the project setup since the last time I worked on it.
> > When I try to build the project I get the following error message :
> > <img alt="xcode_team" width="848" src="https://user-images.githubusercontent.com/15440947/157317702-7e13956b-cbd7-4032-b684-1e29c5fbde81.png">
> > Until now to build the project, I had to switch to my own team. But it seems it's no longer possible ? Any help would be appreciated.
> 
> I know @Kaspik made some recent changes? Are you using the .xcworkspace or the .xcproj? I think we switched to proj from workspace And I might also try using XCode 13.1 - 13.2 is super duper buggy @Kaspik any other tips?

When will the next version be released

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if the issue is fixed - https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.5.2-20032

**Comment by kzthrk** [comment]
Sorry my late response.

I've tried to use the above beta and it works fine!
@Jason-Morcos  Thank you for your prompt actions.
