### ISSUE TITLE
window is moving with no reason when on full screen mode

### ISSUE THREAD

**Issue by RotemWald** [Sequel-Ace/Sequel-Ace#1411]
Please watch the below video which demonstrates the issue:
https://vimeo.com/685583242

Sequel Ace Version 3.5.0 Build 20029
macOS Monterey 12.2.1 (21D62)
New MacBook Pro 14" (M1 Pro)

**Comment by Jason-Morcos** [comment]
I would be shocked if this is a Sequel Ace bug - macOS allows very little control over spaces by apps. I bet this is macOS auto-organizing spaces. Any chance you have `Mission Control->Automatically rearrange Spaces based on most recent use` checked in System Preferences?

**Comment by RotemWald** [comment]
> I would be shocked if this is a Sequel Ace bug - macOS allows very little control over spaces by apps. I bet this is macOS auto-organizing spaces. Any chance you have `Mission Control->Automatically rearrange Spaces based on most recent use` checked in System Preferences?

It help - thank you!

**Comment by RotemWald** [comment]
@Jason-Morcos though it was fixed after changing the settings above, seems it keeps happening:
https://vimeo.com/688428717

**Comment by Jason-Morcos** [comment]
@Kaspik Any idea why this is happening? @RotemWald It seems strange that this is only happening on your machine, maybe a bug in spaces in general? Does this happen with any other apps?

**Comment by RotemWald** [comment]
Nope, it doesn't happen with other apps

בתאריך יום ו׳, 25 במרץ 2022 ב-1:08 מאת Jason Morcos <
***@***.***>:
