### ISSUE TITLE
Make language configurable in preferences

### ISSUE THREAD

**Issue by thomaschaaf** [Sequel-Ace/Sequel-Ace#1412]
Currently Sequel Ace is like half translated into german. Either way I prefer working in english for programming related software. Please create the possibility to change the language of the application in the preferences.

**Comment by Jason-Morcos** [comment]
This is already a built-in feature of macOS! :)

https://github.com/Sequel-Ace/Sequel-Ace/issues/1151#issuecomment-866595006
