### ISSUE TITLE
Wrong translation (German)

### ISSUE THREAD

**Issue by chrisdubai** [Sequel-Ace/Sequel-Ace#1425]
The blue button (confirm clear table) is wrong:

<img width="292" alt="Bildschirmfoto 2022-03-18 um 09 56 09" src="https://user-images.githubusercontent.com/50556105/158971938-eacd414b-07f1-45f5-b3c8-3231cf20ff5e.png">

**Comment by Kaspik** [comment]
Feel free to join Crowdin and fix that string. :)
