### ISSUE TITLE
When I use it to connect to tidb, it can only autocomplete the table name, but not the field name

### ISSUE THREAD

**Issue by yangqingmang** [Sequel-Ace/Sequel-Ace#1433]
When I use it to connect to tidb, it can only autocomplete the table name, but not the field name

**Comment by Jason-Morcos** [comment]
We don't officially support tidb - only MySQL and MariaDB (as per the readme). If you find the root of the issue and can propose a fix that also doesn't break for MySQL and MariaDB, I'd be happy to review that PR, but the core team cannot support additional database engines at this time. Another approach would be to inform tidb of the issue and see if they can fix the lack of parity with MySQL/Maria
