### ISSUE TITLE
"Access denied" over TCP/IP to MySQL 5.7.x; same credentials work with other clients including Sequel Pro

### ISSUE THREAD

**Issue by ernstki** [Sequel-Ace/Sequel-Ace#1435]
- Sequel Ace Version (including build number):
  * 3.5.2
- Sequel Ace Source (App Store/GitHub/Homebrew):
  * I've tried both App Store and GitHub release, result is the same
- macOS Version:
  * 10.15.7 (Catalina)
- Processor Type (Intel/Apple):
  * Intel
- MySQL Version:
  * MySQL 5.7.37-enterprise-commercial-advanced-log
- macOS Localization:
  * German

### Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?

Yes.

### Description

I get "Access denied" errors using Sequel Ace for TCP/IP connections to remote hosts that work in other clients (see "[Additional Context](#additional-context)").

Mostly here looking for advice on how to help debug this, since I did a cursory check but didn't notice anything on the web site mentioning verbose logging, or running the app with, like, a `--debug` flag.

![The error dialog box](https://user-images.githubusercontent.com/4009681/160208982-463936ef-2b1c-4569-a8f9-d325cdc7b7bd.png)

![The TCP/IP connection settings](https://user-images.githubusercontent.com/4009681/160208993-f72313ea-5ec1-4318-b266-0c4f242a38d9.png)

### Related Issues

* could be a duplicate of #960

### Additional Context

* Credentials were copy-pasted from a password manager to (hopefully) rule out typos
* Seeing other issues here related to the macOS keychain, I cleared **every** Sequel Ace password out, then restarted Sequel Ace, then re-entered the credentials
* Tested same host, username, password, along with several other servers on the same remote network in `mysql` CLI, MySQLWorkbench, and Sequel Pro, all with no issue
* Using a tunneled connection over SSH to other hosts on the remote network (running different versions of MySQL) works fine with Sequel Ace
  * I can't connect directly to port 3306 on _those_ hosts, though, so it's hardly an apples-to-apples comparison
  * …and I don't have direct SSH access to the host(s) I'm actually having problems with, so I can't tunnel as a workaround
* This _may_ be a long-standing issue with Sequel Ace going back a couple of years, which is why I'd been sticking with Sequel Pro (and putting up with its crashiness) for so long
* Whether the "Enable Cleartext plugin" checkbox is checked or not doesn't change the outcome
* Filtering Console.app messages by process matching `sequel` doesn't print any notable output during the connection attempt

**Edit:** added context about the cleartext plugin and messages in Console.app

**Comment by Kaspik** [comment]
Is there anything interesting in the console? (Jason mentioned console in the potentially duplicated issue thread)

**Comment by Jason-Morcos** [comment]
Does it work if you enable the clear text plug-in (checkbox in the connection's settings)? Do you know what authentication module you're trying to use to authenticate with the database?

Additionally, can you share the contents of the "files" tab in Sequel Ace's preferences? Do you have the built-in SSH Config selected? 

Is there anything _unique_ about the hosts you cannot connect to?

**Comment by ernstki** [comment]
> Is there anything interesting in the console? (Jason mentioned console in the potentially duplicated issue thread)

I opened up Console.app and filtered the device logs by process containing `sequel`, and there's nothing notable logged there during the connection attempt. Is there a way to bump up the verbosity, enable connection-level debugging, or log to the console or an external file that I can just `tail -f`?

**Comment by Jason-Morcos** [comment]
Thanks for all the info, @ernstki!

This does sound like some issue (or at least finickiness) on the ScaleArc side - I haven't seen other 5.7.x instances have trouble connecting with the MySQL 8 client library. Unfortunately, the MySQL 5.7 library doesn't work with MySQL 8 so we can't simply revert back 🤦 
"Error in extracting client details from LOGIN packet (auth off case)" does sound like ScaleArc just can't handle the handshake Sequel Ace is trying to make, indeed. Have you tried reaching out to ScaleArc support to see if they're aware of this already?

**Comment by ernstki** [comment]
> Have you tried reaching out to ScaleArc support to see if they're aware of this already?

According to our DBA, they have been for a while now, but given the givens, it seems unlikely to be addressed any time soon. I think we can close this as a WONTFIX.

Just out of curiosity: does it seam feasible to dynamically load one client library or the other, per-profile? I don't know a whole lot about Objective C, or macOS development in general, but it's an approach that I noticed HeidiSQL has used:

![220405-0001@scaled_thumb](https://user-images.githubusercontent.com/4009681/161795754-fa8b0842-9a21-4009-b668-1f868762dbaa.png)

**Comment by Jason-Morcos** [comment]
> > Have you tried reaching out to ScaleArc support to see if they're aware of this already?
> 
> According to our DBA, they have been for a while now, but given the givens, it seems unlikely to be addressed any time soon. I think we can close this as a WONTFIX.
> 
> Just out of curiosity: does it seam feasible to dynamically load one client library or the other, per-profile? I don't know a whole lot about Objective C, or macOS development in general, but it's an approach that I noticed HeidiSQL has used on Windows:
> 
> ![220405-0001@scaled_thumb](https://user-images.githubusercontent.com/4009681/161795754-fa8b0842-9a21-4009-b668-1f868762dbaa.png)

It's _probably_ possible (anything is possible with software!) but I'm really not sure how to go about doing it. That may be a viable fix if someone wants to PR it, but given 5.7 even is nearing EOL, I think the core team should focus on MySQL 8+ features.

**Comment by ernstki** [comment]
I'm good just knowing this is in the issue tracker for posterity, in case anyone else finds themselves in the same circumstances.

Right on with your point about 5.7 being EOL, so I'm going to go ahead and close this. Thanks for your responses!
