### ISSUE TITLE
Wrong display of data containing special characters

### ISSUE THREAD

**Issue by faisalmirza** [Sequel-Ace/Sequel-Ace#1436]
- Sequel Ace Version (including build number):  Version 3.5.1 / Build 20031
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.4 (Big Sur)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.37
- macOS Localization: NL

**Description**
Due to special characters the display of data is different in Sequel Ace

**Steps To Reproduce**
1. create a table with a varchar column (encoding utf8mb4)
2. insert row, for the colomn use the following value: استاد اختر شریف صابرحُسین قوال اروپ والے6 جون1998 رنسی والی شریف - 6HMYZ5TUYzY.mp3

**Expected Behaviour**
The screenshot shows how it was suppose to be:

<img width="785" alt="Screenshot 2022-03-26 at 16 13 19" src="https://user-images.githubusercontent.com/1070807/160245959-46f3f61b-550f-4657-af72-ee458a1e465b.png">

**Comment by Jason-Morcos** [comment]
Is this something to do with left-to-right text? Those look like Arabic characters which I believe are left-to-right. Does anyone know anything about this? Perhaps a database setting?
