### ISSUE TITLE
Type varchar default value error

### ISSUE THREAD

**Issue by wooyarich** [Sequel-Ace/Sequel-Ace#1437]
- Sequel Ace Version (including build number): Version 3.5.1 Build 20031
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.3(21E230)
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10
- macOS Localization: Korean

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1. structural designer : If the type is varchar, the null value is not allowed, and the default value is empty, an error occurs.
![aa](https://user-images.githubusercontent.com/5282826/160571067-88b1adb3-f70f-48c4-b40d-8fc4d8814283.jpg)
The default keyword followed by the '' character is missing.
2.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
This is fixed in 3.5.2. Please update to the latest release.
