### ISSUE TITLE
Show amount of table columns in table info

### ISSUE THREAD

**Issue by dkoether** [Sequel-Ace/Sequel-Ace#1438]
I think it could be a helpful feature to add the number of table columns somewhere (maybe in tab "table infos") in Sequel Ace. I haven't found it yet in the GUI but maybe there is already a way?

Thanks in advance and keep up the good work!

Best regards!

**Comment by Jason-Morcos** [comment]
Definitely a nice improvement, duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/1395. PRs welcome! :)
