### ISSUE TITLE
Severe bug when working on a server/account with access to multiple databases

### ISSUE THREAD

**Issue by rauven** [Sequel-Ace/Sequel-Ace#1440]
- Sequel Ace Version:  Version 3.4.5 - Build 20025
- Sequel Ace Source: Github
- macOS Version: 12.1 Monterey
- Processor Type: Intel
- MySQL Version: 5.5.5 (maria db 10.3.34)
- macOS Localization: pt-PT

**Description**
I have an server and account with access to multiple databases, ill pick a database from the dropdown and work on that, everything is fine until at the end of day i put my mac to sleep and go home, the next day when im back to the office, open the lid and continue working, sequel will still be visually identical and show the queries and the database i was on the previous day but anything i do will actually affect the incorrect database (like the one just after the selected db in the dropdown list)

It's quite severe because I've actually ruined a database because of it, i though i was working on my quick test DB, but instead it was editing and modifying a live one and in only noticed that when i did a query and it gave me the error saying that table or procedure didin't exist even thought it was right there in the list, luckily i had backups of the database.

Now at the start of the day, i'm forced to switch dbs back and forwards (no need to disconnect, just switch with the dropdown) and do a quick test query like "SELECT DATABASE();" just to check and make sure i'm working on the right db since i can't just trust what Sequel is showing me.

**Steps To Reproduce**
1. Connect to a server with multiple databases, select a database and work on it.
2. Put the mac to sleep (it may need to be overnight and maybe detect a switch in the wifi like when going from the office to home and back to the office to trigger the bug) *
3. Wake your mac and continue working like usual, the db you're now editing may not be the one sequel is showing you and you had been working previously.

*just putting it to sleep and waking right after doesn't seem to trigger the bug even for me, but it definitely happens 90% of the time when i go back to the office the next day.

**Comment by Jason-Morcos** [comment]
I definitely think we should investigate @Kaspik, not sure where to start - I haven't been able to reproduce this issue even with multiple databases in the same server

**Comment by Jason-Morcos** [comment]
Reopening this in general but I have tried testing locally and cannot reproduce. The reconnect logic for me locally always connects to the appropriate DB

**Comment by Kaspik** [comment]
Did you hear from someone recently after 4.0.3 fixes? Or why did we reopen this?

**Comment by Jason-Morcos** [comment]
Hmmm I'm not exactly sure why I reopened this 😅
I think I must have mistaken this for one of the other complaints about the app getting "database confused"

I think you're right and this should be closed unless we get new issue reports of this with latest fixes.

If we do get more issue reports, I think perhaps there could be some odd path by which the connection's database variable gets out of sync with the front end and/or database itself (most recent use statement executed). If so, I think we'd want to add some logic to re-assert the current database before running queries, or some logic to make the front-end do a bigger reload after a reconnect.

**Comment by rauven** [comment]
Hello, the issue persists on Version 4.0.0 Build 20037 and on another macbook (intel) running Ventura 13.1

After a year, i got the habit of running "SELECT database()" and switching back and forwards every morning to make sure im on the right  DB but still its dangerous as if i forget it and run a major query, i could break something.
