### ISSUE TITLE
Memory use: 88GB

### ISSUE THREAD

**Issue by BMDomLip** [Sequel-Ace/Sequel-Ace#1441]
- Sequel Ace Version (including build number): 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Monterey 12.1
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 8
- macOS Localization: UK

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
Sequel Ace was running for about 3 days (with standby numerous times) and I've just received a force quit message to say it's using 88GB of ram.

**Steps To Reproduce**
1. Keep Sequel Pro running for a few days

**Expected Behaviour**
Not to use 88GB of Ram

**Related Issues**
None

**Additional Context**
Screenshot attached

There is no crash report as it didn't crash.

![image](https://user-images.githubusercontent.com/101876282/161070703-ad3eb736-6207-435b-8986-d529895a4621.png)

**Comment by Kaspik** [comment]
Can we get some info about how many tabs, databases, how big tables etc. you probably have? Thanks!

**Comment by RipperTs** [comment]
内存占用确实会逐渐增加，就是正常少量的测试库数据，几千左右  没有切换选项卡  2天左右内存就达到了2G

**Comment by Kaspik** [comment]
Any update here? If not, will close.
