### ISSUE TITLE
Connection lost every night, reconnect never works

### ISSUE THREAD

**Issue by arlomedia** [Sequel-Ace/Sequel-Ace#1442]
- Sequel Ace Version (including build number): Version 3.5.2, Build 20033
- Sequel Ace Source: GitHub
- macOS Version: 12.3
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7.22-log
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
There are no newer betas available.

**Description**
I leave my Mac on all the time, never sleeping. I usually have 1-3 Sequel Ace tabs open when I finish work for the night. When I come back the next morning and try to use one of these tabs, they always show the Connection Lost error, and the Reconnect button never works -- it shows the beach ball for the timeout length, then the Connection Lost message appears again. It's faster to quit Sequel Ace every morning, restart it and reopen whatever connections I need. This occasionally happens during the workday while I'm working, but it happens every or almost every night when I am away for several hours.

**Steps To Reproduce**
1. Use Sequel Ace.
2. Leave the windows and tabs open and leave the computer running, but stop using the computer overnight.
3. Try using one of the Sequel Ace tabs left open from the day before.

**Expected Behaviour**
Best: Retain the connection automatically. (My "Keep Connections Alive" setting is on.)
Second best: Reconnect successfully with the Reconnect button. (Since a new connection works reliably, I would expect the Reconnect function to work reliably.)

**Related Issues**
This is similar to https://github.com/Sequel-Ace/Sequel-Ace/issues/658, but in my case the computer never goes to sleep.

**Additional Context**
For years I used Sequel Pro, and this occasionally happened, but nowhere close to every night. Then I got a new M1 Mac with Monterey in October and the problem started in Sequel Pro. I then found out about Sequel Ace and switched to that, but the problem remained. So this seems related to some change in the Mac software or hardware, but I'm not sure which since for me they both changed at the same time.

**Comment by Jason-Morcos** [comment]
Hmmmm, since the big bug fix to reconnect I haven't seen any issues with reconnecting and I leave Ace open all the time, but my computer does sleep at night. Are there any other steps to reproduce this? Anything funky or unusual that could be helpful?

**Comment by arlomedia** [comment]
I'm not aware of anything unusual here. I tried sleeping/waking the computer and also turning the network off/on, and the reconnect worked fine. It's just when the computer sits unused for 10 hours or so that the problem happens.

I also realized that of the two servers I regularly connect to, only one has the problem. If I connect to both servers in different tabs and leave them up overnight, the next morning one server "just works" without needing to reconnect, while the other shows the reconnect error and won't reconnect. These are both cloud database servers hosted by the same company and as far as I know use the same technology. The MySQL versions are the same and MySQL uses the same config file on both servers. Their connection settings (bookmarks) are set up the same way, using SSH connections. One difference is that the database where the problem occurs has much more data in it, but the problem still happens if I leave it while viewing a very small table. Another difference is that it gets much more traffic, so maybe my connection gets bumped off my too many other connections? I don't really know how that works and am just trying to think of what might explain the difference. Let me know if you have any ideas that I can test or look into.

**Comment by arlomedia** [comment]
I just tried something different when returning to work this morning. Instead of going directly to one of the "bad" connections that I knew would need to be closed and reopened, I first put my Mac to sleep, then woke it about 30 seconds later. Then I tried using the database connection and it worked seamlessly without even showing the reconnect dialog. It seems that something about the sleep/wake process refreshes the connection in a way that the Reconnect button doesn't. I wonder if that's something Sequel Ace does or something macOS does.

I'm still trying to think of what's meaningfully different between the database that fails to reconnect and the database that stays connected overnight. I used the Database > Show Server Variables command in Sequel Ace and ran a diff on the results for the two databases. Besides different host names and server IDs, the only differences were:

gtid_purged = 3 values in bad database, empty in good database
innodb_buffer_pool_chunk_size = slightly larger in bad database
innodb_buffer_pool_size = 5x larger in bad database
innodb_open_files = 2x larger in bad database
key_buffer_size = 5x larger in bad database
query_cache_size = 2x larger in bad database

Probably not helpful but I'll keep thinking on it.

**Comment by samuelbradshaw** [comment]
> Another difference is that it gets much more traffic, so maybe my connection gets bumped off by too many other connections?

This seems like a good possibility. I'm not sure what the best way to test it would be, though.

**Comment by arlomedia** [comment]
I just noticed something else. Now that I know a connection left open to this database will fail, I've gotten in the habit of switching to Sequel Ace, immediately pressing Command-T for a new tab and quickly double-clicking my bookmark. The last couple times I did this, Sequel Ace returned an SSH connection error: (domain names and IP addresses scrubbed)

`
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/arlo/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict" -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 user@webdomain.com -L 64032:dbdomain.com:3306

OpenSSH_8.6p1, LibreSSL 3.3.5
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to webdomain.com [1.2.3.4] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/arlo/.keys/id_rsa type -1
debug1: identity file /Users/arlo/.keys/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
kex_exchange_identification: Connection closed by remote host
Connection closed by 1.2.3.4 port 22
The SSH Tunnel has unexpectedly closed.
`

If I switch to Sequel Ace and wait a moment before connecting, the new connection works fine. So is there something about Sequel Ace itself that becomes inactive and needs a moment to wake up?

I'm not sure the initial problem is related to SSH, though, because I connect to both my "good" and "bad" databases using the same SSH login to the same web server.

**Comment by arlomedia** [comment]
I noticed that about two weeks ago, I had several days in a row where the problem didn't occur. I'm not aware of any changes to the server setup, the Sequel Ace setup or my usage habits. It just reconnected automatically in the morning. Then the problem came back for about a week. Then it reconnected automatically again one morning. I think these were the first times I ever saw the reconnection happen automatically since upgrading to the M1 Mac with Monterey, so whatever is triggering it is inconsistent, even though it's common. This could support the idea that it's related to other usage on the server bumping me off, but I don't have stats on that. [🤷](https://emojipedia.org/person-shrugging/)

**Comment by arlomedia** [comment]
I upgraded the memory on my database server about a week ago and the problem hasn't happened since then. Maybe that will be a helpful clue if anyone revives this issue.
