### ISSUE TITLE
Query editor has white background when dark mode is enabled

### ISSUE THREAD

**Issue by netojose** [Sequel-Ace/Sequel-Ace#145]
- Sequel Ace Version: 2.1.0
- macOS Version: 10.15.5
- MySQL Version: 8.0.20

**Description**
Query editor has white background when dark mode is enabled
<img width="1140" alt="Screenshot 2020-07-01 at 10 43 47" src="https://user-images.githubusercontent.com/134008/86223641-16c24c00-bb88-11ea-85ab-debf5f2849b9.png">

**Steps To Reproduce**
1. On Mac OS, enable dark mode (system preferences -> general -> Appearance -> dark)
2. Open Sequel Ace, connect and go to Query Editor

**Expected Behaviour**
The query editor should have a dark background when dark mode is enabled, like Text Edit:

Light mode:
<img width="578" alt="Screenshot 2020-07-01 at 10 45 07" src="https://user-images.githubusercontent.com/134008/86223944-7e789700-bb88-11ea-8db0-260eabd4da6e.png">

Dark mode:
<img width="578" alt="Screenshot 2020-07-01 at 10 44 45" src="https://user-images.githubusercontent.com/134008/86223903-6ef94e00-bb88-11ea-9245-3450f1bc7e6a.png">

**Comment by Jason-Morcos** [comment]
@netojose This would be a nice enhancement to implement (specifying a dark mode theme that is different from the light mode one). The query editor is fully customizable theme-wise so please checkout Sequel Ace's preferences if you'd like a black-background query editor. There are multiple themes pre-loaded and you can customize your own.

**Comment by netojose** [comment]
> @netojose This would be a nice enhancement to implement (specifying a dark mode theme that is different from the light mode one). The query editor is fully customizable theme-wise so please checkout Sequel Ace's preferences if you'd like a black-background query editor. There are multiple themes pre-loaded and you can customize your own.

Good @Jason-Morcos , I will see on preferences. Thanks!

**Comment by crstauf** [comment]
@Jason-Morcos Will the query editor be adjusted to match the system color scheme, or is the use of themes the only option?

If a user has light and dark mode scheduled or automatic, going into Preferences and changing the theme twice each day (to match system color scheme) would be tiresome.

**Comment by stychos** [comment]
@crstauf I think this can be done by extending themes to keep some "dark" flag and having dark / white theme pairs, or maybe there's better way. But currently core team is focused on fixing more important connection-, security- and stability-related bugs, that's why this issue is marked "PR Welcome" currently.
