### ISSUE TITLE
Connect to Amazon RDS through SSH/SSM

### ISSUE THREAD

**Issue by etelford** [Sequel-Ace/Sequel-Ace#1450]
I hope this is the right place to ask this.I am attempting to connect to an RDS instance via SSH/SSM. I have a host set in my `~/.ssh/config` as follows:

```bash
Host my-ec2-host
  Hostname i-0abcdefgh123456
  User ec2-user
  ForwardAgent  yes
  ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"

Match Host i-*
  IdentityFile /Users/myusername/.ssh/cert.pem
  BatchMode yes
```

I can successfully connect to my EC2 instance with `ssh my-ec2-host` and I can successfully connect to my RDS instance directly from my EC2 instance with `mysql -uuser -haws.host.of.rds -p`, but I'm not able to connect to the instance with a tunnel in Sequel Ace, which looks like:

<img width="465" alt="Screen Shot 2022-04-14 at 4 39 36 PM" src="https://user-images.githubusercontent.com/1336701/163481215-b73ab5bd-e008-4696-ab22-ec1281b0e297.png">

Is this something Sequel Ace supports?

**Comment by Jason-Morcos** [comment]
Have you selected your SSH config file in Sequel Ace's Preferences (under the Network tab)? Ace is sandboxed so you need to manually select your SSH config if you'd like to use it. It _should_ theoretically work in the way you'd like though!

**Comment by etelford** [comment]
Thanks for the tips! Unfortunately, After selecting the `~/.ssh/config` file as well as the `.pem` certificate, I still can't connect.

From the command line, these both work:

```bash
ssh my-ec2-host
ssh ec2-user@i-{instanceId}
```

Here is the error Sequel Aces displays when I attempt to use the settings in my screenshot above:

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/username/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict" -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 my-ec2-host -L 57223:my-ec2-host-dev.ab1cd2efghi3.us-west-1.rds.amazonaws.com:3306

OpenSSH_8.6p1, LibreSSL 3.3.5
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
ssh: Could not resolve hostname my-ec2-host: nodename nor servname provided, or not known
The SSH Tunnel has unexpectedly closed.
```

And here is my `~/.ssh/config`:

```
Host my-instance
  Hostname i-0123abc4567d8901
  User ec2-user
  ForwardAgent yes
  IdentityFile /Users/username/.ssh/cert.pem
  ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```

**Comment by etelford** [comment]
I think I selected the SSH Config and Known Hosts incorrectly before. So now I've gone to the "Network" tab in Settings and selected my `config` and `known_hosts` file and the error message I received was:

```
sh: aws: command not found
```

So I updated my `config` file and changed the proxy command to:

```
ProxyCommand sh -c "/usr/local/bin/aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```

and now the error is `sh: /usr/local/bin/aws: Operation not permitted`

I've tried adding the `aws` executable to the list of Accessible Files, but when I select the file, it doesn't actually get added to the list.

**Comment by shengslogar** [comment]
I'm having a similar problem, but with `cloudflared`. Explicitely granted `/opt/homebrew`, down to the parent directory of the binary, but can't seem to add the binary itself.

Granted Sequel Ace "full disk access" but that didn't change anything.

```
zsh:1: operation not permitted: /opt/homebrew/bin/cloudflared
```

Pasting the exact command Sequel Ace is running into Terminal works as expected, so definitely a weird sandboxing issue...

**Comment by etelford** [comment]
It seems like access to these executables is indeed the issue. I was able to connect using TablePlus with the same setup (though I had to open it from the command line instead of double-clicking from within Applications). I guess TablePlus isn't sandboxed the same way.

**Comment by shengslogar** [comment]
@etelford Ha, I literally just installed TablePlus and tried the exact same thing. Was able to open TablePlus normally, pop in my SSH config alias and username and it worked perfectly. I know nothing about macOS dev but this is interesting...

**Comment by Jason-Morcos** [comment]
Unfortunately, due to sandboxing, we can't access those executables in usr/local/bin nor in opt/homebrew :/
I didn't see the aws command line access in your SSH config before, that's my bad. I connect to my AWS instances using SSH keys which does work, and you can use entries in your ssh config file, but Ace can't access those other executables.

**Comment by Jason-Morcos** [comment]
Related:
- https://github.com/Sequel-Ace/Sequel-Ace/issues/202
- https://github.com/Sequel-Ace/Sequel-Ace/issues/887
- https://github.com/Sequel-Ace/Sequel-Ace/issues/94
- https://github.com/Sequel-Ace/Sequel-Ace/issues/188
- https://github.com/Sequel-Ace/Sequel-Ace/issues/346

I'm gonna go ahead and close this issue because I think those other ones cover the different parts that are at play here.
