### ISSUE TITLE
Tab UI broken in High Sierra

### ISSUE THREAD

**Issue by bastones** [Sequel-Ace/Sequel-Ace#1452]
- Sequel Ace Version (including build number): 3.5.2 (20033)
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 10.13.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.29 (MySQL)
- macOS Localization: en-BB

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
The text of each tab is duplicated and tab length shrinks and expands unexpectedly.

**Steps To Reproduce**
Open multiple tabs (see video below).

**Additional Context**

https://user-images.githubusercontent.com/845891/165176378-0fba3733-23b7-4c45-b76a-46276b65cda7.mov

**Comment by Kaspik** [comment]
It's unfortunate, but this all is system thing so it seems like first versions of macOS that added native tabbing support just have broken pieces sometimes... Not sure if we should spend time on such an old system version. 🤯

**Comment by bastones** [comment]
The same issue is also present in macOS Mojave and it was broken in a fairly recent release. When I tested an earlier version of Sequel Ace before the tab UI had been changed, it works fine.

If you are going to support these versions of macOS as per the application's system requirements, your contributors should be testing their changes against each supported version of macOS.

It is extremely poor standard to release new features without properly testing the app against the versions of macOS that you intend to support.

**Comment by bastones** [comment]
The same issue is also present in macOS Mojave and it was broken in a fairly recent release. When I tested an earlier version of Sequel Ace before the tab UI had been changed, I could not reproduce this issue.

If you are going to support these versions of macOS as per the documented system requirements, your contributors should be testing their changes against each supported version of macOS.

It is extremely poor standard to release new features without fully testing the app against the versions of macOS that you intend to support.

**Comment by MikeRich88** [comment]
I've seen Safari on Catalina do similar things with the tab bar.

Internally, opening a new tab in Sequel Ace (and other programs using the system tab bar), is actually causing a new window to be created but the contents displayed inside of a tab. In theory it works but in practice I've noticed all kinds of weird little glitches in many apps. Sequel Ace has crashed a few times while using tabs, so now I avoid them completely.

**Comment by Jason-Morcos** [comment]
> Sequel Ace has crashed a few times while using tabs, so now I avoid them completely.

If it crashes in the future, please share the crash.log (from Console app) with us and we can investigate :)
