### ISSUE TITLE
使用触摸板快速滚动会卡顿

### ISSUE THREAD

**Issue by RipperTs** [Sequel-Ace/Sequel-Ace#1457]
使用触控板在“结构” 或 ”内容“ 长内容的情况下  快速上下或左右滚动都会有卡顿现象
应该是有”惯性“的滚动效果的，但是这个没有 感觉很别扭

**Comment by Jason-Morcos** [comment]
Please submit issues only in English. This it to facilitate a greater number of contributors to be able to be involved in fixing them. Thanks!
