### ISSUE TITLE
running too laggy when there are many datasources

### ISSUE THREAD

**Issue by colorbeach** [Sequel-Ace/Sequel-Ace#1459]
I have added 30+ datasources. when i open the Sequel Ace, it acting too laggy and i cannot use it fluently

**Comment by colorbitch** [comment]
macOS: 12.1

**Comment by Jason-Morcos** [comment]
Why so many data sources? 😂

Are you saying the app is laggy just launching the main connection screen, without connecting to any connections yet? If you quit and reopen the app, is it still laggy?

**Comment by colorbitch** [comment]
Yes, even if there is no db connection, sometimes it will be very laggy when i open the main board.

When i reopen the app, it will still be laggy most of the time.

I have a lot of database configurations because there are also a lot of environments 😂.

**Comment by justcodingnobb** [comment]
same question , macOS 12.4 , 16G RAM , more than 3 datasources likes a sloth

**Comment by Jason-Morcos** [comment]
It's nice and snappy for me, unfortunately :/
If anyone is able to identify and make a stab at closing the slowness, PRs are welcome and highly appreciated!

**Comment by somegooser** [comment]
i also need to wait like 15 seconds before sequal ace is ready to click on anything on launch. Even when there is no connection active.

**Comment by Kaspik** [comment]
Just curious, could you please let us know font settings and some other preferences, screenshots of that or anything? :)

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now! If not, will be happy to reopen this issue

https://github.com/Sequel-Ace/Sequel-Ace/releases
