### ISSUE TITLE
Error for Copy as Markdown

### ISSUE THREAD

**Issue by wesamly** [Sequel-Ace/Sequel-Ace#1466]
- Sequel Ace Version (including build number): Version 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.3.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.37
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Already using the latest version available.

**Description**
When a row selected to copy as markdown, the following error occurs:
```
Error for “Copy as Markdown”:
/bin/bash: /usr/bin/python2.7: No such file or directory
**Steps To Reproduce**
```
1. Select table row(s).
2. Right click > Bundles > Copy > Copy as Markdown.

**Expected Behaviour**
To get data formated for markdown usage.

**Comment by Jason-Morcos** [comment]
Yeah, Apple has been removing the embedded versions of php/python/others and breaking all kinds of things :/
Related to https://github.com/Sequel-Ace/Sequel-Ace/issues/1227

**Comment by Jason-Morcos** [comment]
Gonna go ahead and close this in lieu of an expanded #1227
