### ISSUE TITLE
After new drive installed, can't connect to any database

### ISSUE THREAD

**Issue by pstevemichel** [Sequel-Ace/Sequel-Ace#1467]
- Sequel Ace Version (including build number): 3.5.2, 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): Apparently the app store
- macOS Version: 12.4
- Processor Type (Intel/Apple): Intel
- MySQL Version: Several, though 10.3.34-MariaDB-0ubuntu0.20.04.1
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
This is the latest

**Description**
All attempts to connect to databases across several (generally Ubuntu, though a couple in Docker as well) generate this:
"OpenSSH_8.6p1, LibreSSL 3.3.6
Can't open user config file /Users/xxx/.ssh/: Operation not permitted
The SSH Tunnel has unexpectedly closed."

And it shows the tunnel command it tried to use. 

I get the same error whether I'm using a password or a key. 

I have checked permissions on /Users/steve/.ssh directory (drwx------) and the files in it (-rw-------). 

I can connect to remote servers using iTerm, terminal, Transmit and Visual Studio COde, both using keys and passwords. I ran an old version of Sequel Pro, and am able to connect with it (though it crashes later).

I only noticed the problem this week, though I replaced my boot drive early last week. Given that permissions and ownership seem right, and that other apps aren't having the issue, I don't think that's it. I also granted the app full disk access in Security Preferences.

I've looked at  issue "Can't Connect via Socket #113."  SSH password could not be loaded form the keychain #1456." But nothing in those reports has helped me.

**Comment by Kaspik** [comment]
Not only the permissions, but can you also check Sequel Ace has access to that `.ssh` directory? The accessible files etc.?

https://github.com/Sequel-Ace/Sequel-Ace/issues/1108#issuecomment-1010142136

**Comment by pstevemichel** [comment]
Adding the .ssh directory in Preferences -> files fixed the issue for me. Previously only the two ssh files were listed there. I removed that access and change it to the directory, and it works fine. Thanks for the hint; I've been using the client in Code and it's handy, but not as good.
