### ISSUE TITLE
Reopen "Order of columns in Content view resets when I switch to a different table and come back"

### ISSUE THREAD

**Issue by dmitri-minkin** [Sequel-Ace/Sequel-Ace#1473]
Could we reopen the issue [#228](https://github.com/Sequel-Ace/Sequel-Ace/issues/228) ?

This is still a problem.

Tested in 

Version 3.5.2
Build 20033

**Comment by Jason-Morcos** [comment]
Hi, can you please provide a video demonstrating that this is still an issue and the _exact_ steps to reproduce? Then will be happy to reopen.

**Comment by Jason-Morcos** [comment]
Sure, I'll reopen the issue and close this one. This isn't a huge problem and more an inconvenience, however, so it seems unlikely to be a top priority to get fixed soon. PRs are much appreciated and welcome though if you, or someone else, would like to take a stab at fixing it!
