### ISSUE TITLE
"Rename database" causes app to crash and leaves incomplete data migration.

### ISSUE THREAD

**Issue by amfriedman** [Sequel-Ace/Sequel-Ace#1478]
- Sequel Ace Version (including build number): 3.5.2
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.3.1 (Monterey)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.26
- macOS Localization: English/US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** I have no idea.

**Description**
I select a database (500KB of data, nothing fancy in it, no views, no triggers, just InnoDB tables). I try and rename it. The app hangs and then crashes. When I reopen the app, the data migration job is left in an incomplete state, so the old DB is missing a table and the new "renamed" DB has only this one table. 

**Steps To Reproduce**
1. Select database
2. Select Database > Rename Database
3. Write a new name and save
4. Application hangs and eventually crashes followed by an Apple crash report window.

**Expected Behaviour**

DB is renamed.

**Related Issues**

Nothing.

**Additional Context**

**Comment by Kaspik** [comment]
Is this happening still?

**Comment by Kaspik** [comment]
I'm not able to repro.
