### ISSUE TITLE
Password lost when updating bookmark with new host endpoint

### ISSUE THREAD

**Issue by ktwbc** [Sequel-Ace/Sequel-Ace#1479]
- What version of Sequel-Ace are you using? 3.5.2
- What version of macOS are you running on? 10.6.5
- What device(s) are you using Sequel-Ace on? macbook pro

When updating a bookmark with a new host endpoint, the password is wiped out. This is particularly frustrating if copies of RDS are made for testing purposes and you replace the hostname with the copy but have to go into keychain to find the password since it gets blanked out.

**Comment by Kaspik** [comment]
This is on purpose and I don't think there is any plan to change that...

Password is stored in the keychain as a combo of the provided details - changing the details means loosing the ability to load the password (the password is not in the password field in Sequel Acc, it's just a placeholder, we get the password during the connection).
