### ISSUE TITLE
Add support for new MariaDB UUID data type

### ISSUE THREAD

**Issue by pfk84** [Sequel-Ace/Sequel-Ace#1486]
Right now, Sequel Ace doesn't support the UUID data type of MariaDB (10.7.0+) which leads to many issues (unable to delete/edit/alter etc.) if this type is used, especially as index/primary.

More details on the data type can be found here:
[MariaDB: UUID Data Type](https://mariadb.com/kb/en/uuid-data-type/)

**Comment by pfk84** [comment]
Am I really the only one having this issue? Sequel-Ace is practically unusable for me like this :(

**Comment by Jason-Morcos** [comment]
This does appear to be the only issue report of this issue. Would you want to take a stab at making a Pull Request to add this functionality? The team is happy to review any PRs made to Sequel Ace

**Comment by JOldak** [comment]
FWIW I'm also suffering from this problem. I have tables with UUID primary key and so can't edit any rows in Sequel Ace.

Even if a table has an integer primary key, if any columns have a default of UUID() then I can't insert them using Sequel Ace.

(I can write an SQL query to do these things of course, just can't use the Table Content tab to do so)
