### ISSUE TITLE
Small but useful addition for the help docs regarding MAMP

### ISSUE THREAD

**Issue by Braveatom** [Sequel-Ace/Sequel-Ace#1487]
Theres a setting in Mamp Pro that needs to be turned on, to make Sequel Ace connect. I'm not sure if its the same for standard MAMP.

Its documented here on the MAMP site - https://documentation.mamp.info/en/MAMP-PRO-Mac/FAQ/MySQL/How-do-I-connect-to-MySQL-with-Sequel-Ace/

Basically, under MySQL settings within MAMP Pro,  'Allow Network Access to MySQL' needs to be ticked.

While not a big issue, it did fox me for a while yesterday. It'd be great if it could be added to the Sequel Ace Docs.

**Comment by Jason-Morcos** [comment]
Docs are editable on this repo (the /docs folder)! Please submit a PR tweaking the docs accordingly and we'll gladly review and merge! :)

**Comment by Braveatom** [comment]
Thanks - I've created a pull request - apologies if its not up to standard, its the first one I've done on a public repo!

**Comment by Jason-Morcos** [comment]
> Thanks - I've created a pull request - apologies if its not up to standard, its the first one I've done on a public repo!

Thank you for the PR! Congrats on your first contribution! We truly appreciate it 🎉
