### ISSUE TITLE
Sequel Ace uses a lot of memory

### ISSUE THREAD

**Issue by saulstys** [Sequel-Ace/Sequel-Ace#1491]
- Sequel Ace Version (including build number): Version 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Monterey 12.4
- Processor Type (Intel/Apple): Apple M1 Max
- MySQL Version: Mariadb 10.3
- macOS Localization: French 

**Description**

When i start Sequel-Ace, without opening any db connection, it takes 950Mb of memory.
On another computer, it takes only 140Mb.
Same problem if i restart my computer
The problem occured after importing 220Mb of mysql in one database.
During this import, the memory raised up to 4Gb, then after the 1300 requests were executed, Sequel hanged up and the memory raised to 8Gb, then the import dialog disapeared and the memory when back to 4Gb.
After restarting Sequel the memory uses now 950Gb.

**Steps To Reproduce**
Import a 220Mb of sql (server on local network, connection via ssh)

**Expected Behaviour**
The memory should be released properly after import.
The software should use the same amount of memory (around 140Mb) after restart.

**Related Issues**
https://github.com/Sequel-Ace/Sequel-Ace/issues/1441
https://github.com/Sequel-Ace/Sequel-Ace/issues/985

**Additional Context**

**Comment by saulstys** [comment]
FYI, after uninstalling completely the app (with Avast Cleanup) and reinstalling from appstore, the used memory is now 74Mb
Avast Cleanup says that it freed 1.8Gb space when removing the app.

**Comment by Jason-Morcos** [comment]
No need to open a new issue, as you noted this duplicates #1441. Thank you for providing the more detailed set of steps though, that's definitely helpful!
PRs welcome if you've got an idea how to fix, we haven't identified the source of this issue yet.

**Comment by saulstys** [comment]
Hi Jason,
For me this problem can be related to the #1441 but the symptoms are differents.
No need to wait few days to get huge memory usage, you just need to export and import around 200Mb of SQL.
Also when you stop the software, the memory is released. But when you start it again, the memory used reach immediately 1Gb.
So apparently Ace is reloading something stored in a cache at startup.
I'm at your disposal if you need more info.

**Comment by Jason-Morcos** [comment]
We've made some big fixes to a few memory leaks in the 4.0 beta! Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases
