### ISSUE TITLE
Could not Toggle JSON format because of command not found

### ISSUE THREAD

**Issue by armetiz** [Sequel-Ace/Sequel-Ace#1492]
- Sequel Ace Version (including build number): 3.5.2
- macOS Version: 12.4
- Processor Type (Intel/Apple): Intel

**Description**
I could not toggle JSON because of python command not found.

**Steps To Reproduce**
1. Open longblog field containing JSON
2. Right Click : Bundles -> Format -> Toggle JSON Format

**Expected Behaviour**
Pretty JSON.

**Additional Context**

I'm using ZSH. 

```
which python # python: aliased to python3
```

![Capture d’écran 2022-07-07 à 14 24 31](https://user-images.githubusercontent.com/1119250/177772827-6edc9e40-7615-47f6-be2d-8a76ddd6e611.png)

**Comment by Jason-Morcos** [comment]
Related to #1227. The sandbox prevents us from accessing non-system libs and Apple removed python and php from macOS. We don't have a good workaround or fix for this at this time

**Comment by Jason-Morcos** [comment]
Would likely be fixable by https://github.com/Sequel-Ace/Sequel-Ace/issues/346. Just need someone to champion this effort and try to figure it out.
