### ISSUE TITLE
Add an auto-convert unix timestamp function in Table Content Table view 

### ISSUE THREAD

**Issue by gaumondp** [Sequel-Ace/Sequel-Ace#1496]
## Use case
We are constantly using date fields that are in fact unix timestamp (integer) data but the format is not really human friendly at all.

## Feature
Explicitly set a column to "This is a UNIX timestamp" via right click menu or even better set a column name that is recognized as a timestamp (tstamp, crdate, etc.).

HeidiSQL got this feature : https://www.heidisql.com/forum.php?t=12822

**Comment by Jason-Morcos** [comment]
Is this feature helpful at all? This is available in the current release of Ace - https://github.com/Sequel-Ace/Sequel-Ace/pull/862

**Comment by gaumondp** [comment]
I'm ashamed I didn't realize the mouseover over Unix timestamp in Sequel Ace! I just moved from Sequel Pro (Intel) and discovered Ace a month ago out of necessity to run it on M1 chips.

I will close this.

**Comment by robsch** [comment]
I would find it helpful! I like it very much in HeidiSQL. I hardly see an advantage by seeing the unix timestamp. IMO the real value should be shown as a tooltip. Best would be to add a preference in the table structure view, so one can choose.

**Comment by gaumondp** [comment]
> I would find it helpful! I like it very much in HeidiSQL. I hardly see an advantage by seeing the unix timestamp. IMO the real value should be shown as a tooltip. Best would be to add a preference in the table structure view, so one can choose.

Yep "inverting" the display (human value visible and real timestamp on mouseover) would be more useful.

DBeaver client has also that option to see all the column as human readable value instead of timestamp.
