### ISSUE TITLE
Preference panel, Network settings, duped alert when selecting/cancelling custom ssh client

### ISSUE THREAD

**Issue by jamesstout** [Sequel-Ace/Sequel-Ace#150]
- Sequel Ace Version: 2.1.0
- macOS Version: 10.15.5
- MySQL Version: n/a

**Description**
On the prefs panel, if you click to choose a custom ssh client, you get an alert, then click cancel, you get the alert again.

**Steps To Reproduce**
1. Open prefs panel, navigate to Network
2. Click "change" ssh client
3. Click cancel

**Expected Behaviour**
You should only get one alert

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**
It's to do with the `NSAlertFirstButtonReturn`, `NSAlertAlternateReturn` stuff we did in 7805a4b63ae5c0c8aa26c20c0efe834137b93786

Maybe handle as part of #15

**Comment by Jason-Morcos** [comment]
@jamesstout is right, we should fix this as part of the alert changes. @Kaspik can you knock this out?

**Comment by Kaspik** [comment]
Yep, I'll take a look on that.

**Comment by Jason-Morcos** [comment]
Fixed in 2.1.2 release!
