### ISSUE TITLE
Pinned tables result in duplicate exports

### ISSUE THREAD

**Issue by adepssimius** [Sequel-Ace/Sequel-Ace#1501]
- Sequel Ace Version (including build number): 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): Mac App Store
- macOS Version: 12.2.1 (21D62)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.34, InnoDB
- macOS Localization: us english

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**
Exporting tables while the tables are pinned results in the tables being exported twice.

**Steps To Reproduce**
1. pin a table
2. export that table by right clicking on the table in the main list OR in the pinned tables list (it occurs both ways)
3. see that the progress bar indicates that two tables are being exported instead of the expected one table
4. see that the resulting export will drop the table, create the table, insert data into the table, then do it all over again (see attached dump)

**Expected Behaviour**

The table should only be exported once.

**Related Issues**

**Additional Context**

[test_export_7-14-22_15-46-59.sql.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/9114899/test_export_7-14-22_15-46-59.sql.zip)

**Comment by Jason-Morcos** [comment]
@ShashwatC would you be able to look into this as it's likely an unintended side-effect of the table pinning feature?

**Comment by paulohenriquesg** [comment]
Hi guys! 

I just faced this issue today :) 

Do you have any updates on this? 

Is there any way I can help?

**Comment by Jason-Morcos** [comment]
No updates on this, but we'd be happy to review a PR on this if someone would like to take a stab at fixing it!

**Comment by Kaspik** [comment]
I'm pretty sure the table is selected twice in the exporter window already, so unselecting it would fix it even now. Anyways, fixed in #2000
