### ISSUE TITLE
Adding Custom Columns with Joined Data for Tables in the "Content" View

### ISSUE THREAD

**Issue by michaeleisel** [Sequel-Ace/Sequel-Ace#1503]
Suppose I have a table of students and a table of schools. Each student has a school_id column, which is an foreign key that corresponds to the ID of a row in the schools table. I want to see at a glance which school each student is a part of, but the ID isn't meaningful to me and I'd rather see the name of the school (another column that each school row has). For that, I'd like to add a custom column when I look at the students table, which does a join to show me the school name of each student.

**Comment by samuelbradshaw** [comment]
If you have relationships specified in the schema, there's an arrow icon that lets you quickly jump to the record in the corresponding table. What if hovering over that icon showed you information from the record, in a tooltip?

<img width="1222" alt="Screen Shot 2022-07-18 at 5 20 59 PM" src="https://user-images.githubusercontent.com/7323052/179633013-c75aa82d-a264-45e3-9fad-43d98815a85b.png">

**Comment by michaeleisel** [comment]
Yeah, thinking about this more, I think it would be cool to allow the sidebar to show not just tables, but also custom queries, which could include joins. This would solve this use case as well as other ones

**Comment by samuelbradshaw** [comment]
If you want it to show in the sidebar on the left, one option is to create a MySQL view – something like this:
```
CREATE VIEW MyView AS (
  SELECT songId, soNumber, soTitle, Collections.collectionId, coShortName FROM Songs
  JOIN Collections ON Songs.collectionId = Collections.collectionId
  ORDER BY soPosition
)
```

It will show up in Sequel Ace like this:
<img width="223" alt="Screen Shot 2022-07-29 at 3 19 30 PM" src="https://user-images.githubusercontent.com/7323052/181844471-e018a69d-66d7-4eb6-a427-58975fc2b7ea.png">

As a bonus, you can query the view as if it's a table:
```
SELECT * FROM MyView
```

I actually haven't used views much before, but after playing around with it a bit I might start using them. :)

**Comment by michaeleisel** [comment]
Cool! I'll try that out

**Comment by michaeleisel** [comment]
This covers my use case entirely, thanks :)
