### ISSUE TITLE
Shortcuts to filter tables not working

### ISSUE THREAD

**Issue by boyeatssteak** [Sequel-Ace/Sequel-Ace#1508]
- Sequel Ace Version (including build number): 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 12.4
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.38
- macOS Localization: en-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
Pressing `⌃⌥⌘F` doesn't focus the cursor on the filter tables input field anymore.
In the toolbar, the Filter Tables button is also disabled. (Table > Filter Tables)
<img width="284" alt="2022-07-22_20-33-38" src="https://user-images.githubusercontent.com/38873725/180503705-5bf5fa0e-e4f5-4e4f-ab00-1c165b018ec8.png">

**Steps To Reproduce**
1. Select a table
2. Open any of the 6 views (`⌘1` - `⌘6`)
3. Hit `⌃⌥⌘F`
4. Nothing happens

**Expected Behaviour**
1. Select a table
2. Open any of the 6 views (`⌘1` - `⌘6`)
3. Hit `⌃⌥⌘F`
4. The cursor focuses on the filter tables input field
<img width="235" alt="2022-07-22_20-50-59" src="https://user-images.githubusercontent.com/38873725/180504728-b3430ced-7c4a-4663-b9fa-8ccde5fbedf6.png">

**Related Issues**
[#1049 Shortcuts to filter tables not working](https://github.com/Sequel-Ace/Sequel-Ace/issues/1049)

**Additional Context**
In 1049, I noticed that it was [reopened](https://github.com/Sequel-Ace/Sequel-Ace/issues/1049#issuecomment-906160955) on behalf of @prabowomurti, but it doesn't appear that they ever opened a new issue, so maybe it is an issue only on my machine? I tried to thoroughly check though, and saw [Kaspik's comment](https://github.com/Sequel-Ace/Sequel-Ace/issues/1049#issuecomment-906166358) that it depended on the view - I cycled through each of the views (mapped as keyboard shortcuts `⌘1` - `⌘6`), and also checked on a couple different databases, but never could get `⌃⌥⌘F` to work.

**Comment by Jason-Morcos** [comment]
@Kaspik I'm also showing this option always grayed out. Any idea why? Maybe related to the previous window changes?

**Comment by Kaspik** [comment]
Ohh, I was talking about the Filter content. Don't think I ever touched Filter Tables, but probably removed it when I did windows work, can be easily connected back hopefully.

**Comment by yishaiza** [comment]
also reproduced for me. installed from Apple store. 
is there a newer version?
thanks

**Comment by Kaspik** [comment]
Fixed yesterday, no new version available yet.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by AlexanderKopyl** [comment]
Dosen`t work for me
