### ISSUE TITLE
Flashy Refresh on Query Tab

### ISSUE THREAD

**Issue by rawkon** [Sequel-Ace/Sequel-Ace#1510]
When I edit any data in a row in the Query tab, the query result section is refreshing by flashing every time. 
There is no such visual problem in editing in the Content tab, the editing is done very smoothly. This blinking only occurs in Query tab.

Maybe it's not a big deal, but when I work on data for a long time, it starts to get annoying.

**Comment by samuelbradshaw** [comment]
I don't know if this will fix what you're seeing or not, but have you tried turning off the "Reload table after" checkboxes?

<img width="700" alt="Screen Shot 2022-07-26 at 10 50 45 AM" src="https://user-images.githubusercontent.com/7323052/181064683-2ea44b08-5f65-4eac-8acf-696ae380b77f.png">

**Comment by rawkon** [comment]
@samuelbradshaw It worked! Thank you : ]

I had a quick look at the settings, but I probably skipped this part because of fatigue.
