### ISSUE TITLE
Can not connect to old version of mysql(5.6.36)

### ISSUE THREAD

**Issue by ddv12138** [Sequel-Ace/Sequel-Ace#1511]
- Sequel Ace Version (including build number): Version 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version:12.5
- Processor Type (Intel/Apple):Apple
- MySQL Version:5.6.36-log
- macOS Localization:zh_CN

**Description**
Can not connect to old version of mysql(5.6.36)

**Comment by Jason-Morcos** [comment]
You should be able to connect to MySQL 5.6+. Can you share the details of the error given and an appropriately-anonymized screenshot of your connection settings?
What leads you to believe the issue is related to connecting specifically to 5.6?

**Comment by ddv12138** [comment]
I believe the issue is related to connecting specifically to 5.6 because the mysql server was running behind mycat or something ,and it is running perfect when i use beta version of Sequel pro(nightly build) Build 5446 (97c1b857),which can be download [here](https://sequelpro.com/test-builds),and its a 2 years ago test build.

by the way ,the error msg shows username or password error when connect ,no any other information.

And sorry i cant share screenshot or connection settings ,because it is a confidential project, but i can tell the connect setting is just simple as any normal connection.

**Comment by ddv12138** [comment]
and when i use any other db tool like DataGrip or Navicat or Dbeaver or TablePlus, all perfect, except Sequel-Ace, and Sequel-Ace can not choose driver version, so I can not try any other way to fix this

**Comment by Kaspik** [comment]
MySQL 5.6 officially dropped, we are really sorry to hear about your issues and not help you but we are not able to keep supporting version that is after EOL.

**Comment by ddv12138** [comment]
I understand, thanks your help

**Comment by Kaspik** [comment]
Even tho you could try the latest 4.0.0 Beta 1 and see if that fixed your specific issue! :)

**Comment by ddv12138** [comment]
I tried,and still not working ,thanks anyway
