### ISSUE TITLE
Multiple connection tabs aren't saved correctly in session

### ISSUE THREAD

**Issue by nexbridge** [Sequel-Ace/Sequel-Ace#1516]
- Sequel Ace Version: 3.5.2 (build 20033)
- Sequel Ace Source: App Store
- macOS Version: 12.5
- Processor Type: Intel

Steps to reproduce:

1. Open multiple connection tabs and connect
2. Save your session
3. Close your Sequel Ace window
4. Open your saved session

This causes multiple connection _windows_ (not tabs) to open, all with the same connection details (even if the original tabs saved in the session had different connection details).  Also none of them auto-connect (see #1515).

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now! @Kaspik addressed this

https://github.com/Sequel-Ace/Sequel-Ace/releases
