### ISSUE TITLE
Content pane is slow when showing a BLOB column

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#1530]
- Sequel Ace Version (including build number): 3.5.2 Build 20033
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.5
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.5.5
- macOS Localization: en-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

If viewing a database with BLOB columns in the Content pane, the page loads slowly. BLOBS can be very large.

**Steps To Reproduce**

1. Create database with MEDIUMBLOB column
2. load big files there
3. Access Content pane

**Expected Behaviour**

Content pane loads immediately.

MEDIUMBLOB contents are not shown, or are shown truncated.

**Related Issues**

**Additional Context**

**Comment by samuelbradshaw** [comment]
Have you tried using the "Don't load blob and text fields until needed" option in Sequel Ace preferences?
<img width="700" alt="Screen Shot 2022-08-11 at 10 26 30 AM" src="https://user-images.githubusercontent.com/7323052/184182555-8af1e8ba-2972-4731-9f02-473e509afca8.png">

**Comment by fulldecent** [comment]
Killer, thank you!
