### ISSUE TITLE
Feature Request: Client-side sorting

### ISSUE THREAD

**Issue by mjaggard** [Sequel-Ace/Sequel-Ace#1533]
Currently when you click on a column in the results table, Sequal Ace will re-run the query with a sort parameter. This is the correct behaviour in some (most?) cases but I have two use-cases where it would be preferable to just sort the data already in the table on the client.

1. When I run `SHOW FULL PROCESSLIST` I cannot sort the data because clicking on the column takes time.
2. When I'm looking at how many rows in a table have each value (for example how many invoices are pending/unpaid/paid/void, or how many belong to each customer) I often run the query with a `GROUP BY` and then don't do the `ORDER BY` - sometimes because I forget, sometimes because I want to see the first results faster.

What I'd like is to be able to sort the table locally on the client. I guess it should be the default for a column header click in the cases that:
1. No LIMIT was specified on the query - either internally in Sequel Ace or explicitly by the user.
2. There are fewer than some number of rows loaded (1000?)
3. The query has completed?

What do you think?

**Comment by Jason-Morcos** [comment]
I don't think I'm a big proponent of this change. Like you said, in most cases going back to the DB to sort makes sense. This would cause the behavior to be inconsistent (cause us to sometimes not reload and sometimes reload) and would require Sequel Ace to implement sorting behavior that matched MySQL. Especially with inconsistencies between different SQL instances (think even just case sensitivity), this could be a real pain and cause confusion in most users. I see this being a support nightmare for limited benefit.

**Comment by mjaggard** [comment]
Fair point. Any chance that there could be a warning to the user if they click on a sort if the query being sorted took more than an amount of time (1 minute?) so that I can at least not lose the data I've got already when I forget?

**Comment by Jason-Morcos** [comment]
> Fair point. Any chance that there could be a warning to the user if they click on a sort if the query being sorted took more than an amount of time (1 minute?) so that I can at least not lose the data I've got already when I forget?

A PR is welcome to add that as an option that can be toggled on/off from the app's preferences!
