### ISSUE TITLE
Quick Connect connection color visible in connection window

### ISSUE THREAD

**Issue by code2prog** [Sequel-Ace/Sequel-Ace#1536]
I think it would be a very good idea to display the accent color from the quick connections in the database management window. Maybe in the header of the window.
I mark myself production databases in red to be careful when editing them, but this information is not visible in the active database connection window
![M40wCZXW6HrV0QRuLACXis5WmkCTqWs3eqsHlG63](https://user-images.githubusercontent.com/22845213/184835479-81899857-4c75-4aae-8b78-2a4069cd9cc0.jpeg)
.

**Comment by Kaspik** [comment]
Duplicated of many issue around. `View` -> `Show tab bar`.
