### ISSUE TITLE
New openssh version can't connect old openssh version server

### ISSUE THREAD

**Issue by smithyj** [Sequel-Ace/Sequel-Ace#1537]
- Sequel Ace Version (including build number):3.5.3
- Sequel Ace Source (App Store/GitHub/Homebrew):GitHub
- macOS Version: MacOS Ventura Version 13.0 Beta(22A5321d)
- Processor Type (Intel/Apple):Intel
- MySQL Version:5.6
- macOS Localization:English Language

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
yes present all version

**Description**
my mac system version in the last week  upgrade the latest version, but upgraded after mac system update openssh version into 9.0, then sequel ace is can't connect server with ssh, my iterm is can't connect server with ssh, but configured ssh config file，after add `HostKeyAlgorithms +ssh-dss` and `PubkeyAcceptedKeyTypes +ssh-rsa`,  iterm is normal connect server with ssh。

**Steps To Reproduce**
1.upgrade mac os system to the latest version
2.connect to openssh 5.x server 

**Expected Behaviour**
keep .ssh config same behaviour

**Related Issues**
#1108 

**Additional Context**
![image](https://user-images.githubusercontent.com/9820142/185017776-349b4297-0890-41e5-baa2-f1149ed38854.png)

![image](https://user-images.githubusercontent.com/9820142/184087783-03b1510f-5eae-4227-95e7-2ffc8205fdf9.png)

**Comment by Jason-Morcos** [comment]
Did you tell Sequel Ace to use your ssh config file in Sequel Ace's preferences? By default, Sequel Ace can't use your .ssh config file without you specifically telling it to due to apple sandboxing.

**Comment by smithyj** [comment]
> Did you tell Sequel Ace to use your ssh config file in Sequel Ace's preferences? By default, Sequel Ace can't use your .ssh config file without you specifically telling it to due to apple sandboxing.

in sequel ace 3.5.3 version，I didn't find `.ssh/config` relation config option

**Comment by smithyj** [comment]
![image](https://user-images.githubusercontent.com/9820142/185080632-13f65ef6-45b0-4f46-b01e-380acb771007.png)
![image](https://user-images.githubusercontent.com/9820142/185080713-825ca6a7-6182-4bc8-a09f-188736681aaf.png)

**Comment by smithyj** [comment]
![image](https://user-images.githubusercontent.com/9820142/185081052-89f9ad68-8834-45cc-96ee-b574f120dc47.png)

**Comment by Jason-Morcos** [comment]
You need to select your personal SSH config in the Network tab of Sequel Ace's preferences. Sequel Ace doesn't just need access to the config, it needs to know to use it

**Comment by smithyj** [comment]
@Jason-Morcos Thank you very much
