### ISSUE TITLE
Save filter content setting in session

### ISSUE THREAD

**Issue by nexbridge** [Sequel-Ace/Sequel-Ace#1540]
If you have the Filter Content option enabled for a given connection tab, would it be possible for this to be saved in the session to avoid you having to re-enable it for each tab every time you open a saved session?  N.B. I'm not asking for specific existing filters to be saved or anything like that, just the fact that table filters are enabled.

**Comment by Jason-Morcos** [comment]
Sorta duplicates #1517?
Have you tried using the cmd+f keyboard shortcut to quickly open filters?

**Comment by nexbridge** [comment]
One is requesting a new option in the preferences and the other a change to the data saved in a session, so similar but different.  :-)

I'm hoping that one or both of them would be fairly simple to do and therefore a quick win.  The cmd+f shortcut is definitely helpful, but if you have a lot of tabs in your session then either this or #1517 would be better.

**Comment by Jason-Morcos** [comment]
Perhaps a three-way (drop-down) setting: always show by default, never show by default, remember last.

PRs welcome! :)

**Comment by nexbridge** [comment]
I guess you could do it in the menu dropdowns or in the Tables tab of the preferences - which one would be better?  Intuitively I'd probably expect it to be in the preferences, but I don't really mind as long as there's a way of doing it!

**Comment by nexbridge** [comment]
Why is this being marked for closure?  Just because a feature request hasn't been actioned yet doesn't mean it should be closed!
