### ISSUE TITLE
Editing ENUM column throws error due to lack of single quotes on default value

### ISSUE THREAD

**Issue by thomasruns** [Sequel-Ace/Sequel-Ace#1541]
- Sequel Ace Version (including build number): 3.5.1 build 20031
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.1
- Processor Type (Intel/Apple): M1
- MySQL Version: 
- macOS Localization: US_en

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
When editing an existing ENUM column with string values, it builds an invalid query unless you manually add single quotes around the default value. This happens even if the default value was not changed. For example, I update an ENUM column to add an additional value, but I don't edit the default value in any way. When I click away to save I get an error. It's a vague error that the query is invalid and eventually I finally figured out it's because I have to put single quotes around the default value every single time.

**Steps To Reproduce**
1. Edit an existing ENUM column that has a string default value
2. Change anything except for the default value. Don't touch that field at all
3. Click away from the row to save
4. Vague error displays

**Expected Behaviour**
I expect one of 2 behaviors:
1) The default value should retain the quotes around it after being saved. That way future edits would not fail.
2) I expect the query that gets run to save my changes would put single quotes around the default value automatically.

**Related Issues**
The same bug was detailed in an issue that was closed for being stale: https://github.com/Sequel-Ace/Sequel-Ace/issues/1461

**Additional Context**
None

**Comment by origamifreak2** [comment]
Something similar is happening when changing a text field to a varchar field.
![text_to_varchar_query_error](https://user-images.githubusercontent.com/2578041/189449639-f46cdb62-c771-494b-84d5-c09a2cbd3f0b.png)

**Comment by fmaltez** [comment]
I have same issue in Version 3.5.2 Build 20033

**Comment by fmaltez** [comment]
Can confirm, while editing a ENUM field in 4.0.0, it strips the quotes, generating an error while editing or adding a ENUM field in a table.

**Comment by didamaran** [comment]
confirmed on v 4.0.1

**Comment by salvor-hardin** [comment]
Same on 4.0.3

Can't this be fixed so the ALTER query automatically adds the quotes for enums if the user doesn't enter them him/herself?

<img width="372" alt="enum_default_bug" src="https://user-images.githubusercontent.com/40695717/201919989-122bcfab-4bf0-4f3f-8669-e44a3658292f.png">

<img width="1572" alt="enum_default_bug2" src="https://user-images.githubusercontent.com/40695717/201919863-5d398033-0a21-404b-8c35-8881e67fd624.png">

**Comment by thomasruns** [comment]
I'm starting to wonder if this should really change to an issue to fix all the bugs related to structure changes. It's rare I make any structure changes in the UI that actually work. Usually I have to copy the ALTER TABLE query from the error message, fix Sequel Ace's bad code, and run it myself.

The latest is I cannot add a new column to an empty table unless I allow NULL or enter a default value. If I uncheck that NULL checkbox, it doesn't remove `DEFAULT` from the query which makes it an invalid query. So SA creates this query:
```ALTER TABLE `table_name` ADD `field_name` VARCHAR(50) NOT NULL DEFAULT;```
but it should be this:
```ALTER TABLE `table_name` ADD `field_name` VARCHAR(50) NOT NULL;```
The same thing happens if I try to edit an existing field that is NOT NULL and doesn't have a default value.

It seems like all of the bugs on the structure tab are related to it building invalid queries, so maybe the real issue is there needs to be better QA around the code that generates those queries before updates are released. I'd be happy to create a new issue for that problem if that would be helpful.

**Comment by Jason-Morcos** [comment]
Sequel Ace is free and open source and doesn't come with any warranties that you might find in a piece of commercial software. With that, "better QA around the code" really isn't something that's a fair request to make of the maintenance team - we're taking time away from our families and other hobbies to contribute to this project with the time that we do. The way to improve the QA around the code is to introduce some new test cases! PRs to fix bugs and/or add new tests are always reviewed and almost always accepted into the code base. We welcome contributions from the community and encourage everyone to take an active role in making this the best tool it can be :)

**Comment by thomasruns** [comment]
@Jason-Morcos Hey Jason, first and foremost, thank you and everyone else for the work you do on this application. It makes my job easier every day and I truly appreciate it.

I fully understand that an open source application like this cannot go through the same type of QA process a commercial product does. Where I was coming from is that on the Structure tab, there are several things that seem to not be tested at all because basic functionality is broken. And by "tested" I don't mean unit tests, I just mean a developer using the feature after they add it to make sure it works. So on my previous comment about "better QA around the code", I think a better way of putting that would be to say "make sure any new features have been tested before being released". We might still disagree on that, but I wanted to at least clear up that I did not mean that I expect a commercial-grade QA process.

As much as I wish I could contribute to the code and fix bugs like this, I don't have experience with Objective C. But I would love to help in some other way. If you have suggestions for anything I could do to help outside of the code, please let me know.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and confirm it's all good - the fix for this issue is included in the latest 4.0.5+ beta!

https://github.com/Sequel-Ace/Sequel-Ace/releases


@thomasruns I'm sorry for the delayed reply - I got wrapped up with the holidays. I definitely appreciate what you're saying here. I know I try to do my best, but sometimes things slip through. The absolute best thing you can do to contribute is to test the betas and release candidates! Letting us know when you find things before we release them really helps us keep bugs from popping up in the releases. Cheers and happy new year!
