### ISSUE TITLE
Strange multi-desktop behaviour

### ISSUE THREAD

**Issue by nexbridge** [Sequel-Ace/Sequel-Ace#1552]
- Sequel Ace Version: 3.5.3 (build 20035)
- Sequel Ace Source: App Store
- macOS Version: 12.5.1
- Processor Type: Intel

I've found a really strange bug that is difficult to replicate, but I've taken a screen recording to give you an idea of what it looks like in case that gives you a clue as to what might be causing it.  It seems to happen sometimes (but not every time) when I wake my Mac from sleep - if I already have database connections open in Sequel Ace (which I usually do) then it tries to reconnect to them before my Mac has finished connecting to my VPN.  I then get a connection failure message in Sequel Ace (which is fine) so I ask it to retry once the VPN has connected and that usually works (although there may be another bug there as one or two times it's just got stuck at that point).  However sometimes once that's done I end up with the strange situation in my screen recording, where Sequel Ace seems to be on two desktops simultaneously (even though I only ever have it on one), and on the second one it's there in a hidden way, with a strange grey box in the centre (which I highlight with the mouse cursor on the recording) that only appears at the top but isn't there when you focus on that desktop.  Since the Mac obviously wakes from sleep on whichever desktop you were in before you put it to sleep, I think it's that desktop that Sequel Ace then gets confused with when it starts throwing connection errors (if the desktop is different from the one that Sequel Ace is on).

https://user-images.githubusercontent.com/13848887/188279093-4a2956e9-6747-4fdd-bf30-24c8df13f4b3.mp4

**Comment by Jason-Morcos** [comment]
Does this issue still happen in the 4.0 beta? We move made quite a few UI/window fixes in that upcoming release

**Comment by nexbridge** [comment]
I will let you know if the behaviour continues in 4.0, although I can't currently replicate it on demand so will just have to wait until it happens again!

**Comment by Kaspik** [comment]
4.0.0 is out (4.0.1 will be asap), so let us know if it persists, in the meantime closing. :)
