### ISSUE TITLE
Search/Filter databases (Feature Request)

### ISSUE THREAD

**Issue by pdscopes** [Sequel-Ace/Sequel-Ace#1554]
Firstly, I love Sequel Ace and use it all the time and have done for many years!

One feature I really like is the ability to filter the tables in a database. My feature request would be to have the same concept for searching/filtering databases. My initial design would be to use the same panel and search bar as used for Table search but provide a means of going "up" or "back" to a list of databases.

 Table Search | Database Search
:-------------:|:------------------:
<img width="328" alt="Screenshot 2022-09-12 at 08 30 00" src="https://user-images.githubusercontent.com/13329586/189597093-4a51f59a-9f96-4dae-b924-9b2bafde4527.png"> | <img width="323" alt="Screenshot 2022-09-12 at 08 32 08" src="https://user-images.githubusercontent.com/13329586/189597873-37c53df5-a9e1-4a16-9945-5bc3148b1001.png">

**Comment by terranc** [comment]
cmd+shift+D
