### ISSUE TITLE
Allow to disable phone home

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#1557]
Currently the app has a phone home.

<img width="505" alt="Screen Shot 2022-09-12 at 16 44 45" src="https://user-images.githubusercontent.com/382183/189755298-f0689a77-7496-45fd-9118-6841d699896c.png">

Please allow to disable this.

**Comment by Jason-Morcos** [comment]
Sequel Ace does not transmit any of the information contained in your database, nor info about you off of your machine. All that gets sent is anonymized usage data that lets us know if things are crashing or if certain parts of the app are slow/unused.

A PR to add a checkbox to the app's Preferences to allow disabling this is welcome if you'd like to make one! :)

**Comment by fulldecent** [comment]
Thank you, PR sent at https://github.com/Sequel-Ace/Sequel-Ace/pull/1564
