### ISSUE TITLE
Working very slow

### ISSUE THREAD

**Issue by lipatovroman** [Sequel-Ace/Sequel-Ace#1565]
- Sequel Ace Version (Version 3.5.3)
- Sequel Ace Source (App Store)
- macOS Version: 12.5 (21G72)
- Processor Type (Intel):

Hello!
Sequel Ace working very slow. I'm talking about basic actions not related to any MySQL base.
Creating new empty tab - 10-15 seconds.
Switching between opened tabs - 5-10 seconds.

**Comment by Kaspik** [comment]
I have two options - ask for more details, or close this and have you fill up the template properly to give us more info.

- What's activity monitor saying?
- Is it on latest beta 4.0.0 too?
- .... and so much more. Please give us more info properly otherwise we can help you, sorry.

**Comment by lipatovroman** [comment]
> > I have two options - ask for more details, or close this and have you fill up the template properly to give us more info.
> > 
> > * What's activity monitor saying?
> > * Is it on latest beta 4.0.0 too?
> > * .... and so much more. Please give us more info properly otherwise we can help you, sorry.
> 
> I have same issue too. I tried beta 4.0.0, and it seems to have resolved the issue.

Other things work normally in the 4th version?

**Comment by Kaspik** [comment]
Yes, 4.0.0 Beta should work normally, we might promote it to RC and release later this / next week already.

**Comment by lipatovroman** [comment]
> Yes, 4.0.0 Beta should work normally, we might promote it to RC and release later this / next week already.

I've downloaded 4.0.0
But after starting, it doesn't have my favorites from 3.xx
Now I have 2 versions indtalled 
Sequel Ace.app
and
Sequel Ace Beta.app

**Comment by Kaspik** [comment]
That's expected. It's two separate apps so you don't have to get rid of the old one. You can easily export your favorites from main app and import them to the Beta.

**Comment by lipatovroman** [comment]
> You can easily export your favorites

How? Is there any manual for that?

**Comment by lipatovroman** [comment]
Ok, tested.
No success.
Sequel Ace 4 - working works worse than 3.x.x
Very slow, and completely freezes on the most basic operations (open new connection, open new tab etc).

**Comment by Kaspik** [comment]
Can you show us Activity manager and similar performance monitoring stuff when it's running slow?

**Comment by Kaspik** [comment]
Release 4.0.0 is out.

If you are still experiencing this, please provide more details like activity monitor, font setup etc. and I'll be happy to reopen.
