### ISSUE TITLE
Where is filter tool?

### ISSUE THREAD

**Issue by lipatovroman** [Sequel-Ace/Sequel-Ace#157]
Hello!
Where is filter from Sequel Pro?
![Screenshot](https://biblsoft.ru/images/monopics/2020-07-02_23-08-44.jpg)

**Comment by stychos** [comment]
Cmd + F or funnel icon in the status bar.

**Comment by lipatovroman** [comment]
OMG, it have multiple filters!!!!!!!
It was so lacking in Sequel Pro.

**Comment by lipatovroman** [comment]
It will be cool to get SQL query (code) from selected filters.

**Comment by SanderVanLeeuwen** [comment]
> It will be cool to get SQL query (code) from selected filters.

Open the console. The executed queries are all there :)
