### ISSUE TITLE
Setting a user password with a backslash sets the wrong password

### ISSUE THREAD

**Issue by charrington-strib** [Sequel-Ace/Sequel-Ace#1573]
- Sequel Ace Version (including build number): 3.5.3, build 20035
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew (I believe)
- macOS Version: 12.6 21G115
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7.12
- macOS Localization: en_US (? guessing)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Have not attempted.

**Steps To Reproduce**
1. Create a new test user.
2. In the UI, set the password to `abcdabcd`.
3. Validate (perhaps in another tab/window) that it's possible to log in using with the password `abcdabcd`.
4. In the user management UI, change the password to `efgh\efgh`
5. Attempt to log in with the password `efgh\efgh`, which fails.
6. Attempt to log in with the password `efghefgh`, which succeeds.

**Expected Behaviour**
Backslashes in passwords should be escaped in the Sequel Ace user management commands, and it should be possible to log in with the password `efgh\efgh`. Note also that if you set the password to `efgh\\efgh`, it is possible to log in with `efgh\efgh`.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and confirm it's all good - the fix for this issue is included in the latest 4.0.5+ beta!

https://github.com/Sequel-Ace/Sequel-Ace/releases
