### ISSUE TITLE
Option to show current table path first before sql version

### ISSUE THREAD

**Issue by LegeBeker** [Sequel-Ace/Sequel-Ace#1575]
I use Sequel ace mostly as a smaller window, and most of the time I can't see at a glance if I am connected to a local or live database. This distinction is in the given name of my bookmarked databases, but because it is after the sql version I will have to hover to see the full path.

**Comment by Kaspik** [comment]
I recommend using colors for the tabs for local vs. prod environment. Also tab shouldn't be showing SQL version but just the info, right?

**Comment by LegeBeker** [comment]
Colors are only visible when choosing a database. 
![image](https://user-images.githubusercontent.com/49623578/196242677-db598750-3096-4318-8d7c-5517be42bb41.png)
This is what I see. There is no indication to show if its the live or local database.

**Comment by LegeBeker** [comment]
Ow, I never saw this option. But maybe the color of the database could be used in the toolbar? So I could see the category without the tab bar? maybe as a dot before the version and name in the toolbar?

**Comment by Kaspik** [comment]
It's not easy to implement custom views in the window.

I'll close this now as I believe we support what you wanted, just slightly differently than you asked. :)
