### ISSUE TITLE
Copy/Paste SQL INSERT bug

### ISSUE THREAD

**Issue by lipatovroman** [Sequel-Ace/Sequel-Ace#158]
Hello!
I need to copy some lines from table to other table.
![Screenshot 1](https://biblsoft.ru/images/monopics/2020-07-03_00-10-52.jpg)

I selected 1764 lines and copied as SQL INSERT.
![Screenshot 2](https://biblsoft.ru/images/monopics/2020-07-03_00-12-58.jpg)

Then I selected another table and added SQL query.
And only 582 rows was added - instead 1764.
[Screenshot 3](https://biblsoft.ru/images/monopics/2020-07-03_00-14-21.jpg)

**Comment by Jason-Morcos** [comment]
@lipatovroman Are you able to verify that the number of rows inserted was actually wrong? Perhaps the displayed rows affected count was incorrect. Can you verify in your DB that the SQL insert was not fully successful?

Right now I don't know if the issue is in creating the SQL insert, running the SQL insert, or returning the number of rows affected. Narrowing this down would greatly help trying to debug this issue.

**Comment by lipatovroman** [comment]
> @lipatovroman Are you able to verify that the number of rows inserted was actually wrong? Perhaps the displayed rows affected count was incorrect. Can you verify in your DB that the SQL insert was not fully successful?
> 

Please, watch this [video](https://biblsoft.ru/images/monopics/2020-07-03_11-27-51.mp4) how it goes

**Comment by lipatovroman** [comment]
> @lipatovroman Are you able to verify that the number of rows inserted was actually wrong? Perhaps the displayed rows affected count was incorrect. Can you verify in your DB that the SQL insert was not fully successful?
> 
> Right now I don't know if the issue is in creating the SQL insert, running the SQL insert, or returning the number of rows affected. Narrowing this down would greatly help trying to debug this issue.

May be I can send you some logs?

**Comment by Jason-Morcos** [comment]
> > @lipatovroman Are you able to verify that the number of rows inserted was actually wrong? Perhaps the displayed rows affected count was incorrect. Can you verify in your DB that the SQL insert was not fully successful?
> 
> Please, watch this [video](https://biblsoft.ru/images/monopics/2020-07-03_11-27-51.mp4) how it working

Video won't load for me.

Really my question is this - did the insert statement that you executed contain 1764 rows? In other words, if you took the SQL produced by "Copy As SQL Insert" and used another tool to apply it, would you get 1764 rows or 582 rows altered?

**Comment by lipatovroman** [comment]
![Screenshot 1](https://biblsoft.ru/images/monopics/2020-07-04_12-05-43.jpg)

![Screenshot 2](https://biblsoft.ru/images/monopics/2020-07-04_12-08-20.jpg)

**Comment by Jason-Morcos** [comment]
@lipatovroman Awesome so it looks like the bundle is working. Now can you verify that that number of rows altered is accurate? In other words, truncate the table. Then run the insert statement. Then run count(*) against that table.

**Comment by lipatovroman** [comment]
Again, I copied 1764 rows, and after pasting I got 519 rows.
I uploaded video on youtube - https://youtu.be/Cn1ORQ668NY

**Comment by Jason-Morcos** [comment]
> Again, I copied 1764 rows, and after pasting I got 519 rows.
> 
> I uploaded video on youtube - https://youtu.be/Cn1ORQ668NY

Please run count(*) against your table after running the SQL insert against the empty table and send that result. From the video I can't tell if 1764 rows were inserted but the count of rows affected was wrong or if 582 rows is correct and the error is in the execution of the insert. Does that make sense?

**Comment by lipatovroman** [comment]
It's not working for me
![Screenshot](https://biblsoft.ru/images/monopics/2020-07-04_22-46-33.jpg)

**Comment by Jason-Morcos** [comment]
> It's not working for me
> ![Screenshot](https://camo.githubusercontent.com/967ff185cce32adeb6af430186489596e1569b94/68747470733a2f2f6269626c736f66742e72752f696d616765732f6d6f6e6f706963732f323032302d30372d30345f32322d34362d33332e6a7067)

`select count(*) from `inspire_content_!!!`

**Comment by lipatovroman** [comment]
> select count(*) from `inspire_content_!!!`

![Screenshot](https://biblsoft.ru/images/monopics/2020-07-04_22-50-17.jpg)

**Comment by Jason-Morcos** [comment]
I think I figured it out! To make sure we don't create giant insert statements, we chunk the insert statements at a certain size to make sure that we create 3 smaller inserts instead of 1 giant insert. Each time, you're only running the last insert statement which only contains ~500 rows. Instead of just running the last (selected) statement, you should choose to run all statements.

<img width="395" alt="Screen Shot 2020-07-04 at 18 50 06" src="https://user-images.githubusercontent.com/10710367/86523837-4e025880-be27-11ea-8c00-c07b8d88530b.png">

Does this solve your problem?

**Comment by lipatovroman** [comment]
> Does this solve your problem?

Yes, thanks.
When I paste SQL query app separate them by parts with 500 rows.
So, we should to start all queries.
