### ISSUE TITLE
Database selector remains grayed out after closing another tab

### ISSUE THREAD

**Issue by garsaud** [Sequel-Ace/Sequel-Ace#1580]
- Sequel Ace Version (including build number): Version 4.0.0 – Build 20036
- Sequel Ace Source (App Store/GitHub/Homebrew): AppStore
- macOS Version: 12.6 (21G115)
- Processor Type (Intel/Apple): Intel Core i7
- MySQL Version: 8.0.29, 5.5, … (the bug is reproduced on various versions)
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes it is.

**Description**
With multiple tabs open, after closing a tab, the other tab’s Database selector becomes grayed out and cannot be used.

https://user-images.githubusercontent.com/3667366/196902652-a32abe7f-0e4a-4a84-a4aa-2cc4d0d28033.mp4

**Steps To Reproduce**
1. Open a connection. Databases are accessible in the selector.
2. Open another connection in a new tab.
3. Close that tab. It will bring you back to the first one.
4. Check the database selector: it is no longer accessible.

**Expected Behaviour**
Database selectors should always remain accessible.

**Additional Context**
After provoking that bug, the app often gets unstable and ends up crashing after a while.

**Comment by Kaspik** [comment]
We had some mess in the release and released wrong build number. Let us please know if it will also an issue on the latest release that will come out today.
