### ISSUE TITLE
Closing a connection window causes crash of remaining opened connection windows

### ISSUE THREAD

**Issue by outie** [Sequel-Ace/Sequel-Ace#1582]
Sequel-Ace version: Version 4.0.0 Build 20036
MacOS version: MacOS Monterey 12.6
Device: Mac mini (M1, 2020)

I always work with multiple connections and windows. After updating to the latest version on the Mac App Store today to 4.0.0 Build 20036, I consistently have an issue where if I close one of the connection windows, my remaining connection windows become unresponsive, with the spinning ball. I tried to wait for minutes but it never recovered, so I have to Force-close the program.

Steps to reproduce:
- Open multiple connection windows
- Close 1 of the windows
- Remaining windows become unresponsive with spinning beach ball and never recover

**Comment by garsaud** [comment]
Seems to be the same bug as https://github.com/Sequel-Ace/Sequel-Ace/issues/1580

**Comment by Kaspik** [comment]
We had some mess in the release and released wrong build number. Let us please know if it will also an issue on the latest release that will come out today.
