### ISSUE TITLE
Autocomplete weirdness

### ISSUE THREAD

**Issue by RedAnt79** [Sequel-Ace/Sequel-Ace#1591]
Hi,

I had issues with autocomplete for a while now, but with the 4.0 version I decided to give it a try again.
Sequel Ace behaves so weird that I assume it might be rather a problem with my machine/installation and not a general one.

I use a Macbook Pro (15", 2017) with macOS 11.6.7

Sequel Ace version is 4.0.1

I have prepared an example, where I just want to type the query from line 1:

![error1](https://user-images.githubusercontent.com/12165828/197746975-a1734ef9-8c44-4a17-b9d4-2ad97e2bfa29.gif)
This gif shows that something is suggested after a space (in this case "accessible") and while I continue to type, this messes up my query.

![error2](https://user-images.githubusercontent.com/12165828/197746960-97afd77a-b638-4138-ae26-33db750cef6c.gif)
This gif shows that the correct table name is suggested and while I continue typing the table name gets messed up and I have to correct it.

Here are my current settings for the query editor:
![2022-10-25 at 12 44](https://user-images.githubusercontent.com/12165828/197753412-44b57ed2-9711-41a4-a228-e16e7b257a7a.jpg)

**Comment by DannyJJK** [comment]
@Kaspik This is reproducible when you type a character at the same time (or almost the same time) as the autocomplete dialog shows. It looks like @RedAnt79 has their auto-completion set to appear very quickly which exacerbates the issue.

So to replicate this:
Get used to the timeframe that the autocomplete dialog shows based on your settings, Then try to type the next character right before the autocomplete dialog is about to display. This should reproduce the issue.

**Comment by RedAnt79** [comment]
For the video i have decreased the delay for the auto-completion to 0.3
It happens to me also when it is set to the default delay (I think 0.5)
