### ISSUE TITLE
SSH key issue on macOS Ventura

### ISSUE THREAD

**Issue by o15a3d4l11s2** [Sequel-Ace/Sequel-Ace#1592]
- Sequel Ace Version (including build number): Version 4.0.1 Build 20039
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 13.0 (22A380) (Ventura)
- Processor Type (Intel/Apple): Intel

**Description**
Cannot connect to a database using SSH after update to Ventura

**Steps To Reproduce**
1. Download macOS 13.0;
2. Setup a new database connection with SSH using SSH key.

**Expected Behaviour**
The database should be successfully connected

**Related Issues**
No known issues with same error

**Additional Context**
- I have *no* special ssh config
- I have deleted the default Sequal Ace known hosts file and retried
- I have tried a ruby script that does the same (connects to the database through SSH) and it succeeds
- I have tried with another database client and it succeeds
Debug as txt file: [debug.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/9867427/debug.txt)

**Comment by Kaspik** [comment]
Just to make sure - did you try removing SA completely, installing again, and setting the settings from scratch? You can export the favorites before uninstalling so you can import them back again.

I saw some weird behavior on my device after the upgrade too BTW - for example VNP connections stopped working. I had to remove all of them and setup again. You might try to go through the settings, reset all the setup and try the fresh install as a first step before we dive in...

**Comment by alexander-schranz** [comment]
I had without macOS Ventura problems in with SSH last week and did workaround by editing `ssh_config` of SequelACE like described in this issue: https://github.com/Sequel-Ace/Sequel-Ace/issues/1309

**Comment by JackSzwergold** [comment]
Hi folks! New user of Sequel Ace here! Discovered it after[ dealing with a post macOS 13 (Ventura) issue](https://github.com/sequelpro/sequelpro/issues/3855#issuecomment-1290987246) with filters and Sequel Pro. So I am working from a clean install and cannot for the life of me get the SSH key I can use cleanly in Sequel Pro to work with Sequel Ace.

No matter what I do, if I set 100% the same settings as Sequel Pro with the key path of `/Users/[username]/.ssh/id_rsa` I keep on getting this dialog about my “login” chain key:

> The SSH password could not be loaded from the keychain; please enter the SSH password for NKQ4HJ66PX.sequel-ace. SequelAce-2545187028927872154:

<img width="465" alt="Screenshot 2022-10-26 at 11 26 35 AM" src="https://user-images.githubusercontent.com/745105/198070987-ac7c2a43-c069-480a-9afb-3514d3e21a4b.png">

I enter what I know my “login” Keychain password is and it just pauses, I assume does something and then the same effing dialog box comes up again and again.

**Comment by o15a3d4l11s2** [comment]
@JackSzwergold, to me it seems you are getting the same issue. Even tough I setup a SSH key, it fails connecting with it (even though it is correct) and fallbacks to a SSH password and shows me the same dialog.

@Kaspik, thank you for the fast response. Yes, I tried removing the app and re-creating the favourite connection but it did not help.

**Comment by 3tlam** [comment]
Hi
Had the same problem, but it was due to my server having an old SSH key size which is no longer supported by Mac OS Ventura.
By adding `PubkeyAcceptedKeyTypes +ssh-rsa` to `~/.ssh/config` and adding it in Sequel Ace -> Preferences -> Network -> SSH Config solved it

See also here https://github.com/Sequel-Ace/Sequel-Ace/issues/1537

**Comment by o15a3d4l11s2** [comment]
> Hi Had the same problem, but it was due to my server having an old SSH key size which is no longer supported by Mac OS Ventura. By adding `PubkeyAcceptedKeyTypes +ssh-rsa` to `~/.ssh/config` and adding it in Sequel Ace -> Preferences -> Network -> SSH Config solved it
> 
> See also here #1537

That was exactly my issue! I have already checked https://github.com/Sequel-Ace/Sequel-Ace/issues/1537 but did not think I was facing the same problem. Thank you! 🙏

**Comment by AntoineThomire** [comment]
Hey,
It looks like I'm currently having the same issue as people here.
The thing is that I also fixed my ssh config file with the PubkeyAcceptedKeyTypes +ssh-rsa, and I did add ~/.ssh/config to my Sequel network preferences.
That look very weird because actually connecting with ssh to my server is working if I use my terminal, but not working with Sequel.

**Comment by allansun** [comment]
Solved my problem!

> Hi Had the same problem, but it was due to my server having an old SSH key size which is no longer supported by Mac OS Ventura. By adding `PubkeyAcceptedKeyTypes +ssh-rsa` to `~/.ssh/config` and adding it in Sequel Ace -> Preferences -> Network -> SSH Config solved it
> 
> See also here #1537
