### ISSUE TITLE
Field Edits no longer saving to database after update to Mac OS Ventura

### ISSUE THREAD

**Issue by sabasjon** [Sequel-Ace/Sequel-Ace#1595]
- Sequel Ace Version (including build number): 4.0.1 Build 20039
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.0
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.18
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
I have latest version as listed on that page

**Description**
When we are editing a field on the Content view, if we PASTE the edits into the popup window for the field, then the pasted content is not saved to the Database.  The field is a 'medium text' and contains some HTML code, when we paste the data into the popup, it shows the updated information, however after clicking OK and unselecting the row (which previously would save the updates to the DB) the updates get lost and the field reverts back to previous data.  NB: If I edit the data 'manually' (so just type something into the Popup window) then the information does get saved, it is only when pasting the data into the window that the data gets lost. This happens if we paste the ENTIRE contents back in including the edits, or if we just paste in just the edit itself - anything pasted in is ignored.

**Steps To Reproduce** (see screen shots below)
1. On Content View, select field on Row to edit
2. Popup sheet appears
3. Paste updated data into popup sheet
4. verify new data is now on Popup sheet
5. Click OK
6. move to next row (or unselect current row I was editing)
7. data reverts to previous

**Expected Behaviour**
When pasting in edits to the field, the data should be saved to the Database

**Related Issues**
None I could find

**Additional Context**
My colleague is on 3.5.3 of Sequel Ace and OS Monterey (12.6) and doesn't have the problem - so I used Time Machine on my Mac to revert back to 3.5.3 of Sequel Ace to test if it was 4.0.1 update - however this older version was still having the problem on my 
machine running OS Ventura - so we have concluded it must be something to do with the OS version rather than the Sequel Ace version.

Step Screen Shots: 
1. On content view, select field on row to edit
<img width="479" alt="image" src="https://user-images.githubusercontent.com/11357950/199000873-3780f3c4-bbd0-4c95-a583-757c6fb6dea1.png">

2. Popup appears
<img width="741" alt="image" src="https://user-images.githubusercontent.com/11357950/199001189-56f2b166-9fa2-4143-93da-263a42eb8b08.png">

3. PASTE in edits (here we have added the 'hello' comment at the start of the HTML string)
<img width="743" alt="image" src="https://user-images.githubusercontent.com/11357950/199001390-ecb6a0f4-487c-4479-bdcc-b15191c2ca83.png">

4. verify new data is now on Popup sheet (as per above screen shot)

5. Click OK - here you can see the pasted comment has already disappeared
<img width="522" alt="image" src="https://user-images.githubusercontent.com/11357950/199001535-f9af1a26-e3ef-4cb5-ba35-748c0b10eb75.png">

6. Unselect Row

7. Data is missing from DB/Row
<img width="358" alt="image" src="https://user-images.githubusercontent.com/11357950/199001716-5b2b728a-6264-458d-8b24-97a512f15008.png">

**Comment by PhilETaylor** [comment]
I have this to - even when making small changes - they are not saved since using the latest Ventura (was fine in the early beta's)

**Comment by sav-valerio** [comment]
Can confirm, running the latest Ventura.
I'm able to save though if I just add a new line to the field.

**Comment by renkosteenbeek** [comment]
Yup got it too. It would be nice to get this one fixed :)

**Comment by reneroth** [comment]
I can't quite define the issue yet. It has something to do with pasting, and on nullable fields this problem can be mitigated by first clearing the field, saving it, and then pasting the new value in. Otherwise something strange is going on, and the edit states (inline vs modal) start behaving strangely. Sorry, I know I should be able to give a better bug report than that, but it really is behaving in a puzzling way.

**Comment by PhilETaylor** [comment]
> It has something to do with pasting

That would be my case for sure. I never type a change, it's always a long string im pasting from elsewhere.

**Comment by starchild** [comment]
Ditto for me too.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now! If it's fixed, we'll push a 4.0.2 final release very very soon

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by renkosteenbeek** [comment]
> Please try the latest beta and let us know if it's fixed now! If it's fixed, we'll push a 4.0.2 final release very very soon
> 
> https://github.com/Sequel-Ace/Sequel-Ace/releases

I just tested it. It works good!

**Comment by sabasjon** [comment]
Just tested 4.0.2 Build 20041 and confirmed this issue is resolved

**Comment by starchild** [comment]
can we get this build loaded to the app store please?

**Comment by Jason-Morcos** [comment]
> can we get this build loaded to the app store please?

This has been loaded onto the App Store and released. We do phases releases, via the App Store, to mitigate the risk of releasing a bad bug into the wild. Releases happen over a 7-day period automatically managed by Apple. To update sooner than your Apple-chosen slot, go to Sequel Ace on the App Store and you should see the download button show the text "update". Click that to force the update right away.

**Comment by starchild** [comment]
> > can we get this build loaded to the app store please?
> 
> This has been loaded onto the App Store and released. We do phases releases, via the App Store, to mitigate the risk of releasing a bad bug into the wild. Releases happen over a 7-day period automatically managed by Apple. To update sooner than your Apple-chosen slot, go to Sequel Ace on the App Store and you should see the download button show the text "update". Click that to force the update right away.

fantastic, ty very much.

**Comment by starchild** [comment]
> > can we get this build loaded to the app store please?
> 
> This has been loaded onto the App Store and released. We do phases releases, via the App Store, to mitigate the risk of releasing a bad bug into the wild. Releases happen over a 7-day period automatically managed by Apple. To update sooner than your Apple-chosen slot, go to Sequel Ace on the App Store and you should see the download button show the text "update". Click that to force the update right away.

fantastic, ty very much.
