### ISSUE TITLE
Content View Filter Row drawing incorrectly on OS Ventura

### ISSUE THREAD

**Issue by sabasjon** [Sequel-Ace/Sequel-Ace#1596]
- Sequel Ace Version (including build number): 4.0.1 Build 20039
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: OS Ventura 13.0
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.18
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
When trying to use the Filter row on the Content View - the buttons on the Right side overlap - the 2nd row no longer appears, to the FILTER button is on top of the - and + buttons so we can no longer click the - button to remove the filter

**Steps To Reproduce**
1. Open Content View
2. Press Ctrl + F to open Filter Row
3. Filter Button is over lapping -  and + buttons

**Expected Behaviour**

Previously the filter button appeared on a 2nd row below the - and + buttons

**Related Issues**

**Additional Context**
Screen Shot attached

<img width="189" alt="image" src="https://user-images.githubusercontent.com/11357950/199003440-82e9b3f6-45ef-41ff-be53-56d337a1747c.png">

**Comment by renkosteenbeek** [comment]
I can confirm this issue.

**Comment by martinstoehr** [comment]
-     Sequel Ace Version (including build number): 4.0.1 Build 20039
-     Sequel Ace Source (App Store/GitHub/Homebrew): App Store
-     macOS Version: OS Ventura 13.0
-     Processor Type (Intel/Apple): Apple
-     MySQL Version: all
-     macOS Localization: English, German

I can confirm this issue.
