### ISSUE TITLE
Privacy Policy for Sequel Ace

### ISSUE THREAD

**Issue by jakob** [Sequel-Ace/Sequel-Ace#1597]
I just checked the Mac App Store page for Sequel Ace, and at a first glance it looks like the app does a lot of tracking (Apologies for the German screenshot):
<img width="813" alt="Bildschirmfoto 2022-11-04 um 15 41 16" src="https://user-images.githubusercontent.com/198305/200002670-3d5ecc28-8e6a-44de-b282-f5698ac627ec.png">

The link to the privacy page goes here: https://moballo.com/privacy-policy/

However, that page doesn't really talk about Sequel Ace itself, it seems very generic.

So I checked the source code on Github, and at first glance I didn't find any tracking/analytics code, but I didn't do a deep inspection.

Could you clarify this? Does Sequel Ace really track my location and app usage?

Does Sequel Ace contain any of the following?
- analytics code
- tracking code
- advertising code
- crash reporting

Does Sequel Ace connect to any 3rd party services?

**Comment by Kaspik** [comment]
Hey Jakob! Great question, I could probably update AppStore.

We do not track location, any personal data or anything - we just have anonymized usage tracking and crash logging enabled via AppCenter Crash logging. You can disable this one in Settings. Other than that, nothing is being collected. ✌🏼

**Comment by jakob** [comment]
Thank you for the clarification!!

My suggestion would be to add a PRIVACY.md file with this info to this repo and just link that from the Mac App Store privacy policy link.

(But I understand if you don't have time for that, it's not the most urgent thing. Thank you for continuing the legacy of CocoaMySQL / Sequel Pro)

**Comment by Kaspik** [comment]
AppStore should be updated (maybe with the new release). Thanks for catching this!
