### ISSUE TITLE
hard-coded paths

### ISSUE THREAD

**Issue by jamesstout** [Sequel-Ace/Sequel-Ace#16]
```
NSString *SPBundleTaskInputFilePath = @"/tmp/SP_BUNDLE_INPUT";
NSString *SPBundleTaskOutputFilePath= @"/tmp/SP_BUNDLE_OUTPUT";
NSString *SPBundleTaskScriptCommandFilePath = @"/tmp/SP_BUNDLE_SCRIPT_COMMAND";
NSString *SPBundleTaskCopyBlobFileDirectory = @"/tmp/SP_BUNDLE_COPY_BLOB_FILES";
NSString *SPBundleTaskTableMetaDataFilePath = @"/tmp/SP_BUNDLE_TABLE_META_DATA";
```

When you try to write to these you get "Operation not permitted", Trying to clean up.

This is in the bundle editor.

Also the bundle editor does weird things with AppleScript and bash runners.

**Comment by Jason-Morcos** [comment]
@jamesstout should be fixed by https://github.com/Sequel-Ace/Sequel-Ace/commit/82584856e5f9d959253220606678a1df6e898086. If so, we can close this one out
