### ISSUE TITLE
Support for "Apply changes" button/confirm before execution of updates

### ISSUE THREAD

**Issue by anatolipr** [Sequel-Ace/Sequel-Ace#160]
This was originally requested for SequelPro back in 2016 and has kept me away and couple of others from switching to use SequelPro for any production projects due to the danger of randomly committing changes...

We need something similar to the current Delete confirmation, but for editing
![image](https://user-images.githubusercontent.com/29383028/86424963-c71f7580-bc98-11ea-9fb3-c18dad4b84c5.png)

Original issue
https://github.com/sequelpro/sequelpro/issues/2615

**Comment by jamesstout** [comment]
Something like this?

![Screenshot 2020-07-03 at 6 37 53 PM](https://user-images.githubusercontent.com/1576190/86461545-bb958280-bd5c-11ea-9c46-05d93627d63d.png)

![Screenshot 2020-07-03 at 6 37 40 PM](https://user-images.githubusercontent.com/1576190/86461632-de279b80-bd5c-11ea-9569-da603720983f.png)

**Comment by jamesstout** [comment]
I've pushed this to a branch: https://github.com/jamesstout/Sequel-Ace/tree/query-warning

https://github.com/Sequel-Ace/Sequel-Ace/compare/dev...jamesstout:query-warning

**Comment by Jason-Morcos** [comment]
@anatolipr were you able to test out @jamesstout's branch? Does that do what you're looking for?

**Comment by anatolipr** [comment]
@Jason-Morcos no, I haven't been able to test that branch yet.

**Comment by jamesstout** [comment]
Here's a quick screencap:

![query-warning](https://user-images.githubusercontent.com/1576190/87011664-cdfb3a80-c1fa-11ea-9771-f1ef708df8d8.gif)

**Comment by Jason-Morcos** [comment]
> Here's a quick screencap:
> 
> ![query-warning](https://user-images.githubusercontent.com/1576190/87011664-cdfb3a80-c1fa-11ea-9771-f1ef708df8d8.gif)

I love it! If you're happy with it @jamesstout, PR?

**Comment by jamesstout** [comment]
#204

**Comment by anatolipr** [comment]
@jamesstout is the confirmation dialog also preventing accidental in-line edits (via the results pane/grid) ?

**Comment by jamesstout** [comment]
No, not yet, it's on the list (in my head).... will create new issue.

**Comment by jamesstout** [comment]
Or see if I get change today to look at it .. it's different code.

**Comment by jamesstout** [comment]
@anatolipr how about this?

![2020-07-10 18 42 37](https://user-images.githubusercontent.com/1576190/87146907-44249d80-c2de-11ea-899b-bebd17857ea7.gif)

**Comment by Jason-Morcos** [comment]
@jamesstout's PR was merged in and is included in 2.1.3! Please try out the beta, @anatolipr 
https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.3-beta1

**Comment by anatolipr** [comment]
Thanks a lot @Jason-Morcos and @jamesstout. 
I just tested the app from 2.1.3-beta1 release and I can confirm that the feature is implemented exactly as I was expecting. Great job @jamesstout! I really appreciate this!

**Comment by rubenjleon** [comment]
Hi.  Just grabbed the latest for today (7/14/2020) and enabled this feature and noticed the warning applies even to select statements.  I don't know why anyone would need to see such a warning on a select statement?  Select statements are considered  "read only" and no harm can be done issuing them.  So as not to further scare someone new to sql with this warning, I'd suggest issuing the warning only on DML statements.  Just a suggestion.  Thank you.

**Comment by samuelbradshaw** [comment]
I agree that it might be better to just have the warning on "potentially destructive" queries.

**Comment by jamesstout** [comment]
So only these:
https://dev.mysql.com/doc/refman/8.0/en/sql-data-manipulation-statements.html
https://dev.mysql.com/doc/refman/8.0/en/sql-data-definition-statements.html

How about these:
https://dev.mysql.com/doc/refman/8.0/en/show.html - should be OK to skip warning.

**Comment by samuelbradshaw** [comment]
`INSERT` and `SELECT` (from link 1), `CREATE` (from link 2) and `SHOW` (from link 3) are the ones that I consider to be non-destructive.

**Comment by jamesstout** [comment]
@Kaspik Could you take a look at this branch please? https://github.com/jamesstout/Sequel-Ace/tree/restrict-query-warning-to-destructive-sql
