### ISSUE TITLE
Unable to edit table content

### ISSUE THREAD

**Issue by lipatovroman** [Sequel-Ace/Sequel-Ace#1602]
Hello!
Latest version 4.0.1
Unable to change content in tables.
Watch this video please: https://directory.audio/images/monopics/2022-11-07_21-39-15.mp4

**Comment by Eligioo** [comment]
Experiencing the same behaviour. It also happens when the LONGTEXT modal pops up and you press Save.

Version 4.0.1
Build 20039

**Comment by Jason-Morcos** [comment]
Duplicates #1595
