### ISSUE TITLE
Sphinx

### ISSUE THREAD

**Issue by dbrown75** [Sequel-Ace/Sequel-Ace#1603]
Used to use the previous versions of Sequel Pro (and nightly build) to connect to Sphinx

http://sphinxsearch.com/

There isn't any tables per se but you could use the query editor to run Sphinx constructed queries. 

Trying to duplicate the connection in Sequel Ace, I get:

Unable to connect to host XXXXXXX, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Unknown MySQL error

So not sure if it's just how Sequel Ace connect is slightly different?   Expects tables or something more specific then what Sphinx is giving back on connection?

Was a very useful feature in debugging Sphinx Data calls.

**Comment by Kaspik** [comment]
There is a newer MySQL driver / framework than the 5 years old one in last Sequel Pro release - it could be that. I have no idea what Sphinx is actually so I won't be any helpful here, but if you could check the console or try running it from Xcode and debug the connection errors in console in Xcode, you might get an idea what's going on.

**Comment by stychos** [comment]
Hi, despite I don't know if Sequel Ace will work with it, I recommend you looking at the ManticoreSearch as a SphinxSearch successor, which is kind outdated.
