### ISSUE TITLE
Unable to select SSH key

### ISSUE THREAD

**Issue by snax4a** [Sequel-Ace/Sequel-Ace#161]
Hello im unable to select SSH key when adding new connection.
Files browser window is not opening when clicking on the "blue key" icon

**Comment by Jason-Morcos** [comment]
@snax4a Unfortunately we'll need more info before we can really help. Please provide:
- Sequel Ace version number
- Sequel Ace build number
- macOS version

Additionally, please download the latest beta from the GitHub releases page for this project. Does the issue persist in the latest beta?

**Comment by snax4a** [comment]
sequel ace version 2.1.0
Build 2042
macOS Catalina 10.15.3
I cant find the github releases page

**Comment by jamesstout** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/releases

Try 2.1.1 Beta 3

**Comment by snax4a** [comment]
it works here, thanks
