### ISSUE TITLE
ENUM display on Content View is misaligned with other datatypes

### ISSUE THREAD

**Issue by salvor-hardin** [Sequel-Ace/Sequel-Ace#1620]
- Sequel Ace Version (including build number): 4.0.3
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 13.0.1
- Processor Type (Intel/Apple): Intel & Apple
- MySQL Version: MariaDB 10.6.11
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yup

**Description**
The content view displays misalignment for ENUM datatypes.

<img width="255" alt="enum_display_off" src="https://user-images.githubusercontent.com/40695717/201920296-49fc06c4-39f2-4641-9d68-cafe208dfe47.png">

**Steps To Reproduce**
1. Create a table with enum and any other datatype. Enter 1 line with any data. Misalignment on enums when'd displaying content.

**Expected Behaviour**
Data to be displayed aligned horizontally.

**Comment by intrepidws** [comment]
Using certain fonts and sizes, this has a far more drastic impact - resulting in the text barely being legible. See the attached screenshot.

<img width="444" alt="Screenshot 2022-12-06 at 9 10 55 AM" src="https://user-images.githubusercontent.com/125735/205934804-ba94ac24-7f35-4bc4-84de-214de6e529a1.png">

**Comment by Jason-Morcos** [comment]
Please try the latest beta and confirm it's all good - the fix for this issue is included in the latest 4.0.5+ beta!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by intrepidws** [comment]
This release fixes the issue that I was having, thanks.
