### ISSUE TITLE
"Copy with Column Names" shouldn't include column type

### ISSUE THREAD

**Issue by samuelbradshaw** [Sequel-Ace/Sequel-Ace#1623]
- Sequel Ace Version (including build number): 4.0.3 20042
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.6.1 (Monterey)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.25
- macOS Localization: English (en)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes (there isn't a beta newer than the latest released version)

**Description**
The column type shouldn't be included when copying rows from a table or query result using "Copy with Column Names."

**Steps To Reproduce**
1. Connect to a database with content.
2. Go to the Content tab and select a table, OR run a query in the Query tab, to get several rows of content.
3. Select all of the rows.
4. In the menu, choose Edit > Copy with Column Names (or use the keyboard shortcut, ⌥⌘C).
5. Paste the copied rows in an empty spreadsheet or text document.

**Expected Behaviour**
Data should be pasted as tab-separated values. The first row that's pasted should be the column names, without column types.

**Actual Behaviour**
Column types are pasted with the column names. See screenshot below.

**Related Issues**
Issue https://github.com/Sequel-Ace/Sequel-Ace/issues/1610 (fixed in pull request https://github.com/Sequel-Ace/Sequel-Ace/pull/1612)
Issue https://github.com/Sequel-Ace/Sequel-Ace/issues/1614
Pull request https://github.com/Sequel-Ace/Sequel-Ace/pull/1606

**Additional Context**
This problem was introduced with pull request https://github.com/Sequel-Ace/Sequel-Ace/pull/1588.

<img width="1663" alt="Screen Shot 2022-11-15 at 4 36 53 PM" src="https://user-images.githubusercontent.com/7323052/202047405-d4b9863b-2a44-49c6-b65c-8da9695127b3.png">

**Comment by ceavestone** [comment]
Same problem occurs while Exporting also

"id INT","created_at TIMESTAMP","updated_at TIMESTAMP","deleted_at TIMESTAMP",

**Comment by fmaltez** [comment]
I second this. The column type in copy with column names should not include the column type.

At least it should be an option to disable such inclusion in the settings.

**Comment by Alfian5229** [comment]
im using Version 4.0.3 (20042) and this issue still persist

**Comment by Jason-Morcos** [comment]
The fix to this will be included in the 4.0.4 release!
