### ISSUE TITLE
brew install is still installing 4.0.1 instead of 4.0.3 version

### ISSUE THREAD

**Issue by msankhala** [Sequel-Ace/Sequel-Ace#1624]
- Sequel Ace Version: **4.0.1 (20039)**
- Sequel Ace Source (App Store/GitHub/Homebrew): **Homebrew**
- macOS Version: **12.6.1 (21G217)**
- Processor Type (Intel/Apple): **Intel**
- MySQL Version: 
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
```
❯ brew reinstall --cask sequel-ace
==> Downloading https://github.com/Sequel-Ace/Sequel-Ace/releases/download/production/4.0.1-20039/Sequel-Ace-4.0.1.zip

```

**Expected Behaviour**
brew should install the latest version of sequel ace which is 4.0.3.

**Comment by Jason-Morcos** [comment]
We don't support the Homebrew install officially. I'm not sure who creates that brew build or manages it

**Comment by Jason-Morcos** [comment]
Looks like it's been updated to 4.0.3 though now! https://formulae.brew.sh/cask/sequel-ace
