### ISSUE TITLE
Can't Open User Config File error when using proxyjump server

### ISSUE THREAD

**Issue by CorbaDigitpaint** [Sequel-Ace/Sequel-Ace#1635]
- Sequel Ace Version: Version 4.0.3 (Build 20042)
- Sequel Ace Source: App Store
- macOS Version: Ventura 13.0
- Processor Type: Apple M1
- MySQL Version: 5.5.5-10.6.10-MariaDB
- macOS Localization: ??

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Could not find a latest beta after v[4.0.3](https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F4.0.3-20042)

**Description**
When using SSH to connect to a database client, we use a proxyjump to connect to the remote host over SSH. When setting up a proxyjump in the ssh_config of Sequel Ace, the application throws an error. Likely due to the facts that the command does not use quotes in the definition of the config file. 

**Steps To Reproduce**
1. Go to `/Applications/Sequel Ace.app/Contents/Resources`
2. Add the following lines to the ssh_config file, just above the `host *`: 

```
Host *.access.xxx.com
  ProxyJump sshproxy.xxx.com
```
4. Go to Sequel Ace and setup a connection over SSH
5. Hit "Connect"

**Observed Behaviour**
The following error is shown:

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/johndoe/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict" -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -i /Users/johndoe/.ssh/id_rsa.ppk -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 johndoe@instance4.access.xxx.com -L 54287:db1.customer.xxx.com:3306

OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *.access.xxx.com
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 4: Applying options for *
debug1: Setting implicit ProxyCommand from ProxyJump: /usr/bin/ssh -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -v -W '[%h]:%p' sshproxy.xxx.com
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Executing proxy command: exec /usr/bin/ssh -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -v -W '[instance4.access.xxx.com]:22' sshproxy.xxx.com
debug1: identity file /Users/johndoe/.ssh/id_rsa.ppk type -1
debug1: identity file /Users/johndoe/.ssh/id_rsa.ppk-cert type -1
debug1: identity file /Users/johndoe/.keys/id_rsa type -1
debug1: identity file /Users/johndoe/.keys/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
OpenSSH_9.0p1, LibreSSL 3.3.6
**Can't open user config file /Applications/Sequel: No such file or directory**
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
The SSH Tunnel has unexpectedly closed.
```

My assumption is that this happens in this part of the command (due to missing quotes):
`-F /Applications/Sequel Ace.app/Contents/Resources/ssh_config`

**Expected Behaviour**
Expected a connection made to my db1.customer.xxx.com MariaDB instance.

**Related Issues**
-

**Additional Context**
-

**Comment by Jason-Morcos** [comment]
This is probably because Sequel Ace is sandboxed - this means that Sequel Ace can't use other executables (which I assume ProxyJump is) to connect to outside hosts. The solution here would be to open a tunnel outside of sequel ace and then connect to that tunnel via TCP.

**Comment by Jason-Morcos** [comment]
These other issues may be relevant to you: 
https://github.com/Sequel-Ace/Sequel-Ace/labels/Sandboxing

There is no known workaround to make this work today - Apple is very stubborn about the sandbox

**Comment by CorbaDigitpaint** [comment]
Thank you for your response Jason!

I managed to solve this by reverting the changes I made in the `ssh_config` file from Sequel Ace and placing this ProxyJump setting this in the `ssh/config` file of my (Apple) user. Then, I could just select that SSH Config file in the Sequel Ace Settings > Network tab .

I will close this issue now.
