### ISSUE TITLE
Default sort `id` or `primary key` by desc

### ISSUE THREAD

**Issue by phoenixg** [Sequel-Ace/Sequel-Ace#1639]
Currently the default sort is by asc, commonly I want display by desc, it's not convenient(even by `shift + click`) to alter to desc, hope it will support sort by desc as a default.

**Comment by samuelbradshaw** [comment]
Related: Issue https://github.com/Sequel-Ace/Sequel-Ace/issues/1267, Issue https://github.com/Sequel-Ace/Sequel-Ace/issues/1374

**Comment by Jason-Morcos** [comment]
Closing in favor of duplicate #1374
