### ISSUE TITLE
$SP_SELECTED_TABLES is no longer populating for Bundles

### ISSUE THREAD

**Issue by binlabs** [Sequel-Ace/Sequel-Ace#1645]
- Sequel Ace Version (including build number): 4.0.3 Build 20042
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.0.1
- Processor Type (Intel/Apple): Apple M1 Pro
- MySQL Version: 14.14 Distrib 5.7.24, for osx10.9 (x86_64)
- macOS Localization: en-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes.

**Description**
The `$SP_SELECTED_TABLES` variable is no longer being populated when executing a Bundle. Outputting it with `echo` will produce an empty string.

**Steps To Reproduce**
1. When connected to a database, select a table from the table listing in the sidebar
2. Open the _Bundles_ menu from the toolbar
3. Choose _Open_ > _Open Selected Table with..._

If you don't move your mouse, you will see an HTML tooltip with an error message that says "Please select a table."

**Expected Behaviour**
`$SP_SELECTED_TABLES` should contain the name of the table(s) currently selected. I am unsure of the exact format it used to be in.

**Additional Context**
While there may only be this one default bundle that is still using this variable, I do also have custom bundles that depend on it, and I know others do as well.

I know this issue existed for me in the 4.0.1 release as well. It could also simply be a Ventura bug. Interested to see if other people can re-produce, and if it is also happening to users still on Monterey.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and confirm it's all good - the fix for this issue is included in the latest 4.0.5+ beta!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by binlabs** [comment]
@Jason-Morcos Thank you so much for fixing this one. The version with this fix has made it out to the App Store in the past day or so, and it works great!
