### ISSUE TITLE
Export SQL broken in 4.0.3

### ISSUE THREAD

**Issue by renkosteenbeek** [Sequel-Ace/Sequel-Ace#1649]
- Sequel Ace Version (including build number): Version 4.0.3 Build 20042
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 13.0.1 (22A400)
- Processor Type (Intel/Apple): Apple Silicon 
- MySQL Version: 5.7
- macOS Localization:  US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
It's fixed in the latest beta.

**Description**
When exporting a database as SQL file, for each individual record an INSERT INTO line is created. The first line consist of a broken query without VALUES. 
This has the following impact: Errors while importing; a much slower import.

It's fixed using the latest Beta. I think the Beta should be released soon.

**Steps To Reproduce**
1. Select a database
2. Export as SQL file.

**Expected Behaviour**
Many records should be inserted using one query; no broken query should apparent.

**Comment by Kaspik** [comment]
Yeah this is already fixed, we will have 4.0.4 out soon!
