### ISSUE TITLE
cosmetic issue (color checkboxes)

### ISSUE THREAD

**Issue by helptiger** [Sequel-Ace/Sequel-Ace#165]
- Sequel Ace Version: 2.1.1 beta 5
- macOS Version: 10.14.6

**Description**
color of checkboxes inconsistent 

![Screenshot-04-19-2020_12_19_02](https://user-images.githubusercontent.com/10258902/86510642-cea66200-bdf1-11ea-9cb1-1032503f6c01.jpg)

**Steps To Reproduce**
1. select multiple tables (more than 12!)
2. right click export as sql dump
3. scroll down or up
4, when switching to cvs and back, checkboxes are consistent 

**Expected Behaviour**
no color inconsistents

**Comment by Jason-Morcos** [comment]
As we have received no reports of this issue in version 3+ of Sequel ace, I'm gonna close this issue. If you experience this issue again in the latest release of Sequel Ace, please create a new issue and reference this issue number in your description.
