### ISSUE TITLE
There are no horizontal scrollbars in the database table view

### ISSUE THREAD

**Issue by axelf** [Sequel-Ace/Sequel-Ace#1655]
- What version of Sequel-Ace are you using?
Version 4.0.3 20042

- What version of macOS are you running on?
macOS Monterey 12.6

If i resize the window i can see the horizontal scrollbar but after stopping the resize a can't see and use a scrollbar. For large database tables not very useful.

**Comment by Kaspik** [comment]
Video / GIF / screenshot? Have you tried beta version as well?

Would be nice to gather as much data as possible.

**Comment by Kaspik** [comment]
Indeed this is what's your system settings.

**Comment by axelf** [comment]
By using the trackpad it is working but i use the mouse and a second monitor. None of the sysem settings does work for me.

**Comment by axelf** [comment]
I made an update to macOS Ventura 13.1 and now i can see the scrollbars.
