### ISSUE TITLE
"Copy with Column Headers" shouldn't include data type details

### ISSUE THREAD

**Issue by jmozen** [Sequel-Ace/Sequel-Ace#1658]
When you run a query and try to copy and paste the results quickly out to a spreadsheet, the "Copy with Column Headers" option includes the data type for each column. It's fine to see that detail when you're viewing the query pane in the app but I have never found a need for it once the data is in Excel. I have to manually go through and remove that data from every column header.

Yes, I know you can export to CSV but the copy and paste option is so much faster ... or it would be if I didn't have to manually edit every column header. I've looked through the settings several times and haven't found any way to get rid of the data type details.

I would very much appreciate the option to "Copy with Column Headers without Data Type".

**Comment by samuelbradshaw** [comment]
Related: Issue #1623

**Comment by jmozen** [comment]
> Related: Issue #1623

Thanks - I looked through everything open and didn't find an existing issue. Turns out it was already marked closed.

**Comment by Jason-Morcos** [comment]
This should have been fixed in 4.0.4. If this issue is persisting, please open a new issue and fully fill out the issue form template including information like Sequel Ace version and steps to reproduce.
