### ISSUE TITLE
App Keeps Losing Focus Moving behind other apps

### ISSUE THREAD

**Issue by chalamministries** [Sequel-Ace/Sequel-Ace#1659]
- Sequel Ace Version (including build number): 4.0.4 Build 20044
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.0.1
- Processor Type (Intel/Apple): Intel
- macOS Localization: US/en

**Description**
Upon clicking on different tables, Sequel Ace will pop behind all my apps. Its not just a specific app that pops up over it. Any apps that are open (and not minimized) will come to the front and Sequel Ace goes to the back. And it does not do it all the time. It appears to do it if I have not navigated through the database after a little while. So maybe if it tries to reconnect to the DB after having timed out? So usually after a minute?

**Comment by Kaspik** [comment]
Duplicate.
