### ISSUE TITLE
SSH Tunnel exiting before local forwarding established

### ISSUE THREAD

**Issue by dj95** [Sequel-Ace/Sequel-Ace#166]
- Sequel Ace Version: 2.1.1 rc 2
- macOS Version: 10.15.5
- MySQL Version: 5.7

**Description**
The ssh tunnel sets the accept state, such that the MySQL connection is built up, when it finds the string "Entering interactive session." is found. But when the connection is built up through a different jump proxies, the string "Entering interactive session" might occur when the login on one of these jump proxies was performed. You can assure, that the tunnel is available, when the string "Local forwarding listening on" was printed from the ssh binary.

**Steps To Reproduce**
1. SSH Jump Proxy configuration with Interactive session after the first hop
2. Choosing a custom ssh configuration file in Sequel Ace
3. Connecting to the mysql server with the ssh options
4. The connection gets closed

**Expected Behaviour**

A connection to mysql should be established.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Additional Context**

Another bug is, that when you add a file to the secure bookmarks in the "files" tab of the preferences, it overrides the selected ssh config file. This is due to an error in my last pull request.

**Update** I was too slow with the versioning.

**Comment by DieselDrax** [comment]
Hi,

I just downloaded 2.1.2-beta1 and we use ssh jump hosts to access our MySQL servers, however the bug with the ssh tunnel being terminated before it's fully established still isn't fixed.  I can copy and run the exact command that Sequel Ace is running for ssh and it connects fine, so it's not an issue with ssh itself.  The connection error window is also either truncating the output or is still indicating that it's trying to connect after seeing "connection established" at which point the tunnel hasn't been set up yet.

**Comment by dj95** [comment]
Hi @DieselDrax,

can you provide a few more information? E.g.:

- Which macOS version are you running?
- Which ssh version is installed(`ssh -V`)?
- How many jump proxies are involved and how are they set up in the config(e.g. with `ProxyJump` or with `ProxyCommand`)?
- Which SSH Version is installed on the jump proxies and destination?

**Comment by DieselDrax** [comment]
> Hi @DieselDrax,
> 
> can you provide a few more information? E.g.:
> 
> * Which macOS version are you running?
> * Which ssh version is installed(`ssh -V`)?
> * How many jump proxies are involved and how are they set up in the config(e.g. with `ProxyJump` or with `ProxyCommand`)?
> * Which SSH Version is installed on the jump proxies and destination?

* macOS 10.15.5
* Local SSH version: OpenSSH_8.1p1, LibreSSL 2.7.3
* There is only one jump host involved, in this case it's not specifically set to use ProxyJump or ProxyCommand, all we have is the jump host as the 'SSH Host' and the MySQL DB host as the 'MySQL Host.'  This setup has worked with Sequel Pro for ages and we were hoping it would still work with Sequel Ace, but it doesn't.  Authentication is done via ssh agent and not static key pairs so I'm specifying my own .ssh/config file which has 'IdentityAgent' set.  The error output is as follows, which is the same output I got with the current release version.
* Remote ssh server version:  debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/XXX/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Users/XXX/.ssh/config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 jump.host -L 65136:database.host:3306

OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/XXX/.ssh/config
debug1: /Users/XXX/.ssh/config line 58: Applying options for jump.host*
debug1: /Users/XXX/.ssh/config line 62: Deprecated option "useroaming"
debug1: /Users/XXX/.ssh/config line 78: Applying options for *
debug1: /Users/XXX/.ssh/config line 82: Deprecated option "useroaming"
debug1: Connecting to jump.host [jump.host.ipv6.ip] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
load pubkey "/Users/XXX/.ssh/id_rsa": Operation not permitted
debug1: identity file /Users/XXX/.ssh/id_rsa type -1
debug1: identity file /Users/XXX/.ssh/id_rsa-cert type -1
debug1: identity file /Users/XXX/.ssh/id_dsa type -1
debug1: identity file /Users/XXX/.ssh/id_dsa-cert type -1
debug1: identity file /Users/XXX/.ssh/id_ecdsa type -1
debug1: identity file /Users/XXX/.ssh/id_ecdsa-cert type -1

```

**Comment by dj95** [comment]
Thank you for the details! 

I think, the error is not in the establishment of the tunnel. If you take a look at the log, it says the following:

```
load pubkey "/Users/XXX/.ssh/id_rsa": Operation not permitted
```

Does it resolve your issue, when you add the private and public key to the files, Sequel Ace has access to? To do so, open the preferences and add them in the files tab.

For security reasons, Sequel Ace runs in a sandbox, which prevents it from accessing files, that you do not grant explicitly. Therefore it cannot access the key by default.

**Comment by DieselDrax** [comment]
> Thank you for the details!
> 
> I think, the error is not in the establishment of the tunnel. If you take a look at the log, it says the following:
> 
> ```
> load pubkey "/Users/XXX/.ssh/id_rsa": Operation not permitted
> ```
> 
> Does it resolve your issue, when you add the private and public key to the files, Sequel Ace has access to? To do so, open the preferences and add them in the files tab.
> 
> For security reasons, Sequel Ace runs in a sandbox, which prevents it from accessing files, that you do not grant explicitly. Therefore it cannot access the key by default.

Please note that I mentioned we don't use keys, we use the ssh agent (which contains certificates).  In this case, .ssh/id_rsa doesn't even exist so there's no file to add.

**Comment by dj95** [comment]
With ssh-certificates it needs access to the private key as well. A certificate is, more or less, a signed public key(I know, it's a pretty loose explanation). The target server will verify the signature of the certificate and then create a challenge, that is only solvable by owning the private key.

Even if the ssh-agent holds your identity, the ssh binary, called by Sequel Ace, still needs to open the file in order to authenticate against the server.

With Sequel Pro it worked, as Sequel Pro does not run in a sandbox and therefore is able to access all files on your file system.

**Comment by DieselDrax** [comment]
> With ssh-certificates it needs access to the private key as well. A certificate is, more or less, a signed public key(I know, it's a pretty loose explanation). The target server will verify the signature of the certificate and then create a challenge, that is only solvable by owning the private key.
> 
> Even if the ssh-agent holds your identity, the ssh binary, called by Sequel Ace, still needs to open the file in order to authenticate against the server.
> 
> With Sequel Pro it worked, as Sequel Pro does not run in a sandbox and therefore is able to access all files on your file system.

No, with our systems there are no private keys.  Everything is handled with the agent and on the remote side the certificates presented by the agent are verified with a CA file on each remote server.  The certificates in our agents are issued by a central server and we use Yubikeys and these certificates to authenticate.  Literally the only file I need in my ~/.ssh directory is my config.  No other files whatsoever are needed for us to authenticate with our remote servers which is by design for security purposes.

Manually running the same command that Sequel Ace runs shows that none of the default keys exist.  This is not a problem as authentication still succeeds.

```
debug1: identity file /Users/XXX/.ssh/id_rsa type -1
debug1: identity file /Users/XXX/.ssh/id_rsa-cert type -1
debug1: identity file /Users/XXX/.ssh/id_dsa type -1
debug1: identity file /Users/XXX/.ssh/id_dsa-cert type -1
debug1: identity file /Users/XXX/.ssh/id_ecdsa type -1
debug1: identity file /Users/XXX/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/XXX/.ssh/id_ed25519 type -1
debug1: identity file /Users/XXX/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/XXX/.ssh/id_xmss type -1
debug1: identity file /Users/XXX/.ssh/id_xmss-cert type -1
...
debug1: Offering public key: TouchlessSSH-2954297b ECDSA-CERT SHA256:cqTApe6ddoGyaCb/bWxO342iMuxvqlJC1HhU7WTZaFg agent
debug1: Server accepts key: TouchlessSSH-2954297b ECDSA-CERT SHA256:cqTApe6ddoGyaCb/bWxO342iMuxvqlJC1HhU7WTZaFg agent
debug1: Authentication succeeded (publickey).
Authenticated to jump.host ([jump.host.ipv6.ip]:22).
debug1: Local connections to LOCALHOST:58522 forwarded to remote address mysql.database.server:3306
debug1: Local forwarding listening on 127.0.0.1 port 58522.
```

**Comment by dj95** [comment]
In this case, the private and public key are saved on the Yubikey. Since I do not have a Yubikey, I do not really know, how the authentication with this one works.

When I search for documentation about ssh authentication with Yubikey, I find some mentioning the gpg-agent, which provides the key from the Yubikey to the ssh-agent. Can you confirm this?

**Comment by DieselDrax** [comment]
> In this case, the private and public key are saved on the Yubikey. Since I do not have a Yubikey, I do not really know, how the authentication with this one works.
> 
> When I search for documentation about ssh authentication with Yubikey, I find some mentioning the gpg-agent, which provides the key from the Yubikey to the ssh-agent. Can you confirm this?

We don't use gpg-agent, we have an internal tool that connects to a central certificate server which generates the certificate you see above, the tool then loads that certificate into the Yubukey via the yubico-agent process and a socket to the agent which is ~/.yubiagent/sock, which may be the issue here as I see no (easy) way to add access to the socket in Sequel Ace.

Agent:
```
yubico-agent --sock /Users/XXX/.yubiagent/sock --log /Users/XXX/.yubiagent/log
```

SSH config to use the socket to reach the certificates via the agent:
```
IdentityAgent ~/.yubiagent/sock
```

If it can't connect to this socket then authentication will fail.  That's the only file, outside of my ~/.ssh/config, that Sequel Ace should need access to.  Is there a file that I can manually edit to give permissions to the socket since it doesn't show up in the "Add files" window even with "show hidden files" enabled.

**Comment by Jason-Morcos** [comment]
@DieselDrax I think your issue may be related to #94. I don't think the issue is local forwarding, I think it's sandboxing.

**Comment by DieselDrax** [comment]
> @DieselDrax I think your issue may be related to #94. I don't think the issue is local forwarding, I think it's sandboxing.

It may be related but isn't exactly the same.  I do agree that it's likely to do with sandboxing and was hoping I could manually add the path to the yubico-agent socket to allow it as I think that would do the trick.  Our ssh clients aren't interfacing with the PKCS11 library directly, as far as ssh itself is concerned our setup is pretty simple and it does all agent/Yubikey interaction through ~/.yubiagent/sock.  Sorry for taking this issue off-track while working through what we're experiencing.

**Comment by Jason-Morcos** [comment]
@DieselDrax Your issue might also have something to do with #113.
Go ahead and create a separate issue describing your problem so that we don't keep polluting this issue! :)
