### ISSUE TITLE
SSH password issue on macOS Ventura

### ISSUE THREAD

**Issue by gerbz** [Sequel-Ace/Sequel-Ace#1674]
- Sequel Ace Version (including build number):Version 4.0.4 Build 20044
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.5
- macOS Localization: English
- Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)? Yes

**Description**
Getting `SSH connection failed!` error when connecting via SSH to saved connection using an SSH Password (not a key).  Also tried:
- Re-adding fresh connection details (same error)
- Editing `ssh_config` like described in #1309 
- Editing `~/.ssh/config` like described in #1592
- Connecting with Sequal Pro, same error

**Steps To Reproduce**
1. Try connecting via SSH using a password on MacOS Ventura 13.1

**Expected Behaviour**

**Related Issues**
- #1592 
- #1537

<img width="505" alt="Screenshot 2023-01-03 at 2 02 16 PM" src="https://user-images.githubusercontent.com/1421206/210445994-347c8874-5ac2-4dd2-b8cc-6723ceee76ab.png">

**Comment by Kaspik** [comment]
Recently we had similar issue in https://github.com/Sequel-Ace/Sequel-Ace/issues/1660 and the comment talks about how it got resolved. Did you try that?

**Comment by gerbz** [comment]
Thanks @Kaspik , yup I've tried everything described [here](https://github.com/Sequel-Ace/Sequel-Ace/issues/1660#issuecomment-1366027981) and still not working.

Not sure it's relevant as I'm pasting in the password when configuring the connection, not using local keys.

**Comment by samuelbradshaw** [comment]
Are you able to SSH to the server in the Terminal?

**Comment by gerbz** [comment]
@samuelbradshaw yes

**Comment by Jason-Morcos** [comment]
Can you post a obfuscated-as-necessary screenshots of your files and network tabs of Ace's settings and the connection settings, and an obfuscated version of your ssh config if you have a custom one set up?

**Comment by Jason-Morcos** [comment]
Ope I just saw you're using MySQL 5.5. That's probably the issue. We don't support MySql 5.5 (see the readme).

MySQL 5.5 reached end-of-life in 2018. Please update to a newer version of MySQL
