### ISSUE TITLE
ssh issue

### ISSUE THREAD

**Issue by ligne13** [Sequel-Ace/Sequel-Ace#1681]
Hi,

my Sequel Ace fails to connect via ssh. It used to work.

One line of the command verbose log is:

debug1: Trying private key: /Users/Maxime/.keys/id_rsa
no such identity: /Users/Maxime/.keys/id_rsa: No such file or directory

But my keys are stored in /Users/Maxime/.ssh not /Users/Maxime/.keys

Is this something new in Sequel Ace ?
Is it possible to tell Sequel to look into .ssh instead of .keys ?

thanks

**Comment by samuelbradshaw** [comment]
In Sequel Ace Settings, on the Network tab, what do you have set for "SSH Config" and "Known Hosts"? Also, in Settings under the Files tab, are your SSH config and key files added as accessible files? Finally, on the connection window where you enter your connection details, do you have the correct path to the SSH key in the SSH section?

**Comment by ligne13** [comment]
Hi,

I had nothing configured in the Network tab. I have now selected /Users/Maxime/.ssh for ssh config and ssh known hosts, but it still does not work.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/81624/211629833-164eeedb-5a05-431d-97ce-6ed436d14c6b.png">


Under the Files tab, I have /Users/Maxime/.ssh and /Users/Maxime/.ssh/id_rsa
<img width="471" alt="image" src="https://user-images.githubusercontent.com/81624/211629880-bf5c1886-1313-40ee-8f3f-cc52ab8a41dc.png">


On the connection window, the path to the ssh key seems OK :
<img width="456" alt="image" src="https://user-images.githubusercontent.com/81624/211630038-51cd5323-eca9-45dc-a26c-ea39ddae8fd5.png">

Thanks

**Comment by Jason-Morcos** [comment]
@ligne13 You need to select the actual SSH config file and SSH known hosts files (not just the directory itself). Or you can revert to the Sequel Ace defaults for both options. Those current options for SSH Config and Known hosts in your screenshot definitely will not work.

**Comment by ligne13** [comment]
Thank you @Jason-Morcos , I changed but it still does not work.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/81624/211632941-0ac5f888-ec13-424c-aeaf-fb40890bf750.png">

I also tried with Sequel default files, it does not work either.

However, I think the problem is related to the server I am trying to connect to, because I have another ssh connection on another server which is working fine.

**Comment by ligne13** [comment]
Yet this is strange : Sequel Ace cannot connect but when I try the command (printed in the debug log) in my Terminal, it works...

ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/Maxime/.ssh/known_hosts" -F /Users/Maxime/.ssh/config -i /Users/Maxime/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 xxxxxx@xxxxx -L 57366:database.internal:3306

Any idea why Sequel fails when using the same command internally ?

**Comment by samuelbradshaw** [comment]
You may also need to grant Sequel Ace access to the config and known_host files as well, in Settings > Files tab.

**Comment by ligne13** [comment]
I did it.

**Comment by samuelbradshaw** [comment]
In one of your screenshots where it shows the list of SSL Cipher Suites, it shows a header "Disabled Cipher Suites." Is there anything that's not disabled, i.e. above that header – or is everything in the list under disabled?

**Comment by ligne13** [comment]
I do have enabled Cipher suites :

<img width="883" alt="image" src="https://user-images.githubusercontent.com/81624/211638438-3f678a94-e8d8-46e4-aff7-ce1f666f988d.png">

**Comment by Jason-Morcos** [comment]
Often if it works in the terminal and not in Ace, you do need to actually select your ssh config in the network tab of the app's settings. Can you try again with that change and send us a screenshot of the network tab again with this change in place if it doesn't work?

Additionally, what version of MySQL is this?

**Comment by ligne13** [comment]
Hi,

it's not working. Here is the screenshot:
![image](https://user-images.githubusercontent.com/81624/211752833-83d2c3a0-6547-4d4e-b978-cc61773496fc.png)

Server version: 10.2.44-MariaDB-10.2.44+maria~stretch mariadb.org binary distribution

thanks

**Comment by Jason-Morcos** [comment]
What is the exact error message Ace is giving when you try to connect?
Can you pose the full verbose change log for the failed connection?
Have any of these changes changed the error message or verbose log at all?
When you say "It used to work", when did it used to work? Has anything changed since then?

**Comment by ligne13** [comment]
Hi Jason,

I finally got it working. I had to generate a new key pair with the ED25519 algorithm, because the server was rejecting RSA keys.

Thank you for your support, both Jason and Samuel.
Sequel Ace is great!

**Comment by Jason-Morcos** [comment]
Glad you got it working! Cheers
