### ISSUE TITLE
Missing `Save Query As ...` menu item & shortcut since last update

### ISSUE THREAD

**Issue by Ornis007** [Sequel-Ace/Sequel-Ace#1682]
Please re-implement the previous way of handling opened query files and saving them.

Until last update, I often used the `Save Query As … ` menu item. Since last update (which?) I can't find this command and the shortcut ^[Alt][Command] does not work anymore. When modifying an opened query-file and saving it with `Save`-command, it overwrites the query file without warning.

Is this an intentional change? Would be a bad move. Or did I miss something here?

Sequel Ace version: 4.0.5
on MacOS 11.7.1

**Comment by Jason-Morcos** [comment]
Honestly not really sure what you're referring to here. Can you perhaps elaborate further? Can you try some older releases and try to determine when this changed? Can you provide a screenshot indicating what you're describing and what exactly you think the desired behavior should be?

We have a template for bug reports that includes a lot of these kinds of questions that we need answered to really debug things: https://github.com/Sequel-Ace/Sequel-Ace/issues/new?assignees=&labels=&template=bug_report.md

**Comment by Ornis007** [comment]
Thanks Jason

Before I post my bug report, I want to make sure it’s not an issue with my Mac OS

Here (see attachment) exact the same procedure in Version 3.5.3 vs. 4.0.5 when trying to save Query Window Content to SQL by pressing ^[alt][command].

Save Query As… with tooltip `Save Custom Query editor content as SQL file` in 3.5.3 is no longer an option in 4.0.5. That’s what I mean.

(the comparison was made on the same machine with same Mac OS Version and without any changes in preferences > keyboard > shortcuts)

**Comment by samuelbradshaw** [comment]
Your attachment didn't come through to the GitHub issue. However, I see a "Save Query" option in the "View" menu with the shortcut ⌃⌘S (Control-Command-S).

<img width="306" alt="Screenshot 2023-01-11 at 8 44 42 AM" src="https://user-images.githubusercontent.com/7323052/211850689-d259abf0-5a19-403e-886a-4a1841d56683.png">

**Comment by Ornis007** [comment]
Here the attachment file (first: menu in vs 3.5.3, second in vs 4.0.5)
![save_menu_in_3 5 3](https://user-images.githubusercontent.com/118893241/211859042-88fc75ba-9231-401b-b677-db0e1910215b.jpeg)
![save_menu_in_4 0 5](https://user-images.githubusercontent.com/118893241/211859091-fa143ee3-4ca1-4d6a-aeeb-57bfe77436de.jpeg)

**Comment by Ornis007** [comment]
No. What is my workflow:
(1) I open an existing SQL-Query File
(2) I modify the code and save it:
(3 a) Saving Query AS ... (version 3.5.3) pops up a save dialog, asks for the new filename and location of this new file. The existing/old SQL-Query file remains untouched.
(3b) Save Query (version 4.0.5) shows no save dialog and overwrites the existing SQL-Query file without warning.

**Comment by Jason-Morcos** [comment]
@Kaspik Was this change part of this past PR of yours https://github.com/Sequel-Ace/Sequel-Ace/pull/1527? Any thoughts on this?
