### ISSUE TITLE
Automation creation of Favorites with SSL

### ISSUE THREAD

**Issue by gnuWatchesU** [Sequel-Ace/Sequel-Ace#1683]
Hi!  I'm running Sequel Ace 4.0.5 Build 20046 on a M1 Mac OS 12.6.1.

I'm trying to automate addition of favorites.  My team uses a product called teleport which will generate a cert, key, and CA to connect to the DB with on a non-standard port.

I'm modifying the Favorites Plist (`~/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application Support/Sequel Ace/Data/Favorites.plist`) offline, and inserting values exported from the teleport tool.  The connection shows up in Sequel Ace without issue, but upon trying to connect I get `SSL_CTX_set_default_verify_paths`.  If I remove and re-add the files from the UI, it will work.  But what boggles my mind is the plist looks identical before and after I re-add the files.  Is there another piece besides the Favorites plist that I'm missing?

Thanks in advance!

**Comment by gnuWatchesU** [comment]
In case you're wondering how I'm generating the content, please excuse the hackiest hurried python you've ever seen: https://gist.github.com/gnuWatchesU/993999d7c9be84efb495847ed37c7f30

**Comment by Jason-Morcos** [comment]
That's the sandbox! Apple has some magic with actually granting apps access to files.

I would try as a workaround here to grant sequel Ace "full disk access" in system preferences and see if that works!

**Comment by Jason-Morcos** [comment]
Unfortunately I think that means this simply isn't allowed by the sandbox :/
You could try in the files tab in Sequel Ace's preferences giving access to a directory higher up that encapsulates all the keys you're trying to use, but I'm not very optimistic that will work

**Comment by gnuWatchesU** [comment]
Thank you, I appreciate your help!
