### ISSUE TITLE
Basic help to set up S.Ace to connect to remote servers (using MacBook Pro)

### ISSUE THREAD

**Issue by petednz** [Sequel-Ace/Sequel-Ace#1692]
What version of Sequel-Ace are you using? 4.0.5
What version of macOS are you running on? 10.5.17
What device(s) are you using Sequel-Ace on? MacBook Pro (late 2013)

I had  S. Ace working for a site or two (which were failing on S. Pro due to mysql8 issues.

But something has changed, and I have probably lost track of the many things i have tried, but the key error I am getting is that when connecting via SSH the error I get back says 

> Custom SSH binary enabled. Disable in Preferences to rule out incompatibilities!

When I work my way through the tabs in Preferences I don't spot anything that clearly relates to SSH binary.

I have now potentially changed other things just to try, but iirc the settings that used to work were

- SSH Client /Users/pd/.ssh/id_rsa 
- SSH Config /Users/pd/.ssh/config
- Known Hosts /Users/pd/.ssh/known_hosts
and under files I have the above (plus id_rsa.pub which is probably a result of my just trying some changes)

The full error is 

> Custom SSH binary enabled. Disable in Preferences to rule out incompatibilities!
> 
> Used command:  /Users/pd/.ssh/id_rsa -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/pd/.ssh/known_hosts" -F /Users/pd/.ssh/config -i /Users/pd/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 me@them -L 59279:127.0.0.1:3306
> 
> NSInvalidArgumentException: launch path not accessible
> 
> The SSH Tunnel has unexpectedly closed.

I have googled myself to a standstill. there one seem to be a couple of references to "Custom SSH binary" and nothing which sheds any further light (though i wonder if this is a red, or other, coloured herring). Any assistance would be much appreciated.

**Comment by Jason-Morcos** [comment]
> SSH Client /Users/pd/.ssh/id_rsa

This setting is selecting a custom SSH binary. Change this back to the default value. If you want to select a custom ssh key, do that in the connection settings (or use a custom ssh config).

**Comment by petednz** [comment]
ok. thank you. So in Preferences and removed the path set in Networks so it now reads (greyed out) System default.

and Bingo we are back in operation. So I guess that at some point when a connection was failing I must have (mis-)read or mis-remembered something and tried altering that value. Much appreciated
