### ISSUE TITLE
Add server colour on the window

### ISSUE THREAD

**Issue by 542alex** [Sequel-Ace/Sequel-Ace#1697]
<img width="1195" alt="Screenshot 2023-01-31 at 16 13 55" src="https://user-images.githubusercontent.com/62351439/215786739-24d51c47-e854-4f61-976f-7feed4dce32b.png">

Helpful visual indication when working on similar servers. As per the predecessor.

**Comment by Kaspik** [comment]
"Show tab bar".

Also, use search next time.

**Comment by 542alex** [comment]
Thanks!
Sorry for wasting you time, i m hyped today that i found that this project exists!

**Comment by Kaspik** [comment]
No problem, it's just it would save your time too! 🙊
