### ISSUE TITLE
notifications disable not fully working (banner on disconnect)

### ISSUE THREAD

**Issue by helptiger** [Sequel-Ace/Sequel-Ace#170]
- Sequel Ace Version: 2.1.1 rc 2
- macOS Version: 10.14.6

**Description**
I've disabled notifications but still get notifications (a banner on closing app)

![Screenshot-05-23-2020_04 23 37](https://user-images.githubusercontent.com/10258902/86534956-2241aa00-bedd-11ea-8095-c560339d2a1a.png)

![Screenshot-05-24-2020_04 24 29](https://user-images.githubusercontent.com/10258902/86534959-253c9a80-bedd-11ea-8e4c-e304e06ed7fc.png)

**Steps To Reproduce**
1. disable notifications on preferences 
2. close app, start again
3. connect to a db
4. close app

**Expected Behaviour**
Notifications should be completely deactivated

**Comment by Jason-Morcos** [comment]
This is quite likely a bug, but if I was going to fix it I would remove the notifications switch from Sequel Ace entirely and allow users to enable and disable notifications using the native macOS notifications system preferences.
As a workaround, does it work if you disable notifications for sequel Ace from system prefs?

**Comment by helptiger** [comment]
> As a workaround, does it work if you disable notifications for sequel Ace from system prefs?
work

Yes, that works for me. Thank you for all your work!
