### ISSUE TITLE
Under dark mode, Query tab textarea isn't dark background

### ISSUE THREAD

**Issue by hi-hai** [Sequel-Ace/Sequel-Ace#1705]
- Sequel Ace Version (including build number): v4.0.5 b20046
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.2
- Processor Type (Intel/Apple): Apple

**Description**
Under dark mode, the Query tab part is white background, which hurts eye a bit.

**Steps To Reproduce**
1. Switch to dark mode
2. Switch to Query tab

**Expected Behaviour**
Dark background is preferred.

**Additional Context**
Thanks for the great app.

**Comment by Jason-Morcos** [comment]
You can customize the entire theme of the query tab in Sequel Ace's preferences to look exactly how you'd like. Some folks like a light background in the query tab even with a dark mode version of the app and vice versa. There's a pre-existing theme in Sequel Ace's Preferences for a dark query editor.
