### ISSUE TITLE
save empty password

### ISSUE THREAD

**Issue by successgo** [Sequel-Ace/Sequel-Ace#1710]
Hello, as I have turned my localhost mysql password to empty, I could not save to sequel ace.

**Comment by jeduarz** [comment]
Same problem, more in this issue [#285](https://github.com/Sequel-Ace/Sequel-Ace/issues/285)
Is disturbing and more because I imported all my list of connections from Sequel PRO and now is not easy connect differents projects without fill BD & SSH passwords.

**Comment by Jason-Morcos** [comment]
As a workaround, you should be able to use Keychain Access (MacOS Built in app) to remove the password from the Keychain, thus letting you connect with no password
