### ISSUE TITLE
Error duplicating database on Aurora, no additional error info

### ISSUE THREAD

**Issue by ktwbc** [Sequel-Ace/Sequel-Ace#1712]
- Sequel Ace Version (including build number): 4.0.5 20046
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 12.6.3 (21G419)
- Processor Type (Intel/Apple): Intel
- MySQL Version: Aurora MySQL 3.02.1 (8.0.23 compat)
- macOS Localization: US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1. Create Amazon Aurora MySQL RDS instance Aurora MySQL 3.02.1 (8.0.23 compat) 
2. log in with your master credentials
3. Create test database, add at least one table (can just be id primary key)
4. Use Duplicate Database function
5. Enter new name, and check copy contents

**Expected Behaviour**
Should dupe existing database, has worked in the past, now generates Cannot Copy error with no further info. The SQL Console log shows the following output (I created "Test" and then attempted to make a copy "test33"

SHOW TABLES FROM `test`;
CREATE DATABASE `test33` DEFAULT CHARACTER SET = `utf8mb4` DEFAULT COLLATE = `utf8mb4_0900_ai_ci`;
/*!32352 SET foreign_key_checks=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!32352 SET foreign_key_checks=1 */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
SHOW DATABASES;
USE `test33`;
SHOW VARIABLES LIKE 'character_set_database';
SHOW FULL TABLES;
SELECT * FROM information_schema.routines WHERE routine_schema = 'test33' ORDER BY routine_name;
USE `test`;
SHOW VARIABLES LIKE 'character_set_database';
SHOW FULL TABLES;
SELECT * FROM information_schema.routines WHERE routine_schema = 'test' ORDER BY routine_name;

this all appears normal but the popup in Sequel Ace shows
Unable to Copy Database
An error occurred while trying to copy the database 'test' to 'test33'.

**Comment by Jason-Morcos** [comment]
I just tested locally and I can't reproduce this issue - the duplicate database function seems to work for me. 

Are you connected to AWS as root? This could be an issue with your current mysql user having insufficient issues to create a database

**Comment by paolomartini** [comment]
Hello Kris, were you able to solve this? I seem to have a similar problem on a mySQL 8 RDS DB.
