### ISSUE TITLE
Timezone setting error

### ISSUE THREAD

**Issue by mustangxu** [Sequel-Ace/Sequel-Ace#1713]
- Sequel Ace Version (including build number): 4.0.5 build 20046
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 13.2.1
- Processor Type (Intel/Apple): Intel
- MySQL Version:
- macOS Localization: En

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Got an error when connecting with a timezone specified

**Steps To Reproduce**
1. Create a new connection
2. Set any timezone other than 'Use Server Time Zone'
3. Click 'test connection'

**Expected Behaviour**

Test successful with the specified timezone

**Related Issues**

**Additional Context**

<img width="520" alt="截屏2023-02-23 下午6 21 59" src="https://user-images.githubusercontent.com/194269/220881041-6a083b85-2745-40c7-8742-7a44110fb7ae.png">

**Comment by Jason-Morcos** [comment]
This error means the timezones table in the server you're trying to connect to isn't populated. You'll need to populate the timezones table on your localhost instance in order for the timezone setting to work.

https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html
