### ISSUE TITLE
Passwords for saved connections are not saved

### ISSUE THREAD

**Issue by tkindy** [Sequel-Ace/Sequel-Ace#1720]
- Sequel Ace Version (including build number): 4.0.5, Build 20046
- Sequel Ace Source (App Store/GitHub/Homebrew): Tested with Homebrew and App Store
- macOS Version: Ventura 13.2.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: N/A
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

At time of writing, the current GitHub release is the current App Store version.

**Description**
Sequel Ace discards passwords for saved connections.

**Steps To Reproduce**
1. Create a new connection, including a password.
2. Save the connection. The password is cleared.
3. Fill out the password again and "Save Changes".
4. Go to another connection or Quick Connect, then back to the new connection. The password is cleared.

No errors are displayed during this process, about Keychain or otherwise.

**Expected Behaviour**
Sequel Ace saves the passwords for saved connections.

**Related Issues**

Sort of similar to https://github.com/Sequel-Ace/Sequel-Ace/issues/1253, but with brand new connections rather than imported ones.

**Additional Context**

https://user-images.githubusercontent.com/2991842/222236566-aeb13f39-75d5-4343-9063-7987c31e02a3.mp4

The fake password I'm trying to save in the above video is `bar`, in case it matters.

**Comment by tkindy** [comment]
I investigated deeper with some coworkers and found that the issue stems from our setting `LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN` since we use Vitess with LDAP which [requires the cleartext plugin](https://vitess.io/docs/archive/13.0/user-guides/configuration-advanced/ldap_auth/#requirements). (We also set "Require SSL" on our Sequel Ace connections, so we're not actually sending passwords clear over the wire.)

I found the relevant code:

https://github.com/Sequel-Ace/Sequel-Ace/blob/21a431fea443fdb60a79d86cb3bfb93972c087a8/Source/Other/Keychain/SPKeychain.m#L46-L49

I found [the Sequel Pro issue](https://github.com/sequelpro/sequelpro/issues/2437) it references where one of the authors [said](https://github.com/sequelpro/sequelpro/issues/2437#issuecomment-283866970) they intentionally disabled Keychain when the `LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN` environment variable is passed.

I don't really understand that decision. Is there some fundamental conflict between storing passwords in Keychain and sending them to the SQL server in cleartext?

Ideally, I could save passwords even when the cleartext plugin is enabled for the app. But if that's not possible for some reason, I feel this should pop up a warning. It seems like a bug otherwise.

Thank you!

**Comment by tkindy** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/issues/285 was asking for a similar warning but was closed without implementing it.

**Comment by tkindy** [comment]
I was a bit confused why enabling the cleartext plugin with the env var prevents Keychain use when there's an "Enable Cleartext plugin" box in the connection settings which still lets your password be saved in Keychain.

I dug into it and found that [the env var guard](https://github.com/sequelpro/sequelpro/pull/2714) was added back in the SequelPro days, way before [the per-connection setting](https://github.com/Sequel-Ace/Sequel-Ace/pull/484) was added to Sequel Ace.

In light of that, I'm wondering if it'd be reasonable to drop the env var check and leave Keychain enabled to match the experience with setting "Enable Cleartext pugin" on a connection. I'd be happy to open a PR for that if it would be appreciated. Thanks!

**Comment by Kaspik** [comment]
We will be more than happy to review the PR!
