### ISSUE TITLE
Column Types / App Crash / Undesired Filter Reset

### ISSUE THREAD

**Issue by rawkon** [Sequel-Ace/Sequel-Ace#1722]
After doing database export, the filters in the content tab reset.

---

The app crashed when I unchecked the "display column types on content view" option in preferences.

Also, column types still appear in the query view which is annoying.

**Comment by rawkon** [comment]
😐

**Comment by Jason-Morcos** [comment]
Some of these issues have been fixed.
If any persist, please check for existing issues or open new issues with one GitHub issue per problem so we can track them independently. Thank you!
