### ISSUE TITLE
Customize Keyboard Shortcuts

### ISSUE THREAD

**Issue by kolinkorr839** [Sequel-Ace/Sequel-Ace#1726]
I am using Mac. Is it possible to customize the keyboard shortcuts? For example, the "Format SQL" is like a 4-combination keys so I like to be able to change this to something else.

**Comment by Jason-Morcos** [comment]
I suggest using a tool like BetterTouchTool if you want customized keyboard shortcuts in macOS apps. I don't foresee this feature coming to Sequel Ace anytime soon/ever unless a member of the community makes a PR to add it.

**Comment by samuelbradshaw** [comment]
On a Mac, you can customize shortcuts in System Settings:
https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/mac
