### ISSUE TITLE
Unable to display multiple result sets in the same tab 

### ISSUE THREAD

**Issue by shcw** [Sequel-Ace/Sequel-Ace#1727]
Description:

I am using Sequel Ace version 4.0.5 on macOS 12.0.1. I have noticed that when I execute multiple queries in the same tab, only the result set of the last query is displayed. I have checked the "Allow multiple statements" option in the preferences, but it doesn't seem to solve the issue.

I have tried looking for the "Show query tab in window" option mentioned in the Sequel Ace documentation, but I cannot find it in my version. I have also tried clicking on the "Window" tab and selecting "Show all tabs", but it doesn't work either.

Is there a way to display multiple result sets in the same tab? If not, could this feature be added in a future version?

Thank you for your help.

**Comment by Jason-Morcos** [comment]
Duplicate: https://github.com/Sequel-Ace/Sequel-Ace/issues/1451

**Comment by shcw** [comment]
> 

Thank you very much for answering the question
