### ISSUE TITLE
Sequel Ace Windows Arrangement Issue On Mac OS (Ventura 13.2.1)

### ISSUE THREAD

**Issue by wlclhk** [Sequel-Ace/Sequel-Ace#1729]
- Sequel Ace Version (including build number): Version 4.0.5 Build 20046
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version: Ventura 13.2.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: AWS RDS 8.x
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

Sequel Ace Windows Arrangement Issue On Mac OS (Ventura 13.2.1).
Whenever refresh of the database, the current sequel ace windows wants backwards and other open windows like Safari will move forward blocking the sequel ace window. This happens to me since update the New Mac OS Ventura.
whatever you do; run a query, select a table, refresh a connection, whatever that it, after it runs or exe, the other opened application windows will be shown (brought forward). I notices the File menu is still Sequel Ace, but the current (top layered windows) is some other apps.

This is annoying.

**Steps To Reproduce**
1. whatever you do; run a query, select a table, refresh a connection, whatever that it, after it runs or exe, the other opened application windows will be shown (brought forward). I notices the File menu is still Sequel Ace, but the current (top layered windows) is some other apps.

**Expected Behaviour**

expect sequel ace to stay on top like any other Mac apps.

**Related Issues**

**Additional Context**

**Comment by Kaspik** [comment]
Duplicate https://github.com/Sequel-Ace/Sequel-Ace/issues/1618
