### ISSUE TITLE
Do not see the buttons for interpreting data

### ISSUE THREAD

**Issue by goodjack** [Sequel-Ace/Sequel-Ace#1733]
- Sequel Ace Version (including build number): 4.0.5 Build 20046
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 12.6.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: n/a
- macOS Localization: Taiwanese Mandarin

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
20046 is the latest release.

**Description**
Those buttons for interpreting data are gone.

**Steps To Reproduce**
1. Double-click a text field to open the pop-up sheet
2. Do not see the buttons for interpreting data

**Expected Behaviour**
It is expected that there should be a row of buttons below the popup to interpret the data

**Related Issues**
No related issues found

**Additional Context**
<img width="735" alt="image" src="https://user-images.githubusercontent.com/1116129/227422510-9074451f-1b64-4686-8e1c-481defdaee13.png">

**Comment by Jason-Morcos** [comment]
Can you explain more what you expect to see here? Are you referring to the options to view the data as a json?

If so, what is the format of the data itself? Is this text content json-compliant?

**Comment by goodjack** [comment]
Yes, I want to get the JSON in the TEXT field.

Especially if the JSON string contains unicode encoding, this previous function can also help me to decode it.

**Comment by goodjack** [comment]
Sorry, I found this may be two unrelated issues.

### 1. Buttons to interpret the data
First, in Sequel Pro, TEXT type fields have some buttons to interpret the data, while in Sequel Ace they do not.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1116129/230278431-64fe2ff2-a03a-4d52-966b-861b12c8df5e.png">

### 2. Decode Unicode coded text

Second, both in Sequel Pro and Sequel Ace, JSON type fields with *unicode coded text* are automatically decoded, but TEXT type fields are not.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/1116129/230277012-1cc1f970-31de-4813-81cc-2d9101abbeb4.png">

 I remember that early Sequel Ace had the option to decode *unicode encoded text* in the popup window, but maybe not the "interpret data buttons" I mentioned earlier.

**Comment by yanggs07** [comment]
+1 I want this feature!

**Comment by goodjack** [comment]
Hi @Jason-Morcos,
I found that this feature worked well before version **`4.0.1`**, but disappeared after **`4.0.2`**.

![version 4.0.1 worked well](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/79466765-d4a4-41a8-b0c4-9f7f4e3fba43)

![version 4.0.2 disappeared](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/c67bf58a-3e0e-4509-87d1-4739fc2ca98a)

**Comment by goodjack** [comment]
Hi @Jason-Morcos,

I found that this feature worked well before version **`4.0.1`**, but disappeared after **`4.0.2`**.

![version 4.0.1 worked well](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/2ab755a2-8e71-41a5-b0bc-8140bc7d82f1)

![version 4.0.2 disappeared](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/0857a9d4-6069-46a5-ac32-c42f16218538)

**Comment by goodjack** [comment]
And yes, it will decode _unicode encoded text_.

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/a7f4350a-3a96-428f-aee3-3f3b9f844726)
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/0ace5a33-2ce5-468e-9c60-95e752d75030)

**Comment by goodjack** [comment]
And yes, it will decode _unicode encoded text_.


![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/4d6b9bb2-96e2-4566-b34a-22a9000ac9ca)


![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/1116129/c1523577-8004-4094-8a0e-038c4de8de79)

**Comment by Jason-Morcos** [comment]
Hey there - you're welcome to submit a PR if you can figure out what changed that broke this! We're happy to review all community pull requests. Thanks!

**Comment by Jason-Morcos** [comment]
Should be fixed in 4.0.7! https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F4.0.7-20050

**Comment by goodjack** [comment]
I really appreciate it!
