### ISSUE TITLE
Always offer SQL as the default export format.

### ISSUE THREAD

**Issue by henrypenny** [Sequel-Ace/Sequel-Ace#1734]
When I use cmd-shift-e to export my database schemas it often defaults to CSV.
Is there a way to change this. As a developer a CSV export of an entire database is useless.

Please default to SQL every time OR remember my last selection (even after a restart) OR make this a preference.
Thanks.

**Comment by Jason-Morcos** [comment]
Closing in favor of https://github.com/Sequel-Ace/Sequel-Ace/issues/1306
