### ISSUE TITLE
Opened SPF File Doesn't Restore Query Editor Content

### ISSUE THREAD

**Issue by yg-dba** [Sequel-Ace/Sequel-Ace#174]
- Sequel Ace Version: 2.1.0
- macOS Version: 10.14.3
- MySQL Version: 5.7.12 (AWS RDS)

**Description**
When pressing Cmd-S to save the current connection, the file saves as you would expect.  However when opening the file, the query editor is empty :(.

**Steps To Reproduce**
1. Open SequelAce
2. Click on the query-editor tab
3. Type some text
4. Save the file
5. Open the file
6.  The text is not there

**Expected Behaviour**
Queries in the query editor tab should be saved in the .spf file.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Issue occurs in beta.

**Additional Context**
When trying to open the file, the file isn't listed in the Open Recent.  It's not a big deal, but just figured I would mention it in case it's related.

**Comment by Jason-Morcos** [comment]
Hmm. I believe that saving the connection should not include the query editor content. There's a separate save menu option to save current query(s), which would export the query editor content as a .sql file, right?
Is there a use case in which you'd need the connection save to include the current query editor content? I tend to think of the query editor as a (private) scratch pad.

**Comment by stychos** [comment]
Would be cool to have this scratchpad, or custom-made "snippets" or something like this in future!

**Comment by yg-dba** [comment]
Thanks for looking at this.  I’ve been using SequelPro for years, and this is how it always worked.  Saving a .spf in sequelPro did save the queries in the query editor. 

I’m attaching a screenshot where you can see the defaulted checked option to “Remember query editor content”.  

Thanks so much!

**Comment by Jason-Morcos** [comment]
@yg-dba I just tested myself and confirmed that checking the save query editor content switch does cause the content to be saved into the .spf. Can you verify the same? If so, does it not restore the content for you when loading the .spf file?

<img width="1069" alt="Screen Shot 2020-07-06 at 20 34 05" src="https://user-images.githubusercontent.com/10710367/86702829-2c8ca280-bfc8-11ea-95a5-82edb7da938f.png">

**Comment by yg-dba** [comment]
Thank you Jason for debugging this!

Yes I do see the queries in the text file.  But when I open the file, it does not restore the content in the query editor view.

**Comment by yg-dba** [comment]
Not sure if this provides a clue - when opening the file, it does not display the file name in the top nav.  In SequelPro, the filename displays there.

**Comment by yg-dba** [comment]
One more clue - when opening the file, it’s necessary to select the connection again since the password is not saved in the connection.  Maybe this is unsetting the file association and causing it to not restore.

**Comment by Jason-Morcos** [comment]
Thanks for the feedback, @yg-dba! I'm away from my main setup on a trip right now so I can't do much investigation in the short-term but perhaps someone else will be able to pop in and take a look! @Sequel-Ace/all

**Comment by yg-dba** [comment]
This bug is a blocker for me.  Not being able to save queries is almost as bad as SequelPro crashing when I close a tab.  I lose my unsaved work…. 

I would appreciate very much if this gets fixed.

**Comment by gboudreau** [comment]
I know where this comes from. I'll submit a PR soon.

**Comment by jamesstout** [comment]
Hold on
I've just submitting and PR

**Comment by gboudreau** [comment]
@yg-dba A workaround that might help, until the fix is available to you:
edit your .spf file in a text editor, and add this, before the last 2 lines:

```
	<key>queryHistory</key>
	<array/>
```

Result:

```
...
	<key>queryHistory</key>
	<array/>
</dict>
</plist>
```

Sadly, this will be removed each time you save again, but at least, you can open a few .spf file if you really need to.
Fix should be available soon, in beta form.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by yg-dba** [comment]
It works PERFECTLY!!  Thank you so much to all of you who are so devoted to the community!  It’s really special of you to take of your time to help others. 

I always loved SequelPro minus the bugs, and I’m so glad that you’ve created SequelAce to replace it!!

YG
