### ISSUE TITLE
Specified SSH Identity KeyFile is ignored and -i not used in the command at all

### ISSUE THREAD

**Issue by Anutrix** [Sequel-Ace/Sequel-Ace#1743]
- Sequel Ace Version (including build number): Version 4.0.5 Build 20046
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 13.3.1 Ventura
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.31
- macOS Localization: English?

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

No newer beta.

**Description**
SSH KeyFile is ignored when trying to connect to a SQL server via SSH.
The 'used command' in error popup is missing the KeyFile I specify in the UI.
I can't provide the full command but when I do 'used-command-by-sequel-ace -i <path-to-my-identity-file>' in a normal terminal it doesn't fail.

**Steps To Reproduce**
1. Open Sequel Ace.
2. Switch to SSH tab.
3. Fill details and enable SSL.
4. Select identity file in Key File section.
5. Click Test Connection.

**Expected Behaviour**

Sequel Ace should just ssh and connect to the remote mysql.

**Related Issues**

There are similar sounding issues but it all seems permission, macOS or config related. None seem to have -i missing.

**Additional Context**

Sequel Ace has Mac's Full Disk Access. Normal SSH is also working fine with same config and known host files(including sequel ace's default ones) in a terminal.

Since the SSL Key File field is not used in command it tries to use the following 
```
## Specify a dummy id_rsa file so we don't try everything in the .ssh dir. TODO: Actually generate an id_rsa for each user
    IdentityFile ~/.keys/id_rsa
```
and fails as expected.

It was previously working fine. Last I checked was few months ago though. Things that I upgraded to Ventura recently and upgraded Sequel Ace few times.

Last part of error:
```
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /Users/<username>/.keys/id_rsa
no such identity: /Users/<username>/.keys/id_rsa: No such file or directory
debug1: No more authentication methods to try.
<remote-user>@<remote-ip>: Permission denied (publickey).
The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.
```

First part of error:
```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/<username>/<some-path>/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict" -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 <remote-user>@<remote-ip> -L 55xxx:<sql-host>:<sql-port>
```

**Comment by Jason-Morcos** [comment]
Sounds like you have a custom ssh config
Did you select that in Sequel Ace's preferences so Ace can use your custom ssh config?

**Comment by Anutrix** [comment]
> Sounds like you have a custom ssh config Did you select that in Sequel Ace's preferences so Ace can use your custom ssh config?

I don't have a custom ssh config. As I specified before. I always used Sequel Ace's default config and known_hosts. Which first game me this issue.
Just for testing I changed Sequel Ace settings to use the default ssh config(`~/.ssh/config`).
**Both** had same issue.

**Comment by Jason-Morcos** [comment]
Very weird for sure

I know I'm connecting to an SSH server with a private key in the connection with no errors. 

Do you only use quick connect? Does this still happen if you save the connection?

**Comment by Anutrix** [comment]
Not sure what you mean by save connection.
After filling info in the SSH tab I tried Test Connection which gave error and Connect which also gave me the error.

Then I tried 'Add to Favourites'. And repeated Test Connection and Connect. Same errors.

I will try add 'used command' to first github comment of this ticket after removing any sensitive things.

**Comment by Anutrix** [comment]
I think I found the issue. It was kind of on my end.

<img width="399" alt="Screenshot 2023-04-25 at 12 46 45" src="https://user-images.githubusercontent.com/11459028/234202371-a270719c-00f6-445e-8f5e-83dc185af29a.png">
The button next to SSH password is where the SSH Key File needs to go. At my low brightness I didn't notice there was a button there. Maybe that key symbol should darker/black.

I was trying it under 'Key File' field that shows up for SSL. SSL Key File and SSH Key File causing confusion.

Sorry for the trouble.
