### ISSUE TITLE
Refresh table view

### ISSUE THREAD

**Issue by martin-braun** [Sequel-Ace/Sequel-Ace#1747]
On the left side, the table view currently can't be refreshed. This means, when a table is added or removed, you cannot update, you have to reconnect or restart to refresh the left side panel table list.

It would be nice if cmd+R refreshes the table view as well.

**Comment by Jason-Morcos** [comment]
It can be refreshed
There's a refresh button near the bottom of the view

**Comment by martin-braun** [comment]
@Jason-Morcos Thank you, missed this one. I think it would be still intuitive to react to cmd+r when the focus is on the table view.

**Comment by Behinder** [comment]
However table content is still not autorefreshed live if the query is run
