### ISSUE TITLE
Add way to see column names while writing query

### ISSUE THREAD

**Issue by pstevemichel** [Sequel-Ace/Sequel-Ace#175]
I've long wished for this in Sequel Pro. When writing a query, to see the names of columns in tables, you have to switch away from the query to Structure or Content or Table Info, thus losing your place in the query. In other editors there's often a reveal arrow in the name of the table in the left column that will show you the names of columns. This would be really handy, especially when writing complex queries that refer to a number of columns and tables.

**Comment by Briones** [comment]
For what I know that already exists even in Sequel Pro the only thing that you need to do is write the table name a dot (.) and wait a few seconds to see the list of columns that your table have:

![imagen](https://user-images.githubusercontent.com/1811438/86686079-a6715b80-bfc9-11ea-9b40-f84905f80394.png)

Or maybe I misunderstood what you want?

**Comment by Jason-Morcos** [comment]
@pstevemichel Does the solution provided by @Briones fit what you're looking for?

**Comment by pstevemichel** [comment]
Thanks. It's a good workaround, and I use it, but it's not very browsable. I was thinking of something like what is in MySQL Workbench: 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/13258315/86807556-d3a42500-c02e-11ea-8878-f4a78d9beb57.png">

I can look at several tables at a time, and browse columns without having to interrupt my work in the query editor. I believe other SQL Editors have this as well.

Thanks for the consideration; I've been using Sequel Pro for years and years, and am glad it's being worked on again.
