### ISSUE TITLE
Enormous (SSH error) alert size exceeding available vertical screen size

### ISSUE THREAD

**Issue by pedzed** [Sequel-Ace/Sequel-Ace#1759]
I got this enormous alert with some SSH issue, not allowing me to see the OK button. (I managed to take a screenshot using macOS' screenshot tool, though.)

Could it be possible to include a scroll bar inside such an alert? Or even better, output a user friendly error.

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/8146593/2ac4ac3d-dec8-4d64-a826-329a889f2fdd)

**Comment by lostminds** [comment]
Got this as well. Not only could I not figure out what was going wrong despite the very long error message (that I could not read all of it). The fact that the close button is off screen meant I needed for force-quit Sequel Ace since the error message is modal and will block any user interaction.

**Comment by ArneAmeye** [comment]
I'm experiencing this too when trying to connect over SSH to a MySQL 8 database. Found it if you hit the return key it accepts the action of pressing the "ok" button that is out of view. This way you won't have to force close the whole application. However would still like to see a modal that is scrollable or can be resized.

**Comment by yugaego** [comment]
+1

> hit the return key it accepts the action of pressing the "ok" button that is out of view.

Thanks! I couldn't see there's button below the alert text, so <kbd>TAB</kbd> and then <kbd>SPACE</kbd> was my way out. Had to kill *Sequel Ace* process otherwise 😖 

I'm on

```
Version 4.0.5
Build 20046
```

**Comment by simesy** [comment]
> hit the return key it accepts the action of pressing the "ok" button that is out of view.

Oh thanks i was hitting ESC thinking it should do it :D

**Comment by Jason-Morcos** [comment]
Fixed in 4.0.9
