### ISSUE TITLE
Tool to convert encoding

### ISSUE THREAD

**Issue by MacGritsch** [Sequel-Ace/Sequel-Ace#1763]
Would it make sense to implement a tool to convert from an encoding to another encoding and character sets of all tables and columns (keeping default values, nullability and so on).
That would ease the transition from utf8mb3 to utf8mb4.

**Comment by Jason-Morcos** [comment]
I think I'd just go table-by-table changing the encoding by hand - or if you have so many tables that's tough, perhaps it would be worth writing some code somewhere to convert all of yours - this seems fairly niche _and_ a pretty high-risk way of approaching a conversion like this one :)
