### ISSUE TITLE
How do I remove the 'field type' in Query results header??

### ISSUE THREAD

**Issue by kf6spf** [Sequel-Ace/Sequel-Ace#1767]
### Discussed in https://github.com/Sequel-Ace/Sequel-Ace/discussions/1766

<div type='discussions-op-text'>

<sup>Originally posted by **kf6spf** June 13, 2023</sup>
So I used to use Sequel Pro and recently discovered that it was "gone" and came across this program.

Very nice!!

Only question is how do I remove the column type listings in the header of Query Results??

![SequelAceQueryColumnType](https://github.com/Sequel-Ace/Sequel-Ace/assets/18036760/29bfbace-eb2b-4917-a75d-f80eabf3238e)
</div>

<b>Enhancement Request</b>
PLEASE - make a setting in the View Menu to disable the column type in the Query Results table. It's not a "needed" feature and makes the display overly long for small fields.

**Comment by Jason-Morcos** [comment]
PR addressing this is welcome!
