### ISSUE TITLE
Save Connection is saving an .spfs file instead of .spf

### ISSUE THREAD

**Issue by jonajonlee** [Sequel-Ace/Sequel-Ace#1769]
- Sequel Ace Version (including build number): 4.0.5 (20046)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.4 (22F66)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7.12
- macOS Localization: USA?

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes

**Description**
When saving a connection, the subsequent file is saved with an `.spfs` extension. When opening the same file in Sequel Ace, an error "Error while reading connection data file" pops up and the connection is not able to be opened.

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/6760959/e845e86c-0acc-4edf-a947-ff54b28f24e2)

**Steps To Reproduce**
1. Open a connection
2. Add anything to the Query Editor
3. Save Connection (CMD + S)
4. Enter a name `myconnection`
5. Save
6. Note that a file `myconnection.spfs` is created instead of `myconnection.spf`
7. On Sequel Ace, click File -> Open Recent -> `mytest.spfs`
8. Note that an error will pop up
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/6760959/26c2cc0d-e51f-4777-84cd-f3b8bfb549be)

Note: Presumably, Sequel Ace is looking for a `info.plist` which is available in `.spfs` but not `.spf`.

**Expected Behaviour**
The saved file would have `.spf` extension

**Related Issues**
None

**Additional Context**
- If you manually change the extension to `.spf` after the file is created then Sequel Ace successfully opens the file.

**Comment by Jason-Morcos** [comment]
Should be fixed in the latest releases
