### ISSUE TITLE
Can't select off Query tab

### ISSUE THREAD

**Issue by splybon** [Sequel-Ace/Sequel-Ace#1772]
- Sequel Ace Version (including build number): 4.0.4
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Ventura 13.4
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.33-25
- macOS Localization: en

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
Can't select off of query tab.  For the tabs at the top, "Structure" - "Table Info" are greyed out and I can't select them.

**Steps To Reproduce**
1. Click the "Query" tab
2. Attempt to select a different tab

**Expected Behaviour**
I would expect to be able to still select between tabs

**Additional Context**
<img width="1337" alt="Screenshot 2023-06-21 at 10 21 51 AM" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/6655513/7f40f5fa-cba8-47d6-85e1-248a59e7bd13">

**Comment by samuelbradshaw** [comment]
The interaction is a little confusing, but you should be able to switch to the other tabs after you choose a table in the sidebar on the left.

**Comment by Jason-Morcos** [comment]
I think you just need to expand the sidebar from the side! Like drag it back out from the left
https://github.com/Sequel-Ace/Sequel-Ace/issues/1097

**Comment by splybon** [comment]
@Jason-Morcos that's exactly it thank you so much!
