### ISSUE TITLE
'IN' filter on a column name that is a reserved keyword (e.g. 'key.') doesn't work

### ISSUE THREAD

**Issue by maxime-dupuis** [Sequel-Ace/Sequel-Ace#1773]
- Sequel Ace Version (including build number): Version 4.0.5, Build 20046

- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 13.4
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7.12
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Can't use the 'IN' filter on a column name that is a reserved keyword (e.g. key)

**Steps To Reproduce**
1. Open a table
2. Content tab
3. Menu > Table > Filter content
4. Create a filter on a column named 'key' (or other reserved keywords) with the operation 'IN'

**Expected Behaviour**

Filtering works

**Related Issues**

**Additional Context**

This query also fails (this is a MySQL thing, not Sequel Ace)

```
SELECT *
FROM my_table
WHERE key IN ('my_key')
LIMIT 1;
```

Output:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key IN ('my_key')
LIMIT 1' at line 3
```

A fix is adding the column in the query. Maybe you could try that in SequelAce.
```
SELECT *
FROM my_table
WHERE my_column.key IN ('my_key')
LIMIT 1;
```

Or backticks:
```
WHERE `key` IN ('my_key)
```

**Comment by Jason-Morcos** [comment]
Definitely looks like a spot the column name needs to be wrapped in backticks!

**Comment by Jason-Morcos** [comment]
I can't reproduce this locally. Went to try to fix it and I can clearly see the backticks being added around the column, even in an in. If you're still having this issue, please post a screenshot here of what your filters look like specifically, and a create table statement.
<img width="828" alt="Screenshot 2023-07-27 at 11 19 44" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/2bd693d3-eb83-4210-a927-4f5c27f70190">

**Comment by maxime-dupuis** [comment]
Oh sorry, you're right it works
I must have forgotten the quotes when I changed it from a = to IN filter

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/118775839/8dea9bcb-330d-45b1-883f-c47070e676a6)

Quotes not needed for =
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/118775839/583ef676-94d4-43d7-8d4d-3cd8a9f82097)

Quotes needed for IN
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/118775839/70ae119b-8d9f-47cc-a663-8701d44fc232)
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/118775839/a475d4bd-a495-4af4-81e0-f39d8818dedf)
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/118775839/c4eef583-d6da-41e0-b58c-d543c39a8145)
