### ISSUE TITLE
Application keeps hiding itself

### ISSUE THREAD

**Issue by JonLaliberte** [Sequel-Ace/Sequel-Ace#1778]
- Sequel Ace Version (including build number): Version 4.0.5, Build 20046
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 13.3.1 (a) (22E772610a)
- Processor Type (Intel/Apple): Intel
- MySQL Version: NA
- macOS Localization: English/ US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
The application keeps hiding itself. So I'm doing something in the app, then it looks like the app crashed (the window disappears). But, it hasn't crashed, it's just not at the front anymore.
I did not notice this prior to 4.0.5.

**Steps To Reproduce**
1. It's not obvious when it happens. It seems to happen mostly when loading a new (large) table. I have my settings set to limit to 500 rows to load. I keep thinking the app crashed, but it is just that is no longer at the front.
2. I was unable to reproduce the issue just now when trying to. 

**Expected Behaviour**
The window remains at the front.

**Related Issues**
NA

**Additional Context**
NA - Opening in case others have the problem. I'll add logs/screen recordings if I'm able to catch it in action.

**Comment by Jason-Morcos** [comment]
Duplicate
https://github.com/Sequel-Ace/Sequel-Ace/issues/1618

**Comment by JonLaliberte** [comment]
Whoops, sorry for the duplicate. I searched, but didn’t use “focus” as a keyword.
