### ISSUE TITLE
Import SequelPro Preferences and Application Support

### ISSUE THREAD

**Issue by inoas** [Sequel-Ace/Sequel-Ace#178]
Should ask for import if connections ist is empty and sequelpro connections are detected.

~Hello,~

~there should be an easy way to import SequelPro configuration. It'd be okay if passwords were not carried over but the rest should.~

~It should ask on startup if it finds sequel pro configuration and the startup question should have checkbox "don't ask anymore" and there should be a menu item somewhere to do it manually afterwards.~

~Syncing/Overwriting may be an issue then.~

**Comment by inoas** [comment]
Was a dupe of https://github.com/Sequel-Ace/Sequel-Ace/issues/155
Exporting and Importing actually works.
New request: Should ask for import if empty and sequelpro detected

**Comment by Jason-Morcos** [comment]
> Was a dupe of https://github.com/Sequel-Ace/Sequel-Ace/issues/155
> 
> Exporting and Importing actually works.
> 
> New request: Should ask for import if empty and sequelpro detected

Unfortunately, Sequel Ace is sandboxed. We can't crawl the file system to find out if Sequel Pro configs are present.
