### ISSUE TITLE
Imported SequelPro connections with ssh config hosts don't work

### ISSUE THREAD

**Issue by inoas** [Sequel-Ace/Sequel-Ace#179]
I am using `.ssh/config` entries and SequelPro.app worked flawlessly with those. 

It seems SequelAce does not find the ssh hosts:

`ssh: Could not resolve hostname FOOBAR: nodename nor servname provided, or not known`

Versions: 2.1.2 Beta 1 and current App Store release

**Comment by Jason-Morcos** [comment]
Hi, Sequel Ace can't magically access your .ssh configs due to sandboxing. Did you select your ssh config file manually in the app's preferences (network tab) and any support files in the "files" tab?


https://sequel-ace.com/get-started/
See "Sequel Ace doesn’t read my ~/.ssh/config parameters."

**Comment by Jason-Morcos** [comment]
Closed due to inactivity
