### ISSUE TITLE
faulty German translation

### ISSUE THREAD

**Issue by helptiger** [Sequel-Ace/Sequel-Ace#1790]
- Sequel Ace Version: Version 4.0.6, Build 20048

see Comparison

![Bildschirmfoto 2023-07-15 um 15 10](https://github.com/Sequel-Ace/Sequel-Ace/assets/10258902/a31610da-aab1-4521-b566-84bcb811c44e)

**Comment by Jason-Morcos** [comment]
Please join our Crowdin to contribute fixes to localizations. See the readme for more info. Thanks!
