### ISSUE TITLE
Switches app when I use the reload button

### ISSUE THREAD

**Issue by timgurske** [Sequel-Ace/Sequel-Ace#1792]
Version 4.0.5
Build 20046
MacOS 13.3.1 (a) (22E772610a)

When I click the reload button on the bottom of the screen the data reloads and then the mac finder switches to a different app. Or, more correctly, it moves SequelAce to the back of the stack and hides it behind all other apps on my mac. It does it on both my iMac and my Macbook Pro.

**Comment by codivist** [comment]
It also does this for me when selecting a different table

**Comment by Jason-Morcos** [comment]
Duplicate https://github.com/Sequel-Ace/Sequel-Ace/issues/1618
