### ISSUE TITLE
Sudden crash in V4.0.6 after selecting database and table on M1

### ISSUE THREAD

**Issue by juhasev** [Sequel-Ace/Sequel-Ace#1793]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Sequel Ace [35049]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
Identifier:            com.sequel-ace.sequel-ace
Version:               4.0.6 (20048)
App Item ID:           1518036000
App External ID:       858454840
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-20 08:09:00.1384 -0500
OS Version:            macOS 14.0 (23A5276g)
Report Version:        12
Anonymous UUID:        41F5D117-2ACB-F97F-ECCF-D2558A2FB6BB

Sleep/Wake UUID:       0E4D8132-0EC2-4D0A-BEC0-EFDBB447693F

Time Awake Since Boot: 810000 seconds
Time Since Wake:       1095 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001876adf28

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [35049]

Application Specific Backtrace 0:
0   CoreFoundation                      0x0000000183d30a80 __exceptionPreprocess + 176
1   libobjc.A.dylib                     0x0000000183829fa4 objc_exception_throw + 60
2   CoreFoundation                      0x0000000183d30970 +[NSException exceptionWithName:reason:userInfo:] + 0
3   AppKit                              0x000000018740210c -[NSWindow(NSDisplayCycle) _postWindowNeedsUpdateConstraintsUnlessPostingDisabled] + 1844
4   AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
5   AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
6   AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
7   AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
8   AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
9   AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
10  AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
11  AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
12  AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
13  AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
14  AppKit                              0x00000001873ecae4 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 64
15  AppKit                              0x00000001873eca68 -[NSView setNeedsUpdateConstraints:] + 460
16  AppKit                              0x0000000187458c00 NSViewActuallyUpdateFrameFromLayoutEngine + 548
17  AppKit                              0x0000000187418834 -[NSView layout] + 636
18  AppKit                              0x0000000187e1febc ___NSViewLayout_block_invoke + 592
19  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
20  AppKit                              0x00000001874183b4 _NSViewLayout + 96
21  AppKit                              0x0000000187e165d0 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 364
22  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
23  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
24  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
25  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
26  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
27  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
28  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
29  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
30  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
31  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
32  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
33  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
34  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
35  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
36  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
37  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
38  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
39  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
40  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
41  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
42  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
43  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
44  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
45  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
46  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
47  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
48  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
49  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
50  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
51  AppKit                              0x0000000187e16714 __36-[NSView _layoutSubtreeWithOldSize:]_block_invoke + 688
52  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
53  AppKit                              0x0000000187418348 -[NSView _layoutSubtreeWithOldSize:] + 100
54  AppKit                              0x0000000187e170b8 __56-[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:]_block_invoke + 796
55  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
56  AppKit                              0x0000000187417f08 -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 100
57  AppKit                              0x0000000187413890 NSPerformVisuallyAtomicChange + 108
58  AppKit                              0x0000000187417e98 -[NSView layoutSubtreeIfNeeded] + 96
59  AppKit                              0x00000001880be0f4 -[NSWindow(NSConstraintBasedLayoutInternal) _layoutViewTree] + 104
60  AppKit                              0x00000001880be27c -[NSWindow(NSConstraintBasedLayoutInternal) layoutIfNeeded] + 240
61  AppKit                              0x0000000187476bc4 __NSWindowGetDisplayCycleObserverForLayout_block_invoke + 364
62  AppKit                              0x0000000187476160 NSDisplayCycleObserverInvoke + 168
63  AppKit                              0x0000000187475dbc NSDisplayCycleFlush + 644
64  QuartzCore                          0x000000018bc9faf8 _ZN2CA11Transaction19run_commit_handlersE18CATransactionPhase + 120
65  QuartzCore                          0x000000018bc9e8b8 _ZN2CA11Transaction6commitEv + 320
66  AppKit                              0x00000001874f94a0 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 272
67  AppKit                              0x0000000187e5a234 ___NSRunLoopObserverCreateWithHandler_block_invoke + 64
68  CoreFoundation                      0x0000000183cbb5a4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
69  CoreFoundation                      0x0000000183cbb490 __CFRunLoopDoObservers + 532
70  CoreFoundation                      0x0000000183cbaac0 __CFRunLoopRun + 776
71  CoreFoundation                      0x0000000183cba104 CFRunLoopRunSpecific + 600
72  HIToolbox                           0x000000018e257534 RunCurrentEventLoopInMode + 292
73  HIToolbox                           0x000000018e257370 ReceiveNextEventCommon + 648
74  HIToolbox                           0x000000018e2570c8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
75  AppKit                              0x00000001873d0f84 _DPSNextEvent + 660
76  AppKit                              0x0000000187b6d098 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
77  AppKit                              0x00000001873c479c -[NSApplication run] + 476
78  AppKit                              0x000000018739bc44 NSApplicationMain + 880
79  dyld                                0x0000000183865058 start + 2224

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   AppKit                        	       0x1876adf28 -[NSApplication _crashOnException:] + 240
1   AppKit                        	       0x1874f9614 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 644
2   AppKit                        	       0x187e5a234 ___NSRunLoopObserverCreateWithHandler_block_invoke + 64
3   CoreFoundation                	       0x183cbb5a4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
4   CoreFoundation                	       0x183cbb490 __CFRunLoopDoObservers + 532
5   CoreFoundation                	       0x183cbaac0 __CFRunLoopRun + 776
6   CoreFoundation                	       0x183cba104 CFRunLoopRunSpecific + 600
7   HIToolbox                     	       0x18e257534 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x18e257370 ReceiveNextEventCommon + 648
9   HIToolbox                     	       0x18e2570c8 _BlockUntilNextEventMatchingListInModeWithFilter + 76
10  AppKit                        	       0x1873d0f84 _DPSNextEvent + 660
11  AppKit                        	       0x187b6d098 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
12  AppKit                        	       0x1873c479c -[NSApplication run] + 476
13  AppKit                        	       0x18739bc44 NSApplicationMain + 880
14  dyld                          	       0x183865058 start + 2224

**Comment by Jason-Morcos** [comment]
We don't generally investigate random one-off crashes, however if you're seeing this as a repeated issue I encourage you to debug locally and try to isolate the issue. Thanks! :)
