### ISSUE TITLE
Another application icon proposal

### ISSUE THREAD

**Issue by iainhenderson** [Sequel-Ace/Sequel-Ace#1794]
It seems like a number of people have submitted their takes on potential new application icon: https://github.com/Sequel-Ace/Sequel-Ace/pull/411, https://github.com/Sequel-Ace/Sequel-Ace/issues/311, https://github.com/Sequel-Ace/Sequel-Ace/issues/31

My version attempts to:

- Make the spade symbol more recognisable.
- Use a visual metaphor like the old Sequel Pro pancake stack. Now the database platters become poker chips to feel connected to the "Ace" naming, the background is green gaming table felt.
- Use Mac OS icon colouring and materials. Many Mac OS icons have elements which look like shiny white plastic which has highlights and reflects the icon background color (See Facetime, Messages, Pages)

![Sequel Ace 1-8](https://github.com/Sequel-Ace/Sequel-Ace/assets/775758/f919ec3a-cf6f-41a3-bb94-430dfde5ddb6)

**Comment by Jason-Morcos** [comment]
Thank you for the suggestion! I think we're not planning on changing the icon at this time, but I do have to admit this looks pretty darn cool. Excellent work!
