### ISSUE TITLE
Error retrieving Keychain item to edit (code -25300) for SSH items

### ISSUE THREAD

**Issue by j-jalving** [Sequel-Ace/Sequel-Ace#1795]
- Sequel Ace Version  Version 4.0.6 Build 20048:
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 13.4.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 
- macOS Localization: en

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
When editing a favorite entry with an SSH User set, an error is thrown (Error retrieving Keychain item to edit (code -25300)).

**Steps To Reproduce**
1. Create a new SSH connection. 
2. Fill out the required fields and make sure the SSH User field is filled (Otherwise the error won't occur).
3. Add it to favorites
4. Change any field, delete the entry or duplicatie it.

**Expected Behaviour**
I expect the changes to be saved without any error.

**Related Issues**
#600 

**Additional Context**
I've tried uninstalling the app using AppCleaner and wiping all keychain entries for Sequal Ace. But even with a fresh install the problem occurs.

**Comment by Jason-Morcos** [comment]
Does this still occur with version 4.0.5 of Sequel Ace? You can download that version from the GitHub releases. I'm curious if this is a new issue related to our attempts to fix some keychain issues.

**Comment by j-jalving** [comment]
No, I actually installed the previous release so I could still acces my database. No issues with that version.

**Comment by waynedixon** [comment]
I can corroborate that 4.0.6 has this issue but 4.0.5 does not. I setup 4.0.6 on a brand new machine and it gave me the indicated issues. Downgrading to 4.0.5 works without any of the errors.

**Comment by Jason-Morcos** [comment]
Can folks try this latest beta and confirm if it fixes the issue? https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F4.0.7-20049

**Comment by generator85** [comment]
At first I thought it did, I followed the steps in my first post and saving seemed to work fine. But then I duplicated the favorite entry, then tried to delete that duplicate and the error popped up again. After that changing any field and then saving caused the error the pop up every time.

**Comment by j-jalving** [comment]
At first I thought it did, I followed the steps in my first post and saving seemed to work fine. But then I duplicated the favorite entry, then tried to delete that duplicate and the error popped up again. After that changing any field and then saving caused the error the pop up every time.

**Comment by Jason-Morcos** [comment]
> At first I thought it did, I followed the steps in my first post and saving seemed to work fine. But then I duplicated the favorite entry, then tried to delete that duplicate and the error popped up again. After that changing any field and then saving caused the error the pop up every time.

Is it possible that's a different error than this one introduced in 4.0.5 and that one existed before?

**Comment by j-jalving** [comment]
It's the same. I've attached screenshot.
<img width="372" alt="Screenshot 2023-07-27 at 11 01 35" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/60800079/7a903ccb-90a3-4ee4-8071-25b81b2335db">

**Comment by Jason-Morcos** [comment]
I think I might have another fix - will have a new release candidate on GitHub soon to test with. Thanks!

**Comment by Jason-Morcos** [comment]
4.0.7 release candidate out now! Please let me know if this fixes it.
https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F4.0.7-20050

**Comment by j-jalving** [comment]
Seems to work great!
