### ISSUE TITLE
why  pro is ok,ace is bad ? 

### ISSUE THREAD

**Issue by duzhenxun** [Sequel-Ace/Sequel-Ace#1804]
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/4089622/4509d228-0c19-470d-9413-d9f862cca584)

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/4089622/169fec2e-7b27-4048-8055-34fb49978fce)

Version 4.0.7
Build 20050
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/4089622/e96e8361-4755-4348-9e02-7ddc4e465ed2)

**Comment by Jason-Morcos** [comment]
Please follow the standard issue template when submitting an issue. 

I'd search through existing issues for topics like "unable to connect but sequel pro is fine". Generally, you need to select your custom ssh config file in Sequel Ace's preferences under the network tab. We also have lots of documentation on our website https://sequel-Ace.com
