### ISSUE TITLE
can´t connect if proxyCommand is used on ssh/config

### ISSUE THREAD

**Issue by sauriio** [Sequel-Ace/Sequel-Ace#1807]
- Sequel Ace Version (including build number):Version 4.0.7 - Comp 20050
- Sequel Ace Source (App Store/GitHub/Homebrew): tested on App Store and Homebrew
- macOS Version:  13.4.1 (c) (22F770820d)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0
- macOS Localization: ES

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes.

**Description**
When I try to connect with https://github.com/bryanpkc/corkscrew enabled as the proxyCommand in the ssh-config file 
`
ProxyCommand /opt/homebrew/Cellar/corkscrew/2.0/bin/corkscrew 127.0.0.1 1087 %h %p
`
installed through homebrew I get a connection error, this is the log information dumped by Sequel-Ace
`
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile="/Users/marioraymundo/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict" -F /Users/marioraymundo/.ssh/config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 macosta@sandbox.kvcore.io -L 53743:sqldev.kvcore.io:3306

OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/marioraymundo/.ssh/config
debug1: /Users/marioraymundo/.ssh/config line 1: Applying options for sandbox.kvcore.io
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Executing proxy command: exec /opt/homebrew/Cellar/corkscrew/2.0/bin/corkscrew 127.0.0.1 1087 sandbox.kvcore.io 22
debug1: identity file /Users/marioraymundo/.ssh/id_ed25519 type 3
debug1: identity file /Users/marioraymundo/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
zsh:1: operation not permitted: /opt/homebrew/Cellar/corkscrew/2.0/bin/corkscrew
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
El túnel SSH se ha cerrado inesperadamente.
`
from the information, I can only assume that this is a sandboxing issue, I tried to give some permissions on the Accessible Files tab of the preferences menu, but I can only give it to the folder and that didn't help 
**Steps To Reproduce**
1.install corkscrew and set an HTTP proxy, then configure the ssh config file to use this proxy with the ProxyCommand instruction
2.try to connect

**Expected Behaviour**
connection successfully created.

**Related Issues**
NO ISSUES AFAIK.

**Comment by Jason-Morcos** [comment]
Proxy commands won't work as they're not supported in Sandboxed macOS apps. Sequel Ace is sandboxes for your security.
