### ISSUE TITLE
Lost focus when open and close popup window

### ISSUE THREAD

**Issue by jheroy** [Sequel-Ace/Sequel-Ace#1809]
- Sequel Ace Version (including build number): 4.0.7
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 13.3.1(a)
- Processor Type (Intel/Apple):apple 
- MySQL Version: 5.6
- macOS Localization:

**Steps To Reproduce**
1. Open popup window, `Database -> Go to Database` or use `Shift+Cmd+D`
2. Press Ok or Cancel

Focus lost.

**Comment by rloechner** [comment]
I have a similar error when I run queries or apply filters. I will lose focus and Sequel Ace will jump to the back of whatever windows are open. I have a video I can share for anyone interested in seeing the behavior.
