### ISSUE TITLE
Running Database Report Bundle opens Sequel Pro

### ISSUE THREAD

**Issue by gms8994** [Sequel-Ace/Sequel-Ace#181]
- Sequel Ace Version: 2.1.1 and 2.1.2 beta1
- macOS Version: Catalina
- MySQL Version: N/A

**Description**
Looks like when #120 was brought over, the Database Report bundle must specifically mention Sequel Pro somehow - clicking that option opens Sequel Pro which then errors out (assuming that Sequel Pro is installed, I assume).

**Steps To Reproduce**
1. Install 2.1.1
2. Select a database
3. Choose Report -> Database Report from the Bundles menu

**Expected Behaviour**
No error occurs

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Verified in both 2.1.1 and 2.1.2 beta 1

**Comment by Jason-Morcos** [comment]
Good catch! Please try this latest beta and let me know if it works now. 

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.2-beta2

**Comment by gms8994** [comment]
@Jason-Morcos Thank you for such a quick turnaround! That "works" within Sequel Ace now, but also now throws the following error:

```
Error for “Database Report”:
line 54: /usr/local/bin/perl: Operation not permitted
line 57: /usr/local/bin/perl: Operation not permitted
line 118: /usr/local/bin/perl: Operation not permitted
line 118: /usr/local/bin/perl: Operation not permitted
line 118: /usr/local/bin/perl: Operation not permitted
```

I'm not sure, but I think perhaps the files that should be written aren't being written? Those lines match up with mentions of `$SP_QUERY_RESULT_FILE`.

**Comment by Jason-Morcos** [comment]
Hmmm now that sounds like a sandboxing issue (the app is sandboxed for App Store release), we may in fact have to remove the database report capability.

**Comment by gms8994** [comment]
Even though I downloaded and used the Beta app? I wouldn't be surprised, but wanted to confirm.

**Comment by Jason-Morcos** [comment]
Yup, Sequel Ace in all forms is sandboxed. We submit the same binary to the App Store that we upload to GitHub
