### ISSUE TITLE
The varchar length displayed on the Pop-up Sheet title is inconsistent with the field length defined in the table

### ISSUE THREAD

**Issue by binmao2023** [Sequel-Ace/Sequel-Ace#1812]
- Sequel Ace Version (including build number): Version 4.0.6 Build 20048
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 13.4.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.31
- macOS Localization: Chinese

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
My table defines a varchar field with 255 length, named label.
```
# show create table admin_lib__menu;

CREATE TABLE `admin_lib__menu` (
  `id` int NOT NULL,
  `desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `label` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `path` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `resourceId` json DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `createdAt` timestamp NULL DEFAULT NULL,
  `updatedAt` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC
```
When I edit the field in Pop-up Sheet, the sheet title shows the field length is 1020. Even the maximum length of I can edit is still 255.
Like below:
![企业微信截图_84e9a776-c006-4c2b-84ee-1b80c2492554](https://github.com/Sequel-Ace/Sequel-Ace/assets/139862486/660511c7-bb0d-4aa0-94f6-3fa4fd1a0be3)

**Expected Behaviour**

The field length displayed on the Pop-up Sheet is consistent with the table's field length.

**Related Issues**

**Additional Context**

**Comment by luis-** [comment]
This is due to `utf8mb4_0900_ai_ci` (and many others) not being in the list of know charsets: https://github.com/Sequel-Ace/Sequel-Ace/blob/33e9cb8ce88fc23e02faa45cbd8480eeed659719/Frameworks/SPMySQLFramework/Source/SPMySQLResult%20Categories/Field%20Definitions.m#L46


Short fix: we can manually add to list of charsets.


Long term: we may want to consider having Sequel Ace dynamically building this list by using so we don't have to keep adding to the list manually.
```mysql
SHOW COLLATION;
select * from information_schema.collations;

SHOW CHARACTER SET;
select * from information_schema.character_sets;
```

**Comment by Jason-Morcos** [comment]
@luis- Agree completely, we probably should refactor this to be built dynamically

To add this charset for now,

@binmao2023 could you post the results of the query `SHOW COLLATION WHERE Charset = 'utf8mb4';`?
