### ISSUE TITLE
Error detail window's text truncated / can't scroll

### ISSUE THREAD

**Issue by nilbus** [Sequel-Ace/Sequel-Ace#182]
- Sequel Ace Version: 2.1.1
- macOS Version: 10.15.5
- MySQL Version: n/a

**Description**
SSH connection error detail output is not scrollable, making it appear as if there are no more lines beyond the bottom of the window. This is especially misleading with longer errors.

**Steps To Reproduce**
1. Attempt to connect via SSH in a way that produces an error
2. Click the Show Detail button
3. If the error output does not fill the entire detail window, resize the window to be smaller. Observe that you cannot scroll to lines below the window fold.

**Expected Behaviour**
The error output should be scrollable.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
There's no PR addressing this, so I assume it's present.

**Additional Context**
Workaround: Make the window larger, and/or pinch-zoom to make the text smaller.

**Comment by Jason-Morcos** [comment]
Good catch! Please try this new beta and let me know if it's now working for you!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.2-beta2

**Comment by nilbus** [comment]
✅ Scrolling works now for long messages. 🎉 

This shouldn't necessarily block the scrolling fix, but this change introduced some weird behavior for shorter error messages when resizing.
![resize](https://user-images.githubusercontent.com/64751/86935183-8ac19e80-c10a-11ea-98a6-629fa57f0474.gif)

**Comment by Jason-Morcos** [comment]
> ✅ Scrolling works now for long messages. 🎉
> 
> This shouldn't necessarily block the scrolling fix, but this change introduced some weird behavior for shorter error messages when resizing.
> ![resize](https://user-images.githubusercontent.com/64751/86935183-8ac19e80-c10a-11ea-98a6-629fa57f0474.gif)

@Sequel-Ace/all I feel like we saw a similar issue somewhere else. Does anyone remember/know how to solve?

**Comment by jamesstout** [comment]
`<off-topic/>`What app did you sue to make the gif?

**Comment by Kaspik** [comment]
@jamesstout https://gifox.io :)

**Comment by jamesstout** [comment]
> @Sequel-Ace/all I feel like we saw a similar issue somewhere else. Does anyone remember/know how to solve?

Not seeing the same issue on that branch, iMac19,1, 10.15.5

![Untitled3](https://user-images.githubusercontent.com/1576190/87021196-7b744b00-c207-11ea-8bbc-e0dbff9caf8f.gif)

**Comment by nilbus** [comment]
@jamesstout Are you testing with 2.1.2-beta2?

I used and recommend https://getkap.co (free).
