### ISSUE TITLE
Horizontal scroll vanishes on the Content section 

### ISSUE THREAD

**Issue by rpai9** [Sequel-Ace/Sequel-Ace#1821]
- Sequel Ace Version (including build number): 4.0.7/20050
- Sequel Ace Source (App Store/GitHub/Homebrew):App store
- macOS Version: 13.5 (22G74)
- Processor Type (Intel/Apple): intel
- MySQL Version:8.0.28
- macOS Localization: US-en

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes the issue is present on 4.0.7 RC

**Description**
The horizontal scroll bar vanishes and the only way to scroll horizontally is by using the trackpad (2 finger swipe). This is inconvenient if you are working with a closed clamshell most of the time. 
 
https://github.com/Sequel-Ace/Sequel-Ace/assets/68650968/46dcce86-4d1f-49e7-b461-41e2671faedd

**Steps To Reproduce**
1. Open any table that you need to scroll horizontally to view the data.
2. Try to scroll using just a mouse (normal one not the apple) the scroll bar vanishes in a few seconds after you open the table. 

**Expected Behaviour**

**Related Issues**

The issue might be similar to - https://github.com/Sequel-Ace/Sequel-Ace/issues/1677 

**Additional Context**

**Comment by samuelbradshaw** [comment]
Related: https://github.com/Sequel-Ace/Sequel-Ace/issues/1228 – there are a few workarounds here.
I assume you see the same issue on other apps with horizontal scroll too, like in Finder with column view enabled?

**Comment by rpai9** [comment]
@samuelbradshaw Thank you for pointing me to https://github.com/Sequel-Ace/Sequel-Ace/issues/1228! Changing the `Show scroll bars` to `Always`  fixes the issue.
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/68650968/2e8bbbca-8563-47d2-bb0f-baec272dbc90)
