### ISSUE TITLE
Import DB without foreign key checks

### ISSUE THREAD

**Issue by kossa** [Sequel-Ace/Sequel-Ace#1825]
Hello,

Is there a way to import DB without foreign key checks?

Thanks

**Comment by stychos** [comment]
Hi, by default for a long time mysqldump provides this out of the box. You can notice lines like these in you database dumps:
```/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;```

Anyway, you can try to open connection, run `SET FOREIGN_KEY_CHECKS = 0` in the Query tab, then perform an import. Or, you can add this as a first line in your dump. Don't forget to run `SET FOREIGN_KEY_CHECKS = 1` or add it as a last line in your dump.

**Comment by kossa** [comment]
Some file are big so dont want to open it and update it

The second solution is good, but need to be run each time I open sequel ace.

The best is to add it a configuration :)

**Comment by stychos** [comment]
> Some file are big so dont want to open it and update it
```SH
echo 'SET FOREIGN_KEY_CHECKS = 0' > new_dump.sql
cat old_dump.sql >> new_dump.sql
echo 'SET FOREIGN_KEY_CHECKS = 1' >> new_dump.sql
```

**Comment by kossa** [comment]
Thank you 👍
