### ISSUE TITLE
Couldn't save the password

### ISSUE THREAD

**Issue by Ihabafia** [Sequel-Ace/Sequel-Ace#1829]
- Sequel Ace Version (including build number): Version 4.0.7 Build 20050
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.7.8 (20G1351)
- Processor Type (Intel/Apple): Intel
- MySQL Version:  5.5.5-10.7.1-MariaDB-1:10.7.1+maria~focal
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
When I added all the information to the db and tested the connection, it success.  But when I tried to save the information I got the error: 
```An error occurred while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Ace team, supplying the error code -60005.```

**Steps To Reproduce**
1. Add a Connection, including the password.
2. Test and then save, it gives that error, but when I go back to it again, I found all the data saved except the db password.

**Expected Behaviour**
It used to save including the password with no issues.

**Comment by ssx** [comment]
I've also seen this on a M2 mac too.

**Comment by Jason-Morcos** [comment]
I'm not able to reproduce this issue on an M1 Max. If someone else is able to reproduce this, please submit a PR and I'd be happy to review!

Any chance you've been experimenting with the beta? Sometimes having the beta and normal app installed can mess with the keychain - it may be worth trying to clear out any "Sequel *" keychain items and trying again

<img width="704" alt="Screenshot 2023-09-04 at 13 05 47" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/b1dfb8a9-3987-4c6a-af6a-72105297ad80">

**Comment by ssx** [comment]
@Jason-Morcos that's a good shout - I think I was running the beta at some point so I think you're likely right there!
