### ISSUE TITLE
SSH Config unexpectedly overridden when adding accessible files

### ISSUE THREAD

**Issue by nilbus** [Sequel-Ace/Sequel-Ace#183]
- Sequel Ace Version: 2.1.1
- macOS Version: 10.15.5
- MySQL Version: n/a

**Description**
Adding an accessible file (introduced in #114) always and unexpectedly overrides the selected ssh config file.

**Steps To Reproduce**
1. Under Network settings, select an SSH Config file (e.g. ~/.ssh/config).
2. Under File settings, add any other file.
3. Under Network settings, observe that the SSH Config file selection is now blank.
4. Make a connection using an SSH tunnel. Observe that the SSH command includes `-F /path/to/newly-added/file`.
5. Under Network settings, restore the selected an SSH Config file (e.g. ~/.ssh/config).
6. Make a connection using an SSH tunnel. It should work again.

**Expected Behaviour**
Adding a file under Files settings should not automatically change the SSH Config setting.

In my specific scenario, I'm in a troubleshooting loop where I'm adding additional files until my SSH connection works. Each time, I have to go back and reset my SSH Config setting.

**Additional Context**
It seems to me that this may be the offending code:
https://github.com/Sequel-Ace/Sequel-Ace/blob/d0d768492336aaf752c47b41f5de79a90fdfd22f/Source/SPFilePreferencePane.m#L277-L285

**Comment by Jason-Morcos** [comment]
Yup. We discovered this issue recently. Can you try out the latest 2.1.2 beta? It should be fixed there. 

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by Tklaversma** [comment]
@Jason-Morcos it is not fixed in beta 2.1.2 yet. Just tried it.

When I set my SSH config in the network tab, then restart the app and connect to a server.. it fails on the config.
But when I set my SSH config in the network tab without restarting after, it works. FYI @nilbus

**Comment by Tklaversma** [comment]
@nilbus @Jason-Morcos 
Just found a work around. If you add your private key to the list as well.. its should work.

Debug log showed "no access" to id_rsa

**Comment by nilbus** [comment]
Confirmed fixed in 2.1.2-beta2. 🎉 

@Tklaversma It sounds like you're describing a separate issue that I can't reproduce. Mind filing a new issue?

**Comment by Tklaversma** [comment]
@nilbus will do
