### ISSUE TITLE
Cannot open database using url with url characters inside dbUser, psw or database

### ISSUE THREAD

**Issue by Sander-Addink** [Sequel-Ace/Sequel-Ace#1843]
- Sequel Ace Version (including build number): Version 4.0.8, Build 20051
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: Version 13.5.2 (22G91)
- Processor Type (Intel/Apple): Intel Core i7
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
When trying to open a database from the command line using `open mysql://root:passw?rd@127.0.0.1:3306/db -a Sequel Ace` the password is not read properly (I'm assuming it is because it contains a special url character). When using percent-encoding to avoid this issue the password is not decoded and will directly be put in as password.

**Steps To Reproduce**
1. Connect to a database having a url characters in the password (for example: `open mysql://root:passw?rd@127.0.0.1:3306/db -a Sequel Ace`)

**Expected Behaviour**
I would expect that the specified user, password and database are decoded using percent-decoding before using them.

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
I feel like using glob-style characters in db passwords is generally bad practice because of things like this.
Are you able to change the password? If so, could you use a password that contains more safe characters like `: @ . , / + - ! =` instead of `" ' $ , [ ] * ? { } ~ # % \ < > | ^ ;`?

**Comment by harmputman** [comment]
I disagree, questionmark should be a valid password character, should be URL encoded though.

Just tested with other database clients and url encoded password e.g. `open mysql://root:passw%3Frd@127.0.0.1:3306/db` and client successfully opened the client.

**Comment by samuelbradshaw** [comment]
It seems like this could be problematic either way. For example, if your password actually contained a percent sign, it would get "decoded" then would fail to authenticate.

**Comment by Jason-Morcos** [comment]
> It seems like this could be problematic either way. For example, if your password actually contained a percent sign, it would get "decoded" then would fail to authenticate.

Completely agree with @samuelbradshaw - I don't think there's a great answer here because of this problem

**Comment by harmputman** [comment]
If your password contains a percent sign it should be urlencoded too (`%25`). This should work in a URL as well.

**Comment by Jason-Morcos** [comment]
That's a good point
It should be pretty straight-forward to find the place in the code that processes these inbound connection URLs (I'd start with the SPAppController around line 904 - `handleMySQLConnectWithURL`). You're welcome to take a stab at addressing this and opening a PR that adds support for these encoded URLs. I'd be happy to review it and include it in a future release :)
