### ISSUE TITLE
Filter bar should have an option to hide

### ISSUE THREAD

**Issue by jonjieviduya** [Sequel-Ace/Sequel-Ace#1848]
The filter bar should have an option to hide to make it cleaner and more space to work on. And why is that every time I switch tables, it opens? I don't understand the behavior of this filter bar.

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/60085585/1de49cfe-a3a8-4e45-bd09-f2e3dfc8abdb)

**Comment by Jason-Morcos** [comment]
It does have an option to hide - try the funnel icon in the footer of the content view. Please let us know if that option isn't working as expected

**Comment by jonjieviduya** [comment]
> It does have an option to hide - try the funnel icon in the footer of the content view. Please let us know if that option isn't working as expected

Oh, this is the one im looking for. Thanks
