### ISSUE TITLE
Connection Timeout can't be set to 0 seconds in preferences

### ISSUE THREAD

**Issue by Genjiff** [Sequel-Ace/Sequel-Ace#1852]
- Sequel Ace Version (including build number): Version 4.0.9 Build 20052
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.7.8
- Processor Type (Intel/Apple): Intel
- MySQL Version: Any
- macOS Localization: English (United States)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
If the connection timeout is set to 0 in preferences, when trying to connect via SSH to a DB, the ConnectTimeout parameter is still 10 seconds.

**Steps To Reproduce**
1. Set a SSH connection that will fail (so you can see the command that is used in the failure screen)
2. Open Preferences > Network > Connection Timeout and set it to 0 seconds
3. Close preferences and click connect
4. In the failure screen you should see `Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10...`

**Expected Behaviour**
The ConnectTimeout option should use 0 when 0 is set in the preferences

**Related Issues**
None

**Comment by Jason-Morcos** [comment]
Practically, what's the value of a connection timeout of zero? Does zero make practical sense? What are you trying to accomplish here?

**Comment by Genjiff** [comment]
0 means "use the default system TCP timeout", it's the same as not passing this parameter. The connection to some servers can fail if a custom value to this option is set, and that was how I discovered this bug. What I'm trying to accomplish is being able to connect with such servers.

**Comment by Jason-Morcos** [comment]
Thanks for the detailed response, @Genjiff. Will try to resolve this.

**Comment by Jason-Morcos** [comment]
Included in the latest beta of 4.0.10!
https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F4.0.10-20054

**Comment by Genjiff** [comment]
Thanks for solving it so quickly :)
