### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by stefanfuerst** [Sequel-Ace/Sequel-Ace#1865]
- Sequel Ace Version: 4.0.9
- Sequel Ace Source: App Store
- macOS Version: 10.15.7
- Processor Type: Intel/Apple;
- MySQL Version: irrelevant
- macOS Localization: irrelevant

**Description**
Crash on launch

**Steps To Reproduce**
1. Start
2. Crash

**Additional Context**

Process:               Sequel Ace [2209]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
Identifier:            com.sequel-ace.sequel-ace
Version:               4.0.9 (20052)
App Item ID:           1518036000
App External ID:       860235150
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Ace [2209]
User ID:               501

Date/Time:             2023-10-04 09:06:39.830 +0200
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Bridge OS Version:     6.6 (19P6064)
Anonymous UUID:        8F997FB5-252D-B378-FD1C-FB943520969E

Sleep/Wake UUID:       9F795FA0-3B9D-4998-B6A2-DEDFC24910E3

Time Awake Since Boot: 2400 seconds
Time Since Wake:       1200 seconds

System Integrity Protection: enabled

Crashed Thread:        16

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2209]

VM Regions Near 0:
--> 
    __TEXT                 00000001061e6000-000000010661e000 [ 4320K] r-x/r-x SM=COW  /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6a9b6dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6a9b7160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff30bf1135 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff30befc02 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff30bef07e CFRunLoopRunSpecific + 462
5   com.apple.HIToolbox           	0x00007fff2f81baad RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff2f81b7c5 ReceiveNextEventCommon + 584
7   com.apple.HIToolbox           	0x00007fff2f81b569 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff2de643c9 _DPSNextEvent + 883
9   com.apple.AppKit              	0x00007fff2de62c10 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
10  com.apple.AppKit              	0x00007fff2de5491e -[NSApplication run] + 658
11  com.apple.AppKit              	0x00007fff2de26706 NSApplicationMain + 777
12  libdyld.dylib                 	0x00007fff6a875cc9 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff6aa75b68 start_wqthread + 0

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff6a9b6dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6a9b7160 mach_msg + 60
2   com.sequel-ace.sequel-ace     	0x0000000106558005 plcrash::async::gnu_ehptr_reader<unsigned long long>::read(plcrash_async_mobject*, unsigned long long, long long, plcrash::async::DW_EH_PE, unsigned long long*, unsigned long*) + 32173
3   libsystem_pthread.dylib       	0x00007fff6aa7a109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff6aa75b8b thread_start + 15

Thread 12:: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib        	0x00007fff6a9b9872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6aa7a425 _pthread_cond_wait + 698
2   libc++.1.dylib                	0x00007fff67b46623 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 93
3   com.apple.JavaScriptCore      	0x00007fff353f7a55 bmalloc::Scavenger::threadRunLoop() + 741
4   com.apple.JavaScriptCore      	0x00007fff353f7469 bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 9
5   com.apple.JavaScriptCore      	0x00007fff353f9b47 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 39
6   libsystem_pthread.dylib       	0x00007fff6aa7a109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6aa75b8b thread_start + 15

Thread 13:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6a9b6dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6a9b7160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff30bf1135 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff30befc02 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff30bef07e CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff2e005bf4 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff6aa7a109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6aa75b8b thread_start + 15

Thread 14:
0   libsystem_kernel.dylib        	0x00007fff6a9b6dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6a9b7160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff30bf1135 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff30befc02 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff30bef07e CFRunLoopRunSpecific + 462
5   com.apple.Foundation          	0x00007fff333b3fad -[NSConnection run] + 115
6   com.apple.Foundation          	0x00007fff33287222 __NSThread__start__ + 1064
7   libsystem_pthread.dylib       	0x00007fff6aa7a109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6aa75b8b thread_start + 15

Thread 15:: SPSSHTunnel SSH binary communication task
0   libsystem_kernel.dylib        	0x00007fff6a9b6dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6a9b7160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff30bf1135 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff30befc02 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff30bef07e CFRunLoopRunSpecific + 462
5   com.apple.Foundation          	0x00007fff33343210 -[NSConcreteTask waitUntilExit] + 325
6   com.sequel-ace.sequel-ace     	0x00000001062e8ba2 0x1061e6000 + 1059746
7   com.sequel-ace.sequel-ace     	0x00000001063b7a61 0x1061e6000 + 1907297
8   com.apple.Foundation          	0x00007fff33287222 __NSThread__start__ + 1064
9   libsystem_pthread.dylib       	0x00007fff6aa7a109 _pthread_start + 148
10  libsystem_pthread.dylib       	0x00007fff6aa75b8b thread_start + 15

Thread 16 Crashed:
0   ???                           	000000000000000000 0 + 0
1   com.sequel-ace.spmysql        	0x00000001067c69e9 mysql_options4 + 329
2   com.sequel-ace.spmysql        	0x00000001067c415c csm_begin_connect(mysql_async_connect*) + 348
3   com.sequel-ace.spmysql        	0x00000001067c3f85 mysql_real_connect + 197
4   com.sequel-ace.spmysql        	0x00000001067a7e2f -[SPMySQLConnection(PrivateAPI) _makeRawMySQLConnectionWithEncoding:isMasterConnection:] + 1429
5   com.sequel-ace.spmysql        	0x00000001067a7615 -[SPMySQLConnection(PrivateAPI) _connect] + 310
6   com.sequel-ace.sequel-ace     	0x00000001062f7fcd 0x1061e6000 + 1122253
7   com.sequel-ace.sequel-ace     	0x00000001063b7a61 0x1061e6000 + 1907297
8   com.apple.Foundation          	0x00007fff33287222 __NSThread__start__ + 1064
9   libsystem_pthread.dylib       	0x00007fff6aa7a109 _pthread_start + 148
10  libsystem_pthread.dylib       	0x00007fff6aa75b8b thread_start + 15

Thread 16 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000016  rbx: 0x00006000027e3060  rcx: 0x0000000000000001  rdx: 0x0000000106b93cec
  rdi: 0x0000000000000038  rsi: 0x00007fff67b8e750  rbp: 0x000070000a6757d0  rsp: 0x000070000a675728
   r8: 0x00000001065c3bd5   r9: 0x000000000000c247  r10: 0x00000000fe000000  r11: 0x00000001067a735d
  r12: 0x0000000000000000  r13: 0x000070000a675789  r14: 0x0000000000000016  r15: 0x00007fc5d702be00
  rip: 0x0000000000000000  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000014 (no mapping for user instruction read)
Trap Number:     14

**Comment by Jason-Morcos** [comment]
I think this is a duplicate - See #1858
