### ISSUE TITLE
No access "id_rsa" when using own SSH config file

### ISSUE THREAD

**Issue by Tklaversma** [Sequel-Ace/Sequel-Ace#187]
- Sequel Ace Version: 2.1.2-beta2 Build 2057
- macOS Version: 10.15.5
- MySQL Version: n/a

**Description**
Adding your own SSH config in the network tab, then restarting the app and then trying to connect to your database (with your config settings of course), give the error "no access" to the ```id_rsa``` file (private key), which is needed for the connection of course.

In order for this to work, I've added my id_rsa file to the tab "Files" as an accessible file.

This makes sense, but it would be nice if this happens automatically or in the background when adding your SSH config in the network tab

**Steps To Reproduce**
1. add SSH config in the network tab
2. close the app
3. start the app
4. try to connect to your database with your ssh config
5. getting an "no access" error to the id_rsa file

**Expected Behaviour**
Adding id_rsa file (private key) automatically to the accessible files list (under tab Files) or gain access in the background

**Comment by Jason-Morcos** [comment]
Unfortunately, due to sandboxing, there is absolutely no way we can automatically get access to your id_rsa key. Sandbox is very very strict and required for App Store release.

**Comment by Tklaversma** [comment]
@Jason-Morcos understandable. I would prefer you'd make an update in the readme though so others now about this "issue". Do you agree?

**Comment by Jason-Morcos** [comment]
Would gladly accept a PR to the documentation or readme. How would that look, however?

**Comment by RoodFruit** [comment]
@Jason-Morcos hmmm.. though one. Maybe this issue that is closed should be enough doc? Let's go with that.
