### ISSUE TITLE
Crash upon opening connection with new sonora build

### ISSUE THREAD

**Issue by Ornis007** [Sequel-Ace/Sequel-Ace#1870]
After installing the new sonora build, Sequel Ace crashes immediately after opening connection with either external host as well as local host.

Sequel Ace Version 4.0.9
Updated through app store 2023-10-05
Build 20052

on

MacBook Pro Retina 15 (Mid 2014)
Mac OS 11.7.9
2.8 GHz Quad-Core Intel Core i7

<img width="295" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/118893241/21701668-4cf8-4bc0-a535-8a88362543e8">

**Comment by Jason-Morcos** [comment]
Will be fixed in 4.0.10 which is targeted for release as soon as tonight.
