### ISSUE TITLE
Multiple Tabs then change the selected table, and the Tab title displayed error

### ISSUE THREAD

**Issue by evanyangg** [Sequel-Ace/Sequel-Ace#1873]
- Sequel Ace Version (including build number): 4.0.10
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version:  Sonoma 14.0
- Processor Type (Intel/Apple): Apple
- MySQL Version:  8.0.25
- macOS Localization: 

**Description**
When there are multiple Tabs, if the table selected under a certain tab is modified, the corresponding tab title will display an error.

**Steps To Reproduce**
1. Open multiple Tabs
2. Select one of the Tabs and Click Table name

**Expected Behaviour**
The selected table only modifies the current tab title

**Comment by Jason-Morcos** [comment]
Duplicate, use search
