### ISSUE TITLE
Table History back button doesn't keep going back, instead swaps between two most recent tables

### ISSUE THREAD

**Issue by dyllandry** [Sequel-Ace/Sequel-Ace#1878]
- Sequel Ace Version (including build number): Version 4.0.9 Build 20052
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version: 13.5.2 (22G91)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.1.0
- macOS Localization: English Canada?

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

When I hit the back Table History button repeatedly, it always swaps between the two last visited tables. It never goes further back in history.

**Steps To Reproduce**
1. Connect to DB
2. Navigate to three different tables A > B > C
3. Hit back button, goes to table B
4. Hit back button, goes to table C
5. Hit back button, goes to table B

**Expected Behaviour**

I'd have expected it to go C > B > A not C > B > C.

**Related Issues**

Maybe https://github.com/Sequel-Ace/Sequel-Ace/issues/1288 ? I'm not sure.

**Additional Context**

When I click and hold on the back history button, I see that the app is pushing the table I just went back from on to the top of the stack. That probably shouldn't happen if someone presses the back button.

**Comment by luis-** [comment]
I have fix more or less in place, but need to do some more manual testing after work. Will open PR if all goes well.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases
