### ISSUE TITLE
The Running query modal window is not modal anymore

### ISSUE THREAD

**Issue by bntswn** [Sequel-Ace/Sequel-Ace#1879]
- Sequel Ace Version (including build number): 4.0.10 (20057)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 13.5.2
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.32
- macOS Localization: French

**Is Issue Present in 4.0.10 (20056)?**
Yes.

**Description**
The Running query modal window is not modal anymore. It can disappear below the main window while running a query and appears in the Exposé window list.

**Steps To Reproduce**
1. Type in a query that takes some time to execute in the query editor.
2. Run the query.

**Expected Behaviour**
We should have a **modal** transparent window on the top of the main window saying "Running query" with a "Stop query" button and this window **should remain modal** whatever the action is performed in the interface within the current tab.

![SequelAceModal](https://github.com/Sequel-Ace/Sequel-Ace/assets/129183874/9550d662-4811-4bf8-a470-5cee71b688e1)

**Comment by Jason-Morcos** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/pull/1849

@Tantalon Do you have any thoughts here?

**Comment by Tantalon** [comment]
The first time it shows it stays in front.
On subsequent shows it no longer stays in front.

The difference appears to be the parent relationship. The progress window is initially parented to the main window, and on subsequent shows it's not. Still checking to see how it's losing the parent relationship.
