### ISSUE TITLE
Is it possible to open and connect from the command line?

### ISSUE THREAD

**Issue by chellman** [Sequel-Ace/Sequel-Ace#189]
macOS 10.14.6, Sequel Ace 2.1.1 build 2053.

I know it's possible to construct a plist file that Sequel Ace can ingest and connect.  Is it possible to pass command line params into the app to make a connection, ala MySQL Workbench?

`"/Applications/MySQLWorkbench.app/Contents/MacOS/MySQLWorkbench" --query "root:root@127.0.0.1:3306"`

I'm looking to create a command a Docker-based LAMP stack that can grab the database container details and construct a direct connection into Sequel Ace.  The port changes, so a simple bookmark isn't what I'm looking for.

**Comment by Jason-Morcos** [comment]
I believe it is not currently possible, but I am unsure. Certainly something that is possible to add, unsure of the size of the undertaking to do so.

**Comment by cafferata** [comment]
You can use the macOS `openURL`

```bash
open "mysql://root:root@127.0.0.1:3306/db"
```

Or if Sequel Ace is not your default application, you can use

```bash
open "mysql://root:root@127.0.0.1:3306/db" -a "Sequel Ace"
```

**Comment by chellman** [comment]
@cafferata Perfect! That's just the thing.
