### ISSUE TITLE
Cancel a query.

### ISSUE THREAD

**Issue by tamasssimon** [Sequel-Ace/Sequel-Ace#1891]
In the previous versions, there was a popup showing query in progress, with a cancel button.   It seems to have disappeared.  if we launch a query accidentally (or a long running query), no way to get control back to the editor.

I am on 
Version 4.0.10
Build 20057

Thanks!
Simon

**Comment by Jason-Morcos** [comment]
Hey! We're pushing a 4.0.11 release tonight that I think will fix this. Please give 4.0.11 a try (available on GitHub soon) and let us know if the issue persists beyond that. Thanks!
