### ISSUE TITLE
Eexport doesnt' work at all

### ISSUE THREAD

**Issue by glitchtracker** [Sequel-Ace/Sequel-Ace#1898]
- Sequel Ace Version (including build number): 4.011
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Sonoma 14.0
- Processor Type (Intel/Apple): M1 Pro
- MySQL Version: MySQL 5.5.5-10.5.21-MariaDB-log (AWS)
- macOS Localization: French

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1. Clic the export button Filetered  query or Query result

**Expected Behaviour**

a file with the exported data

but a barregraph taht evers ends appears

**Comment by Jason-Morcos** [comment]
Hi, 
Unfortunately we don't support MySQL < 5.7. 
Please try an older version of Sequel Ace if you need to use 5.5.

https://github.com/Sequel-Ace/Sequel-Ace?tab=readme-ov-file#compatibility

Thank you
