### ISSUE TITLE
Will Sequel Ace add support for sqlserver

### ISSUE THREAD

**Issue by successgo** [Sequel-Ace/Sequel-Ace#1899]
Hello, Sequel Ace team,

Sequel Ace is so great, and I have been using Sequel Pro now Sequel Ace for years. Thanks for all your contributions to the software.

If there is any possibility to add support for sqlserver, I hope this request is not rude, and I'm sorry if so.

**Comment by Jason-Morcos** [comment]
Hey @successgo!

Glad you've been enjoying Ace! Unfortunately I don@5 think we have bandwidth to add support for additional types of engines today, but we'd be open to PRs that add this support if someone in the community is interested in doing so!

Thanks,
Jason
