### ISSUE TITLE
Unable to connect to RDS MySQL ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by samlin86** [Sequel-Ace/Sequel-Ace#190]
- Sequel Ace Version: 2.1.1 build 2053
- macOS Version: Mojave 10.14.6
- MySQL Version: 5.6.34

**Description**

I am unable to connect to a few of my RDS MySQL instances. The error I get upon connecting is `MySQL said: SSL connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

The instance does not have SSL enabled, and is publicly available.

I am previously able to connect (and still am) using nightly build of Sequel Pro.

**Steps To Reproduce**
1. Enter hostname, password, database. Connect using SSL is not checked.
2. Click Connect

**Expected Behaviour**
Connected to MySQL instance.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Tried 2.1.2 Beta 3 - error still present.

**Additional Context**
![Screen Shot 2020-07-08 at 2](https://user-images.githubusercontent.com/24234325/86972056-2103bd80-c127-11ea-9ec7-863878f80987.png)

**Comment by Kaspik** [comment]
Might be related? https://stackoverflow.com/a/50842202/4927614

**Comment by samlin86** [comment]
> Might be related? https://stackoverflow.com/a/50842202/4927614

In the host field I have entered the direct endpoint (there is no mysql:// equivalent if I'm understanding correctly).

I am using straight TCP/IP (not Socket or SSH). Port is standard 3306.

**Comment by Kaspik** [comment]
I was more referring to if you use `https` or `http` - anyways I have no way to repro this so I'll leave it up to anyone else. 🤷🏻‍♂️

**Comment by gboudreau** [comment]
> The instance does not have SSL enabled

Are you sure? I thought all RDS instances supported SSL.
Can you try to connect using SSL?
Specify the `rds-combined-ca-bundle.pem` file in the `CA Cert` field in Sequel Ace; you can download this file here:
https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem

**Comment by bobber205** [comment]
@samlin86 Have you had a chance to try @gboudreau 's suggestion yet?FWIW I tried it and it made no difference. Same error.

**Comment by samlin86** [comment]
@bobber205 sorry I had been MIA for a bit. I tried the solution @gboudreau suggested above and it gives the same error. Looks like the same connection properties that you are also running into on your [issue](https://github.com/Sequel-Ace/Sequel-Ace/issues/267#issuecomment-671467497). All our Dev servers are fine, just not the production instances.

Another possibility that I might float here is that earlier this year in March 2020, everyone was required to rotate their Certificate authority on their RDS instances to the latest version, `rds-ca-2019` from `rds-ca-2015`. We did so on our Staging/Dev instances, but we skipped restarting the instance (using the `--no-certificate-rotation-restart` flag) as we were not using SSL connection from our app to MySQL.

On the Console it shows us as having the latest version, but it won't be applied until the next instance restart. Could this be a hint?

![Screen Shot 2020-08-17 at 1 32 19 PM](https://user-images.githubusercontent.com/24234325/90441620-1fb2a280-e08e-11ea-844d-ef75d2c56725.png)

**Comment by bobber205** [comment]
@samlin86 Rebooted our production DB and getting the same error.

**Comment by bobber205** [comment]
I really want this to keep open thanks!

**Comment by qintianli** [comment]
I encountered same error, tried using CA Cert but didn't help, any update?

**Comment by gboudreau** [comment]
No update no. No developer was able to reproduce this issue yet.

**Comment by Ray0427** [comment]
Sequel Ace Version: 2.2.2 build 2104
macOS Version: Mojave 10.15.7
MySQL Version: 5.6.34
I have this problem only in one RDS, and the others RDS is fine.
In the same computer Sequel Pro can connect, but Sequel Ace happened this problem.

**Comment by Jason-Morcos** [comment]
> Sequel Ace Version: 2.2.2 build 2104
> macOS Version: Mojave 10.15.7
> MySQL Version: 5.6.34
> I have this problem only in one RDS, and the others RDS is fine.
> In the same computer Sequel Pro can connect, but Sequel Ace happened this problem.

Any idea what's different between the two RDS instances? Different versions? Different settings? Knowing what's different between the two is crucial to figuring out why one works and the other doesn't

**Comment by Ray0427** [comment]
> > Sequel Ace Version: 2.2.2 build 2104
> > macOS Version: Mojave 10.15.7
> > MySQL Version: 5.6.34
> > I have this problem only in one RDS, and the others RDS is fine.
> > In the same computer Sequel Pro can connect, but Sequel Ace happened this problem.
> 
> Any idea what's different between the two RDS instances? Different versions? Different settings? Knowing what's different between the two is crucial to figuring out why one works and the other doesn't

The different between the two instances:

the primary insance can't connect
- Role: Primary
- Class: db.r4.large
- Region & AZ: us-east-1c

the replica instance can connect
- Role: Replica
- Class: db.m5.large
- Region & AZ: us-east-1b

**Comment by outie** [comment]
Having the same issue on master+replications RDS instances. They just won’t connect with the same SSL error. I am trying to connect via TCP/IP that works just fine with Sequel Pro.

**Comment by Jason-Morcos** [comment]
https://github.com/openssl/openssl/issues/6289
This seems to suggest cipher mismatches between the server and the client could cause this issue. Or perhaps the replica instance has different TLS settings/support than the primary?

**Comment by thunderquote** [comment]
Had this issue for one of my RDS instances. Was working with Sequel Pro Nightly but not Sequel Ace

Main issue was that I was still using the old RDS certificate. Once I went to the DB, click modify and adjusted the certificate settings to use rds-ca-2019, the problem resolved

![image](https://user-images.githubusercontent.com/25244900/99151973-dcda8800-26d9-11eb-8ded-ba3d4f341fdd.png)

**Comment by bobber205** [comment]
@thunderquote Awesome man! I'll check this on my prod DB and see if it works on Monday.

**Comment by outie** [comment]
@thunderquote Mine is already at rds-ca-2019. I think few months or last year AWS wanted us to update it but also gave us a no-reboot option, which is what I used as we don't use SSL for connections. I just rebooted the RDS instance and I can now connect to it using Sequel Ace like normal.

**Comment by samlin86** [comment]
This is what I mentioned above but @bobber205 said they rebooted their instance and it didn't solve it. https://github.com/Sequel-Ace/Sequel-Ace/issues/190#issuecomment-675099138

Unfortunately our production workload is unable to be rebooted, so I cannot test this theory - what you mentioned @outie is exactly what we did as well.

**Comment by thunderquote** [comment]
I guess a solution would be to see if the SSL protocol connection should be disabled unless the "Connect using SSL" option in Sequel Pro is checked, which is the expected behaviour? I find it strange that it still attempts to establish an SSL connection even if the option is not checked.

**Comment by Kaspik** [comment]
Latest release had updated ciphers and seems like this is not really an issue with Sequel Ace, right? Can we close this?

**Comment by timbuckingham** [comment]
I'm having this same issue with the latest 12/29 app store build while connecting to an RDS instance through an EC2 SSH tunnel.

**Comment by Jason-Morcos** [comment]
@timbuckingham Do you have any new info that might help us reproduce the issue? Reading through the previous comments, the issue auto-closed after no devs were successful in reproducing it and behavior for users was inconsistent at best and seemed to be a likely environment issue (server reboots seemed to fix at least sometimes).

Does the latest 3.1.0 beta also still have this issue for you? 

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by timbuckingham** [comment]
The latest beta still has the issue for me:

> MySQL said: SSL connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
> SSL connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Not sure if it's helpful, but the RDS instance is in US-East-1b with multi-zone availability in US-East-1a on MySQL Community Engine version 5.7.19.

**Comment by Jason-Morcos** [comment]
> Had this issue for one of my RDS instances. Was working with Sequel Pro Nightly but not Sequel Ace
> 
> Main issue was that I was still using the old RDS certificate (rds-ca-2015). Once I went to the AWS console, clicked modify and adjusted the certificate settings to use rds-ca-2019, the problem resolved. Think the issue was it was still using the expired certificate:
> https://aws.amazon.com/blogs/database/amazon-rds-customers-update-your-ssl-tls-certificates-by-february-5-2020/
> 
> I ignored it. since i wasn't using SSL to connect to the instance, but apparently Sequel Ace does an SSL connection or something.
> 
> ![image](https://user-images.githubusercontent.com/25244900/99151973-dcda8800-26d9-11eb-8ded-ba3d4f341fdd.png)

@timbuckingham Have you tried the steps in this comment?

**Comment by bobber205** [comment]
I've been having this issue and this cert suggestion fixed it for me!

There is where I found the pending update.

![image](https://user-images.githubusercontent.com/5841107/104070914-d7228f80-51bc-11eb-91bc-c0f8af643deb.png)

![image](https://user-images.githubusercontent.com/5841107/104070902-cf62eb00-51bc-11eb-9b37-8ef70bd5b99e.png)

**Comment by timbuckingham** [comment]
I haven't had a chance to do a restart of our production server to test out whether that's an issue, but shouldn't it not use SSL if the Connect using SSL option isn't checked? I suppose that may be a separate issue.

**Comment by rsmck** [comment]
I think I have the same issue (hence not opening a new one) but it seems that Sequel Ace is attempting to connect with SSL even if the Connect Using SSL option is not checked. As a result it's impossible to connect to non-SSL MySQL / MariaDB services at all.

**Comment by armetiz** [comment]
I have the same issue using latests Sequel ACE 3.4.5, with a MySQL server 5.7.19 without SSL.

**Comment by Jason-Morcos** [comment]
This should be fixed in the upcoming 3.5.1 update (no beta available yet) as part of issue #1351 @armetiz

**Comment by aleemb** [comment]
Received this error a few days ago out of the blue:

    MySQL said: SSL connection error: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

AWS had prompted for certificate updates which I did following which this error is now persistent.

**Comment by Jason-Morcos** [comment]
@aleemb if you can figure out what cipher might be missing, we can try to add it. You could see if it's clear from the AWS console?
