### ISSUE TITLE
The left tree table list panel has disappeared.

### ISSUE THREAD

**Issue by zhaoyou** [Sequel-Ace/Sequel-Ace#1904]
- Sequel Ace Version (including build number):Version 4.0.11  Build 20057
- Sequel Ace Source (App Store/GitHub/Homebrew): AppStore
- macOS Version:Mac Mini 2023 Sonoma 14.0
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.1
- macOS Localization: CN

**Description**

After opening the software, select any of the links that have been saved in your personal collection on the left and click on the link to connect successfully. This time directly display the right side of the direct display query form. The left side of the table tree menu structure can not be seen.

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/612257/dcca7516-990c-43ac-82c0-a6f0db49791c)

Additional information:

1) The software was working fine before, and at some point after connecting to the server the panel on the left did not appear.
2) Reinstalling the software didn't work either
3) Clicking on the menu [Table] at the top of the software to display the filter table doesn't work either.

![截屏2023-10-30 10 05 29](https://github.com/Sequel-Ace/Sequel-Ace/assets/612257/8416d624-d489-4d4d-81d8-b43f73b32203)

**Comment by samuelbradshaw** [comment]
Related: https://github.com/Sequel-Ace/Sequel-Ace/issues/1101

**Comment by zhaoyou** [comment]
I Got it.
The table panel on the left has a width of 0. You need to manually widen it a bit. 😺

**Comment by ignacio-chiazzo** [comment]
> The table panel on the left has a width of 0. You need to manually widen it a bit. 😺

Thank YOU! it took me quite some time to figure it out.

**Comment by Eccatoe** [comment]
> I Got it. The table panel on the left has a width of 0. You need to manually widen it a bit. 😺
@zhaoyou How do you widen this panel? I have been trying forever. I cannot select it with my resize cursor

**Comment by busy-mango** [comment]
> #1101

I have same problem

**Comment by blankbro** [comment]
> I Got it. The table panel on the left has a width of 0. You need to manually widen it a bit. 😺

how to set it?

**Comment by zhaoyou** [comment]
> > I Got it. The table panel on the left has a width of 0. You need to manually widen it a bit. 😺
> 
> Hello, I have been searching for a long time and have not found the side extension sidebar or the parameter setting area. Thank you for your answer and hope to provide a detailed configuration path. I have been puzzled by this issue for a long time

Put the mouse on the left edge and pull it to the right.

**Comment by blankbro** [comment]
> > > I Got it. The table panel on the left has a width of 0. You need to manually widen it a bit. 😺
> > 
> > 
> > Hello, I have been searching for a long time and have not found the side extension sidebar or the parameter setting area. Thank you for your answer and hope to provide a detailed configuration path. I have been puzzled by this issue for a long time
> 
> Put the mouse on the left edge and pull it to the right.

very very very very very Thanks. 👍(づ￣3￣)づ╭❤～

**Comment by bicpi** [comment]
Oh wow, never happened to me in years of using it; I searched all menus to find if I may have disabled the sidebar ... thx for this answer :-)
