### ISSUE TITLE
Export doesn't allow setting export location

### ISSUE THREAD

**Issue by levi** [Sequel-Ace/Sequel-Ace#1906]
When trying to export a table, the export dialog complains that there is no location set. When trying to set a location, no finder window opens to allow for selection, nor is the path text field editable.

**Comment by Jason-Morcos** [comment]
Please fill out the full issue template when creating issues including particularly the version of Sequel Ace being used, version of MySQL/MariaDB, and any logs that may be applicable. Video recordings of glitches or unexpected behavior are particularly helpful. In the case of a feature request, please be sure to clearly explain what you're trying to accomplish (the root issue) and if any workarounds currently exist.

We try to be as helpful as possible, but the volume of issues reported limits us to only have time to dig into those that include all the details needed. I encourage you to open a new issue with all the details provided.

**Comment by levi** [comment]
Ok, just try to export on the latest version and you'll see the bug.

**Comment by Jason-Morcos** [comment]
I just tested and was able to export on the latest version.
