### ISSUE TITLE
Handling right mouse button in a table list without tables switch

### ISSUE THREAD

**Issue by stychos** [Sequel-Ace/Sequel-Ace#191]
- Sequel Ace Version: 2.1.1 b2053, 2.1.2-beta3 b2058
- macOS Version: 10.15.5
- MySQL Version: mysqld  Ver 5.7.30 for Linux on x86_64 (MySQL Community Server (GPL)) 

**Description**
When I clicking right mouse button in a table list to open a table in a new tab, main table view is automatically refreshsed with the table under the mouse

**Steps To Reproduce**
1. Click with right mouse button to call context menu
2. Wait few seconds

**Expected Behaviour**
Main view must not switch tables

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Comment by stychos** [comment]
Do not sure this is a "bug", because I see the same in Sequel Pro. And as I understand tables switching when an item in table list is selected (and obviously, it's selected on the context menu call). So, any thought if this feature can be implemented in future or not?

**Comment by samuelbradshaw** [comment]
I agree, as a user, I would not expect the selected table to switch when right-clicking on it. The same thing happens in the Favorites list before connecting to the database.
