### ISSUE TITLE
How to set the option of not displaying data tables in the database

### ISSUE THREAD

**Issue by zzwit** [Sequel-Ace/Sequel-Ace#1910]
My problem is linking the database and not displaying the database's tables. I don't know how to set it to display the data edge. I hope you can give me some advice
<img width="598" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/7939493/87f6852c-ad05-40c8-be44-f22af3a7c970">

<img width="657" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/7939493/bb8cdc12-2bc4-4042-94b3-768726f261cf">
My computer system version
<img width="301" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/7939493/b3c1ee43-00a3-440a-bce4-b15608e94134">

**Comment by zzwit** [comment]
How to set up to display the data table

**Comment by Jason-Morcos** [comment]
I think you might be looking for this? https://github.com/Sequel-Ace/Sequel-Ace/issues/1904

**Comment by zzwit** [comment]
Hello, I have been searching for a long time and have not found a side expansion sidebar. You can set a numerical value where you want to set the path for the side expansion sidebar. Thank you for your confusion. I have been puzzled for a long time
