### ISSUE TITLE
The left tree table list panel has disappeared

### ISSUE THREAD

**Issue by zzwit** [Sequel-Ace/Sequel-Ace#1911]
Hello, I have been searching for a long time and cannot find the side extension sidebar or parameter setting area. Thank you for your answer and would like to provide a detailed configuration path. This question has been confusing for a long time, and I don't know where to set it now

**Comment by zzwit** [comment]
<img width="548" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/7939493/fbdfee5e-b76d-4294-9a57-488ba7bcaa36">
<img width="706" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/7939493/e186eb3b-d9f1-476d-902d-c0b698faad63">

**Comment by zzwit** [comment]
Thank you. I know how to set it up now

**Comment by busy-mango** [comment]
> Thank you. I know how to set it up now谢谢。我现在知道如何设置了

how to set it?

**Comment by blankbro** [comment]
> Thank you. I know how to set it up now谢谢我现在知道怎么设置了

how to set it?
