### ISSUE TITLE
TABLE INFORMATION shows created and updated null on the left bottom corner

### ISSUE THREAD

**Issue by successgo** [Sequel-Ace/Sequel-Ace#1912]
- Sequel Ace Version (including build number): v4.0.11 Build 20057
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: macOS 14
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7
- macOS Localization: en-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Open and connect to any mysql database instance. Look at the left bottom corner.
<img width="282" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/13791720/d168902f-092a-4d60-9afe-47f42bbca5f1">

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Can't reproduce with MySQL 5.7. My guess is this is a permissions issue - as in your user account doesn't have permissions to see that info. Or, for some reason, those particular tables/databases have some interesting settings.

<img width="208" alt="Screenshot 2023-11-02 at 17 45 32" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/6ff94c22-30d5-4e60-8676-f89d8f8b049e">

**Comment by successgo** [comment]
Much thanks for your response.

I have tested on my local database instance and some cloud vendor database instances, the results are the same.

And one more interesting thing is some table does show  `updated` in table information.

<img width="279" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/13791720/b96f8372-2435-4b01-866d-2efe1ad84dd0">

I have no idea how to dig deepper for now.

**Comment by Jason-Morcos** [comment]
Super weird - is this working for others? @Sequel-Ace/all

**Comment by robinkunde** [comment]
It works for me

**Comment by gduh** [comment]
it's ok for me too!

**Comment by Jason-Morcos** [comment]
Closing - can reopen if we can get some reproduction/traction here

**Comment by successgo** [comment]
Fine though.
