### ISSUE TITLE
"Save Changes" button is greyed out in connection details

### ISSUE THREAD

**Issue by aegrant00** [Sequel-Ace/Sequel-Ace#1925]
4.0.12 Build 20059 - Sequel Ace Version (including build number):
App Store - Sequel Ace Source (App Store/GitHub/Homebrew):
Ventura 13.4 - macOS Version:
Intel - Processor Type (Intel/Apple):
8 - MySQL Version:
English - macOS Localization:

Issue exiasts in latest beta as well.
**Steps To Reproduce**
1. try and save a profile

**Expected Behaviour**
ability to save profile

**Related Issues**
none

**Additional Context**
none

<img width="532" alt="Screenshot 2023-11-13 at 2 19 20 PM" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/36866276/fbac4b15-6e40-4dba-8532-751616fecdb4">

**Comment by Jason-Morcos** [comment]
Did you make changes? If so, which fields did you change?

Generally, that button _is_ grayed out unless you actually make some changes to the connection settings

**Comment by aegrant00** [comment]
yes.  I added all those values.  there are none saved.  it's a new install.


Andy Grant
Castle Rock, Colorado
O: 303.834.7678
C: 303.808.7680

**Comment by Jason-Morcos** [comment]
Ahhh I see
You need to save it to your favorites first (the left option) if you want to be able to then make changes and save those changes later. There's no changes to save since you haven't saved the connection as a favorite

**Comment by aegrant00** [comment]
Thanks, I will!
