### ISSUE TITLE
can't connect using ssh

### ISSUE THREAD

**Issue by pstevemichel** [Sequel-Ace/Sequel-Ace#1927]
- Sequel Ace Version (including build number): Version 4.0.13 Build 20062
- Sequel Ace Source (App Store/GitHub/Homebrew): app store
- macOS Version: 14.1.1
- Processor Type (Intel/Apple): Apple
- MySQL Version:10.3.38-MariaDB
- macOS Localization:

**Steps To Reproduce**

Updated from teh store this morning (though haven't used it before on this Mac). When I try to connect to db with ssh, I get this:

OpenSSH_9.4p1, LibreSSL 3.3.6
Can't open user config file /Users/xxx/.ssh/: Operation not permitted
The SSH Tunnel has unexpectedly closed.

I've tried with several different Ubuntu servers. Seems the issue is local to the Mac.

**Comment by Jason-Morcos** [comment]
Can you go to Sequel Ace's preferences and reselect your SSH config and re-grant access to any keys you might be using?

This looks to me like macOS updated and you have to re-grant Sequel Ace permissions to your .ssh directory in order to be able to connect

**Comment by pstevemichel** [comment]
Thanks. That’s what I was thinking too, and I tried it to no avail. It has and had access to ./ssh/id_rsa. I also went to terminal and explicitly granted read access to everyone, just in case, but that didnt’ help. I also clicked the key icon next to SSH password, and selected id_rsa, but again no luck.

At the same time one appreciates all Apple’s efforts in security, they can drive you nuts.

I also fired up my old copy of Sequel Pro, and its working fine.

**Comment by Jason-Morcos** [comment]
The issue here looks to be your SSH config - any chance that is incorrectly selected (rather than the key) or expired sandbox access?
Or any chance you accidentally selected a key where the Sequel Ace's preferences is expecting a config?

If that still doesn't fix it, please provide screenshots of your Sequel Ace preferences (files and network tabs) and of the connection, covering up any private info before posting.

**Comment by pstevemichel** [comment]
Your suggestion did it.

In Network Preferences, SSH Config was empty. When I set it to Sequel Ace default, it worked. When I chose either id_rsa or id_dsa, it didn’t work and gave me other error messages. 

I’ve been using Sequel Ace since it was released, and I don’t think I’ve ever even looked at its Settings; it’s always just worked.

thanks.
