### ISSUE TITLE
Connecting to Teleport DB proxy causes a crash

### ISSUE THREAD

**Issue by Skyrail** [Sequel-Ace/Sequel-Ace#1931]
- Sequel Ace Version (including build number): 4.0.13 (20062)
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version: macOS 14.1.1 (23B81)
- Processor Type (Intel/Apple): M1
- MySQL Version: MySQL 8.2.0
- macOS Localization: English (UK)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Latest production release is newer than beta, and I've tried all production versions 4.0.8-4.0.13

**Description**
When attempting to connect to a [Teleport DB proxy connection](https://goteleport.com/docs/connect-your-client/gui-clients/#get-connection-information) Sequel Ace crashes every time.

The following are working as expected:
* Using 'Test connection' it returns a 'Connection succeeded' message.
* Connecting via MySQL CLI works with the same connection details
* Connecting to another local MySQL DB works as expected with similar details (localhost/127.0.0.1, same user name, no password, same port)
* Connecting to remote DBs works 

**Steps To Reproduce**
This requires a working [Teleport 'cluster'](https://goteleport.com/docs/) to connect to which I understand may not be feasible but I'm happy to work alongside a developer to assist testing/troubleshooting - I'd also be happy to set up a test cluster for a developer to connect via while troubleshooting if that would help.

1. Create a Teleport proxy connection to the DB `tsh proxy db --tunnel <db_name> --db-user <db_user> --port <local_port>`
2. Open Sequel Ace
3. Create a new TCP/IP connection with the following details:
* Name: Teleport Test
* Host: `127.0.0.1`
* Username: `<db_user>` (from the Teleport proxy command)
* Password: leave empty (Teleport performs the auth on our behalf)
* Port: `<local_port>` (from the Teleport proxy command)
4. Click 'Test connection'
5. Success message
6. Click 'Connect'
7. Sequel Ace Crashes

**Expected Behaviour**

I would expect Sequel Ace to connect to the DB proxy, and thus the DB succesfully without crashing.

**Related Issues**

There are a number of closed tickets related to crashing on connection but they appear to be general crashes rather than a specific connection type - they've also all been closed off.

**Additional Context**

I've attached a crash log from one of the crashes
[sequelace_4013_crash_log.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/13613553/sequelace_4013_crash_log.txt)

The Teleport proxy debug logs show the same on both the 'test connection' and 'connect' actions:

```
2023-12-08T11:49:07Z DEBU [LOCALPROX] Accepted downstream connection. alpnproxy/local_proxy.go:194
2023-12-08T11:49:07Z DEBU [LOCALPROX] checking local proxy database certs alpnproxy/local_proxy.go:380
2023-12-08T11:49:07Z DEBU [LOCALPROX] Using ping connection alpnproxy/local_proxy.go:240
2023-12-08T11:49:09Z DEBU [LOCALPROX] Accepted downstream connection. alpnproxy/local_proxy.go:194
2023-12-08T11:49:09Z DEBU [LOCALPROX] checking local proxy database certs alpnproxy/local_proxy.go:380
2023-12-08T11:49:09Z DEBU [LOCALPROX] Using ping connection alpnproxy/local_proxy.go:240
``` 

The following Teleport proxy command matches with the following Sequel Ace settings in a screenshot, and the Teleport logs show that Sequel Ace does connect and manages to run various commands on the DB before crashing.

**Teleport proxy command**
```
 tsh proxy db --tunnel teleport-test-db --db-user cs_aled --port 5306
```

**Sequel Ace connection settings**
![Screenshot 2023-12-08 at 12 03 44](https://github.com/Sequel-Ace/Sequel-Ace/assets/956617/5d16beeb-5a48-4fbc-b878-de3340de06d8)

**Teleport audit logs**
![Screenshot 2023-12-08 at 12 04 19](https://github.com/Sequel-Ace/Sequel-Ace/assets/956617/36e5e98c-7bf7-4faa-bd74-a849bc3384df)

I have connected using the MySQL CLI and ran all of the commands listed in the audit log with no issues so there are no unexpected response from the queries themselves.

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all Does anyone have a teleport setup they could play with reproducing this and proposing a fix?

**Comment by Jason-Morcos** [comment]
I see @Skyrail additionally has offered to spin up a test cluster if needed. Unfortunately, I am dealing with some personal things right now and don't have bandwidth to work on this through the end of the year and perhaps beyond. However, if someone is able to PR a fix I should be able to find a couple minutes to push a new release that patches this issue.

**Comment by robinkunde** [comment]
I can debug this weekend. You can email me connection details at robin.kunde@recoursive.com.

**Comment by Skyrail** [comment]
Morning both, thanks for the quick response and being willing to take a look at this. Frustratingly (or thankfully) I was creating the new setup for Robin to take a look at and I can't replicate the error.

While I didn't replicate the user/database names exactly the setup was close enough but with a fresh Teleport cluster and fresh RDS/Aurora instances.

So not to waste any more time on this I'll close it as can't reproduce - if I come across it again I'll make sure it can be reproduced and then will come to this issue.

Thanks again and hope you have a good weekend.

**Comment by dominykasn** [comment]
I am experiencing the same issue, any way I can send you crash logs or something?

**Comment by robinkunde** [comment]
@dominykasn Would you be able to set up an instance we can connect to in order to debug the issue?

**Comment by dominykasn** [comment]
Not really, my instances are all company provided therefore I cannot share such credentials.

**Comment by Skyrail** [comment]
I encountered this issue again yesterday, restarting the instance the Teleport agent was running on which fixed it.

While I've been unable to purposefully replicate it, as I can see it's happened again, and with others, I will see if I can replicate it in a test environment. If I do get a failed state I'm happy to give access to a developer and run through any setup required.

I'll also see if I can get any useful logs from the DB, Teleport or the instance. This may take some time, as I mentioned - there's no obvious way to repeat it.

**Comment by robinkunde** [comment]
@Skyrail Thank you

**Comment by brmb** [comment]
The issue is still there with the newest Sequel Ace:
```
Process:               Sequel Ace [9427]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
Identifier:            com.sequel-ace.sequel-ace
Version:               4.1.5 (20077)
App Item ID:           1518036000
App External ID:       869854366
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2024-11-18 10:21:18.5668 +0200
OS Version:            macOS 15.1 (24B83)
Report Version:        12
Anonymous UUID:        9D36A1CF-3C24-52F6-034B-C982D3B05BE3
```

<img width="200" alt="Screenshot 2024-11-26 at 10 49 46" src="https://github.com/user-attachments/assets/29a5883d-6b62-43b6-8c62-0d3ac53b0db4">

@robinkunde @Jason-Morcos, I could send you the crash log if it would help 🤷🏼‍♂️
