### ISSUE TITLE
The table editing doesn't support expression default values

### ISSUE THREAD

**Issue by tomatofrommars** [Sequel-Ace/Sequel-Ace#1935]
- Sequel Ace Version (including build number): Version 4.0.13 Build 20062
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 13.6.1 (22G313)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.31
- macOS Localization: Chinese

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**
A table with expression default values (for example `(JSON_OBJECT())`) cannot be inserted by the TABLE EDITOR.
```
CREATE TABLE IF NOT EXISTS `test__entity_with_json`
( 
`id` BIGINT NOT NULL PRIMARY KEY, 
`alias` JSON NULL DEFAULT (JSON_OBJECT())
) ;
```
![企业微信截图_7908c19a-b070-4b80-afaa-8574ecdde2ff](https://github.com/Sequel-Ace/Sequel-Ace/assets/16113120/a27698c5-6bd1-4fe4-b2ae-dd40fd8321be)

**Steps To Reproduce**
1. Create Table
```
CREATE TABLE IF NOT EXISTS `test__entity_with_json`
( 
`id` BIGINT NOT NULL PRIMARY KEY, 
`alias` JSON NULL DEFAULT (JSON_OBJECT())
) ;
```
2. Select the table and insert values via TABLE EDITOR
![企业微信截图_44976d5a-8c86-48b8-aea1-461513f5c191](https://github.com/Sequel-Ace/Sequel-Ace/assets/16113120/34f0631c-5ac6-4a72-975b-3090b2d337bb)
3. Hit enter and the error shows.

**Expected Behaviour**
![企业微信截图_2fbb3d77-696d-44c5-9774-cbf274d73787](https://github.com/Sequel-Ace/Sequel-Ace/assets/16113120/e07b78af-1941-4438-97f2-6c09df2cd98c)

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Funky funky, you're welcome to take a stab at fixing this issue and submitting a pull request! I'd be happy to review any PR that comes in.
