### ISSUE TITLE
Recommendations on UI layout

### ISSUE THREAD

**Issue by bash1350** [Sequel-Ace/Sequel-Ace#1938]
### Discussed in https://github.com/Sequel-Ace/Sequel-Ace/discussions/1937

<div type='discussions-op-text'>

<sup>Originally posted by **bash1350** December 21, 2023</sup>
Below is the interface layout of Sequel Pro. It has three compactly arranged areas on the left side of the software interface. It is very convenient to move the mouse from Area 1 and Area 2 to Area 3.
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/15766444/d9163f62-6f37-48de-b128-6102acf93ddd)

However, in Sequel Ace, as shown in the figure below, it is quite inconvenient to move the mouse from Area 1 to Area 2, especially when working on a large screen. I have two proposed solutions. 

- Solution 1: Move Area 2 to the left, adjacent to Area 1, to maintain consistency with Sequel Pro. 
- Solution 2: Move Area 1 to the right, adjacent to Area 2.

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/15766444/8335d1cb-7148-4c84-bec9-1a6b683e41e1)

</div>

**Comment by Jason-Morcos** [comment]
Duplicate https://github.com/Sequel-Ace/Sequel-Ace/issues/1294


Also, there are keyboard shortcuts to switch between the different panes if you're looking at being more efficient.

**Comment by bash1350** [comment]
Oh yeah, this is a very effective way.  Thanks~~

**Comment by bash1350** [comment]
I personally think that the most frequently used views should be rearranged in the following order:
View 1: Table Info
View 2: Table Content
View 3: Custom Query
It's most convenient for the left hand to access these three views with shortcuts. After triggering view 4, it's not as convenient for the fingers. I hope the shortcut keys can be rearranged to correspond to the order of the views.
The subsequent order could be:
View 4: Table Structure
View 5: Table Relations
View 6: Table Triggers

**Comment by bash1350** [comment]
> It's most convenient for the left hand to access these three views with shortcuts. After triggering view 4, it's not as convenient for the fingers. I hope the shortcut keys can be rearranged to correspond to the order of the views.

It may be related to my personal usage habits. Another solution could be to add a feature for customizing shortcut keys for views, allowing users to adjust them as they see fit. I hope this suggestion can be considered. Thank you.

**Comment by bash1350** [comment]
> Duplicate #1294
> 
> Also, there are keyboard shortcuts to switch between the different panes if you're looking at being more efficient.



Oh yeah!This is a very effective solution.



I personally think that the most frequently used views should be rearranged in the following order:
View 1: Table Info
View 2: Table Content
View 3: Custom Query
It's most convenient for the left hand to access these three views with shortcuts. After triggering view 4, it's not as convenient for the fingers. I hope the shortcut keys can be rearranged to correspond to the order of the views.
The subsequent order could be:
View 4: Table Structure
View 5: Table Relations
View 6: Table Triggers


It may be related to my personal usage habits. Another solution could be to add a feature for customizing shortcut keys for views, allowing users to adjust them as they see fit. I hope this suggestion can be considered. Thank you.

**Comment by Jason-Morcos** [comment]
Check out BetterTouchTool :) 
Customizing would be cool, but definitely a feature that is well handled by BTT today. And I think a global change today would confuse lots of existing users
