### ISSUE TITLE
Table List rendering 

### ISSUE THREAD

**Issue by riula** [Sequel-Ace/Sequel-Ace#194]
- Sequel Ace Version: 2.1.1
- macOS Version: 10.15.4
- MySQL Version: MariaDB 10.3.13

When connected to a database with a large number of tables, the table list will fail to render while scrolling. Clicking the now blank space where the list once existed triggers a render displaying the list again. The failure to render does not always occur.

**Steps To Reproduce**
1. Populate a database with a large number of tables.
2. Wait X amount of time and use other apps.
3. Return to Sequel Ace and scroll.

**Expected Behaviour**
Scrolling the list of tables always shows the database tables that are expected to appear in that components view port. 

**Is Issue Present in (https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Occurs in latest release

**Additional Context**

<img width="301" alt="Screen Shot 2020-07-07 at 5 53 14 PM" src="https://user-images.githubusercontent.com/558331/86957846-8603e700-c118-11ea-94a3-9bdb2458c9fe.png">

**Comment by Kaspik** [comment]
I'm worried (especially because `Wait X amount of time and use other apps.`) this has something to do with memory handling on MacOS and the fact we are not ARC compatible etc. (yet) Our memory handler is not great (if there is even some) and it will need some time to get it into better shape after all the years.

If anyone has any other idea what causes it, let me know, otherwise thiw will be put on hold once we get Sequel Ace in to better shape and modern codebase. 😞

**Comment by Kaspik** [comment]
This might be fixed with 3.0.0 release in about week or two. let us know if it's still an issue there!

**Comment by dlt-** [comment]
Sorry for late comment, but there is another thing to consider when getting a list of tables from MySQL/mariadb.

Looks like you use SHOW TABLE STATUS to get the list. On a database server with more than 100k tables it takes at least several minutes to complete.

If you change this to SHOW TABLES, it will get full list in less than 0,2 seconds. 

I am not sure if this is already changed in upcoming 3.0.0 ?

**Comment by Kaspik** [comment]
We use the `Comment` field from table to have information about the the table, which `SHOW TABLES` doesn't give us.

It's a question if we want to have better performance, but loose comments, or we want to keep it as it is.

**Comment by dlt-** [comment]
> We use the `Comment` field from table to have information about the the table, which `SHOW TABLES` doesn't give us.
> 
> It's a question if we want to have better performance, but loose comments, or we want to keep it as it is.

More detailed view is only needed for "Display comments in tables list". Please use SHOW TABLES (as it used to be earlier) if comments are not enabled. This will also help reducing load on sql server when browsing databases with a lot of tables.

**Comment by dlt-** [comment]
I just made comparison on a database with a lot of ARIA tables, when all tables were not already on server's table cache (ie. not used recently). for all non-cached tables server had to open it to read information. SHOW TABLES does not require opening.
   

show table status took more than 5 minutes (had to abort..).
show tables ->  about 0,2s :)

The difference was smaller (1,2 seconds compared to 0,18 seconds) after they were cached on the server side.
(I know this is a special use case, but it should be pretty easy to fix, as opening 10s of thousands of tables at once could cause performance issues on another threads too)

**Comment by Kaspik** [comment]
Hmm, yeah, I didn't know there is a settings for comment tables in list.

Tried switching, but it's unfortunately not that easy. The returned schema for that command is completely different, and I'm pretty sure it is different for different MySQL versions as well. I'll check what we can do to be sure that we don't break anything.

**Comment by dlt-** [comment]
It used to be SHOW TABLES earlier:

https://github.com/Sequel-Ace/Sequel-Ace/commit/068ff8392d5442dce56d8cad782d04d6f90a2558#diff-3de963dc7ff612caa0ef8628645044dd8d3c260ab08e35db9a9ab0a3e340099dR208

it returns just the list of table names without anything else. output has been similator for all mysql/mariadb versions. 

Should be much easier to parse than show table status with all additional information.

**Comment by Kaspik** [comment]
It used to be, it's not anymore. :))

it used to return array of table names, now it always (seems like it) returns dictionary. But the given dictionary doesn't have all the fields - has just one. Unfortunately - the one field is not `Name` or `NAME` or whatever - the key is always `Tables_in_%databaseName%` - which is kind of hard to.. directly decode. Two examles - database `intra` and one `heroku` database:
<img width="281" alt="Screen Shot 2020-11-20 at 13 39 20" src="https://user-images.githubusercontent.com/7204168/99801391-402f4480-2b36-11eb-9074-8c45323c93ea.png">
<img width="395" alt="Screen Shot 2020-11-20 at 13 40 57" src="https://user-images.githubusercontent.com/7204168/99801397-41607180-2b36-11eb-8ca3-5efd95032281.png">

In perfect world of Swift type-safety - we would be good, but the types here are just terrible. Anyways I opened a PR (https://github.com/Sequel-Ace/Sequel-Ace/pull/526) to have a workaround, we will try that. :)
