### ISSUE TITLE
View Structure shows incorrect collations

### ISSUE THREAD

**Issue by j-fulbright** [Sequel-Ace/Sequel-Ace#1946]
- Sequel Ace Version (including build number): 4.0.13
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 14.1.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.28
- macOS Localization: English?

**Description**
When creating views the structure, it shows that the collation is defaulted to either the connection collation or default MySQL 8 collation. 

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/10793868/fac8e1d4-0244-43b4-a6f4-542de28a2aef)

**Steps To Reproduce**
1. Import a View
2. View Structure
3. Run `show full columns from ViewName

**Expected Behaviour**
I would expect the structure to match what `show full columns` returns
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/10793868/0ed90dd2-d085-426a-aa43-e9dae5339f0c)

**Comment by Jason-Morcos** [comment]
Couple questions:

1. Is this only for Views? Or does the same bug exist for Tables?
2. Can you share the result of `SELECT * FROM INFORMATION_SCHEMA.COLLATIONS ORDER BY ID`

**Comment by Jason-Morcos** [comment]
Closing due to no response

**Comment by j-fulbright** [comment]
Sorry! I have way too many notifications to go thru, so just now trying to clear things up today. 

I originally noted this was something with MySQL 8, but on my local with 5.7, it is exhibiting the same issue.

This is only happening for Views, Tables appear to be correct. 

Just to refresh all of the above:

View collation under `Structure`
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/10793868/d7339ecc-c6dc-4b4e-933e-24a1e0fae5e8)

`show full columns` results
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/10793868/9c8945d9-9cf4-47ae-8d50-4a16273fee9d)

Collation of server/client/connection
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/10793868/3afc2ee2-dfa0-4aee-8c37-d97e3a6af21d)

List of collations from your above command
[mysql-collations.csv](https://github.com/Sequel-Ace/Sequel-Ace/files/14223706/mysql-collations.csv)
