### ISSUE TITLE
Freezing on Launch

### ISSUE THREAD

**Issue by tombajzek** [Sequel-Ace/Sequel-Ace#1952]
- Sequel Ace Version (including build number):4.0.13
- Sequel Ace Source (App Store/GitHub/Homebrew):App Store
- macOS Version: 13.6.3
- Processor Type (Intel/Apple):Apple M1
- MySQL Version: Not relevant
- macOS Localization:US English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
When I launch the app, sometimes it comes up frozen, and I have to Force quit the app. Once this happens, it continues 100% of the time until I reinstall the app. Sometimes, I've also had to delete the Library files that support the app. I've found strong stuff in those directories in some cases.

**Steps To Reproduce**
1. Launch the app.
2.

**Expected Behaviour**
The app should behave normally.

**Related Issues**

**Additional Context**

[SequelAceCrash.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/13942231/SequelAceCrash.txt)

**Comment by tombajzek** [comment]
On an older, Intel Mac, release 4.0.7 does not have this problem.

**Comment by tombajzek** [comment]
I'm running 4.0.13 Build 20062.

**Comment by Jason-Morcos** [comment]
I'm not able to reproduce this issue locally, but if you'd like to take a stab at compiling locally and trying to make a fix I'd be happy to review any PR aimed at addressing this issue!
Be sure you're not doing anything funky with syncing library files between devices/on removable media. This to me screams funky filesystem issues rather than Sequel Ace bugs

**Comment by tombajzek** [comment]
Another set of these. See the crash dump here attached.
[SequelAceCrashDump.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/14016640/SequelAceCrashDump.txt)

**Comment by Jason-Morcos** [comment]
Hey Tom,

I'm definitely sorry to hear you're having issues. Sequel Ace is a hobby project for those of us that work on it. Life is a busy thing, and unfortunately none of us can do all the work we'd like to. That being said, I know I personally am unlikely to have any time to dig into this issue; I generally focus my efforts on bugs and requests that impact a large portion of the community or myself, personally.

That being said, if you or someone else in the community would like to take a stab at fixing the issue, I'd be more than happy to review any PR to address a issue and provide timely feedback.

**Comment by tiptronic85** [comment]
I have the same problem when i start my mac from standby, and it tries to connect to each tab, but they need tunnels or i'm not connected to the vpn.
I think the solutions would be to not force auto-connection (i don't have the option selected), but it tries the same to connect to each tab even if i want to connect only to the active tab.

**Comment by tombajzek** [comment]
My problem has nothing to do with auto-starting the app the Mac. It doesn't even necessarily follow a startup. So far, I've not found anything I can correlate this with. I can say that it does not seem to happen with my Intel MacBook Pro, which Is from about 2015, roughly. So, when it happens now, I usually just switch to the older laptop to do that work. This is very inconvenient, but less so than interrupting my work to fight a losing battle with Sequel Ace.

One thing I noticed that puzzles me is that the support files for Sequel Ace are not in /Library/... but rather in ~/Library, and that the directories and files I find there are not what I would have expected. There is a directory ~/Library/Containers/Sequel Ace/Data that has aliases for all of my top-level directories. In that is one directory that is not an alias - Library - that contains what looks pretty much like a top-level system directory, minus the com.apple... files that you would expect to find there. I don't know if that's supposed to be normal or not. Inside this there is a Sequel Ace directory with zbuncles, Data, and Themes. That seems unnatural to me.

**Comment by Kaspik** [comment]
Can you both try updating to macOS 14?

**Comment by spartanatreyu** [comment]
Potential fix!

Sequel ace randomly stopped working for me after a macOS update. The application would stop responding on startup. Replacing the application with the newest version (v 4.0.17) did not help.

After inspecting the application in Activity Monitor I could see the following ports and files loaded:

```txt
/Users/production/Library/Containers/com.sequel-ace.sequel-ace/Data
/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
/Applications/Sequel Ace.app/Contents/Frameworks/QueryKit.framework/Versions/A/QueryKit
/Applications/Sequel Ace.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/A/ShortcutRecorder
/Library/Preferences/Logging/.plist-cache.1UhLWRYz
/System/Library/CoreServices/SystemVersion.bundle/English.lproj/SystemVersion.strings
/private/var/db/timezone/tz/2024a.1.0/icutz/icutz44l.dat
/private/var/db/analyticsd/events.allowlist
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/InfoPlist.loctable
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/InputManager.loctable
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/DictationManager.loctable
/usr/lib/libobjc-trampolines.dylib
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Placeholders.loctable
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/MenuCommands.loctable
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/InfoPlist.loctable
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/SPMySQL
/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h
/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h.04
/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h.03
/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h.01
/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h.02
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/libssl.1.1.dylib
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLight.car
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/libcrypto.1.1.dylib
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLight.car
/usr/share/icu/icudt74l.dat
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car
/Applications/Sequel Ace.app/Contents/Resources/Fonts/Menlo.ttc
/System/Library/Fonts/SFNS.ttf
/System/Library/Fonts/HelveticaNeue.ttc
/System/Library/PrivateFrameworks/SFSymbols.framework/Versions/A/Resources/CoreGlyphs.bundle/Contents/Resources/Assets.car
/System/Library/Fonts/Helvetica.ttc
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAqua.car
/dev/null
/dev/null
/dev/null
```

I force quit the application, opened Finder, clicked Go -> Go To Folder (⇧⌘G), pasted in part of the top line of the list above (`/Users/production/Library/Containers/`) and hit Enter, then I deleted the contents of the `com.sequel-ace.sequel-ace/` folder.

The application started working again.

It seems there is some way for the contents (or access) of that directory to become borked to the point that the application becomes unresponsive when starting.
