### ISSUE TITLE
Please make a function to choose a language

### ISSUE THREAD

**Issue by happylie** [Sequel-Ace/Sequel-Ace#1953]
I'm using MacOS. 
The keyboard settings set on your Mac automatically select the application language depending on the input source. 

If you use multiple input sources, you are selected as the last language. 

There is no separate language selection in the current Sequel Ace configuration. 
I would appreciate it if you could add these parts.

I'm always using that application well. 
Thank you for developing it.

**Comment by samuelbradshaw** [comment]
Related: https://github.com/Sequel-Ace/Sequel-Ace/issues/1412, https://github.com/Sequel-Ace/Sequel-Ace/issues/1151

**Comment by happylie** [comment]
Thank you for the information.
I knew how to do it, but I left it because I thought it would be nice to add a function that the application handles directly.
