### ISSUE TITLE
Not escaping singel quotes (')

### ISSUE THREAD

**Issue by toddpage** [Sequel-Ace/Sequel-Ace#1956]
- Sequel Ace Version (including build number): Version 4.0.13 (Build 20062)
- Sequel Ace Source (App Store/GitHub/Homebrew): N/A
- macOS Version: 13.5 (22G74)
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 
- macOS Localization: Tried on RHEL8 and Debian 11 

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1. Go to export data
2. Error on importing data
3. View SQL file and single quotes are not escaped, Example:

INSERT INTO `thisTable` (`word`, `language`, `active`)
VALUES
	('any','en',0),
	('are','en',0),
	('aren't','en',0), <=  did not escape
	....

**Expected Behaviour**

INSERT INTO `thisTable` (`word`, `language`, `active`)
VALUES
	('any','en',0),
	('are','en',0),
	('aren\'t','en',0), <=  should have escaped
	....

**Related Issues**

**Additional Context**

**Comment by vuon9** [comment]
![image](https://github.com/user-attachments/assets/93c66197-5718-4d03-9937-03a4d5afb078)

I just tried and got it as escaped when using **Export...** to SQL 🤔  
Could you pls share more details if it could still happen in the last build? @toddpage
