### ISSUE TITLE
Please put a business model behind this

### ISSUE THREAD

**Issue by JackEllis** [Sequel-Ace/Sequel-Ace#196]
Congratulations on the resurrection.

Please find a way to sustain this project financially. One-off donations won't work. Please take a look here: https://calebporzio.com/i-just-hit-dollar-100000yr-on-github-sponsors-heres-how-i-did-it

And let me know how I can send you money.

**Comment by Kaspik** [comment]
Duplicated of https://github.com/Sequel-Ace/Sequel-Ace/issues/60

We appreciate this, but it's not the right time yet! :)

**Comment by JackEllis** [comment]
Thanks for the reply @Kaspik. I’ll stick with Sequel Pro for now then but I look forward to when you’ve found a way to make this project sustainable 🔥
