### ISSUE TITLE
Invalid configuration written to SSH config file after a successful connection

### ISSUE THREAD

**Issue by Jiia** [Sequel-Ace/Sequel-Ace#1961]
- Sequel Ace Version (including build number): 4.0.13 build 20062
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew & App Store
- macOS Version: 13.5
- Processor Type (Intel/Apple): Intel

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Not going to check

**Description**
When connecting to a database using default SSH agent Sequel Ace seems to write a new line to my `~/.ssh/config` which breaks any subsequent use of the config file. The first connections succeeds, but subsequent connections fail because 

```
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/u/.ssh/config
debug1: /Users/u/.ssh/config line 1: Applying options for x.x.com
debug1: /Users/u/.ssh/config line 11: Applying options for *.x.com
debug1: /Users/u/.ssh/config line 32: Applying options for *
/Users/u/.ssh/config: line 41: Bad configuration option: x.x.com
/Users/u/.ssh/config: terminating, 1 bad configuration options
The SSH Tunnel has unexpectedly closed.
```

When I look at `~/.ssh/config` I see that one new line has been added to the end of the file. Here's what the end of the file looks like afterwards.

```
Host *
  ConnectTimeout 10
  ExitOnForwardFailure yes
x.x.com ssh-ed25519 [long string]
```

The last line here is the new one that's appended.

**Steps To Reproduce**
1. Connect to a new database using SSH with configuration loaded from ~/.ssh/config
2. Connect to the database again

**Expected Behaviour**
Both connections work as expected

**Related Issues**

**Additional Context**

I tried this with both AppStore and Homebrew versions with the same issue. The permissions of the config file are 600.

Before connecting to the database, I'm promted that `the authenticity of hots 'x.x.com' can't be established. This key is not known by any other names.` This is expected, so I press 'yes'.

**Comment by Jason-Morcos** [comment]
I think you've selected your ssh config as your known hosts file.

Take a look in Sequel Ace's settings and make sure the known hosts file isn't set to your ssh config.
