### ISSUE TITLE
Changing column name on UUID type (MariaDB) fails

### ISSUE THREAD

**Issue by gronke** [Sequel-Ace/Sequel-Ace#1966]
- Sequel Ace Version (including build number): `Version 4.0.13, Build 20062`
- Sequel Ace Source (App Store/GitHub/Homebrew): `Homebrew`
- macOS Version: `14.3.1` (Sonoma)
- Processor Type (Intel/Apple): `Apple`
- MySQL Version: `11.2.2-MariaDB-1:11.2.2+maria~ubu2204-log`
- macOS Localization: `Germany`, `US-English`

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Unconfirmed.

**Description**

When renaming a UUID column from the Structure view, the following error occurs:

```sql
An error occurred when trying to change the field 'uuid' via

ALTER TABLE `users` CHANGE `uuid_before` `uuid_after` UUID
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
NULL
DEFAULT NULL

MySQL said: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci
NULL
DEFAULT NULL' at line 2
```

Manually reproducing the query confirms the error. Without `CHARSET` and `COLLATE`, the change succeeds though:

```sql
ALTER TABLE `users` CHANGE `uuid_before` `uuid_after` UUID NULL DEFAULT NULL
```

**Steps To Reproduce**

1. Connect to a MariaDB database
2. `CREATE TABLE users (uuid_before UUID);`
3. Open Sequel-Ace Structure view of `users` table
4. Change `uuid_before` column name to `uuid_after`

**Expected Behaviour**

The column is renamed without error message without modification of the column type or properties.

**Comment by Jason-Morcos** [comment]
This feels like we're probably just missing a little guard and treating UUIDs like string (char) fields somewhere in the code.
Not sure where exactly that might be though - @Sequel-Ace/all this feels like a small one if someone knows where to make this change?

**Comment by robinkunde** [comment]
Probably here https://github.com/Sequel-Ace/Sequel-Ace/blob/a5be31baa3a8e96f880de15cb3db8e2b38eb4a76/Source/Controllers/MainViewControllers/TableStructure/SPTableStructure.m#L888

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

Thank you, @gduh!
