### ISSUE TITLE
Color code tables

### ISSUE THREAD

**Issue by jdrucey** [Sequel-Ace/Sequel-Ace#1968]
Would be really handy to be able to color code tables within a database (in the side bar/list), in much the same way you can color code connections.

In my use case, I'm deprecating some tables in a new piece of development, I can't change the tables name as it is in use, but it would be great to differentiate it with color so I know it will soon be removed. This would help me declutter the list by being able to visually skip past these tables as I scan down the list.

**Comment by Kaspik** [comment]
Honestly I don't think this will be on the roadmap ever, so I feel like closing this. We would need to be storing a tons of data locally, per connection / DB  per table, and if that table would be removed, we would need self-cleaning and other stuff. That's probably super low on priorities for years even if we would get few folks working in a regular basis. Sorry!
