### ISSUE TITLE
document how to import favorite db from sequel pro

### ISSUE THREAD

**Issue by morgunder** [Sequel-Ace/Sequel-Ace#197]
i see in other issues that the getting started documentation explains how to import existing sequel pro favorites (minus passwords).  however i did not see that in the place linked to.  can you clearly explain how to do this so all i have to do is patch in the passwords?

thx

**Comment by p3yman** [comment]
> i see in other issues that the getting started documentation explains how to import existing sequel pro favorites (minus passwords). however i did not see that in the place linked to. can you clearly explain how to do this so all i have to do is patch in the passwords?
> 
> thx

Hi @morgunder, I'm just mentioning it if it helps you. You can find it in this article:
https://medium.com/@harrybailey/migration-from-sequel-pro-to-sequel-ace-c6a579399c90

**Comment by cafferata** [comment]
@morgunder @Jason-Morcos what do you think is a logical explanation?

The basis is in fact quite simple:
1. Screenshot of Sequel Pro export window
1. Screenshot of Sequel Ace import window
1. Migration completed.

See also
1. https://github.com/Sequel-Ace/Sequel-Ace/issues/155#issuecomment-653173810 
1. https://github.com/Sequel-Ace/Sequel-Ace/issues/155#issuecomment-653641228

**Comment by Jason-Morcos** [comment]
I think making a documentation page which just has the information available all in one place would be helpful for users transitioning over. We could link to the documentation page in our readme and App Store description.
Documentation website is composed of /docs folder on repo (GitHub pages) so should be pretty easy to add another page

**Comment by Jason-Morcos** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/issues/155#issuecomment-658014010
This could also be useful to include in our documentation!

**Comment by cafferata** [comment]
@Jason-Morcos Is it perhaps an idea to include @bartdecorte's work as a bash script in the repository and refer to it from the documentation? Obviously with the same assumptions as @bartdecorte has mentioned.

**Comment by Jason-Morcos** [comment]
@cafferata No, I would rather keep it entirely in the documentation. Migration scripts like these could not be distributed with the app on the App Store - Apple would absolutely reject this.

**Comment by bartdecorte** [comment]
@cafferata I would recommend some further testing in that case. Like I said, this was written pretty quickly to serve my needs. I'm not aware of how often Apple makes changes to that `security` command. I ran this on Catalina. Additionally, I'm using the `-T` flag with `security add-generic-password` to grant Sequel Ace permission to read the new key. However, connecting for the first time still requires the user to grant permission explicitly. This I did not expect, but I took my peace with it. As that option exists, I think there must be a way to achieve the same without additional user interaction. I guess what I'm saying here is that there may be some room for improvement. In any case, I would always suggest users to back up their keychains.

**Comment by cafferata** [comment]
Totally agree! We ourselves have already migrated, but I think it makes sense for many of us to look further. Personally I thought it was an interesting side track from the documentation point of view.

**Comment by Jason-Morcos** [comment]
Please take a look, all!
https://github.com/Sequel-Ace/Sequel-Ace/pull/226

**Comment by Muffinman** [comment]
For anyone else having the same issue as me... I was not able to import my favourites from Sequel Pro when using a symlink. See #252.

I had to switch to a hard link to make it work, presumably some limitation of the sandboxing?
