### ISSUE TITLE
Confirmation Popup Before Exiting

### ISSUE THREAD

**Issue by rawkon** [Sequel-Ace/Sequel-Ace#1971]
Please add a confirmation (yes/no) popup before quitting the application.

Sometimes I accidentally press [command + Q] or the window close button and lost all the session.

**Comment by samuelbradshaw** [comment]
Would this meet your need?
https://medium.com/macoclock/how-to-get-confirmation-alert-before-quitting-safari-on-macos-f76aef37477e

**Comment by rawkon** [comment]
> Would this meet your need? https://medium.com/macoclock/how-to-get-confirmation-alert-before-quitting-safari-on-macos-f76aef37477e

Is this some kind of joke?! Can't you read what's my need?

There is no logical point of suggesting users tons of headache instead of implementing a simple solution.

**Comment by Jason-Morcos** [comment]
Hey @rawkon - this is an open source project that people work on, outside of work, for no pay. I think @samuelbradshaw's suggestion was a great possible workaround for your need. If you're unhappy with it, this is an open source project - you're able to submit a code change that implements this functionality (probably as an optional setting) - I know I'd be happy to review such a code change and include it.

**Comment by rawkon** [comment]
I am aware that you work on a voluntary basis and I am truly grateful for that. If I had Objective-C experience, I would like to show my support as much as I can.

However, such critically important details directly affect usage.

Although you are open to feature requests, it does not seem reasonable to me that you suggest hacking the operating system instead of intervening on a software basis.
