### ISSUE TITLE
Is it possible to open Sequel Ace from Terminal into an ssh connection?

### ISSUE THREAD

**Issue by john-kelly** [Sequel-Ace/Sequel-Ace#1973]
Is it possible to open Sequel Ace from Terminal into an ssh connection?

I found this: https://github.com/Sequel-Ace/Sequel-Ace/issues/189 that describes something like this:

```
open "mysql://root:root@127.0.0.1:3306/db" -a "Sequel Ace"
```

however, i was unable to get this to work with an ssh connection.

Thank you!

**Comment by Jason-Morcos** [comment]
Looks like this was contributed as a feature and should be available in the app! https://github.com/Sequel-Ace/Sequel-Ace/issues/108#issuecomment-1426619066

**Comment by john-kelly** [comment]
@Jason-Morcos amazing! thank you so much. will give it a try.
