### ISSUE TITLE
当我尝试复制一个大表的聚合结果的部分内容的时候, 双击变成修改, 然后导致工具卡死

### ISSUE THREAD

**Issue by xuxujie** [Sequel-Ace/Sequel-Ace#1980]
select distinct tags from order where aid=1430 and pay_order_id like '400%';
当我尝试获取tags的部分内容的时候, 对内容进行了双击, 结果卡住了.
我希望是当选择的列没有主键或者是聚合结果的时候, 不可以编辑.

**Comment by Jason-Morcos** [comment]
Hi - please resubmit this issue in English if possible. Unfortunately, as the majority of our team are English speaking, it's difficult for us to support tickets in other languages.

Thank you
