### ISSUE TITLE
change database 

### ISSUE THREAD

**Issue by aohanhongzhi** [Sequel-Ace/Sequel-Ace#1987]
![Snipaste_2024-04-02_09-29-52](https://github.com/Sequel-Ace/Sequel-Ace/assets/37319319/d12818b3-2fbf-44c6-910e-80f88591f0d3)

**Comment by mario-fehr** [comment]
@aohanhongzhi open a new connection tab/window in the file menü or close the existing window

**Comment by aohanhongzhi** [comment]
@mario-fehr 

I can not find another database 

<img width="542" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/37319319/6fa9beff-ad5b-4266-ac76-cb6e00ee3681">

I need close the windows and click launcher again to open the below UI to change database 

<img width="1546" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/37319319/8660407e-6261-435c-a81e-62894cced521">

**Comment by mario-fehr** [comment]
@aohanhongzhi you are close use one of this
![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/14167832/465bbaef-e030-4ca3-8a1e-698d71d3eb49)
