### ISSUE TITLE
Feature Request: Support MySQL < 5.6

### ISSUE THREAD

**Issue by robertoschwald** [Sequel-Ace/Sequel-Ace#199]
With the update of mysqllib to a more recent version, it is not possible to connect to legacy MySQL 5.1 databases anymore.
bad_handshake error occurs.
This works in Sequel Pro, as it uses the MySQL 5.5 mysqllib.

Maybe there is a possibility to add connection support for old MySQL dbs into Sequel Ace?

**Comment by Jason-Morcos** [comment]
Yup, when upgrading to support MySQL 8 we dropped support for MySQL < 5.6. Legacy databases are not supported by Sequel Ace (similarly not supported by MySQL Workbench). I can leave this issue open, but I think it's fairly unlikely support for legacy databases is added back in.

**Comment by pstevemichel** [comment]
I'm another that would like to access the older versions of MySQL. I have a large legacy database running in 5.5.62. I guess I'll keep a copy of Sequel Pro around for the time being.
