### ISSUE TITLE
remember the choice database

### ISSUE THREAD

**Issue by aohanhongzhi** [Sequel-Ace/Sequel-Ace#1994]
<img width="536" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/37319319/7eb24478-a6d9-44ca-a6cb-76e4c9aedd17">

**Comment by Jason-Morcos** [comment]
You can choose the default db to connect to for a favorite by inputting the database name on the main connection screen.

**Comment by aohanhongzhi** [comment]
@Jason-Morcos  thanks for your reply
