### ISSUE TITLE
Sequel Ace cannot be opened because of a problem.

### ISSUE THREAD

**Issue by billynoah** [Sequel-Ace/Sequel-Ace#1995]
- Sequel Ace Version (including build number): 4.0.15
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 10.14.6
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.36
- macOS Localization: ???

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes.

**Description**
Opening Sequel Ace gets me a popup that reads:
> **Sequel Ace cannot be opened because of a problem.**
> Check with the developer to make sure Sequel Ace works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.
> Click Report to see more detailed information and send a report to Apple.

**Steps To Reproduce**
1. Download latest from GitHub
2. Try to open the App

**Expected Behaviour**

Both App Store and GitHub home project page says:
> macOS: >= 10.13 *
> Processor: Intel & Apple Silicon

Based on this, my OS version is supported.

**Additional Context**

[crash.log](https://github.com/Sequel-Ace/Sequel-Ace/files/14998652/crash.log)

**Comment by Kaspik** [comment]
Before we dive in, wanna make sure you have Swift Standard Library installed? https://github.com/Sequel-Ace/Sequel-Ace?tab=readme-ov-file#compatibility

**Comment by billynoah** [comment]
@Kaspik - no I don't.  I just upgraded from Sequel Ace 4.0.13 so I'm assuming this is a new requirement.  I'll get it installed.  Thanks for the quick response!

 This seems like a significant change in requirements for a micro version. Perhaps this requirement could be mentioned in the Release Notes or "What's Changed" section in releases? I typically don't review requirements when updating a micro-version, but I do read the release notes. Just a thought...

**Comment by Kaspik** [comment]
I have no idea if this is it, but we used newer version of Xcode and you never know what Apple changed for older / legacy versions of macOS... this was just my first hint to try. If that will be it we will surely do something about it.

**Comment by billynoah** [comment]
Odd problem - The Swift download page says "These libraries are included in the OS starting with macOS Mojave 10.14.4." and I am running 10.14.6 but it is missing.  When I try to install it says "This version of maxOS is too new" and won't allow me to install.

I'm going to try and install Xcode_11.3.1 which I'm guessing might contain the necessary library.  What a pain in the neck. Is there any way to build Sequel Ace that eliminates this requirement?

**Comment by billynoah** [comment]
I downloaded Xcode but it just runs as an application.  I have no idea how to get the SwiftUI library installed.

**Comment by Kaspik** [comment]
Then it's not that, as it says you already have it cause you have newer macOS version.

@Jason-Morcos New Xcode problems?

**Comment by Kaspik** [comment]
I will check if we need to include it, but we didn't add anything new, would have to be some dependency we updated.

**Comment by Jason-Morcos** [comment]
Definitely not sure what's going on here. So far this is the only report I've heard of this issue and we build both 4.0.14 and 4.0.15 with the most recent Xcode release so it seems likely that we would have heard other reports by now if this was a broader issue. Definitely could be a dependency change in the latest release however.
@billynoah are you seeing the same behavior with 4.0.14? Can you confirm that downgrading to 4.0.13 does fix your issues faced?

**Comment by billynoah** [comment]
@Jason-Morcos - Yes I am seeing it with 4.0.14.  And yes, downgrading to 4.0.13 resolves the issue. It could be an anomaly with my particular install but unfortunately I haven't found any way to get that library installed.  I wonder if somewhere along the way it was somehow removed or didn't get installed for some reason during a botched subversion upgrade. I tried downloading Xcode 11.3.1 which is the newest version supported for my OS but it just unzips as an App and I don't see any way to install the SwiftUI framework.

**Comment by samuelbradshaw** [comment]
SwiftUI is different from Swift. I don't think Sequel Ace is using SwiftUI, is it?

**Comment by samuelbradshaw** [comment]
Not sure if it's helpful, but I found this:
https://forums.developer.apple.com/forums/thread/750024

**Comment by Jason-Morcos** [comment]
Please try this beta, @billynoah, and let us know if it solves the issue! https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F4.0.16-20066

**Comment by billynoah** [comment]
> Please try this beta, @billynoah, and let us know if it solves the issue! https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F4.0.16-20066

I tried it just now and it works!  Thank you so much for your contributions to this great application and for the quick patch.

**Comment by Jason-Morcos** [comment]
Thank you! All thanks to @samuelbradshaw's research!
