### ISSUE TITLE
MAS CLI install broken

### ISSUE THREAD

**Issue by lacymorrow** [Sequel-Ace/Sequel-Ace#2004]
>Redownload Unavailable with This Apple ID

>This redownload is not available for this Apple ID either because it was bought by a different user or the item was refunded or cancelled.

<img width="274" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/1311301/f225213a-dfc1-4ddb-acfb-03d2a6476f7b">

<img width="562" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/1311301/3f68bea8-bb3b-45df-adc4-96f3b28d67b4">

**Comment by Jason-Morcos** [comment]
Hi - this doesn't sound like an issue with Sequel Ace but rather with the mas cli (or with an issue with you being logged in under a mismatched account). Please open this issue with the mas team. https://github.com/mas-cli/mas

**Comment by Jason-Morcos** [comment]
This part of the mas readme may also be useful: https://github.com/mas-cli/mas?tab=readme-ov-file#-when-something-doesnt-work
