### ISSUE TITLE
It would be better if the interface could look a little nicer.

### ISSUE THREAD

**Issue by tlerbao** [Sequel-Ace/Sequel-Ace#2005]
<img width="772" alt="CleanShot 2024-04-24 at 15 52 20@2x" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/20442232/dc901f18-9112-42da-a7ac-7c20aef47655">

As shown in the figure, this position displays database version, name, etc. ((MySQL 5.7.28-log) MySQL/test_yoshop2_db/yoshop_store_), which doesn't look very good. I hope to improve this area.

**Comment by Kaspik** [comment]
Enable "Show tab bar" and there will be shorter info / more related to the database / table.

Right now there is no other plan on changing how this works, UI is always a nice improvement, but we have tons of more important work to do unfortunately...

**Comment by tlerbao** [comment]
> Enable "Show tab bar" and there will be shorter info / more related to the database / table.
> 
> Right now there is no other plan on changing how this works, UI is always a nice improvement, but we have tons of more important work to do unfortunately...

对不起，我没有找到设置 "Show tab bar" 的位置？
