### ISSUE TITLE
FIDO 2FA for SSH Tunnels

### ISSUE THREAD

**Issue by irvinechris** [Sequel-Ace/Sequel-Ace#2008]
We are generally hardening access to hosts by turning off various authentication methods. Furthermore, we would like to restrict access to only ssh connections using 2FA security key configurations.

Apple doesn't yet, AFAIK, support FIDO 2FA in their MacOS SSH client. But, the process to install a the fully capable client via homebrew is easy to do today. Then instead of the default client, you just use /opt/homebrew/opt/openssh/bin/ssh

Some other Mac OS apps allow using an alternate ssh client, and to my delight, some of them already appear to work with my Yubikey SSH connections. However, when I try to use my Homebrew SSH client in Sequel Ace, I get "NSInvalidArgumentException: launch path not accessible". And even if that was fixed, I expect there might still be issues with the human prompt that would be appropriate.

Specifically, I'd like to restrict my MySQL/MariaDB host to only support PubkeyAuthentication and only the sk-ssh-ed25519@openssh.com key type. Sequel Ace should be able to use my Homebrew ssh client, until Apple improves theirs. Then ideally prompt for a human tap on the blinking security key, similar to how ssh does it in the terminal, "Confirm user presence for key ED25519-SK SHA256:...".

**Comment by Jason-Morcos** [comment]
This is one of those things that's blocked by the sandbox... I'm going to close this in lieu of #346. If we solve #346, that should solve this issue too
