### ISSUE TITLE
JSON format Error

### ISSUE THREAD

**Issue by fuguangli** [Sequel-Ace/Sequel-Ace#2019]
- Sequel Ace Version (including build number):Version 4.0.17 Build 20067
- Sequel Ace Source (App Store/GitHub/Homebrew):App Store
- macOS Version:macOS Sonoma 14.4.1
- Processor Type (Intel/Apple):Apple
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
When I double-click a cell whose content is a json string, and then click the “JSON” button below in the popup window, the decimal formatting error in the formatted content, e.g.:{“levelRatio”:0.30} will be formatted as {“levelRatio” : 0.299999999999999999999999999999999}; Sincerely hope the Maintainers can solve this bug as soon as possible, thank you very much, thank you for your hard work!
<img width="344" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/29936353/6aa4d759-0697-4e20-9458-07eae7a96b27">
<img width="747" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/29936353/7ddb0045-5ea7-47ff-bf79-a48fd6b66bb6">
<img width="747" alt="image" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/29936353/5439581c-3b8c-4808-a6c7-7580215bb27d">

**Steps To Reproduce**
1.double-click a cell whose content is a json string
2.click the “JSON” button below in the popup window

**Expected Behaviour**

Formatting decimals correctly

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Can you please share what version of MySQL you're using and share the create table SQL for this example table from the screenshots?

**Comment by vuon9** [comment]
https://forums.developer.apple.com/forums/thread/110414 
Seems like an issue with built-in library NSJSONSerialization? 🤔
