### ISSUE TITLE
MySQL提示：client charset is not supported

### ISSUE THREAD

**Issue by bytezyp** [Sequel-Ace/Sequel-Ace#2022]
- Sequel Ace Version (including build number):4.0.17
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version:12.0.1 
- Processor Type (Intel/Apple):.4 GHz 四核Intel Core i5
- MySQL Version:5.7.24
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1. tcp/ip client type
2.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Please fill out the full issue template when creating issues including particularly the version of Sequel Ace being used, version of MySQL/MariaDB, and any logs that may be applicable. In the case of a feature request, please be sure to clearly explain what you're trying to accomplish (the root issue) and if any workarounds currently exist.

We try to be as helpful as possible, but the volume of issues reported limits us to only have time to dig into those that include all the details needed. I encourage you to open a new issue with all the details provided.
