### ISSUE TITLE
Filter for multiple tables

### ISSUE THREAD

**Issue by Morgy93** [Sequel-Ace/Sequel-Ace#2025]
Hello,

I'd love to be able to filter for multiple table names via the input field:

![image](https://github.com/Sequel-Ace/Sequel-Ace/assets/7961978/71e81972-2e1d-457a-bf7f-647449abe09a)

Something like `table_;elbat_` or `table_,elbat_` whatever works best.

So that I can see both `table_*` and `elbat_*` results at the same time.

**Comment by fefed22** [comment]
Hello,

Sorry but i think it's already possible with a pipe !

So you can write : `table_|elbat_`

Best regards

**Comment by samuelbradshaw** [comment]
I'm guessing it's using regex behind the scenes?
