### ISSUE TITLE
Multiple tabs

### ISSUE THREAD

**Issue by sgyaa** [Sequel-Ace/Sequel-Ace#2028]
- Sequel Ace Version (4.0.17, build: 20067):
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version: 11.7.10
- Processor Type (Intel):
- MySQL Version: 5.7.39
- macOS Localization: en

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
When I open a new tab, it works fine. But, if I open one more tab in the same window, the app does not respond anymore.

**Steps To Reproduce**
1. Open a tab using a same connection (an other table for example using right click on it)
2. Open a new tab as by step 1

**Expected Behaviour**
App opens several tabs in one window (no more, than 5 tabs should be enough)

**Related Issues**

**Additional Context**

unfortunately no detailed crash log file available, only one line in the system.log
Jun 15 13:01:04 MacPro-A-346GHz-2x6cores-5 com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.sequel-ace.sequel-ace.84152892.84152899(501)> [510]

**Comment by Jason-Morcos** [comment]
Can't reproduce this one - I've got 5 tabs open locally and having no issues toggling between them and interacting normally. Did it persist after restarting your computer?

**Comment by sgyaa** [comment]
Hi Jason!

Unfortunately restart does not help.
I checked it on Monterey and Sonoma and it works well on these OSes.

On Sonoma there is no significant speed issues, but on Monterey with every new tab gets slower and slower.
Under Big Sur, the 2nd tab takes about 20 sec, the 3rd tab takes forever to appear, and then app is not responding.

Never mind this issue. Switching to Monterey is the solution.

Regards,

Surmann Gyula
art director

DrawJob Advertising Agency Ltd.
Egres str. 32-40.
2000 Szentendre, Hungary
phone: +36 20 530 6401
e-mail: ***@***.*** ***@***.***>

design · typography · prepress · website · mobile app

**Comment by sgyaa** [comment]
Hi Jason, now it happened again and I have some logs as well.
Hope, it helps.

**Sample process:**
`cwd
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data
txt
/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
txt
/Applications/Sequel Ace.app/Contents/Frameworks/QueryKit.framework/Versions/A/QueryKit
txt
/Applications/Sequel Ace.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/A/ShortcutRecorder
txt
/Library/Preferences/Logging/.plist-cache.uwjgpsmT
txt
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/libssl.1.1.dylib
txt
/private/var/db/timezone/tz/2024a.1.0/icutz/icutz44l.dat
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
txt
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/SPMySQL
txt
/System/Library/dyld/dyld_shared_cache_x86_64
txt
/usr/lib/libobjc-trampolines.dylib
txt
/private/var/db/analyticsd/events.allowlist
txt
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
txt
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
txt
/System/Library/dyld/dyld_shared_cache_x86_64.3
txt
/System/Library/dyld/dyld_shared_cache_x86_64.1
txt
/System/Library/dyld/dyld_shared_cache_x86_64.2
txt
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/libcrypto.1.1.dylib
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car
txt
/Applications/Sequel Ace.app/Contents/Resources/button_bar_handleTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/grabber-horizontal.png
txt
/Applications/Sequel Ace.app/Contents/Resources/button_duplicateTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/key-icon.tiff
txt
/Applications/Sequel Ace.app/Contents/Resources/key-icon-alternate.tiff
txt
/usr/lib/dyld
txt
/usr/share/icu/icudt70l.dat
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLight.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLight.car
txt
/Applications/Sequel Ace.app/Contents/Resources/Assets.car
txt
/System/Library/Fonts/Times.ttc
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
txt
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.apple.iconservices/store.index
txt
/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/UnknownFSObjectIcon.icns
txt
/private/var/db/mds/messages/501/se_SecurityMessages
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantDark.car
txt
/Applications/Sequel Ace.app/Contents/Resources/button_edit_modeTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/table-small.tiff
txt
/Applications/Sequel Ace.app/Contents/Resources/table-property.png
txt
/Applications/Sequel Ace.app/Contents/Resources/button_edit_mode_selectedTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/Fonts/Menlo.ttc
txt
/System/Library/Fonts/SFNS.ttf
txt
/System/Library/Fonts/HelveticaNeue.ttc
txt
/System/Library/CoreServices/CoreGlyphs.bundle/Contents/Resources/Assets.car
txt
/System/Library/Fonts/Helvetica.ttc
txt
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
txt
/System/Library/CoreServices/CoreGlyphsPrivate.bundle/Contents/Resources/Assets.car
txt
/System/Library/Fonts/LucidaGrande.ttc
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAqua.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantDark.car
txt
/System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver
txt
/System/Library/Components/AudioCodecs.component/Contents/MacOS/AudioCodecs
txt
/Applications/Sequel Ace.app/Contents/Resources/button_filterTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/button_filter_activeTemplate.pdf
txt
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/31001/libraries.data
txt
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/16777236_4004/functions.data
txt
/Applications/Sequel Ace.app/Contents/Resources/quick-connect-icon.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/database-small.tiff
txt
/System/Library/Fonts/Keyboard.ttf
txt
/System/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
txt
/System/Library/LinguisticData/Latn/Dict2.dat
txt
/System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/Resources/tokruleLE.data
txt
/System/Library/LinguisticData/Latn/Dict1.dat
txt
/System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/Resources/com.apple.datadetectorscore.cache.urlifier.system
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Graphite.car
txt
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite-shm
txt
/private/var/db/nsurlstoraged/dafsaData.bin
txt
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Assets.car
txt
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-shm
txt
/usr/share/langid/langid.inv
txt
/usr/share/germantok/german.index
txt
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/0/com.apple.LaunchServices.dv/com.apple.LaunchServices-3028-v2.csstore
0
/dev/null
1
/dev/null
2
/dev/null
3
4
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite
5
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite-wal
6
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite-shm
7
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib.metallib
8
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db
9
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-wal
10
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-shm
11
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db
12
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-wal
13
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters.metallib
14
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib_stitchable.metallib
15
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters_stitchable.metallib
16
localhost:50871->localhost:mysql
17
localhost:50876->localhost:mysql
18
count=0, state=0
19
/System/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
20
count=0, state=0
21
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Saved Application State/com.sequel-ace.sequel-ace.savedState/window_40.data
22
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/31001/libraries.data
23
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/31001/libraries.list
24
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/16777236_4004/functions.data
25
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/16777236_4004/functions.list
26
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Saved Application State/com.sequel-ace.sequel-ace.savedState/data.data
27
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Saved Application State/com.sequel-ace.sequel-ace.savedState/windows.plist
28
localhost:60613->localhost:mysql
29
192.168.1.109:61242->scdn.copy-space.com:mysql
30
count=0, state=0x8
31
192.168.1.109:61243->scdn.copy-space.com:mysql
32
count=0, state=0x8
33
localhost:60614->localhost:mysql
34
count=0, state=0
35
9C79D5DD-C7B1-4E47-9F34-7EDF9DE3EA69[5] user-packet-pool
36
count=0, state=0
`

**Current activity log:**
`cwd
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data
txt
/Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
txt
/Applications/Sequel Ace.app/Contents/Frameworks/QueryKit.framework/Versions/A/QueryKit
txt
/Applications/Sequel Ace.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/A/ShortcutRecorder
txt
/Library/Preferences/Logging/.plist-cache.uwjgpsmT
txt
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/libssl.1.1.dylib
txt
/private/var/db/timezone/tz/2024a.1.0/icutz/icutz44l.dat
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
txt
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/SPMySQL
txt
/System/Library/dyld/dyld_shared_cache_x86_64
txt
/usr/lib/libobjc-trampolines.dylib
txt
/private/var/db/analyticsd/events.allowlist
txt
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
txt
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
txt
/System/Library/dyld/dyld_shared_cache_x86_64.3
txt
/System/Library/dyld/dyld_shared_cache_x86_64.1
txt
/System/Library/dyld/dyld_shared_cache_x86_64.2
txt
/Applications/Sequel Ace.app/Contents/Frameworks/SPMySQL.framework/Versions/A/libcrypto.1.1.dylib
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car
txt
/Applications/Sequel Ace.app/Contents/Resources/button_bar_handleTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/grabber-horizontal.png
txt
/Applications/Sequel Ace.app/Contents/Resources/button_duplicateTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/key-icon.tiff
txt
/Applications/Sequel Ace.app/Contents/Resources/key-icon-alternate.tiff
txt
/usr/lib/dyld
txt
/usr/share/icu/icudt70l.dat
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLight.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLight.car
txt
/Applications/Sequel Ace.app/Contents/Resources/Assets.car
txt
/System/Library/Fonts/Times.ttc
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
txt
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.apple.iconservices/store.index
txt
/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/UnknownFSObjectIcon.icns
txt
/private/var/db/mds/messages/501/se_SecurityMessages
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantDark.car
txt
/Applications/Sequel Ace.app/Contents/Resources/button_edit_modeTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/table-small.tiff
txt
/Applications/Sequel Ace.app/Contents/Resources/table-property.png
txt
/Applications/Sequel Ace.app/Contents/Resources/button_edit_mode_selectedTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/Fonts/Menlo.ttc
txt
/System/Library/Fonts/SFNS.ttf
txt
/System/Library/Fonts/HelveticaNeue.ttc
txt
/System/Library/CoreServices/CoreGlyphs.bundle/Contents/Resources/Assets.car
txt
/System/Library/Fonts/Helvetica.ttc
txt
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
txt
/System/Library/CoreServices/CoreGlyphsPrivate.bundle/Contents/Resources/Assets.car
txt
/System/Library/Fonts/LucidaGrande.ttc
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAqua.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantDark.car
txt
/System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver
txt
/System/Library/Components/AudioCodecs.component/Contents/MacOS/AudioCodecs
txt
/Applications/Sequel Ace.app/Contents/Resources/button_filterTemplate.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/button_filter_activeTemplate.pdf
txt
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/31001/libraries.data
txt
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/16777236_4004/functions.data
txt
/Applications/Sequel Ace.app/Contents/Resources/quick-connect-icon.pdf
txt
/Applications/Sequel Ace.app/Contents/Resources/database-small.tiff
txt
/System/Library/Fonts/Keyboard.ttf
txt
/System/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
txt
/System/Library/LinguisticData/Latn/Dict2.dat
txt
/System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/Resources/tokruleLE.data
txt
/System/Library/LinguisticData/Latn/Dict1.dat
txt
/System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/Resources/com.apple.datadetectorscore.cache.urlifier.system
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Graphite.car
txt
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite-shm
txt
/private/var/db/nsurlstoraged/dafsaData.bin
txt
/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Assets.car
txt
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-shm
txt
/usr/share/langid/langid.inv
txt
/usr/share/germantok/german.index
0
/dev/null
1
/dev/null
2
/dev/null
3
4
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite
5
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite-wal
6
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/HTTPStorages/com.sequel-ace.sequel-ace/httpstorages.sqlite-shm
7
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib.metallib
8
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db
9
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-wal
10
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-shm
11
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db
12
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Caches/com.sequel-ace.sequel-ace/Cache.db-wal
13
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters.metallib
14
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib_stitchable.metallib
15
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters_stitchable.metallib
16
localhost:50871->localhost:mysql
17
localhost:50876->localhost:mysql
18
count=0, state=0
19
/System/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree
20
count=0, state=0
21
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Saved Application State/com.sequel-ace.sequel-ace.savedState/window_40.data
22
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/31001/libraries.data
23
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/31001/libraries.list
24
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/16777236_4004/functions.data
25
/private/var/folders/10/dfpb7rrd5491w_x5jtsjd3jr0000gn/C/com.sequel-ace.sequel-ace/com.sequel-ace.sequel-ace/com.apple.metal/16777236_4004/functions.list
26
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Saved Application State/com.sequel-ace.sequel-ace.savedState/data.data
27
/Users/sgyaa/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Saved Application State/com.sequel-ace.sequel-ace.savedState/windows.plist
28
localhost:60613->localhost:mysql
29
192.168.1.109:61242->scdn.copy-space.com:mysql
30
count=0, state=0x8
31
192.168.1.109:61243->scdn.copy-space.com:mysql
32
count=0, state=0x8
33
localhost:60614->localhost:mysql
34
count=0, state=0
36
count=0, state=0
`

**Comment by Kaspik** [comment]
I dont think we have capacity to debug single user - single OS issues unfortunatelly.
