### ISSUE TITLE
French translation for build number is wrong

### ISSUE THREAD

**Issue by bntswn** [Sequel-Ace/Sequel-Ace#2031]
- Sequel Ace Version (including build number): 4.0.17 20067
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 13.6.7 (22G720)
- Processor Type (Intel/Apple): Apple
- macOS Localization: French

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes.

**Description**
The translation for "build" is wrong.

**Steps To Reproduce**
1. Open the About window.

**Expected Behaviour**
The build number in French should not display "Construire", which means "To build", but rather "Build", or at least "Construction" which is the appropriate translation for "Build".

<img width="712" alt="SCR-20240620-lzct" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/129183874/1b77d1be-2acc-4af5-a920-cc317cc47c62">

**Comment by Jason-Morcos** [comment]
Hey there! We accept updates to Translations all the time via our Crowdin. You're welcome to submit an update via that system - https://github.com/Sequel-Ace/Sequel-Ace?tab=readme-ov-file#translations

Thank you
