### ISSUE TITLE
Application quits when the connecrtion is closed

### ISSUE THREAD

**Issue by NiklasBr** [Sequel-Ace/Sequel-Ace#2035]
- Sequel Ace Version (including build number): 4.0.17 (Build 20067)
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 14.5 (23F79)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0
- macOS Localization: en_GB

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
(seems to be the same as the current release)

**Description**
Apple's Human Interface Guidelines as well as long-standing tradition going back into the 1980:ies is that an application is not a document, therefore the application should not quit when the document window is closed. This is exemplified by how Apple's applications such as Safari, Mail, Automator, Books, FaceTime, Music, Xcode, and so on all remain running when closing the workspace window.

Sequel Ace does not adhere to this standard behaviour.

**Steps To Reproduce**
1. Open Sequel Ace
2. Open one or more DB connection
3. Close the connection(s)

**Expected Behaviour**
Sequel Ace application should remain running when the final connection is closed.

**Related Issues**
#2016

**Comment by Kaspik** [comment]
I think you mentioned the original issue, you definitely read it too. While I appreciate the "explanation, Apple HIG doesn't specify anything on this..:)

**Comment by NiklasBr** [comment]
Bug still exists even if you close this issue, so I don't really understand your reasoning here.

**Comment by Kaspik** [comment]
It's closed as not planned. If you wanna do it - do it, we will be more than happy to reviews a PR. Team considered it and there is no plan to do it anytime soon. as the priority of this is really low.

**Comment by NiklasBr** [comment]
I'm giving it a try now.
