### ISSUE TITLE
SSH gives "bad configuration options"

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#205]
Version: 2.1.1
MacOS: 10.15.5

When I use the private key of my server to connect, it gives me the following error.
A manual SSH with the same key to my server is working 100%.

Any ideas here?

Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/XXXXXXXX/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Users/XXXXXXXX/.ssh/id_ed25519 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 USER@IP -L 61465:127.0.0.1:3306

OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/XXXXXXXX/.ssh/id_ed25519
/Users/Daan/.ssh/id_ed25519: line 1: Bad configuration option: -----begin
/Users/Daan/.ssh/id_ed25519: line 2: Bad configuration option: LINE OF KEY
/Users/Daan/.ssh/id_ed25519: line 3: Bad configuration option: LINE OF KEY
/Users/Daan/.ssh/id_ed25519: line 4: Bad configuration option: LINE OF KEY
/Users/Daan/.ssh/id_ed25519: line 5: Bad configuration option: LINE OF KEY
/Users/Daan/.ssh/id_ed25519: line 6: Bad configuration option: LINE OF KEY
/Users/Daan/.ssh/id_ed25519: line 7: Bad configuration option: LINE OF KEY
/Users/Daan/.ssh/id_ed25519: line 8: Bad configuration option: -----end
/Users/Daan/.ssh/id_ed25519: terminating, 8 bad configuration options

**Comment by Jason-Morcos** [comment]
Did you set a manual ssh config file or grant access for Sequel Ace to access other files in Sequel Ace's preferences?
If so, make sure in the network tab of Sequel Ace's preferences that the "ssh config file" is correct (your file, or Sequel Ace default if no custom ssh config).
There's a known issue where granting files access can set the ssh config file incorrectly.

**Comment by jamesstout** [comment]
Do you have `/Users/XXXXXXXX/.ssh/id_ed25519` In the network prefs?

![Screenshot 2020-07-10 at 11 49 23 PM](https://user-images.githubusercontent.com/1576190/87173846-f07b7980-c308-11ea-83e6-7e9b45f52a2f.png)

Your connection string has your private key set for the `-F` arg:

` -F /Users/XXXXXXXX/.ssh/id_ed25519 `

It should be for the `-i` arg.

Try this setup:

![Screenshot 2020-07-10 at 11 56 34 PM](https://user-images.githubusercontent.com/1576190/87175412-31748d80-c30b-11ea-892b-5cef340b3793.png)

![Screenshot 2020-07-10 at 11 57 29 99PM](https://user-images.githubusercontent.com/1576190/87175431-38030500-c30b-11ea-9753-af127ad597ca.png)

**Comment by cappadaan** [comment]
Thx Jamers, your setup works.

**Comment by ernstki** [comment]
> Do you have `/Users/XXXXXXXX/.ssh/id_ed25519` In the network prefs?

It seems obvious _now_ that "config" ≠ "private key file," but I totally did this.

Is the reason those files appear in the list _just_ because the app was already granted access to them, _e.g._, private keys for individual profiles? Would there be a way to filter that list down, or suppress it?

Maybe there will only ever be two of us who do this accidentally, but it sure seems like a potential pitfall for a new user looking to set up SSH for the first time.

![Screenshot showing drop-down in Sequel Ace Preferences dialog for "SSH Config" option](https://user-images.githubusercontent.com/4009681/157135588-1b66fc15-370f-4788-a2c1-470dd83d82a4.png)

**Comment by Jason-Morcos** [comment]
> > Do you have `/Users/XXXXXXXX/.ssh/id_ed25519` In the network prefs?
> 
> 
> 
> It seems obvious _now_ that "config" ≠ "private key file," but I totally did this.
> 
> 
> 
> Is the reason those files appear in the list _just_ because the app was already granted access to them, _e.g._, private keys for individual profiles? Would there be a way to filter that list down, or suppress it?
> 
> 
> 
> Maybe there will only ever be two of us who do this accidentally, but it sure seems like a potential pitfall for a new user looking to set up SSH for the first time.
> 
> 
> 
> ![Screenshot showing drop-down in Sequel Ace Preferences dialog for "SSH Config" option](https://user-images.githubusercontent.com/4009681/157135588-1b66fc15-370f-4788-a2c1-470dd83d82a4.png)
> 
> 
> 
> 

Seems like a good possible improvement to try to cut down that list! That list is, like you said, just the list of files Ace has access to. One challenge I see is that basing it on filename could be inconsistent (any of those files could be named anything). Maybe we could _inspect_ the contents of the file and not let you select key files as configs? PRs are always welcome! :)
