### ISSUE TITLE
CMD + w should only close connection

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#206]
While connected to a database, the key combi "CMD + w" closes the whole application window.
A more logical behaviour would be to close the current connection only and return to the start screen of the application. 

Alsof Firefox uses "CMD + w" to only close the current tab and not the complete application, and maybe many more other applications do.

**Comment by samuelbradshaw** [comment]
I would expect ⌘W to close the current tab if there's more than one tab open, and to close the window if there's only a single tab. That's the behavior I see in all other apps I've used.

It wouldn't hurt to add a keyboard shortcut for closing the connection, but I don't think ⌘W should be used for that.

**Comment by cappadaan** [comment]
The problem is: if I have 3 connections open and I want to close them all and connect to a 4th new one.
I press 3x ⌘W, but then the whole app is closed. So I have to reopen it again.

Currently there is no way to go back to the home screen after closing the last connection.

**Comment by samuelbradshaw** [comment]
I would normally do `⌘W ⌘W ⌘W ⌘N` or `⇧⌘W ⌘N` in this scenario. I don't think it's a good idea to change a standard key combination to do something different than what other apps do.

Could we do something like `⌃⌘W` (with the control key) to close the connection? I don't think that would replace any standard shortcuts.

**Comment by cappadaan** [comment]
Or ⌘C ? (2 is easier than 3 keys)

**Comment by samuelbradshaw** [comment]
⌘C is the default command for "Copy". Otherwise it'd be perfect. :)

**Comment by Jason-Morcos** [comment]
<img width="221" alt="Screen Shot 2020-07-14 at 13 19 06" src="https://user-images.githubusercontent.com/10710367/87456215-9b738800-c5d4-11ea-8a4c-ccae0e49a4c7.png">
These are the key combos from Safari and this is what we should copy.
I am happy to review a PR if anyone would like to make one to make this change!

**Comment by Jason-Morcos** [comment]
Actually, I put my foot in my mouth there a bit - we already are using those combos.
Now I think I understand. @cappadaan you would like to change the mapping of the ⌘W keystroke to close the connection and _not_ close the tab.

Well first, I don't think we should change the ⌘W. We currently match what Safari does and that's how it should stay. I am open to adding a new keystroke and action to close the connection and _not_ close the tab but that duplicates an existing issue. Please see https://github.com/Sequel-Ace/Sequel-Ace/issues/139 to continue discussion.

I like @samuelbradshaw's idea to use the keystroke ⌃⌘W to close the current connection
