### ISSUE TITLE
Crashing when opening and closing the ID field for a binary UUID with a format override.

### ISSUE THREAD

**Issue by mmplanet** [Sequel-Ace/Sequel-Ace#2067]
- Sequel Ace Version (including build number): 4.1.0 20070
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 14.5 (23F79)
- Processor Type (Intel/Apple): M1 Max
- MySQL Version: 8.0.29
- macOS Localization: 

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
On a table with binary UUIDs, I use the new format override feature (right click on the ID column, UUID).
IDs become blue and in an UUID format. I double click on an ID to copy it, I close the window that appears, Sequel Ace crashes.

**Steps To Reproduce**
1. Use the new UUID format override feature
2. Double click on an overridden ID to copy it
3. Close the editor window that just appeared.
4. Sequel Ace crashes.

**Expected Behaviour**
Sequel ace should allow copying the ID and closing of the field editor window without crashing.

**Related Issues**

**Additional Context**

**Comment by luis-** [comment]
Will take a look when I get home from work today!

**Comment by Jason-Morcos** [comment]
Thank you!
