### ISSUE TITLE
Copy as SQL insert without primairy keys

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#207]
Currently there is an option "Copy as SQL insert" in the contents view of a table.

I really would like to see the option "Copy as SQL insert without primairy keys" added. 

There are many cases that I need to copy rows from 1 database to another, which are similar structure, but with different data and different primairy keys. In the current application I have to manually remove all the primairy key data before I can run the Insert command.

**Comment by MacTrophy** [comment]
I am wondering, would this be skipping all primary key values or only those that are auto-increment? I do see the use for skipping auto-increments (and had this need in the past myself a couple of times) but for other types of keys I am wondering.

**Comment by cappadaan** [comment]
I meant the auto-increment keys only

**Comment by jamesstout** [comment]
so, if a non AUTO_INCREMENT column is say a UNIQUE KEY, then you would still want to copy that?

**Comment by jamesstout** [comment]
And would you want this to be a global option in prefs or an extra menu item/right click option?

![Screenshot 2020-07-11 at 10 26 11 PM](https://user-images.githubusercontent.com/1576190/87226478-950fc100-c3c6-11ea-9ad6-867700517d2f.png)

![Screenshot 2020-07-11 at 10 25 40 PM](https://user-images.githubusercontent.com/1576190/87226482-9b05a200-c3c6-11ea-9fb5-018e0e8c273a.png)

**Comment by cappadaan** [comment]
Only auto increment, the rest of the data should be copied as is.

An extra menu item/right click would be most useful here

**Comment by jamesstout** [comment]
Something like this?

![2020-07-11 23 46 14](https://user-images.githubusercontent.com/1576190/87228147-c3df6480-c3d1-11ea-8fe0-b45e2368f4f5.gif)

**Comment by cappadaan** [comment]
Wow, this is the perfect solution! Good job!

**Comment by jamesstout** [comment]
@Sequel-Ace/all You ok with this? The menu item name ok?

![Screenshot 2020-07-14 at 7 39 35 PM](https://user-images.githubusercontent.com/1576190/87421769-0e4b2600-c60a-11ea-8622-b53fa41c71dd.png)
![Screenshot 2020-07-14 at 7 40 07 PM](https://user-images.githubusercontent.com/1576190/87421783-12774380-c60a-11ea-96c2-3f540571ec50.png)

**Comment by Jason-Morcos** [comment]
> @Sequel-Ace/all You ok with this? The menu item name ok?
> 
I'm okay with it! Go ahead and PR
I don't love the ctrl+shift+c keystroke but honestly can't think of a better one! Maybe shift+alt+cmd+c instead?

**Comment by jamesstout** [comment]
shift+alt+cmd+c does something weird. OK with shift+control+command+c?

**Comment by Jason-Morcos** [comment]
> shift+alt+cmd+c does something weird. OK with shift+control+command+c?

Yup! Works for me!
