### ISSUE TITLE
Changing MySQL Host field on connection favorite also resets password field

### ISSUE THREAD

**Issue by lostminds** [Sequel-Ace/Sequel-Ace#2076]
- Sequel Ace Version (including build number): 4.1.1 Build 20071
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store?
- macOS Version: 14.6.1
- Processor Type (Intel/Apple): Apple M2 Pro
- MySQL Version: not relevant, Sequel-Ace UI issue
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No newer releases available to try as far as I can tell

**Description**
In the SSH Connection details UI, changing the "MySQL Host:" field also resets/clears the password field. This is annoying when changing connection details (for example after a server move) since you then need to find and re-enter the password even though you do not wish / need to change it.

**Steps To Reproduce**
1. Select a connection favorite you've saved previously
2. Change the MySQL Host field.
3. Observe Password field being cleared.

**Expected Behaviour**
1. Select a connection favorite you've saved previously
2. Change the MySQL Host field.
3. Only MySQL Host field changes, nothing else.

**Comment by Kaspik** [comment]
That's correct - because everything is stored in Keychain, it has to match. On change, the password gets reset because the match wouldn't be found.

**Comment by Jason-Morcos** [comment]
Also a bit of a security thing - to protect from sending that password that was saved to a different host. This one's on purpose for today.
