### ISSUE TITLE
Files are no more accessible in Sequoia

### ISSUE THREAD

**Issue by MatzeKitt** [Sequel-Ace/Sequel-Ace#2092]
- Sequel Ace Version (including build number): 4.1.2 20072
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: Sequoia 15.0 (24A335)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.4
- macOS Localization: German

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
After the update to macOS Sequoia, I cannot add accessible files anymore. Also all previous added files are no more accessible to Sequel Ace. They appear red in the list.

**Steps To Reproduce**
1. Update to macOS Sequoia
2. Go to **Settings > Files > Add Files…**
3. See that nothing has changed

https://github.com/user-attachments/assets/e3e6aa36-d26d-4e74-bbc4-60efa2e4b2f9

**Expected Behaviour**
The selected files are added to the list of accessible files and are actually accessible.

**Related Issues**

**Additional Context**

**Comment by MatzeKitt** [comment]
Hm … I just downloaded the current version from GitHub, but the problem persists. I also completely cleaned the system with AppCleaner and reinstalled it with default settings, but the problem persists.

Is there maybe a system-wide permission necessary?

**Comment by scheibome** [comment]
I have exactly the same problems. My version is version 4.1.2.

**Comment by MatzeKitt** [comment]
Even more strange: after some time, it just started working again for me. 🤔

**Comment by scheibome** [comment]
I have now given the app full disk access and restarted it. I can now actually add the files again.
@MatzeKitt have you restarted your Mac so that it works again? That might be the solution. Even if it is strange that it suddenly stopped working.

**Comment by MatzeKitt** [comment]
No, I did nothing. I even left Sequel Ace open the whole time.

**Comment by ifullgaz** [comment]
Same problem here, I cannot add files using the preferences panel and Sequel Ace doesn't prompt me to add revoked files.

**Comment by ziemkowski** [comment]
I gave full disk access to both Sequel Ace and `ssh` since the error is from OpenSSH:
> OpenSSH_9.8p1, LibreSSL 3.3.6
> Can't open user config file /Users/adrian/.ssh/config: Operation not permitted

However, the error continues even after restarting Sequel Ace and killing all `ssh` processes.

**Comment by nicolabeghin** [comment]
following

**Comment by ThorTL67** [comment]
I had the same issue on version 4.1.3 - resolved by restarting my Mac.

The window still crashes when you click add file but it does add it this time

**Comment by dazecoop** [comment]
Same problem here. Quitting & re-opening sometimes seems to work.

I've also found when adding files and it _doesn't_ show the files that I've just added, often the files _are actually_ granted & I can proceed to connect. Almost as if the UI is not reflecting the action I've just taken.

- Sequel Ace Version: 4.1.3 (20074)
- Sequel Ace Source: App Store
- macOS Version: Sequoia 15.0 (24A335)
- Processor Type: Apple M1

**Comment by dahjelle** [comment]
Oddly, things were working fine until mid-day today, at which point I was prompted for re-granting access. I don't remember all the sequence of events, but some things that happened amongst many re-starts of Sequel Ace:

- I was prompted for access, and then the dialog for opening the file kept opening for the same file.
- Even though the warning was only about a single file, all files ended up showing up red, and eventually disappearing altogether.
- I was prompted for the password of my SSH key.
- Like @dazecoop observed, I was able to blindly grant access to the necessary files, and then I am back in a workable state.

The App Store says my copy of Sequel Ace was updated yesterday, and I did modify some SSH files today, so I'm not surprised at being re-prompted.

My configuration is also the same as @dazecoop .

**Comment by MatzeKitt** [comment]
Since I started this issue, I experienced the problem multiple times again. Sometimes I was able to just re-select the files and it was working, sometimes it was not. After closing the app for a few hours and opening it again, the problem sometimes vanished, sometimes not. Very inconsistent behavior.

**Comment by dazecoop** [comment]
I'm still experiencing constant issues, to the point where this is unusable for me now.

I have even resorted to uninstalling & reinstalling & I still face the same issues (periodically I may add, which adds to the annoyance). Have restarted my Mac multiple times in the past few days simply for this one single issue.

I am currently on a trial of [Querious](https://www.araelium.com/querious/renew) to simply get me through this period. May end up paying & moving to that at this point. 😕

**Comment by proudnerds-typo3** [comment]
Same problem here after upgrading to Mac Sequoia. Even after updating to latest version the issue remains. Can't proceed with my work due to this.

**Comment by dahjelle** [comment]
Very oddly, without any updates that I'm aware of, I came in this morning, and got the error message. The difference is that I was able to actually add files in the Files pane of Settings and they showed up and it worked!

I have no idea what would have changed between yesterday and today on my end.

**Comment by Kaspik** [comment]
There seems to be an issue in new macOS that simply "prevents" apps from doing regular things that just goes away (not related to Sequel Ace) automatically by itself... can't say more now. 😄

**Comment by spointecker** [comment]
Same issue here on Sequoia and version 4.1.4

**Comment by MatzeKitt** [comment]
A similar issue can occur on export. Sometimes, the path is empty and even if I select a new path, it stays empty and thus an export is impossible.

**Comment by salvor-hardin** [comment]
Got some workaround to fix it... perhaps it might help other people out there.

Close all applications.

Download & Install Onyx https://titanium-software.fr/en/onyx.html 
This is a general purpose macOS cleaner and tweaker.

Run the normal maintenance (screenshot).

Restart when prompted.

When you open Sequel Ace after restart, certificates will still not be there, however if you add the certificates once more and save, connect, then quit Sequel Ace, and reopen... certs will be kept there and this apparently fixes it right now. 
Will report if this not working later today.

![2024-10-16 at 09 45 37](https://github.com/user-attachments/assets/12e947cc-3245-4da1-8f19-48ba3b1ae050)

**Comment by kilinvs** [comment]
Same issue for me, updated to macos Sequoia straight after release. Sequel Ace worked fine until today, today it displayed a prompt to access ssh config files, I have cancelled it. And now there is no way to add access to files from settings. Same behaviour as on issuer creator video.

**Comment by ThomasNimstad** [comment]
I'll join the list of users that suddenly cannot use Sequel Ace anymore. Which is odd since I updated two weeks ago and user Sequel Ace daily, but lost access randomly an hour ago.

**Comment by salvor-hardin** [comment]
> I'll join the list of users that suddenly cannot use Sequel Ace anymore. Which is odd since I updated two weeks ago and user Sequel Ace daily, but lost access randomly an hour ago.

Have you tried my workaround ? Since I did it that I had no problems on that computer.

**Comment by Kaspik** [comment]
Or simply restart few times your Mac 😃

**Comment by ThorTL67** [comment]
Managed to fix this for myself.

In SequelAce -> Settings -> Network, My 'Known Hosts' was set to ADVANCED - I changed this to SequelAce default and it started to work for me. I don't recall ever changing this setting before

![Screenshot 2024-10-25 at 11 08 14](https://github.com/user-attachments/assets/b16057de-bc43-4940-a5d5-6d7c86bcd506)

**Comment by floorz** [comment]
Also still happening for me on macOS Sequoia 15.0.1 with Sequal Ace 4.1.5 build 20077

Attempting to update macOS to 15.1 now to see if it resolves

**Comment by aaajeetee** [comment]
I was having the same issue and I can confirm that upgrading to Sequoia 15.1(.1) fixes this issue.

**Comment by MatzeKitt** [comment]
Thanks für your confirmations. I’ll close this for now.
