### ISSUE TITLE
Issue with default TIMESTAMP values when inserting new rows

### ISSUE THREAD

**Issue by MacGritsch** [Sequel-Ace/Sequel-Ace#2095]
- Sequel Ace Version: 4.1.2 (20073)
- MySQL Version: 8.1 and 9.0

**Description**
If a table has a column of type TIMESTAMP with a default VALUE of CURRENT_TIMESTAMP, when entering a new row, Sequel-Ace tries to enter it with single quotes:
```
INSERT INTO `test_table` (`id`, `test_ts`) VALUES (NULL, 'CURRENT_TIMESTAMP');
```
This code does not work. This would be the correct query:
```
INSERT INTO `test_table` (`id`, `test_ts`) VALUES (NULL, CURRENT_TIMESTAMP);
```

Table syntax:
```
CREATE TABLE `test_table` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `test_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

```

**Comment by Jason-Morcos** [comment]
@vuon9 possibly related to https://github.com/Sequel-Ace/Sequel-Ace/pull/2063? Want to take a look?

**Comment by vuon9** [comment]
I know the problem, let me give a fix soon. Sorry for the inconvenience!

**Comment by HiroYuan-DAICHIGP** [comment]
I'm using Sequel Ace macos app.
Inserte new row or update column value using CURRENT_TIMESTAMP resulting "0000-00-00 00:00:00".
Hope this will be fixed soon!
