### ISSUE TITLE
Can't click "show details" on sssh connection error

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#21]
I get the error "The SSH Tunnel has unexpectedly closed.". When I click Show Detail, the popup disappears without telling me why.

**Comment by Jason-Morcos** [comment]
@gbourdreau I'm not sure what's causing this one. I too had the show details button working a few commits ago. Perhaps sandboxing interrupted this too? Or perhaps it was unrelated

**Comment by Jason-Morcos** [comment]
Perhaps it was related to this fix?

https://github.com/Sequel-Ace/Sequel-Ace/commit/437a0bdc541b1203ed41426a47ed534c08b45e03

**Comment by gboudreau** [comment]
I can take a look, if you are not already on it..?

**Comment by jamesstout** [comment]
Hmmm, sorry fellas. I tested that quite a bit as well...

**Comment by gboudreau** [comment]
Some of the return codes used in `SPConnectionController` (but not all of them) are defined in [SPAlertSheets.m](https://github.com/Sequel-Ace/Sequel-Ace/blob/master/Source/SPAlertSheets.m)
If we change them in that file, then we'll need to change the returnCodes used in the conditionals everywhere `SPAlertSheets` is used.
But I also noticed that sometimes, a regular `NSAlert` is used, and return codes needs to use the deprecated values, until those `NSAlert` are updated (to use `completionHandler:` instead of a `didEndSelector:` ..?)

**Comment by gboudreau** [comment]
Overall, removing all deprecated notices would need some effort in that regard.
I suggest just reverting the modified conditionals, until someone takes more time to resolve the issue globally.

**Comment by gboudreau** [comment]
Of note: `NSOKButton => NSModalResponseOK` can be kept, as those two are equivalent.

**Comment by Jason-Morcos** [comment]
Does this fix it for everyone? I accept both the new and legacy conditional values

https://github.com/Sequel-Ace/Sequel-Ace/commit/7805a4b63ae5c0c8aa26c20c0efe834137b93786

**Comment by jamesstout** [comment]
Tested ssh fails last night and looked good (not the bind error though, not sure how to replicate). Didn't get chance to check fav import fails or bundle deletes, but for those two I'd changed them to the `withCompletion` instantiation. I'll check later. 

Just FYI - I'm back to work now and in Hong Kong (GMT+8).

**Comment by jamesstout** [comment]
fav import failure just displays one OK button and return code isn't checked.
delete bundle - OK and cancel work as expected.
delete favourite - OK and cancel work as expected.

ssh bad username - buttons work as expected
ssh wrong IP -  buttons work as expected
ssh wrong port -  buttons work as expected
ssh no key or pass -  buttons work as expected
ssh bad key (edit `~/.ssh/id_rsa`) -  buttons work as expected
revert edit and re-select key - connection fails. Maybe not copied to` .keys`?
`cp ~/.ssh/id_rsa.bak` to `~/.ssh/id_rsa` and re-select key - connection works.
