### ISSUE TITLE
SQL execution error when updating datetime fields

### ISSUE THREAD

**Issue by smile-magic** [Sequel-Ace/Sequel-Ace#2101]
- Sequel Ace Version (including build number):4.1.3
- Sequel Ace Source (App Store/GitHub/Homebrew):GitHub
- macOS Version:14.7 
- Processor Type (Intel/Apple):Intel
- MySQL Version:5.7 and 8.0
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
The SQL executed when modifying the datetime field value is
```sql
UPDATE `city` SET `create_time` = 2024-03-18 16:41:20 WHERE `id` = '3';
```
error message:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '11:51:27 WHERE `id` = '2'' at line 1

**Expected Behaviour**

```sql
UPDATE `city` SET `create_time` = '2024-03-18 16:41:20' WHERE `id` = '3';
```

**Comment by Jason-Morcos** [comment]
Is this new in 4.1.3 or was this existing in 4.1.2?

**Comment by smile-magic** [comment]
> 这是 4.1.3 中的新内容还是 4.1.2 中存在的功能？

All exist

**Comment by Jason-Morcos** [comment]
I'm a bit confused - are you saying this is a bug that existed in older versions too? Just making sure it wasn't caused by the change in 4.1.3 https://github.com/Sequel-Ace/Sequel-Ace/pull/2096

Fyi @vuon9

**Comment by smile-magic** [comment]
The problem only exists with `DEFAULT CURRENT_TIMESTAMP`

**Comment by vuon9** [comment]
Let me have a look soon
