### ISSUE TITLE
Single quotes around default value of (curdate())

### ISSUE THREAD

**Issue by b-fitzpatrick** [Sequel-Ace/Sequel-Ace#2103]
- Sequel Ace Version (including build number): 4.1.3, 4.1.2, works fine in 4.1.1
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Sonoma 14.6.1
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.39
- macOS Localization: US

**Description**
I have a table with a date field with the default value of (curdate()).
![image](https://github.com/user-attachments/assets/ebaaa17d-6b4f-496d-95df-c058ec49c87b)

When I insert a row, I receive this error.
![image](https://github.com/user-attachments/assets/eea4de90-69c4-44c6-b4d1-96d5075a1b8f)

I have reverted to 4.1.1, and it works without error. I believe the single quotes around (curdate()) are the problem.

**Comment by Jason-Morcos** [comment]
@vuon9 Also possibly related?

**Comment by vuon9** [comment]
> @vuon9 Also possibly related?

I think so, let me have a look.

**Comment by Jason-Morcos** [comment]
Hey @vuon9  - have you had a chance to look at this one? I'm about to push another release and was gonna hopefully include the fix for this as well if we have it :)

**Comment by vuon9** [comment]
Hey @Jason-Morcos 
Sorry, I don't have free time to work on it yet. Let me see it in this weekend.

**Comment by Jason-Morcos** [comment]
No worries, thank you for the help!!
