### ISSUE TITLE
long queries suddenly dying with "The table .... is full"

### ISSUE THREAD

**Issue by BillSeitz** [Sequel-Ace/Sequel-Ace#2106]
- Sequel Ace Version (including build number): 4.1.3 20074
- Sequel Ace Source (App Store/GitHub/Homebrew): AppStore
- macOS Version: 13.5.2
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.36
- macOS Localization: US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**
I have some queries which take 10min to run. They worked fine a week ago. I since updated to the latest version, and now when I run them they die after ~8min with "The table '/rdsdbdata/tmp/#sql131_83b2_a' is full"

I just retstart my Mac to make sure that wasn't an issue. There's plenty of disk space, etc.

**Steps To Reproduce**
1. run (a slow) query
2. runs for a while, then dies with error message noted above.

**Expected Behaviour**

Finish/list the query (that results table is usually ~100 rows.)

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Is this a cloud-hosted db server? It sounds like you're hitting some storage limits on the db-side

**Comment by Jason-Morcos** [comment]
https://stackoverflow.com/questions/77327919/sql-error-1114-hy000-the-table-rdsdbdata-tmp-sql161-17a011-a-is-full

**Comment by BillSeitz** [comment]
Yes, we had switched recently to using Aurora. After seeing a variety of issues come up, our devops contractor decided Aurora wasn't going to give us any benefit anyway, so we switched back. So hopefully problem will go away.
