### ISSUE TITLE
long time no use will show error  table database1.table2 not doesn't exsit

### ISSUE THREAD

**Issue by kdlz30** [Sequel-Ace/Sequel-Ace#2114]
- Sequel Ace Version (including build number): Version 4.1.4  Build 20075
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 14.4.1 (23E224)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 5.7

when i open a database (like database1) and change  to another database (like database2)  after many time no use it 
when i return to do some oprate for database2 (like refresh table2) 
I't will show error  "" 
I guest the app is only save first database ,when  i change database ,it's not update the new database

![Uploading WX20241013-134120@2x.png…]()

**Comment by Jason-Morcos** [comment]
Duplicate https://github.com/Sequel-Ace/Sequel-Ace/issues/1806

**Comment by Jason-Morcos** [comment]
Duplicate https://github.com/Sequel-Ace/Sequel-Ace/issues/1806
