### ISSUE TITLE
Extra connection opened simultaneously for metadata which is only terminated when i quit the application 

### ISSUE THREAD

**Issue by muhammetbudak** [Sequel-Ace/Sequel-Ace#2115]
- Sequel Ace Version (including build number): Version 4.0.13 Build 20062
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 14.5 (23F79)
- Processor Type (Intel/Apple): Apple
- MySQL Version: 8.0.x
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes. I downloaded latest beta [4.1.4 (20075)] and issue still exists.

**Description**
An extra connection is established when i try to access a database, this connection checks some metadata. But this connection is not closed when i close this connection tab. It's only closed when i completely quit Sequel Ace application.

**Steps To Reproduce**
1.Connect to a mysql database using terminal and check processes with a specific user.
2.Then open a sequel ace connection tab with this user and check processlist from other connection. 
3.There will be an extra connection. To specify each connection different databases can be picked in each connection. i.e. information_schema on one connection, performance_schema on other connection.
4.Close sequel ace tab and check processlist using terminal.
5.Extra connection will appear until sequel ace application is completely terminated. 

**Expected Behaviour**

I've 3 recommendations.
1.Metadata can be checked with same connection.
2.The connection used for metadata check can be closed immediately when the tab is closed.
3.There may be a setting to disable this extra connection.

**Related Issues**

**Additional Context**

I can not produce a screenshot because i need to show not a moment, a connection flow. And i can not provide a crash log because there is no crash. But issue is very easy to reproduce with the steps i mentioned above. I can only provide a flow of commands on a terminal while there is an open connection with the application background.

**Comment by Jason-Morcos** [comment]
@Kaspik I wonder if this is the memory leak that's existing? An extra connection to pull metadata?

**Comment by Kaspik** [comment]
What, that exists?!

**Comment by vuon9** [comment]
I think we can confirm this issue, here are some logs


```
// Disconnect - Closing a tab
// Only 1 connection has been closed

[AppCenterAnalytics] INFO: -[MSACSessionTracker sendStartSession]/107 New session ID: 34A51C5F-E35A-4348-A0D2-1D3B12535D7A
[AppCenter] DEBUG: -[MSACChannelUnitDefault enqueueItem:flags:]_block_invoke/159 Saving log, type: startSession, flags: 1.
-[SPDatabaseDocument closeConnection]:2340: closeConnection
-[SPMySQLConnection disconnect]:296: calling _disconnect
-[SPMySQLConnection disconnect]:296: calling _disconnect
-[SPMySQLConnection(PrivateAPI) _disconnect]:1099: _disconnect
-[SPMySQLConnection(PrivateAPI) _disconnect]:1099: _disconnect
-[SPMySQLConnection(Querying_and_Preparation) cancelCurrentQuery]:558: cancelCurrentQuery
-[SPMySQLConnection(Querying_and_Preparation) cancelCurrentQuery]:558: cancelCurrentQuery
-[SPMySQLConnection(Ping_and_KeepAlive) _cancelKeepAlives]:306: _cancelKeepAlives
-[SPMySQLConnection(Ping_and_KeepAlive) _cancelKeepAlives]:306: _cancelKeepAlives
-[SPMySQLConnection(PrivateAPI) _disconnect]:1133: calling mysql_close(mySQLConnection)

// Connect - Clicking on favorite database
// 2 connections are opened

-[SPMySQLConnection connect]:268: connect
-[SPMySQLConnection(PrivateAPI) _connect]:544: _connect
-[SPTablesList updateTables:]:193: updateTables, sender: <SPTablesList: 0x110eedd70>
-[SPDatabaseDocument startTaskWithDescription:]:1147: startTaskWithDescription: Loading (null)...
-[SPDatabaseDocument startTaskWithDescription:]:1185: Schedule appearance of the task window in the near future, using a frame timer
-[SPHistoryController updateHistoryEntriesWithUpdateToolbarItem:]:220: updateHistoryEntries
-[SPDatabaseDocument endTask]:1338: endTask
-[NSMutableString(RegexKitLiteAdditions) replaceOccurrencesOfRegex:withString:]:2620: Regex: %
-[NSMutableString(RegexKitLiteAdditions) replaceOccurrencesOfRegex:withString:]:2621: replacement: %%
-[NSMutableString(RegexKitLiteAdditions) replaceOccurrencesOfRegex:withString:]:2620: Regex: (?<!`)@(?!=`)
-[NSMutableString(RegexKitLiteAdditions) replaceOccurrencesOfRegex:withString:]:2621: replacement: %@
-[SPDatabaseDocument endTask]:1338: endTask
-[SPDatabaseDocument endTask]:1343: _isWorkingLevel = 1
-[SPDatabaseDocument endTask]:1349: _isWorkingLevel = 0
-[SPDatabaseDocument endTask]:1357: !_isWorkingLevel, all tasks have ended
-[SPDatabaseDocument endTask]:1361: Cancel the draw timer if it exists
-[SPDatabaseDocument endTask]:1367: self showQueryExecutionTime
-[SPMySQLConnection connect]:268: connect
-[SPMySQLConnection(PrivateAPI) _connect]:544: _connect
-[SPDatabaseDocument showQueryExecutionTime]:1205: showQueryExecutionTime: 00:00:00
-[SPDatabaseDocument endTask]:1369: queryExecutionTimer invalidate
-[SPDatabaseDocument endTask]:1375: taskDisplayIsIndeterminate,stopAnimation
-[SPTableData updateStatusInformationForCurrentTable]:1051: updateStatusInformationForCurrentTable called
-[SPTableData updateStatusInformationForCurrentTable]:1060: No table selected, returning
```

By process list UI, we could also verify the issue:

I closed one of two tabs, leaving three connections open.
![image](https://github.com/user-attachments/assets/de60192a-c2db-4437-89de-ce4747c2f524)

After opening a new tab and connecting to a database, I end up with five connections.
![image](https://github.com/user-attachments/assets/cb81ad3e-0e29-40ba-8485-b3d165ca2eeb)
