### ISSUE TITLE
LONGTEXT field not being escaped in exports (but is when using Copy as SQL Insert)

### ISSUE THREAD

**Issue by Mesuva** [Sequel-Ace/Sequel-Ace#2116]
- Sequel Ace Version -  4.1.4, build 20075
- Sequel Ace Source - App store
- macOS Version: Sonoma 14.6.1
- Processor Type: Apple
- MySQL Version: MariaDB 10.6.18
- macOS Localization: English

When using File->Export and exporting an SQL dump, I've found that some Longtext fields with some JSON in them are not being escaped. E.g:
 
![Screenshot 2024-10-14 at 19 11 22](https://github.com/user-attachments/assets/057b1ed6-3f7b-4050-afc3-c39b77f1df0f)

If on the other hand you use the Copy as SQL common on an individual row, the SQL generated through that process is being escaped. 

I've used Sequel Ace for quite some time, doing lot of dumps and restores, and this is the first time I've seen this issue.
What was produced was a dump that had many errors, simply because of places where the escaping was needed.

The thing that stands out to me is that it's for a longtext field, as I would expect to be running into this issue a lot more if it was all text or varchar types.

**Expected Behaviour**
I would expect the database dump data to be fully escaped.

For my immediate need to backup and transfer, I used TablePlus and that worked without issue, suggesting it's not corrupt data or similar.

**Related Issues**
I'm wondering if this is related: https://github.com/Sequel-Ace/Sequel-Ace/issues/1956

**Comment by vuon9** [comment]
Would you help to share the schema and sample data that you have got that issue?
I tried but seems it works fine for me when exporting to file as sql.

**Comment by Mesuva** [comment]
Sure, here's the table in question:

```
CREATE TABLE `crop_entries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `form_id` bigint(20) unsigned NOT NULL,
  `policy_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `share_farmers_insured` tinyint(1) DEFAULT NULL,
  `all_properties_insured` tinyint(1) DEFAULT NULL,
  `suffered_damage` tinyint(1) DEFAULT NULL,
  `reducing_excess_default` tinyint(1) DEFAULT '0',
  `comments` text COLLATE utf8mb4_unicode_ci,
  `crop_failure_notes` text COLLATE utf8mb4_unicode_ci,
  `insurance_history` tinyint(1) NOT NULL DEFAULT '0',
  `insurance_history_notes` longtext COLLATE utf8mb4_unicode_ci,
  `street_address` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postcode` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shire` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `completed_by_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_cache` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `agworld_cache` longtext COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2574 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

And here's a valid SQL statement to insert a row of data:
```
INSERT INTO `crop_entries_example` (`id`, `form_id`, `policy_type`, `share_farmers_insured`, `all_properties_insured`, `suffered_damage`, `reducing_excess_default`, `comments`, `crop_failure_notes`, `insurance_history`, `insurance_history_notes`, `street_address`, `city`, `state`, `postcode`, `shire`, `completed_by_name`, `data_cache`, `agworld_cache`, `created_at`, `updated_at`)
VALUES
	('1651', '1829', 'pre-harvest', NULL, '1', '0', '0', 'nil', 'lack of rain', '0', NULL, 'REDACTED', 'REDACTED', 'SA', '5000', '', 'REDACTED', '{ \"cropSelected\": [ { \"barley\": true, \"wheat\": true, \"oats\": true }, { \"barley\": true }, { \"barley\": true }, { \"barley\": true } ], \"cropDefaultValue\": [ { \"barley\": \"0\", \"wheat\": \"0\", \"oats\": \"0\" }, { \"barley\": \"0\" }, { \"barley\": \"0\" }, { \"barley\": \"0\" } ], \"cropDefaultYield\": [ { \"barley\": \"0\", \"wheat\": \"0\", \"oats\": \"0\" }, { \"barley\": \"0\" }, { \"barley\": \"0\" }, { \"barley\": \"0\" } ], \"cropDefaultReducingExcess\": [ { \"barley\": false, \"wheat\": false, \"oats\": false }, { \"barley\": false }, { \"barley\": false }, { \"barley\": false } ], \"cropDefaultExcess\": [ { \"barley\": 5, \"wheat\": 5, \"oats\": 5 }, { \"barley\": 5 }, { \"barley\": 5 }, { \"barley\": 5 } ], \"fields\": [ { \"0\": { \"name\": \"FOX\'S MULBERRY\", \"crop_type\": \"barley\", \"area\": 36, \"cover_type\": \"\", \"insured_yield\": \"0\", \"insured_value\": \"0\", \"fire_cover\": true, \"hail_cover\": false, \"interest\": \"\", \"excess\": \"0\", \"reducing_excess\": false, \"share_farmer_name\": \"\", \"share_farmer_insurer\": \"\", \"share_farmer_agreement\": \"\", \"boundary\": \"\" } } ], \"properties\": [ { \"name\": \"REDACTED\", \"shire\": \"Fergusson - SA\", \"latitude\": \"\", \"longitude\": \"\", \"area\": 1411, \"expected_shire\": \"FERGUSSON - SA\" } ] }', NULL, '2024-09-17 13:52:26', '2024-10-10 14:58:47');
```

- if you then right click on the entry and go Copy as SQL, it's valid (that's what is above)
- if you use the export feature (i.e. right click on the table and go Export as SQL Dump...), that produces broken SQL, as attached below.  Search for the word MULBERRY.
[crop_entries_example.sql.zip](https://github.com/user-attachments/files/17445116/crop_entries_example.sql.zip)

**Comment by vuon9** [comment]
Thanks! It's reproducible with the provided data. It's likely similar to the issue (when the field has `COLLATE utf8mb4_bin`) and I have fixed for copy function on right click https://github.com/Sequel-Ace/Sequel-Ace/pull/2062.

I'll handle this.

**Comment by Mesuva** [comment]
I actually never noticed the utf8mb4_bin collation. That wasn't something I intentionally picked.
