### ISSUE TITLE
>100% CPU usage when idle

### ISSUE THREAD

**Issue by shaw-01** [Sequel-Ace/Sequel-Ace#2128]
- Sequel Ace Version (including build number): Version 4.1.5 Build 20077
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 15.1 (24B83)
- Processor Type (Intel/Apple): Apple m2  MacBook Air 2022
- MySQL Version: mysql 5.7.40
- macOS Localization: Chinese language

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
After upgrading the latest Mac OS system,After a few hours of use, the CPU usage rate> = 100%

![20241108-170708](https://github.com/user-attachments/assets/f1ec69d6-a9b9-465c-bc67-b0dfe32c3568)

![img_v3_02ge_480bf7f5-a668-41d7-914d-b3e239ceff4g](https://github.com/user-attachments/assets/08b8af5a-3815-48da-baed-e1bdc9f03564)

**Steps To Reproduce**

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
Duplicate https://github.com/Sequel-Ace/Sequel-Ace/issues/1693
