### ISSUE TITLE
Add an option to paste in DATABASE_URL or DSN syntax to create a connection

### ISSUE THREAD

**Issue by frank-laemmer** [Sequel-Ace/Sequel-Ace#2130]
When creating a new database connection, it's mundane to copy / paste over multiple values. As far as I understand, there are multiple dialects to describe a database connection in one line:

```
Database_url also used by Symfony and supported by TablePlus:
mysql://[user]:[password]@[host]:[port]/[database]

DataGrip:
jdbc:mysql://[host]:[port];databaseName=[database];user=[user];password=[password]

PDO DSN:
mysql:host=[host];port=[port];dbname=[database];user=[user];password=[password]
```

My feature request: Parse such syntax when pasting it into the host field when creating a connection. Then automatically create the connection.

**Comment by Jason-Morcos** [comment]
Sequel Ace does support connection url strings, but as you noted doesn't support those being pasted into the connection config.

**Comment by frank-laemmer** [comment]
Thanks for pointing. I missed and I am still option where to enter the URL. Can you point me where to find the option?

With TablePlus one can enter an URL which than will be parsed into the normal connection setting setup.

**Comment by Jason-Morcos** [comment]
No option to enter the URL - it's got url open-in support. So you should be able to click a link somewhere else on your Mac (maybe right click if you have multiple compatible apps) and open in Sequel Ace. 

`mysql://[user[:password]@][host[:port]][/database][?ssh_host=][&ssh_port=][&ssh_user=][&ssh_password=][&ssh_keyLocation=][&ssh_keyLocationEnabled=]`

**Comment by frank-laemmer** [comment]
Very interesting (somehow hidden) feature. Specifically that it also seems to support a connection via SSH tunnel. 

I suggest to close this feature request for now. Thanks Jason, not only for quick replies but also for maintaining Sequel Ace!

**Comment by Jason-Morcos** [comment]
Happy to help! :)

**Comment by frank-laemmer** [comment]
Sorry to be a PITA. I like to point out that I had to register Sequel Ace to open mysl:// links, while TablePlus already registered itself somehow.

[mysql://user:password@host:3306/database](mysql://user:password@host:3306/database)

<img width="466" alt="Screenshot 2024-11-12 at 15 16 51" src="https://github.com/user-attachments/assets/34f8059b-b484-457e-a31e-f762fdd6c560">

**Comment by Jason-Morcos** [comment]
Is it possible Table Plus took priority because it was installed first? We definitely publish that we support these links in the Apple spec per standard

**Comment by frank-laemmer** [comment]
Interesting. Not sure if it matters: I have had Sequel Pro, later installed Sequel Ace, also the Beta version for a while, now only for testing purposes installed TablePlus. Like noted, Sequel Ace was not shown initially for me. I first had to click the 'Choose…' button with 'Choose another Application'.

Some background: We provide a small PHP hosting service. I am currently designing a new dashboard. Setting up the local MySQL connections is of course a mundane task. So I am looking forward to provide the MySQL link as a one click short cut in addition to traditional settings. We provide access via SSH tunnel only, so eager to test that as well.

We have a lot of macOS users in support, thus many are using Sequel Ace. But I will also have to test this with Workbench.
