### ISSUE TITLE
SQL export UI needs some conveniences — too many checkboxes!

### ISSUE THREAD

**Issue by crackwilding** [Sequel-Ace/Sequel-Ace#2133]
It's easy enough to check or uncheck a few of these boxes, but I have reason to uncheck many, and I'm pulling my hair out:

<img width="899" alt="image" src="https://github.com/user-attachments/assets/e29e5fea-5b69-4a8f-bd0c-df15b6cb5d0f">

It would be nice to be able to select a bunch of rows and check the boxes with keys (S,C, or D would be good). Checking hundreds of tiny boxes is a nightmare.

**Comment by samuelbradshaw** [comment]
Is this in the Export dialog?

If so, you can select or unselect a full column by clicking the "S", "C", or "D" column header:
<img width="114" alt="Screenshot 2024-11-13 at 11 12 04 AM" src="https://github.com/user-attachments/assets/2542320f-ba9d-4431-af3e-3991ba4f7a18">

You can also select or deselect all columns by clicking the minus or checkmark icon at the bottom:
<img width="91" alt="Screenshot 2024-11-13 at 11 12 46 AM" src="https://github.com/user-attachments/assets/b8040bfe-37cb-4ec3-bae3-87b1c5897adf">

I discovered this a while back by trial and error (it's a little bit hidden).

**Comment by crackwilding** [comment]
Yeah I knew about that, but I ran into a situation where I needed to export an arbitrary selection of like 150 tables out of about 300, some of them just structure and drop tables, some all three. I had no choice but to click hundreds of boxes.

**Comment by Jason-Morcos** [comment]
Feel free to open up a PR or feature request if you've got some specific changes that would make this UI better :)

**Comment by crackwilding** [comment]
How do you open a feature request?

**Comment by Jason-Morcos** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/issues/new?assignees=&labels=&projects=&template=feature_request.md

Please be sure to be specific about the change you'd like, however. A general gripe is pretty tough to address.
Realistically, if you want to see a change the best thing to do is PR that change yourself. That's the joy of Open Source Software :)

**Comment by crackwilding** [comment]
Understood. Obj-C is not my thing really but I can at least create a detailed design plan.

**Comment by crackwilding** [comment]
And thanks.

**Comment by vuon9** [comment]
I hate this kind of naming but I'm still working on many projects which have that. 

I assume I couldn't change the table names but Sequel Ace could have an toggle option in this view to group the tables has the same prefix into a nested structure, then I can easily select/unselect a group of table with 1 click on the parent nodes.
