### ISSUE TITLE
Display tables with column privileges

### ISSUE THREAD

**Issue by kevin-kortum-trustedshops** [Sequel-Ace/Sequel-Ace#2137]
My team at work has the requirement to limit access to specific columns for users. Thus, we have to use the column privilege feature of MySQL (see [docs](https://dev.mysql.com/doc/refman/9.0/en/grant.html#grant-column-privileges)). To be precise, we are using MariaDB for that.

A grant for a column looks something like that:

```sql
GRANT SELECT (id, value) on table_name.column_name to 'user'@'localhost';
```

As of writing, you cannot run wildcard selects with those grants such as

```sql
SELECT * FROM table_name;
```

will fail with an error

```sql
ERROR 1142 (42000): SELECT command denied to user 'user'@'localhost' for table `database_name`.`table_name`
```

This is the same error that i currently get from Sequel Ace when trying to select those tables with limited privileges.

With such a grant, column names have to be retrieved via

```sql
SHOW COLUMNS FROM table_name;
```

To then create the correct select that will not fail

```sql
SELECT id, value FROM table_name;
```

As i don't see this behavior as a bug in Sequel Ace, i'd like to request this as a feature. I don't know what a recommended way for an implementation could be. This feature would require the application to always pull the grants first and then create selects based on that knowledge. The additional call could have an impact on users that don't use such details grants. So a minimal viable solution for me would be to have a setting that allows checking the grants first.

I hope i could explain my feature wish. If not, let me know ;)

**Comment by Jason-Morcos** [comment]
SPTableContent.m and particularly dataColumns are gonna be the items of concern here.

To start, can you share the results of `SHOW CREATE TABLE table_name`?
Under the hood, Ace is using SHOW CREATE TABLE and not SHOW COLUMNS. Don't see a reason we couldn't switch, except that it would take some refactoring to do so.
I'm curious if the columns are hidden in the create statement, or if the statement does something else entirely

**Comment by Jason-Morcos** [comment]
Additionally, can you confirm in the Sequel Ace console that the query being run is indeed a select *? Just to make sure we're on the right track here

**Comment by kevin-kortum-trustedshops** [comment]
> Additionally, can you confirm in the Sequel Ace console (View->Show Console) that the query being run is indeed a select *? Just to make sure we're on the right track here. It's also possible that Ace is spelling out columns that are blocked, not just doing a *

Hi Jason,

Sorry for the confusion. This was just the result of our internal analysis and was not specified for Sequel Ace. I did not consider any other issue here yet.

The `SELECT *` statement actually happened in another context. You are totally right, Sequel Ace does do `SHOW TABLE STATUS LIKE table_name` and `SHOW CREATE TABLE database_name.table_name`.

The actual error then is
```
MySQL said: SHOW command denied to user 'user'@'localhost' for table `database_name`.`table_name`
```

Also, the 'localhost' value for the user is just an example. In my case it spells the ip address. Wanted to mention this, as you could consider other issues here.

Thanks for the feedback. I will give you as many information as i can.

**Comment by Jason-Morcos** [comment]
Interesting, thank you for digging! Can you tell what permission exactly is needed for `SHOW CREATE TABLE` to work?
Indeed it's unfortunately nearly impossible for Sequel Ace to work _without_ `SHOW CREATE TABLE` access (since this is needed to understand and render the table across all the different tabs). I agree unfortunately that this might be too niche a case to broadly support, nor am I sure _how_ we could support it
