### ISSUE TITLE
Can't connect to MAMP mysql through localhost socket

### ISSUE THREAD

**Issue by eablokker** [Sequel-Ace/Sequel-Ace#214]
- Sequel Ace Version: 2.1.2
- macOS Version: 10.13.6
- MySQL Version: 5.7.26
- MAMP Version: MAMP Pro 5.7

**Description**
Can't connect to localhost MAMP mysql through socket, even when manually setting the socket to `/Applications/MAMP/tmp/mysql/mysql.sock`.

`MySQL said: Can't connect to local MySQL server through socket '/Applications/MAMP/tmp/mysql/mysql.sock' (1)`

Works normally in Sequel Pro with and without socket set manually. Exact same connection settings used in Sequel Pro and Sequel Ace.

**Steps To Reproduce**
1. Create new connection
2. Select Socket tab
3. Enter username and password
4. Have MAMP running with mysql enabled
5. Click Connect or Test connection

**Expected Behaviour**
Should connect to the database without any error message. Sequel Pro connects without error using same settings.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Probably since this version was released only 1 hour ago. Issue present in previous version too.

**Additional Context**
![Screen Shot 2020-07-11 at 12 06 18 PM](https://user-images.githubusercontent.com/2616961/87231793-fdcb4f00-c36e-11ea-80d6-c66efa4d3a2d.png)
![Screen Shot 2020-07-11 at 12 05 44 PM](https://user-images.githubusercontent.com/2616961/87231801-07ed4d80-c36f-11ea-8b68-7095eca989d4.png)

**Comment by Jason-Morcos** [comment]
Unfortunately, duplicates #113. We're waiting on a reply from Apple on how to use sockets via Sandboxed apps (App Store apps). So far, we have been unable to find a workaround.
Currently _all_ socket connections are being blocked by the sandbox.

**Comment by eablokker** [comment]
Ohh, thank you! I did search for that issue and didn't find it.
