### ISSUE TITLE
Make text change from MySQL vs MariaDB when connecting to MariaDB instances

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#215]
As of MariaDB 10.5, as far as I know it is a complete different product than MySQL, although it is build on the same base.
While connecting to MariaDB I see references to MySQL in Sequel Ace (in settings (host) and also "mysql connecting...")

It would be a nice touch to somehow change this to MariaDB.

**Comment by Jason-Morcos** [comment]
This request seems pretty nitpicky but I can leave this issue out there in case someone wants to knock it out. You said it, MariaDB is built on the same base. Need we really specify which specify MySQL variant you are connecting to every time? Just seems incredibly low priority compared to existing bugs or other desired features.
