### ISSUE TITLE
Restore connections after update

### ISSUE THREAD

**Issue by stychos** [Sequel-Ace/Sequel-Ace#217]
Would be great to have a possibility to restore all opened connections and queries windows contents after Sequel Ace update, crash, and, may be, on quit.

I am keeping Sequel Ace opened for days with a dozens of tabs, and it's not very comfortable to reopen everything after the MAS update.

I think the best example of this behaviour can be seen in Sublime Text.

**Comment by erikbaan** [comment]
I would be extremely happy with this feature!

**Comment by erikbaan** [comment]
Please re-open this.. This would be a major improvement

**Comment by Jason-Morcos** [comment]
I'll leave it open but it's not a high priority at this time until we can resolve other issues with Ace and complete a broader restructure of the inner workings.
