### ISSUE TITLE
Revert Icon Changes

### ISSUE THREAD

**Issue by Sylk** [Sequel-Ace/Sequel-Ace#220]
I would like to propose a revert of the icon. I don't particularly enjoy the red/white coloring, and I prefer the original icon that it had.

**Comment by Jason-Morcos** [comment]
@Sylk You can replace the icon on your local machine (https://support.apple.com/guide/mac-help/create-custom-icons-files-folders-mac-mchlp2313/mac), but I think it's unlikely we revert the icon nor change it anytime soon. The response to the new icon has been overwhelmingly positive.
Is it the color combo that you don't like? The original icon was the same colors - red, white, and black.

**Comment by Sylk** [comment]
I just prefer the circular icons, as I feel they feel more IOS based.

If they icon were a bit larger, I may have no complaints as well, it may just feel a bit short?

**Comment by Jason-Morcos** [comment]
Ahh, currently we're following the new Big Sur templates for macOS 11. Most icons will change how they look pretty soon to be the same shape we are now.
About the size, I believe it is correct for Big Sur. When the os comes out if the icon still looks small we can tweak the size!

**Comment by Sylk** [comment]
@Jason-Morcos thanks for the context, much appreciated. Was not aware of such a thing. Sorry for looking like a fool.
