### ISSUE TITLE
(Cosmetic) Margins in left sidebar are too thin

### ISSUE THREAD

**Issue by samuelbradshaw** [Sequel-Ace/Sequel-Ace#229]
- Sequel Ace Version: 2.1.2
- macOS Version: 10.15.5 (Catalina)
- MySQL Version: 5.7.30

**Description**
The margins on the sides of icons and text in the sidebar are thinner than I would expect.

**Steps To Reproduce**
1. Open a new connection window, without connecting.
2. Add a folder under Favorites.
3. Note the margin to the right of the folder icon, in the sidebar.

OR

1. Connect to a database.
2. Note the margins to the left and right of each table icon, and to the left of the "Tables" header, in the sidebar.

**Expected Behaviour**
Margins should be similar to margins in Finder.

**Actual Behaviour**
Margins are thinner than expected. See screenshots.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, tested in 2.1.3 Release Candidate 1.

<img width="125" alt="Screen Shot 2020-07-14 at 8 59 45 PM" src="https://user-images.githubusercontent.com/7323052/87498731-bc100200-c615-11ea-9ebd-a2cc5d1d0f64.png">
<img width="226" alt="Screen Shot 2020-07-14 at 8 55 34 PM" src="https://user-images.githubusercontent.com/7323052/87498750-c500d380-c615-11ea-8de6-15b019bd590e.png">

**Comment by Kaspik** [comment]
We made a lot of changes, although this might not have been fixed. I'll close it anyways as I don§t think anyone will be looking at this specifically until we rewrite the table list itself...
