### ISSUE TITLE
Improve SQL Formatter

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#23]
The current SQL formatter bundle now at least works, but it doesn't inject the formatted SQL string back into the editor.
At the very least, the formatted SQL string should be injected back into the editor.

Better yet, we should consider implementing local formatting of the SQL string that doesn't require access to the internet (perhaps via python) both for security purposes and for allowing offline development with a local DB.

It may make sense to make SQL formatting a built in true function of Sequel Ace and no longer a default bundle.

**Comment by rowanbeentje** [comment]
I think SP was hoping to do a built-in implementation at some point, but years ago there didn't seem to be a nice library we could use. Things have hopefully changed!

**Comment by jamesstout** [comment]
> At the very least, the formatted SQL string should be injected back into the editor.
> 

Tried this out and all you need to do is change `showashtml` to `replaceselection `

```xml
<key>output</key>
<string>replaceselection</string>
```

in https://github.com/Sequel-Ace/Sequel-Ace/blob/82584856e5f9d959253220606678a1df6e898086/SharedSupport/Default%20Bundles/Format%20SQL.spBundle/command.plist#L45-L46

**Comment by jamesstout** [comment]
> Better yet, we should consider implementing local formatting of the SQL string that doesn't require access to the internet (perhaps via python) both for security purposes and for allowing offline development with a local DB.

[poor-mans-t-sql-formatter-npm-cli](https://github.com/TaoK/poor-mans-t-sql-formatter-npm-cli) works quite well on basic SQL I tested, but two issues with it:

1. User needs `node` installed, and `npm`
2. It's for T-SQL, so complex MySQL might not get formatted properly.

**Comment by jamesstout** [comment]
poor man's formatter:

```sql
UPDATE IGNORE PushRegos,
	PushRegos_copy
SET `PushRegos`.`deviceToken` = `PushRegos_copy`.`deviceToken`
FROM `PushRegos_copy`
INNER JOIN PushRegos ON PushRegos_copy.deviceToken LIKE CONCAT (
		PushRegos.deviceToken,
		'%'
		)
	AND LENGTH(PushRegos.deviceToken) < 64;
```

```sql
INSERT IGNORE
INTO warningsHist
VALUES (
	15,
	"Strong Monsoon Signal ( 11:20 HKT - 25.06.2012 )",
	now(),
	NULL,
	NULL
	);

```
sqlformat.org formatter:

```sql
UPDATE
IGNORE PushRegos,
       PushRegos_copy
SET `PushRegos`.`deviceToken` = `PushRegos_copy`.`deviceToken`
FROM `PushRegos_copy`
INNER JOIN PushRegos ON PushRegos_copy.deviceToken LIKE CONCAT(PushRegos.deviceToken, '%')
and LENGTH(PushRegos.deviceToken) < 64;
```

```sql
INSERT
IGNORE INTO warningsHist
values (15,"Strong Monsoon Signal ( 11:20 HKT - 25.06.2012 )", now(), NULL, NULL)
```

I think I prefer sqlformat.org.

**Comment by Jason-Morcos** [comment]
I prefer sqlformatter.org too!

Could also look into bundling the app with python (unless we can still use system python from the sandbox? That would be better) and using a package to parse locally, like mentioned here. https://github.com/sequelpro/sequelpro/issues/1988#issuecomment-413791571

**Comment by Jason-Morcos** [comment]
> > At the very least, the formatted SQL string should be injected back into the editor.
> 
> Tried this out and all you need to do is change `showashtml` to `replaceselection `
> 
> ```
> <key>output</key>
> <string>replaceselection</string>
> ```
> 
> in
> 
> https://github.com/Sequel-Ace/Sequel-Ace/blob/82584856e5f9d959253220606678a1df6e898086/SharedSupport/Default%20Bundles/Format%20SQL.spBundle/command.plist#L45-L46

Cool!
There may be an issue with the default bundle updater too because when I made this change in the default bundle, for me at least it wasn't automatically copied over into my user's copy of the bundle.

**Comment by jamesstout** [comment]
> Could also look into bundling the app with python (unless we can still use system python from the sandbox?

The bundles run system php, ruby and bash somehow from the sandbox. 

https://github.com/Sequel-Ace/Sequel-Ace/blob/56c5a55cf3a79e20906835307961abfc82fa2a34/Source/SPBundleCommandRunner.m#L101-L102
