### ISSUE TITLE
Importing new rows to a table shouldn't give a warning

### ISSUE THREAD

**Issue by samuelbradshaw** [Sequel-Ace/Sequel-Ace#230]
- Sequel Ace Version: 2.1.2
- macOS Version: 10.15.5 (Catalina)
- MySQL Version: 5.7.30

**Description**
When I attempt to import new data from a CSV into my database, I get a warning about potentially overwriting data. I don't think there's any way that data could be overwritten when importing a CSV.

**Steps To Reproduce**
1. Connect to a database with one or more tables. Open one of the tables.
2. Create a CSV file with a few rows, with header names that match a few of the columns in your table.
3. Go to File > Import…
4. Choose the CSV file you created (if needed, select "CSV" as the format) then click "Open."

**Expected Behaviour**
Popup with options for mapping the CSV columns to MySQL columns should appear.

**Actual Behaviour**
Warning appears about data potentially being overwritten. See screenshot. (After choosing "Yes, continue anyway," everything works fine as it previously did.)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, tested in 2.1.3 Release Candidate 1. This is new to Sequel Ace (it didn't happen in Sequel Pro).

<img width="1087" alt="Screen Shot 2020-07-14 at 9 07 43 PM" src="https://user-images.githubusercontent.com/7323052/87499330-40af5000-c617-11ea-9c57-141f68c41bdd.png">

**Comment by Jason-Morcos** [comment]
This popup was intentionally added as a warning anytime anyone imports anything. I'm not opposed to turning it off for CSV imports, however, this is fairly low priority issue as it's just an extra safety warning.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by samuelbradshaw** [comment]
Works great! Thanks!
