### ISSUE TITLE
Dynamic font size in table listing and structure

### ISSUE THREAD

**Issue by rollscia** [Sequel-Ace/Sequel-Ace#233]
My compliments for the good job you made with the release of Sequel Ace. I am an old developer, therefore my eyes are not as good as once. I found settings to adjust fonts for content and queries, but not for tables listing and structure. Would be nice to have the possibility to manage also those.

Raul Tabasso
Rome, Italy

**Comment by Kaspik** [comment]
We are just about to release new version with bigger font that moght ajust to the system too, let's see :)

**Comment by rollscia** [comment]
Great,
thank you 💪

Raul

**Comment by Jason-Morcos** [comment]
@rollscia The new release will be 2.1.3 which currently has a beta available for download! Can you check if the font size adjusts like you would like it to in 2.1.3 beta?

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by rollscia** [comment]
I can see "2.1.3 Release Candidate 1” or "2.1.4 Beta 1”.
Which one?

**Comment by Kaspik** [comment]
Doesn't matter :) But it probably won't work and I might need to take a look that.

**Comment by rollscia** [comment]
Hello Jason,
I am running version 2.1.4 but I still don’t see the options to adjust fonts in tables listing and structure.

Raul Tabasso
Tabasoft
Rome, Italy

**Comment by Kaspik** [comment]
We made some changes but this one is not there yet, sorry for that, I'll try to do it over the weekend. :)

**Comment by rollscia** [comment]
Great Jakub 💪

Raul

**Comment by wlkns** [comment]
Don't mean to revive a dead issue but has this been implemented yet? I'm running 2.2.2 and the table list font still looks relatively small to me and does not match the font configured for the table content/data.

**Comment by Kaspik** [comment]
Not yet, sorry!

**Comment by Kaspik** [comment]
Sorry it took so long, I made bigger changes altogether.

Whole app has been rewritten to use selected font from preferences. This will apply to favorites, tables list, content, structure, indexes, and everything else. You will find this settings in Preferences of Sequel Ace in upcoming version 2.3.0.

I hope it will help ya! :)

**Comment by wlkns** [comment]
Not to worry - it just wasn't clear in your last message whether it was tough luck or coming soon, lol.

Oh la la - sounds excellent, thank you.

**Comment by Jason-Morcos** [comment]
Included in 2.3.0 release

**Comment by wlkns** [comment]
Thanks!
