### ISSUE TITLE
Some Documentation Links still reference Sequel Pro's website

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#24]
- We need to create MVP similar documentation in the /docs folder for GitHub Pages and update the links in the app to reference this new documentation

**Comment by stychos** [comment]
Hello! Glad to see this project is in proper hands now. I am terrible programmer but can try to help with this if no one is working on it already.

**Comment by Jason-Morcos** [comment]
Hey @stychos! Working on documentation would be awesome! I don't think any of us have tried to figure out github pages, but it is setup to use the /docs folder and be live. Documentation will certainly be crucial to the longterm success of Sequel Ace.

**Comment by stychos** [comment]
I haven't tried it yet too, but don't think it's impossible. Ok, I will play around this and will return with my thoughts / commits on it.

**Comment by Jason-Morcos** [comment]
Note: Will need to change all kinds of links to point at https://sequel-ace.com

**Comment by AstroBoy269** [comment]
Hey @stychos, I'm in the same boat as you.  This isn't the kind of development I do either.  But I can help with the Docs.  If there's some pages you want me to help with, please don't hesitate to let me know.  I don't want to blindly jump in the middle of the stuff you've already got going.

**Comment by stychos** [comment]
@Jason-Morcos noted, will continue with this in few hours.

**Comment by stychos** [comment]
Hi @AstroBoy269 let me finish with the basics to allow v. 2.1.0 launch. I'll try to do that by tomorrow. Then I can form a list of missing things and pass you maintaining on this. I am doing it very basic way, just in .md files － maybe you can dig deeper and make us good template with Jekyll in future?

**Comment by Jason-Morcos** [comment]
The are the links from the app that will need to be switched to our documentation!:

```#define SPLOCALIZEDURL_HOMEPAGE            NSLocalizedString(@"https://sequel-ace.com/", @"Localized home page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_FAQ                 NSLocalizedString(@"https://www.sequelpro.com/docs/Frequently_Asked_Questions", @"Localized help page for Frequently Asked Questions - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_DOCUMENTATION       NSLocalizedString(@"https://www.sequelpro.com/docs/", @"Localized documentation home page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_CONTACT             NSLocalizedString(@"https://www.sequelpro.com/docs/Contact_the_developers", @"Localized contact page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_KEYBOARDSHORTCUTS   NSLocalizedString(@"https://www.sequelpro.com/docs/Keyboard_Shortcuts", @"Localized keyboard shortcuts page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_CONNECTIONHELP      NSLocalizedString(@"https://www.sequelpro.com/docs/category/getting-connected/", @"Localized connection help page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_BUNDLEEDITORHELP    NSLocalizedString(@"https://www.sequelpro.com/bundles/reference/", @"Localized help page for bundle editor - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_CONTENTFILTERHELP   NSLocalizedString(@"https://www.sequelpro.com/docs/Content_Filters", @"Localized help page for content filter - do not localize if no translated webpage is available")```

**Comment by unbreak** [comment]
Here: https://sequel-ace.com/ref/features.html i can read: 

> The connections strings are stored in the following preference file:
> 
> ~/Library/Preferences/com.sequelpro.SequelPro.plist

**Comment by stychos** [comment]
@AstroBoy269 I have some IRL troubles for the nearest days, and it's already been merged what I've done for now. It's all yours now!

**Comment by stychos** [comment]
> The are the links from the app that will need to be switched to our documentation!:
> 
> ```
> #define SPLOCALIZEDURL_FAQ                 NSLocalizedString(@"https://www.sequelpro.com/docs/Frequently_Asked_Questions", @"Localized help page for Frequently Asked Questions - do not localize if no translated webpage is available")
> #define SPLOCALIZEDURL_DOCUMENTATION       NSLocalizedString(@"https://www.sequelpro.com/docs/", @"Localized documentation home page - do not localize if no translated webpage is available")
> #define SPLOCALIZEDURL_CONTACT             NSLocalizedString(@"https://www.sequelpro.com/docs/Contact_the_developers", @"Localized contact page - do not localize if no translated webpage is available")
> #define SPLOCALIZEDURL_KEYBOARDSHORTCUTS   NSLocalizedString(@"https://www.sequelpro.com/docs/Keyboard_Shortcuts", @"Localized keyboard shortcuts page - do not localize if no translated webpage is available")
> #define SPLOCALIZEDURL_CONNECTIONHELP      NSLocalizedString(@"https://www.sequelpro.com/docs/category/getting-connected/", @"Localized connection help page - do not localize if no translated webpage is available")
> #define SPLOCALIZEDURL_BUNDLEEDITORHELP    NSLocalizedString(@"https://www.sequelpro.com/bundles/reference/", @"Localized help page for bundle editor - do not localize if no translated webpage is available")
> #define SPLOCALIZEDURL_CONTENTFILTERHELP   NSLocalizedString(@"https://www.sequelpro.com/docs/Content_Filters", @"Localized help page for content filter - do not localize if no translated webpage is available")
> ```

I propose these replacements:

```
// Predefined localisable URLs
#define SPLOCALIZEDURL_HOMEPAGE            NSLocalizedString(@"https://sequel-ace.com/", @"Localized home page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_FAQ                 NSLocalizedString(@"https://sequel-ace.com/get-started/", @"Localized help page for Frequently Asked Questions - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_DOCUMENTATION       NSLocalizedString(@"https://sequel-ace.com/", @"Localized documentation home page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_CONTACT             NSLocalizedString(@"https://github.com/Sequel-Ace/Sequel-Ace/issues", @"Localized contact page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_KEYBOARDSHORTCUTS   NSLocalizedString(@"https://sequel-ace.com/shortcuts.html", @"Localized keyboard shortcuts page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_CONNECTIONHELP      NSLocalizedString(@"https://sequel-ace.com/get-started/", @"Localized connection help page - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_BUNDLEEDITORHELP    NSLocalizedString(@"https://sequel-ace.com/ref/", @"Localized help page for bundle editor - do not localize if no translated webpage is available")
#define SPLOCALIZEDURL_CONTENTFILTERHELP   NSLocalizedString(@"https://sequel-ace.com/filter/", @"Localized help page for content filter - do not localize if no translated webpage is available")
```

Last one haven't live link yet, but original one haven't it too :)

**Comment by Jason-Morcos** [comment]
@stychos Dev branch (And latest beta) should have the right links! Do you want to make issues for key remaining documentation things (notably the SPLOCALIZEDURL_CONTENTFILTERHELP link that doesn't exist yet)? We could put them in a new project.

Then we could close out this issue woot woot!

**Comment by stychos** [comment]
I think that's a cool idea. Especially, because now I still have big timing troubles. Going to create them.
