### ISSUE TITLE
Ssh connection failed

### ISSUE THREAD

**Issue by appaydin** [Sequel-Ace/Sequel-Ace#240]
- Sequel Ace Version: 2.1.2
- macOS Version: 10.15.5
- MySQL Version: 5.7

**Description**
We started the [Pritunl](https://pritunl.com/) ssh application. No problem with SequelPRO beta. But in this application he constantly asks for a password.

**Comment by Jason-Morcos** [comment]
Are you unable to connect or are you prompted for your password every time you connect? Are you prompted for your ssh password or your user macOS user account password?

**Comment by appaydin** [comment]
We load SSH keys with [this](https://docs.pritunl.com/docs/ssh-client#macos) application.

**Comment by Jason-Morcos** [comment]
I'm sorry, I'm having trouble understanding what you're saying. Would you be able to provide screenshots of your setup in Sequel Ace and the popup you're getting?

**Comment by Jason-Morcos** [comment]
Sequel Ace is a sandboxed app. If you'd like to use an ssh key, you'll need to select it from Sequel Ace. It cannot crawl the filesystem for keys that may be applicable.
This page may be helpful if you'd like to try to use a custom ssh config file. https://sequel-ace.com/get-started/

**Comment by appaydin** [comment]
<img width="1440" alt="Ekran Resmi 2020-07-15 21 47 00" src="https://user-images.githubusercontent.com/8649070/87584755-a3bbe800-c6e6-11ea-8ecb-7b2615ce9ea8.png">
<img width="1440" alt="Ekran Resmi 2020-07-15 21 48 50" src="https://user-images.githubusercontent.com/8649070/87584769-aa4a5f80-c6e6-11ea-9eea-3ed5a35c055a.png">
<img width="801" alt="Ekran Resmi 2020-07-15 21 50 07" src="https://user-images.githubusercontent.com/8649070/87584783-b0404080-c6e6-11ea-801e-597b4f39c752.png">
<img width="1440" alt="Ekran Resmi 2020-07-15 21 56 29" src="https://user-images.githubusercontent.com/8649070/87584791-b504f480-c6e6-11ea-9a8c-9181253b2929.png">

**Comment by Jason-Morcos** [comment]
I see you have granted Sequel Ace access to the key, but haven't told it to use the key to connect. On the Connection settings where it says "SSH Password", click the key icon to the right and navigate to and select your ssh key. Then it should work.

**Comment by appaydin** [comment]
> I see you have granted Sequel Ace access to the key, but haven't told it to use the key to connect. On the Connection settings where it says "SSH Password", click the key icon to the right and navigate to and select your ssh key. Then it should work.

Thank you. It worked that way.

**Comment by benlind** [comment]
I went into Preferences > Network > SSH Config > Other file... and selected my ~/.ssh/config file.
