### ISSUE TITLE
Put caret in textfield after selecting filter in dropdown list

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#241]
A small but very useful change would be to put the caret (focus) automatically in the text/formfield after selecting a filter.
Most of the time I select a table and then a filter, but the focus is still on the selection of the table.  

<img width="785" alt="Screenshot 2020-07-16 at 08 39 40" src="https://user-images.githubusercontent.com/25279400/87635770-e827a200-c73f-11ea-84b2-649b5a1ca957.png">

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by cappadaan** [comment]
The focus on selection works as expected! Maybe it could be useful to also set the focus on the first active filter while selecting a table, but I am not sure about that.
