### ISSUE TITLE
When change username do not clear the password

### ISSUE THREAD

**Issue by RicardoRamirezR** [Sequel-Ace/Sequel-Ace#246]
Good to see you work here, congrats!

In Sequel Pro when I have a connection saved, If the username is changed the password is kept.

In Sequel Ace when I have a connection saved, If the username is changed the password cleared.

If is possible to have the same behavior in Sequel Ace?

Thank you!

**Comment by Jason-Morcos** [comment]
Hey there, @RicardoRamirezR, we made this change on purpose. That way if you have a DB with two accounts with the same password (a root and non-root account), you can't just change the username and hit connect. This is a purposeful security improvement!

**Comment by RicardoRamirezR** [comment]
Can we have an option to disable it, or per connection? I have quite a lot of  users with the same password. Thank you!

**Comment by Jason-Morcos** [comment]
That's got some pretty big security implications. For instance, what would keep me from flipping that option to true, changing the username and boom logged in. I don't really like weakening security restrictions once implemented. Perhaps you could create a connection for each of your users? Why frequently change which user you use to login to a database?

**Comment by RicardoRamirezR** [comment]
Understood.

> Perhaps you could create a connection for each of your users? 
There are quite a few...

> Why frequently change which user you use to login to a database?
We support our customers and we use the username as a tenant identification
