### ISSUE TITLE
Horizontal scrolls resets after sorting column in content view table

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#250]
It happens the content view of a table with al lot of columns.
If you scroll horizontally (because there are too many columns for the screens width) to the last column, and then sort the last column, the horizontal scroll resets to the initial position (first column).

If possible, the horizontal scroll position should be kept while sorting columns in a table.

**Comment by Jason-Morcos** [comment]
Duplicate of #163
