### ISSUE TITLE
SSH connection failed!

### ISSUE THREAD

**Issue by augusl** [Sequel-Ace/Sequel-Ace#251]
- Sequel Ace Version:2.1.4
- macOS Version:10.15.6
- MySQL Version:5.7

**Description**
SSH connection failed!

The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.

![CleanShot2020-07-17at16.28.30@2x1](https://cdn.jsdelivr.net/gh/augusl/oss@master/CleanShot%202020-07-17%20at%2016.28.30@2x1.png)
![CleanShot2020-07-17at16.35.32@2x](https://cdn.jsdelivr.net/gh/augusl/oss@master/CleanShot%202020-07-17%20at%2016.35.32@2x.png)
![CleanShot2020-07-17at16.36.50@2x](https://cdn.jsdelivr.net/gh/augusl/oss@master/CleanShot%202020-07-17%20at%2016.36.50@2x.png)
![CleanShot2020-07-17at16.38.03@2x](https://cdn.jsdelivr.net/gh/augusl/oss@master/CleanShot%202020-07-17%20at%2016.38.03@2x.png)
**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Please try the [latest beta](https://github.com/Sequel-Ace/Sequel-Ace/releases). If the latest beta works, we've fixed the issue already and will get the fix out soon.

**Additional Context**

**Comment by Jason-Morcos** [comment]
A couple things - 
1. Please include actual textual description of your issue. It's tough to follow just screenshots.
2. As far as I know, you cannot use .pem files for ssh keys, these are for ssl. So I believe you have selected the wrong private key.
3. However, that message in the full log "permission for ... are too open" is an important one. If the key you're trying to use is too opened up, ssh will not allow you to use it. So to fix that kind of issue, you use chmod. However, like I said, I think you've selected the wrong key.

**Comment by augusl** [comment]
> A couple things -
> 
> 1. Please include actual textual description of your issue. It's tough to follow just screenshots.
> 2. As far as I know, you cannot use .pem files for ssh keys, these are for ssl. So I believe you have selected the wrong private key.
> 3. However, that message in the full log "permission for ... are too open" is an important one. If the key you're trying to use is too opened up, ssh will not allow you to use it. So to fix that kind of issue, you use chmod. However, like I said, I think you've selected the wrong key.

No problem with SequelPRO, And Tableplus. I always use it like this
![CleanShot2020-07-17at21.11.50@2x](https://cdn.jsdelivr.net/gh/augusl/oss@master/CleanShot%202020-07-17%20at%2021.11.50@2x.png)

**Comment by Jason-Morcos** [comment]
Sequel Pro and Table plus are _not_ sandboxed - they can just crawl your .ssh dir and try all the private keys there. Sequel Ace is sandboxed - we can't do that. Unfortunately, with Sequel Ace you have to explicitly sélect the correct private key. A private key should be similar to you id_rsa key, it shouldn't have .pem on the end.

**Comment by augusl** [comment]
> Sequel Pro and Table plus are _not_ sandboxed - they can just crawl your .ssh dir and try all the private keys there. Sequel Ace is sandboxed - we can't do that. Unfortunately, with Sequel Ace you have to explicitly sélect the correct private key. A private key should be similar to you id_rsa key, it shouldn't have .pem on the end.

ok,Thank you, I try

**Comment by stychos** [comment]
If that's Amazon's "pem" then it's fine to connect with them (those are the private keys). But _"permission for ... are too open"_ trouble must be fixed, otherwise ssh won't connect, try to use this command: `chmod -R 600 ~/.ssh/*pem`

**Comment by augusl** [comment]
> If that's Amazon's "pem" then it's fine to connect with them (those are the private keys). But _"permission for ... are too open"_ trouble must be fixed, otherwise ssh won't connect, try to use this command: `chmod -R 600 ~/.ssh/*pem`
> And don't forget to select the exact private key for the needed host.

thank you very much,is this problem

**Comment by augusl** [comment]
> If that's Amazon's "pem" then it's fine to connect with them (those are the private keys). But _"permission for ... are too open"_ trouble must be fixed, otherwise ssh won't connect, try to use this command: `chmod -R 600 ~/.ssh/*pem`
> And don't forget to select the exact private key for the needed host.

Thank you very much, the problem is solved with your method👍
