### ISSUE TITLE
Allow symlinks for Favorites.plist

### ISSUE THREAD

**Issue by Muffinman** [Sequel-Ace/Sequel-Ace#252]
In Sequel Pro I was always able to symlink the `Favorites.plist`to a file in my Dropbox account, this let me keep all my devices in sync with each other.

It seems that in Sequel Ace this function no longer works:

## With Symlink

![Screen Shot 2020-07-17 at 11 14 43](https://user-images.githubusercontent.com/1319568/87775905-c0f3d200-c81e-11ea-9bb7-9f52faa000ab.png)

![Screen Shot 2020-07-17 at 11 15 08](https://user-images.githubusercontent.com/1319568/87775934-c9e4a380-c81e-11ea-827b-e4fdf2ca8283.png)

## With regular file or Hardlink

![Screen Shot 2020-07-17 at 11 17 08](https://user-images.githubusercontent.com/1319568/87776081-14662000-c81f-11ea-92b8-31e28b64ad8c.png)

![Screen Shot 2020-07-17 at 11 16 42](https://user-images.githubusercontent.com/1319568/87776202-4f685380-c81f-11ea-886c-d937122cc9b9.png)

I think hardlinks will work for my case, since my Dropbox directory is on the same filesystem. But it would be nice to have the clarity of a symlink, being able to quickly see that the favourites file is linked to my Dropbox with the `ls` command.

Is allowing symlinks easy / possible?

**Comment by Jason-Morcos** [comment]
I think you're correct that this is a limitation of the sandbox. The one thing you could try is setting up the symlink and then going to the files tab of Sequel Ace's preferences and adding the location of the original file (Dropbox) to the list of granted files (giving the app access to the real file). That may or may not work, but if it doesn't work there's probably no chance of making it work within the sandbox.

**Comment by Jason-Morcos** [comment]
I'm going to close this issue in favor of #53, but let us know if granting Sequel Ace access to the file makes it work!

**Comment by Muffinman** [comment]
It didn't work :) I shall await cloud sync.
