### ISSUE TITLE
Esc key should close and remove all filters

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#258]
Like it does in Safari!
Cmd+F shows the filters, but (as far as I know) there's no keyboard shortcut to dismiss them. Esc is what Safari uses

**Comment by samuelbradshaw** [comment]
I never thought of the filters being equivalent to the Find on Page in Safari, but I guess it makes sense. It'd be awesome if there were a filter that behaved a little more like Find on Page, looking for a match in any column, instead of having to specify a column to filter on.

**Comment by stychos** [comment]
I don't like an idea to have different "Find on a page" and "Filters" things, like in some other SQL apps. It's very confusing for me. Maybe the exit here is to highlight matched columns in the result table?

**Comment by samuelbradshaw** [comment]
> I don't like an idea to have different "Find on a page" and "Filters" things, like in some other SQL apps. It's very confusing for me. Maybe the exit here is to highlight matched columns in the result table?

What I'm picturing is an "[Any Column]" option as the first item in the list of columns in our current filter UI.

**Comment by Jason-Morcos** [comment]
> What I'm picturing is an "[Any Column]" option as the first item in the list of columns, in our current filter UI. After you run the filter, it would only show the matching rows, the same way it does today.

How would that actually work though? Is there a MySQL magic thing to search the whole table? You definitely wouldn't be able to use some index. I'm not worried about the UI, how would this actually work from a SQL perspective?
Current filters are basically MySQL WHERE clauses, often WHERE LIKE clauses. I guess technically you could search every column by going column by column and concatenating OR WHERE LIKE clauses but that seems like horrific performance.

**Comment by samuelbradshaw** [comment]
Here are a couple of potential ways:

`WHERE (field1 = 'test' OR field2 = 'test' OR field3 = 'test')`

`WHERE CONCAT_WS('   ', field1, field2, field3) = 'test'`

I'm not sure what performance would be like.

**Comment by Jason-Morcos** [comment]
If we do want to keep discussing this, this should be a different issue probably. This issue is specifically about the _small_ task of making the esc key close the filters! :)

**Comment by samuelbradshaw** [comment]
You're right, sorry. :)

**Comment by samuelbradshaw** [comment]
Thanks – discussion on a filter for all columns moved to #260.
