### ISSUE TITLE
Provide a filter that searches all columns

### ISSUE THREAD

**Issue by samuelbradshaw** [Sequel-Ace/Sequel-Ace#260]
It would be great if there were a way to find a value in any column using Sequel Ace's table filter.

What I'm picturing is an "(Any Column)" option as the first item in the list of columns, in our current filter UI. After you run the filter, it would show the rows that contain a match in any column.

Here are a few potential ways this could be done (for the simple case of `=`):

`SELECT * FROM table WHERE (field1 = 'test' OR field2 = 'test' OR field3 = 'test')`

`SELECT * FROM table WHERE CONCAT_WS('   ', '   ', field1, field2, field3, '   ') LIKE '%   test   %'`

`SELECT * FROM table WHERE 'test' IN (field1, field2, field3)`

I'm not sure what performance would be like, and some of the more complicated operators might need to be disabled when (Any Column) is chosen, depending on the solution.

**Comment by jamesstout** [comment]
You can use Table->Advanced Filter Content (or ⇧⌘F)

Enter a value in one of the columns, then select search all fields:

![Screenshot 2020-08-11 at 1 17 03 AM](https://user-images.githubusercontent.com/1576190/89811294-0a5ee500-db71-11ea-8ae8-3178ed00a25b.png)

**Comment by samuelbradshaw** [comment]
Wow, that's awesome! Thanks for pointing this out. It looks like a lot of the code is already here; it'd be great if it could be integrated into the regular filter bar. I also like the "Search while typing" option here.

By the way, is there any difference between "Table > Filter Content" and "Edit > Find > Find..."?

**Comment by jamesstout** [comment]
> "Edit > Find > Find..."?

This just activates or gives focus to the filter field on the content view:

```objc
/**
 * Allow Command-F to set the focus to the content view filter if that view is active
 */
- (void)performFindPanelAction:(id)sender
{
	[tableContentInstance makeContentFilterHaveFocus];
}
```

**Comment by Jason-Morcos** [comment]
Duplicates #152
