### ISSUE TITLE
Allow Specifying Custom Known Hosts file

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#261]
It would be great to either offer a selection for the known hosts file or automatically use ~/.ssh/known_hosts when access is allowed. It's not even possible to reference ~/.ssh/known_hosts in the config file because the shell parameter overrides it.

_Originally posted by @wedi in https://github.com/Sequel-Ace/Sequel-Ace/issues/156#issuecomment-661095328_

**Comment by Jason-Morcos** [comment]
Should be identical to the existing selector for SSH config and should leverage the same kind of logic

**Comment by wedi** [comment]
Keep alive ping.

Thanks for creating this ticket, @Jason-Morcos.

**Comment by mfehr94** [comment]
Ping
