### ISSUE TITLE
Timeout when reconnecting

### ISSUE THREAD

**Issue by christatedavies** [Sequel-Ace/Sequel-Ace#263]
- Sequel Ace Version: 2.1.3
- macOS Version: 10.15.5 (19F101)
- MySQL Version: 10.1.44-MariaDB-0ubuntu0.18.04.1

**Description**
Occasionally after I've left my Mac alone for a while, and its gone into sleep, or whatever, the SSH MySQL/MariaDB connection is dropped. And when it prompts me for the SSH password (I don't save them for security reasons) I cannot click in the input, or type. I just get the beachball of death. 

The only solution is to kill the Sequel Ace app, and restart it. Annoying when you've been working with large, unsaved queries. It would be handy if they auto saved as you typed.

**Steps To Reproduce**
It is difficult to reproduce. I think it probably has to be a long time asleep. I will test again tomorrow morning.

**Expected Behaviour**
I would expect to be able to enter the requested password

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Its been in all since I migrated from SequelPro

**Additional Context**
<img width="888" alt="myqlerror" src="https://user-images.githubusercontent.com/1114343/88036349-54891380-cb3b-11ea-8ab3-c9671ce21605.png">

**Comment by Jason-Morcos** [comment]
This sounds very frustrating! I haven't experienced this issue and am not sure how to go about forcibly trying to reproduce. Perhaps someone else on the @Sequel-Ace/all team has experienced this?

**Comment by christatedavies** [comment]
I've woken my Mac up this morning and I had left Sequel Ace connected. 

After reconnecting to my company OpenSSH VPN, I attempted to run a simple query (which I was able to type into the query text area) but when I pressed CMD+R to run it, I was prompted for the SSH password, which I entered. I was then prompted for it a second time, but this time I couldn't enter it.

I believe it is related to the sleeping nature of the Mac. However, there must be a Mac "real" sleep time, because if I sleep the Mac manually and re-awaken it straight away, it doesn't have these errors. But leaving it overnight, as far as I have noticed, shows the behaviour repeatedly.

Perhaps after an hour or so of sleeping, the Mac goes into a deep sleep?

I mean, I can live with it, but yeah its slightly frustrating. I guess I could change my habits and close Sequel Ace manually before shutting down for the day.

**Comment by Kaspik** [comment]
I think this has something to do with ARC and memory cleanup by Mac and because we are not yet ARC compatible, our memory handling is not perfect. Issues like this might and might not be related, so this will be hard to debug until we move the project infra to newer specs.

**Comment by Kaspik** [comment]
Can be please verified with 3.0.1?

**Comment by anonymous4argus** [comment]
@Kaspik Perhaps this is the same issue as https://github.com/sequelpro/sequelpro/issues/2503 
I requested a pull request there months ago after testing the fix in my mac.
https://github.com/sequelpro/sequelpro/pull/3736/commits/9825d60b2566d84d6761bae99a5ff99e4f97c9cd
