### ISSUE TITLE
Dock icon padding

### ISSUE THREAD

**Issue by pioz** [Sequel-Ace/Sequel-Ace#265]
- Sequel Ace Version: 2.1.4
- macOS Version: 10.15.5
- MySQL Version: 8.0

**Description**
The SequelAce dock icon has a padding that makes it appear smaller than it should be, as can be seen from the follow screenshot:
![screen](https://i.imgur.com/HYf5Jwo.png)

For me is quite annoying.

**Comment by Jason-Morcos** [comment]
The icon is designed to match the Big Sur macOS 11 look that will launch this fall.

@Kaspik, does the size look correct on Big Sur or is there too much padding there too?

**Comment by Kaspik** [comment]
<img width="984" alt="Screen Shot 2020-07-22 at 23 23 47" src="https://user-images.githubusercontent.com/7204168/88230289-6de0ab80-cc72-11ea-95cd-2d606ea0aa0c.png">

**Comment by samuelbradshaw** [comment]
I think the dark red background makes it look a little smaller than it is. Maybe it should be brightened a bit?

**Comment by Kaspik** [comment]
I'm pretty sure it matches as it should for Big Sur even tho other apps on @pioz screenshots have bigger icon - but the same will happen once Big Sur comes out - all these icons will be too big where Sequel Ace will be correct.

I would lean towards not doing anything here, it's not a big issue and it's about two months till BS release. :)

**Comment by Jason-Morcos** [comment]
I'm going to close this now, but I can assure you, @pioz, that we will be reviewing the icon (and the rest of the app) to ensure it looks right on Big Sur (and older OSes) in the coming months!
