### ISSUE TITLE
Selecting a column to filter/search by should auto focus the input field

### ISSUE THREAD

**Issue by bobber205** [Sequel-Ace/Sequel-Ace#266]
First I wanna say I love Sequel Ace! Great sequel (lol) to Pro.

I'm used to searching via columns to look at data, selecting the column name then typing/pasting my value. Currently ace does not focus the search field which I find really annoying.

I think it'd be great if it focused!

**Comment by Jason-Morcos** [comment]
Hey! Give the latest beta a try. I _believe_ we already did this and fixed in latest 2.1.5 beta!
https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by bobber205** [comment]
@Jason-Morcos Correct! I've downloaded that beta and it's working as intended <3

Closing.
