### ISSUE TITLE
Not Able to Connect to Our Production Server

### ISSUE THREAD

**Issue by bobber205** [Sequel-Ace/Sequel-Ace#267]
I'm having a really hard time coming up with a reason why this might be happening, if anyone has any ideas on info I could provide to help debug this I'm happy to do so but I'm at a lost.

Here's what I've been doing on my migration from Pro to Ace.

Export the connection detail for say my dev environment to a plist file on my desktop. There's no password in that file of course so once imported into Ace I go to my environment files and copy the password.

Works great.

Except for our production environment. I pasted the correct password, verified by importing the same file into Pro and pasting the password, and I get the following error.

```
Unable to connect to host URL-HERE, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: SSL connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Note: this isn't a timeout it happens immediately. Any ideas Ace community? Our dev and prod DBs were created around the same time and have the same security settings on amazon.

***Details***
OS X 10.15.5 (19F101)

**Comment by Jason-Morcos** [comment]
Perhaps this is the same as #190?

**Comment by Jason-Morcos** [comment]
Seems to be something funky about AWS RDS. Not sure if anyone else on the team is able to debug (@Sequel-Ace/all)

**Comment by gboudreau** [comment]
@bobber205 Could you show us the settings you are using to connect (screenshot of connection details)?
(You can blur the host/database/user names on your screenshot.)

Also:
- Do you connect directly to the hostname of your RDS database? Or do you go through a load balancer?
- What is the RDS database type, and version?

**Comment by gboudreau** [comment]
Are you connecting using the `rds-combined-ca-bundle.pem` file in the `CA Cert` field in Sequel Ace?
You can download this file here: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem

**Comment by bobber205** [comment]
@gboudreau I am not currently. 
I'll give that a try for sure but it'll be probably a week or so till I can get to it. (2nd son is being born today)

My staging database is RDS and I'm not having any issues with that though...

**Comment by bobber205** [comment]
@gboudreau I tried it and it didn't work (same error)

Do I did it right?

![image](https://user-images.githubusercontent.com/5841107/88954835-d53cc380-d24f-11ea-9a0b-074ab8843171.png)

**Comment by gboudreau** [comment]
> @gboudreau I tried it and it didn't work (same error)
> 
> Do I did it right?

Yes, this is how I connect to my RDS instances.

**Comment by bobber205** [comment]
@gboudreau What version are you using?

**Comment by gboudreau** [comment]
Aurora 1.x instances nowadays (~ MySQL 5.6.x equivalent).

Could you show us the settings you are using to connect (screenshot of connection details)?
(You can blur the host/database/user names on your screenshot.)

Also:
- Do you connect directly to the hostname of your RDS database? Or do you go through a load balancer (or the new RDS Proxy) ?
- What is the RDS database type, and version?

**Comment by bobber205** [comment]
@gboudreau Sorry for the delayed response. Today is my first day back from paternity leave. 

```
Engine version
5.6.34

Instance class
db.m3.xlarge
```

No load balancer.  Yes I connect directly to the hostname using username/password.


![image](https://user-images.githubusercontent.com/5841107/89808343-dcd15780-daee-11ea-8971-9d50faaf15a3.png)
