### ISSUE TITLE
Error updating Keychain item [error code -25293]

### ISSUE THREAD

**Issue by ashatrov-realforce** [Sequel-Ace/Sequel-Ace#268]
- Sequel Ace Version: 2.1.4 Build 2070
- macOS Version: 10.14.6
- MySQL Version: -

**Description**
After I updated Sequel-Ace to the latest version all saved passwords disappeared.
If I try to set a new password it shows me en error:  Error updating Keychain item [error code -25293]
Screenshot: https://ibb.co/Zx9d4Zt

**Comment by Jason-Morcos** [comment]
Hi,

Could you try to the steps mentioned in this support article? It appears this may be an issue with your Mac's keychain (not necessarily specific to Sequel Ace, but Sequel Ace does rely heavily on the keychain)

https://discussions.apple.com/thread/2280636

**Comment by ashatrov-realforce** [comment]
Hi @Jason-Morcos ,
This article helped to fix an issue 👍
