### ISSUE TITLE
The target export folder is not writable.

### ISSUE THREAD

**Issue by joomlabeat** [Sequel-Ace/Sequel-Ace#27]
I just discovered this fork, after searching for any updates and the development status of the original app and I was happy to see the Ace version.
I started using it right away and I am currently facing an issue.
When I try to export (dump) any tables I get: 
"The target export folder is not writable.  Please select a new export location and try again."
I tried saving the .sql file on a folder inside my local http docs, then tried to use my desktop as the target folder, then back again in the previous folder by adjusting its permissions.
In all cases I am getting that error message.

- Sequel Ace Version: 2.0
- macOS Version: 10.11.6
- MySQL Version: 5.7.6

**Comment by Jason-Morcos** [comment]
Oh no! I'm sorry you're having this issue! 

Can you try the new version that's pending App Store review and let me know if this fixes the issue? We sandboxed the app compared to Sequel Pro which makes it more secure but has certainly encountered some hurdles!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.0.1-rc1

**Comment by joomlabeat** [comment]
Hi Jason! 
I tried with 2.0.1 - still getting the same issue.

**Comment by Jason-Morcos** [comment]
Thank you for trying 2.0.1!
After some investigating, it looks like this is a sandbox issue! Like we're trying to pre-select a path and just let you hit export. In the sandbox world order, we instead shouldn't have a path selector and will have to make the user manually select an export location by navigating to it, perhaps after clicking the "export" button (likely after the file has been build so we can just drop it on the location after building it into a local temp dir). @gboudreau or @jamesstout would either of you be able to look into implementing this?

**Comment by jamesstout** [comment]
Is it a simple as configuring the `NSOpenPanel` with `canChooseDirectories = YES`? I can take a look.

**Comment by jamesstout** [comment]
> In the sandbox world once you've asked the user for a folder you can create a security scoped bookmark and save it in your apps preferences; on subsequent runs you can use that bookmark to re-establish rights to access the folder without user intervention

from https://stackoverflow.com/a/19258627

**Comment by jamesstout** [comment]
Very weird behaviour. 

1. navigate to desktop, create new folder, open, export = error
2. navigate to desktop, choose new folder from 1., open, export = error
3. navigate to desktop, don't select new folder, but it looks like you are in the new folder, but path is actually Desktop, open, export = error
4. navigate to desktop, choose new folder from 1., open, export = SUCCESS.

This is driving me mad. It's reproducible though.
create new folder in say ~/tmp, choose that folder, fail.
choose ~/tmp, fail
choose ~/tmp/new again, fails.
choose ~/tmp, fail
choose ~/tmp/new again, works.

**Comment by jamesstout** [comment]
I've got it working via `startAccessingSecurityScopedResource`. Just checking for leaks now, not written non-ARC code for a while...

**Comment by jamesstout** [comment]
Can you try out this branch? 46e9ab1c01412e10cf1160da47224988cd86270c

**Comment by Jason-Morcos** [comment]
@jamesstout Your fix works for me with 2 tiny caveats!
1. We probably should add the bookmark app and document entitlements to the app. likely will be required to have them for App Store release if using security scoped bookmark access (I had removed them before when we weren't using them - https://github.com/Sequel-Ace/Sequel-Ace/commit/a89002572f6350172f67c6f7b423a603f2e4ded8)

2. It does _not_ work if you go straight to the export dialog and click export because it fills in a default path (~/Documents for ex.) and doesn't have the bookmark because the user didn't select the path location manually. Probably the tiniest fix is just to not fill in a default export location and throw an error requiring the user to select export location if it's blank?

**Comment by jamesstout** [comment]
1. Added. Do we need [doc scope](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW19)? We're not using documents to access folders.
2. The app stores two locations in prefs: last navigated to folder: `NSNavLastRootDirectory` and `LastExportSettings.exportPath`. `NSNavLastRootDirectory` doesn't seem to be used. The export panel defaults to desktop, otherwise their home directory, then checks for `LastExportSettings.exportPath` and uses that if set.

We could just not set to desktop/home directory, and then prompt for a location, probably on first ever use. Then, if we're going to use bookmarks, we could store them in prefs, with a use count, then default to the most used location? But keep last used location if they export more than once in a session? Starting to get a bit more complicated.

I'll look at the first use example first, no `~` or `~/Desktop`.

**Comment by jamesstout** [comment]
Interestingly, if you don't enter a path, no error occurs and it doesn't tell you where it saved it. Had to do a `find`, but should have realised the file would be in `./Library/Containers/com.sequel-ace.sequel-ace/Data/nextcloud_2020-06-20.sql` Which the average user will never find. Even me!

**Comment by jamesstout** [comment]
Took me a while to get the alert in the right place, but please take a look at the same fork mentioned above.

https://github.com/Sequel-Ace/Sequel-Ace/compare/dev...jamesstout:target-export-folder?expand=1

**Comment by jamesstout** [comment]
Made a few changes to store the bookmarks.

**Comment by Jason-Morcos** [comment]
> 1. Added. Do we need [doc scope](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW19)? We're not using documents to access folders.
> 2. The app stores two locations in prefs: last navigated to folder: `NSNavLastRootDirectory` and `LastExportSettings.exportPath`. `NSNavLastRootDirectory` doesn't seem to be used. The export panel defaults to desktop, otherwise their home directory, then checks for `LastExportSettings.exportPath` and uses that if set.
> 
> We could just not set to desktop/home directory, and then prompt for a location, probably on first ever use. Then, if we're going to use bookmarks, we could store them in prefs, with a use count, then default to the most used location? But keep last used location if they export more than once in a session? Starting to get a bit more complicated.
> 
> I'll look at the first use example first, no `~` or `~/Desktop`.

Probably don't need doc scope if we're not doing any doc scope bookmarks!

Latest changes to fork worked for me! A little funky workflow that first time getting the error and having to go back and set export location - almost might be better to immediately pop up the export location select the first time if no location selected or something. But it 100% fixes the bug! PR it and will merge! Awesome work, @jamesstout!

**Comment by jamesstout** [comment]
I've added a warn user if they have not chosen a directory alert.

**Comment by jamesstout** [comment]
wait .. there might be a bug...

**Comment by emjayess** [comment]
Hm, just came looking for reports of this issue because I've been experiencing it... still.

Sequel Ace **2.1.7**
Build 2077
and Mac Homebrew installed

**Comment by Jason-Morcos** [comment]
@emjayess Hmmm, we issues a patch months ago which should have fixed this issue for everyone. You may be experiencing a different issue. Please open a new issue if you're still having this problem and please include the exact steps to reproduce. Feel free to reference this issue in your new issue (#27)

**Comment by incidentist** [comment]
@emjayess I also encountered this issue today (having installed Sequel Ace yesterday and imported my preferences from Sequel Pro), and fixed it with two steps. First, in System Preferences -> Security and Privacy -> Privacy tab. Unlock the pane via the lock in the lower-left, and click "Full Disk Access". Click the `+` button and add Sequel Ace. Restart Sequel Ace. In the export dialog, I had to click the `Change...` button to the right of the Path field, and re-select the same path that was already in that field before the export would work.

**Comment by mrpaulphan** [comment]
This happened to me randomly today and @incidentist solution worked for me 😀

**Comment by kalesh13** [comment]
In macOS BigSur 11.3.1, it is not showing any warning to access the directory. It would be better if some warnings are shown so that users know it's a directory permission issue.

**Comment by Jason-Morcos** [comment]
Please open a new issue for any new/re-appeared problem (you can and should link to/reference this issue from the new one if you believe it is relevant). Due to the quantity of issues, we can't monitor new comments on closed issues,

**Comment by Goran-S** [comment]
This is still happening. Back to Sequel Pro it is.

**Comment by zajako** [comment]
incidentist's method worked, I just had to save a new sft or whatever file in another directory.

I'm not sure the purpose of this feature but it takes a very simple required feature and makes it complicated due to macOS's security hell.

**Comment by timlinde** [comment]
Still happening for me as well. I tried giving the application full disc access without any luck.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now! We made an attempt at an improvement to sandbox bookmark management 

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by patrik90909** [comment]
> Please try the latest beta and let us know if it's fixed now! We made an attempt at an improvement to sandbox bookmark management
> 
> https://github.com/Sequel-Ace/Sequel-Ace/releases

Work for me, thanks!

**Comment by OneHatRepo** [comment]
Same issue for me. Using the latest version (3.4.0, build 3038) on Big Sur doesn't work. No exports are currently possible, because it doesn't remember the write directory path after it's selected.

**Comment by Jason-Morcos** [comment]
> Same issue for me. Using the latest version (3.4.0, build 3038) on Big Sur doesn't work, with full disk access granted. No exports are currently possible, because it doesn't remember the write directory path after it's selected.

We fixed this issue two months ago. If you're still having issues, please remove access to ALL directories/files in the app's settings, restart the app, and try again. Previous folder accesses from old versions before the bug fix are likely the culprit here.

**Comment by OneHatRepo** [comment]
That worked. Thanks.

**Comment by standerksen** [comment]
Issue still happens in version 4.0.5 on macOS Ventura 13.1 (Intel) when writing to `~/Documents`. The folder and its subfolders have `Read & Write` rights for `Everyone`.

**Comment by bruno-farias** [comment]
Here is what worked for me: 

- Go to the Applications folder in Finder, 
- Select Sequel Ace, right-click on it
- Select "Get info"
- Scroll down to the Sharing & Permissions section
    - click the lock to enable this section
    - click on the "+" signal to include your user with "Read & Write" permission
