### ISSUE TITLE
Tabs colors are very similar when inactive [Dark theme]

### ISSUE THREAD

**Issue by ashatrov-realforce** [Sequel-Ace/Sequel-Ace#273]
When the dark mode is enabled all disabled tabs colors look very similar. It is difficult to recognize that I am in the production DB :)
It would be nice to have more bright colors or pick color from the color palette.

https://prnt.sc/tpurcp

**Comment by stebogit** [comment]
Copying it here just to make it easier to see the picture. Also I'd like to point out that the close tab button (`x`) is hard to see

![download](https://user-images.githubusercontent.com/12717225/89212584-8efda200-d578-11ea-95bd-df44fc05d1d4.png)

**Comment by aledexter** [comment]
When the GUI is in dark mode the close tab button (x) and the new tab button (+) should be in white colour (or the active default color fot dark mode)

**Comment by MaximeLaurenty** [comment]
Same here: brighter colors would be very appreciated! 
Even in light mode I find them too grey / similar.

**Comment by origamifreak2** [comment]
Same here. I was about to add a feature request to show the new tab button (+) when only one tab was open, but then I realized it was already there, I just couldn't see it, lol.

**Comment by Kaspik** [comment]
Can be please verified with 3.0.1?

**Comment by aledexter** [comment]
> Can be please verified with 3.0.1?

I checked now. I see graphicals improvemenets but the "+" button is always too dark and similat to the background when the ui is in darck mode

**Comment by origamifreak2** [comment]
The "+" new tab and "x" close tab symbols are much more visible now. Thanks! :-)
