### ISSUE TITLE
More noticeable write statement execution feedback

### ISSUE THREAD

**Issue by brenoferreira** [Sequel-Ace/Sequel-Ace#275]
When you run a write statement to the database (INSERT/UPDATE/DELETE for example), it's hardly noticeable that the operation executed successfully. It's only a very small text update on the toolbar in the bottom corner (see screenshot).

<img width="1063" alt="Screen Shot 2020-07-28 at 12 07 16" src="https://user-images.githubusercontent.com/707019/88684135-e4decf80-d0ca-11ea-8cc7-f85410a76e7c.png">

It would be nice to have something a bit more prominent and noticeable in the UI indicating that the statement executed successfully. Not noticing your DELETE statement did actually run successfully in your production database on a Friday evening could be troublesome :)

**Comment by Jason-Morcos** [comment]
@brenoferreira Do you have any ideas for what you think this notice should look like? Perhaps an option in settings to have an alert displayed anytime an insert/update/delete is run that says the number of rows affected?

**Comment by brenoferreira** [comment]
@Jason-Morcos sorry for the delay in replying. I've seen some other DB clients that write statements show an "OK" message in the results pane, as if the query returned an "OK" in the first column. Does that make sense?
