### ISSUE TITLE
Save filters per table, as defaults

### ISSUE THREAD

**Issue by soeffingc** [Sequel-Ace/Sequel-Ace#276]
I'd like to have default filters saved per table. I often use a filter(s), remove the filter(s), and then use the same filter(s) again. I'd like to save the current set of filters as the default.

For example:

1. I start with a find to select specific data
2. I remove filters to return to viewing all data
3. At some point I want to bring those filters back, right now I need to re-enter those values. I'd love to have the last set of filters automatically "loaded".

<img width="843" alt="image" src="https://user-images.githubusercontent.com/66377994/88792632-86b4f980-d169-11ea-8803-d33b50aedc29.png">

These defaults should be saved per table.

**Comment by samuelbradshaw** [comment]
If you un-check the checkmarks to the left of the filter, then press the Filter button, the table will load all data while preserving the filters. Does that meet your use case?

**Comment by soeffingc** [comment]
I was thinking the "default set" would be saved and would be there after quitting the app, closing a tab, etc.

The checkmarks help, but I am constantly closing tabs, creating new ones, and I use the same set of filters almost all the time for a given table.

I can't speak to how many other people would find this useful, but it would save me a lot of time.

**Comment by samuelbradshaw** [comment]
That makes sense. I've also wished before that filters could persist after closing the app.
