### ISSUE TITLE
Sidebar changes size in fullscreen mode

### ISSUE THREAD

**Issue by AdrianFahrbach** [Sequel-Ace/Sequel-Ace#279]
- Sequel Ace Version: 2.1.5
- macOS Version: 10.15.5
- MySQL Version: 5.7.26

**Description**
The sidebar gets quite a lot wider when opening Sequel Ace in fullscreen mode.

**Steps To Reproduce**
1. Open Sequel Ace in window mode
![Bildschirmfoto 2020-07-30 um 11 34 27](https://user-images.githubusercontent.com/45072099/88908038-adeaf400-d259-11ea-88bd-0f33c1372b47.png)
2. Enter full screen mode
![Bildschirmfoto 2020-07-30 um 11 34 31](https://user-images.githubusercontent.com/45072099/88908055-b3483e80-d259-11ea-9626-7476e128fb94.png)

**Expected Behaviour**
The sidebar should stay the same size, just like in Sequel Pro
![Bildschirmfoto 2020-07-30 um 11 34 19](https://user-images.githubusercontent.com/45072099/88908197-decb2900-d259-11ea-9652-4f2c0cf4b5c8.png)
![Bildschirmfoto 2020-07-30 um 11 34 23](https://user-images.githubusercontent.com/45072099/88908189-de329280-d259-11ea-8011-3db7f9cb9be0.png)
**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes.

**Additional Context**
Maybe this is related to this sidebar sizing issue: #45

**Comment by Kaspik** [comment]
It might be resolved in 3.0.0 as I removed some funky code related to resizing.
