### ISSUE TITLE
Operation not permitted on Bash when using a jumphost

### ISSUE THREAD

**Issue by renebakx** [Sequel-Ace/Sequel-Ace#281]
- Sequel Ace Version: 2.1.5
- macOS Version: 10.14.6
- MySQL Version: not applicable

**Description**
When opening a connection to a jumphost that is declared in my ~/ssh/config the connection opens without any issues. But before connection to the remote server the connection crashed with

`/usr/local/bin/bash: Operation not permitted`

I did upgrade the default version of bash on my computer with a version from homebrew, that normally symlinks files in /usr/local/bin/ so I removed the symlink and did a hard copy of the bash bin to that location.
Tried setting the rights  to 777 on /usr/local/bin/bash no change
Even tried giving SequelAce full disk access via the security & privacy preferences 

**Steps To Reproduce**
1. Upgrade bash to the version provided by homebrew
2. Set /usr/local/bin/bash as default on the user
3. Open a connection to a host via a jumphost

**Expected Behaviour**
Opening a tunnel to the desired host.

**Additional Context**
EDIT: reverting back to the default /bin/bash solves this issue.

Error detail

```
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/rene.bakx/.ssh/config
debug1: /Users/rene.bakx/.ssh/config line 1: Applying options for *
debug1: /Users/rene.bakx/.ssh/config line 179: Applying options for 192.168.11.*
debug1: Setting implicit ProxyCommand from ProxyJump: /usr/bin/ssh -F /Users/rene.bakx/.ssh/config -v -W '[%h]:%p' kcluster
debug1: Executing proxy command: exec /usr/bin/ssh -F /Users/rene.bakx/.ssh/config -v -W '[192.168.11.8]:22' kcluster
debug1: identity file /Users/rene.bakx/.ssh/id_xxxxx_rsa.pub type 0
debug1: identity file /Users/rene.bakx/.ssh/id_xxxxx_rsa.pub-cert type -1
debug1: identity file /Users/rene.bakx/.ssh/id_xxxxx_rsa type 0
debug1: identity file /Users/rene.bakx/.ssh/id_xxxxx_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
/usr/local/bin/bash: Operation not permitted
ssh_exchange_identification: Connection closed by remote host
```
Snippet from the ssh config

```
Host kcluster
    Hostname cluster.xxxxx.xx
    StrictHostKeyChecking no
    IdentityFile ~/.ssh/id_xxxxx_rsa
    User ubuntu

Host 192.168.11.*
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    IdentityFile ~/.ssh/id_xxxxx_rsa
    User ubuntu
    ProxyJump kcluster
```

**Comment by Jason-Morcos** [comment]
Due to funkyness with the sandbox, we probably can't normally support non-standard bash setups.
If you grant Sequel Ace file access to the actual custom installed bash executable in sequel ace's prefs (see the files tab), does it work then?

**Comment by renebakx** [comment]
No I tried that. Perhaps it could work from the root down and giving access to the full /usr/local structure. But that sounds like a lot of hassle for a little gain.

**Comment by Jason-Morcos** [comment]
> No I tried that. Perhaps it could work from the root down and giving access to the full /usr/local structure. But that sounds like a lot of hassle for a little gain.

Try granting access to usr/local/bin in Sequel Ace's prefs files tab if you'd like to use a custom (homebrew) bash! Otherwise, little to nothing we can do here otherwise due to the sandbox.
