### ISSUE TITLE
Not accessing SSH keys

### ISSUE THREAD

**Issue by julian-weinert** [Sequel-Ace/Sequel-Ace#283]
- Sequel Ace Version: 2.1.5
- macOS Version: 10.14.6

First of all thanks for this work! I was sad in tears for a few years now and had my own little fixed version locally. But that finally a project with proper ambitions comes around is simply great!

I have multiple SSH keys for different servers / services installed on my system. I use them on a daily basis in the command line and have all my hosts configured with their host names, user names and key files.

When connecting using SSH in Sequel Ace it does not use these keys.

I found an `ssh_config` inside the app bundle with the need comment `## Specify a dummy id_rsa file so we don't try everything in the .ssh dir. TODO: Actually generate an id_rsa for each user`

Actually it would be better to try everything in .ssh or even better yet would be to use the systems `ssh_config`.
I suspect this is because of sandboxing.
But this is one of the many reasons I think Apples sandbox is simply stupid. There are a ton of absolutely valid reasons an application needs to access files on the system – this being one of them.

**Comment by julian-weinert** [comment]
I guess this issue could be closed. I just found the setting and feel a bit stupid.

Is the reason for this setting actually sandboxing? I would suggest just using the default system config.
There is actually a workaround. The file could be tagged with `com.apple.security.temporary-exception.files.home-relative-path.read-only` in the entitlements.

I'd love to get involved with this project. I will be looking at some tickets and see what I can do.
Is there a slack and / or discord for this project? I think it might be good for questions like "why did we do it that way" and general discussion

**Comment by categoryshell** [comment]
> I guess this issue could be closed. I just found the setting and feel a bit stupid.
> 
> Is the reason for this setting actually sandboxing? I would suggest just using the default system config. Or using the system config as default instead of creating an internal configuration.
> 
> There is actually a workaround. The file could be tagged with `com.apple.security.temporary-exception.files.home-relative-path.read-only` in the entitlements.
> 
> I'd love to get involved with this project. I will be looking at some tickets and see what I can do.
> Is there a slack and / or discord for this project? I think it might be good for questions like "why did we do it that way" and general discussion

Can you please share what setting / solution this is?

**Comment by julian-weinert** [comment]
It's the new "SSH Config" setting under Network.
![Screenshot 2020-08-07 at 19 04 09](https://user-images.githubusercontent.com/3418452/89670076-e1c0bc00-d8e0-11ea-975c-a3257a2b29b7.png)

What do you mean by "With the correct key selected"? If there is a key selected you should not have the same "issue" I was facing. I simply didn't have the right config, but for you it sounds like you had the correct one selected? Otherwise SA shouldn't have selected any key...
Which SSH config do you use? The usual `~/.ssh/config`?

**Comment by julian-weinert** [comment]
I'm going to close the issue. I'm still interested in the discussion anyway and also if there is some kind of place for loose discussions for people interested in contribution :)

**Comment by julian-weinert** [comment]
I'm going to close the issue. I'm still interested in the discussion anyway and also if there is some kind of place for loose discussions for people interested in contribution :)

**Comment by categoryshell** [comment]
My issue started when i added the password of my private key into the Keychain. 
Suddenly Sequel Ace refused to use that key. Removing the entry from Keychain, and manually entering the password every single time, worked.

Which comes to the issue i added the password to my Keychain in the first place.
Sequel Pro used the key i stored in session, via terminal (ssh-add ~/.ssh/id_rsa), that way i don't have to enter the password everytime i use that key during the session.
Sequel Ace doesn't seem to use that session and keeps asking for the password

**Comment by julian-weinert** [comment]
Hmm. I'm not too sure, sorry. I have no passwords set on my SSH keys, so I don't have hands on experience.
Do you have the correct config selected in the settings?

Unfortunately the last time I had a look in the code is a few years back and I don't recall messing with the SSH stuff. But as far as I can tell there are not too many changes either.
Mostly this config, which I suspect was added for sandboxing

**Comment by Jason-Morcos** [comment]
@julian-weinert Glad you found the setting!
I'd rather by default not use the user's .ssh directory. I would argue it's better to stay as in-the-sandbox as possible and allow users to opt out when desired (as in that .ssh config file setting). Relying on temporary exemptions sets us up for breaking in a future version of macOS.
I'm not sure if there's any other lingering questions in here but if so please open up a new issue and let's dig in!

**Comment by julian-weinert** [comment]
Sounds like another battle of sanity lost to the idiocracy of Apple. Sad.
So why App Store then? It forces so many unnecessary changes.
It disables so many things that are simple daily business for developers. It only makes things harder why absolutely no added benefit.
The App Store simply is not a place for professional software, but for Bubble Popping games and other unneeded... "Stuff".

**Comment by geoidesic** [comment]
I can't get this working either. Although I've selected the config it still asks for the password.
