### ISSUE TITLE
New possible Application Icon

### ISSUE THREAD

**Issue by greenchapter** [Sequel-Ace/Sequel-Ace#29]
Hey I would ask if you're interested in a new Icon for Sequel Ace? I have some Ideas in mind, maybe that is a little bit more aligned with the Official Apple Icons.

What do you think?

**Comment by Jason-Morcos** [comment]
Very interested!

Quite honestly, the current icon was just the quickest thing I could throw together that wasn't the Sequel Pro icon haha

**Comment by Jason-Morcos** [comment]
Duplicates #31
