### ISSUE TITLE
How to build Sequel-Ace in Xcode 11.4 locally?

### ISSUE THREAD

**Issue by vuongggggg** [Sequel-Ace/Sequel-Ace#298]
![Screenshot 2020-08-14 at 3 34 08 PM](https://user-images.githubusercontent.com/3168632/90230346-9ad44880-de43-11ea-8687-c9cca868426d.png)

I'm new on Xcode, with Sequel Pro I can build it in Xcode, but can't with Sequel-Ace. Seems like the problem related to Apple Development Account? Could anyone please help me on this issue to build it locally?

**Comment by Kaspik** [comment]
You wouldn't to be part of our Apple Developer account or change the code signing to yours.

The main question here is - why do you want to build it? It was the way how to use it for Sequel Pro, but we distribute Sequel Ace differently now. :)

**Comment by vuongggggg** [comment]
I want to build because I believe that I got an error in using it. So if I can build it, means I could investigate something to report as a new issue.

**Comment by Kaspik** [comment]
Yes, you need your own code signing then :)

**Comment by stychos** [comment]
@vuongggggg first, open XCode Preferences -> Accounts tab and log in to iCloud.
Second, open sequel-ace project properties, choose "Signing and Capabilities" tab and change "Team" to your Personal Team. Also, you need to change Bundle Identifier for it and repeat this for Frameworks/SPMySQLFramework.xcodeproj

<img width="1763" alt="Screenshot 2020-08-14 at 14 02 46" src="https://user-images.githubusercontent.com/1531639/90243127-fc41ea80-de36-11ea-9333-f7e00b1dd15c.png">
