### ISSUE TITLE
Switching between two saved connections removes the saved passwords

### ISSUE THREAD

**Issue by upatelte** [Sequel-Ace/Sequel-Ace#308]
- Sequel Ace Version: 2.1.5
- macOS Version: Catalina 10.15.6
- MySQL Version: N / A

**Description**
Switching between two favorite connections removes the saved passwords from the connections.

**Steps To Reproduce**
1. Save two different connections as favorite with passwords. (no need for valid credentials)
2. Click on left column to toggle between these two connections
3. You will see that the saved passwords are removed and you will need to reenter and save the connection again. 

**Expected Behaviour**
* The saved passwords for individual connections should persist, unless user explicitly changes `Username` for that particular connection.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
yes

**Additional Context**
-

**Comment by Jason-Morcos** [comment]
Cannot reproduce, followed your steps exactly. Anyone else able to reproduce this?
