### ISSUE TITLE
Font of the Pop-up editor sheet should default to MySQL content font

### ISSUE THREAD

**Issue by gboudreau** [Sequel-Ace/Sequel-Ace#316]
If one chooses a new font for `MySQL content font`:
![image](https://user-images.githubusercontent.com/370329/90977458-bdd1bd00-e513-11ea-90a4-2bacac5b5bd6.png)

That font should also be used by default in the pop-up sheet used to edit values.

Currently, those two fonts are different:
![image](https://user-images.githubusercontent.com/370329/90977495-e0fc6c80-e513-11ea-83dc-c142de6fb370.png)
![image](https://user-images.githubusercontent.com/370329/90977497-e35ec680-e513-11ea-88dd-8eed5cb24146.png)

That's because the pop-up sheet uses either the default system font, or the default monospaced font (if you enabled `Use monospaced fonts` in the preferences).
Instead, if should use the user-selected content font (if defined), and then fallback to its current behaviour.

Of note: one can also change the font used in the pop-up sheet by right-clicking in it, choosing "Font > Show Fonts", and changing the font there:
![image](https://user-images.githubusercontent.com/370329/90977564-5d8f4b00-e514-11ea-8549-d51f7f4e6fcb.png)
Sequel-Ace will persist that change, so obviously, we should keep that behaviour: using the content font as default should only happen when no`FieldEditorSheetFont` has been selected.

**Comment by gms8994** [comment]
This is similar (same, maybe) as sequelpro/sequelpro#3495. There may be useful information there.
