### ISSUE TITLE
MySQL 8.0.20 connection error

### ISSUE THREAD

**Issue by netojose** [Sequel-Ace/Sequel-Ace#32]
- Sequel Ace Version: 2.0.1
- macOS Version: 10.15.5
- MySQL Version: 8.0.20

**Description**
Couldn't to connect with MySQL 8.0.20 version

**Steps To Reproduce**
1. Open Sequel Ace
2. Type credentials
3. Test connection
4. An error message with unknown error code appears:
<img width="451" alt="Screenshot 2020-06-21 at 14 39 25" src="https://user-images.githubusercontent.com/134008/85224810-26de6c80-b3cd-11ea-95ed-fc012c5f41bd.png">

**Expected Behaviour**
A successful message should be displayed

**Additional Context**
The database is running inside a docker container.

**Comment by jamesstout** [comment]
No SSH? The docker instance is running on localhost? Can we see your connection window please?

**Comment by jamesstout** [comment]
Just d/l and spinning up a MySQL Version: 8.0.20 docker image....

**Comment by gboudreau** [comment]
@netojose Are you connecting using SSL ?
If so, this is an old Sequel Pro bug: https://github.com/sequelpro/sequelpro/issues/3520
I think this is because the MySQL client library that Sequel Pro/Ace uses doesn't support TLS 1.2: https://github.com/sequelpro/sequelpro/issues/2854#issuecomment-452119291

**Comment by gboudreau** [comment]
Ref, on how to check the SSL protocols supported, and how to change which are allowed: https://dev.mysql.com/doc/refman/8.0/en/encrypted-connection-protocols-ciphers.html#encrypted-connection-protocol-configuration

**Comment by netojose** [comment]
So, I can connect with the same credentials using workbench.
@jamesstout , is running on my machine (localhost).

**Comment by gboudreau** [comment]
I'm guessing updating the `SPMySQLFramework/MySQL Client Libraries` might resolve this. The currently used version is `5.7.26`.

**Comment by jamesstout** [comment]
> So, I can connect with the same credentials using workbench.
Yeah, this person fixed with workbench also: https://github.com/sequelpro/sequelpro/issues/3520#issuecomment-569248657. It must have updated connection libraries.

**Comment by Jason-Morcos** [comment]
So it does look like, reading through that sequel pro thread, there is a workaround at least, @netojose https://github.com/sequelpro/sequelpro/issues/3520#issuecomment-607473290

Looks like nobody from the sequel pro team even commented on that issue haha.
I think we're gonna have to support TLS 1.2. Seems like MySQL 8 support is pretty critical. I mostly use MySQL 6 so I hadn't realized 8 wasn't fully supported.

**Comment by jamesstout** [comment]
> > I've managed to connect to my DO MySQL 8 by setting up an SSH tunnel between my local machine and DO server
> > [sequelpro#3520 (comment)](https://github.com/sequelpro/sequelpro/issues/3520#issuecomment-607473290)
> 
Currently trying that, ssh into my docker instance, then try to connect to mysql, getting: 

```
MySQL said: Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

**Comment by Jason-Morcos** [comment]
> I'm guessing updating the `SPMySQLFramework/MySQL Client Libraries` might resolve this. The currently used version is `5.7.26`.

Seems like this was the thinking of the Sequel Pro team too - https://github.com/sequelpro/sequelpro/issues/3037#issuecomment-398490129

Not sure what it will take to support TLS 1.2 though (let alone 1.3)

**Comment by jamesstout** [comment]
> I'm guessing updating the `SPMySQLFramework/MySQL Client Libraries` might resolve this. The currently used version is `5.7.26`.

Do you know who built libmysqlclient last? Trying to figure out how to build it.

**Comment by gboudreau** [comment]
I don't think we want to build it; it is available for download in the TAR archives available on https://dev.mysql.com/downloads/mysql/

![image](https://user-images.githubusercontent.com/370329/85230184-79635d00-b3bc-11ea-9306-5b3fa8297d9c.png)

**Comment by jamesstout** [comment]
Ah, I downloaded the source, not the already compiled tar.gz.

Anyway, somehow, I built it:

![Screenshot 2020-06-22 at 1 12 03 AM](https://user-images.githubusercontent.com/1576190/85230909-ab5cd980-b425-11ea-8d0e-ce7fea3afb79.png)

**Comment by Jason-Morcos** [comment]
@netojose Please try out the latest pre-release beta and let us know if this fixes your MySQL 8 issues! https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.0-beta1

**Comment by netojose** [comment]
> @netojose Please try out the latest pre-release beta and let us know if this fixes your MySQL 8 issues! https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.0-beta1

@Jason-Morcos , the [2.1.0-beta-1](https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.0-beta1) worked, it's perfect!

**Comment by jamesstout** [comment]
Also works for me. Great stuff @gboudreau. I got to updating `MYSQL_FIELD`, `MYSQL` and `MYSQL_RES` and had about 100 errors. I'd missed a few new header files.

**Comment by Jason-Morcos** [comment]
For anyone coming to this issue today - MySQL 8 will be supported in Sequel Ace 2.1.0 which is currently in Beta!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.0-beta3
