### ISSUE TITLE
After mysql8.0.17,Integer display width is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by bpzhang** [Sequel-Ace/Sequel-Ace#320]
In the version after mysql8.0.17, mysql officially no longer recommends setting the length for integer type fields such as int and bigint. Can the client optimize this? Now it is not displayed after the client is set, which is unfamiliar People will think that the setting is not successful

**Comment by Jason-Morcos** [comment]
I'm a little confused, what change exactly do you think we should make? We of course must support mySQL < 8 too

**Comment by bpzhang** [comment]
> I'm a little confused, what change exactly do you think we should make? We of course must support mySQL < 8 too


Yes, support is required under version 8. I hope to have better tips for versions above version 8. There is no hint after the length of the above version is modified, which may cause some misunderstandings for unfamiliar people

**Comment by cappadaan** [comment]
I tried to remove the lengt from an int(10) field from within the structure view to test what is happening:

- Double click on the value of length
- backspace = remove value
- focus off field
-> value "10" re-appears as Length

Is this expected behaviour?

I use Mariadb 10.5.5

**Comment by bpzhang** [comment]
> I tried to remove the lengt from an int(10) field from within the structure view to test what is happening:
> 
> * Double click on the value of length
> * backspace = remove value
> * focus off field
>   -> value "10" re-appears as Length
> 
> Is this expected behaviour?
> 
> I use Mariadb 10.5.5

I think it's a bug, just like the inability to add lengths above version 10
