### ISSUE TITLE
Search entire database for a string

### ISSUE THREAD

**Issue by lamda** [Sequel-Ace/Sequel-Ace#322]
The only thing that's keeps me going back to phpMyAdmin is the fuzzy search across an entire database, exhibit A:

![image](https://user-images.githubusercontent.com/1311431/91399760-da853200-e83e-11ea-9c1a-493e82bdc1ef.png)

This is very useful to e.g., identify in what tables wrong URLs or specific options are saved. Is there a way to do this in Sequel-Ace?

**Comment by Jason-Morcos** [comment]
Duplicates https://github.com/Sequel-Ace/Sequel-Ace/issues/152
