### ISSUE TITLE
Stored Procedure Support

### ISSUE THREAD

**Issue by Sylk** [Sequel-Ace/Sequel-Ace#324]
Does Sequel-Ace currently support stored procedures?

**Comment by Jason-Morcos** [comment]
Me thinks not, but does anyone else know more certainly? @Sequel-Ace/all

**Comment by gboudreau** [comment]
Stored procs and functions can be created in any client, Sequel-Ace included. Example:

```mysql
DELIMITER //
CREATE PROCEDURE test_sproc
(IN val INT(11))
BEGIN
  SELECT * FROM test_charsets
  WHERE id = val;
END //
DELIMITER ;
```

Select all this in the Query editor, and `Run Selection` (`Cmd-R`).

Procs & functions appear below tables, in the left column:
![image](https://user-images.githubusercontent.com/370329/91635315-89ec1100-e9c5-11ea-8b50-28e81578d288.png)

But there isn't much you can do with those, except see they are available. To view or modify them, you'll need to use the Query editor.

**Comment by Jason-Morcos** [comment]
I'm going to go ahead and close this issue. If @Sylk you intended to make this a request for greater support of stored procedures, please open a new issue making that clear. I interpreted this issue as a question and not a feature request.

**Comment by mnowliniar** [comment]
You can use them in queries. For example to call test_sproc and pass a parameter:
`Call test_sproc(@some_param);`

You cannot edit them via the GUI, but you can edit them via SQL.
