### ISSUE TITLE
MySQL said: Bad handshake

### ISSUE THREAD

**Issue by aledexter** [Sequel-Ace/Sequel-Ace#327]
- Sequel Ace Version: 2.1.6 build 2074
- macOS Version: Mojave 10.14.6
- MySQL Version: mysql  Ver 14.14 Distrib 5.1.71, for redhat-linux-gnu

**Description**
I am migrating from sequel pro to sequel ace.
I can connect to one of my old database with sequel pro.
I cannot connect to the same database with sequel ace with
 the same parameters.

**Steps To Reproduce**
1. I try to connect to the database
2. i get an handshake error from mysql and the Connection Failed message from Sequel Ace gui.

**Expected Behaviour**
I expect to can connect to the database as i can with sequel pro

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
I tried the 2.1.7 latest build avaible 2076 and the issues still persist

**Additional Context**
Sequel Ace error:
```
CONNECTION FAILED!
Unable to connect to host 127.0.0.1, or the request timed out.
Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).
MySQL said: Bad handshake
```

![error](https://user-images.githubusercontent.com/11591259/91641648-18907a80-ea26-11ea-8e0f-7d703b64987b.png)

thank you

**Comment by Jason-Morcos** [comment]
Looking at your MySQL version, is it MySQL 5.1? Sequel Ace only supports MySQL 5.6 and above (a side effect of upgrading to support MySQL 8).

**Comment by aledexter** [comment]
Ok, the issue is now clear.

There is a way to use seuqel ace to connect to  MySQL < 5.6 version?
Some flag like a "compatibility mode" for older version?

or we should continue use sequel pro for older mysql versions?

Thank you in advance

**Comment by Jason-Morcos** [comment]
We're not planning to support older versions of MySQL. Not only are they officially unsupported and have reached end of life, but supporting them would require basically two versions of the connection code. If you must stick with MySQL < 5.6, unfortunately you will be stuck using Sequel Pro :/
But, I encourage you to update to MySQL 5.6 or later (5.6 doesn't reach end of life until February of next year at least)
