### ISSUE TITLE
Query Favorites cannot be saved normally when global option is not selected。

### ISSUE THREAD

**Issue by westoi** [Sequel-Ace/Sequel-Ace#331]
- Sequel Ace Version: 2.1.6
- macOS Version: macOS High Sierra
- MySQL Version: 5.7.12

**Description**
If this global is not selected, the saved query favorites can only exist in the current window. If you re-enter this connection of the software, it will disappear.

**Steps To Reproduce**
1.Enter an SQL and select save all to query favorites. Do not select the global option.
2.Exit the software and re-enter this connection. The saved query favorites cannot be found

**Comment by Jason-Morcos** [comment]
What is the "global" option? Unfortunately, I don't really understand your bug report. Would it be possible to try to explain in more detail or in a different way?

**Comment by westoi** [comment]
<img width="1162" alt="QQ20200831-151126@2x" src="https://user-images.githubusercontent.com/19583244/91692621-40a1ea00-eb9c-11ea-9de4-6abb7eef6eb4.png">
<img width="1150" alt="QQ20200831-151058@2x" src="https://user-images.githubusercontent.com/19583244/91692628-439cda80-eb9c-11ea-93cd-1ef0cd2d083e.png">

**Comment by westoi** [comment]
I am sorry for my poor english, so please forgive me to talk with you with h ehelp of some tools
