### ISSUE TITLE
Auto trim value in filter form field

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#332]
Is it possible to automatically trim the (text) values in the filter form field?

Most of the time I copy/paste data into the filter fields to search in my tables, which often contain additional spaces. This results in no search results.

**Comment by Jason-Morcos** [comment]
Maybe as a specific preference I guess. Some users may include spaces intentionally so it probably would be a setting and not on by default

**Comment by cappadaan** [comment]
Maybe only auto trim on "paste" ?

**Comment by Jason-Morcos** [comment]
> Maybe only auto trim on "paste" ?

Perhaps, but even then what if you copied and pasted a string whose value is " 123" and wanted to filter to exact matches on that. It would be sorta confusing if the string was magically trimmed on paste

**Comment by cappadaan** [comment]
I have to admit it could be confusing. Leaving it the way it is seems to be the best option.
