### ISSUE TITLE
Point type edit error: GeomFromText does not exist

### ISSUE THREAD

**Issue by jandreasn** [Sequel-Ace/Sequel-Ace#333]
- Sequel Ace Version: 2.1.7 Build 2077
- macOS Version: 10.15.6
- MySQL Version: 8.0.21

**Description**
When editing a row with a point type column, an error alert pops up with:

>Unable to write row
> MySQL said:
>
>FUNCTION mytable.GeomFromText does not exist

 

**Steps To Reproduce**
1. Create a table with a point, type, e.g:
```
CREATE TABLE `mytable` (
    `id` int DEFAULT NULL,
    `location` point DEFAULT NULL
);
```
2. Insert a row with for example "POINT(45 90)" in the location column.

**Expected Behaviour**
No error alert. Row is updated.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Comment by Jason-Morcos** [comment]
https://github.com/sequelpro/sequelpro/issues/3365
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-0.html
If we can confirm that the SP_* methods are available in all supported variants of MySQL>=5.6, we should be good to replace them all, it looks like to me at least.
@Sequel-Ace/all

**Comment by Jason-Morcos** [comment]
I have a possible bug fix written, @jandreasn, but will need to get it tested by someone with MySQL 8 access before merging it! https://github.com/Sequel-Ace/Sequel-Ace/pull/334

**Comment by jandreasn** [comment]
Great, thanks! If you don't find anyone else you can send a build to me for testing.

**Comment by Jason-Morcos** [comment]
@jandreasn New beta published! Please check it out and let us know if it is working for you.
https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.8-beta1

**Comment by jandreasn** [comment]
I no longer get the previous error message!  But, for some coordinates a get a new error message now:

>Unable to write row
>MySQL said:
>Latitude 105.337788 is out of range in function st_geomfromtext. It must be within [-90.000000, 90.000000].
>

Can be reproduced using this table:
```
CREATE TABLE `mytable` (
    `id` int DEFAULT NULL,
    `location` point /*!80003 SRID 4326 */ DEFAULT NULL
 );
```

and then try to insert this value in location: `POINT(105.337788 84.02116100000001),4326`. 

I don't know that much about MySQL's spatial functions but it seems coordinates should be stored as longitude, latitude instead of the more common latitude, longitude format.

**Comment by Jason-Morcos** [comment]
Latitude and longitude must be between -90 and 90. Can't go more than 90° in either direction or you'd be on the other side of the earth! So the 105 you have in your insert is invalid (not a real coordinate)

**Comment by jandreasn** [comment]
That is only for latitude as I understand it. Longitude is in the range between -180 and +180.

**Comment by Jason-Morcos** [comment]
> That is only for latitude as I understand it. Longitude is in the range between -180 and +180.

Ah yes you are correct. But MySQL uses `POINT(lat, lon)` syntax so your insert is backwards
https://dba.stackexchange.com/questions/182136/does-mysql-store-point-datatypes-as-lat-lng-or-lng-lat

**Comment by jandreasn** [comment]
This is confusing. Here's another answer:  https://stackoverflow.com/questions/11082696/lon-lat-order-when-using-spatial-point-type-with-mysql which says it's lon, lat.

This works:

     INSERT INTO `mytable` SET location = ST_SRID(Point(105.337788, 84.021161), 4326)

But this doesn't: 

    INSERT INTO `mytable` SET location = ST_SRID(Point(84.021161, 105.337788), 4326)

Which indicates that it should be `POINT(lon, lat)`.

**Comment by gboudreau** [comment]
I can confirm the syntax is `POINT(x y)`, and for SRID 4326, x = lon and y = lat. [Ref](https://epsg.io/4326)

```sql
SELECT GeomFromText('POINT(105.337788 84.021161)', 4326)
```
Unless MySQL 8 changed something about this (which I doubt; that would be a major breaking change).
