### ISSUE TITLE
ssh connection fail with ssh alias set at ~/.ssh/config

### ISSUE THREAD

**Issue by yanggs07** [Sequel-Ace/Sequel-Ace#335]
- Sequel Ace Version:2.1.5 build 2073
- macOS Version:10.15.6
- MySQL Version:8.0/not related

**Description**
when connect mysql server with ssh proxy, use ssh alias not work
the detail seems to not following the ssh config with the host,port and user.

**Steps To Reproduce**
1. new connect with SSH by ssh host named by ssh alias
2. test connection

**Expected Behaviour**
sequel pro can support ssh alias well.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, 2.1.7 RC1 still has this bug.

**Additional Context**
ssh error detail:
```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/<user>/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -i /Users/<user>/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 <user>@proxy -L 53925:db.server:3306

OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Connecting to proxy [<ip>] port 22.
debug1: connect to address <ip> port 22: Operation timed out
ssh: connect to host proxy port 22: Operation timed out
```
ssh config:
```
 17 Host proxy
 18     Hostname _foo.example.com
 19     User <user>
 20     Port 1234
```

**Comment by Jason-Morcos** [comment]
Not a bug, it's part of the sandbox. Please see the FAQ - you must open Sequel Ace's preferences and select your ssh config file if you'd like to use your ssh config connections. Additionally you must grant access to any key files needed to authenticate.
Sequel Pro was not sandboxed, Sequel Ace is.

https://sequel-ace.com/get-started/
See "Sequel Ace doesn’t read my ~/.ssh/config parameters."

**Comment by Jason-Morcos** [comment]
Duplicates #68
