### ISSUE TITLE
Dark Mode Toggle should be hidden on macOS < 10.14

### ISSUE THREAD

**Issue by carkar7** [Sequel-Ace/Sequel-Ace#340]
- Sequel Ace Version: 2.1.7
- macOS Version: 10.13.6 High Sierra
- MySQL Version: 10.2.21-MariaDB

**Description**
Enabling dark mode in preferences does not work. However, I'm able to apply a dark mode theme for the query editor 

**Steps To Reproduce**
1. SequelAce
2. Preferances
3. Appearance > Dark

Layout stays same as default. Tried restarting, still does not change. Issue occurs with colleague as well.

**Expected Behaviour**
For the UI to be dark

**Additional Context**

![Xnip2020-09-04_12-48-18](https://user-images.githubusercontent.com/22269536/92280237-d8118080-eead-11ea-8555-fd54719a433a.jpg)

**Comment by Jason-Morcos** [comment]
Dark mode isn't available on macOS < 10.14. We should have disabled this preference in older versions of macOS

**Comment by Jason-Morcos** [comment]
@stychos We need to disable this toggle on older Mac OS Vs. #294

**Comment by stychos** [comment]
Huh.. will be more attentive next time. Thanks for catching this!

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now! The appearance selector should be grayed out on older versions of macOS

https://github.com/Sequel-Ace/Sequel-Ace/releases
