### ISSUE TITLE
Sometimes when the connection reestablishes, the filter is no longer visible

### ISSUE THREAD

**Issue by webtoolbox** [Sequel-Ace/Sequel-Ace#342]
- Sequel Ace Version: 2.1.6
- macOS Version: 10.15.16
- MySQL Version: 5.5

**Description**
Sometimes when a tab/connection is open for a long period of time and you return to it and it reconnects, the filter options are no longer visible on the Content tab even though they were previously open. One has to click the filter icon to open the filter again.

**Steps To Reproduce**
1. Go to the content tab and click the filter icon to make the filter visible.
2. Go to a different tab.
3. Leave the computer and the connection for a long period of time.
4. Return and click the Content tab.
5. Now the filter option might not be visible. (It doesn't always happen. Only sometimes. I can't seem to identify exactly when.)

**Expected Behaviour**
It would be nice if Sequel Ace remembered your preference for keeping the filter visible or not and then just remember it for ALL connections as a master preference. It shouldn't become invisible again unless the filter icon is pressed again.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Please try the [latest beta](https://github.com/Sequel-Ace/Sequel-Ace/releases). If the latest beta works, we've fixed the issue already and will get the fix out soon.

Unsure, but I don't see any bug reports for it.

**Comment by Jason-Morcos** [comment]
Sounds like a bug, but hard to fix if it's not deterministic to reproduce.

**Comment by webtoolbox** [comment]
Just got the exact steps!
1. Go to Content
2. Click the filter icon to open the filter options
3. Click on Triggers
4. View a different table
5. Now click on Content again
6. The filter option will be hidden again.

**Comment by webtoolbox** [comment]
Step 3 can be any other icon like Query or Table Info as well.

**Comment by jamesstout** [comment]
PR #890
