### ISSUE TITLE
Load data local infile

### ISSUE THREAD

**Issue by serbanc66** [Sequel-Ace/Sequel-Ace#343]
Hi All,
thanks for your job.
I am trying to substitute Sequel Pro with Sequel Ace, but I continue to have the issue related to the command "LOAD DATA LOCAL INFILE" that in Ace result not allowed.
I tried to include the file to append into table in Folders allowed (preferences/files -> adding the files accessible) but it continue not to work. With Sequel Pro never had this issue. (using the same config)
My config is described below:

- Sequel-Ace: 2.1.7 build 2077
- macOS: 10.13.6
- MySQL 5.6.14 on WIN virtual machine server.

Thanks in advance

**Comment by Jason-Morcos** [comment]
Duplicates #245
