### ISSUE TITLE
Sequel Ace having a spinning beachball while running long procedures/queries

### ISSUE THREAD

**Issue by xingmungwa** [Sequel-Ace/Sequel-Ace#345]
Hi

I am on Sequel Ace 2.1.7 (Build 2077) + macOS Catalina 10.15.6 + MacBook Pro 2015.

While trying to call a procedure which should take around 15min to complete, the **Running query dialogue keeps spinning forever. Hitting Stop query doesn't change the state of the spinning wheel. Only way to get out is force quitting the application**.

It would be nice if the issue could be resolved allowing the application to be stable even for long calls.

**Comment by stychos** [comment]
Had this issue some time ago, but not related to the long query, had catch it after connection troubles. I think may be related to https://github.com/Sequel-Ace/Sequel-Ace/issues/282

**Comment by Kaspik** [comment]
The mentioned issue is closed now, would you mind trying 3.3.0 if it's fixed?

**Comment by xingmungwa** [comment]
Yeah sure, thank you.

**Comment by Jason-Morcos** [comment]
I believe this is fixed! Please let me know if it is not.
