### ISSUE TITLE
Add Settings for Known Hosts

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#35]
Add a setting to reset known hosts (delete the known hosts file) [critical for when remote servers change]
Perhaps add a setting to allow disabling strict host key checking?
Allow the user to manually add/remove known hosts through settings GUI?

**Comment by johnathan99j** [comment]
> (delete the known hosts file)

The known hosts file and its entries shouldn't just be ignored or deleted if there's a miss match on a key fingerprint. Yes the vast majority of the time it's just that a key's changed on the server and you **can delete the single bad entry** but it's a useful mechanism to flag potential [man in the middle attacks](https://www.ssh.com/attack/man-in-the-middle). It's dangerous to train people to [ignore warning messages ](https://www.theguardian.com/technology/2015/feb/24/people-ignore-security-warnings-browsing-web) and leads to bad habits.

That all said, I'm all for a feature that clears the single miss matched entry (presuming the user is informed of the implications etc.) it'd actually be quite useful as clearing the entry manually can be a bit of a pain, especially if you have lots of known hosts!
