### ISSUE TITLE
Default Bundle Updates Don't Seem to Be Applied

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#36]
The latest changes to the SQL formatter bundle don't appear to be applied despite incrementing build&version numbers

**Comment by jamesstout** [comment]
We seem to have lost this from the build script:

https://github.com/sequelpro/sequelpro/blob/53cd722f37d6e1818206613d1234c0f2e21cb189/Scripts/build.sh#L100-L110

```bash
copy_default_bundles()
{
	log "Copying default bundles from '${SRCROOT}/SharedSupport/Default Bundles' to '${SHARED_SUPPORT_DIR}'"


	# Copy all Default Bundles to build product
	rm -rf "${SHARED_SUPPORT_DIR}/Default Bundles"


	mkdir -p "${SHARED_SUPPORT_DIR}/Default Bundles"


	cp -R "${SRCROOT}/SharedSupport/Default Bundles" "${SHARED_SUPPORT_DIR}"
}
```

**Comment by Jason-Morcos** [comment]
Hmmm I wonder how we even do this in a sandbox world. Perhaps we bundle them into our Resources folder and then copy them into application support on first run?
