### ISSUE TITLE
Singe line connection

### ISSUE THREAD

**Issue by JoppeDC** [Sequel-Ace/Sequel-Ace#360]
The ability to connect using a single, MYSQL styled line.
user:password@host:port/database

This is a small feature, and it may not be used by a ton of people. But still, i think it would be a nice addition.

**Comment by robinkunde** [comment]
Description of the format can be found here: https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html

**Comment by Jason-Morcos** [comment]
We do open mysql:// urls. Is the request here some input in the app by which you could provide this format and connect?

**Comment by JoppeDC** [comment]
Hi @Jason-Morcos !

Correct. Provide some field in the interface to allow pasting the mysql:// url. It's also possible to just make it prefill all the fields, so you can still connect the regular way.
Reason for request: I connect to dozens of databases daily, and just being able to copy / paste 1 long url is way more efficient than copy/pasting host,user,pass,db, ...

**Comment by JoppeDC** [comment]
(Could also maybe be something nice for Hacktoberfest - tho i don't know if this project will participate)
