### ISSUE TITLE
Slow/laggy scrolling in Query view with large query

### ISSUE THREAD

**Issue by Acen** [Sequel-Ace/Sequel-Ace#362]
- Sequel Ace Version: 2.1.7 (build 2077)
- macOS Version: 10.15.6
- MySQL Version: 5.6.10

**Description**
Scrolling in Query with large multi-line query lagging/slow scrolling

**Steps To Reproduce**
1. Place 250-300 line query into query tab.
2. Select inside the content.
3. Attempt scrolling up and then down or vice versa.

**Expected Behaviour**
High scrolling performance

**Comment by Jason-Morcos** [comment]
Duplicates https://github.com/Sequel-Ace/Sequel-Ace/issues/269

You may want to try the steps described in that issue such as turning off syntax highlighting. We're aware of the issue but haven't yet found a good fix!
