### ISSUE TITLE
Ability to set a column as "sticky" or "locked" when viewing query results

### ISSUE THREAD

**Issue by crazytonyi** [Sequel-Ace/Sequel-Ace#364]
If a query (or a table showing all columns) has a ton of columns, this requires a lot of horizontal scrolling. When looking for a specific column value for more than one result, this can get exhausting, having to scroll over to see value of column X for row A (with id and name as first columns), then scrolling back to line up another row. Or if you were scrolling down the rows with column X in focus looking for sets of values, etc, having to scroll over to see who it matches up with. 

Could a column be pinned to the left so that when viewing a column that is 40 columns over, you can scroll and see which name/id it matched up with without having to scroll back and forth?

**Comment by samuelbradshaw** [comment]
Columns can be dragged left and right to reorder them on the fly. Is that what you're looking for?

**Comment by crazytonyi** [comment]
> Columns can be dragged left and right to reorder them, after the query runs. Is that what you're looking for?

Not quite, but I didn't know about that feature (neat!) and may use it as a workaround in the future.

The problems with that solution is:

- You have to drag the given field to where you want it, but maybe I want to see the main id/name field for a few different columns. Having the column lock into place would avoid the need for dealing with the UIs drag and drop clunkiness, as well as be a faster / more robust solution (for my use case)
- I assume that the column order stays in that order (like a local user preference) indefinitely? I am not always wanting to do a side by side for the same columns, so I'd have to find where I last left my id column and drag it to where I want it.

for what it's worth, I also think that the HTML standard is lacking for this feature (although there are libraries for making it happen in JS). There needs to be a way to make the header column (as it were) locked so that users can quickly match up a distant column with the record.

**Comment by Jason-Morcos** [comment]
Is this a duplicate of #228?

**Comment by crazytonyi** [comment]
> Is this a duplicate of #228?

No. I saw that before I posted. They are talking about how the UI jumps to the start of the window after you edit a far over column. I imagine even with my feature request in place, this would still be an issue, as locking the first column wouldn't prevent the window to scroll all the way back to the start (far left) of the frame.
