### ISSUE TITLE
Query History search very slow

### ISSUE THREAD

**Issue by Nuranto** [Sequel-Ace/Sequel-Ace#366]
- Sequel Ace Version: 2.1.7
- macOS Version: 10.15.6
- MySQL Version: Mariadb10.4

When searching for a query in Query History, it tooks over a minute. 
I configured to remember last 100 queries.

I also noticed that it launched a search for every character input. That doesn't help. For exemple if you search for "null", it will search for "n", then "nu", then "nul" and finally "null". Some millisecond timer to not launch any search while typing would help probably. But that's not the main issue I think. Even like that, text searching over 100 records should be instant.

**Comment by jamesstout** [comment]
See what you think of this [branch](https://github.com/Sequel-Ace/Sequel-Ace/commits/improve-query-history-search)

**Comment by Kaspik** [comment]
2.3.1 is out 🚀
