### ISSUE TITLE
mysql:// link handler

### ISSUE THREAD

**Issue by tylershuster** [Sequel-Ace/Sequel-Ace#369]
*Back in the day* Sequel Pro could open `mysql://` links...then that feature disappeared. It's very helpful for me as someone who manages lots of databases that are created and deleted on the fly. I would love to see this feature again, and would appreciate a point in the direction of any way to do it myself in the meantime.

**Comment by Jason-Morcos** [comment]
This feature wasn't removed. What leads you to believe that it's not working?

**Comment by Jason-Morcos** [comment]
I just tested and confirmed that I indeed can open mysql:// urls in Sequel Ace

**Comment by tylershuster** [comment]
I narrowed down the problem to passing the password using this syntax:

`mysql://username:password@domain.name:9047/database`

This is what used to work for me and no longer does. Is this incorrect or unsupported syntax?

**Comment by Jason-Morcos** [comment]
We should support URL's in the `mysql://[user[:password]@][host[:port]][/database]` syntax, yes. When you say it doesn't work, what happens?

**Comment by Jason-Morcos** [comment]
The relevant code for the behavior is in SPAppController.m
<img width="654" alt="Screen Shot 2020-10-02 at 15 08 41" src="https://user-images.githubusercontent.com/10710367/94973689-30de3400-04c1-11eb-9af1-5110716ee8a1.png">

**Comment by tylershuster** [comment]
I'm sorry, this was an issue with my configuration. This seems to work exactly as expected.
