### ISSUE TITLE
Malformed Packets error

### ISSUE THREAD

**Issue by lcsqlpete** [Sequel-Ace/Sequel-Ace#379]
- Sequel Ace Version: 2.1.1
- macOS Version: 10.14.6
- MySQL Version: 5.6?

**Description**
Clicking a table or view frequently results in a"malformed packets" error and no data is displayed.

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Please try the [latest beta](https://github.com/Sequel-Ace/Sequel-Ace/releases). If the latest beta works, we've fixed the issue already and will get the fix out soon.

**Comment by Jason-Morcos** [comment]
I' musing MySQL 5.6 and have never encountered this issue. Do you have more precise steps to reproduce? Anything special about your setup?

**Comment by lcsqlpete** [comment]
The db in question is on an AWS mySQL server using CA certification.  It’s an intermittent problem but once it happens I generally get it on every subsequent attempt.

**Comment by Gulivertx** [comment]
Same error here !

- Sequel ACE 2.2.2
- Macos 10.15.7
- Mysql 5.7

I get this error on some tables, always the same, but where Sequel Pro does not have any trouble to fetch data in the same tables.

**Comment by Jason-Morcos** [comment]
We haven't been able to reproduce this error. If someone can identify a more deterministic process to reproduce it, it would make it quite a bit easier to fix. Right now it just seems to happen at random to a small subset of users.

**Comment by robinkunde** [comment]
If someone could stand up and EC2 instance for us, or at least provide and AMI where they can reliably reproduce the issue, it would help us a lot.
