### ISSUE TITLE
Duplicate does not duplicate

### ISSUE THREAD

**Issue by categoryshell** [Sequel-Ace/Sequel-Ace#396]
Sequel Ace 2.1.5 build 2073

**Description**
When i want to duplicate an existing connection, it doesn't duplicate anything other than hostnames and usernames.

**Steps To Reproduce**
1.  Create new connection and fill in all the credentials
2. Duplicate that connection

**Expected Behaviour**
I expect the connection to be fully duplicated, with all the fields that are filled in the connection i want to duplicate.

**Comment by Jason-Morcos** [comment]
For security purposes, we only copy the non-security credentials. This is expected behavior

**Comment by categoryshell** [comment]
Can you elaborate on that?
Because there is no security reason as far as i know.

I have access to the connection i want to duplicate, i can alter the connection i want to duplicate.
This sounds to me that this behaviour fixes a problem that doesn't exist.

**Comment by Jason-Morcos** [comment]
I think the primary concern is that someone could change the connection and connect to something it wasn't setup to connect to (ex. someone is silly and uses the same password for all accounts. It would be bad if you could just change the username to god and login). Currently, when you edit something like the account name, we null out the password for this same reason. Does it really matter if it nulls out all that info before duplicating or after you change a connection setting?

I guess the better question - what is the use case you want to duplicate in which you would _want_ the secure connection info to be copied over? I guess I just don't see the standard case here :)
