### ISSUE TITLE
How to manage MySQL Functions ?

### ISSUE THREAD

**Issue by ligne13** [Sequel-Ace/Sequel-Ace#397]
Hi,

how can I manage MySQL functions in Sequel Ace ?

thanks

**Comment by stychos** [comment]
Unfortunately, there is no way to use procedures / functions in UI same as in the Sequel Pro.
I am selecting procedure / function in tables list and choosing "Show Create ... Syntax".
Then I analysing syntax and running call manually in the query window.

Same as #324, closing this  And the same, if you intended to make this a request for greater support of stored procedures, please open a new issue making that clear. I interpreted this issue as a question and not a feature request.
