### ISSUE TITLE
Keep Sequel-Ace simple

### ISSUE THREAD

**Issue by helptiger** [Sequel-Ace/Sequel-Ace#399]
To keep Sequel Ace simple, special features that are uninteresting or even confusing for the majority of users should be activated via the preferences or appear as advanced settings on a 2nd level.

the new options Timezone and Allow LOCAL_DATA_INFILE are uninteresting and rather confusing for the majority of users

**Comment by Jason-Morcos** [comment]
Thank you for the feedback.
We're definitely open to removing these features from the main connection screen, and have had early discussions about adding an advanced menu to connection options. We felt these options should be connection-specific, so we didn't want to put them in the existing general preferences. However, if someone wishes to redesign the connection interface to have an advanced settings area per-connection, we'd gladly review (and likely accept) such a PR.
