### ISSUE TITLE
Search all tables

### ISSUE THREAD

**Issue by llamafilm** [Sequel-Ace/Sequel-Ace#400]
I frequently need to search for a string in all columns of all tables.  I use phpMyAdmin for this and it works great.  A colleague suggested I switch to Sequel Ace instead, but I can't find a way to do this.  Otherwise, I like the responsiveness of a native app, but I cannot work without this feature.  Here's a screenshot of how the search results work in phpMyAdmin.

![phpmyadmin](https://user-images.githubusercontent.com/3991046/96019745-f490c900-0e1a-11eb-9785-59e93e0ef024.png)

**Comment by Jason-Morcos** [comment]
Currently Sequel Ace doesn't support this feature but there is an existing feature request for it: https://github.com/Sequel-Ace/Sequel-Ace/issues/152

**Comment by Jason-Morcos** [comment]
Additionally, this info may be helpful for you:

There is some useful discussion about this on another duplicate issue (which has been closed) https://github.com/Sequel-Ace/Sequel-Ace/issues/260#issuecomment-671483777

From @jamesstout:
> You can use Table->Advanced Filter Content (or ⇧⌘F)
> 
> Enter a value in one of the columns, then select search all fields:
> 
> ![Screenshot 2020-08-11 at 1 17 03 AM](https://user-images.githubusercontent.com/1576190/89811294-0a5ee500-db71-11ea-8ae8-3178ed00a25b.png)


For any further discussion, please see issue #152
