### ISSUE TITLE
SPMySQL framework libraries linked by Xcode project are all only built for x86

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#401]
These three libraries need to be replaced with universal binaries that support ARM and X86. We cannot build for Apple Silicon until these three libraries are updated with universal compiles.
- libcrypto.1.1.dylib
- libmysqlclient.a
- libssl.1.1.dylib

**Comment by stychos** [comment]
Maybe useful:
- libcrypto + libssl: https://gist.github.com/tmiz/1441111
- libmysql: https://bugs.mysql.com/bug.php?id=23701 (Suggested fix section)

Maybe I'll have some time at weekend to test. But not sure now :(

**Comment by robinkunde** [comment]
I'm gonna take a stab at openssl, since I'm in build hell right now anyway

**Comment by stychos** [comment]
Oh lol, just noticed my link for SSL is for i386 -> amd64 transition. Sorry.

**Comment by robinkunde** [comment]
Not having any luck so far. I need to install the latest Big Sur beta, and try it there. Won't be able to do that until Sunday tho.

**Comment by jamesstout** [comment]
Seems like, after adding the new configuration for ARM Macs, this:

```
./Configure darwin64-arm64-cc --prefix="/tmp/openssl-arm" no-asm
make
make install
```

builds both archs. No need for the `lipo` steps

**Comment by jamesstout** [comment]
First attempt following instructions in the link.

`libcrypto.1.1.dylib` and `libssl.1.1.dylib`

[dylibs.tar.gz](https://github.com/Sequel-Ace/Sequel-Ace/files/5395718/dylibs.tar.gz)

**Comment by Jason-Morcos** [comment]
> First attempt following instructions in the link.
> 
> `libcrypto.1.1.dylib` and `libssl.1.1.dylib`
> 
> [dylibs.tar.gz](https://github.com/Sequel-Ace/Sequel-Ace/files/5395718/dylibs.tar.gz)

@jamesstout AWESOME! Those both aren't throwing any warnings on Apple Silicon compile! Only one left is the libmysql one
Opened a PR to switch the two you built #412

**Comment by Jason-Morcos** [comment]
Correction, libmysqlclient.a might not be done yet so leaving issue open

**Comment by Jason-Morcos** [comment]
Looks like ShortcutRecorder is also not build universal. So ShortcutRecorder.framework and libmysqlclient.a are the two blocking ARM native support ATM

**Comment by samuelbradshaw** [comment]
> Looks like ShortcutRecorder is also not build universal. So ShortcutRecorder.framework and libmysqlclient.a are the two blocking ARM native support ATM

Is Sequel Ace using https://github.com/JanX2/ShortcutRecorder?

If so, there's a forked version that's been updated more recently, and supposedly supports ARM, here:
https://github.com/Kentzo/ShortcutRecorder

I don't know how it's determined, but according to this page, version 3.3.0 supports macOS (ARM):
https://swiftpackageindex.com/Kentzo/ShortcutRecorder

**Comment by Jason-Morcos** [comment]
The license file links to this one - https://code.google.com/archive/p/shortcutrecorder/
But I'm not sure exactly

**Comment by Jason-Morcos** [comment]
Looks like the Kentzo one includes a CocoaPod. So if we want to keep implementation as is, probably simplest thing is to add the pod to the main-3_0_0 branch (as a PR), remove the existing static framework, and make any migration changes needed. Possibly just a drop-in.
https://github.com/Kentzo/ShortcutRecorder

**Comment by jamesstout** [comment]
> Possibly just a drop-in.

Tried it, it's a bit more tricky than expected...

**Comment by jamesstout** [comment]
I've almost got `libmysqlclient.a` building for ARM.

It needs:

- [x ] `libsssl`
- [x ] `libcrypto`
- [] `libevent`

I couldn't get `libevent` to build for ARM on my non-ARM Mac. The Homebrew people say it builds but I can't find the formula.

Is anyone else looking at this?

**Comment by Jason-Morcos** [comment]
> I've almost got `libmysqlclient.a` building for ARM.
> 
> It needs:
> 
> * [x ] `libsssl`
> * [x ] `libcrypto`
> * [] `libevent`
> 
> I couldn't get `libevent` to build for ARM on my non-ARM Mac. The Homebrew people say it builds but I can't find the formula.
> 
> Is anyone else looking at this?

Awesome progress, @jamesstout! I don't think anyone else is looking at this, and I'm away from my ARM Mac and primary computer for the next couple weeks for medical reasons so can't provide much ARM-mac assistance, but in ~mid December I will be able to test things. And I believe @Kaspik has access to an ARM Mac now!

**Comment by Kaspik** [comment]
I'm almost done compiling libmysql too as the acript is still in repo and just needs to add arch arm64... 😅 I do have M1 MacBook already, so if you have some branches, just DM me what you need :)

**Comment by Kaspik** [comment]
Aaaaand here we are, Apple Silicon / M1 native! 🎉
