### ISSUE TITLE
Can't Archive 2.1.0

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#41]
The current dev branch (2.1.0) can't be archived.
After doing a clean build folder, running archive errors with a `error: install_name_tool: can't open file: SPMySQL (No such file or directory)` error.

<img width="1583" alt="Screen Shot 2020-06-21 at 18 32 50" src="https://user-images.githubusercontent.com/10710367/85236645-bac03080-b3ed-11ea-9d1a-fb299d1c42f4.png">

This seems to be related to #38, @gboudreau?

**Comment by gboudreau** [comment]
I guess I'm missing double-quotes on the `cd ...` command in the script I added!
