### ISSUE TITLE
The console window will automatically pop up when import a csv file

### ISSUE THREAD

**Issue by bpzhang** [Sequel-Ace/Sequel-Ace#410]
- Sequel Ace Version:
Version 2.2.1
build 2101
- macOS Version:
Version 10.15.7 
- MySQL Version:

**Description**

**Steps To Reproduce**
1. create table 
2.import *.csv file

then: 
The console window will automatically pop up

**Comment by jamesstout** [comment]
Is there an error also when importing?

**Comment by stychos** [comment]
> Is there an error also when importing?

Used it few times, import is fine.

**Comment by jamesstout** [comment]
As far as I can tell, the console only pops up when there is an error.

However, the error wasn't written to the console so it's not clear why it's popped up. I've added the errors to the console, so you now see the errors in red.
