### ISSUE TITLE
Copy tables between databases

### ISSUE THREAD

**Issue by llamafilm** [Sequel-Ace/Sequel-Ace#414]
One of my most common operations is copying an entire table from one database to another.  This is easy in phpMyAdmin, but I can't find any way to do it in Sequel Ace.  I need an exact duplicate with structure and content.  If the table is less than 1000 rows then I can highlight them and `Copy as SQL INSERT` but I often have more than 1000 rows.
If the data is very large, it should be duplicated on the server side, to avoid excessive network bandwidth copying and pasting to the local clipboard.

**Comment by Jason-Morcos** [comment]
Well as a way to duplicate (albeit not server-side), what about right clicking on the table in the sidebar and selecting export->As SQL dump and exporting with both the structure and content boxes checked? That will give you a SQL file with structure and content that you can import on the other DB to import the table

**Comment by samuelbradshaw** [comment]
If you right-click the table on the left, there's an option "Duplicate Table…". You could duplicate the table, then use an ALTER TABLE command to move the copy to a different database (https://stackoverflow.com/questions/15558461/move-table-from-one-database-to-another-in-mysql).

**Comment by llamafilm** [comment]
@Jason-Morcos  Dumping locally will take a long time if the data is large over a network connection.
@samuelbradshaw thanks, that seems to work fine.  But I have to type out the name of the database which is prone to errors.  It would be great to have this built in so when you duplicate the table, the dialog box lets you specify a different database.
