### ISSUE TITLE
[Release 3.0.0] Dropping macOS 10.10 and macOS 10.11 + near future plans

### ISSUE THREAD

**Issue by Kaspik** [Sequel-Ace/Sequel-Ace#425]
Good afternoon community!

We are really happy to see that you like SequelAce and we are already planning things for near future as well as long-term. As you might notice, there is still only few of us (4-6 people working on it in their free time) and it's pretty hard to do all the stuff community wants and needs together with major infrastructural changes, rewriting the project to ARC, fixing warnings about deprecations and (we would love to) moving fully to AutoLayout - well - saying "pretty hard" is not enough - it's almost impossible. 😄 

In order to move faster, introduce new things, and make it easier for us to develop, we decided to drop macOS 10.10 and macOS 10.11 in next major release 3.0.0. We also want to include Crashlytics for easier debugging and it requires macOS 10.12 as a minimum SDK, which just helped our decision.
Project tracking current progress of 3.0.0 is [here](https://github.com/Sequel-Ace/Sequel-Ace/projects/5)

We are still working on 2.x.x release (project [here](https://github.com/Sequel-Ace/Sequel-Ace/projects/6)) and we won't release 3.0.0 in near future. We will be just working on that alongside current `main` branch with current releases.

That said - if there are some crucial bugs that should be fixed before dropping there systems, let us know by creating an Issue and we will prioritize that.
If there won't be much stuff to do (then great!), we will focus on 3.0.0 so we can give you even better experience sooner rather than later.

Thanks for being with us and stay tuned!

Cheers,
SequelAce team ♠️

**Comment by Briones** [comment]
Thanks for the great work! I'm glad that this project is getting more support than the original one! Congrats! 🚀

**Comment by Kaspik** [comment]
2.3.1 is the last macOS 10.10 and 10.11 release, project officially switched to version 3.0.0 that is macOS 10.12+.

**Comment by Kaspik** [comment]
Released another version 2.3.2 with bug fixes.
