### ISSUE TITLE
Issue in customizing filename while exporting data

### ISSUE THREAD

**Issue by xingmungwa** [Sequel-Ace/Sequel-Ace#431]
- Sequel Ace Version: 2.2.2 Build 2104
- macOS Version: 10.15.7
- MySQL Version: 8.0

**Description**
While trying to export a table or procedure, there is an option to customize the filename, while typing in the field, after every character the cursor jumps to the end of line. So one needs to drag it back to the position one intends to type at.

**Steps To Reproduce**
1. Right click on any table or procedure or function, select any of the options under the export drop down
2. Expand on the "Customize Filename" arrow
3. Start typing a filename, type one character and wait for a second and see the cursor jumping to the end of the line before you can type the next character.

[Screen Recording 2020-10-24 at 10.18.20.mov.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/5432426/Screen.Recording.2020-10-24.at.10.18.20.mov.zip)

**Comment by jamesstout** [comment]
There's a piece of code that tries to tokenize the custom string (i.e. covert `{database}` to the blue token), but it's triggered:

```
// if we are currently inside or at the end of a string segment we can
// call for tokenization to happen by simulating a return press
```

I think is should just be at the end, or after a closing `}`

**Comment by jamesstout** [comment]
I've gone with: only attempt tokenization if string contains a { or }
