### ISSUE TITLE
Inserting NULL into a field

### ISSUE THREAD

**Issue by wlkns** [Sequel-Ace/Sequel-Ace#435]
- Sequel Ace Version: 2.2.2 build 2104
- macOS Version: Catalina 10.15.7
- MySQL Version: 5.7.31

**Description**

**Steps To Reproduce**
1. Type NULL into any nullable field

**Expected Behaviour**

The field to be set to NULL as it is nullable, instead the text NULL is inserted. In PHP `NULL !== "NULL"`.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Yes

**Additional Context**

This previously worked for years in Sequel Pro, and still does.

**Comment by stychos** [comment]
Are you typing in uppercase? String **null** is not `NULL` here.

Default NULLs:
<img width="96" alt="Screenshot 2020-10-26 at 15 03 20" src="https://user-images.githubusercontent.com/1531639/97175639-7dedb700-179c-11eb-9e64-dbff74cb8487.png">

Filled few values:
<img width="113" alt="Screenshot 2020-10-26 at 15 03 38" src="https://user-images.githubusercontent.com/1531639/97175655-8514c500-179c-11eb-8e6c-7c743fc4acaf.png">

Reverting to NULLs:
<img width="114" alt="Screenshot 2020-10-26 at 15 03 53" src="https://user-images.githubusercontent.com/1531639/97175674-8c3bd300-179c-11eb-9a54-ceb98bd8817e.png">

**Comment by wlkns** [comment]
My mistake, I think for whatever reason the field wasn't NULLABLE, as this seems to be working now.

Sorry!
