### ISSUE TITLE
Setting time zone doesn't change datetimes in selects

### ISSUE THREAD

**Issue by mr-mmmmore** [Sequel-Ace/Sequel-Ace#439]
```
- What version of Sequel-Ace are you using?      2.2.2 build 2104
- What version of macOS are you running on?      10.14.6
- What device(s) are you using Sequel-Ace on?    MacBook Pro
```

Hi,

I was happy to discover the new time_zone feature (added by https://github.com/Sequel-Ace/Sequel-Ace/pull/307) and have tried it straight away, but I see no effect. Here is what I do:

1. Set the time zone of a connection to GMT (the server and my system are on CEST), save and connect
2. Run the query `SELECT NOW();`

--> The result is displayed in my time zone instead of GMT. Isn't the goal of this feature to replace the need for calling `SET time_zone=xxxx` when opening a session? If so, the datetimes should be displayed in the set time zone.

I have tried with some other time zones and always get the same result.

Also what I would like to set is actually UTC, not GMT: what I am willing to do is seeing the actual datetimes stored in the DB (which are in UTC), not working in a specific time zone. I think this feature should help in this. Do you think it's possible to add UTC to the list?

**Comment by Kaspik** [comment]
@robinkunde Feedback for #307 :)

**Comment by jamesstout** [comment]
Hmm, can't replicate.

Can you show the output from:

`SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
`

and

`SELECT COUNT(*) FROM mysql.time_zone_name;`

**Comment by jamesstout** [comment]
> Also what I would like to set is actually UTC, not GMT: what I am willing to do is seeing the actual datetimes stored in the DB (which are in UTC), not working in a specific time zone. I think this feature should help in this. Do you think it's possible to add UTC to the list?

Strange, [knownTimeZoneNames](https://developer.apple.com/documentation/foundation/nstimezone/1387223-knowntimezonenames?language=objc) doesn't contain UTC, but 

`SELECT * FROM mysql.time_zone_name WHERE NAME LIKE '%UTC%'`

does...

**Comment by robinkunde** [comment]
Ok, a couple of things:
- While there are subtle differences between UTC and GMT, they provide the same offset.
- We get the list of timezones from macOS where UTC is an alias for GMT. That's also why UTC is not in the list.
- AFAIK, timezone support on the server sides is implemented through a set of tables in the `mysql` database. I believe that if the `mysql. mysql.time_zone_name` table (which you probably need to be root to access) is empty, the server would always defer to system time.
- existing values in `date` and `datetime` columns are unaffected by changes to the timezone. 
- I'm not neccessarily opposed to manually adding UTC to the list, but it doesn't seem like it would make a difference here.

Questions:
1. Can you check the Sequel Ace console to see if the `SET time_zone = 'XXX'` command is being executed?
2. Does it work as expected if you run the command yourself?
3. Can you reproduce the issue on other servers?

**Comment by mr-mmmmore** [comment]
>     1. Can you check the Sequel Ace console to see if the `SET time_zone = 'XXX'` command is being executed?

Yes, I can see `SET time_zone = 'GMT';`

>     2. Does it work as expected if you run the command yourself?

No, if i run above command, I get `Unknown or incorrect time zone: 'GMT'`. It works if I use `SET time_zone = "+00:00"`. I think it is because using time zone names instead of time zone offsets requires the `mysql.time_zone_name` table with those names, wich I don't have or is empty on the servers where I encounter the problem. 


>     3. Can you reproduce the issue on other servers?

Yes: I experience the same behavior on my local vagrant server and on an production server.

Also as @jamesstout asked for it:

> SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;

returns `SYSTEM	SYSTEM`

**Comment by robinkunde** [comment]
Interesting. Maybe the solution here is to set the offset instead of the timezone identifier, via https://developer.apple.com/documentation/foundation/nstimezone/1387221-secondsfromgmt. Thoughts? @jamesstout @Kaspik

**Comment by Jason-Morcos** [comment]
> Interesting. Maybe the solution here is to set the offset instead of the timezone identifier, via https://developer.apple.com/documentation/foundation/nstimezone/1387221-secondsfromgmt. Thoughts? @jamesstout @Kaspik 

How will that work with variable offsets (daylight savings time)?
What about requiring the MySQL timezones table, showing a warning if it cannot be found and instructing the user on how to set it up?
Also we could swap (manually) GMT with UTC in the list in a step when we're generating the list of timezones? UTC/GMT is a special case

**Comment by robinkunde** [comment]
It handles variable offsets based on the current date. I think a checkbox for sending offsets instead of identifiers might be less work that bubbling up the error to the UI (given the way that part of the app is written right now) and providing instructions for the most common setups. Instructions are of limited use anyway because not every user has admin access to the server configs.

**Comment by jamesstout** [comment]
`What about SELECT COUNT(*) FROM mysql.time_zone_name;?`

I'm wondering if your server has no timezones... @mr-mmmmore

**Comment by jamesstout** [comment]
> `mysql.time_zone_name` table with those names, wich I don't have or is empty on the servers where I encounter the problem.

Oh, you don't. Are you able to load them? `mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql` .. I guess not, hence the discussion of offsets

**Comment by jamesstout** [comment]
> Interesting. Maybe the solution here is to set the offset instead of the timezone identifier, via https://developer.apple.com/documentation/foundation/nstimezone/1387221-secondsfromgmt. Thoughts? @jamesstout @Kaspik

seems to work .. I tried this: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

**Comment by jamesstout** [comment]
> >  bubbling up the error to the UI (given the way that part of the app is written right now) 

I tried last night, the error occurs in the SQL framework, but all our alert code is in the app.

This is why we need remote logging :)

**Comment by mr-mmmmore** [comment]
> > `mysql.time_zone_name` table with those names, wich I don't have or is empty on the servers where I encounter the problem.
> 
> Oh, you don't. Are you able to load them? `mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql` .. I guess not, hence the discussion of offsets

I can't on the production server where I don't have the admin access. But anyway I think that making the feature depend on those rights and on updates of the mysql database  is excessive whereas it could work by only setting offsets.

> I think a checkbox for sending offsets instead of identifiers might be less work that bubbling up the error to the UI (given the way that part of the app is written right now) and providing instructions for the most common setups.

Another way would be to add the time offsets to the list.

**Comment by robinkunde** [comment]
I've relabed this as an enhancement, since it appears to be a matter for missing timezone's in the server.
Two action items:

1. Add the ability to alert the user if setting the timezone fails.
2. Add fallback that sets an offset instead of a timezone. Offset could be manually selected or we use the offset provided by macOS (that would also take care of DST).

**Comment by bytejedi** [comment]
- What version of Sequel-Ace are you using?      3.2.2 (3021)
- What version of macOS are you running on?      10.14.6
- What device(s) are you using Sequel-Ace on?    Mac mini(2018)

Hi! The Timezone issues appeared on my device.  
I have tried with some other time zones and always back to the UTC.

![image](https://user-images.githubusercontent.com/43159905/109284678-15523c00-785b-11eb-9f85-c4a26fd56070.png)
