### ISSUE TITLE
Readonly/Safe Mode

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#44]
Ability to open database in a readonly mode that forbids update

Possibly set some DB params to protect from hurting yourself

Like issue https://github.com/sequelpro/sequelpro/issues/2739

>It would be nice to have a feature to connect in read-only mode or at least to have an option to set the --i-am-a-dummy (--safe-updates) connection flag (https://dev.mysql.com/doc/refman/5.7/en/mysql-tips.html#safe-updates)

**Comment by anatolipr** [comment]
Also see https://github.com/sequelpro/sequelpro/issues/2615

**Comment by Dayjo** [comment]
Big fan of this feature request. It can be rather scary accidentally being connected to production :D

**Comment by jamesstout** [comment]
> sequelpro/sequelpro#2615

We sort of have this: https://github.com/Sequel-Ace/Sequel-Ace/pull/204

**Comment by jamesstout** [comment]
> > It would be nice to have a feature to connect in read-only mode or at least to have an option to set the --i-am-a-dummy (--safe-updates) connection flag (https://dev.mysql.com/doc/refman/5.7/en/mysql-tips.html#safe-updates)

Looks like `--safe-updates` is a query option, not a connection option. We could have a pref and then send `SET SQL_SAFE_UPDATES = 1` like we set the encoding. I'll try it out.

**Comment by jamesstout** [comment]
Well it works in the custom query window, but not in the content window if you right click and delete more than one row... still investigating.

**Comment by jamesstout** [comment]
@Jason-Morcos Do we want to do this? Add another pref to the connection view?

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos Do we want to do this? Add another pref to the connection view?

You added that thing to prompt before destructive actions already, yes? If so I don't think we need safe mode!

**Comment by jamesstout** [comment]
> You added that thing to prompt before destructive actions already, yes? If so I don't think we need safe mode!

Yes I did, but it's not triggered on the Content view if you select then delete rows .. .maybe I could add it there?

**Comment by Jason-Morcos** [comment]
> > You added that thing to prompt before destructive actions already, yes? If so I don't think we need safe mode!
> 
> 
> 
> Yes I did, but it's not triggered on the Content view if you select then delete rows .. .maybe I could add it there?

I like that plan! If that's any easier?

**Comment by jamesstout** [comment]
> I like that plan! If that's any easier?

Done in #559
