### ISSUE TITLE
 Link TIDB crashes

### ISSUE THREAD

**Issue by czhangjiang** [Sequel-Ace/Sequel-Ace#447]
- Sequel Ace Version:
- macOS Version: 10.15.7 (19H2)
- MySQL Version: 

**Description**

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Please try the [latest beta](https://github.com/Sequel-Ace/Sequel-Ace/releases). If the latest beta works, we've fixed the issue already and will get the fix out soon.

**Additional Context**

**Comment by stychos** [comment]
Sorry, it's unclear what your trouble is, marking this as invalid and closing.
