### ISSUE TITLE
DATA LOAD INFILE

### ISSUE THREAD

**Issue by serbanc66** [Sequel-Ace/Sequel-Ace#453]
- Sequel Ace Version:2.2.2 - build 2104
- macOS: 10.13.6
- MySQL: 5.6.14

With the new rel 2.2.2 basing on communication #394 the issue related to LOAD DATA LOCAL INFILE had to be solved, instead notwithstanding I flagged the checkbox in login I continue to have issues:

sql: LOAD DATA LOCAL INFILE '...../file.txt' INTO TABLE table

error:

File '......./file.txt' not found (OS errno 1 - Operation not permitted)

I am connecting to DB trought VPN Pulse Secure.

With Sequel Pro (night build or last release no issue)

**Comment by Jason-Morcos** [comment]
Sequel Ace still has to be granted access to the file before it works (due to sandboxing). Did you add the txt file to the files tab in Sequel Ace's settings?

**Comment by serbanc66** [comment]
Thanks,
Adding the file no more issue, but …. it isn't possible set an entire folder instead of singular file?


Il giorno 03 nov 2020, alle ore 15:36, Jason Morcos <notifications@github.com> ha scritto:


Sequel Ace still has to be granted access to the file before it works (due to sandboxing). Did you add the txt file to the files tab in Sequel Ace's settings?

**Comment by Jason-Morcos** [comment]
You should be able to add a folder there, I think?

If not, if you'll be using Infile a lot it way be worth turning on full disk access for Sequel Ace via system preferences.

Thanks!

**Comment by serbanc66** [comment]
Il giorno 03 nov 2020, alle ore 16:03, Jason Morcos <notifications@github.com> ha scritto:


You should be able to add a folder there, I think? NO only single file no Folder

If not, if you'll be using Infile a lot it way be worth turning on full disk access for Sequel Ace via system preferences. I am using 10.13.6, the feature is not on system preference

Thanks!
