### ISSUE TITLE
Query editor should prompt to save unsaved changes when close window

### ISSUE THREAD

**Issue by yg-dba** [Sequel-Ace/Sequel-Ace#455]
When closing a tab in the query editor, it's incredibly frustrating when you forget to save and lose your work.

It would be so appreciated if we can implement a prompt - "Do you want to save your changes?" when closing a tab or SequelPro.

Another related feature would be autosave.  I personally am okay without it, but I know others that rely on this feature in other clients.

**Comment by jamesstout** [comment]
Closing tab, done, closing app, bit more tricky....

**Comment by yg-dba** [comment]
Thank you so much for tackling this!

**Comment by jamesstout** [comment]
You think it should be a default, or an option in preferences?

**Comment by yg-dba** [comment]
In my opinion, it should be the default.  I think it's expected not to lose changes when closing the app.

**Comment by stychos** [comment]
> You think it should be a default, or an option in preferences?

Maybe an option enabled by default with a "Don't warn me again" checkbox?

**Comment by Kaspik** [comment]
There won't be any popup or modal, but we will save the query to query history automatically.  :)
