### ISSUE TITLE
Change Complete with Backticks --> Always Complete With Backticks

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#457]
Please rename the preference "Complete with Backticks" to be "Always Complete With Backticks".

Some people want to use backticks with every identifier. That's rare, but I guess HFWT.

Everybody else that is using autocomplete expects that backticks will be added automatically if required. e.g. if you have a table column named `varchar` for some reason then autocompleting `mytable.var...` should insert backticks when you accept the recommended text.

---

Alternatively there is a case to be made in UX design to always avoid checkboxes. If you subscribe to that idea then I recommend:

"Complete using backticks:"

- ( ) Always
- ( ) Only when required

**Comment by samuelbradshaw** [comment]
Is this issue as simple as changing a string, or does the behavior of the setting also need to change?
