### ISSUE TITLE
localhost gets replaced by 127.0.0.1 silently

### ISSUE THREAD

**Issue by julian-weinert** [Sequel-Ace/Sequel-Ace#459]
Im running SA 2.2.2 on macOS 10.14.6

In the past when typing "localhost" into the host name field Sequel displayed a warning with a choice given wether or not the host name should be replaced by "127.0.0.1".

The current Sequel Ace version seems to replace it silently without changing the host name field visibly.
I just ran into an issue where the hoster I'm trying to connect to only seems to have permissions for the MySQL user set on the literal "localhost" hostname.

Now Sequel Ace tries to connect to "user@127.0.0.1" and returns an access denied error.

**Comment by Jason-Morcos** [comment]
Sounds like this is not fixable - localhost is a socket always, 127.0.0.1 is an ssh target. https://github.com/sequelpro/sequelpro/issues/2904

**Comment by Jason-Morcos** [comment]
If someone is able to produce a PR that resolves this issue and doesn't break other things however, I am certainly open to merging some sort of fix.

**Comment by julian-weinert** [comment]
Maybe it is an illconfigured host.
I can only show what I experienced. I also experienced the same while being logged in via SSH on the host itself.
Whenever I try connecting using `127.0.0.1` access is denied and when I use `localhost` it is granted.

What do you mean by "localhost is a socket always, 127.0.0.1 is an ssh target"?

**Comment by julian-weinert** [comment]
Is there any other additional information I can provide (in reference to the label)?

**Comment by Jason-Morcos** [comment]
As I understand it, localhost is a socket connection (not ssh) whereas 127.0.0.1 is an IP-based connection. The issue is tagged with need more info here because someone would need to I investigate and understand the exact issue (is localhost really valid in this case) before fixing; whereas some issues we know the issue and proper fix right away, this one requires some investigating first.

**Comment by Kaspik** [comment]
@julian-weinert Question here - "silently" - are you not seeing the alert about "Use 127.0.0.0"?

**Comment by julian-weinert** [comment]
@Kaspik Exactly! I stated in in my original post, I may have not worded clearly enough.
The main reason why I'd like to get the alert is the option it gave to deliberately use the local hostname.

It might only be a strange fluke at the hosters end, but there's nothing I can do about it.
But if the case exists for me it very well may exist for other users too

**Comment by Kaspik** [comment]
The alert should be visible always you write "localhost" to the field. Curious if you tried 3.0.0 RC1 or any Beta?

**Comment by julian-weinert** [comment]
I just tried 3.0.0 RC1. I just discovered that it's the same.

BUT. I also discovered that I didn't mention SSH in my original question, only in the comments.
And when using SSH this alert does not come up.
Now since I saw the alert again it makes sense that it does not come up with an SSH connection, because it is about the socket stuff.

Unfortunately today I couldn't even login via the console anymore so I couldn't confirm the precise behaviour again.
I'll try it tomorrow again and keep you updated as soon as I find out more (the hoster is pretty weird unfortunately)

**Comment by Kaspik** [comment]
Any update on this from your side Julian? :)

**Comment by julian-weinert** [comment]
I can confirm my findings. I used Sequel to go via SSH onto the server.
The MySQL command returns a failed attempt to connect to `user@127.0.0.1` whereas I put `localhost` into the MySQL Host field.

The host is actually configured in a way the users only have access when connecting using `user@localhost`

**Comment by julian-weinert** [comment]
I ran the following commands on the Host via SSH:
```
$ mysql -u user -h 127.0.0.1 -p pass
> ERROR 1045 (28000): Access denied for user 'user'@'127.0.0.1' (using password: YES)

$ mysql -u user -h localhost -p pass
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Server version: 5.7.29 MySQL Community Server (GPL)
```

Using Sequel I entered `localhost` as MySQL host and the SSH credentials. The SSH connection succeeds and then this error comes up:
```
MySQL said: Access denied for user 'user'@'127.0.0.1' (using password: YES)
```

Note that the MySQL server denies an attempt to connect to the IP instead of localhost.

**Comment by Jason-Morcos** [comment]
I made a branch to attempt to allow users to make TCP/IP connections to localhost. However, it doesn't appear to work. As previously mentioned, the MySQL client portion appears to assume all localhost connections are socket connections. I'm not sure how (or if it's possible) to overwrite this behavior.
<img width="260" alt="Screen Shot 2021-01-08 at 07 51 48" src="https://user-images.githubusercontent.com/10710367/104035126-9e67c380-5186-11eb-8ee9-2eee09bb32cb.png">
Branch is called attempt-to-allow-localhost, @Sequel-Ace/all

**Comment by Jason-Morcos** [comment]
Actually, I think I figured it out! This PR would force Ace to connect via TCP/IP unless socket was specifically selected, and would allow entering localhost for the host field. https://github.com/Sequel-Ace/Sequel-Ace/pull/765

**Comment by Jason-Morcos** [comment]
The next update should include full support for using localhost for TCP/IP connections! Stay tuned for a new beta this week.

**Comment by julian-weinert** [comment]
Thanks a lot, @Jason-Morcos! I'm looking forward to it.

**Comment by julian-weinert** [comment]
Uhm... I'm running into the issue again, @Jason-Morcos. I've never come around to properly test the release since I had a workaround and didn't need to touch this weird host anymore – until now.
I'm having the issue when connecting via SSH. Would it be possible to apply the same patch to SSH connections as well?

**Comment by julian-weinert** [comment]
Sorry, but for me a software replacing my user input silently is a bug.
Yes. Specific to entering "localhost" to have it silently replaced by "127.0.0.1". Silently, without leaving me the option.

This is *exactly* what I came across here as well. I enter "localhost" and the thing connects to "127.0.0.1". But I want to connect to `localhost`, not 127.0.0.1.

Software should NEVER try to be smarter than the user, that will always lead to confusion.
Simple software design principle.

I will open another issue if you really need that. But honestly I don't understand the endless discussion around this.
The software does something unexpected. That shouldn't be the case.

**Comment by Jason-Morcos** [comment]
> Sorry, but for me a software replacing my user input silently is a bug.
> 
> Yes. Specific to entering "localhost" and having it silently replaced by "127.0.0.1". Silently, without leaving me the option.
> 
> This is *exactly* what I came across here as well. I enter "localhost" and the thing connects to "127.0.0.1". But I want to connect to `localhost`, not 127.0.0.1.
> 
> 
> 
> I think I explained in much detail how I encounter this issue. But for you I'll quote myself here
> 
> 
> 
> > I can confirm my findings. I used Sequel to go via SSH onto the server. The MySQL command returns a failed attempt to connect to `user@127.0.0.1` whereas I put `localhost` into the MySQL Host field.
> 
> > 
> 
> > The host is actually configured in a way the users only have access when connecting using `user@localhost`
> 
> 
> 
> Just setup an MySQL user on your server with access rights ONLY over `localhost` and then try to access it via Sequel Ace. You will not be able to.

The latest version of sequel Ace doesn't do this. Are you talking about sequel Ace 2? We aren't supporting sequel Ace 2 anymore and this behavior has changed in SA3

**Comment by pioz** [comment]
Hi, I'm still experiencing this issue. It hasn't been resolved on my side yet and continues to occur under the same conditions described previously. My database (for which I cannot change the grants) only allows access for `localhost`. However, when I set `localhost`, it gets replaced with `127.0.0.1`, which results in an "Access denied" error due to the grant mismatch.
