### ISSUE TITLE
Version 2.2.2 Build 2104 - Crashes on launch (Mac OS 10.11)

### ISSUE THREAD

**Issue by joomlabeat** [Sequel-Ace/Sequel-Ace#473]
- Sequel Ace Version: 2.2.2
- macOS Version: 10.11
- MySQL Version:

Description
Just updated to latest version available in Appstore - tried to open the application - no application window opens - only the menus. Clicking for a second time on the app icon on the dock, or clicking the menu for a new connection window - the app crashes.

**Comment by Kaspik** [comment]
Can you try latest beta/RC from https://github.com/Sequel-Ace/Sequel-Ace/releases and let us know?

And FYI, we are gonna drop 10.11 soon: https://github.com/Sequel-Ace/Sequel-Ace/issues/425

**Comment by Jason-Morcos** [comment]
As to reverting to a previous version, you can download a previous release manually from the releases page on GitHub.


https://github.com/Sequel-Ace/Sequel-Ace/releases
