### ISSUE TITLE
please enhance the speed of auto complete in query~

### ISSUE THREAD

**Issue by ysnows** [Sequel-Ace/Sequel-Ace#474]
please enhance the speed of auto prompt in query~

-- thanks for your wonderful work

**Comment by jamesstout** [comment]
related: #269 #366

I've made a start: https://github.com/Sequel-Ace/Sequel-Ace/commits/improve-query-history-search

**Comment by Kaspik** [comment]
Duplicate of https://github.com/Sequel-Ace/Sequel-Ace/issues/269 as mentioned, I'll close this one. :)

**Comment by Kaspik** [comment]
Moving to Done as this has been improved.
