### ISSUE TITLE
Dragging/dropping a query favorite isn't working

### ISSUE THREAD

**Issue by aardloper** [Sequel-Ace/Sequel-Ace#475]
- Sequel Ace Version: 2.2.2, Build 2104
- macOS Version: 10.15.5
- MySQL Version: 8.0.22

**Description**
Dropping a favorite item in Query Favorites will not move it on the cursor position.

**Steps To Reproduce**
1. Go to tab Query
2. Go to pull down Query Favorites
3. Choose Edit Favorites...
4. Drag an item title to another position
5. A horizontal line appears between the lines at the cursor position 
5. Drop the item (release of the mouse button)
6 Nothing happens

**Expected Behaviour**
Move the item to the cursor position after a drop.

**Comment by Kaspik** [comment]
2.3.1 is out 🚀
