### ISSUE TITLE
Query Editor should remain open even if the database is no longer accessible

### ISSUE THREAD

**Issue by bb-seamus** [Sequel-Ace/Sequel-Ace#479]
I'm tired of losing my work in thee query editor. Far too often I take my laptop someplace to work and I switch to Sequel Ace to work on a query, my database can't be reached from this public IP, and so Sequel Ace closes.

Steps to recreate:
1. Open a valid connection in sequel ace. 
2. Write a query in the query editor.
3. Disable the connection to the database somehow. ie. If local, end the mysql process. If remote, just turn off your wifi. 
4. Switch back to sequel ace and start working with your query again. 
5. After a few seconds, it'll seize up, tell you it can't reach the database.
6. If you can't reconnect, it'll close the active window and your query work is gone. 

Possible solutions: 
- Keep the window open, but disable the sidebar and the results. Attempts to run a query will cause an alert window announcing that the database is currently unreachable.
- Make the queries in the query editor persistent. The next time I open that connection, my previous queries would be recovered. There are issues here that may be annoying/risky security-wise, so I'd lean toward the first solution. 
- Make the query editor a separate window. I would open a connection window and pop out the query editor. If the connection fails, the connection window disappears but the editor window persists.

**Comment by Kaspik** [comment]
Latest release 2.3.0 is saving query to recet queries when closing the window so you don't loose your work.

**Comment by Jason-Morcos** [comment]
2.3.0 is now released
