### ISSUE TITLE
Show warning if trying to connect to unsupported MySQL version host

### ISSUE THREAD

**Issue by lostminds** [Sequel-Ace/Sequel-Ace#482]
I recently discovered that connecting to a MySQL 5.5 host is not supported in recent versions of Sequel Ace. That's fine I guess, since it's an old version. However, it currently doesn't tell you that's the problem when it fails to connect. Instead you get an SQL error message about the SSL key being too short (see #476), which was confusing to me. 

So my suggestion is simply that if you can detect/guess the MySQL version of the host during the connection and see that it's an unsupported version of MySQL, show a warning explaining that to the user.

**Comment by Jason-Morcos** [comment]
I don't think we can detect or guess the MySQL version until we've connected to the MySQL host, something that fails on incompatible hosts but also can be a legitimate error on mis-configured compatible hosts.

I can leave this open in case someone has some great idea on how to do so, but I don't think this is possible

**Comment by lostminds** [comment]
Yeah, I did some looking and all methods I found were for getting the version once the connection had been established, so you could be right about that. 

But maybe there is some way to do a handshake of some sort, or cases where the initial connection might be successful but later actions fail due to the unsupported host version. So I figured something like this could still be useful then to help the user figure out what's going wrong.

**Comment by Kaspik** [comment]
I don't think anyone is going to take a look on this and it's really low priority / edge case. I'll close this. :)
