### ISSUE TITLE
Cannot change QUERY EDITOR font / font size on Big Sur

### ISSUE THREAD

**Issue by matthewrk** [Sequel-Ace/Sequel-Ace#487]
- Sequel Ace Version: 2.3.0 Build 2111 (via app store)
- macOS Version: 11.0.1 Big Sur

**Steps To Reproduce**
1. Go to Sequel Ace > Preferences, Click Query Editor
2. Click Select to open the font dialog
3. Change font and font size, observe change not persisted in Font textbox on Sequel Ace and no changes to font in main query editor window

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Present in latest release, 2.3.0, 11th Nov 2020 - https://github.com/Sequel-Ace/Sequel-Ace/tree/2.3.0

**Additional Context**
Have also tested in Sequel Pro to make sure my expectations on when the font should change (or how to correctly use the dialog) are correct. In Sequel Pro when changing the font in the font dialog the textbox labelled Font in preferences immediately changes, as does the font from the main query editor window.

**Screenshot of the issue in Sequel Ace:**
<img width="1488" alt="Screenshot 2020-11-13 at 13 21 55" src="https://user-images.githubusercontent.com/998908/99076822-b0c4e700-25b3-11eb-8a29-cabca6773c80.png">

**Comment by Kaspik** [comment]
We see some issue where if you close the text selector then open it again (maybe even close the preferences itself) fixes this issue, and I'm not able to find why it's happening (though I was trying the font in "General" tab - not the Query one).

One thing we know is that Apple deprecated (and maybe even removed already) `changeFont` delegate method, so it doesn't really inform the app realtime, and I had to find a workaround for the main general font settings.... https://developer.apple.com/documentation/objectivec/nsobject/1462311-changefont

I'll take a look on the query editor, in the meantime try couple of times closing / reopening the settings window, or double tapping on the font size.

**Comment by matthewrk** [comment]
I couldn't get around it by opening/closing preferences or restarting the app. I can confirm this works though and is reproducible for me:

1. Open app
2. Go to Preferences > Query Editor
3. Attempt to change font - observe not working
4. Go to General tab
5. Attempt to change font - observe working
6. Go back to Query Editor tab
7. Attempt to change font - observe working

I don't know much about programming mac desktop apps but id assume some kind of delegate/event issue overlap with the main font editor dialog, so that's why doing that one first activates the query editor one... that would be a total uneducated guess though.

**Comment by Kaspik** [comment]
Yeah the change by Apple is somehow confusing on Big Sur... we will investigate, I'm happy the new font change on General tab worked! :)

**Comment by CodeBrauer** [comment]
Happens also in Catalina 10.15.7 - workaround available

**Comment by JonLaliberte** [comment]
Yep, happens on Catalina for me as well.

https://user-images.githubusercontent.com/5403662/103028285-742aca80-4525-11eb-908b-34266afba065.mov

**Comment by jamesstout** [comment]
@Kaspik I think I may have fixed this. Could you please check out the PR - #757
