### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by aradapilot** [Sequel-Ace/Sequel-Ace#488]
Like it says on the tin.  This is great UI design, we used to use sequelpro on macs, and I'd love to see a linux build of this to use today.

**Comment by Jason-Morcos** [comment]
This is a substantially sizable effort and not in our current plans or anywhere in the foreseeable future. If someone wants to develop a Linux variant, they should fork this project and begin to do so. We'd be happy to aid such a person, but can't dedicate such a huge effort to another operating system and still deliver a quality Mac app.

**Comment by Kaspik** [comment]
Or rather than fork let us know so we can chat it through on Slack! :)

**Comment by aradapilot** [comment]
Understood.  No bandwidth for this on our end right now, but I'm always pushing for the company to do more FOSS work.  It's a giant slow moving machine - still, maybe I can justify it in the future.  If anyone else does first, that'd be lovely, I'll keep watch on this project.
