### ISSUE TITLE
Big Sur Preferences Menu Bar Truncated

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#496]
The app prefs menu is a little funky on Big Sur and could use some TLC so users don't have to hit a funky button to see all the tabs

<img width="710" alt="Screen Shot 2020-11-14 at 13 31 20" src="https://user-images.githubusercontent.com/10710367/99157464-de766280-267d-11eb-942d-cd7cdac8523a.png">

**Comment by Kaspik** [comment]
2.3.1 is out 🚀
