### ISSUE TITLE
Spanish localization

### ISSUE THREAD

**Issue by pulsedrivervstibby** [Sequel-Ace/Sequel-Ace#499]
Hallo,

i see that this project is forked from Sequel Pro.

I have translated into Spanish and I would like to include the translation of sequel pro and contribute with the translation of Sequel Ace.

Can you include in source code the strings files?

I wait your answer.

Thank you for all. PvD.

**Comment by Jason-Morcos** [comment]
I'm personally not very familiar with what multi-language support looks like in macOS apps so if someone else wants to take charge and make this a reality I'd be happy to take a look at a PR but don't feel very comfortable setting up that architecture myself.

**Comment by pulsedrivervstibby** [comment]
Hello Jason,

this article can help you to create all files to localize Sequel Ace:

https://help.apple.com/xcode/mac/current/#/deve2bc11fab

I wait your answer.

Regards.

**Comment by Jason-Morcos** [comment]
> Hello Jason,
> 
> this article can help you to create all files to localize Sequel Ace:
> 
> https://help.apple.com/xcode/mac/current/#/deve2bc11fab
> 
> I wait your answer.
> 
> Regards.

I would be happy to review a PR which begins to implement localization, but I will personally not be the one creating such a PR at this time. Things are quite busy working on Big Sur and Apple Silicon support so localization is relatively not a priority at this time. However, if someone with passion wants to create a PR that begins this process and does some or all of the steps described (without breaking things), I would be very willing to take look, provide feedback, and merge if acceptable. Thank you.

**Comment by Kaspik** [comment]
I'll take a lead on this now as things are bit more stable and I'll be more than happy to get some people onto it if they want! :)

I'll create project on Crowdin (https://crowdin.com) as I'm mostly familiar with that and they can give us license for Open Source for free.

@pulsedrivervstibby Will you be interesting in translating there? If so, can you also in the meantime send us the translations you did so I can upload them too?

**Comment by pulsedrivervstibby** [comment]
Hello Kaspik,

I work with crowdin for the Vienna project and transifex for the Wireshark project but in other projects I only work with strings files because for me it is the best way to work, when I have translated one file I send it to the developer and he merges it with the project.

I would like that you include in the resources folder the es.lproj folder with all the strings files to begin working with them and I can build the app to test my translation.

Thank you for all.

Regards.  PvD.

**Comment by Kaspik** [comment]
@pulsedrivervstibby Thanks for your interest! I opened (and will merge) a PR with Spanish localization.

However, I would love to use Crowdin. There is multiple reasons (versioning, multi-people cooperation, typo-fixes, translation offers etc. The project is here: https://crowdin.com/project/sequel-ace

If you give me your email, I'll invite you as a translator. :)

**Comment by Giuliano-sn** [comment]
Hello @Kaspik !
I would like to contribute with Portuguese (Brazilian) localization.
May you add that in crowdin?

**Comment by Kaspik** [comment]
Yep, please open new Issue for me so I don't forget. :)
