### ISSUE TITLE
Bug: Pressing enter key while filter option is active doesn't apply filters

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#50]
If I start adding a filter with a text field to provide input (like where IN) and then press the enter key while active in that text field, the table reloads but the filter doesn't actually apply. This seems strange. I think an enter key press from within filters should cause all filters to be applied and _then_ table reloaded

**Comment by gboudreau** [comment]
@Jason-Morcos `Fixed & Pending Release` label added by error here?

**Comment by Jason-Morcos** [comment]
@gboudreau I tried to replicate it on the latest dev and it appears to me to be fixed by your filters fixes! Do you have this issue on latest dev? If not can close out with 2.1. release

**Comment by gboudreau** [comment]
Indeed, can't reproduce.
