### ISSUE TITLE
Big Sur table name random grey

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#500]
This randomly happens on Big Sur, some table names are grey. Sometimes its 1 tables, sometimes a lot of tables.

<img width="94" alt="Screenshot 2020-11-16 at 10 30 44" src="https://user-images.githubusercontent.com/25279400/99235975-daba1b80-27f6-11eb-8529-e9a045f35abf.png">

**Comment by Kaspik** [comment]
Unfortunately known issue... it's a "cosmetic" thing, so not the highest priority, but we are aware of that. 😞

**Comment by Kaspik** [comment]
I'm not seeing this on macOS 11 nor 12, are you?
