### ISSUE TITLE
Sort foreign key table list alphabetically

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#502]
Would be really useful if the table list was sorted alphabetically in the FK creation form

<img width="305" alt="Screenshot 2020-11-16 at 12 11 50" src="https://user-images.githubusercontent.com/25279400/99246097-05ab6c00-2805-11eb-83c8-896b952bee76.png">

**Comment by Kaspik** [comment]
Related to https://github.com/Sequel-Ace/Sequel-Ace/pull/498 - @robinkunde you wanna take a look? :)

**Comment by Jason-Morcos** [comment]
I believe this is fixed, but if not toggle it back to not fixed @robinkunde

**Comment by Kaspik** [comment]
2.3.1 is out 🚀

**Comment by cappadaan** [comment]
This is not fixed in 2.3.1, still same unsorted list

**Comment by Jason-Morcos** [comment]
This change will not be released until version 3.0. I apologize for the inconvenience!

**Comment by Kaspik** [comment]
We are now closing issues as they got fixed on master. Closing this in favor of that, release 3.0.0 will be out probably next week.
