### ISSUE TITLE
Row count shown as Kib

### ISSUE THREAD

**Issue by endelwar** [Sequel-Ace/Sequel-Ace#504]
- Sequel Ace Version: 2.3.0
- macOS Version: 10.15.7
- MySQL Version: 5.7.32

**Description**
Row count and row selected number are treated as byte count

**Steps To Reproduce**
1. select a table on left
2. look at numbers on bottom

**Expected Behaviour**
Numbers should be displayed as number without unit of measure

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No beta ATM

<img width="803" alt="Schermata 2020-11-16 alle 22 51 33" src="https://user-images.githubusercontent.com/28512/99312924-083aaf80-285f-11eb-8981-1c32a85a92c8.png">

**Comment by corecoding** [comment]
Thank you. I noticed this the other day.

**Comment by SumBeam** [comment]
I would like to take a look at this one, if thats ok with the other developers :)

**Comment by Kaspik** [comment]
2.3.1 is out 🚀

**Comment by felixkempf** [comment]
Even with 2.3.1, I still have this issue in both the table information as well as the bottom info area.

Sequel Ace Version: 2.3.1 (Build 2117)
macOS Version: 10.14.6
MySQL Version: 5.7.32 

mysql was just updated, restarted OS, tried a manually downloaded Sequel Ace as well (normally using the App Store version)

<img width="819" alt="Screenshot 2020-11-23 at 18 13 20" src="https://user-images.githubusercontent.com/8512231/100015275-02514b00-2dd8-11eb-8865-572649756a8d.png">

**Comment by SumBeam** [comment]
Oh! I think I see the issue. I made my fix for 3.0.0 version and not for 2.3.1, so that explains why you still see this behaviour.

**Comment by Kaspik** [comment]
Yes, sorry, this is closed but for 3.0.0 release probably next week. :)

**Comment by felixkempf** [comment]
oh, thanks for the clarification. I clearly misunderstood https://github.com/Sequel-Ace/Sequel-Ace/issues/504#issuecomment-730979944 as in "it was fixed with that version".

**Comment by Kaspik** [comment]
Released 2.3.2 hotfix, available in the AppStore already.

**Comment by endelwar** [comment]
@Kaspik will it be released as compiled asset in release section?

**Comment by Kaspik** [comment]
Yes, once James wakes up to notarize the build, I don't have certificates here. :)

**Comment by jamesstout** [comment]
Wait what do I need to do?

**Comment by Kaspik** [comment]
lol, Jason, not James 😂

**Comment by endelwar** [comment]
😂😂😂
