### ISSUE TITLE
Have a preference to "Force LONGTEXT to be edited inline, hold option while double clicking for popup view"

### ISSUE THREAD

**Issue by lonkle** [Sequel-Ace/Sequel-Ace#508]
I, honestly, have wanted this since this app was Sequel Pro. I have **so many** (almost all) fields (especially in Wordpress) that are labeled as `LONGTEXT` when they're honestly just a few bytes long (sometimes even a boolean). You know what would be even smarter, for Sequel Pro to **detect** the amount of bytes a field is actually using and edit it inline if it's within a number of characters (set by the user but default could be something sane). What do you guys think?

**Comment by lonkle** [comment]
If no current developer has interest in adding this slight tweak. I wouldn't mind PR-ing it. Does any developer on here have guidance as to which file needs edited to make this a possibility. I can RE that myself but if anyone knows off the top of your head. Lemme know. :)

**Comment by Jason-Morcos** [comment]
> If no current developer has interest in adding this slight tweak. I wouldn't mind PR-ing it. Does any developer on here have guidance as to which file needs edited to make this a possibility. I can RE that myself but if anyone knows off the top of your head. Lemme know. :)

If the change is to selectively choose whether or not to popup the full field editor or edit inline, that would be SPCopyTable.m `shouldUseFieldEditorForRow`

But there probably will also be some changes to preferences to accommodate this change. There also appears to be a possible bug with the button that chooses to use the popup editor or not..

**Comment by lonkle** [comment]
@Jason-Morcos That makes sense, thanks for the guidance. Since I'm not great with GUI code, I may just add a conditional for all LONGTEXT fields to be edited if they're within 15 characters long. 

Or do you think even though that seems like an intelligent / sane criteria to edit in-line - it still would need a "Force all LONGTEXT fields to be edited in a popup" preference option in the GUI?

**Comment by Jason-Morcos** [comment]
Realistically, if we want to do it right I think that the best option would probably be a 3-way select.
1. Always edit inline
2. Intelligently switch between inline and popup
3. Always edit in popup

I think we'd want to default people to 2 and use a popup if the content is large, or the content is image/json/binary (something not useful to edit line).

**Comment by lonkle** [comment]
@Jason-Morcos I feel the same way. I won't be able to get to this for a couple months. But, I'll submit a PR with that exact behavior when the time comes. Thanks for the help!

**Comment by samuelbradshaw** [comment]
I've run into this myself as well. My preference would be for the "Intelligently switch between inline and popup" option (or whatever it may be called) to choose which experience to use for text fields not based on the text field type, but based on the length of the content in the text field.

**Comment by lonkle** [comment]
@samuelbradshaw Thanks for the feedback. So, at least we can know it's a worthwhile feature for people to have! I'm glad the idea has support. ☺️

**Comment by jamesstout** [comment]
> There also appears to be a possible bug with the button that chooses to use the popup editor or not..

I think I fixed this in #899

**Comment by lonkle** [comment]
@jamesstout I don't believe your fix will interfere with this requested feature. Thanks for the update!

**Comment by jamesstout** [comment]
I had a quick stab at implementing this: https://github.com/Sequel-Ace/Sequel-Ace/tree/inline-popup-switch

**Comment by Jason-Morcos** [comment]
> I had a quick stab at implementing this: https://github.com/Sequel-Ace/Sequel-Ace/tree/inline-popup-switch

Wanna PR, @jamesstout? I like it

**Comment by jamesstout** [comment]
> Wanna PR, @jamesstout? I like it

Didn't want to steal any thunder from @lonkle. I'll PR then.

**Comment by lonkle** [comment]
@jamesstout No no, def throw in your PR. It's community contributions and passions like this that make me love open source. Thank you for considering me but I think my contribution was the idea and the discussion of its implementation. You took it the rest of the way and I'm excited to check out your contribution! 💜
