### ISSUE TITLE
Option to go to structure of content of table from the table list

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#522]
In the table list It would be really useful to have the option to go to either the structure or the content.
Phpmyadmin has this option, if you click on the tablename you goto the content, if you click on the icon, you go to the structure.
Something similar would be perfect.

The new setup is not helping either, now I need to go to the upper right (iso left, which was closer by) of my screen every time to toggle between content and structure.

<img width="359" alt="Screenshot 2020-11-20 at 09 45 11" src="https://user-images.githubusercontent.com/25279400/99779296-23cee000-2b15-11eb-88c1-936d574b5db1.png">

**Comment by Jason-Morcos** [comment]
The keyboard shortcuts might help you with this at least for now. Command+1 is structure and Command+2 is content. See the "View" menu
