### ISSUE TITLE
Move actions to upper left screen of add a preference for it

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#524]
The "select database", structure etc actions are now suddenly placed on the right side. Can this be either reverted or changed via preferences.
I have a big resolution monitor and these options are now really far away from the result of the useful stuff (tables, data etc). 

<img width="2032" alt="Screenshot 2020-11-20 at 09 49 37" src="https://user-images.githubusercontent.com/25279400/99779762-cf783000-2b15-11eb-8e7e-aef5975dc872.png">

**Comment by Kaspik** [comment]
This is a Big Sur thing.
You shouldn't put toolbar on left side (so you will see it in all apps probably), but we will make some UI updates as we slowly upgrade app to newer iOS :)

https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/
