### ISSUE TITLE
Preferences synchronisation

### ISSUE THREAD

**Issue by stychos** [Sequel-Ace/Sequel-Ace#53]
Based on https://github.com/sequelpro/sequelpro/issues/1843

When working with multiple client machines it would be nice to be able to save the settings / connections to Dropbox / iCloud so that you don't have to recreate the connections on each machine.

(Personally I would prefer iCloud sync)

**Comment by jlubeck** [comment]
I was about to open a similar issue but saw this... Is there a way to import the preferences from the old Sequel Pro somehow?

**Comment by stychos** [comment]
@jlubeck try to move your `~/Library/Application Support/Sequel Pro/Data/Favorites.plist` into `~/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application Support/Sequel Ace/Data`

**Comment by jlubeck** [comment]
Thank you @stychos . It imported the sites, but not the passwords. I guess it's better than nothing. Thank you!

**Comment by jamesstout** [comment]
> It imported the sites, but not the passwords. I guess it's better than nothing. Thank you!

passwords are in the keychain.

**For the rest of the team:** 
To sync them, it seems you can add an attribute: [kSecAttrSynchronizable](https://developer.apple.com/documentation/security/ksecattrsynchronizable?language=objc), but then accessing synced passwords changes.

We'd have to look at `SPKeychain.m`

We already have an App Group and Keychain Group. Docs mention App Group not Keychain Group which seems strange.

Could replace our SPKeychain with a package: https://github.com/kishikawakatsumi/UICKeyChainStore#icloud_sharing

There's even a Swift version for @Kaspik 

Caveat:

> Only password items can be synchronized. Keychain syncing is not supported for certificates or cryptographic keys.

**Comment by Kaspik** [comment]
Let’s not switch ti anything yet and let me take a look on the current Keychain. :)

**Comment by jamesstout** [comment]
OK. I had a play with that package anyway, and synced a password from my main iMac to my old iMac:

New mac:

![Screenshot 2020-06-25 at 3 50 03 PM](https://user-images.githubusercontent.com/1576190/85680071-8b1a6c80-b6fc-11ea-882b-40089dcfd67c.png)

old mac after installing and running Sequel Ace from the MAS:

![Screenshot 2020-06-25 at 3 49 55 PM](https://user-images.githubusercontent.com/1576190/85680152-9bcae280-b6fc-11ea-8ff4-6ed121b5a0e1.png)

**Comment by ceesvanegmond** [comment]
Same issue here. Maybe an option is to sync all with iCloud?

**Comment by jamesstout** [comment]
> Let’s not switch ti anything yet and let me take a look on the current Keychain. :)

Any update on this one? thanks

**Comment by Kaspik** [comment]
We have a docs for the migration: https://github.com/Sequel-Ace/Sequel-Ace/blob/main/docs/get-started/migrating-from-sequel-pro.md

I don't think we are planning to introduce iCloud sync soon enough to make this Issue open, so I would recommend closing it for now...
