### ISSUE TITLE
Add Cmd+backspace shortcut for deleting a selected row or table

### ISSUE THREAD

**Issue by cyberrrr** [Sequel-Ace/Sequel-Ace#533]
CMD+Backspace should delete a selected row or selected table, like it can delete files and folders in Finder when it's selected.

For example, highlight a table and press CMD+Backspace to remove it with a shortcut, instead of right click + Delete

Not sure about others but CMD+Backspace shortcut seems like the most important to me.

**Comment by samuelbradshaw** [comment]
Does just pressing Delete meet this need? You can delete selected rows by selecting them, and pressing Delete, without a modifier key.

**Comment by cyber1111** [comment]
Hi, I didn't notice that until now. 

I think it would be more consistent for using CMD+Backspace because that's what Finder uses and other applications use as well.
