### ISSUE TITLE
I suggest this kind of toolbar is better

### ISSUE THREAD

**Issue by evanyangg** [Sequel-Ace/Sequel-Ace#534]
![image](https://user-images.githubusercontent.com/22952321/99906941-d8832000-2d14-11eb-9358-f243194a4b95.png)
I suggest this kind of toolbar is better.
Ace Version like this 
![image](https://user-images.githubusercontent.com/22952321/99906989-2dbf3180-2d15-11eb-8ccf-e7c723ff0f6e.png)
It's too far.

**Comment by Kaspik** [comment]
First UI changes for Big Sur are already merged in for 3.0.0 release (https://github.com/Sequel-Ace/Sequel-Ace/pull/528), we will continue on improving that. :)

**Comment by evanyangg** [comment]
@Kaspik  👍👍👍
