### ISSUE TITLE
Cannot hide the filter for the current session

### ISSUE THREAD

**Issue by jonjieviduya** [Sequel-Ace/Sequel-Ace#539]
I'm trying to hide this filter bar but it can only achieve by closing and opening the app again. Is there any way I can hide this bar and then when I switch to different table, it should still be hidden until I turn it back on again? When I click the [-] icon, yes it disappears but when I switch to different table, boom it is there again. This is a bit annoying when switching between tables. Please see screenshot below.

<img src="https://i.imgur.com/1LTU5KQ.png">

**Comment by Jason-Morcos** [comment]
Just to be sure, this is purely aesthetic issue, yes? This does not negatively impact what you're seeing in any of the tables, the annoyance is only that the filter bar doesn't stay hidden when you hide it?

**Comment by Jason-Morcos** [comment]
Can you please verify if this issue still exists in the latest release 3.2.2? It may be fixed

**Comment by jonjieviduya** [comment]
> Just to be sure, this is purely aesthetic issue, yes? This does not negatively impact what you're seeing in any of the tables, the annoyance is only that the filter bar doesn't stay hidden when you hide it?

Yes, exactly.

**Comment by jonjieviduya** [comment]
> Can you please verify if this issue still exists in the latest release 3.2.2? It may be fixed

No, I just tried it now and still getting the same result.

**Comment by jamesstout** [comment]
@jonjieviduya would you be OK switching to using this button (in red) to remove the filter?

<img width="787" alt="Screenshot 2021-02-25 at 5 17 49 PM" src="https://user-images.githubusercontent.com/1576190/109131629-f043c780-778d-11eb-876e-91cd3528ffb4.png">

If so, I'll PR this branch: https://github.com/Sequel-Ace/Sequel-Ace/tree/fix-filter-539
