### ISSUE TITLE
Navigating using foreign keys is not working

### ISSUE THREAD

**Issue by Sofianio** [Sequel-Ace/Sequel-Ace#54]
### Environment:
Sequel Ace Version: 2.0.1 Build 2029
macOS Version: 1.15.4
MySQL Version: 5.6.28
### Description
Linking and navigating isn't working .. copy of issue [#3491](https://github.com/sequelpro/sequelpro/issues/3491) in Sequel Pro

### Steps To Reproduce:

- Go to any table with a foreign key 
- Click the foreign key (little arrow)
- Expected Behavior:
    It used to take you to the related table and show the selected index only, now it only opens the table

### Additional Context:

This used to work fine in Sequel Pro 1.1.2, it was soooo helpful.

Please bring it back

**Comment by Dalamar** [comment]
Same build same issue.
This is one of the most valuable features of the Sequel Pro.
I really miss it.
Hope it will be fixed soon.

**Comment by Jason-Morcos** [comment]
I think this is gonna entail some changes to filtering so that filters are set on the table you get to in order to match the params of the foreign key clicked.

**Comment by Sofianio** [comment]
I'm Impressed at how fast and efficient this was, 
I'm happy to see this feature back :)
Thank you all
