### ISSUE TITLE
Crash when trying to make table on MariaDB CONNECT engine

### ISSUE THREAD

**Issue by evilangelmd** [Sequel-Ace/Sequel-Ace#540]
- Sequel Ace Version: 2.3.1
- macOS Version: 10.14.6
- MySQL Version: MariaDB 10.2.36

**Description**
Added new table with engine "CONNECT" UTF-8, crashed instantly after hitting ADD

**Steps To Reproduce**
1. Login to database
2. Create a table via "+" sign with table type CONNECT

**Expected Behaviour**
Create table

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**
`Process:               Sequel Ace [86741]
Path:                  /Applications/Sequel Ace.app/Contents/MacOS/Sequel Ace
Identifier:            com.sequel-ace.sequel-ace
Version:               2.3.1 (2117)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Ace [86741]
User ID:               501

Date/Time:             2020-11-23 11:27:50.712 +0100
OS Version:            Mac OS X 10.14.6 (18G5033)
Report Version:        12
Anonymous UUID:        141CC7F7-AFD9-7134-7EBF-D776D356F038

Time Awake Since Boot: 850000 seconds

System Integrity Protection: enabled

Crashed Thread:        13  SPTablesList table addition task (SPDatabaseDocument#3)

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
terminating with uncaught exception of type NSException
abort() called`

Details: https://pastebin.com/jFJrM9fN

**Comment by Kaspik** [comment]
Probably related: https://github.com/Sequel-Ace/Sequel-Ace/issues/523

**Comment by jamesstout** [comment]
Hopefully fixed by #566
