### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by Tklaversma** [Sequel-Ace/Sequel-Ace#542]
I guess no need for further explanation... see title.

![img](https://user-images.githubusercontent.com/2269283/100120491-4431ce00-2e78-11eb-8b1c-3983c4524d9d.jpg)

**Comment by mfehr94** [comment]
@Tklaversma See #62 they add support for silicon for version 3.x.

**Comment by Tklaversma** [comment]
Didnt saw that one.. you can close this :)

**Comment by Jason-Morcos** [comment]
Indeed, we're working on it. Duplicates #62
