### ISSUE TITLE
Wrong flexible space behavior

### ISSUE THREAD

**Issue by zgr0629** [Sequel-Ace/Sequel-Ace#544]
- Sequel Ace Version:2.3.1 build 2117
- macOS Version:11.0.1 (20B29)
- MySQL Version:5.7.32

**Description**
In customize tool bar, Flexible space is not flexible.

**Steps To Reproduce**
1. right click toolbar
2.choose Customize toolbar

**Expected Behaviour**
Flexible space should push the icons to the left side.

**Additional Context**

![image](https://user-images.githubusercontent.com/5328562/100183780-c377de00-2f1a-11eb-9d47-e4089a5cede7.png)

**Comment by Jason-Morcos** [comment]
Experimenting with other apps in Big Sur such as Finder this appears to be global (affecting all macOS apps). Closing this issue as it's a macOS thing outside the purview of Sequel Ace. If I am incorrect, please let me know and we can reopen this issue. If this change on Apple's part concerns you, I encourage you to submit a bug report to Apple.

**Comment by Kaspik** [comment]
Also - we changed default toolbar for 3.0.0 release, where we added spaces instead of flexible spaces. We will evaluate this further once 3.0.0 is out!

**Comment by zgr0629** [comment]
@Jason-Morcos 
After I test Mail.app and Finder.app, it does seem to be a issue with macOS itself. Flexible space behaves even differently in Mail.app and Finder.app
![image](https://user-images.githubusercontent.com/5328562/100203133-2c704d80-2f3d-11eb-9190-059ee98cd82d.png)
![image](https://user-images.githubusercontent.com/5328562/100203294-5de91900-2f3d-11eb-9ad3-b73a43ac777c.png)

The layout is a bit uncomfortable for me now, as the group of buttons used to be on the left.
Looking forward to the look of version 3.0.0, thanks.

**Comment by Kaspik** [comment]
The flexible space works differently based on `where` you put it (left, right, center, next to some group, etc) - so yes, it's macOS thing. I also have big 27" 5K screen on iMac so I'll try to find some UI that works for that as well.
