### ISSUE TITLE
The unit of rows is wrong

### ISSUE THREAD

**Issue by mhdhamouday** [Sequel-Ace/Sequel-Ace#545]
Sequel Ace Version: 2.3.1
macOS Version: 10.15.7
MySQL Version: MariaDB 10.2.36
Description
There is an error in all units of lines in all places, such as the number of rows in the table, etc.
Units are shown as units of size, not number of lines

Steps To Reproduce

Login to database
Go to the table and look in bottom of table

Is Issue Present in Latest Beta?
I don't have Beta version, I use last version from Apple store

Additional Context
![image](https://user-images.githubusercontent.com/16991900/100205272-30807900-2f05-11eb-9216-ca126d87723e.png)

**Comment by Jason-Morcos** [comment]
Duplicates #504
Fixed already and will be released as part of version 3.0 :)

**Comment by Kaspik** [comment]
Released 2.3.2 hotfix, available in the AppStore already.

**Comment by mhdhamouday** [comment]
Thanks!
