### ISSUE TITLE
Chinese garbled occasionally

### ISSUE THREAD

**Issue by MrLegeek** [Sequel-Ace/Sequel-Ace#547]
Sometimes the fields containing Chinese will be garbled  , like '?????VIP??'

**Comment by mfehr94** [comment]
@MrLegeek please add some imformation like: 
>Sequel Ace Version: 2.3.1
>macOS Version: 10.14.6
>MySQL Version: MariaDB 10.2.36

and add some Steps To Reproduce

**Comment by MrLegeek** [comment]
Sequel Ace Version: 2.3.0 Build2111
macOS Version: 10.15.7
MySQL Version: MySql5.7.28

I opened the software using the extended screen, and then I did not use this window for a period of time. If I switch this window again, this garbled code will happen occasionally.

Thanks.

**Comment by Kaspik** [comment]
These "did not use for some time" all sounds like memory issues that should be fixed in 3.0.0 with ARC enabled, let's see.

**Comment by MrLegeek** [comment]
> These "did not use for some time" all sounds like memory issues that should be fixed in 3.0.0 with ARC enabled, let's see.

When will version 3.0 be released?

**Comment by Kaspik** [comment]
Probably next week, depends on how fast we move with M1 and Apple Silicon updates. So far looks good.
