### ISSUE TITLE
Sequel-Ace-2.3.2-release.zip missing

### ISSUE THREAD

**Issue by mfehr94** [Sequel-Ace/Sequel-Ace#554]
To build brew cask with the new version the Sequel-Ace-2.3.2-release.zip is needed. It would be nice if anyone can add it.

Thanks

**Comment by Kaspik** [comment]
Once @Jason-Morcos wakes up, we will notarize the build and upload it. I released the hotfix asap but don't have certificates here right now.

**Comment by Kaspik** [comment]
Release 🎉

**Comment by mfehr94** [comment]
@Kaspik @Jason-Morcos is it intentional that the url looks like this? https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F2.3.2-2121

**Comment by Jason-Morcos** [comment]
> @Kaspik @Jason-Morcos is it intentional that the url looks like this? https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F2.3.2-2121

That is the correct URL to the latest GitHub release, yes. We've changed to production- tags for fastlane deployment things!

**Comment by mfehr94** [comment]
ok so we have to fix the url in the cask script from this https://github.com/Sequel-Ace/Sequel-Ace/releases/download/2.3.2/Sequel-Ace-2.3.2-release.zip to this https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F2.3.2-2121

**Comment by Jason-Morcos** [comment]
> ok so we have to fix the url in the cask script from this https://github.com/Sequel-Ace/Sequel-Ace/releases/download/2.3.2/Sequel-Ace-2.3.2-release.zip to this https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F2.3.2-2121

Close, should fix it to https://github.com/Sequel-Ace/Sequel-Ace/releases/download/production%2F2.3.2-2121/Sequel-Ace-2.3.2-release.zip

**Comment by Kaspik** [comment]
Yeah, sorry, it will be like this from now on. We will have `production/app.version-build.version` and `beta/app.version-build.version` :)

**Comment by mfehr94** [comment]
ok thats tricky I need to read the docs first.

**Comment by Kaspik** [comment]
I'll find the code for paraing that that we use for measuring release times.

**Comment by Jason-Morcos** [comment]
I wonder if there's a way to be smart or programmatic about it in some way? Perhaps we could figure out a way to have a link that aliases to the latest release or something, perhaps through the GitHub pages site?

**Comment by mfehr94** [comment]
I allready updated the url to the new standard  Homebrew/homebrew-cask#93722
