### ISSUE TITLE
Crash when opening local SQL file

### ISSUE THREAD

**Issue by fyodorovich** [Sequel-Ace/Sequel-Ace#557]
- Sequel Ace Version: 2.3.2
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel i7
- MySQL Version: 10.4.13-MariaDB Homebrew

**Description**
Opening an SQL database on a local drive causes the app to crash.

**Steps To Reproduce**

1. File->Open... 
2. Select an SQL database on a local drive.
3. A dialog appears asking to verify opening a 3.4MB file. 
4. Select "Import" or "Open"
5. Watch the app disappear

**Expected Behaviour**
I would like the app to remain open and to display a new window, allowing me to interact with the database.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes. 

**Additional Context**

[Sequel Ace_2020-11-27-101151_MacBook-Pro-3.crash.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/5605156/Sequel.Ace_2020-11-27-101151_MacBook-Pro-3.crash.zip)

**Comment by Jason-Morcos** [comment]
`Over-release of NSResponder or subclass.`
@Kaspik To me, this looks like an ARC issue. We should probably test that this works in 3.0 but I believe this is likely fixed already by the ARC conversion

**Comment by jamesstout** [comment]
> `Over-release of NSResponder or subclass.`
> @Kaspik To me, this looks like an ARC issue. We should probably test that this works in 3.0 but I believe this is likely fixed already by the ARC conversion

Yes, works fine in 3.0.

**Comment by Kaspik** [comment]
Just one note to this - this is not new in 2.3.2, right? This had to be happening since... forever. If that's the case, we will probably close this in favor of 3.0.0 and not try to fix it in 2.x.x :)
