### ISSUE TITLE
toolbar items on right, bad.

### ISSUE THREAD

**Issue by jimlongo56** [Sequel-Ace/Sequel-Ace#562]
### used to be
![Screen Shot 2020-11-27 at 2 32 49 PM](https://user-images.githubusercontent.com/6787988/100479907-a4fe1800-30bd-11eb-87f9-3801a19436bc.png)

### Now
![Screen Shot 2020-11-27 at 2 29 51 PM](https://user-images.githubusercontent.com/6787988/100479913-aaf3f900-30bd-11eb-95a2-c5c61fda8d97.png)
The eye and mouse travel is very bad.  

All for the sake of a really big header.  I suppose it was to save vertical height. Put the header on the right.

**Comment by Jason-Morcos** [comment]
This is macOS Big Sur. Unfortunately, we don't have control over this :/

**Comment by jimlongo56** [comment]
Thanks.
i'm sure you know more than me, but I see other apps with toolbar flush left.
