### ISSUE TITLE
Attempting to build locally and receiving error messages

### ISSUE THREAD

**Issue by gms8994** [Sequel-Ace/Sequel-Ace#565]
- Sequel Ace Version: 3.0.0
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: N/A

**Description**
Following the instructions in the readme, I'm attempting to build locally to test the system on an older version of macOS, but getting a series of error messages:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/50712/100520233-c10bc300-316a-11eb-81dc-b92dfd49891c.png">

**Steps To Reproduce**
1. Clone repo on new install of macOS
2. Follow instructions in readme for building locally

**Expected Behaviour**
Build succeeds

**Additional Context**
I'm sure this is simply because I don't have everything set up correctly locally. If there's something that I can do to make this process easier for the entire Sequel Ace team, please don't hesitate to contact me. Relates to #269.

**Comment by Kaspik** [comment]
This is an XCode issue, you have to use XCode 12 because of Big Sur unfortunately. :)

**Comment by gms8994** [comment]
Xcode suggests I'm using 12.1?

<img width="642" alt="image" src="https://user-images.githubusercontent.com/50712/100520446-b56ccc00-316b-11eb-984b-99da88940931.png">

**Comment by Kaspik** [comment]
Hmm, weird, there is a `@availability` check that should handle the `imageWithSystemSymbolName` function as it's macOS 11+ (https://developer.apple.com/documentation/appkit/nsimage/3622472-imagewithsystemsymbolname?language=objc)

Does it work when you change the `availability` to 10.16 instead?

**Comment by Kaspik** [comment]
Okay, it seems like you have to have XCode 12.2... could you please try that?

**Comment by gms8994** [comment]
Xcode 12.2 no longer reports the `imageWithSystemSymbolName` error, but the other errors related to team and signing certificates persist. Is there something that I need to do to make those errors go away?

**Comment by Kaspik** [comment]
Are you running the Local Testing scheme?

If so, just change code signing to local or no aign at all just to get it running on your machine :)

**Comment by Kaspik** [comment]
I hope you were able to make it run, if not - we shipped first beta already, so you can play with that. :)

**Comment by gms8994** [comment]
I didn't actually get to as even though I'd set to local signing, it still threw errors. I'll try again on a future issue. For now, I have an issue to open from a crash on the new beta :)
