### ISSUE TITLE
Crashes When Viewing MySQL "View" Content

### ISSUE THREAD

**Issue by Jason-Morcos** [Sequel-Ace/Sequel-Ace#572]
- Sequel Ace Version: 3.0.0 Beta 1
- macOS Version: 11.0.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.6

**Description**
Attempt to view a view's contents - it will crash

**Steps To Reproduce**
1. Connect to MySQL 5.6 db
2. Navigate to the content view for a view

**Expected Behaviour**
Expect view contents to load

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**

[Sequel Ace Beta_2020-11-29-155351_Jasons-Mac.crash.zip](https://github.com/Sequel-Ace/Sequel-Ace/files/5613138/Sequel.Ace.Beta_2020-11-29-155351_Jasons-Mac.crash.zip)

**Comment by jamesstout** [comment]
Hmmm ... strange one.

**Comment by jamesstout** [comment]
Happens on all views. The table list thinks it's a table, not a view.

**Comment by Kaspik** [comment]
It will be related to this: https://github.com/Sequel-Ace/Sequel-Ace/pull/526
