### ISSUE TITLE
High CPU Usage when editing large queries

### ISSUE THREAD

**Issue by gms8994** [Sequel-Ace/Sequel-Ace#573]
- Sequel Ace Version: 2.3.2 / 3.0.0
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7

Related to #269 

**Description**
Editing a large SQL query (think about a large sproc or something) causes high CPU usage

**Steps To Reproduce**
1. Open a large SQL file (or copy and paste one in)
2. Attempt to edit *anything but the end of the query* (add a comment, add additional SELECT/INSERT/UPDATE statements)
3. Notice that the CPU usage of Sequel Ace quickly ramps up

**Expected Behaviour**
Editing of queries in the query window don't cause high CPU utilization

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**
Verified on a 200 line SQL file; the 'interactivity' of the app while editing seems to be related to the length of the overall set of queries, and does not seem to have any effect if the previous query is ended via `;` (or DELIMITER, either) but still has 100% cpu usage.

**Comment by Kaspik** [comment]
Okay, so now it's not a syntax highlight problem, it's a bracket highlight problem that i didn't even take a look at. :)

See this comment: https://github.com/Sequel-Ace/Sequel-Ace/pull/356#issuecomment-735768195

**Comment by gms8994** [comment]
Is there an "expected" size query window where this works? I downloaded the latest beta release (which actually reports itself as Beta 3001) and am editing a 150 line query and am still getting high CPU usage.

![image](https://user-images.githubusercontent.com/50712/100900711-1b6d9200-3491-11eb-87cf-7d8ed64d354a.png)

**Comment by Kaspik** [comment]
Could you paste the query here, and screenshot your query preferences please?

I would love to check it out.

**Comment by gms8994** [comment]
I think the screenshot requested is the correct one, but if not, please let me know and I'll correct ASAP. Thank you guys so much for looking in to this (and all the other issues)!

<details><summary>Here's the query being used</summary>
SELECT 

table_a.schedule_id,

DAYNAME(table_a.appointment_date) AS slot_named_day_of_week,
table_a.appointment_date,

IF (
	sas.slot_time IS NULL, 
	CASE table_a.type
		WHEN 'before' THEN sec_to_time(time_to_sec(table_a.existing_appointment_begins) - @average_inspection_time)
		WHEN 'after' THEN sec_to_time(time_to_sec(table_a.existing_appointment_ends))
	END,
	sas.slot_time
) AS slot_available_start,


sec_to_time(time_to_sec(
	IF (
	sas.slot_time IS NULL, 
		CASE table_a.type
			WHEN 'before' THEN sec_to_time(time_to_sec(table_a.existing_appointment_begins) - @average_inspection_time)
			WHEN 'after' THEN sec_to_time(time_to_sec(table_a.existing_appointment_ends))
		END,
		sas.slot_time
	)) + @average_inspection_time
) AS slot_available_end,

table_a.existing_appointment_begins, table_a.existing_appointment_ends, table_a.type,
table_b.start_time,

acos( 
      cos(radians( table_d.latitude ))
    * cos(radians( the_claim_we_want_to_move.latitude ))
    * cos(radians( table_d.longitude )  - radians( the_claim_we_want_to_move.longitude ))
    + sin(radians( table_d.latitude )) 
    * sin(radians( the_claim_we_want_to_move.latitude ))
  ) * 3959 AS distance_in_miles_from_confirmed_to_claim_to_move,

acos( 
      cos(radians( table_c.latitude ))
    * cos(radians( the_claim_we_want_to_move.latitude ))
    * cos(radians( table_c.longitude )  - radians( the_claim_we_want_to_move.longitude ))
    + sin(radians( table_c.latitude )) 
    * sin(radians( the_claim_we_want_to_move.latitude ))
  ) * 3959 AS distance_in_miles_from_claim_to_move_to_next_confirmed,

FLOOR((
round(
acos( 
      cos(radians( table_d.latitude ))
    * cos(radians( the_claim_we_want_to_move.latitude ))
    * cos(radians( table_d.longitude )  - radians( the_claim_we_want_to_move.longitude ))
    + sin(radians( table_d.latitude )) 
    * sin(radians( the_claim_we_want_to_move.latitude ))
  ) * 3959 * @average_minutes_per_mile * 60)+900)/1800)*1800 AS travel_time_from_confirmed_to_rescheduled,
 
FLOOR((
round(
acos( 
      cos(radians( table_c.latitude ))
    * cos(radians( the_claim_we_want_to_move.latitude ))
    * cos(radians( table_c.longitude )  - radians( the_claim_we_want_to_move.longitude ))
    + sin(radians( table_c.latitude )) 
    * sin(radians( the_claim_we_want_to_move.latitude ))
  ) * 3959 * @average_minutes_per_mile * 60)+900)/1800)*1800 AS travel_time_from_rescheduled_to_next_confirmed

FROM (
SELECT
	a.id, a.schedule_id, a.start_time AS existing_appointment_begins,
	a.end_time, a.actual_end_time AS existing_appointment_ends, a.appointment_date,
	(
	
	/* HERE BE DRAGONS */
	
	
		SELECT COUNT(*) FROM appointments a2
		WHERE status = 1
		AND a2.appointment_date = a.appointment_date
		AND (
			a2.start_time BETWEEN a.actual_end_time AND sec_to_time(time_to_sec(a.actual_end_time) + @average_inspection_time)
		)
	) AS slot_is_not_available, 'after' as type
FROM
	appointments a
WHERE
	status = 1
	AND start_time >= @daily_start_time 
HAVING slot_is_not_available = 0
UNION

SELECT
	a.id, a.schedule_id, a.start_time AS existing_appointment_begins,
	a.end_time, a.actual_end_time AS existing_appointment_ends, a.appointment_date,
	time_to_sec(start_time) - time_to_sec(@daily_start_time) > @average_inspection_time AS slot_is_not_available,
	'before' as type
FROM
	appointments a
WHERE
	status = 1
	AND start_time > @daily_start_time
HAVING slot_is_not_available = 0

) AS table_a

LEFT OUTER JOIN appointments table_b
ON table_b.id = (
	SELECT id FROM appointments
	WHERE status = 1
	AND appointment_date = table_a.appointment_date
	AND start_time > CASE table_a.type
 		WHEN 'before' THEN sec_to_time(time_to_sec(table_a.existing_appointment_begins) - @average_inspection_time)
 		WHEN 'after' THEN sec_to_time(time_to_sec(table_a.existing_appointment_ends))
 	END
 	ORDER BY start_time ASC
 	LIMIT 1
)

LEFT OUTER JOIN schedulings table_c
ON table_b.schedule_id = table_c.id


INNER JOIN (
	SELECT COUNT(1) AS num_appts, a8.appointment_date FROM appointments a8
	WHERE status = 1
	GROUP BY a8.appointment_date
) AS confirmed_daily_count
ON confirmed_daily_count.appointment_date = table_a.appointment_date
AND confirmed_daily_count.num_appts < @appointments_per_day

INNER JOIN schedulings table_d ON table_a.schedule_id = table_d.id
CROSS JOIN schedulings the_claim_we_want_to_move ON the_claim_we_want_to_move.id = @claim_id_that_we_want_to_move
LEFT OUTER JOIN slots_available_steps sas
ON
sas.slot_time <= sec_to_time(time_to_sec(
	COALESCE(table_b.start_time, '19:00:00')
) - @average_inspection_time)
AND sas.slot_time >= CASE table_a.type
	WHEN 'before' THEN sec_to_time(time_to_sec(table_a.existing_appointment_begins) - @average_inspection_time)
	WHEN 'after' THEN sec_to_time(time_to_sec(table_a.existing_appointment_ends))
END

WHERE

1 = 1

ORDER BY table_a.appointment_date ASC, sas.slot_time ASC
;
</details>

<details><summary>Screenshot</summary>
![image](https://user-images.githubusercontent.com/50712/100924526-c04a9800-34ae-11eb-8cc6-cad7d1c71cb1.png)
</details>

**Comment by Kaspik** [comment]
Sooo I copied your query, it did the highlight on paster super quickly (can't even notice it's doing anything), and then I can't get over like 20%, and 20% is pretty okay I think considering it's preparing `offers` what to autocomplete on background when you stop typing... Not sure what's going on with your build 😞 

<img width="1007" alt="Screen Shot 2020-12-04 at 19 06 30" src="https://user-images.githubusercontent.com/7204168/101198502-d64d8980-3663-11eb-8a15-65430ce9ba21.png">

Do you have [App cleaner](https://freemacsoft.net/appcleaner/) to remove the app completely and then install? (It will remove really everything, so don't do it if you have a lot of bookmarks etc.)... Or wait for stable release to try it there, sorry, I would love to help more here!

**Comment by gms8994** [comment]
I'll wait until a release build then; hopefully it's just something wonky with the beta that I downloaded and it won't be present later.

Thank you so much for all your work on this! It's a very impressive improvement :)
