### ISSUE TITLE
Unhelpful dialogue on failure of imported favorite

### ISSUE THREAD

**Issue by davidbankes** [Sequel-Ace/Sequel-Ace#579]
- Sequel Ace Version: 3.0.0.0 (beta build 3000)
- macOS Version: 11.01
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.26

**Description**
Attempting to use an imported connection from sequel ace to sequel ace BETA initially failed.

**Steps To Reproduce**
1. I exported my connections from Sequel Ace and then imported them into Sequel Ace Beta. 
2. Then I attempted to access a connection that is via an SSH tunnel and has an accompanying key
3. I got the screenshot below
4. I pressed Yes (thinking perhaps that meant to accept the new signature or something) and the connection failed
5. Then I deleted the key and re-added it and it works

**Expected Behaviour**
I expected the connection to work OR for it to give me a helpful dialogue explaining what was wrong with the connection.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**
The beta looks great!

![Screen Shot 2020-11-30 at 1 29 27 PM](https://user-images.githubusercontent.com/3212205/100649710-d91d4700-3310-11eb-9344-8c1379a85a4e.png)

**Comment by Kaspik** [comment]
This is an interesting issue. We don't have modal with `Yes` and `No` in the app afaik, and we don't have this string in the app. So It's a modal where we get all the strings right from MySQL as error details.

I think this is modal saying `if you really want to proceed`, where `yes` should connect you (https://superuser.com/questions/421074/ssh-the-authenticity-of-host-host-cant-be-established)

Not sure how more helpful can we be here, as these errors are from MySQL...

**Comment by jamesstout** [comment]
Seems like it comes from `openssh`:

https://github.com/openssh/openssh-portable/blob/33313ebc1c7135085676db62189e3520341d6b73/sshconnect.c#L1043-L1079

@davidbankes do you have anything special in your `ssh_config`?

**Comment by Kaspik** [comment]
I believe I also changed the dialog and copy - so should be fixed.

**Comment by Kaspik** [comment]
Closing, let us know if next beta will have the same issue. :)
