### ISSUE TITLE
Syntax highlighting after session import

### ISSUE THREAD

**Issue by wildshaman** [Sequel-Ace/Sequel-Ace#581]
- Sequel Ace Version: 3.0.0.1
- macOS Version: 11.11

Query editor window has no syntax highlighting after importing .spfs session file (with connections and queries in editor).
"Syntax highlighting" in settings is enabled. Unchecking it and checking again leads to app freeze (totally).

**Comment by Kaspik** [comment]
Could you please provide some details about how many lines we talking about etc? Also are you testing Beta 1 or Beta 2? Beta 2 fixed bracket highlighter.

Thanks!

**Comment by wildshaman** [comment]
3.0.0 (3001) - Beta 2

Just copying queries list (1000-3000 queries with empty strings) to the query editor is ok - small frezze up to 1-2 second and no freezes later while scrolling\editing. Highlighting is ok in this case.

But if i want to import .spfs session file (with saved connections, tabs, all queries in editor in tabs) - import is ok but the query window has no highlighting.
But if i try to edit something right after that - the query editor becomes highlighted - but only the visible part of editor (10-20 strings). All other lines are not highlighted even after that.

**Comment by Kaspik** [comment]
Thanks, interesting, everything should be highlighted at the beginning (the freeze is expected for now, we need to rewrite the whole editor - https://github.com/Sequel-Ace/Sequel-Ace/pull/563). Will check why `spf` file is not highlighted as `sql` files definitely are on import.

**Comment by Kaspik** [comment]
Fixed in https://github.com/Sequel-Ace/Sequel-Ace/pull/575/commits/be724198a4db0bff0bda81d3428e4f9f794e17ed, thanks for testing.
