### ISSUE TITLE
Styling the list of tables in db in the left side

### ISSUE THREAD

**Issue by wildshaman** [Sequel-Ace/Sequel-Ace#582]
It will be good to add the ability to change tables list font size and background color (now the font size looks so big and white background merges with the right (main - content, structure, etc) part of window.

**Comment by Kaspik** [comment]
Afaik tables list font size is defined in your Sequel Ase preferences - General - Font.

**Comment by wildshaman** [comment]
> Afaik tables list font size is defined in your Sequel Ase preferences - General - Font.

Ohoho, thank you!

But, nevertheless, cant find background color option to change it. Just want to change white background of the left side (with tables) to grey (as in old Sequel Pro).

**Comment by Kaspik** [comment]
We will hopefully get to the point where sidebar behaves natively (blurry _gray_ background) before 3.0.0 release so we are not planning to add background customization for sidebar, sorry! But the native way should fix this problem. :)

**Comment by Kaspik** [comment]
Fixed in https://github.com/Sequel-Ace/Sequel-Ace/pull/575/commits/689d1721cf56c25d351949579c443409031fe332
