### ISSUE TITLE
Crash after DB duplication

### ISSUE THREAD

**Issue by robsch** [Sequel-Ace/Sequel-Ace#584]
- Sequel Ace Version: 2.3.2
- macOS Version: 10.15.7 Catalina
- Processor Type (Intel/Apple): 2,6 GHz 6-Core Intel Core i7
- MySQL Version: 8.0.21
- Connection via SSH Host and public key

**Description**
When I try to duplicate a database (with content), Sequel Ace crashes. The new DB gets created but it has no tables.

**Steps To Reproduce**
1. Connect
2. Choose DB
3. Duplicate with content

**Expected Behaviour**
A duplicated DB should be created without a crash.

Tried duplication without content: same effect.

**Comment by Kaspik** [comment]
Fixed for 3.0.0.
