### ISSUE TITLE
add option show connection tab forever in preferences

### ISSUE THREAD

**Issue by maprangsoft** [Sequel-Ace/Sequel-Ace#585]
when working on multiple database at the same time if the connection tab show  forever very useful when switch database.

thank you advance.

**Comment by Kaspik** [comment]
Could you please post a screenshot what you mean "connection tab"?

**Comment by maprangsoft** [comment]
![1607077898561](https://user-images.githubusercontent.com/25447955/101153174-a8157d00-3656-11eb-8c36-af4d88ec12c1.jpg)

**Comment by Kaspik** [comment]
Ohh, so you want this visible even with one tab?

**Comment by maprangsoft** [comment]
yes.

**Comment by Kaspik** [comment]
I don't think we will prioritize this anytime soon... everything that the tab shows is also shown in left top corner (database / table name), so the added value is almost zero from my point of view.

I'll close this but if more people find it valuable and would like to get this prioritized, we can always reopen. :)
