### ISSUE TITLE
Feature Request: Ability to edit JSON data in Popup editor

### ISSUE THREAD

**Issue by calumk** [Sequel-Ace/Sequel-Ace#59]
Copying a feature as requested from Sequel-Pro that was never implemented

It's common nowadays for serialised JSON/XML/etc to be stored in cells. 
It would be great for a built in JSON editor to detect and format them for any inline tweaking.

https://github.com/sequelpro/sequelpro/issues/2934

**Comment by llamafilm** [comment]
In version 2.2 the formatting is working well for me.  However, you can't edit text in this view.  It would also be cool to do syntax highlighting.

**Comment by llamafilm** [comment]
I still think this is an good feature

**Comment by Jason-Morcos** [comment]
Just to be clear, the viewing functionality is fine. Now this request is just about being able to edit the data as JSON?

**Comment by llamafilm** [comment]
The viewing works well for me, inserting correct newlines and indentation.  But I have two suggestions which may belong as separate issues:
1. Detect the type of cell content and display as JSON instead of text automatically
2. JSON syntax highlighting

And yes, editing in this view would be great.

**Comment by calumk** [comment]
Just bumping to keep the request open 
As @llamafilm  suggested, JSON syntax highlighting would be nice

Formatting would also equally/more helpful, to help with the inspection of json data.
A large chunk of JSON data can be quite hard to read if its not formatted, 
At the moment, i often need to copy the field into Vscode or similar, format it, edit it, and then copy it back.... 
so perhaps the ability to toggle formatting?

eg:

``` {"name":"calumk","arr":[{"a":0},{"b":1}]}```

-->

```
{
    "name":"calumk",
    "arr":[
        {
            "a":0
        },
        {
            "b":1
        }
    ]
}
```

I appreciate this is a big addition, so not expecting it, but its certainly on my wish-list!
