### ISSUE TITLE
Previous Next Page Shortcut?

### ISSUE THREAD

**Issue by lipatovroman** [Sequel-Ace/Sequel-Ace#590]
Hello!
Is it possible to add Previous Next Page Shortcut?

![2020-12-04 21-00-04](https://user-images.githubusercontent.com/6747127/101203827-f422ea80-3673-11eb-8e77-e8162ad96b0c.jpg)

**Comment by Jason-Morcos** [comment]
I'm not sure what you're referring to, like a keyboard shortcut?

**Comment by lipatovroman** [comment]
Yes, keyboard shortcut.
Something like CMD + Arrows

**Comment by samuelbradshaw** [comment]
Would the Page Up / Page Down buttons on a wider keyboard fit for this use case? If so, the equivalent to those on a Mac is either Function + ↑/↓ or Option + ↑/↓ (see https://osxdaily.com/2015/07/07/page-up-page-down-mac-keyboard/ , including the comments).

**Comment by lipatovroman** [comment]
I think Cltr + Cmd + ←/→ will be better

**Comment by jamesstout** [comment]
Shift + Cmd ←/→?

(Can't get Control to take in interface builder...)

**Comment by lipatovroman** [comment]
> Shift + Cmd ←/→?
> 
> (Can't get Control to take in interface builder...)

Yes, it's ok. Any way it's better than Function + ↑/↓

**Comment by jamesstout** [comment]
May be reopened by #782
