### ISSUE TITLE
Return header design back

### ISSUE THREAD

**Issue by megaezz** [Sequel-Ace/Sequel-Ace#595]
Please return back design of application header. Now it's so ugly and not friendly. Or please give opportunity to change this option in settings.

**Comment by Jason-Morcos** [comment]
This is due to Big Sur and is outside of our control.

Duplicate of #562, #544 and #534

**Comment by megaezz** [comment]
> This is due to Big Sur and is outside of our control. There will be some UI changes coming in release 3.0.0 that will make things look a little better.
> 
> Duplicate of #562, #544 and #534

Thank you for explanation. Sorry to hear that.
