### ISSUE TITLE
Tables is missing

### ISSUE THREAD

**Issue by MrLegeek** [Sequel-Ace/Sequel-Ace#596]
* Sometimes ，when I switch to a database, all the tables under the database，all tables show Dynamic
* Mac OS：15.7
* Version： 2.3.2 Build 2121
* MySQL： 5.7.28 

![image](https://user-images.githubusercontent.com/20502325/101319071-4a727200-389c-11eb-8eb1-d93b81365be5.png)

**Comment by Kaspik** [comment]
We have changed the way tables are loaded for 3.0.0 is it might be improved as the speed improved as well. I'll leave this open till 3.0.0 or if you want to try the Beta 3, feel free to give it a go. :)

**Comment by Kaspik** [comment]
Closing in favor of 3.0.0 changes, will reopen if it's still an issue after the 3.0.0 release.
