### ISSUE TITLE
Code complete  Issue

### ISSUE THREAD

**Issue by bpzhang** [Sequel-Ace/Sequel-Ace#597]
When I use a table alias, or join multiple tables, each with an alias, when I use the alias association field, the code completes, it is a full database search, not a specified table search, is this a bug or no improved feature?

**Comment by Kaspik** [comment]
When you are creating a new issue, there is a template that you should fill out to give us as much info as possible. Without that, I'm afraid we can't help you or give you any answer, sorry.
