### ISSUE TITLE
Always invalid credentials, when connecting by TCP/IP

### ISSUE THREAD

**Issue by Jurager** [Sequel-Ace/Sequel-Ace#598]
- Sequel Ace Version:  3.0.0 (3003) - Beta 3
- macOS Version: 11.0.1 (20B50)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.19-10 (Percona Stable)

**Description**

Trying to connect to local database via TCP/IP and login/password. 

Using Login - "root", and password - "secret".

Pressed "Test Connection" - "Connection Succeeded". 

Pressed "Connect" - "Unable to connect to host 127.0.0.1 because access was denied." Error message from server was - "Access denied for user 'root'@'localhost' (using password: NO) Access denied for user 'root'@'localhost' (using password: NO)"

However, using the same login details in version 2.3.2 (2121), I successfully connect to the database

**Steps To Reproduce**
1. Launch, try to connect to local database via TCP/IP and login/password
2. Profit.

**Expected Behaviour**
I expected to successfully connect to the database

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

![Снимок экрана 2020-12-07 в 20 54 43](https://user-images.githubusercontent.com/954178/101365811-70b10580-38ce-11eb-8603-9e2726af0b56.png)
![Снимок экрана 2020-12-07 в 20 55 03](https://user-images.githubusercontent.com/954178/101365925-93dbb500-38ce-11eb-868f-7348af682062.png)

**Comment by Kaspik** [comment]
I wonder if it's somehow related to https://github.com/Sequel-Ace/Sequel-Ace/issues/459

**Comment by Jason-Morcos** [comment]
Looks to me like it may be something to do with the password field getting clear bed or not sent. Because of the "using password: NO" message in the error

**Comment by Jason-Morcos** [comment]
@Jurager does it work if you _don't_ test the connection first before trying to connect?

**Comment by Jurager** [comment]
> @Jurager does it work if you _don't_ test the connection first before trying to connect?

Nope, isn't working

**Comment by jamesstout** [comment]
In  `SPConnectionController.m` https://github.com/Sequel-Ace/Sequel-Ace/blob/0f66fda86fac883dc66b2e6feb18aa11a3b98dc7/Source/Controllers/MainViewControllers/ConnectionView/SPConnectionController.m#L2092-L2096

The code doesn't match the comment.

` if ((!connectionKeychainItemName || isTestingConnection) && [self password]) { `

The if condition is matched if there is no keychain item OR we ARE testing. Code hasn't changed for 3 years.

In testing I can replicate, but I don't see the keychain item in my keychain, but SA thinks I have one. Weird.

If we fixed the if condition to match the comment, then it wouldn't work while testing but would when you save/connect...

**Comment by FaimMedia** [comment]
Same here 👆🏻

**Comment by Kaspik** [comment]
> In `SPConnectionController.m`
> 
> https://github.com/Sequel-Ace/Sequel-Ace/blob/0f66fda86fac883dc66b2e6feb18aa11a3b98dc7/Source/Controllers/MainViewControllers/ConnectionView/SPConnectionController.m#L2092-L2096
> 
> The code doesn't match the comment.
> 
> `if ((!connectionKeychainItemName || isTestingConnection) && [self password]) {`
> 
> The if condition is matched if there is no keychain item OR we ARE testing. Code hasn't changed for 3 years.
> 
> In testing I can replicate, but I don't see the keychain item in my keychain, but SA thinks I have one. Weird.
> 
> If we fixed the if condition to match the comment, then it wouldn't work while testing but would when you save/connect...

The problem was with the Keychain getter itself. Keychain returned empty string even if we didn't use favorite (aka quick connect), which caused this condition to fail and skip the password.

No idea why it's visible now as the code hasn't changed for .... years?

Anyways fixed in https://github.com/Sequel-Ace/Sequel-Ace/pull/606 , will be in beta 4, thanks everyone!
