### ISSUE TITLE
Deleting a row does not work (beta3)

### ISSUE THREAD

**Issue by dlt-** [Sequel-Ace/Sequel-Ace#599]
- Sequel Ace Version: 3.0.0 (3003) - Beta 3
- macOS Version: 11.1beta (20C5048)
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: MariaDB 10.5.6

**Description**
Deleting a row by using "-"-button on bottom toolbar or right-clicking a row & choosing "Delete row" does not work.
A popup asking to confirm "Delete selected row?" appears but nothing happens after clicking Delete.

Same issue was present on Beta 1 too.

With 2.3.2 this works as expected.

Tried with multiple different kind of tables, ones with only a couple of columns with primary key and ones without.

**Comment by jamesstout** [comment]
Checking this out. I changed things related to deleting rows recently.

**Comment by Kaspik** [comment]
Yeah I have it on my todo in upcoming days, feel free to leave it to me :)

**Comment by jamesstout** [comment]
found it .. `if (alertReturnCode == NSModalResponseOK) {`  in `SPTableContent.m` ..  OK .. will leave it.

**Comment by Kaspik** [comment]
Well if you got it then fix it, I'll check the PR! 😄
