### ISSUE TITLE
Ability to donate/sponsor to support ongoing development of Sequel Ace

### ISSUE THREAD

**Issue by thomasgriffin** [Sequel-Ace/Sequel-Ace#60]
Not really a feature, but harking back to my initial request listed here: https://github.com/sequelpro/sequelpro/issues/3571

I was serious about offering a sponsorship/payment to continue to ongoing work of Sequel Pro. I'd like to support this effort to ensure it continues to move forward, because this is an important productivity tool for my own companies (and I'm sure countless others who rely on MySQL/MariaDB databases).

If the maintainer of this new repo/initiative is interested, please visit my website and contact me through the contact form and we can continue discussing there: https://thomasgriffin.com/contact/

And if you want to see it happen, please upvote and let them know!

**Comment by Kaspik** [comment]
Thanks Thomas!

I can't speak in behalf of author / other folks, but I think the team needs to stabilize and find out how much time can everyone spend on this project first.

Personally - if so - I would suggest enabling Github Sponsors right here in this repo. :)

The question is who will be active, how much, and what is actually the price of that - usually OSS offers some "premium support" for money etc - not the product itself.

PS: Also, we should keep in mind people that started this originally as a Sequel Pro and never used the sponsorship. I know it led to this moment, just something to think about.

**Comment by stychos** [comment]
I am living in a poor country and always thinking like "shut up and give me money!" But @Kaspik is right － the most important question is an ability to spend enough of time for the core developers (I am not one of them, unfortunately). Hope they will keep this astonishing pace and you'll be able to help them too!

Also, looks like original authors had accepted donations in the past, but they deserve something for their past efforts.

**Comment by thomasgriffin** [comment]
@Kaspik Makes sense. I just wanted to make sure my offer did not get lost and to remind folks this is important! :)

**Comment by Jason-Morcos** [comment]
Hey there, @thomasgriffin. Love to hear the excitement and willingness to sponsor. I thinking @Kaspik is completely right,  we need to stabilize and figure out what Sequel Ace looks like moving forward. Stay tuned.

I think we'll table this in general and revisit in a month or two.

**Comment by Kaspik** [comment]
We will re-evaluate this later definitely! :)

**Comment by Jason-Morcos** [comment]
We are now accepting donations through open collective! You can checkout the link at the top of the repo to "Sponsor", or head directly to the collective! https://opencollective.com/sequel-ace

**Comment by fulldecent** [comment]
I am happy to donate based on what I already got and with no expectations about what will come in the future.
