### ISSUE TITLE
Keychain error when saving favorite if Keychain Access is used to change the password

### ISSUE THREAD

**Issue by dnicolson** [Sequel-Ace/Sequel-Ace#600]
- Sequel Ace Version: 2.3.1 and 3.0.0 (3003) - Beta 3
- macOS Version: 11.0.1 (20B29)
- Processor Type (Intel/Apple): Intel

**Description**
Updating connection favorite fails with Keychain error -67701 or -25300.

<img width="372" alt="Screen Shot 2020-12-07 at 19 53 39" src="https://user-images.githubusercontent.com/2276355/101392614-452a1d00-38c6-11eb-8d77-cf89308f184b.png">

**Steps To Reproduce**
1. Create favorite
2. Edit password in Keychain Access
3. Save changes

**Expected Behaviour**
The connection to be saved. Quitting Sequel Ace and opening it again appears to be a workaround.

**Comment by Jason-Morcos** [comment]
Hmmm we can look into this but this really isn't a normal, expected use case. Going into keychain access manually and editing a keychain entry could change ownership or lower-level properties which ace can't control. Especially given this can be resolved by quitting and reopening Sequel Ace, this is a pretty low-priority issue as described.

**Comment by kented** [comment]
I get this error when attempting to update a password for a favorite in the app

**Comment by Jason-Morcos** [comment]
> I get this error when attempting to update a password for a favorite in the app

Did you mess with passwords in keychain assistant? I'd suggest quitting sequel Ace, blowing them away in keychain assistant, and then trying again

**Comment by kented** [comment]
Thanks. I wiped my keychain entries and that seems to have resolved it. They were originally created by Sequel Pro, fyi. I'm guessing that was problematic, in some way.
