### ISSUE TITLE
Adding functionality to create and edit Stored Procedures and Functions

### ISSUE THREAD

**Issue by xingmungwa** [Sequel-Ace/Sequel-Ace#602]
It would be nice to add functionality to create and edit Stored Procedures and Functions in the UI like MySQL Workbench does. That is mostly the only reason I need to use Workbench.

**Comment by dwSun** [comment]
any update?

**Comment by Jason-Morcos** [comment]
No update
This issue closed automatically due to inactivity. Not a priority for the core team at this time, but we would gladly review a PR from someone else aimed at adding this functionality.
