### ISSUE TITLE
Supporting OBDC

### ISSUE THREAD

**Issue by karimhm** [Sequel-Ace/Sequel-Ace#611]
Adding [OBDC](https://en.wikipedia.org/wiki/Open_Database_Connectivity) to **Sequel Ace** would make it possible to use it with many databases other than MySQL and MySQL Like ones.

**Comment by karimhm** [comment]
Related to #61

**Comment by Jason-Morcos** [comment]
I believe this is a means to accomplishing #61, yes? Overall, this and #61 are basically duplicates so I encourage you to comment over there instead if you have suggestions!
