### ISSUE TITLE
Timed queries

### ISSUE THREAD

**Issue by christatedavies** [Sequel-Ace/Sequel-Ace#613]
I'm running some user tests on an application which require me to refresh a query after each user action.

It'd be really good if I could set a timer (say 4 seconds) and the query in focus would continue to run so I can have two windows open and not have to keep switching between them.

I did actually clone the sequel ace code to see if I could do this myself using a timer, but I'm struggling to build the bundle. I get some GEM ruby issue so I cannot even play with it.

Anyway, it would be great to have this. I believe Heidi SQL and DBeaver both have this ability

**Comment by Jason-Morcos** [comment]
> I'm running some user tests on an application which require me to refresh a query after each user action.
> 
> 
> 
> It'd be really good if I could set a timer (say 4 seconds) and the query in focus would continue to run so I can have two windows open and not have to keep switching between them.
> 
> 
> 
> I did actually clone the sequel ace code to see if I could do this myself using a timer, but I'm struggling to build the bundle. I get some GEM ruby issue so I cannot even play with it.
> 
> 
> 
> Anyway, it would be great to have this. I believe Heidi SQL and DBeaver both have this ability

Checkout the instructions for building locally in the readme and if you still have trouble let us know again (but in a separate issue for building locally, not in this timer issue)
