### ISSUE TITLE
App freezes when running query

### ISSUE THREAD

**Issue by Callahhh** [Sequel-Ace/Sequel-Ace#622]
- Sequel Ace Version: 3.0.0
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7

**Description**
Just messing around with 3.0 (wasn't able to login before, but that was fixed in today's release!), clicked one of my "Query Favorites", then hit "run current" (or command + r). App is completely frozen & I have to force quit out of it. Basic queries like SELECT * FROM Table work fine, but any other query just freezes the app. Bit unhelpful I apologize, not entirely sure how to replicate it as it's happening to all my queries (joins, count, etc) and I can't pinpoint what's different between them. 

**Steps To Reproduce**
1. Run query that isn't just a basic SELECT * FROM Table
2. App freezes

**Expected Behaviour**
Not freeze. 
**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, I'm using the build that was released today. 
**Additional Context**
While the app is frozen, clicking the menu bar at the top instantly closes the dropdown. Commmand + Q'ing the app doesn't do anything, so I have to open the force close menu to close it. 

Love this app btw, have been using it for a while & it's awesome! Thanks 😊

**Comment by cappadaan** [comment]
+1, any query freezes the app

**Comment by jamesstout** [comment]
Just using the keyboard shortcut freezes the app?

I can replicate the freeze pressing the run current button, but cmd+r works ok.

**Comment by cappadaan** [comment]
same here, cmd + r works
