### ISSUE TITLE
Create table window is really small

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#623]
Version 3.0.0

Table info > Create table window is really small

<img width="519" alt="Screenshot 2020-12-15 at 08 58 07" src="https://user-images.githubusercontent.com/25279400/102186982-aac46d80-3eb3-11eb-920e-6178af9aaafa.png">

**Comment by Kaspik** [comment]
You can drag the window (center top) to make it bigger. By default, this is not used by users, so it's smaller with optionally making it bigger. :)
