### ISSUE TITLE
SQL Code convert to comment isn't working

### ISSUE THREAD

**Issue by AstroBoy269** [Sequel-Ace/Sequel-Ace#639]
- Sequel Ace Version: 3.0.0
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.6

**Description**
When editing SQL queries in the Query Window, the system used to allow me to press the Command+/ key to automatically flag a line or lines as comments.  The key stroke still works but now instead of commenting out the highlighted line the formatter puts a commented version of the line at the end of the query.

**Steps To Reproduce**
1. Type a simple little multi-line query.  Click into a single line you want to comment out and then press Command+/
2. Alternatively, select multiple lines to comment out, then press command+/.  The system should use `/*` and `*/` to comment out the block, which it sort of does but the duplicates the commented out lines at the end of the query.

**Expected Behaviour**
1. The line that was active at the time of the Command+/ should be commented out
![Screen Shot 2020-12-16 at 4 16 09 PM](https://user-images.githubusercontent.com/10376292/102407468-2ad4fb00-3fba-11eb-8987-7fd039a428b8.png)
2. The lines that were active at the time of the Command+/ should be commented out with `/*` and `*/` instead of being appended to the end of the query 
![Screen Shot 2020-12-16 at 4 18 06 PM](https://user-images.githubusercontent.com/10376292/102407787-a767d980-3fba-11eb-83e5-20df7f24c3e7.png)

**Comment by Jason-Morcos** [comment]
Reopening as 2 parts still remain
Single-line comment out is fixed, but 2 issues still able to repo:
1. After you comment out a line, your cursor gets moved to the next line (which is actually quite annoying if you change your mind about a line)
2. Multi-line comment out still gets inserted at the end (selecting multiple lines and then doing cmd+/)
