### ISSUE TITLE
Query window seems to "forget" what query is active when editing the query and using Command+r for rerun

### ISSUE THREAD

**Issue by AstroBoy269** [Sequel-Ace/Sequel-Ace#640]
- Sequel Ace Version: 3.0.0
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.6

**Description**
**First, I wanted to say, I love the new 3.0.0 version and all the work the entire team has done with SequelAce.  The overall improvements and changes since the SequelPro days is awesome.**  

When you enter a new query the query window 'knows' which query you want to run when you do a Command+r, you can even see the command block highlighted.  However, after you run the query the code block is no longer high lighted and won't run with the Command+r sequence.  At this point you manually have to highlight the code block and then use Command+r.  A code block that has been manually highlighted will stay highlighted and the Command+r option will continue to work until you decide to edit the code block.  Then the block needs to be manually highlighted again.

**Expected Behaviour**
The "old" system seemed to 'guess' which block you wanted to run even if you had multiple query blocks on the screen as long as you had your statements separated with semi-colons.  It used the cursor location for that guess.  So you could edit a few lines in a long statement and simply hit Command+r again to rerun that query.

- Here's an example where the editor has highlighted a block as I added the semi-colon to the end.  This will successfully execute with a Command+r 
![Screen Shot 2020-12-16 at 4 28 42 PM](https://user-images.githubusercontent.com/10376292/102408642-e77b8c00-3fbb-11eb-859b-b863dae18b66.png)

- After command execution this block is no longer highlighted and will not execute with Command+r. 
![Screen Shot 2020-12-16 at 4 29 57 PM](https://user-images.githubusercontent.com/10376292/102408736-0bd76880-3fbc-11eb-89ba-efc8358e1879.png)

- Manual highlighting restores the Command+r functionality again 
![Screen Shot 2020-12-16 at 4 31 12 PM](https://user-images.githubusercontent.com/10376292/102408849-31647200-3fbc-11eb-8f72-2d2c3a127a94.png)
- Edit this code block anywhere and the highlighting is lost and so is the Command+r

**Comment by shaunek** [comment]
I'm also experiencing this problem, and wanted to share a brutish workaround in the case that you hate to highlight the query manually yourself... if you do CMD+R and it has "forgotten" which query to highlight/run, you can just type in any character, perhaps a space, tab, or ENTER and then hit CMD+R again. It will magically remember how to highlight the right query. Then the next time you want to run you can hit backspace and CMD+R. 

Super lame workaround, I know, but someone might find this helpful until the issue is resolved.

**Comment by lphilps** [comment]
I see another "likely related" problem to this one.  In version 3.0.1 if I open the Query window and enter any query, say
`select * from users limit 1;`
then I click "Run Previous" it works.  But subsequent clicks of "Run Previous" fail - Sequel Ace just beeps and does nothing.  If I go back into the query window, type a space after the semi-colon and then click "Run Previous", it works, the first time, then beeps on subsequent attempts.  Go back into the query window, backspace over the space and you can run the command ... exactly once.

So, it seems that after executing a query, it's completely losing context that isn't restored until "something changes" in the query input window itself?

**Comment by Jason-Morcos** [comment]
Another issue report (#689) also indicated the same thing is true after pasting a query. Something about we need to make the query window re-find selection after a query is run or content is pasted.
