### ISSUE TITLE
Crashes when trying to run app with error "Unable to load nib file: MainMenu, exiting"

### ISSUE THREAD

**Issue by tomasvts** [Sequel-Ace/Sequel-Ace#649]
- Sequel Ace Version: 3.0.0
- macOS Version: 11.1 Big Sur
- Processor Type (Intel/Apple): Intel
- MySQL Version: Not related

**Description**
On 11.1 macOS Big Sur installed Sequel Ace from AppStore and Downloaded the last release (the same 3.0.0 version) and both failed with:
*2020-12-18 08:38:15.051 Sequel Ace[43105:2098132] Unable to load nib file: MainMenu, exiting*

**Steps To Reproduce**
1. Install from AppStore
2. Run it

**Expected Behaviour**
The app should start correctly.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**
I don't know if it matters, my Xcode version is 12:3 (12C33)

![image](https://user-images.githubusercontent.com/4351937/102587890-e0b05e80-410c-11eb-9467-2b6fc3ecbffa.png)

**Comment by alvaro-octal** [comment]
No sure if this is the same issue, but on MacOS 10.13 High Sierra the app crashes it self instantly.

**Comment by Kaspik** [comment]
I think your localization of your macOS is not "EN" in which case (just found out) it fails because when we added localizations, I didn't add fallback. Will be fixed in 3.0.1 asap.
