### ISSUE TITLE
Test Connection works, but can not connect to database using SSH details

### ISSUE THREAD

**Issue by mira-thakkar** [Sequel-Ace/Sequel-Ace#652]
- Sequel Ace Version: 3.0.0
- macOS Version: 10.15.7 ( MacOS Catalina)
- Processor Type (Intel/Apple): Intel Core i5
- MySQL Version: Mysql 8.0

**Description**
I am not able to connect the database using 

**Steps To Reproduce**
1. Add Database and ssh connection details
2. Try testing connection with database and ssh credentials set
3. Now try to connect to the same database

**Expected Behaviour**
It should be able to connect successfully

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Additional Context**
On test connection
![Screenshot 2020-12-18 at 6 28 11 PM](https://user-images.githubusercontent.com/13957788/102617432-2eee4d80-415f-11eb-8832-fbdca6dd9edc.png)

On connecting 
![image](https://user-images.githubusercontent.com/13957788/102617719-a4f2b480-415f-11eb-9719-56f7e1c8ec09.png)

**Comment by Kaspik** [comment]
Are you editing favorite? If so, you need to first hit "save changes" (based on your screenshot).

**Comment by mira-thakkar** [comment]
@Kaspik Thanks a lot @Kaspik. It works :D
