### ISSUE TITLE
Need Multiple query editor in tabs

### ISSUE THREAD

**Issue by atishamte** [Sequel-Ace/Sequel-Ace#661]
Like heidisql, here we would require multiple query editors to be open in tabs

**Comment by Jason-Morcos** [comment]
Currently, you can just open multiple app tabs with a query editor in each as a workaround.

**Comment by pinpins** [comment]
But titles for them are as per table, would like to see opened .sql file in title for each tab

**Comment by pinpins** [comment]
Pity is just got closed
