### ISSUE TITLE
Need to view multiple query result in tab if we run multiple select query in query editor

### ISSUE THREAD

**Issue by atishamte** [Sequel-Ace/Sequel-Ace#662]
Need to view multiple query result in tab if we run multiple select query in query editor

**Comment by pinpins** [comment]
Pity it is low prio, otherwise needful feature

**Comment by andrewinsurify** [comment]
@Jason-Morcos, any chance this might make the list now?  Would be super helpful!

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos, any chance this might make the list now?  Would be super helpful!

PRs to add features are always welcome and reviewed in a timely fashion :)
Speaking for myself personally, I've been very busy with work/personal life and certainly can't commit to working on this anytime soon.
