### ISSUE TITLE
Export database/tables from one connection to other directly

### ISSUE THREAD

**Issue by atishamte** [Sequel-Ace/Sequel-Ace#663]
Export database/tables from one connection to other directly

eg. I want to transfer 3 tables from DB-A to DB-B, there should be direct option to export instead of exporting to csv or sql file

**Comment by mfehr94** [comment]
See PR #620

**Comment by atishamte** [comment]
This PR is regarding database between the same connection. I have raised the same with respect to copying tables between databases of separate connection.

**Comment by Jason-Morcos** [comment]
Marked this as low priority as there's an easy workaround available - exporting as SQL and then importing into the other DB.

**Comment by atishamte** [comment]
I think, this feature should be there. So no SQL file handling would be there and can be done on transaction basis

**Comment by Jason-Morcos** [comment]
I don't disagree that the feature would be nice, however we have finite resources. This issue has been open a while. Nobody in the core team has had sufficient passion/time/resources to get this done, and nobody in the community has deemed to jump to implement and PR the feature. At a certain point, having an open PR for this serves no real utility. See my response to #329.
