### ISSUE TITLE
Auto update or at least version check?

### ISSUE THREAD

**Issue by n9yty** [Sequel-Ace/Sequel-Ace#666]
Thanks so much for the early Christmas present of v3.0!

The former project had an auto-update feature, could that be reimplemented? Or at least a version check and notification of new version? You could make it optional for people who don't want any unknown/unwanted outbound connections.

If it is there and I just can't find it, I'm sorry, but I just randomly checked and saw v3 otherwise I wouldn't have known.

Thanks for the consideration,
 Steve

**Comment by Kaspik** [comment]
Hey! Thanks for letting us know.

As the primary channel for us is AppStore, that has auto-update, I'll close this with "not now" answer unfortunately.

We will reconsider this later probably once we sort-out more infra, more important, features. :)

**Comment by Kaspik** [comment]
Btw. @n9yty , I already suggested this to someone else in older ticket - setup IFTTT notification for GitHub releases if you want! :)
https://rschu.me/github-release-notification-via-ifttt-2346f3a71f3b
