### ISSUE TITLE
Strange title and sidebar behavior

### ISSUE THREAD

**Issue by chumbawumba** [Sequel-Ace/Sequel-Ace#669]
- Sequel Ace Version (including build number): 2.3.2 2121
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.0.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: n/a

**Description**
In Big Sur the title bar is somewhat mangled with the "ssh connected" underneath the icons on the right-side.

I'm not sure if this is related, but I've noticed since the upgrade that there is a gap above the table list that I can't seem to get rid of even if I expand and contract the table details pane. It is just an odd permanent gap above the table listings.

**Steps To Reproduce**
1. Connect to any server through an SSH tunnel on Big Sur
(I don't know how to reproduce the cosmetic gap issue, it's been persistent since the upgrade)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
The "ssh connected" yes, the table gap no.

**Additional Context**
2.3.2 (2121)
![image](https://user-images.githubusercontent.com/8107428/102834307-ab806680-43c1-11eb-8ebc-81406baf128b.png)

3.0.1 (3008)
![image](https://user-images.githubusercontent.com/8107428/102834752-f2229080-43c2-11eb-9dbb-5e02e9d2b1d0.png)

**Comment by Jason-Morcos** [comment]
That table side bar space issue was indeed fixed in 3.0.0. In general, we won't worry about issues with any version of Sequel Ace older than the latest release.
Menu bar text issue overlapping known, duplicates #497
