### ISSUE TITLE
Increase font line height

### ISSUE THREAD

**Issue by mattkingshott** [Sequel-Ace/Sequel-Ace#672]
At the moment, the spacing between table rows is very narrow, making it difficult to identify individual rows at a glance.

Is there a way to increase the spacing / line height of these rows?

Thanks!

**Comment by Kaspik** [comment]
Can you give u some info / screenshots what you mean / where, as well as your font settings in preferences?

**Comment by mattkingshott** [comment]
My font settings are unchanged / the defaults. Here is a screenshot. I'd just like to add some vertical padding between the rows

![Screenshot 2020-12-22 at 2 40 29 pm](https://user-images.githubusercontent.com/51963402/102900140-ce635700-4463-11eb-966a-771486ecc684.png)

**Comment by jamesstout** [comment]
Current:

![Screenshot 2020-12-24 at 11 41 41 PM](https://user-images.githubusercontent.com/1576190/103097454-3f606580-4642-11eb-81ba-e8ada5057c26.png)

+3 points

![Screenshot 2020-12-24 at 11 41 21 PM](https://user-images.githubusercontent.com/1576190/103097756-49369880-4643-11eb-933b-6d21960b10da.png)


+5 points


![Screenshot 2020-12-24 at 11 40 57 PM](https://user-images.githubusercontent.com/1576190/103097761-4e93e300-4643-11eb-8000-bd78fd29c26c.png)

**Comment by Kaspik** [comment]
Does it adjust when you increase font size? We need ti make sure the spacing is not gonna be huge then.

**Comment by mattkingshott** [comment]
Personally, I’d say 5 points above and below would be good, though it would be ideal if it was adjustable through settings. 

At present, It does adjust when you change font / size, but it varies wildly depending on the font’s natural line height.
