### ISSUE TITLE
SQL insert query copy and paste - crashing app

### ISSUE THREAD

**Issue by rajjanorkar** [Sequel-Ace/Sequel-Ace#673]
- Sequel Ace Version (including build number): 3.0.1
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8
- macOS Localization: English

**Description**
Copy large sql insert query from on table - using right click "copy as sql insert"
then try to paste it in query console.

App hangs - don't respond i had to force close it.

**Steps To Reproduce**
see above

**Expected Behaviour**

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Related Issues**

**Additional Context**

**Comment by Kaspik** [comment]
How `large` are we talking about? When inserting a code to the query editor, we now process syntax highlight. There is expected behavior that it's on main thread and will `hang` the app for a second(s) based on how big the query is. If we are talking about 4000 lines, it can take up to 20 seconds. Can you give me some details about the query size or if it works when you wait a little?

**Comment by rajjanorkar** [comment]
Based on your answer.
Does not matter how big/small the copy/paste is. Just go to query console and try command + v or mouse right click paste.
App goes unresponsive.

**Comment by Kaspik** [comment]
Even if you go and paste `SELECT * FROM table LIMIT 1;`?

**Comment by rajjanorkar** [comment]
Have you tried?

1. open any table select (few or all rows) right click and "Copy as SQL insert"
2. Open query console
3. Do paste

Try big/small selection if you would like.

See what happens.

**Comment by rajjanorkar** [comment]
It goes unresponsive for me - i waited for 2 to 3 mins then i need to force quit.

If it works for you then don't bother - it may be just me and i will go and use previous version.

**Comment by Kaspik** [comment]
Okay, update here:

I'm able to repro it if I select all rows in some table with 15 columns (my preference is to show 1000 rows), which means I paste to the query editor 191 605 characters. That's just tooo big text for the syntax highlighter - that's also why I asked about how big query are we talking about.

I'll restrict the force syntax highlight on paste to small insert only for next version, which means the syntax highlight will be then calculated on the go when you edit the query.

**Comment by rajjanorkar** [comment]
Perfect thank you so much. Will wait for next version then.

**Comment by Robert-Saiter** [comment]
Seems I got here too late but confirming I have the same issue, very happy to see the issue has been identified. 

Work around:  _**Preferences->Query Editor**_ and Uncheck _**Syntax highlighting**_.

**Comment by SeanPrashad** [comment]
Hi there peeps! Myself and another colleague just encountered this issue when attempting to run a query of a few million lines. Happy to share more data points and/or our steps to reproduce but in the meantime, will keep our eyes peeled for a patch! Cheers!

**Comment by jeanrajotte** [comment]
Hi all,

I'm working w/ a 7-row result set. When invoking "Copy as SQL INSERT (no auto_inc)", it crashes before putting the data in the clipboard.  When invoking "Copy as SQL INSERT", it just works.
