### ISSUE TITLE
Changing username/password of favorite works a bit wonky

### ISSUE THREAD

**Issue by websmurf** [Sequel-Ace/Sequel-Ace#679]
- Sequel Ace Version (including build number): 3.0.1 ( 3008)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intell
- MySQL Version: 5.6.
- macOS Localization: NL

**Description**
Since the last update from the app store (that was installed yesterday) I'm having difficulty connection to a mysql server over an SSH socket when changing the username/password that was stored there. 

Previously I could just enter the new username and password and click connect; and it would use the entered details. 
Now I need to save the favorite after I've changed the username, then again after changing the password to avoid the changes from not being stored.

**Steps To Reproduce**
1. Edit an existing favorite and enter a new username / password there
<img width="487" alt="Schermafbeelding 2020-12-23 om 10 49 58" src="https://user-images.githubusercontent.com/4027236/102984363-c3fd9780-450d-11eb-92fd-414acb486a52.png">
2. Click connect without saving; the connection will fail: 
<img width="577" alt="Schermafbeelding 2020-12-23 om 10 50 28" src="https://user-images.githubusercontent.com/4027236/102983933-1ab6a180-450d-11eb-92fb-662a6916c090.png">

This flow will work:
1. Edit an existing favorite and enter a new username
2. Save the change
3. Enter a new password
4. Save the change again
5. If you click connect at this point, it will fail the connection again with the same error
6. Click one of the other favorites, then switch back to the one you edited and click connect -> This will work.

**Expected Behaviour**
Either the new username/password will be used if you input them or directly after you store them (I would prefer the first since we have quite a few customers where the connection details are the same except for the username/password)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
There are currently no newer beta's available.

**Related Issues**
Perhaps related: #674

**Comment by Kaspik** [comment]
Yeah, related to not only #674 but also to #675 - should be fixed on master + by #678 - will be released in beta asap.

**Comment by websmurf** [comment]
Ah roger, missed 675 for some reason. Sorry for that!

**Comment by Kaspik** [comment]
No worries. :)
