### ISSUE TITLE
Password Removed After Saving To Favourites

### ISSUE THREAD

**Issue by anywherecreative** [Sequel-Ace/Sequel-Ace#685]
- Sequel Ace Version (including build number): 3.0.1 Build 3008
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: N/A

**Description**
When saving a new favourite testing the credentials succeeds, but connecting clears the password preventing connection. Closing and opening the application restores the password. 

**Steps To Reproduce**
1. Add New favourite
2. Test connection (should succeed) 
3. Save
4. connect (this will fail)

**Expected Behaviour**
After saving or pressing connect, the password should remain and the connection should succeed.

**Comment by jamesstout** [comment]
Should be fixed in the next build. @Kaspik fixed in #677 and #678
