### ISSUE TITLE
Option to disable sounds

### ISSUE THREAD

**Issue by JonLaliberte** [Sequel-Ace/Sequel-Ace#687]
Would be nice if there were a setting to allow disabling the disconnect (or any other) sounds.

**Comment by Jason-Morcos** [comment]
<img width="668" alt="Screen Shot 2020-12-23 at 10 41 59" src="https://user-images.githubusercontent.com/10710367/103027879-88fa6480-450b-11eb-8738-58de52fad351.png">
You can turn off sounds for notifications (such as the connect and disconnect notifications) in System Preferences. I don't believe there are other sounds except those through notifications (except perhaps a few system beeps)

**Comment by JonLaliberte** [comment]
🤦🏼‍♂️Thanks, it wasn't clicking that these were coming from the notifications.

**Comment by campsoftware** [comment]
OMG. Thank you. This was driving me nuts!
