### ISSUE TITLE
ScaleFT support

### ISSUE THREAD

**Issue by nilbus** [Sequel-Ace/Sequel-Ace#694]
My organization uses [ScaleFT](https://www.scaleft.com/) to secure SSH access via Okta SSO. This results in a `.ssh/config` similar to

```
Match exec "/usr/local/bin/sft resolve -q  %h"
  ProxyCommand "/usr/local/bin/sft" proxycommand  %h
  UserKnownHostsFile "/Users/user/Library/Application Support/ScaleFT/proxycommand_known_hosts"
```

Now that Sequel-Ace is sandboxed, this configuration isn't picked up by default. By v2.1.1, Sequel-Ace added support for specifying a proxy command and specifying files to allow the application to break out of the sandbox to access, which are both needed to get ScaleFT working. However, it isn't clear yet which files need to be granted access for `sft` to work properly. See https://github.com/Sequel-Ace/Sequel-Ace/issues/68#issuecomment-656127448.

I'd like to use this issue first to explore finding a working solution with @robert-chiniquy, who built ScaleFT. Then once we have a working solution, we can explore ways that Sequel-Ace might make it easier to configure for ScaleFT.

**Comment by robert-chiniquy** [comment]
Hey, Merry Christmas! Until I get a SequelAce environment set up I can test with, it would help if you could get me some troubleshooting info from your environment when you try to connect. There's a message in the logs concerning `SP_PASSWORD_METHOD`, an env var that it looks like SequelAce sets (similar to SequelPro) in some circumstances, I'm curious if I will see this log message in your client logs or if I will see something else. 

To get me your logs, you can just:
1. Try a failing connect with SequelAce using `sft proxycommand` as in your example ssh config, and then immediately after
2. Run `sft support submit` and share the resulting support code which it prints in this issue.

Doing it immediately after is really helpful just in case there are a lot of logs, it means I can just check the most recent couple files and I won't have to dig.

**Comment by nilbus** [comment]
Sounds good. I can try this on Monday.

**Comment by nilbus** [comment]
@robert-chiniquy Done. Support code: `careful-spirit`

Error detail:
```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/nilbus/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Users/nilbus/.ssh/config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 production-data-bastion -L 58384:prod-mysql-master.dox.box:3306

OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/nilbus/.ssh/config
debug1: Executing command: '/usr/local/bin/sft resolve -q  production-data-bastion'
ssh: Could not resolve hostname production-data-bastion: nodename nor servname provided, or not known
```

The `production-data-bastion` host normally only resolves via `sft resolve`, not standard DNS. It is the SSH Host I have configured in Sequel Ace, and I can ssh to that host using `ssh`, outside of Sequel Ace.

I have marked these files as accessible in the app preferences:
![accessible files](https://user-images.githubusercontent.com/64751/104057966-f91e1100-51c0-11eb-8cd6-a8faa6ba83c2.png)

Could you take a look at the diagnostics data and let me know what you see? Thanks!

**Comment by nilbus** [comment]
I took a look at the logs via `sft support collect`.

I see an error frequently:

    2021-01-08T14:44:57.117-0500    DEBUG   Did not load a config from file, using default values   {"path": "/Users/nilbus/Library/Application Support/ScaleFT/sft.conf", "error": "stat /Users/nilbus/Library/Application Support/ScaleFT/sft.conf: no such file or directory"}

That seems to be a red herring though, because that file truly does not exist, not there nor anywhere else under my home dir, even when I can successfully `ssh production-data-bastion` outside of Sequel Ace.

**Comment by nilbus** [comment]
Playing with it more, I'm finding that running sft within the Sequel Ace sandbox **does not produce logs** that get persisted outside of the sandbox that `sft support` can collect.

**Comment by nilbus** [comment]
@Jason-Morcos @jamesstout Since the Add Files file selector does not allow selecting a directory, we're unable to diagnose this issue. Is it possible to make that file selector also grant write permissions to a directory?

**Comment by Jason-Morcos** [comment]
> @Jason-Morcos @jamesstout Since the Add Files file selector does not allow selecting a directory (`~/Logs/ScaleFT/sft/`), we're unable to diagnose this issue. Is it possible to make that file selector also grant write permissions to a directory?

Latest release file selector allows selecting directories :)

**Comment by robert-chiniquy** [comment]
Hey, sorry for the delay checking in, I got wrapped up in work after New Year's. 

OK, so, checking your client logs, like you said, not very much there, also yes that message re: config file is a red herring. 

Anyway, I did not see the message I expected after skimming the SequelAce source code, so we have an additional step we can try which may help. Could you set an environment variable in your shell and try again? I'm not sure how you get the environment variable into the context where it is being used, let me know if you want help figuring that out. The variable name is `SFT_SKIP_BRIDGE_QUEUE`, and you can just set it to "yes" (but any non-zero length string should do). This slightly changes the timing between SSH channel initialization and TCP connection states in a way which helps clients outside of the terminal sometimes. Anyway if you can get that set, try again, and if it works, great, but if it doesn't, then get another support bundle please.

**Comment by robert-chiniquy** [comment]
I think there's a spot in SequelAce where environment variables are set for the proxycommand process, right? Probably can just add it there to test.
