### ISSUE TITLE
Older MySQL server password format?

### ISSUE THREAD

**Issue by n9yty** [Sequel-Ace/Sequel-Ace#70]
This had been working in Sequel Pro, and I think it has to do with the old/new password format, but I can't log into some servers running very old versions of MySQL.

Can this be remedied, either automatically or via a configuration setting?

**Comment by Jason-Morcos** [comment]
Which version of Sequel Ace are you using?

**Comment by n9yty** [comment]
Oh, I pulled the latest from the releases page here, maybe that is the problem. I saw it added MySQL 8 support so I thought that may have been it. 

It is v2.1.0-beta2 build 2036

**Comment by Jason-Morcos** [comment]
Ahh could quite possibly be something broken by MySQL 8! Did the latest App Store release/2.0.2 beta work for you?

What version of MySQL is the "old version" being run?

**Comment by n9yty** [comment]
There are several old servers, probably v5.0.xx versions.

The App Store version works.

**Comment by Jason-Morcos** [comment]
@gboudreau Any ideas? Probably indeed caused by MySQL 8 updates. Maybe need some legacy stuff?

**Comment by gboudreau** [comment]
Pretty sure the latest MySQL libraries stopped supporting old passwords a while ago, for security.

@n9yty Can you try the latest version of the MySQL Workbench to connect to those servers?
If it works, or not, might help us know if there is a way forward or not, on the client-side

**Comment by n9yty** [comment]
Well, I had v8.0.14 installed, the latest is v8.0.20, but the version installed doesn't work. I haven't used that for a long time on these old servers so I hadn't noticed.

Same message:
Your connection attempt failed for user 'xxxxxxx' to the MySQL server at xxxxx.xxxxx.xxxxx:3306:
  Bad handshake

So I guess the answer is.... Keep an old version of the program (or some program) around for managing those old databases. It's a shame they can't be upgraded, but it is what it is.

**Comment by Jason-Morcos** [comment]
Unfortunate, but good to know. Perhaps we should note somewhere the minimum supported MySQL version and then close out this issue?

**Comment by Jason-Morcos** [comment]
My hunch would be MySQL 6 is minimum supported, but that's just a guess.

**Comment by n9yty** [comment]
Yes, that is why I filed as a feature request not a bug, I was afraid this might be just the way it will have to be. Thanks!  I think WorkBench says 5.5 or higher.
