### ISSUE TITLE
[Visual] Tab bar has slowmo animations and glitchy visual

### ISSUE THREAD

**Issue by oliveratgithub** [Sequel-Ace/Sequel-Ace#707]
- Sequel Ace Version (including build number): 3.0.1 Build 3008
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: Big Sur 11.2 Beta (20D5029f)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.11
- macOS Localization: English

**Description**
The Tab bar for multiple connections is glitched with displaying 1 tab aftre closing/collapsing another. And is very slowly collapsing additional or back to 1 single tab. See video:

https://user-images.githubusercontent.com/280207/103212783-1ecb3080-490c-11eb-8171-f9720fb421f7.mov

**Steps To Reproduce**
1. Open Sequel Ace
2. Open a connection
3. Open another connection in a new Tab
4. Observe the tab bar
5. Close one of the tabs
6. Observe the behaviour in the tab bar

**Expected Behaviour**
Snappy & visually clear behaviour :)

**Comment by Kaspik** [comment]
I believe the "single" tab is not a glitch but it's shown because of the favorite color. It's orange to refer to orange color for your favorite. :)

The animation could be smoother tho.

**Comment by jamesstout** [comment]
In the code ... "hackery follows" :

```objc
- (void)frameDidChange:(NSNotification *)notification
{
	[self _checkWindowFrame];

	// trying to address the drawing artifacts for the progress indicators - hackery follows
	// this one fixes the "blanking" effect when the control hides and shows itself
```

**Comment by Kaspik** [comment]
Thinking about this even more, I think we will drop the animation, and we will behave the same as Safari and other native apps - we will show the tab all the time with `+` button on right side. We will be able to get rid of a lot of code and the "weird" view above will be real tab. :)

**Comment by oliveratgithub** [comment]
> Thinking about this even more, I think we will drop the animation, and we will behave the same as Safari and other native apps

Sounds legit :)

**Comment by oliveratgithub** [comment]
Wow you guys are fast 🚀
