### ISSUE TITLE
Favorites missing on pre-releases

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#708]
- download pre release
- rename Sequel Ace Beta.app to Sequel Ace.app
- overwrite existing app (with working favorites)
- open app
- all favorites are gone

This way we cannot use or test pre releases.

**Comment by jamesstout** [comment]
Even though you rename it, internally, it's still `com.sequel-ace.sequel-ace-beta`. 

You can copy:

`/Users/<user>/Library/Containers/com.sequel-ace.sequel-ace/Data/Library/Application Support/Sequel Ace/* `

to

`/Users/<user>/Library/Containers/com.sequel-ace.sequel-ace-beta/Data/Library/Application Support/Sequel Ace Beta/`

**Comment by oliveratgithub** [comment]
I had to do the copy magic to get the favorites in the pre-release 👍

**Comment by Kaspik** [comment]
Please DON'T rename the app locally. It has different name on purpose - so you can have both version at the same moment - this way, on main app, just `export` favorites` and in beta just `import` them.

Internally it's separated, so you might mess with your data when updating back to main app if you rename beta.
