### ISSUE TITLE
Password Not Sent When Not Saved In Connection Details

### ISSUE THREAD

**Issue by PeterLavetsky** [Sequel-Ace/Sequel-Ace#709]
- Sequel Ace Version (including build number): 3.0.1 Build 3008
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.14.6
- Processor Type (Intel/Apple):Intel
- MySQL Version:
- macOS Localization: en_us

**Description**

Using a Favorite connection that does not have the password saved, the password appears to not be sent to the server after being entered and clicking Connect or pressing Return.

Using the same Favorite connection, if the password is entered and then Save changes is clicked, the password is then sent correctly to the server when clicking Connect or pressing Return.

Only after clicking Save changes with a password entered am I able to connect to the server.

![Screen Shot 2020-12-28 at 9 29 46 AM](https://user-images.githubusercontent.com/882344/103221265-35638e80-48f0-11eb-97cd-78b160c5eb85.png)

**Comment by PeterLavetsky** [comment]
Appears to be fixed in beta.

**Comment by Kaspik** [comment]
Yes, https://github.com/Sequel-Ace/Sequel-Ace/issues/675, https://github.com/Sequel-Ace/Sequel-Ace/issues/674 and couple of others. :)
