### ISSUE TITLE
Hanging during update via app store

### ISSUE THREAD

**Issue by carkar7** [Sequel-Ace/Sequel-Ace#717]
- Sequel Ace Version (including build number): 3.0.1 3008
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.13.6 
- Processor Type (Intel/Apple): 2.6 GHz Intel Core i7
- MySQL Version: 5.6.25
- macOS Localization:

**Description**
This is an issue related to updates on the app store. The app store doesn't appear to be recognizing the update as it does not recommend it to me via the updates area in the app store application. But, if I attempt to update the app to the new version by searching for "sequelace" and selecting "update" manually, it just hangs. I appears that I need to wait a couple of days after the latest release otherwise attempting to updated this way just results in hanging. Luckily, I was able to download the 3.0.1 update yesterday morning after trying last week with the same issue. However, today I see that there is another update for v3.0.2, again this doesn't appear in the updates section of the app store and using the aforementioned process results in the same hanging issue. FWIW, coworker of mine is experiencing the same issue.

**Steps To Reproduce**
1. Open App Store
2. Search "SequelAce"
3. Select "Update"

**Comment by Kaspik** [comment]
3.0.2 is out as a phased rollout available only for 1% of users, that's why it wasn't offered yet. :)

Issues with AppStore need to be resolved via AppStore, usually logging out, removing the app, clearing AppStore cache or something similar...

We expect 3.0.2 to be out during this week fully.
