### ISSUE TITLE
pasting in query editor has lag

### ISSUE THREAD

**Issue by SBerkovic** [Sequel-Ace/Sequel-Ace#718]
- Sequel Ace Version (including build number): 3.0.2 (3010)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.14.6
- Processor Type (Intel/Apple): Intel i7
- MySQL Version: 5.6.20
- macOS Localization: English

**Description**
pasting into a query editor that has many (50+) lines of sql already in it is very slow, causes the spinning beach ball and can take a long time to complete the paste. It seems to get worse with more lines of sql in the editor. sometimes it gets better when you add in more sql for a total of about 215 lines.

**Steps To Reproduce**
1.open editor and add many lines of sql - 150 should be enough to clearly see the lag
2. paste in a number or character 

**Expected Behaviour**
pasting into editor should be near instantaneous 

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
yes

**Related Issues**

**Additional Context**

**Comment by Kaspik** [comment]
That is (unfortunately) known issue for now. To make query editor faster, we process syntax highlight on paste directly (up to certain size of the query) which leads to spinning ball and couple of secs lag (again depends on query size).

That was improved a lot for 3.1.0, but won't be fixed until we switch to background processing (somehow, later on...).

Closing in favor of #715 but keeping in mind with other issues.
