### ISSUE TITLE
Field Popup Text to Json Format  is Breaking

### ISSUE THREAD

**Issue by isopropylcyanide** [Sequel-Ace/Sequel-Ace#726]
- Sequel Ace Version (including build number): 3.0.1/3008
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel i7
- MySQL Version: 5.7.32
- macOS Localization: Asia/En

**Description**
Selecting a column of type "TEXT" from a row opens a pop up. If this text column contains valid JSON data, it is not converted to its equivalent form. Conversion to Hex / Text works but conversion to Text <-> Hex does not.

**Steps To Reproduce**
1. Screencast is attached

**Expected Behaviour**
- JSON format / conversion should happen properly.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
No

https://user-images.githubusercontent.com/12872673/103375262-c3fa2a80-4aff-11eb-8a56-cdbf4e5590d1.mov

**Related Issues**
Did a grep on "JSON". Couldn't find it in the issues dir.

**Comment by jamesstout** [comment]
I fixed a bug recently with the JSON segment, I'll take a look.

**Comment by jamesstout** [comment]
How's this?

https://user-images.githubusercontent.com/1576190/103405757-25b7a480-4b93-11eb-96b1-481cf9fa8ebb.mp4

**Comment by isopropylcyanide** [comment]
This looks good. Can you try with a heavier payload as well, say a couple of megs? That should seal the deal.

**Comment by jamesstout** [comment]
10MB worked fine ... a little sluggish though. Vid rendering...

**Comment by jamesstout** [comment]
https://user-images.githubusercontent.com/1576190/103415877-0e8eac00-4bbf-11eb-9427-b1c90baa105b.mp4

**Comment by isopropylcyanide** [comment]
That looks good @jamesstout Pretty print for 10 megs was quick.

**Comment by jamesstout** [comment]
There was a guard before attempting to convert the cell data to JSON. It only checked that the data was of `NSData` type, but it could also be of `NSString` type.

I just changed:

```objc
 if([sheetEditData isKindOfClass:[NSData class]]) {
```

to

```objc
if([sheetEditData isKindOfClass:[NSData class]] || [sheetEditData isKindOfClass:[NSString class]]) {
```

It wasn't introduced with my other bug fix.
