### ISSUE TITLE
Two custom queries with syntax errors = crash

### ISSUE THREAD

**Issue by jamesstout** [Sequel-Ace/Sequel-Ace#734]
- Sequel Ace Version (including build number): 302 3010
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7 (19H15)
- Processor Type (Intel/Apple):
- MySQL Version: mysql (5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal)
- macOS Localization: en_HK

**Description**
Enter two bad queries and execute - crash

**Steps To Reproduce**
1. Open db, table, custom query window
2. enter two queries with syntax errors. e.g.

```sql
drop database 'GGGGGG';
drop database 'VVVVVVV';
```
(those a single quotes, not backticks)

3. select and run all
4. app crashes with 

`[SPMainThreadTrampoline setStringOrNil:]: unrecognized selector sent to instance 0x60000001f1e0`

**Expected Behaviour**
No crash and alert/error in console saying syntax error.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** YES

**Related Issues**

**Additional Context**

```
[General] An uncaught exception was raised
2021-01-02 14:16:09.162842+0800 Sequel Ace[21166:1705937] [General] -[SPMainThreadTrampoline setStringOrNil:]: unrecognized selector sent to instance 0x60000001f1e0
2021-01-02 14:16:09.162933+0800 Sequel Ace[21166:1705937] [General] (
	0   CoreFoundation                      0x00007fff37ac4b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff709505bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff37b43be7 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff37a293bb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff37a28d98 _CF_forwarding_prep_0 + 120
	5   Sequel Ace                          0x000000010000ceeb -[SPCustomQuery performQueriesTask:] + 5787
	6   Sequel Ace                          0x000000010031c454 -[SPNamedThread run:] + 148
	7   Foundation                          0x00007fff3a0da7b2 __NSThread__start__ + 1064
	8   libsystem_pthread.dylib             0x0000000101340c65 _pthread_start + 148
	9   libsystem_pthread.dylib             0x000000010133c4af thread_start + 15
```
)

**Comment by Jason-Morcos** [comment]
Fixed by #736 and will be included in next release
