### ISSUE TITLE
Tunneling over SSH is difficult and unreliable — keychain/passwords don't work well

### ISSUE THREAD

**Issue by cal-zone** [Sequel-Ace/Sequel-Ace#745]
- Sequel Ace Version (including build number): 3.02
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version:
- macOS Localization:

**Description**

When first trying to use Sequel Ace, there was utterly no way I could get it to connect using an SSH tunnel. I noticed the database password would either get cleared or replaced with some ultra long string. Manually typing both a new database password and SSH password ended up in connection failure due to SSH password being rejected.

Eventually, I tried seeing if I could follow the migration steps from Sequel Pro and only then I could finally connect, but even then, it always asks me for the SSH password with a prompt saying it cannot retrieve the password from the keychain.

This is even though I've connected many times and tried saving the connection many times and verified the password is in the keychain. This is even if I type the password in the connection details (except then I have no known hosts field and the connection fails because of that).

Once I get a bookmark working (but still prompting me for a password every time) if I change ANY detail about the bookmark, it breaks and fails to connect every time (password failure). The database password gets cleared and manually entering it doesn't help. 

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

Password management and known hosts management should be seamless and transparent to the user. Most of us are pretty technical, but really un-ideal to force us to designate which ssh known hosts file we want to use and un-ideal to not handle a changed hosts key gracefully. A user should enter a password for a connection once and everything should work and never have to deal with it again. 

This is a major security issue. Passwords should be difficult. SSH passwords and MySQL passwords especially. And they should be different from each other. For anyone who manages multiple systems, remembering and dealing with all these passwords becomes impossible and that's why we have a keychain that takes care of all of this.

Sequel Pro did not have this password issue (however, it did recently exhibit bad known-hosts management behavior for me). I would hope/expect Sequel Ace to behave the same way in regards to managing ease of connecting.

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Related Issues**

**Additional Context**

**Comment by Kaspik** [comment]
Keychain and password have been changed for 3.0.2 and for 3.1.0 as well to fix many issues. There is a known issue - https://github.com/Sequel-Ace/Sequel-Ace/issues/437 - but that shouldn't be your case.

Your issue template also misses a lot of details - installation source, build number, did you try the latest beta with fixes?

I suggest trying that first once new beta comes out today.

**Comment by cal-zone** [comment]
I'm using the app from the App Store. I don't build my own apps.

**Comment by cal-zone** [comment]
I just looked in About Sequel Ace:

3.0.2
build 3010

**Comment by Jason-Morcos** [comment]
One note - any time you change anything about the connection, the password is cleared. This is for security. #78 
Additionally, are you saving the connection after making changes before trying to connect?

**Comment by Kaspik** [comment]
I just shipped 3.1.0 beta 2 - there are some improvements. Note that we are not able to fix changed password in keychain (yet), so if something doesn't work, I recommend clearing the keychain so it's stored in next "save" again in clear state if it's messed up now.

**Comment by Kaspik** [comment]
3.1.0 is out.
