### ISSUE TITLE
Copy as SQL INSERT (no auto_inc) is broken

### ISSUE THREAD

**Issue by SBerkovic** [Sequel-Ace/Sequel-Ace#747]
- Sequel Ace Version (including build number): 3.1.0 (build 3012)
- Sequel Ace Source (App Store/GitHub/Homebrew): Git Hub
- macOS Version:  10.14.6
- Processor Type (Intel/Apple):  Intel i7
- MySQL Version: 5.6.20
- macOS Localization: English

**Description**
Copy As SQL INSERT (no auto_inc) still includes the auto_inc column

**Steps To Reproduce**
 I think its self explanatory 

**Expected Behaviour**

generated SQL should not include the auto_inc column

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** yes

**Related Issues**

**Additional Context**

I do not remember this functionality ever working for me, i thought it was under development until a colleague told me how much he likes it and it works for him.

**Comment by Jason-Morcos** [comment]
What is the auto_inc column that's being included? Is it _not_ called "id"? I just tested locally and it works for me with latest release and latest 3.1.0 beta both

**Comment by SBerkovic** [comment]
auto_inc column is called "id". 
heres an example of my table that does not work
`CREATE TABLE `test1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(55) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;`

**Comment by Jason-Morcos** [comment]
Hmmm odd. Does it work for you as well, @jamesstout @Kaspik?

@SBerkovic Could you paste the result of the copy no auto inc SQL (redacted as needed)? And which control/shortcut/button path are you taking _exactly_ to copy without auto inc? Perhaps just one button in one place is doing the wrong thing (and we may be using different buttons).

**Comment by jamesstout** [comment]
Are you on the query view or table content view?

**Comment by jamesstout** [comment]
Can't replicate with that table on either screen. It works (mariadb 10.5.8):

```sql
INSERT INTO `test1` (`type`)
VALUES
	('one'),
	('two');

```

**Comment by SBerkovic** [comment]
i am on content view
2 finger click to bring up the menu
result: `INSERT INTO `test1` (`id`, `type`)
VALUES
	(2, 'local2');
`
![image](https://user-images.githubusercontent.com/14169287/103782277-42c1fc80-5005-11eb-803a-7061669dfbc0.png)

**Comment by Jason-Morcos** [comment]
Hmmm so I'm doing the right click method and I definitely cannot reproduce. Not sure what's going on there. 
I used your exact create statement, MySQL 5.6, and macOS 11.1, right clicking, and cannot make it _not_ work.

**Comment by Jason-Morcos** [comment]
Can you share a screenshot of the "content" tab view for your demo table?

**Comment by SBerkovic** [comment]
here you go! it's really weird, maybe it has to do with my os version 10.14.6?
![image](https://user-images.githubusercontent.com/14169287/103834145-a9b8d300-5050-11eb-9697-6f2f051080f2.png)

**Comment by samuelbradshaw** [comment]
In case it's helpful, I wasn't able to reproduce this issue either. I'm on macOS 10.15 (Catalina). I tried on one of my tables, where the ID fields have various names (for example, "collectionId"). I also tested in a table with the CREATE TABLE syntax above, and tried adding rows by manually typing the IDs vs. letting it fill in the IDs automatically and it was the same – "Copy as SQL INSERT (no auto_inc)" works as I would expect... Tested in the released app and in 3.1.0 3011 beta. It must be something unique to your setup.

**Comment by Jason-Morcos** [comment]
> here you go! it's really weird, maybe it has to do with my os version 10.14.6?
> ![image](https://user-images.githubusercontent.com/14169287/103834145-a9b8d300-5050-11eb-9697-6f2f051080f2.png)

So sorry, I meant to ask for the "structure" tab - could you share that? Sorry for the inconvenience!

**Comment by SBerkovic** [comment]
> > here you go! it's really weird, maybe it has to do with my os version 10.14.6?
> > ![image](https://user-images.githubusercontent.com/14169287/103834145-a9b8d300-5050-11eb-9697-6f2f051080f2.png)
> 
> So sorry, I meant to ask for the "structure" tab - could you share that? Sorry for the inconvenience!

![image](https://user-images.githubusercontent.com/14169287/103853240-9f5ffe80-507b-11eb-9f47-a28e14ca105a.png)

**Comment by Jason-Morcos** [comment]
Hmm really cannot reproduce this. I am indeed using 11.1 and I guess it could be something specific to 10.14.6, but am not sure what that would be because the code looks to make sense.

**Comment by Kaspik** [comment]
I'm on 11.1, can't reproduce it either, but I'm not sure why this would be OS specific.

Just out of curiosity, did you try to remove Sequel Ace via AppCleaner (backup your favorites) and install completely fresh new?

**Comment by SBerkovic** [comment]
> I'm on 11.1, can't reproduce it either, but I'm not sure why this would be OS specific.
> 
> Just out of curiosity, did you try to remove Sequel Ace via AppCleaner (backup your favorites) and install completely fresh new?

That's exactly what I was thinking of doing next. Hopefully I'll have time over the weekend to try that.
Thanks

**Comment by dhcmega** [comment]
Hi!
Just in case, I have the same problem. Since I installed it a few month ago.
macOS, now on last version. I have also installed it on my notebook and I have the same problem. Tested it on different databases.
The copy feature copies the same a the "normal" copy.
Thanks a lot!!

**Comment by Jason-Morcos** [comment]
> Hi!
> Just in case, I have the same problem. Since I installed it a few month ago.
> macOS, now on last version. I have also installed it on my notebook and I have the same problem. Tested it on different databases. Tested on Mojave and Big Sur.
> The copy feature copies the same a the "normal" copy.
> Thanks a lot!!

Which button/path are you using to get to the copy without auto inc option? What's the info on your table/db connection (version/anything unique)? Any new tidbits of info that might help us find the issue? Nobody in the Ace team has been able to reproduce so far

**Comment by dhcmega** [comment]
Hi
I select a few row in "Content" section, then right click -> Copy as SQL INSERT (no auto_ic)
Connection over SSH, system timezone, none of the 3 checkboxes is checked
innodb table, just integer and string columns.

May I got it wrong? I believed that this will not copy the id column, right? 

Would it help if I record the screen and upload a video?

Thanks!!

**Comment by Jason-Morcos** [comment]
> Hi
> 
> I select a few row in "Content" section, then right click -> Copy as SQL INSERT (no auto_ic)
> 
> Connection over SSH, system timezone, none of the 3 checkboxes is checked
> 
> innodb table, just integer and string columns.
> 
> 
> 
> May I got it wrong? I believed that this will not copy the id column, right? 
> 
> 
> 
> Would it help if I record the screen and upload a video?
> 
> 
> 
> Thanks!!

Could definitely upload a video to make sure we're on the same page, however I think we understand the problem just haven't been able to reproduce it :/

**Comment by SBerkovic** [comment]
> I'm on 11.1, can't reproduce it either, but I'm not sure why this would be OS specific.
> 
> Just out of curiosity, did you try to remove Sequel Ace via AppCleaner (backup your favorites) and install completely fresh new?

I just removed both versions of Sequel Ace (beta and App Store) that i had installed, via AppCleaner. For good measure i also removed Sequel Pro. I am still having the issue though.

**Comment by dhcmega** [comment]
Hi @Jason-Morcos 
Here is my video, hope it helps.
Thanks

https://user-images.githubusercontent.com/6719578/104124768-4e793000-5331-11eb-92db-adae21f278af.mov

**Comment by Jason-Morcos** [comment]
@dhcmega thanks for the video!
One question - when you copy without auto inc, is some _other_ column (not I'd) excluded by chance?

**Comment by dhcmega** [comment]
@Jason-Morcos your are welcome.
It's the same. Both generate the same SQL code. Maybe they both point to the same method?
Thenks

**Comment by Jason-Morcos** [comment]
@dhcmega Yes, they are the same method behind the scenes, but with a little extra logic applied when the no auto-inc option is chosen. Like I said, it works 100% of the time for me so it's not some global issue with the method, it's something rare/specific. 

@jamesstout I see in SPCopyTable.m ~line 462 that we have a few CLS_LOG statements and safe fallthroughts. I assume something around there is failing. Do we only get those logs sent to crashlytics when it crashes? Any ideas?

**Comment by jamesstout** [comment]
> Do we only get those logs sent to crashlytics if an actual Exception is thrown?

Yes, or we manually record an error.

**Comment by jamesstout** [comment]
We've removed CLS logging. We would need to add a `MSACAnalytics trackEvent` to see what's going on now. @Kaspik you OK with us adding one?

**Comment by Kaspik** [comment]
Sure, add the event as "error" as we talked about and add details to params. :)

**Comment by SBerkovic** [comment]
so..... just saying 👋  and mentioning that the issue still exists 😉

**Comment by SBerkovic** [comment]
issue still exists in latest beta 3.3.0 (3025)

**Comment by Jason-Morcos** [comment]
Hi @SBerkovic,
Unfortunately, nobody else has been able to reproduce this issue. As it's not a crash, there's not a great way for us to get a trace of what's going on. It looks like somehow just two users are affected, you and @dhcmega. While we definitely want to fix this issue, it's highly unlikely someone on the core team will have the time, bandwidth, or chance to figure out what's going on here. I'd be super happy to review a PR aimed at fixing this bug and can try to point you in the right direction, but ultimately I think if you want this fixed you're going to have to try to compile locally and identify what's going on. The code is fairly straightforward so I'm really not sure what's going on and don't have a change I can think of that may fix the issue.

@jamesstout Any chance that logging you added in #838 recorded any info about this?

**Comment by SBerkovic** [comment]
@Jason-Morcos  @jamesstout 
I updated my OS to 11.2.3 Big Sur and updated xcode and xcode dev cli
and now it works fine 🥳  🤷
