### ISSUE TITLE
Query editor fonts not respecting Preferences if restoring a query favourite

### ISSUE THREAD

**Issue by victorjkhalaf** [Sequel-Ace/Sequel-Ace#753]
- Sequel Ace Version (including build number): 3.0.2 Build 3010
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.22
- macOS Localization: Eng

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
The query editor fonts are not respecting the preferences font when restoring a query favorite

**Steps To Reproduce**
1. In the Query tab, click Query Favorite and add a saved query. In the editor the font of the query will be different from your saved font from the Preferences.
2. Type anywhere within the query that was restored, you will then see the Preferences font applied

**Expected Behaviour**

It should look just as the preferences Query Editor font is set to

**Related Issues**

May be related to https://github.com/Sequel-Ace/Sequel-Ace/issues/487

**Additional Context**

You can see in the screenshot below how it behaves. I typed some different numbers in the date range to show how the font styles mix.
![image](https://user-images.githubusercontent.com/410897/103794408-ab63a600-5012-11eb-923a-7a70102970dd.png)

**Comment by Jason-Morcos** [comment]
Odd bug, unlikely related to #487, however. #487 is about the font selector being funky. This issue looks to be about us inserting the saved query as plain text and not attributing it

**Comment by jamesstout** [comment]
@victorjkhalaf  How's this look? (You can see I still have to use this [workaround](https://github.com/Sequel-Ace/Sequel-Ace/issues/487#issuecomment-726786504)), but the insert takes the query editor set font...

https://user-images.githubusercontent.com/1576190/103891169-531cc900-5124-11eb-8179-324accea7187.mp4

@Jason-Morcos 

> This issue looks to be about us inserting the saved query as plain text and not attributing it

Exactly that.

**Comment by victorjkhalaf** [comment]
> @victorjkhalaf How's this look? (You can see I still have to use this [workaround](https://github.com/Sequel-Ace/Sequel-Ace/issues/487#issuecomment-726786504)), but the insert takes the query editor set font...
> 

Yeah that looks right
And also thanks for taking point so quickly and addressing it!

**Comment by jamesstout** [comment]
I've also fixed the need for the workaround.
