### ISSUE TITLE
[Feature Request] - compatibility with mouse forward and back buttons

### ISSUE THREAD

**Issue by jasonwilliams** [Sequel-Ace/Sequel-Ace#758]
My mouse has 2 side buttons I use for forward and back. Some applications automatically work with this, like the web browser and other tools that support forward/back. This isn't something I set up, these applications just worked with it out the box.

Is it possible for sequel ace to map table history forward/back to these buttons? 
I don't know in-depth how the mapping would work so I can't provide much detail on that.

OS: MacOS 10.15.7

**Comment by Kaspik** [comment]
I think it would need proper support of swipe-back/forward on trackpad and magic mouse too, which means proper history controller handling.

**Comment by jamesstout** [comment]
What mouse is it? Any special drivers? Do you use BetterTouchTool?

**Comment by jasonwilliams** [comment]
@jamesstout I use the Logitech G603 i think the tech specs are here:
https://www.logitechg.com/en-gb/products/gaming-mice/g603-lightspeed-wireless-gaming-mouse.910-005102.html#product-tech-specs

**Comment by aramhovsepyan** [comment]
First of all, thanks to the developers and contributors.
The swiping (including proper history tracking) works for me on version 3.0.2 perfectly. On 3.0.3 it is gone however.

**Comment by Kaspik** [comment]
Weird, we never released 3.0.3... 😄

**Comment by aramhovsepyan** [comment]
Oh sorry I meant 3.1.0 (latest release).

**Comment by Jason-Morcos** [comment]
> First of all, thanks to the developers and contributors.
> 
> The swiping (including proper history tracking) works for me on version 3.0.2 perfectly. On 3.0.3 it is gone however.

Please open a new issue for this as it's not really related to the mouse buttons request.

**Comment by jasonwilliams** [comment]
@Jason-Morcos can we not close this issue? The bot is a bit overzealous

**Comment by BadApple9** [comment]
**A trick solution for Logitech mouse:**

If you're using Logitech mouse series, try to open 'Logi Options' APP and define your side buttons' function.

For Forward side button, add Keystroke assignment: Opt + Ctrl + →
For Back side button, add Keystroke assignment: Opt + Ctrl + ←
