### ISSUE TITLE
window stuck

### ISSUE THREAD

**Issue by MrLegeek** [Sequel-Ace/Sequel-Ace#761]
- macOS Version: 15.7
- Processor Type (Intel/Apple): mbp 2018 13` i5
- MySQL Version: 5.7.28

- desc:
-  When I copy and paste the SQL in the picture to the query interface page, it will be stuck, the mouse keeps spinning around for about tens of seconds before it is available

![image](https://user-images.githubusercontent.com/20502325/103983027-8ceedd80-51bf-11eb-9245-b6f1b619f631.png)

![image](https://user-images.githubusercontent.com/20502325/103982950-6630a700-51bf-11eb-92b1-33ac5be64525.png)

**Comment by Kaspik** [comment]
Related / Duplicate: https://github.com/Sequel-Ace/Sequel-Ace/issues/756

3.1.0 has more improvements on query paste, will be out soon.
