### ISSUE TITLE
[Feature Request] Sidebar for databases

### ISSUE THREAD

**Issue by jcbjoe** [Sequel-Ace/Sequel-Ace#767]
Hello Sequel Ace Team!

I was wondering if it would be possible to make the sidebar once connected to a server more like a tree system? So that it would first list databases then followed by a dropdown button which would then show you the table names. This would make it a lot easier to switch between databases quickly. 

I used to use Navicat but switched to Sequel Ace but they use the tree system and I found a screenshot of this online here:
![image](https://user-images.githubusercontent.com/3605644/104112290-bb1a0d80-52e4-11eb-9910-3ceb8c1a3e81.png)

Let me know what you think.

Thanks,
Joe!

**Comment by Jason-Morcos** [comment]
Interesting suggestion, I don't think we'll make a change like this right now but it's something we can consider when we redesign the sidebar!
For switching databases quickly, so you have the database selector in your toolbar? If not, you can customize the toolbar to include it and that should let you switch databases very quickly.
Thanks!
