### ISSUE TITLE
[Feature Request] Table edit query generation

### ISSUE THREAD

**Issue by jcbjoe** [Sequel-Ace/Sequel-Ace#768]
Hello Sequel Ace Team!

My idea was having a way to see the commands that are executed to edit a table. So for example when you add a new column to a table this would be outputted somewhere so that it could be copied. This would be useful because I use migrations a lot and I have a version of the databases locally then make the edits there and then write the migrations. If Sequel Ace could tell me the SQL commands that it generated to make my changes that would be a huge help.

I had two ideas for how this could work, however there is probably a better way:

1. Having a log page where you can just see the ran commands.
2. Now this is quite a big change so unlikely this will happen. Make it so the changes are not live and they only go live when a save button is pressed. This means that before you press the save button you will be able to see a page to see the commands that will be ran on the table.

Thanks,
Joe

**Comment by Jason-Morcos** [comment]
Have you tried looking at the console? The console shows every single query that Ace runs, including ALTER statements :)

**Comment by jcbjoe** [comment]
Oh! I cant believe I didn't see this! For some reason I though the console worked differently! Thanks!
