### ISSUE TITLE
Filter gets cleared up when changing table

### ISSUE THREAD

**Issue by maprangsoft** [Sequel-Ace/Sequel-Ace#770]
i uninstall application and reinstall but problem can't resolve.
video: https://www.loom.com/share/def5d95942f9445381de1015dafc406f

<img width="618" alt="Screen Shot 2564-01-10 at 20 54 16" src="https://user-images.githubusercontent.com/25447955/104124936-426b8d80-5386-11eb-9f03-3146c5d670bf.png">

**Comment by Kaspik** [comment]
I believe it's because the `column` you are filtering by is not available in the other table. If you would filter by `id` (which is in both tables), the filter would work as expected. Is it correct?

**Comment by maprangsoft** [comment]
table have match column filtering cleared as well but previous version v.3.0.2 no this problem. https://www.loom.com/share/aca9bc2b640743adb489685d0ff85362

**Comment by Jason-Morcos** [comment]
As I understand it, this used to work and now doesn't. I'm not sure why at all, but would classify that as a regression. Tagging accordingly.

**Comment by jamesstout** [comment]
Fixed by #783
