### ISSUE TITLE
MySQL said: Malformed packet

### ISSUE THREAD

**Issue by lrrrs** [Sequel-Ace/Sequel-Ace#776]
Following up on these two issues: https://github.com/Sequel-Ace/Sequel-Ace/issues/379 and https://github.com/Sequel-Ace/Sequel-Ace/issues/123. 
I still have the issue, that I can't view some tables when using the latest Sequel Ace version:

- Sequel Ace `3.1.0`
- MySQL Version `5.7.34`

- Error: MySQL said: Malformed packet. The connection then is lost until I restart `Sequel Ace`.

This is a table that causes the error:

```
CREATE TABLE `xyz` (
  `user_id` varchar(80) COLLATE utf8mb4_bin NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `code` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

Note that the same table can be accessed without error when using `MySQL 8.0`
It there some logfile that I could have a look at? To find out, what `Malformed packet` actually means?

**Comment by Kaspik** [comment]
Console _might_ give you more info, did you check that?

**Comment by jamesstout** [comment]
Is this still an issue? I can't replicate...

**Comment by lrrrs** [comment]
Me neither. Update `3.1.1` seems to fix it. Thanks.

**Comment by jamesstout** [comment]
Just checking the code, there was some legacy checks in the create table code re engine types. This was removed recently as it only applied to MySQL v4.

**Comment by lrrrs** [comment]
Sorry, have to re-open the issue. Still happening on an Apple Silicon Macbook for the same tables. The error message is a bit different though: `The table data couldn't be loaded. MySQL said: Unknown MySQL error`.

Nothing really useful in the logs. Is there something I can help with? Does Sequel Ace write its own log files somewhere?

**Comment by jamesstout** [comment]
> Does Sequel Ace write its own log files somewhere?

Not yet. @Kaspik is working on something.

Are you using the same server version? Is this in a popup alert?

I can only find one spot in the code that emits this error. In the table load values method, with no filter.

Alas I don't have Apple Silicon yet. Maybe @Kaspik could try it again?

**Comment by lrrrs** [comment]
MySQL: `5.7.32-35`, Sequel Ace: `3.1.1 Build 3016`, Big Sur `11.1`, Apple Silicon

Yes, it's a popover:

<img width="372" alt="Bildschirmfoto 2021-01-29 um 08 47 52" src="https://user-images.githubusercontent.com/671002/106246634-b32bfa00-620e-11eb-8cbb-13b606ebe84c.png">

**Comment by jamesstout** [comment]
> The table data couldn't be loaded. MySQL said: Unknown MySQL error

@lrrrs Could you please show us the output from:

```sql
SHOW VARIABLES LIKE 'lc%' 
```
Do you have access to the server? What OS/version etc?

If you have access can you please check the `lc_messages_dir` returned in the output from above. Probably `/usr/share/mysql/`

For me (Debian:buster-slim)

```bash
root@mysql5:/usr/share/mysql# ls
INSTALL-BINARY	 fill_help_tables.sql	      my-default.cnf		    polish
bulgarian	 french			      mysql-log-rotate		    portuguese
charsets	 german			      mysql-systemd-start	    romanian
czech		 greek			      mysql_security_commands.sql   russian
danish		 hungarian		      mysql_sys_schema.sql	    serbian
dictionary.txt	 innodb_memcached_config.sql  mysql_system_tables.sql	    slovak
docs		 install_rewriter.sql	      mysql_system_tables_data.sql  spanish
dutch		 italian		      mysql_test_data_timezone.sql  swedish
english		 japanese		      mysqld_multi.server	    ukrainian
errmsg-utf8.txt  korean			      norwegian			    uninstall_rewriter.sql
estonian	 magic			      norwegian-ny

```

Also the output from `mysqld --print-defaults` if you can please.

```bash
root@mysql5:/usr/share/mysql# mysqld --print-defaults
mysqld would have been started with the following arguments:
--skip-host-cache --skip-name-resolve --user=mysql --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306 --basedir=/usr --datadir=/var/lib/mysql --tmpdir=/tmp --lc-messages-dir=/usr/share/mysql --explicit_defaults_for_timestamp --symbolic-links=0
```

Again, looking for the `--lc-messages-dir` param

Thanks

**Comment by lrrrs** [comment]
Hey @jamesstout I can not reproduce it here anymore (Just updated to macOS 11.2).
Everything works like a charm… So whatever Apple did, something has fixed it? 🤷‍♂️
