### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by Linus-XZX** [Sequel-Ace/Sequel-Ace#780]
I'm from mainland China and I'd like to work on a Chinese translation for this project. I can hopefully focus on Simplified Chinese first and then turn to Traditional if I have enough spare time.

I will be new to Crowdin (and translation for a project as a whole, in fact) but after seeing this project's Crowdin page I think I generally know how it works.

My thanks in advance.

**Comment by Kaspik** [comment]
Hey! Thanks for your interest. Please sign up for Crowdin and join our group as a translator: https://crwd.in/sequel-ace

I'll upload Chinese strings in couple of hours. :)
