### ISSUE TITLE
Filters selected during query in content view are not persisted

### ISSUE THREAD

**Issue by isopropylcyanide** [Sequel-Ace/Sequel-Ace#784]
- Sequel Ace Version (including build number): 3.0.1/3008
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel i7
- MySQL Version: 5.7.32
- macOS Localization: Asia/En

**Description**
Filters selected during querying in content view are not persisted across tables

**Steps To Reproduce**
1. Select a table T1, go to content view, add a filter F1
![image](https://user-images.githubusercontent.com/12872673/104466285-1137cb00-55db-11eb-802f-ab293c7bf04e.png)

2. Select another table T2 and view its contents.

3. Come back to T1. The filters are reset. In the screenshot id is the default primary key, first column.
![image](https://user-images.githubusercontent.com/12872673/104466343-23196e00-55db-11eb-945d-22b658c65ce0.png)

**Expected Behaviour**
The filters should not be reset. Often, multiple filters are attached. Moving across tables should not clear them.

**Related Issues**
N/A

**Additional Context**
- You don't even have to select another filter on the second entity. Just navigating away from a filter and coming back will reset it.

**Comment by Jason-Morcos** [comment]
Duplicates #770
Will be fixed in next release (3.1.1)!
