### ISSUE TITLE
Show utc time when hovering over value that could be a timestamp

### ISSUE THREAD

**Issue by snapey** [Sequel-Ace/Sequel-Ace#793]
The popular Laravel framework stores queued jobs with execution timing stored as unsigned int values.

It would be very useful to be able to interpret a value that could be a unix timestamp (ie a value within range* of the current timestamp) as a UTC string on hover of those fields.

![Screenshot 2021-01-15 at 15 42 06](https://user-images.githubusercontent.com/328747/104747326-4877ba80-5748-11eb-8fdd-7aba4d8269b3.png)

range*: It's probable that most uses of timestamp is for things that are to be processed relatively near to the current time.  The tooltip could consider if the value is within +/- 31536000 (one year) of the current timestamp

**Comment by Jason-Morcos** [comment]
Interesting feature idea, I like it. Perhaps, however, there's even more to be done here - like some option on a right click dropdown to "edit as timestamp" or something which could pop up a view that parses the timestamp into local time and unix time and allows the user to modify the timestamp. Thanks for the idea!
