### ISSUE TITLE
>100% CPU usage when idle

### ISSUE THREAD

**Issue by scarlac** [Sequel-Ace/Sequel-Ace#795]
- Sequel Ace Version (including build number): 3.1.0
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.11
- macOS Localization: en_US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Unknown, hard to directly reproduce.

**Description**
When connected to one or more DBs (open in tabs) and having the app running in the background the CPU sometimes rises to >100% and stays there for a while. When I notice, I activate the app to see what's going on. Nothing visibly interesting going on - no custom queries, typically I will have the data browser activated but it won't have more than the default amount of rows (below 500).

**Steps To Reproduce**
1. Open Sequel Ace
2. Connect to one or more database
3. Leave app running in the background

**Expected Behaviour**

I expect CPU to be 0% or close to 0 when app is hidden.

**Related Issues**

Other related issues seem to be when user is editing or actively using the app. This is an issue when the user is not using the app at all.

**Additional Context**

No crash, no visible activity.

**Comment by ludengji** [comment]
Similar question... When app is running in the background, the cpu rises to 50%.  the fan is busy and noisy. 
Mac os version: 11.1
app version: 3.1.0 build 3013

**Comment by jamesstout** [comment]
Can't replicate. I installed [Coolant](https://coolantformac.com/), but no reports yet.

> a menu bar app that lets you know when an app is using an excessive amount of CPU or memory so you can close it and save battery power.

**Comment by shmert** [comment]
I'm also seeing a roughly 9-12% idle CPU usage from Sequel Ace when it is in the background doing nothing. Opening new tabs spikes the CPU, then it comes back to the same 9-12%. Tried closing all tabs, same thing with no visible window open. So I don't think it's specific to my database.

**Comment by Kaspik** [comment]
3.3.0 release has major change in tabs and windows - I wonder if you still see the spike when opening a new tab @shmert ?

**Comment by shmert** [comment]
@Kaspik I've got two active tabs open on 3.3.0 and CPU usage is 0.0%

Well done, folks!

**Comment by Kaspik** [comment]
@scarlac Let us know if it's still an issue for ya, closing now. :)

**Comment by rust17** [comment]
Similar question...
App Version: 3.3.3 
Mac os version: 11.4

When I have an active window in background
![image](https://user-images.githubusercontent.com/16575052/122902484-0ef34d00-d381-11eb-8444-4bc34b873255.png)
After close all windows
![image](https://user-images.githubusercontent.com/16575052/122902539-203c5980-d381-11eb-91bc-f095bac7d0a5.png)

**Comment by zacharyfreiberg** [comment]
> The same issue: in background CPU usage > 100% Sequel Ace Version 4.0.3, Build 20042; Mac OS: Ventura 13.0.1 Hard: M1 pro
> 
> this is a background usage, there are 3 tabs opened no queries in editors... <img alt="cpu_usage" width="735" src="https://user-images.githubusercontent.com/110167375/206441956-b6c494e9-048b-480a-8347-63a03aae5ecf.png">

I am having same issue on my Mac book pro 2019. My computer has crashed 6+ times in the last 2 weeks and I think this is the issue.

**Comment by aglukharev3c** [comment]
> I am having same issue on my Mac book pro 2019. My computer has crashed 6+ times in the last 2 weeks and I think this is the issue.
> 
> 2 Tabs open. No queries running.
> 
> Sequel Ace 4.0.3 Build 20042 macOS Ventura 13.0.1

When I install Sequel Ace from the App Store I face issues with high load. When I install using Brew it works perfect - no high load.

**Comment by zacharyfreiberg** [comment]
> When I install Sequel Ace from the App Store I face issues with high load. When I install using Brew it works perfect - no high load.

Thank you!

I'm due to be setting up a new computer next week, I will give this a try and keep my current configuration. It's a pain to do, but I just close my tabs when I don't need them!

**Comment by Kaspik** [comment]
Please leave this ticket closed and inactive, there is an open one so let's stick to that.
