### ISSUE TITLE
Table filters not persisted

### ISSUE THREAD

**Issue by danielsetreus** [Sequel-Ace/Sequel-Ace#799]
- Sequel Ace Version (including build number): 3.1.0 Build 3013
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel i7
- MySQL Version: 5.7
- macOS Localization: sv-se

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** yes, although not as much

**Description**
When adding a table content filter, and then switching between different tables or tabs (content, relation, query etc) the content filter is not persisted when returning to that view.

**Steps To Reproduce**
1. Select table A, enter a filter in the content pane (i.e. id = x)
2. Select table B
3. Go to Queries tab and run a sql query manually
4. Go back to table A, and the Content tab - the filter will be gone.

**Expected Behaviour**

I expect the filter to be persisted at least for as long as the connection is open , but it would be even better if filters are stored on a per saved server basis.

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
> **Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** yes, although not as much

Please explain "yes, although not as much"? We believe this issue was fixed in the 3.1.1 beta and will need to know exactly what issue remains to try to fix it further.

**Comment by Jason-Morcos** [comment]
Related: #770

**Comment by danielsetreus** [comment]
The issues I had seems to have been fixed with v 3.1.1. Thank you! Closing this issue.
