### ISSUE TITLE
Request to Volunteer

### ISSUE THREAD

**Issue by 9ae8sdf76** [Sequel-Ace/Sequel-Ace#8]
Thank you for taking the initiative with this project. Sequel Pro is a great software, and I'm glad that it'll live on. I do not have any experience with macOS desktop development, but I would still like to contribute. I am a "full-stack" web developer with skills in HTML/CSS design, Javascript, and PHP development. I also have moderate experience with devops. If you feel any of this can be helpful, I'd love to do my part (and maybe learn a thing or two). :)

**Comment by Jason-Morcos** [comment]
Hello! That would be wonderful! I will review any PRs to this repository so if you have changes you'd like to make, feel free to make a PR! Likely a list of issues will start to build under the issues tab and these would be great things to attempt to fix!
