### ISSUE TITLE
Filter bar should stay open when switching tables, closing app

### ISSUE THREAD

**Issue by christianjsanders** [Sequel-Ace/Sequel-Ace#80]
At the moment, we have to click the filter icon at the bottom of the screen on the content view to be able to quickly filter the data in our selected table. 

Would it be possible to have a setting whereby we can have this auto enabled instead of having to enable it via clicking on each table we look at. 

Thanks!

**Comment by anotherjames** [comment]
Looks like this might correspond to https://github.com/sequelpro/sequelpro/issues/3670 as well.

**Comment by gboudreau** [comment]
I've been using a custom-build Sequel Pro version with this enabled for years!
This indeed needs to be available in Sequel Ace. Should be easy enough to port.
My opinion on this is that the filter view should always be visible; don't think we need as setting for the user to decide if he wants it or not. Users who don't want to use it just won't, but its still there if they need to.

**Comment by gboudreau** [comment]
This is actually a bug; the Filter UI should stay visible, when switching tables. And closing the app and re-opening it should also remember the Filter UI visibility.
So if you prefer to always have the Filter UI visible, you toggle it on, and it should always stay on, until you disable it manually.
Will submit a PR to fix this soon.

**Comment by simplenotezy** [comment]
I still have this issue @Kaspik - I am in version 2.1.5 @gboudreau 

Should I open a new issue?
