### ISSUE TITLE
Feature Request: Filter content // Add dropdown

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#802]
I hope that filters will become more discoverable // see #801 

When the filter is set as a "=" filter, we can be more helpful.

<img width="721" alt="Screen Shot 2021-01-18 at 12 43 05" src="https://user-images.githubusercontent.com/382183/104948089-b9a6b000-598a-11eb-839d-cd33e0401258.png">

On the right, please add a dropdown icon (looks like "V").

Clicking the dropdown opens a popup immediately extending from the icon which shows a loading spinner and which can be closed using the ESC key or by moving focus off of that box (e.g. clicking the filter text box immediately right of the "=").

Then a query will run to fetch the dropdown options. There is a risk that running this query will cause a table lock and it will slow down other users on the database. That would be dangerous and unexpected. This is why it is hidden behind a button which must be clicked. Furthermore, I have researched ways to minimize risk of negative effects.* Here is the query to run:

```sql
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT /*+ MAX_EXECUTION_TIME(2000) */ DISTINCT @COLUMN
  FROM @TABLE_NAME
 LIMIT 1000;
COMMIT;
```

\* Documentation:

- Max execution time hint: https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-execution-time
- `ISOLATION LEVEL` notes: https://stackoverflow.com/a/918092/300224

---

Other notes

- An alternative is to detect if the query will be "fast" by checking if there is already an index on the table for that column. In this case, queries can run "for free" and it would be possible to immediately show a dropdown (and autocomplete while typing!) for the filter box. But this could cause user confusion when they see some filters work awesomely and some require pressing a button to get a dropdown. Such an advanced feature (and associated documentation) would be really cool and they are outside the scope of this issue.

**Comment by Jason-Morcos** [comment]
I'm not totally sold on this one. I tend to paste exactly what I'm looking for into the textbox to the right. If we need to allow text entry and/or dropdown entry, that adds some significant complexity. That's in addition to the already mentioned concerns about performance.
I like your point about checking if there's an index on that column (and potential checking the size of the table in general first), but don't really know if the benefits outweigh the potential dip in performance and complexity introduced by trying to allow manual data entry and dropdown selection. Nor do I believe that dropdown selection would be a positive user experience.
Imagine that you select an "id" column for a table with a 10 million rows. There's an index on ID, so we load the full list of IDs. How is that experience better than typing the ID? Perhaps there's some scale at which the two approaches are equivalent (maybe ~50 rows perhaps), but for some columns loading the list of values seems obnoxious. 
On the other hand, I can see how nice this would be for an ENUM type column with just a few values.


All in all, I strongly lead towards _not_ making this change. Unless this doesn't have _any_ negative impact on users whom like to copy/paste the exact value _nor_ on performance in general, I don't think the change is a net positive.
I can leave the issue open for a bit to see if others have thoughts, but this is one of those rare cases in which I likely would not support merging of a PR if someone else wrote the code, so I don't encourage anyone to go off and write this without further discussion :)

**Comment by fulldecent** [comment]
All fair. Here is a smaller feature that is easier and has no negative parts:

If the column type is ENUM and the filter is "=" or "≠" then there should not be a free form text box. Instead it should be a drop down with the ENUM options.

**Comment by Jason-Morcos** [comment]
> All fair. Here is a smaller feature that is easier and has no negative parts:
> 
> 
> 
> If the column type is ENUM and the filter is "=" or "≠" then there should not be a free form text box. Instead it should be a drop down with the ENUM options.

Definitely better, but likely difficult to implement due to the way the filtering system works. This is definitely better and I would take a look at a PR that did such, but wouldn't implement it myself. The juice still isn't worth the squeeze, in my opinion :)
