### ISSUE TITLE
Unable to compile project with 'Sequel Ace Local Testing' schema

### ISSUE THREAD

**Issue by gduh** [Sequel-Ace/Sequel-Ace#803]
I would like to offer my contribution for the project. 
First I clone the project 
I try to compile it (using `Sequel Ace Local Testing` schema) but I have the following error : "Sequel Ace" requires a provisioning profile...
I have a developer account for iOS, not for Mac, but I have already compiled an app just by specifying `Sign up to run localy`, so I tried to set this value for the project and all the targets but, at then end, I have the same issue !
Any help about the possibility to compile easily the project ?
Thx for your answer.

**Comment by Kaspik** [comment]
<img width="1444" alt="Screenshot 2021-01-18 at 19 28 24" src="https://user-images.githubusercontent.com/7204168/104951707-56853f80-59c3-11eb-9cc9-8e3c45078a97.png">

What do you have here, have you tried "Team: None"?

**Comment by Jason-Morcos** [comment]
Hey there, @gduh! Glad to hear you want to contribute!

That sounds like you're probably missing a profile locally. You'll have to make signing certificates for macOS in order to self-sign macOS applications.

Additionally, this thread may be helpful: https://developer.apple.com/forums/thread/107260

**Comment by gduh** [comment]
Yes, I tried with "Team:None"

**Comment by gduh** [comment]
If I try to use my account with `Sequel Ace` target, I have the following error : 

![xcode_signing](https://user-images.githubusercontent.com/15440947/104957425-6eae8c00-59ce-11eb-8cfe-e5e37ab509f0.png)

So, Must I change the bundle id too ?

**Comment by Jason-Morcos** [comment]
> If I try to use my account with `Sequel Ace` target, I have the following error :
> 
> ![xcode_signing](https://user-images.githubusercontent.com/15440947/104957425-6eae8c00-59ce-11eb-8cfe-e5e37ab509f0.png)
> 
> So, Must I change the bundle id too ?

Ahhh yes, I believe you must unfortunately

**Comment by gduh** [comment]
Ok, so, now I'm able te compile the project, it works fine.
But, when I will commit my changes, it will be with the modified bundle id, unless I think about changing the value before my commit !

**Comment by Kaspik** [comment]
Just don't commit the pbxproj file itself and it should be fine. We will need to come up with universal solution.

**Comment by gduh** [comment]
ok for the commit.
I start to make a first small change to gradually enter the project.

**Comment by stychos** [comment]
@Jason-Morcos not related, but maybe makes sense in this context － I would love to see configuration of Source/Frameworks/SPMySQLFramework.xcodeproj project an the top-level too, first time when I was unfamiliar with XCode and project structure I spent some good time to find that I need to change signing settings there to get it compiled :)
