### ISSUE TITLE
"Run current" button is broken

### ISSUE THREAD

**Issue by wangyi6854** [Sequel-Ace/Sequel-Ace#804]
- Sequel Ace Version (including build number): 3.1.0(build 3013)
- Sequel Ace Source (App Store/GitHub/Homebrew): homebrew
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): intel
- MySQL Version: 5.6.46
- macOS Localization: en-us

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes. (3.1.1 (3015) Beta 2)

**Description**
Any sql query can't run by clicking "run current" button.

**Steps To Reproduce**
1. input any sql query
2. click "run current" button

**Expected Behaviour**
The query should run when click run current button.

**Related Issues**
No

**Additional Context**
No

**Comment by stychos** [comment]
I noticed that "Run current" do not works with the queries which are not completed by the semicolon (the single one or the last in a series). Try to complete your query with the semicolon.

**Comment by wangyi6854** [comment]
Yes, I know it working by adding semicolon, but the button changed to "run previous". Or just change the button to "run all queries".

**Comment by stychos** [comment]
If you move cursor **into** the query, button'll show "Run Current". The little flaw is that it really needs close queries (with semicolon), but literally it doesn't mean that Sequel Ace do not runs current query.
Or I can't reproduce this, can you make some visual gif?

**Comment by cyber1111** [comment]
Same problem here 👍

**Comment by Firehed** [comment]
The keyboard shortcut for the same is also affected, so presumably it's something with the query parser/tokenizer.

This goes back to at least v3.0.2 (which I have installed) and I don't think it goes back further. Mine's the MAS version.
