### ISSUE TITLE
Crashes when query contains semicolon.

### ISSUE THREAD

**Issue by jachwe** [Sequel-Ace/Sequel-Ace#813]
- Sequel Ace Version (including build number): 3.1.0 Build 3013
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.3.13+maria~bionic (docker)
- macOS Localization: de_DE

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
yes

**Description**
Whenever i run multiple queries, seperated by semicolons - the app crashes without any warning.

**Steps To Reproduce**
1. Put a query into the query editor which contains a semicolon e.g. 'SELECT * FROM foo; SELECT * FROM bar'
2.Hit "Run all"

**Expected Behaviour**
The app should not crash or at least give a meaningful error message/crash report.

**Related Issues**
?

**Additional Context**

**Comment by Kaspik** [comment]
Hmm, I thought 3.1.1 fixed this. 🤔

**Comment by jachwe** [comment]
Hi @Kaspik , thanks for the swift response. 
I see now, that the latest version is not yet available via homebrew. Hence, i thought i was up-to-date.
Now i loaded the Appstore Version, and in fact the problem was resolved. Thank you and sorry for the confusion.

**Comment by Kaspik** [comment]
Yeah it was released yesterday so the cask wasn't updated yet probably as we are not maintaining it.
I just tried that and seems like it's not that hard... 😂 PR is open, we will see: https://github.com/Homebrew/homebrew-cask/pull/98471

**Comment by mfehr94** [comment]
It looks like I missed updating the caks. Sorry for that.

**Comment by Kaspik** [comment]
No worries, I thought it's automated based on the github release update.
