### ISSUE TITLE
Allow relations editing

### ISSUE THREAD

**Issue by abagmut** [Sequel-Ace/Sequel-Ace#814]
Now if you want to change the name of the relation or some of its property you have to remove existing one and create new from the scratch.
It would be really handy to have ability to just edit it.

**Comment by Jason-Morcos** [comment]
I believe MySQL only allows creating or dropping foreign keys, not editing them. Please correct me if I'm mistaken! https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html

If MySQL doesn't allow editing foreign keys, we probably won't either at this time (as really behind the scenes all we'd be doing is dropping the relation and creating the new one)

**Comment by samuelbradshaw** [comment]
MySQL 5.7 added the ability to rename an index, but not a constraint, unfortunately.

**Comment by abagmut** [comment]
@Jason-Morcos you are right you can't do it as one MySQL query
it would need to DROP foreign key and then create new
But it looks pretty handy for me to have this ability of inputting a new name and app do all necessary manipulations under the hood
