### ISSUE TITLE
App crashes when selecting table on CSV import

### ISSUE THREAD

**Issue by thaithcock** [Sequel-Ace/Sequel-Ace#817]
- Sequel Ace Version (including build number): 3.1.1 (3016)
- Sequel Ace Source (App Store/GitHub/Homebrew): App store
- macOS Version: 10.15.7 (Catalina)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.19
- macOS Localization: US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
I first tried updating, but am still getting the issue.

**Description**
When trying to import a csv, the app crashes after selecting a certain table in the table dropdown.

I have provided an equivalent schema with which I am able to reproduce the issue, including a second table to which it has a foreign key.

In my preliminary testing, it did *not* crash if TestTable2 does not have the foreign key.

Skimming the crash report, this seems like an important bit of information:
`Crashing on exception: *** -[__NSArrayM objectAtIndex:]: index 10 beyond bounds [0 .. 9]`

**Steps To Reproduce**
1. Create tables using the provided sql in [tables.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5850516/tables.txt)
2. Attempt to import using [import-to-test-table-2.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5850514/import-to-test-table-2.txt) (rename this to be .csv).
3. In the import dialog, switch the target table to TestTable2
4. It should crash

**Expected Behaviour**
It doesn't crash when selecting the table, and I can import my data.

**Related Issues**
Looks like there's a [few bugs related to importing](https://github.com/Sequel-Ace/Sequel-Ace/issues?q=is%3Aissue+crash+on+import), but I don't think any are running into this exact issue.

**Additional Context**
[crash_report.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5850506/crash_report.txt)
[tables.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5850516/tables.txt)
[import-to-test-table-2.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5850514/import-to-test-table-2.txt) (rename to .csv)

Let me know if you're unable to reproduce the issue, or if you need more information.

**Comment by samizreal** [comment]
I am also having the same issue, running the same build on an M1 Mac mini. I also get a similar line in my crash report: 
Application Specific Information:
Crashing on exception: *** -[__NSArrayM objectAtIndex:]: index 16 beyond bounds [0 .. 15]

I've attached the full crash report. 

(I'm not a developer, so apologies if I'm not following protocol correctly by commenting on this. It seems identical to the issue I'm having)
[sequel_ace_crash_report_01.21.21.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5852634/sequel_ace_crash_report_01.21.21.txt)

**Comment by Jason-Morcos** [comment]
Hmmm @thaithcock I cannot reproduce in App Store 3.1.1 release nor on latest main. @Kaspik Can you symbolicate one or both of these crash reports? I believe you have the DSYMs

<img width="698" alt="Screen Shot 2021-01-23 at 18 26 04" src="https://user-images.githubusercontent.com/10710367/105619558-a0e23400-5da8-11eb-8485-9b2266cc4df6.png">

**Comment by gduh** [comment]
I can reproduce in main branch ! Do you want me to try to fix it ?

**Comment by Kaspik** [comment]
@gduh Sure, do it if you are able to repro. I can't seem to find it even in Crashlytics.
