### ISSUE TITLE
Query History saving multiple queries separated by semicolons as separate entries

### ISSUE THREAD

**Issue by outie** [Sequel-Ace/Sequel-Ace#818]
- Sequel Ace Version (including build number): 3.1.1 Build 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 5.7.17
- macOS Localization: US English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
After updating to 3.1.1, Query History now saves multiple queries that were separated by semicolon as separate entries. Instead of showing multiple queries in the query window, there's only 1 line showing.

**Steps To Reproduce**
1. Run multiple queries in the query window, separated by semi colons and click Run All like this:
/* this is a test */
update mytable set name='hi';
select * from mytable;

2. Clear the query window
3. Call up Query History and select the last query of multiple queries but all the individual queries showed up as 1 entry. So the Query History shows up like this in the selection window:
select * from mytable;
update mytable set name='hi';
/* this is a test */

**Expected Behaviour**
Like prior to 3.1.1, the Query History should show multiple lines queries as 1 single entry and populate the Query Window as such.

**Comment by Jason-Morcos** [comment]
May I ask, what is wrong with the current behavior? Aren't all the queries being saved into query history? Realistically, they _are_ all separate queries, even if you chose to run them as all. I'm not sure why the behavior changed, but is the new behavior not more correct overall?

**Comment by outie** [comment]
After an import of records, I run multiple queries to clean up the data all at once (remove bad records cross referencing different tables) and also do a select at the end to see the results. The Query History has behaved correctly (to me) since Sequel Pro and just now changed to individual entries. 

I just think if I am running multiple queries in the query window it should be saved as such, as it has always been. Thanks.

**Comment by Jason-Morcos** [comment]
> After an import of records, I run multiple queries to clean up the data all at once (remove bad records cross referencing different tables) and also do a select at the end to see the results. The Query History has behaved correctly (to me) since Sequel Pro and just now changed to individual entries in 3.1.1.
> 
> I just think if I am running multiple queries in the query window it should be saved as such, as it has always been.
> 
> Another side effect is that with the multiple lines separated into individual history item, less queries could be saved as there’s a limit of history (200 items?)
> 
> Is this new behavior the effect of fixing the semi colon crash?
> 
> Thanks.

Any thoughts @Sequel-Ace/all?

I think it has to do with selection, but I don't think we intentionally changed the behavior. As a test, if you select all the queries (like text select) and run, are they saved as one entry or several? My hunch is if you select all the queries are run it may be saved as one entry but if you use run all it may be saved as several. Additionally, can you install 3.1.0 and verify that the behavior was indeed certainly changed (exact same steps results in different result kind of thing).

The semicolon crash fix could have caused this, but my gut says not. The semicolon crash really had to do with a < vs <= length comparison when running current query.

**Comment by jamesstout** [comment]
> I'm not sure why the behavior changed, but is the new behavior not more correct overall?

I changed it in #778 to fix duplicates in the history. I added a 'normalise query' method to separate out the queries by semi-colon, then only insert unique queries to history.

If this is not the correct way, then I can make it a pref?

**Comment by Jason-Morcos** [comment]
> > I'm not sure why the behavior changed, but is the new behavior not more correct overall?
> 
> 
> 
> I changed it in #778 to fix duplicates in the history. I added a 'normalise query' method to separate out the queries by semi-colon, then only insert unique queries to history.
> 
> 
> 
> If this is not the correct way, then I can make it a pref?
> 
> 

Ahhh
The new behavior feels more correct to me, however it may satisfy everyone if there indeed was a pref to choose whether or not to save them split up?

**Comment by outie** [comment]
I can't say it's correct or not, but I don't think anyone ever complained about multiple queries being saved as 1 history entry as an issue. Regardless, if you could either revert it or make it a pref I'd greatly appreciate it. Thank you!

**Comment by outie** [comment]
I'd like to further expand this issue. It seems like it's not just separating different history items by semi colons, I am using union and they all got separated into individual history items.

Steps to reproduce:
1.) Enter an union query:
select * from table1 where 1

union

select * from table2 where 1

union

select * from table3 where 1
2.) Run All
3.) Each query (in this case, each statement before union) is entered into history as 1 item. Then, there's a single history item of "union" word in it. So for this SINGLE query example above, it's entered into History as 4 items.

**Comment by Jason-Morcos** [comment]
@jamesstout Did you want to try to take a stab at this and https://github.com/Sequel-Ace/Sequel-Ace/issues/820? I know you mentioned you have familiarity with the new normalize query stuff.
I'll be on a business trip tomorrow through the end of the week and will be mostly out of pocket, but can take a look next weekend if needed

**Comment by jamesstout** [comment]
@Jason-Morcos yep, will take a look. 

1. Make a pref
2. handle > 1 line queries
3. From #820 - fix History Replaces Editor Content

@outie if you have a few more queries and what you expect in the history drop-down, I can write some unit tests.

**Comment by jamesstout** [comment]
@Sequel-Ace/all @outie Also a name for the preference? "Save query history by row ending in ;"? Or "Save queries to history line by line?"

**Comment by jamesstout** [comment]
> Another side effect is that with the multiple lines separated into individual history item, less queries could be saved as there’s a limit of history (200 items?)

Defaults to 20, but UI says max 100 (not enforced)

As this is no longer stored in a plist, and in a sqlite db, we could think of increasing the default max. The search field does only search the SPCustomQueryMaxHistoryItems from the default though. Could change that.

**Comment by jamesstout** [comment]
@outie @Jason-Morcos How's this?

https://user-images.githubusercontent.com/1576190/105635725-65766100-5e9f-11eb-815c-5ec469d0c04c.mp4

**Comment by Jason-Morcos** [comment]
Spacing looks a little funky on the checkbox for the pref, I would just make sure the auto layout values match those of the checkbox above it :)
Also, I feel that unions should never be split up, regardless of the pref. To me, a union is like one big query and doesn't make sense to break up into the individual selects which create it. Also, what about subqueries? I assume that nested subqueries don't get split into separate queries regardless of the pref as well?

Also, maybe instead of line by line we could say "individually"? Save queries to history individually (since a multi-line query would still be saved as one so long as it didn't have a semicolon somewhere in there, I presume).

**Comment by jamesstout** [comment]
> Spacing looks a little funky on the checkbox for the pref, I would just make sure the auto layout values match those of the checkbox above it :)

Yes, I've sorted.

> Also, maybe instead of line by line we could say "individually"?

I've already changed the pref to that.

Will have a look at unions/subqueries.....

**Comment by jamesstout** [comment]
> Spacing looks a little funky on the checkbox for the pref, I would just make sure the auto layout values match those of the checkbox above it :)

Any better?

![Screenshot 2021-01-25 at 2 35 44 AM](https://user-images.githubusercontent.com/1576190/105639991-5818a100-5eb6-11eb-8ace-f516508a47f7.png)

**Comment by Jason-Morcos** [comment]
> > Spacing looks a little funky on the checkbox for the pref, I would just make sure the auto layout values match those of the checkbox above it :)
> 
> 
> 
> Any better?
> 
> 
> 
> ![Screenshot 2021-01-25 at 2 35 44 AM](https://user-images.githubusercontent.com/1576190/105639991-5818a100-5eb6-11eb-8ace-f516508a47f7.png)
> 
> 

Looks great!!

**Comment by jamesstout** [comment]
> To me, a union is like one big query and doesn't make sense to break up into the individual selects which create it. Also, what about subqueries? I assume that nested subqueries don't get split into separate queries regardless of the pref as well?

Gave it a go ... it's a best guess without full SQL parsing:

https://github.com/Sequel-Ace/Sequel-Ace/pull/825/commits/a5d81c6132e137d0c1f856dd63737612eaf7eb12

**Comment by n9yty** [comment]
They are now going in history, and I have the option set to keep them all together (not breaking them apart), but they are going into the history in a random order, or at lesat the queries in the menu are showing up in weird order, makes it almost useless.

**Comment by Jason-Morcos** [comment]
> They are now going in history, and I have the option set to keep them all together (not breaking them apart), but they are going into the history in a random order, or at lesat the queries in the menu are showing up in weird order, makes it almost useless.

Is it fixed in the latest beta? If not, please open a new issue and we'll dig in again!

**Comment by n9yty** [comment]
The latest beta is problematic to run because none of my connections are seen by it, or any history/preferences/etc... I know, I'm being lazy, but also being honest. ;)  I will, though, try to set it up and see what I can find, it is the least I can do to try to give back a little.

**Comment by n9yty** [comment]
I did download 3.2.3 (3023) Beta 2 and it does seem, after some light testing, to be working properly. Can't wait for this to make release status, it will be so much nicer. :)
