### ISSUE TITLE
Toolbar is moved to the right site ...

### ISSUE THREAD

**Issue by matejsp** [Sequel-Ace/Sequel-Ace#829]
Toolbar is now moved to the right side of the screen (but not completely).
Also "select database" is moved to the right (instead of above Filter).

Very confusing UI.

- Sequel Ace Version (including build number): 3.1.1
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Big Sur
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.5.5
- macOS Localization: english

![image](https://user-images.githubusercontent.com/3091122/105715177-909f9580-5f1d-11eb-88e8-0b9dd314d376.png)

**Comment by Kaspik** [comment]
Duplicate of #562, #544, #534, #578, #595 and #618. Big Sur related.
