### ISSUE TITLE
Feature Request: Allow selecting which columns will be shown

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Sequel-Ace/Sequel-Ace#831]
I have multiple big tables where I have to scroll horizontally to find the data I need. It would be nice if I could select which columns are shown in the "Content" view. By default all columns should be selected (like they are now). This could be added to the bottom toolbar for instance. This could also be available in the "Structure" view.

**Comment by christatedavies** [comment]
This sounds like a standard `SELECT` query to me. 

Personally, I do find sometimes that I want to write a query to show 80% of the fields, which can be a burden when you have hundreds of fields to specify.

But the way I see it, this is a limitation in MySQL rather than something a GUI would do.

**Comment by GijsGoudzwaard** [comment]
It's true that this can be done using a standard `SELECT`. Though in my opinion it would be a simpler user operation to just use the mouse to select which columns you'd like to return. You could then also select all columns and deselect a couple if you'd want to select 80% of the fields. Making it less of a pain to select a handful of columns.

**Comment by GijsGoudzwaard** [comment]
@Jason-Morcos Can the stale label be removed before the issue is closed?
