### ISSUE TITLE
Feature Request: Allow searching the field columns in the "Structure" view

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Sequel-Ace/Sequel-Ace#832]
I have a lot of columns in some tables. It would be nice if I could filter the columns in the "Structure" view by searching for them so I can find if a table has a specific column. This is supported in Tableplus and would be nice if it was also supported on Sequal Ace.

**Comment by cappadaan** [comment]
+1, this is also my most wanted feature

**Comment by GijsGoudzwaard** [comment]
@Jason-Morcos Can the stale label be removed before the issue is closed?
