### ISSUE TITLE
Pasting into query editor causes an unexpected whitespace character to be added at the end

### ISSUE THREAD

**Issue by bbleakley** [Sequel-Ace/Sequel-Ace#834]
Version 3.1.1 build 3016
App store
Catalina 10.15.7
Apple
Mysql 5.7.32

**Description**
Pasting copied text into the query editor pastes the expected text plus a single whitespace character so pasting "hello world" appears as "hello world" for a brief moment before whitespace is appended to the end of it so it instead reads "hello world ". This is producing invalid SQL in several situations such as pasting the name of a table and then typing the field name: the expected behavior would be "accounts.id" but instead whitespace is added after pasting "accounts" resulting in "accounts .id"

**Comment by jamesstout** [comment]
OK, this is a hack I added to trigger syntax highlighting. I'll look at a fix asap.

**Comment by jamesstout** [comment]
Fixed.

**Comment by bbleakley** [comment]
Thanks! Love the app. Keep up the good work!
