### ISSUE TITLE
Query History is mangled

### ISSUE THREAD

**Issue by n9yty** [Sequel-Ace/Sequel-Ace#837]
- Sequel Ace Version (including build number): Version 3.1.1 (Build 3016)
- Sequel Ace Source (App Store/GitHub/Homebrew): AppStore
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: Not relevant
- macOS Localization: English

After asking about update notification/auto-update, I was pointed to the AppStore version, which sheepishly I didn't know existed. I downloaded and installed that and didn't notice right away, but some time after I went into the Query History and all the lines in there are scrambled so it is useless. The lines of the queries are all randomly(?) distributed and no longer together.

I looked at the sqlite3 queryHistory.db file and it is indeed messed up.

I doubt there is any recovery from this, just reporting it.

**Comment by Kaspik** [comment]
Should be fixed on master already - https://github.com/Sequel-Ace/Sequel-Ace/issues/818

**Comment by n9yty** [comment]
@Kaspik I do have a backup of the .plist from a previous version, but not the .db, is it possible to reimport the history from the plist format?

**Comment by n9yty** [comment]
I found it, I changed the plist to set SPMigratedQueriesFromPrefs to 0 and it reimported them.
