### ISSUE TITLE
SSH connection using private key (and optionally from the config file)

### ISSUE THREAD

**Issue by gduh** [Sequel-Ace/Sequel-Ace#839]
So far, I start by opening an SSH tunnel in a terminal and then I open a db connection in ACE.
To open the SSH connection I usually use a private key, not a login/password for security reason.

It seems ACE does not allow to open a connection using a private key, nor using an alias from the SSH config file. 
It would be great if at least, ACE could use a private key.

**Comment by Kaspik** [comment]
If this is supposed to be feature request - please read the docs, you can add your own user config - https://sequel-ace.com/get-started/

If this is supposed to be a bug report, please fill the form correctly.
