### ISSUE TITLE
Duplicate Table... name not editable

### ISSUE THREAD

**Issue by outie** [Sequel-Ace/Sequel-Ace#845]
- Sequel Ace Version (including build number): 3.1.1 Build 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Apple M1
- MySQL Version: 5.7.17
- macOS Localization: US English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
It's not possible to edit the name when you right click a table and select "Duplicate Table..."

**Steps To Reproduce**
1. Right click a table
2. Select Duplicate Table...
3. Under "Duplicate table 'table' to:, it defaults to 'table_copy' and you cannot modify this value

**Expected Behaviour**
In prior versions, you could edit that field to name the new table to a desired value.

**Related Issues**

**Additional Context**

**Comment by jamesstout** [comment]
Fixed for next release.
