### ISSUE TITLE
Toolbar UI issue with multiple monitors

### ISSUE THREAD

**Issue by FaimMedia** [Sequel-Ace/Sequel-Ace#847]
- Sequel Ace Version (including build number): 3.1.1 Build 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: 11.1 (20C69)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.?
- macOS Localization: nl-NL

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Not sure.

**Description**
The toolbar/UI is getting smaller than the window size, something even about half the size as it should be. Sometimes the database selection dropdown even gets hidden behind the arrows, if I click the arrows and choose 'Select database', nothing happens, making it impossible to select a database. I have to restart the app to get a new correctly shaped toolbar.

<img width="1792" alt="Schermafbeelding 2021-02-01 om 11 49 16" src="https://user-images.githubusercontent.com/11771199/106449576-63eeff00-6484-11eb-9f14-a82c672a0775.png">
<img width="1587" alt="Schermafbeelding 2021-02-01 om 11 49 24" src="https://user-images.githubusercontent.com/11771199/106449588-65202c00-6484-11eb-8889-057b354ef307.png">

**Steps To Reproduce**
I cannot directly reproduce this problem, but it seems to be related to moving the window between monitors with different resolutions and DPI settings, and also switching between Apple TV meeting mode and back to Retina.

**Expected Behaviour**
Toolbar width related to full window width.

**Comment by Jason-Morcos** [comment]
This should be fixed in the latest releases! Give a shout if not!
