### ISSUE TITLE
Query History is saving "lines" not "queries"

### ISSUE THREAD

**Issue by lphilps** [Sequel-Ace/Sequel-Ace#849]
Sequel Ace Version: 3.1.1 Build 3016
Sequel Ace Source: App Store
macOS Version: 10.15.7
Processor Type: Intel
MySQL Version: 8.0.20
macOS Localization: English
Is Issue Present in Latest Beta? Not according to the release notes associated with 3.2.0 Beta1

Description
When you run queries in the query editor that span "multiple lines" the Query History is saving every line in the multi-line query "as if" each line was a standlone query.

Steps To Reproduce
Clear the query history, then enter a simply query and run it.  Edit the query, adding newlines so the same query is split across multiple lines and run it.

Look at the query history and the number of entries for the 2nd query executed will be the number of lines in the multi-line query. Select part of that and only the "line selected" will be copied back to the query editor, not the entire query.

Related Issues
None that I know of

Additional Context
<img width="688" alt="Screen Shot 2021-02-01 at 8 38 07 AM" src="https://user-images.githubusercontent.com/922790/106467020-11084e00-646a-11eb-9b0e-6d418f89ae77.png">

**Comment by jamesstout** [comment]
Yes, sorry, this has been addressed in #825

**Comment by lphilps** [comment]
Great news.  My apologies.  I looked but miss that issue.
