### ISSUE TITLE
Add in support for "Check for Updates"

### ISSUE THREAD

**Issue by adamwinn** [Sequel-Ace/Sequel-Ace#85]
Missing is the action for "Check for Updates" with the Sparkle framework.  Currently, we have to visit github to see if a new version is available.

**Comment by Jason-Morcos** [comment]
Sequel Ace is designed to be distributed via the App Store. However, if someone wants to PR this feature (if it can be turned off for versions downloaded from the App Store and can be backed by GitHub releases or automation to release updates), I'd be happy to review the PR.

**Comment by Kaspik** [comment]
I'll close this PR.

For now, we are trying to make the app stable, migrate to new API after couple of years without any update, and focusing on Mac AppStore compatibility - there is no plan to build something like this in foreseeable future.

It doesn't mean someone can't create a PR and slowly build a support, it's just not necessary to keep this open. :)

Btw: We are trying to release once per 2 weeks, and you can setup IFTTT for new release (for example https://rschu.me/github-release-notification-via-ifttt-2346f3a71f3b) for yourself. :)
