### ISSUE TITLE
Quoting "shortcut" in Query Editor does not work as intended

### ISSUE THREAD

**Issue by rickthemad** [Sequel-Ace/Sequel-Ace#850]
- Sequel Ace Version (including build number): 3.1.1 Build 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Big Sur 11.1
- Processor Type (Intel/Apple): 1,4 GHz Intel Core i5 quad-core
- MySQL Version: 5.7.27
- macOS Localization: it-IT (with italian keyboard)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Was not able to try, the connections do not work for some reason so I cannot open the Query Editor.

**Description**
The Query Editor's "shortcut" to enclose words or text portions in single or double quotes is not working anymore. If you try to use it by double-clicking on some text then pressing one of the quotes button, the selected text will be added at the end of the entire SQL text with the quotes instead of being replaced in the correct position.

**Steps To Reproduce**
1. Double click on a portion of text on the query editor
2. Press the double or single quote button on the keyboard

**Expected Behaviour**
The portion of text enclosed in double quotes in the same position as the selection.

**Related Issues**
Did not find any.

**Additional Context**
![Schermata 2021-02-02 alle 09 21 09](https://user-images.githubusercontent.com/78407479/106571896-06b48580-6538-11eb-9e83-463dbff04901.png)
I think the issue started to show up in the 3.1.0 (3013) release version.

**Comment by jamesstout** [comment]
I've noticed this myself and was on my TODO list.

Very strange, the "wrap" code has not changed for years.

Taking a look.

**Comment by jamesstout** [comment]
Seems like it has changed, but I can't see where in the commit history.

I have a fix.

**Comment by jamesstout** [comment]
PR submitted: #854
