### ISSUE TITLE
Indenting issue in query editor

### ISSUE THREAD

**Issue by Maikel-Koek** [Sequel-Ace/Sequel-Ace#853]
- Sequel Ace Version (including build number): Version 3.1.1, build 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): Github
- macOS Version: Big Sur 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.32
- macOS Localization: Dutch

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, confirmed, in https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.2.0-3017

**Description**
Existing indenting is not honored when moving to a newline. In fact, the indenting that should be added at my new line (tabs or spaces), is added to the end of my query in the editor.

For example, after hitting enter at the end of `my_column`, results in the following (`¶` added for readability):
```
select¶
	my_column,¶
¶
from my_table	¶
```

While I would expect it would result in this:
```
select¶
	my_column,¶
	¶
from my_table¶
```

**Steps To Reproduce**
1. Enter query editor and type something indented (tabs or spaces)
2. Hit enter; new line starts without indenting.

**Expected Behaviour**
I would expect to automatically have my new line indented, if the previous line is.

**Comment by jamesstout** [comment]
Do you have "Indent new lines" in prefs set to on?

![Screenshot 2021-02-02 at 10 57 55 PM](https://user-images.githubusercontent.com/1576190/106618423-664b7900-65aa-11eb-89c3-36c033cb5349.png)

**Comment by Maikel-Koek** [comment]
@jamesstout Yes, I do!
All of my settings, to be complete:

![Schermafbeelding 2021-02-02 om 16 09 33](https://user-images.githubusercontent.com/6301809/106619668-1dc39980-6571-11eb-81bc-701f09119661.png)

**Comment by jamesstout** [comment]
Hmmm ... very strange then. .... i'll continue to investigate.

**Comment by jamesstout** [comment]
ok it works if you have no text at all after the indented line you are typing, but if there is any text at all anywhere else in the window, the indentation is added after that (you noticed this).

Trying to figure out how to insert at the right spot...

**Comment by jamesstout** [comment]
PR submitted: #855

**Comment by Maikel-Koek** [comment]
@jamesstout Possibly related to this; when I don't have any text after the line I'm typing, indenting does work as you stated, but then indenting doesn't seem to align, see screenshot. I'm using tabs.

![Schermafbeelding 2021-02-03 om 11 14 13](https://user-images.githubusercontent.com/6301809/106732450-00460c80-6611-11eb-89d9-3954cbd7bbde.png)

This is a copy of the exact query in that screenshot:

```
select
	entity_id,
	created_at,
	state
```

Didn't change any settings since my comment yesterday.

Any idea what could cause this?

Thanks!

**Comment by Maikel-Koek** [comment]
Could also be related;
When pasting text at the end of my query, a space (` `) is automatically inserted after my pasted text.
When pasting somewhere else, a space is also added **to the end of my query**.
Both cases are confusing and not really desirable.
