### ISSUE TITLE
Cannot set path exporting SQL

### ISSUE THREAD

**Issue by kossa** [Sequel-Ace/Sequel-Ace#856]
- Sequel Ace Version (including build number): 3.1.1
- Sequel Ace Source (App Store/GitHub/Homebrew): Homebrew
- macOS Version: Catalina
- Processor Type (Intel/Apple):Intel
- MySQL Version: 8.0.22

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Cannot export DB 

**Steps To Reproduce**
1. Open DB
2. Select tables
3. Export

I also set Full disk access in security

![image](https://user-images.githubusercontent.com/1175584/106644682-b109c880-658b-11eb-8eaa-ab092f675f03.png)

![image](https://user-images.githubusercontent.com/1175584/106644499-7acc4900-658b-11eb-9afc-8b8c6d19be7a.png)

**Comment by Jason-Morcos** [comment]
You have to hit the "change" button and can't just type a path, due to the sandbox. Does the change button work?

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all we likely need to change the export file workflow
