### ISSUE TITLE
Freeze when window maximized or restored 

### ISSUE THREAD

**Issue by umutkirgoz** [Sequel-Ace/Sequel-Ace#857]
Sequel-Ace freeze a while when window is maximized or restored to previous size.

- Sequel Ace Version v3.1.1 (Build 3016)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: macOs Catalina (v10.15.7)
- Processor Type (Intel/Apple): Intel Core i7
- MySQL Version:
- macOS Localization: EN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Main window freezes when window maximized (switched to full screen) or restored to previous size. Application freezes about 10 seconds and window switched to full screen. Same behaviour occurs when it is restored to previous size...

**Steps To Reproduce**
1. Open the Sequel-Ace
2. Maximize it to full screen

**Expected Behaviour**
There should be no delay in maximize/minimize window actions

**Comment by jamesstout** [comment]
Strange. If you click somewhere else on the screen (not within Sequel Ace), does it maximise?

**Comment by jamesstout** [comment]
Works OK on 10.13 and 10.12. I don't have 10.14 to test. Will try Big Sur next.

**Comment by jamesstout** [comment]
OK on 10.15.0 also.

**Comment by jamesstout** [comment]
OK on 10.15.3

**Comment by jamesstout** [comment]
OK on 10.15.5

**Comment by jamesstout** [comment]
hmmm, and a fresh install of 10.15.7 is OK too.

**Comment by jamesstout** [comment]
Ignore the comments above. re-testing

**Comment by jamesstout** [comment]
**UPDATE:**
10.12 - OK
10.13 - OK
10.15.3 - Not OK 
10.15.7 - Not OK

Will try Big Sur next.

Also: Looking for a 10.14 VM....

**Comment by jamesstout** [comment]
10.14.4 - Not OK
11.2.1 - OK

**Comment by jamesstout** [comment]
11.2.1 (20D74) - OK.

**Comment by FaimMedia** [comment]
Not sure if it's related, but after I switched to another app, cannot focus Sequel Ace by clicking on the window (records or tables) except for the top toolbar.

**Comment by sumairz** [comment]
Mac OS Mojave

Sequel Ace version 3.2.2 build 3021

When sequel ace is opened but not used for long time and when clicked on icon it opened another instance of the app with connection screen

**Comment by Jason-Morcos** [comment]
> Mac OS Mojave
> 
> Sequel Ace version 3.2.2 build 3021
> 
> When sequel ace is opened but not used for long time and when clicked on icon it opened another instance of the app with connection screen

This was fixed in 3.2.3 and is unrelated to this current issue thread. Please update to 3.2.3 and let us know if it persists (in a new issue, not by commenting on this issue). :)

**Comment by Kaspik** [comment]
Is this still an issue on 3.3.0?

**Comment by umutkirgoz** [comment]
I just recheck the issue, I think it's fixed in 3.3.0. 
tHanks to all
