### ISSUE TITLE
MySQL 8.0 not supported 

### ISSUE THREAD

**Issue by amebfederal** [Sequel-Ace/Sequel-Ace#86]
I am trying to connect to Digital Ocean Managed Database (Mysql 8.0) but it's not supported yet.

Unable to connect to host **********.db.ondigitalocean.com, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: SSL connection error: unknown error number

Same connection works fine on MySQL workbench. 

Is this feature coming soon ?

**Comment by Jason-Morcos** [comment]
Duplicates #32 

We are supporting mySQL 8 in 2.1.0 which is currently in beta!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.1.0-beta3
