### ISSUE TITLE
Ability to sort by columns in the structure table 

### ISSUE THREAD

**Issue by Kwadz** [Sequel-Ace/Sequel-Ace#863]
We can sort data by clicking on a column in the content table. It would be nice to have the same ability in the structure table.

![image](https://user-images.githubusercontent.com/1472599/107241593-6c6aab00-6a2b-11eb-9f3f-429d7174c5a4.png)

**Comment by Jason-Morcos** [comment]
Hmm I'm not sure I agree with this. MySQL is structured, there is an actual order to the individual columns in the table. It seems strange to allow you to sort the columns some other way.

**Comment by Kwadz** [comment]
It's a time saver when you have a big list. About the actual order we just need to add an index column to preserve it.
