### ISSUE TITLE
SQL_MODE='NO_AUTO_VALUE_ON_ZERO' lost when importing tables with triggers

### ISSUE THREAD

**Issue by doublesharp** [Sequel-Ace/Sequel-Ace#865]
- Sequel Ace Version (including build number): 3.1.0 build 3013
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.3.27
- macOS Localization: EN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, this issue also exists in the beta.

**Description**
When creating a database export that includes tables with triggers before tables with a `0` value on an autoincrement column the `SQL_MODE='NO_AUTO_VALUE_ON_ZERO'` setting is lost resulting in  an error of `Duplicate entry '1' for key 'PRIMARY'`. If the auto increment value is included on the table the duplicate entry error is avoided but the row with an ID of `0` is set to whatever the next autonumber value is.

This error comes up for me using a Magento database - it uses "0" for the default `customer_group`, `store`, `store_group`, and `store_website` tables and has triggers on some of the `catalog_*` tables that come first, alphabetically, in the export file. 

**Steps To Reproduce**
1. Create a table named `table_a`
2. Add a trigger to `table_a`
3. Create a table named `table_b` with an autonumber primary key
4. Create two entries in `table_b` with IDs for 0 and 1
5. Create an export of the database and do not include auto increment value in the table definition.
6. Try to import the export file.

SQL to reproduce
```
DROP TABLE IF EXISTS `table_a`;
DROP TABLE IF EXISTS `table_b`;

CREATE TABLE `table_a` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `table_a` (`id`)
VALUES
	(1);

DELIMITER ;;
CREATE TRIGGER `trg_table_a_after_insert` AFTER INSERT ON `table_a` FOR EACH ROW BEGIN
END;;
DELIMITER ; 

CREATE TABLE `table_b` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET SESSION SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

INSERT INTO `table_b` (`id`)
VALUES
	(0),
	(1),
	(2);
```
Exporting creates the following SQL file:
[example.sql.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5953898/example.sql.txt)
<img width="751" alt="Screen Shot 2021-02-09 at 11 59 38 AM" src="https://user-images.githubusercontent.com/571472/107421216-8b6e4900-6ace-11eb-8b42-505aa65d31dd.png">

**Expected Behaviour**
Expected behavior is for `SQL_MODE='NO_AUTO_VALUE_ON_ZERO'` to remain set throughout the export file and not conflict on the primary key.

**Related Issues**
There are no open or closed issues containing `NO_AUTO_VALUE_ON_ZERO`

**Additional Context**
Example export file created from a Magento database:
[magento_2021-02-09.sql.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/5953739/magento_2021-02-09.sql.txt)

On line 55 is `/*!50003 SET SESSION SQL_MODE="NO_AUTO_VALUE_ON_ZERO" */;;` but on line 60 it is set to `/*!50003 SET SESSION SQL_MODE=@OLD_SQL_MODE */;` which seems to make it fall back to `/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;` on line 20 resulting in tables further down not using `0` for the auto value and instead going to the next auto increment value.

When trying to use this export to initialize a docker database instance the following error is reporting. Removing the `SET SESSION SQL_MODE=@OLD_SQL_MODE` allows the import to complete.
```
magento_db_1     | 2021-02-09 19:24:16+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/magento_2021-02-09.sql
magento_db_1     | ERROR 1062 (23000) at line 77: Duplicate entry '1' for key 'PRIMARY'
```

A workaround is to set the `--sql_mode` parameter in the `docker-compose` command so that when the SQL_MODE is reset in the SQL file it will still be set correctly.

**Comment by jamesstout** [comment]
Interesting note in the [docs](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_auto_value_on_zero):

> For example, if you dump the table with `mysqldump` and then reload it, MySQL normally generates new sequence numbers when it encounters the 0 values, resulting in a table with contents different from the one that was dumped. Enabling `NO_AUTO_VALUE_ON_ZERO` before reloading the dump file solves this problem. For this reason, `mysqldump` automatically includes in its output a statement that enables `NO_AUTO_VALUE_ON_ZERO`.

In our export code there is this TODO:
```objc
// TODO: SQL_MODE
// * There is no point in writing out that the file should use a specific SQL mode when we don't even know which one was active during export.
// * Triggers, procs/funcs have their own SQL_MODE which is still set/reset below, though.
//
// But an unknown SQL_MODE (!sqlModeIsValid) could perhaps still affect how MySQL returns the "SHOW CREATE…"
// data for those objects (like it does for "SHOW CREATE TABLE") possibly rendering them invalid (need to check that),
// so it may be better to flat out refuse to export schema object DDL if we don't have a valid sql_mode.

[metaString appendString:@"/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n"];
[metaString appendString:@"/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;\n\n\n"];
```

However, just above that, we set `SQL_MODE` to `''` :
```objc
//set sql mode for export
if([@"" isEqualToString:oldSqlMode]) {
    // the current sql_mode is already the one we want (empty string), no need to change+revert it
    SPLog(@"oldSqlMode: %@", oldSqlMode);
    oldSqlMode = nil;
    sqlModeIsValid = YES;
}
else {
    [connection queryString:@"SET SQL_MODE=''"]; //mysqldump uses a conditional comment for 40100 here, but we want to see the error, since it can't simply be ignored (also ANSI mode is supported before 4.1)
    if (![connection queryErrored]) {
        sqlModeIsValid = YES;
    }
    else {
        [errors appendFormat:@"%@ (%@)\n", NSLocalizedString(@"The server's SQL_MODE could not be changed to one suitable for export. The export may be missing important details or may not be importable at all!", @"sql export : 'set @@sql_mode' query failed message"), [connection lastErrorMessage]];
        [metaString appendFormat:@"# SET SQL_MODE Error: %@\n\n\n", [connection lastErrorMessage]];
        //if we couldn't change it, we don't need to restore it either
        oldSqlMode = nil;
    }
}
```

After the trigger creation code is generated, (as @doublesharp mentioned), we reset the `SQL_MODE` to `@OLD_SQL_MODE`, which does not contain `NO_AUTO_VALUE_ON_ZERO`, so the inserts to `table_b` fail.

I think the fix is this:

```objc
// so to address issue #865, where creating a table with a trigger discards NO_AUTO_VALUE_ON_ZERO,
// by setting SESSION SQL_MODE to the mode used when the trigger was created then resetting SQL_MODE to @OLD_SQL_MODE
// we add NO_AUTO_VALUE_ON_ZERO to @OLD_SQL_MODE here, for the export file to properly work.
[metaString appendString:@"/*!40101 SET @OLD_SQL_MODE='NO_AUTO_VALUE_ON_ZERO', SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n"];
```

**Comment by jamesstout** [comment]
PR #866 submitted
