### ISSUE TITLE
Allow User to Manage SSH known_hosts

### ISSUE THREAD

**Issue by sjlehn** [Sequel-Ace/Sequel-Ace#867]
Since Sequel Ace is managing its own known_hosts file, it should really provide a way to provide a way to manage/remove entries. 

When the connection fails, there is a mess of debugging output in the warning dialog that pops up, and you have to scroll past a lot of not-so-relevant information in order to get to the meat of the message, which is the usual SSH panic over a changed host key. 

I would suggest that (a) SSH debug output be hidden, either not displayed in this case or at least put behind a "Show More" prompt and (b) create a concise version of the host key changed warning that is suitable for presentation in a dialog box (rather than a terminal window), with either clear instructions on how to resolve the error (editing ~/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict), and possibly (c) giving the user options to replace the key or abort the connection.

It might also be beneficial to have an additional section in the preferences window that allows the user to view and and remove existing known_hosts.

**Comment by effata** [comment]
What's especially annoying about this is that even if I specify a custom SSH Config, `UserKnownHostsFile` is not respected.

**Comment by Jason-Morcos** [comment]
> What's especially annoying about this is that even if I specify a custom SSH Config, `UserKnownHostsFile` is not respected.

That's a good point. @Sequel-Ace/all does anyone have thoughts on a good way of handling this? We need to specify our known hosts file when a user doesn't specify one, but do want to allow users to choose their own known hosts. Perhaps we add a pref to say "use Sequel Ace's built-in Known Hosts system" and then if users opt out of that they _must_ specify a known hosts file in their SSH config (and grant ace access to that file). Can we be smarter about it somehow?

**Comment by Jason-Morcos** [comment]
Classifying as a bug as a user cannot choose their own UserKnownHostsFile even via their custom SSH config.


I guess a simple way we could do this is move our specification of the known hosts file into our built-in SSH config, and then require **all** users who use their own custom SSH config to also use their own known_hosts, but that transition seems like it may be confusing for existing users.

**Comment by effata** [comment]
As a user, I would expect specifying a custom SSH config to behave the same as in my shell. As in there are default values, and anything I specify is an override. For my personal use case, I want to be able to specify a custom known hosts file for specific hosts only, so I'm fine with using defaults otherwise.

**Comment by Jason-Morcos** [comment]
> As a user, I would expect specifying a custom SSH config to behave the same as in my shell. As in there are default values, and anything I specify is an override. For my personal use case, I want to be able to specify a custom known hosts file for specific hosts only, so I'm fine with using defaults otherwise.

Yeah I'm absolutely with you on that, I'm just trying to think about how to actually _do_ it. Does that mean we're have to parse the user's entire ssh config and try to determine if we need to specify a hosts file? Haven't thought of a good way to accomplish that.

**Comment by Jason-Morcos** [comment]
Note: Related to #261

**Comment by jamesstout** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/tree/custom-known-hosts may solve this.
