### ISSUE TITLE
Search Bar Missing

### ISSUE THREAD

**Issue by amebfederal** [Sequel-Ace/Sequel-Ace#87]
In the old Sequel Pro, there is an easy way to search data on the top bar (next to table name)

Is there a plan to bring it back ?

**Comment by Jason-Morcos** [comment]
Are you talking about the filter bar?
The filter bar can be shown with the little funnel icon on the bottom of the application, or by pressing "Command+F".

Does this solve this issue?

**Comment by amebfederal** [comment]
Oh Yes. Thanks for that. That solved my issue :)
