### ISSUE TITLE
Displaying language - some parts in English some parts in Spanish 

### ISSUE THREAD

**Issue by ecubero** [Sequel-Ace/Sequel-Ace#872]
- Sequel Ace Version (including build number): 3.1.1 build 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.12
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.5.5-10-1.26
- macOS Localization: German

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Issue persists using the latest version in the App Store (3.1.1), the latest one in production branch (3.2.0-3019) and the beta branch (3.2.0-3018)

**Description**
Computer language is German. When I open the application the menu bar is in English. Where I select the database is also in English and where it says structure, content, relations is in Spanish. If I want to get to the app's preferences all the main options on the top (General, Tables, etc) are in Spanish.

**Steps To Reproduce**
1. Open application
2. In the main screen, where you enter the information to connect to a Database is in English but the menu on top (Structure, Content, Relations, etc) is in Spanish.

**Expected Behaviour**
Every option and label on the program should be in one language.

**Additional Context**
This is the way it looks when I open the application

<img width="1280" alt="Bildschirmfoto 2021-02-12 um 8 35 29 PM" src="https://user-images.githubusercontent.com/68167248/107839496-dd82c900-6d71-11eb-84c0-128c0050c7dc.png">

**Comment by jamesstout** [comment]
could you please show us the output from:

`defaults read -g AppleLanguages`

**Comment by ecubero** [comment]
> could you please show us the output from:
> 
> `defaults read -g AppleLanguages`

Hi @jamesstout, this is the output for the apple languages command:

<img width="569" alt="Bildschirmfoto 2021-02-13 um 9 32 55 AM" src="https://user-images.githubusercontent.com/68167248/107854033-e493f080-6dde-11eb-958b-ec13a2cc6e45.png">

Thanks

**Comment by Jason-Morcos** [comment]
I think this is just because the app isn't _fully_ localized yet. We're in the process of adding support for languages other than English, but not everything has been updated to support this yet. Is this correct, @Kaspik?

**Comment by Kaspik** [comment]
Yes, ES has translated 68% strings, and we are still not translating the xibs (UI) yet.

**Comment by Kaspik** [comment]
> > could you please show us the output from:
> > `defaults read -g AppleLanguages`
> 
> Hi @jamesstout, this is the output for the apple languages command:
> 
> <img alt="Bildschirmfoto 2021-02-13 um 9 32 55 AM" width="569" src="https://user-images.githubusercontent.com/68167248/107854033-e493f080-6dde-11eb-958b-ec13a2cc6e45.png">
> 
> Thanks

Your second language is `es` which means german fallbacks to it. We don't have German translations, if you wanna join us and start translating, we can add it. :)
