### ISSUE TITLE
Reset Auto-increment for all rows, regardless of size

### ISSUE THREAD

**Issue by 9ae8sdf76** [Sequel-Ace/Sequel-Ace#874]
I don't know the threshold that Sequel Ace uses, but if a large enough number of rows are being deleted from a table you are given a checkbox on whether or not you want to reset the auto increment id. This request is to ask that regardless of the number of rows being deleted that the auto increment checkbox always be available. Thank you.

**Comment by Jason-Morcos** [comment]
That seems kinda annoying for just normal deletes of one or two rows to see a pop up alert at all. Do you have any ideas about how to make this not annoying for small deletes?
Perhaps instead we make there a second right click option to delete and reset auto-increment?

Also, I'm not looking at the code right now, but is it possible the pop up is related to whether or not you're deleting the last row in the table (and therefore freed up at least one id at the end), and is not dependent on the number of rows selected?

**Comment by 9ae8sdf76** [comment]
> That seems kinda annoying for just normal deletes of one or two rows to see a pop up alert at all.

I wouldn't default to there not being any alert when deleting any number of rows. The last thing anybody wants is to be connected to any database and accidentally wipe a table. I'd vote to keep the dialog.

> Perhaps instead we make there a second right click option to delete and reset auto-increment?

For me this would be acceptable.

> is it possible the pop up is related to whether or not you're deleting the last row in the table

No, unfortunately that's not the case. It looks like you have to [delete more than 50 rows](https://github.com/Sequel-Ace/Sequel-Ace/blob/2e642c83e6d333d35e009bdd8e4353344e049c03/Source/Controllers/MainViewControllers/TableContent/SPTableContent.m#L1767).

**Comment by Jason-Morcos** [comment]
As a workaround, does it work for your @9ae8sdf76 to go to the table's info tab and using this (honestly sorta-hidden) option to reset auto-inc whenever you want to?

<img width="595" alt="Screen Shot 2021-02-15 at 21 18 09" src="https://user-images.githubusercontent.com/10710367/108021395-50d74580-6fd3-11eb-845e-ab57563d68cb.png">

**Comment by Jason-Morcos** [comment]
After investigating, the prompt to reset auto-increment only shows up if you delete **all rows** in a table. It has nothing to do with the _count_ of rows selected explicitly, it's if you're deleting all of them. Which to me makes logical sense. In most cases, you really don't want to be resetting the auto inc. Wiping the whole table is that one case that maybe you do.
Additionally, anytime you want you can go to the table info page and reset the auto inc manually if you so desire.

I'm for closing this issue, but am open to other arguments.

**Comment by 9ae8sdf76** [comment]
I believe you misunderstand:

The reset auto-increment checkbox only is available when there are more than 50 rows in a table and you're deleting all of the rows:

> if (([tableContentView numberOfSelectedRows] == [tableContentView numberOfRows]) && **[tableContentView numberOfSelectedRows] > 50** && !isFiltered && !isLimited && !isInterruptedLoad && !isEditingNewRow) {

I'm asking to remove that part of the condition so that when deleting all rows out of a table, regardless of the table size, it'll allow easily resetting the auto-increment; regardless of whether there are 5 rows or 50. Please re-open and re-consider. Yes, there is a work-around, and it is tedious when having to deleting from multiple tables that use foreign keys and cannot be truncated.

**Comment by Kaspik** [comment]
I have no idea why there was the threshold for 50 rows but feel free to open a PR with this change. :)

**Comment by 9ae8sdf76** [comment]
@Kaspik Done. I was unable to build locally because I do not know how to set up XCode and I'm being blocked by the code signing process. Do you have any resources available that can help get me set up?

**Comment by Kaspik** [comment]
You have to use your own developer account unfortunately for now, and change the local code signing, but we will fix it soon hopefully!
