### ISSUE TITLE
Unsuccessful time zone setting does not throw warnings/errors

### ISSUE THREAD

**Issue by UlrichThomasGabor** [Sequel-Ace/Sequel-Ace#881]
- Sequel Ace Version (including build number): 3.1.1 Build 3016
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2
- Processor Type (Intel/Apple): Intel
- MySQL Version:  5.7.33 
- macOS Localization: GER

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**
Setting a time zone, which is not present in MySQL, is silently ignored.

**Steps To Reproduce**
1. Change time zone of a connection to "Europe/Berlin", which does not exist in MySQL (DELETE FROM `mysql`.`time_zone_name`)
2. Query `SET time_zone = 'Europe/Berlin';` is executed by SequelAce but MySQL says "Unknown or incorrect time zone: 'Europe/Berlin'". [This can happen if MySQL lacks time zone information.](https://www.aptget.de/unknown-or-incorrect-time-zone-europe-berlin/) (Only god knows why this can happen with a mysql apt installation at all, but it just happened to me...)
3. This MySQL error is not shown but silently ignored by SequelAce.

**Expected Behaviour**

Throw a warning/error.

**Related Issues**

#307 

**Additional Context**

**Comment by jamesstout** [comment]
@UlrichThomasGabor - How's this look:

![Screenshot 2021-02-17 at 6 45 53 PM](https://user-images.githubusercontent.com/1576190/108193748-c157a100-7150-11eb-9987-0522616127fe.png)

Also in the Console:

![Screenshot 2021-02-17 at 6 46 24 PM](https://user-images.githubusercontent.com/1576190/108193802-cf0d2680-7150-11eb-9267-dbd983871c67.png)

**Comment by UlrichThomasGabor** [comment]
@jamesstout Looks good!

**Comment by jamesstout** [comment]
PR #884 submitted.
