### ISSUE TITLE
Import Favorites from Sequel Pro

### ISSUE THREAD

**Issue by MacGritsch** [Sequel-Ace/Sequel-Ace#888]
I have a ton of favorites in Sequel Pro.
Is there any way to import them into Sequel Ace?
It would be ok to lose the saved passwords on import (but would great to keep them).

Thank you

**Comment by Kaspik** [comment]
https://sequel-ace.com/get-started/migrating-from-sequel-pro.html - this should help.

**Comment by MacGritsch** [comment]
O great. I have tried the password-mirgration and I see all the passwords in the keychain-app (and all are assigned to the Ace-app). But if I open Sequel Ace, it does not ask to get access to the passwords and therefore the password-fields are empty. Am I missing something? (have downloaded the app from MAS).

**Comment by MacGritsch** [comment]
I think I have found the "issue".
It worked with some of the favorites, but not with all.
The non-functioning ones had in common that the favorites were renamed in Sequel Pro (long time ago) after I logged in the first time (when the password was saved).

**Comment by Kaspik** [comment]
Glad to hear it works! :)
