### ISSUE TITLE
Can't log in via the jump server

### ISSUE THREAD

**Issue by bpzhang** [Sequel-Ace/Sequel-Ace#89]
it can not log in via jump server 

The error tips:The SSH Tunnel could not authenticate with the remote host. Please check your password and ensure you still have access.
![image](https://user-images.githubusercontent.com/1734396/85490295-17953400-b604-11ea-989a-b0ec6296382e.png)

But I can be sure the password is correct and I have this permission

**Comment by Jason-Morcos** [comment]
Which version of Sequel Ace are you using? Have you tried the latest beta to see if the issue persists or has been fixed?

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by bpzhang** [comment]
> Which version of Sequel Ace are you using? Have you tried the latest beta to see if the issue persists or has been fixed?
> 
> https://github.com/Sequel-Ace/Sequel-Ace/releases

use the 2.0.2 
and I use 2.1.0 Beta 4 ,It can show me the dialog of MFA auth
But when Input the MFA code then show me the follow tips:


![image](https://user-images.githubusercontent.com/1734396/85492324-9475dd00-b607-11ea-83e6-aa5c0dd2bc1e.png)

**Comment by Jason-Morcos** [comment]
Does your setup perhaps rely on settings from your .ssh directory, perhaps your ssh config file? Sequel ace is sandboxed and currently does not support custom ssh config files (although future support is in discussion).

**Comment by gboudreau** [comment]
This error, is a MySQL error, not a SSH error. So the SSH connection is working.
It's when libmysqlclient tries to connect to the MySQL server from there, that it fails.

Are you connecting using SSH to the MySQL server itself? If so, in the MySQL Host field, you need to input `127.0.0.1`, because you are connecting using the SSH connection, and thus you need to connect using the localhost address, not the public adress.

**Comment by Jason-Morcos** [comment]
@bpzhang Were you able to get this figured out?

**Comment by bpzhang** [comment]
> This error is a MySQL error, not a SSH error. So the SSH connection is working.
> It's when libmysqlclient tries to connect to the MySQL server from there, that it fails.
> 
> Are you connecting using SSH to the MySQL server itself? If so, in the MySQL Host field, you need to input `127.0.0.1`, because you are connecting using the SSH connection, and thus you need to connect using the localhost address, not the public address.

Yeah，At first I thought it was a problem with mysql, but I can  connect  through the Terminal

**Comment by bpzhang** [comment]
> Were you able to get this figured out

I still don't know the specific cause of this problem. According to the prompt, I feel that I should be logged in through ssh, and then there was a problem when connecting to mysql.

**Comment by gboudreau** [comment]
@bpzhang In Host field, are you specifying `127.0.0.1`?

**Comment by bpzhang** [comment]
> @bpzhang In `MySQL Host` field, are you specifying `127.0.0.1`? If not, please try that.

It may be a configuration problem, I have no permission to modify the online environment

**Comment by Jason-Morcos** [comment]
Is this fixed in the latest beta for you @bpzhang, or is it still an issue?

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by bpzhang** [comment]
> Is this fixed in the latest beta for you @bpzhang, or is it still an issue?
> 
> https://github.com/Sequel-Ace/Sequel-Ace/releases

Yes, it is still an issue, as @gboudreau said: it may be the problem of database server settings and I can not modify the server config So this problem is not solved on my side, you can invite others to test it

**Comment by Jason-Morcos** [comment]
Fixed the primary jump server issue in the 2.1.2 release. If other issues crop up for users, please open new issues and we can investigate!
