### ISSUE TITLE
Sequel Ace opening new connection windows by itself

### ISSUE THREAD

**Issue by FaimMedia** [Sequel-Ace/Sequel-Ace#892]
- Sequel Ace Version (including build number): 3.2.1 (3020) and 3.2
- Sequel Ace Source (App Store/GitHub/Homebrew): 3.2.1 AppStore, 3.2 GitHub
- macOS Version: 11.2.1 (20D74)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8.0.xx
- macOS Localization: nl-NL

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

No BETA present ATM.

**Description**
Somehow since version 3.2, Sequel Ace is opening additional 'new connection' windows (not tabs). Not sure when this exactly happens. But when I leave the app running in the background and switch back to Sequel Ace, a new empty window will be on top of the 'old' window. Usually not if I switch-back within a few seconds, but in a few minutes.

**Steps To Reproduce**
1. Switch away from Sequel Ace and make other program active for a few minutes;
2. Switch back to Sequel Ace, a new empty window will be on top of the first window.

**Expected Behaviour**
Not open new windows

<img width="1173" alt="Schermafbeelding 2021-02-19 om 16 07 05" src="https://user-images.githubusercontent.com/11771199/108521951-8e3a1c80-72cc-11eb-98f2-a3ba058b2036.png">

**Comment by Kaspik** [comment]
That will be one of my changes trying to get windows hierarchy done better...  Weird I didn't catch it, but I'll take a look.

**Comment by jamesstout** [comment]
Seems to be this code:

https://github.com/Sequel-Ace/Sequel-Ace/blob/8163a4250dcf389a320ff081ccab74628639a088/Source/Controllers/SPAppController.m#L1346-L1355

Which calls:

https://github.com/Sequel-Ace/Sequel-Ace/blob/8163a4250dcf389a320ff081ccab74628639a088/Source/Controllers/SPAppController.m#L1236-L1238

If the window has _only_ resigned main window then `activeWindowController` is not null and no new window is created.
If the `windowDidMiniaturize` then `activeWindowController` is null and a new window is created

**Comment by xiangbohua** [comment]
I got the same problem today.
It's should open the active window but now it's opening a whole new when click the icon on the dock.

**Comment by olimortimer** [comment]
Same on Big Sur 11.1 (20C69)

**Comment by AndrewAtkinson** [comment]
Same issue on Catalina

**Comment by andryska** [comment]
And on Big Sur 11.2.1
