### ISSUE TITLE
Window tab bar implementation click and drag problems

### ISSUE THREAD

**Issue by lostminds** [Sequel-Ace/Sequel-Ace#896]
- Sequel Ace Version (including build number): 3.2.0 3019
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version: 11.2.1
- Processor Type (Intel/Apple):Intel
- MySQL Version:
- macOS Localization:

**Description**
The custom tab bar implementation in the Sequel Ace seems to have some issues on macOS 11, especially with relation to click and drag move, which hides the entire window and then offsets it incorrectly. Entire window disappears as long as you hold mouse, when you release it, even if you just move a couple of pixels, the window will be offset to have the x.origin at the mouse point.

**Steps To Reproduce**
1. Open Sequel Ace
2. Click and drag in tab view. 

**Expected Behaviour**
Either nothing or window moving when dragging, also expected macOS standard View menu option to show/hide tab bar.

**Additional Context**
It might be a good idea to replace what looks like a custom built tab bar control with the standard macOS window tab bar solution (just check out NSWindow .tabbingMode and .allowsAutomaticWindowTabbing ). That way you'll get all the tab interactions and appearances working as expected, and as a bonus get the standard hiding/showing of the tab bar behavior users expect. Like the now missing View menu option to hide the tab bar.

**Comment by Kaspik** [comment]
I'm aware of this and already tried to implement the native solution. First PR in window hierarchy was merged, but there is a big chunk of work involved in this that still needs to be done to fully remove our old tab bar solution...

**Comment by Kaspik** [comment]
Closing in favor of project: https://github.com/Sequel-Ace/Sequel-Ace/projects/7

Not sure when this will make it into the release, but actively working on this as one very very big refactoring.
