### ISSUE TITLE
The favourites side panel takes on the wallpaper tint in full screen mode

### ISSUE THREAD

**Issue by jamesstout** [Sequel-Ace/Sequel-Ace#902]
- Sequel Ace Version (including build number): latest main
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version: 11.2.1 (20D74)
- Processor Type (Intel/Apple): Intel
- MySQL Version: 8
- macOS Localization: en_HK

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**
The favourites side panel takes on the wallpaper tint in full screen mode.

**Steps To Reproduce**
1. Set a colourful background - e.g. Big Sure Automatic
2. Set Allow Wallpaper tinting on windows to on.
3. Open Sequel Ace and make full screen.
4. The faves sidebar looks like this:

<img width="327" alt="Screenshot 2021-02-24 at 8 48 27 PM" src="https://user-images.githubusercontent.com/1576190/109003438-6ab70d80-76e2-11eb-85c5-928b622eb9ce.png">

**Expected Behaviour**
Not sure if this is a feature or a bug, or if it's overridable? 

**Related Issues**

**Additional Context**

**Comment by Jason-Morcos** [comment]
@Kaspik I believe you made this change? Thoughts?

**Comment by Kaspik** [comment]
Sidebars usually use blur as a background (native calendar, notes, mail, ...), so this is expected behavior. :)
