### ISSUE TITLE
Can't connect with empty password

### ISSUE THREAD

**Issue by mrdziuban** [Sequel-Ace/Sequel-Ace#904]
- Sequel Ace Version (including build number): 3.2.2 build 3021
- Sequel Ace Source (App Store/GitHub/Homebrew): GitHub
- macOS Version: 10.14.3
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.4.10
- macOS Localization: EN-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

N/A, there are no beta releases newer than v3.2.2.

**Description**

I'm unable to connect to MariaDB when leaving the password field empty, even though the database user (`root`) has no password. The error message says "Access denied for user 'root'@'localhost' (using password: YES)"

**Steps To Reproduce**
1. Setup a database user with no password
2. Add a TCP/IP connection using the new user and leaving the password field empty
3. Try to connect, see "Access denied!" error

**Expected Behaviour**

I should be able to connect to the database without specifying a password.

**Additional Context**

<img width="400" src="https://user-images.githubusercontent.com/4718399/109014310-02384400-7682-11eb-9498-57f695fe4333.gif">

**Comment by Kaspik** [comment]
Based on `Save changes` it seems like you are using existing favorite. Is that the case? If so, does the favorite itself has a password stored? Does it work via `Quick connect` on left side?

**Comment by mrdziuban** [comment]
Yes, I was editing an existing favorite that has a password, I thought deleting it from the field would prevent it from being used. And yes it does work via quick connect, can't believe I didn't try that 🤦 

Feel free to close this if you'd like or perhaps update it to refer to not being able to remove a password from an existing favorite if you think that's worth investigating. Thanks for the quick help!

**Comment by Kaspik** [comment]
It would work if you would hit `save changes` - until then it still uses what's saved. :) Glad it works!
