### ISSUE TITLE
Support GitHub Sponsors

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#91]
I am currently supporting the old project on GitHub Sponsors and would like to move my support here.

**Comment by Jason-Morcos** [comment]
Hi, @fulldecent! While we're thrilled about the desire to support, I think the project needs to stabilize a bit before we feel comfortable accepting sponsorship/monetary contributions. We'll keep everyone posted though on this moving forward and will likely review again in a month or two!

**Comment by Jason-Morcos** [comment]
Closing as duplicates https://github.com/Sequel-Ace/Sequel-Ace/issues/60
