### ISSUE TITLE
impossible to set NULL value to VARCHAR field

### ISSUE THREAD

**Issue by vitaha85** [Sequel-Ace/Sequel-Ace#910]
Version 3.2.2
Build 3021

Issue - when you have VARCHAR field with length less than 4 chars you can't set NULL value in editor

**Comment by jamesstout** [comment]
Do you have allow null checked?

e.g.

` article_title varchar(3) DEFAULT NULL,`

**Comment by vitaha85** [comment]
> Do you have allow null checked?
> 
> e.g.
> 
> ` article_title varchar(3) DEFAULT NULL,`

yes, i have
`result` varchar(2) DEFAULT NULL,

**Comment by vitaha85** [comment]
<img width="64" alt="Снимок экрана 2021-02-25 в 12 52 28" src="https://user-images.githubusercontent.com/9131415/109143138-5c133980-7768-11eb-9154-281c39b3c1a5.png">

**Comment by jamesstout** [comment]
Strange. varchar(3) allows you to enter NULL...

**Comment by jamesstout** [comment]
Anyway, found a comment that says:

`Validate editTextView for maximum text length except for NULL as value string`

Clearly not working .... taking a look.

**Comment by jamesstout** [comment]
PR submitted.
