### ISSUE TITLE
Query history can't be display complete in one row

### ISSUE THREAD

**Issue by xiangbohua** [Sequel-Ace/Sequel-Ace#913]
- Sequel Ace Version (including build number): 3.2.1 build 3020
- Sequel Ace Source (App Store/GitHub/Homebrew): APP Store
- macOS Version:11.2.2
- Processor Type (Intel/Apple): intel
- MySQL Version: any
- macOS Localization: EN

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes. The problem was keep shown in the version 3.2.2(build 3021)
 

**Description**
Query history was split to many parts if the statement contain new line character.
For ex: select *from 
(there was new line) table1 where a = 1;
After run this statement there are 2 lines shown on the "Query History";

**Steps To Reproduce**
1. Open the app and connect to any MySQL server
2.run any sql statement with new line character(may be:\r\n). complex statement will be better
3.Click Query History
4.You will see the statement may has been split to many row
5.Click any row of the Query History you will see a part of the statement will fill into query windows but not the complete statement.

**Expected Behaviour**
The executed statement should be fill into query window completely after click Query History.

**Related Issues**
---

**Additional Context**
<img width="399" alt="WeCom20210226-170848@2x" src="https://user-images.githubusercontent.com/10529889/109279924-4f204400-7855-11eb-815b-20d6bd4500ab.png">

**Comment by xiangbohua** [comment]
<img width="552" alt="WeCom20210226-171742@2x" src="https://user-images.githubusercontent.com/10529889/109280919-965b0480-7856-11eb-8390-69ced7be34c7.png">

this pic will show more information

**Comment by Jason-Morcos** [comment]
<img width="156" alt="Screen Shot 2021-02-26 at 10 36 48" src="https://user-images.githubusercontent.com/10710367/109340959-8b847d80-781e-11eb-9479-14fdb07126cf.png">

I can indeed reproduce with the latest release. 
When toggling off "Save Query History Individually", the query is saved as one. However, I do agree that a multi-line query should be saved together.

@jamesstout  Sounds like some feedback on https://github.com/Sequel-Ace/Sequel-Ace/pull/825. Looks like the individual option is splitting on `\n` and not `;\n`

**Comment by jamesstout** [comment]
PR #916 submitted

**Comment by xiangbohua** [comment]
@Jason-Morcos 
@jamesstout 
fxxk, it was a feature???  my bad. sorry about that
