### ISSUE TITLE
New connection when maximise after minimise

### ISSUE THREAD

**Issue by abifathullah** [Sequel-Ace/Sequel-Ace#918]
- Sequel Ace Version (including build number): Version 3.2.2 Build 3021
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.2
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.32
- macOS Localization:

**Description**
When minimise the application windows, upon maximise the application, it shows 'New Connection' instead of showing previous connected database windows

**Steps To Reproduce**
1. Launch application.
2. Connect to localhost
3. Minimise application
4. Maximise application
5. Application shows 'New Connection' windows instead of previous connected database window.

**Expected Behaviour**
Application supposedly to maximise previously minimise connected window instead of showing 'New Connection' window.

**Comment by mfehr94** [comment]
Use search please 😔

Duplicate of #892

**Comment by abifathullah** [comment]
Sorry. Wrong search keyword used. Thank you.
