### ISSUE TITLE
Support Language Server

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#92]
2020 not the year where you want to be maintaining a code editor and language support by yourself.

The VS Code project has factored out language support into the project https://langserver.org

I think that long-term, the code editor for Sequel Ace could support this project. 

This will allow perfect code completion ("do I need backticks here or not?") and support from the millions of developers on VS Code which are already using SQL.

**Comment by Jason-Morcos** [comment]
Cool idea. Looks like a fairly involved undertaking. Would love to encourage someone in the community to jump in headfirst on this one. I think we'd all be very happy to review/merge such a PR.

**Comment by gboudreau** [comment]
I don't see MySQL, or even SQL, in the list of supported languages.
I think T-SQL is implemented by MS (why is it not listed on langserver.org ?), but for a MySQL client, I don't think that would be useable as-is.
