### ISSUE TITLE
Export to > SQLite [BOUNTY USD 250]

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#926]
Currently you can export a query result or table to: SQL, CSV, XML and DOT.

I would like to request an addition of: SQLite

Using this option would export a SQLite table using the same information.

The cool thing about SQLite is that columns are untyped. So this will NOT require passing/converting column types.

---

💰  Pacific Medical Training commits a bounty of USD 250 to anybody that can solve this issue. Terms:

- The PR must follow all project guidelines here
- The PR must be accepted here into the main branch by 2021-04-02
- The PR must address the required features in this issue

---

<img width="1009" alt="Screen Shot 2021-03-02 at 15 09 21" src="https://user-images.githubusercontent.com/382183/109708583-98300b00-7b69-11eb-8b55-4803f09480fc.png">

**Comment by jamesstout** [comment]
@fulldecent Do you want to be able to select Structure/Content/Drop like on the SQL export tab?

**Comment by fulldecent** [comment]
`DROP` does not makes sense here because the output is a *.db file.

The CSV/XML/DOT export is more similar to what is needed here

**Comment by fulldecent** [comment]
Closing. Not enough interest. And the end of the bounty will not increase interest level.

**Comment by Kaspik** [comment]
I wouldn't say not enough interest, but as I mentioned on other ticket - we were focused on stability and modernizing the code behind the app before introducing new thing. We are just about to release completely rewritten windows and app structure / hierarchy, then I would like to do couple more changes bahind the scene memory related. We might get to this then. :)
