### ISSUE TITLE
Error: The table data couldn't be loaded

### ISSUE THREAD

**Issue by sebastiansulinski** [Sequel-Ace/Sequel-Ace#931]
I'm on version 3.2.1 Build 3020 with BigSur and MySQL 8.

There seem to be an issue with database selection when switching between databases.
Steps to reproduce:

1. Select database
2. Select table of that database
3. Switch database
4. Try to export entire database without selecting any table

You will get `Error: The table data couldn't be loaded...`

**Comment by jamesstout** [comment]
When the code gets to `loadTableValues`, the `selectedTable` is still the table from the previous database. A fix would be to select the first table in the new database. What do you think?

**Comment by jamesstout** [comment]
See PR #940
