### ISSUE TITLE
SequelAce defaults to utf8mb4_0900_ai_ci 

### ISSUE THREAD

**Issue by byteasc** [Sequel-Ace/Sequel-Ace#932]
- Sequel Ace Version (including build number): 3.2.2-3021
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: Aurora (MySQL 5.7.12-log)
- macOS Localization: english

**Description**
When connecting to an AWS Aurora 2.0 (MySQL 5.7) server, the connection for the client is being flagged to use utf8mb4_0900_ai_ci (which is incompatible with 5.7). When detecting utf8mb4, it should be trying to use the utf8mb4_general_ci collation instead.

![image](https://user-images.githubusercontent.com/10793868/109870277-84e77300-7c2f-11eb-9b00-e02e9d2add35.png)

This is results of a query to the server and the resulting connections that are set by the client.

**Comment by Kaspik** [comment]
@Jason-Morcos This was your change, right?

**Comment by Jason-Morcos** [comment]
I changed us from utf8 to utf8mb4, yeah. But this looks funky.

@byteasc Do you think it's possible you have a server setting or local config file setting that's choosing that 0900_ai_ci collation? I'm not sure why/how we would be choosing such a funky encoding. What's that query you're running in the screenshot?

**Comment by byteasc** [comment]
> I changed us from utf8 to utf8mb4, yeah. But this looks funky.
> 
> @byteasc Do you think it's possible you have a server setting or local config file setting that's choosing that 0900_ai_ci collation? I'm not sure why/how we would be choosing such a funky encoding. What's that query you're running in the screenshot?

I'm just using `SHOW VARIABLES LIKE 'collation%';` basically along with `SHOW VARIABLES LIKE 'character_set%';`

When I connect to my local MySQL instance (MySQL 5.7.32) its come back with this:
![image](https://user-images.githubusercontent.com/10793868/109885205-bec27480-7c43-11eb-9176-6e7c632ccda9.png)
Which is what I would expect. `collation_connection` is also client handled but there is no place to change that in Sequel Ace.

**Comment by Jason-Morcos** [comment]
@byteasc Can you share a screenshot of Sequel Ace's Database->View Using Encoding dropdown options for your AWS connection? Testing with a MySQL 5.6 Aurora connection I can't reproduce. Especially as it looks right locally, it feels like it's possible there's something funky somewhere with your MySQL config, either on your computer itself or in you rAWS configuration.

**Comment by byteasc** [comment]
> @byteasc Can you share a screenshot of Sequel Ace's Database->View Using Encoding dropdown options for your AWS connection? Testing with a MySQL 5.6 Aurora connection I can't reproduce. Especially as it looks right locally, it feels like it's possible there's something funky somewhere with your MySQL config, either on your computer itself or in you rAWS configuration.

We are using Aurora 2.0 (5.7)
![image](https://user-images.githubusercontent.com/10793868/110037294-d3fed800-7d03-11eb-947f-98a448bcd700.png)

I could believe there was some configuration thing, but from everything I've read the 'collation_connection' is 100% clientside, so unless Big Sur is causing something to act weird, Idk where it would be pulling the 0900_ai_ci from, since it isn't MySQL 8

**Comment by byteasc** [comment]
I've done some more research on this and it appears to be possibly be a combination of Sequel Ace + Aurora 2.0... AWS Aurora 2.0 actually has backported support for utf8mb4_0900_ai_ci, so while MySQL doesnt technically support it till 8.0, Amazon added into their version of 5.7.

I would assume that this is getting detected and thus is becoming the client collation of choice.

**Comment by byteasc** [comment]
Closing this for now since it seems to be a weird AWS situation

**Comment by lbbniu** [comment]
> SHOW VARIABLES LIKE 'collation%';

unknown error: execute sql error, sql: SHOW VARIABLES LIKE 'collation%', err: ERROR 1273 (HY000): Unknown collation: 'utf8mb4_0900_ai_ci'
