### ISSUE TITLE
Frequent crashes under 10.15 Cathalina

### ISSUE THREAD

**Issue by ATM-NET** [Sequel-Ace/Sequel-Ace#937]
- 3.2.1 Build 3020
- App store
- 10.15.7
- Intel
- 5.7.26 (under MAMP / macOS)
- Russian

Sorry, I'm afraid to install Beta versions.

**Steps To Reproduce**
1. Open the DB conectiion
2. Select any table 
3. Scroll in table, vertical or horisontal
4. Chrash. Failure does not always happen, but several times per hour.

**Expected Behaviour**
Stable behavior.
![_screenshot 2021-03-04 в 15 00 57](https://user-images.githubusercontent.com/42110592/109946910-93e72780-7cfa-11eb-8399-3e0ad276bf85.jpg)
[sequel-ace-crash-log.txt](https://github.com/Sequel-Ace/Sequel-Ace/files/6082579/sequel-ace-crash-log.txt)

**Comment by Kaspik** [comment]
These delegate tooltips are fixed in 3.2.2 afaik. :) Please update.
