### ISSUE TITLE
"Auto pair characters" setting changes font and causes undo issues

### ISSUE THREAD

**Issue by origamifreak2** [Sequel-Ace/Sequel-Ace#939]
- Sequel Ace Version (including build number): 3.2.2 Build 3021
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.0.1
- Processor Type (Intel/Apple): Intel
- MySQL Version: 10.5.8-MariaDB Homebrew
- macOS Localization: United States

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes

**Description**
When highlighting a word and typing any character that would be paired (eg. "`" or "'"). The font changes just for the highlighted word and pressing cmd + z causes some strange behavior

**Steps To Reproduce**
1. type a query without paired characters (SELECT * FROM test_table)
2. Highlight a word you want to add paired characters to
3. Type the paired character

**Expected Behaviour**
Paired characters should be added around the highlighted word without changing the font and breaking the undo command.

**Related Issues**
None known

**Additional Context**

https://user-images.githubusercontent.com/2578041/109992357-30003700-7cd9-11eb-85e4-48fca5253452.mov

![Sequel_ace_editor_settings](https://user-images.githubusercontent.com/2578041/109992685-82415800-7cd9-11eb-9b7b-80b2da37c4ab.png)

**Comment by jamesstout** [comment]
I've [fixed the font changing](https://github.com/Sequel-Ace/Sequel-Ace/commit/998fe4e2582962f3deebac6a35994022fb7f51c3). Still looking at the undo issue.

**Comment by jamesstout** [comment]
[Fixed the undo issue](https://github.com/Sequel-Ace/Sequel-Ace/commit/c003a690266708141bbaf0a71ebe19f46d6581ed).

**Comment by jamesstout** [comment]
PR #941

**Comment by origamifreak2** [comment]
> [Fixed the undo issue](https://github.com/Sequel-Ace/Sequel-Ace/commit/c003a690266708141bbaf0a71ebe19f46d6581ed).

Awesome! Thanks :)
