### ISSUE TITLE
Password is deleted with username change

### ISSUE THREAD

**Issue by eriku** [Sequel-Ace/Sequel-Ace#946]
- Sequel Ace Version (including build number):3.2.2
- Sequel Ace Source (App Store/GitHub/Homebrew): App Stor
- macOS Version: 11.2.2
- Processor Type (Intel/Apple): Intel
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
I'm not sure if the issue is present in the latest beta

**Description**
When adding login for TCP/IP or SSH the password keeps on getting deleted if I need to change/edit the username

**Steps To Reproduce**
1. New Connection (or Quick Connect)
2. Enter username
3. Enter password
4. Go back and change/edit username

**Expected Behaviour**
I should be able to edit/change the username without having to re-enter the password.

**Related Issues**
Couldn't find any related issues

**Additional Context**

**Comment by Kaspik** [comment]
I'm pretty certain this is expected behavior happening since forever because there is a logic added to do this on purpose for security purpose - not a bug. Don't remember more details...

**Comment by samuelbradshaw** [comment]
Related: https://github.com/Sequel-Ace/Sequel-Ace/issues/246
