### ISSUE TITLE
Website - Documentation: Work on Content

### ISSUE THREAD

**Issue by stychos** [Sequel-Ace/Sequel-Ace#95]
This Issue is to continue started work on documentation.
Key things that are still need to be done:

- [x] Place Download links (from AppStore & from GitHub Releases)
- [ ] Revise Getting Connected Section
- [ ] Reference Section
- [ ] Bundles Section
- [ ] Contribute Section
- [ ] Usage Screenshots

**Comment by stychos** [comment]
Need to mention https://github.com/Sequel-Ace/Sequel-Ace/pull/144

**Comment by Jason-Morcos** [comment]
> Need to mention https://github.com/Sequel-Ace/Sequel-Ace/pull/144

I added a tiny bit but definitely could use a lot more! https://github.com/Sequel-Ace/Sequel-Ace/commit/c0e528de40d96fee5dfdf95c0107e2d77fe2355b
