### ISSUE TITLE
SQL statement auto complete working unusual when filling functions

### ISSUE THREAD

**Issue by xiangbohua** [Sequel-Ace/Sequel-Ace#954]
- Sequel Ace Version (including build number): Version 3.2.3 Build 3024
- Sequel Ace Source (App Store/GitHub/Homebrew): Github download
- macOS Version: 11.2.2(20D80)
- Processor Type (Intel/Apple): Intel
- MySQL Version:5.7.27
- macOS Localization: Zh-Han

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Nerver found

**Description**
SQL statement auto complete working unusual when filling functions. 
I think those mysql functions may be split to two parts. One part is the name of the function and other part is the '()' and function parameters. The problem is '()' and function parameters was append to the tail of the statement rather than the tail of the function name.
It's looks like this:
Function 'SUM' in statement 'select sum(id) from table_name '  will be filled as 'select sum from table_name(id)  '.
'select sum(id) from table_name;' ----> 'select sum from table_name;()'

Change input method from Chinese to English was not helpful.

**Steps To Reproduce**
1.connect to any server
2.write any sql statement and trying to type a function name such as 'su' or 'grou'(do not write completely)
3.type enter when the statement hit was shown

**Expected Behaviour**
You will see the '()' with parameters demo will be append to the tail of the whole statement.

**Related Issues**
Never  found.

**Additional Context**

https://user-images.githubusercontent.com/10529889/110271453-0f9aea00-8003-11eb-89eb-baeb70c497b9.mov

**Comment by Iv4nS** [comment]
also experiencing this, if for example using a function that has parameters the highlight happens in an area that is not meant to. for example try doing the same as above but with FORMAT

**Comment by Jason-Morcos** [comment]
I believe this is fixed in the latest beta! Please let me know if not. 

https://github.com/Sequel-Ace/Sequel-Ace/releases
