### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by elgs** [Sequel-Ace/Sequel-Ace#955]
1. Currently the minimum delay of auto complete is .5 seconds, can it be set to no delay?
2. Can you please make auto complete tolerant to not typing the underscore? For example if I have a table `some_awesome_table`, the auto complete will be off if I type `somea`. Can you please make it tolerant to `someaw`, or even `sat`?
3. Can you please show SQL preview before every DML is committed by the UI?

Thanks!

**Comment by elgs** [comment]
> > 3. Can you please show SQL preview before every DML is committed by the UI?
> 
> We added a setting to alert you to 'destructive' SQL queries: #160. Does that suit your needs?

Yes. Thanks. But I also observed that when I edit a field, sometimes it pops up a new window, and sometimes I am allowed to edit inline. When I edit it in the popup window, the DML preview doesn't show.

**Comment by jamesstout** [comment]
> Yes. Thanks. But I also observed that when I edit a field, sometimes it pops up a new window, and sometimes I am allowed to edit inline. When I edit it in the popup window, the DML preview doesn't show.

OK, will check.

**Comment by jamesstout** [comment]
How's this?

![2021-03-09 21 00 10](https://user-images.githubusercontent.com/1576190/110474401-94c4f280-811a-11eb-8105-f61bbbc65d6e.gif)

This is with fuzzy set to always on...

**Comment by jamesstout** [comment]
It calls `doAutoCompletion` (after delay) for every character typed, but only executes the auto-completion once, after the user stops typing and the delay, cancelling any other auto-completion requests.

**Comment by Jason-Morcos** [comment]
> It calls `doAutoCompletion` (after delay) for every character typed, but only executes the auto-completion once, after the user stops typing and the delay, cancelling any other auto-completion requests.

Hmmm it still seems a little crazy. A half second already is so fast. Maybe for now we could drop the delay down a bit, but I just don't see the need for 0. 

Additionally, @elgs, in the future please open a feature request per each _individual_ feature you're requesting. Combing three together, even if they're small, makes it very hard to track issues.

**Comment by jamesstout** [comment]
> > Yes. Thanks. But I also observed that when I edit a field, sometimes it pops up a new window, and sometimes I am allowed to edit inline. When I edit it in the popup window, the DML preview doesn't show.
> 
> OK, will check.

I can't reproduce. Could you please give me some steps to follow? Thanks.

**Comment by elgs** [comment]
> > > Yes. Thanks. But I also observed that when I edit a field, sometimes it pops up a new window, and sometimes I am allowed to edit inline. When I edit it in the popup window, the DML preview doesn't show.
> > 
> > OK, will check.
> 
> I can't reproduce. Could you please give me some steps to follow? Thanks.
![CleanShot 2021-03-09 at 09 50 41](https://user-images.githubusercontent.com/55955/110515418-3d446980-80bd-11eb-8aad-e2fdc390f52f.gif)

**Comment by jamesstout** [comment]
> This is with fuzzy set to always on..

What do @Sequel-Ace/all think about enabling fuzzy matching for all non-SQL keywords?

**Comment by jamesstout** [comment]
> Maybe for now we could drop the delay down a bit, but I just don't see the need for 0.

I’ve implemented 0.0 but with a warning that pops up saying BEWARE: can cause weird output. Happy to remove though. Or set to 0.2?

**Comment by elgs** [comment]
I think the first popup (leading of the debounce) should be 0, and you can do .1 or .2 of debounce. I don't see any reason to have any delay on the first trigger, or the `leading` of the debounce should be 0.

**Comment by jamesstout** [comment]
> > > > Yes. Thanks. But I also observed that when I edit a field, sometimes it pops up a new window, and sometimes I am allowed to edit inline. When I edit it in the popup window, the DML preview doesn't show.
> > > 
> > > 
> > > OK, will check.
> > 
> > 
> > I can't reproduce. Could you please give me some steps to follow? Thanks.
> 
>

Fixed.

**Comment by Jason-Morcos** [comment]
> > This is with fuzzy set to always on..
> 
> What do @Sequel-Ace/all think about enabling fuzzy matching for all non-SQL keywords?

Fine by me!


> I’ve implemented 0.0 but with a warning that pops up saying BEWARE: can cause weird output. Happy to remove though. Or set to 0.2?

Ehhh if a user wants to do 0 I'm okay with letting them do zero, especially if you're warning them when they do. Fine by me!

**Comment by Jason-Morcos** [comment]
> > > I’ve implemented 0.0 but with a warning that pops up saying BEWARE: can cause weird output. Happy to remove though. Or set to 0.2?
> > 
> > 
> > Ehhh if a user wants to do 0 I'm okay with letting them do zero, especially if you're warning them when they do. Fine by me!
> 
> Do you mind to explain what weird output could it possibly cause?

I think it has to potential to cause odd crashes and perhaps poor performance, so more bugs than unexpected outputs, but still something good to be aware of.
