### ISSUE TITLE
Allow tab key to be used for indent in SQL editor

### ISSUE THREAD

**Issue by ssx** [Sequel-Ace/Sequel-Ace#957]
Can you add support to make the tab key indent text in the editor instead of overwriting it?

**Comment by origamifreak2** [comment]
Tabbing does not overwrite characters for me. What are your settings for the query editor?
![Screen Shot 2021-03-22 at 4 25 39 PM](https://user-images.githubusercontent.com/2578041/112053861-460c5500-8b2b-11eb-91df-80dffef5c9cf.png)


https://user-images.githubusercontent.com/2578041/112053777-2412d280-8b2b-11eb-8976-6c84f1508c6f.mov

**Comment by ssx** [comment]
Ah yes - I've described this terribly, if you highlight all of that block - then press tab - does that indent it?

**Comment by ssx** [comment]
Zomg. Turning soft indent on works and does exactly as above!
