### ISSUE TITLE
Website & Documentation: Work on Structure

### ISSUE THREAD

**Issue by stychos** [Sequel-Ace/Sequel-Ace#96]
Currently, documentation is implemented by writing simple .md files and passing them to GitHub's parser.
Would be good to have it refactored to have some common header with, at least, global menu and download links.
Maybe it's needed to start using Jekyll or to make some another kind of static website for MVP.

Question: right now the domain[ sequel-ace.com](sequel-ace.com) points to the documentation root. Do we need to think about separating documentation from other parts of website, or keep it documentation-centric?

**Comment by DNA** [comment]
I think it would be better to move the docs from the site. Something like a docs.sequel-ace.com. This way we can keep the docs in a fixed location if we ever need to add more contento to the website.

As for the structure, I think a good tool for that would be [Docsify](https://docsify.js.org/). With it we can keep the markdown files that are easy to write and edit, and also add some nice plugins to enhance it :)

I have no idea on how to write objective-c, but I can help with the doc/website :D

**Comment by stychos** [comment]
@DNA or maybe move them into the /docs. I don't sure, but looks like we can use almost anything static in Github Pages to accomplish this, or use some more Jekyll stuff. Unfortunately, I still have no possibility to return to this in the nearest 1.5-2 weeks, thus your involvement will be highly appreciated!

**Comment by Jason-Morcos** [comment]
We're hosting the /docs dir as sequel-Ace.com
I think it's okay if we want to subdir the docs (docs/docs in the repo) and have a home-page (but we'd have to update the links from the app itself) but the is there really a need to create a second docs repo that hosts docs.sequel-ace.com instead? What do we really gain from that that we don't have just doing sequel-Ace.com/docs?

**Comment by stychos** [comment]
Keeping it in current repo (even in /docs/docs):
+ can be done easy way by writing Markdown files
+ easier to ask contributors to add documentation changes on PRs
- not so flexible, need some Jekyll kung-fu to implement menus and improve layout

Keeping in separate repo:
+ flexible, we can use another language to develop website and do whatever we need in it
- needs hosting (I can provide it, but will need to set ddns callback because my IP is dynamic)
- more complex, that will be two projects

**Comment by zachflauaus** [comment]
I'd also be willing to help contribute to the new site or some documentation. Glad to help this project however I can.

**Comment by stychos** [comment]
@zachflauaus would be very cool to see your help here! I did not finish with the conversion of bundles pages yet. Also we need to think on some common menu section which is need to be included instead of copy-pasted in each file. Or maybe you have some another cool proposals for the Sequel Ace? Hope you have enough of time and wish!

**Comment by Kaspik** [comment]
Trying to poke around here two years later.

@stychos / @zachflauaus Anyone up to help with the docs/docu here?
