### ISSUE TITLE
Access denied only in Sequel-Ace

### ISSUE THREAD

**Issue by DarthPestilane** [Sequel-Ace/Sequel-Ace#960]
- Sequel Ace Version (including build number): 3.2.3 (build: 3024)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.19
- macOS Localization: zh_CN.UTF-8

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

I think I'm using the latest release according to the version number.

**Description**

Cannot access to mysql db by TCP/IP with username and password, while I can do it in terminal with the same credential

**Expected Behaviour**

Should access to mysql

**Comment by Jason-Morcos** [comment]
Hmmm I just tested again and I can absolutely connect to my db via TCP/IP. Also, we haven't had this issue reported recently and this is a very common connection type so I'm inclined this is something to do with your specific setup.
Do you perhaps have some special settings that Sequel Ace can't see? Sequel Ace is sandboxed, so it can't magically access things like your ssh config. Are you perhaps engaging in a socket connection and not TCP/IP in the terminal? There are some serious known issues with sockets and Sequel Ace (#113 )

**Comment by DarthPestilane** [comment]
I just setup like this:
![image](https://user-images.githubusercontent.com/15375753/110589550-8b3a9980-81b1-11eb-8a57-178af6665810.png)

**Comment by Jason-Morcos** [comment]
> I just setup like this:
> ![image](https://user-images.githubusercontent.com/15375753/110589550-8b3a9980-81b1-11eb-8a57-178af6665810.png)

Right, I'm referring to some config outside of Sequel Ace that your terminal may be using but Sequel Ace doesn't have access to. Is there anything else special about the way you're set up?

**Comment by Jason-Morcos** [comment]
Very odd, any errors in the console.app when Ace fails to connect?

**Comment by DarthPestilane** [comment]
There's no new logs when connection failed.

**Comment by Jason-Morcos** [comment]
@Sequel-Ace/all Anyone got any ideas? I'm at a loss on this one

**Comment by DarthPestilane** [comment]
Maybe it's about the server side? I'm actually connecting a proxy to mysql not directly connecting to a mysql server

**Comment by neilmcgibbon** [comment]
@DarthPestilane did you ever find a fix for this? I'm experiencing the same

**Comment by DarthPestilane** [comment]
@neilmcgibbon  Nope, but I haven't use Sequel-Ace for a while, so I'm not sure.

**Comment by stiucsib86** [comment]
I'm also facing access denied while trying to connect to 10.4.20-MariaDB - MariaDB Server.
![Screenshot 2021-09-09 at 1 11 41 PM](https://user-images.githubusercontent.com/74789/132626818-4db327f2-0da7-4824-a70f-2019f340003f.png)

**Comment by Jason-Morcos** [comment]
Does it work by chance if you try 127.0.0.1 instead of localhost?

**Comment by stiucsib86** [comment]
So sorry, please ignore my issue. Just found out the user connection when I'm tunnelling is root@127.0.0.1. Updated the password and resolved.

**Comment by drizzleL** [comment]
same problem here, 
Access denied in both sequel ace and mysql 8.0, while 5.7 and navicat is ok

connection result from mysql 5.7:
----
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 922
Server version: 5.0.51b

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
----

**Comment by Jason-Morcos** [comment]
@drizzleL please open a new issue and fully fill out the issue template so that we can assist you with this issue. Be sure to include a screenshot of your connection screen, blurring out details for confidentiality as needed.
