### ISSUE TITLE
Pretty print BINARY field data

### ISSUE THREAD

**Issue by wedi** [Sequel-Ace/Sequel-Ace#962]
It would be cool if Sequel-Ace had an option to encode and display binary fields in some "human readable" form. This would make it possible for a human to check the actual bytes that got stored in the database. Since GUIs are usually designed for humans primarily, one could even argue that this option should be the default. In addition, it became possible to move data via copy and paste without applications choking on "funny" characters.

The following screenshot illustrates quite strikingly what I mean. It's a snippet from a Shopware 6 database. [Shopware 6](https://github.com/shopware/platform) uses binary keys for Reasons™. On the far right you can see that not all fields are gibberish, but I had to truncate them for pricacy reasons.

![grafik](https://user-images.githubusercontent.com/1466269/110671006-525ced80-81ce-11eb-852d-95fbad4e3756.png)

For completenes, here's the SQL to create the tables shown.
```sql
CREATE TABLE `order_customer` (
  `id` binary(16) NOT NULL,
  `version_id` binary(16) NOT NULL,
  `customer_id` binary(16) DEFAULT NULL,
  `order_id` binary(16) NOT NULL,
  `order_version_id` binary(16) NOT NULL,
  `email` varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL,
  `salutation_id` binary(16) NOT NULL,
  `first_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customer_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `custom_fields` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `remote_address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`,`version_id`),
  KEY `fk.order_customer.customer_id` (`customer_id`),
  KEY `fk.order_customer.order_id` (`order_id`,`order_version_id`),
  KEY `fk.order_customer.salutation_id` (`salutation_id`),
  CONSTRAINT `fk.order_customer.customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk.order_customer.order_id` FOREIGN KEY (`order_id`, `order_version_id`) REFERENCES `order` (`id`, `version_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk.order_customer.salutation_id` FOREIGN KEY (`salutation_id`) REFERENCES `salutation` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by jamesstout** [comment]
Is viewing as Hex no good? (_View->Display Binary Data as Hex_)

**Comment by wedi** [comment]
Viewing the fields in hex is pretty much what I expected. Neither me nor my colleagues found this. Thanks for the pointer.

There's just a tiny usability issue left: https://github.com/Sequel-Ace/Sequel-Ace/issues/971
