### ISSUE TITLE
SSH connection failed only in Sequel Ace (Sequel Pro works)

### ISSUE THREAD

**Issue by RodolfoGS** [Sequel-Ace/Sequel-Ace#968]
- Sequel Ace Version (including build number): Version 3.2.3 Build 3024
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): Apple
- MySQL Version: MariaDB 10.3.23
- macOS Localization: English

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** Yes

**Description**

I can't connect via SSH. I tested Sequel Pro with the same config in the same machine and I can connect perfectly.

I keep the SSH Password empty to use my public/private keys from ~/.ssh/

```
SSH connection failed!

Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o UserKnownHostsFile=/Users/__USER__/Library/Containers/com.sequel-ace.sequel-ace/Data/.keys/ssh_known_hosts_strict -F /Applications/Sequel Ace.app/Contents/Resources/ssh_config -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 __user__@__ip__ -L 58635:__server__.us-east-1.rds.amazonaws.com:3306
```

**Steps To Reproduce**
1. Configure a connection using SSH
2. Tap on **Test connection**

**Expected Behaviour**

Connect to the server perfectly

**Related Issues**

Can't Connect via Socket: https://github.com/Sequel-Ace/Sequel-Ace/issues/113
Access denied only in Sequel-Ace: https://github.com/Sequel-Ace/Sequel-Ace/issues/960

**Additional Context**

<img width="455" alt="Untitled 2" src="https://user-images.githubusercontent.com/870365/110964469-d6bb8780-8318-11eb-9643-c83f888179b5.png">

<img width="281" alt="Untitled" src="https://user-images.githubusercontent.com/870365/110963799-20f03900-8318-11eb-8ee9-d8fd8e5a25e4.png">

**Comment by mfehr94** [comment]
<img width="573" alt="sequel ace" src="https://user-images.githubusercontent.com/14167832/110969402-ef4b9200-8358-11eb-8148-b110d4e22c35.png">
I can select my ssh key file over the key button at the SSH Password field. Never tried to keep it empty. 
Do you have a special ssh config? Sequel Ace ist sandboxed so it can not read the ssh key file or the ssh config by its own. You have to give him the right to do it.

**Comment by RodolfoGS** [comment]
Got it, you're right. Sequel Age need to pass the ssh key file in that field. Now it's working perfectly.
Thank you so much @mfehr94!

**Comment by jpmurray** [comment]
Adding the file corrects the problem on my end, but the preferences doesn't seems to save ? I have to readd the key in accessible files each time I close and reopen Sequel Ace. Am I doing something wrong ?

**Comment by mfehr94** [comment]
@jpmurray cannot reproduce your issue, also not on the latest beta.

**Comment by jpmurray** [comment]
@mfehr94 I'll wait until the release then! ;-) 👍

**Comment by stephVenegas** [comment]
My connection fails every time, I guess this could be because I need to pass my password from my ssh key because otherwise the connection will be dropped, does anyone know how to do this?
