### ISSUE TITLE
Connection name hidden by db/server version

### ISSUE THREAD

**Issue by mirko77** [Sequel-Ace/Sequel-Ace#972]
I just updated to the latest build on Big Sur.

I noticed when I connect to a remote database I do not see the connection name only in the toolbar, but mysql/server version is prepended. I see the connection name only if I hover  as it expands

This is quite annoying as I always need to hover to expand it. It would be great to have an option to hide the mysql/server versions, I find more useful to know what remote database I am working on at a glance, when working with multiple connections to localhost, production, dev, staging, etc...

I tried to search for a duplicate issue but no success, I apologize if this was posted already.

<img width="360" alt="Screenshot 2021-03-15 at 17 46 40" src="https://user-images.githubusercontent.com/1233305/111190546-78f89b00-85b7-11eb-9bbc-cac722d50bc2.png">

See above, no connection name on small screens

As a workaround I removed a few controls from the toolbar and I am using the app fullscreen, still not ideal.

**Comment by Kaspik** [comment]
This was all changed in https://github.com/Sequel-Ace/Sequel-Ace/pull/970 so it might be improved in upcoming version. Stay tuned and let me know once that one will go out! :)

**Comment by mirko77** [comment]
@Kaspik thanks I missed that
