### ISSUE TITLE
Connection Stuck when using a specific remote server w/ Sequel-Ace 3

### ISSUE THREAD

**Issue by alzedd** [Sequel-Ace/Sequel-Ace#973]
- Sequel Ace Version 3.2.3 (3024) (tried 3.2.2 too and some other 3.x)
- Sequel Ace Source (App Store/GitHub/Homebrew): github (tried appstore, brew)
- macOS Version: 11.2.2
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.32-35
- macOS Localization: it_IT

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**  every version >=3 (latest 2.X is working fine)

**Description**
Unfortunally I cannot access the server configs, but I cannot connect to a single host. The connection seems to be stuck and I can wait forever. If I use Sequel-Ace 2.xx everything is fine, the connection is super fast and everything is working properly.

**Is there a way to get some logs to paste here?**

*I know it's like a shot in the dark, and the description is very unclean, but I don't know what else to add.*

**Expected Behaviour**
connection succeded (like when using 2.x)

**Comment by Jason-Morcos** [comment]
What type of connection are you attempting to make? SSH? TCP/IP? Both?
Are you using a custom SSH config file?
Any messages from Sequel Ace showing up in Console.app?

**Comment by alzedd** [comment]
I'm using TCP/IP connection.

No custom ssh config file, the behaviour is described above, once I click 'Connect', sequel-ace keeps showing "Connecting..." and it stays like that forever.

I did not know about console.app, i am going to update this comment once I get something useful.


By now the only useful thing is 
```
-[SPMySQLConnection(PrivateAPI) _disconnect]: Could not acquire connection lock within time limit (10s). Forcing unlock!
```

**Comment by Jason-Morcos** [comment]
> I'm using TCP/IP connection.
> 
> No custom ssh config file, the behaviour is described above, once I click 'Connect', sequel-ace keeps showing "Connecting..." and it stays like that forever.
> 
> I did not know about console.app, i am going to update this comment once I get something useful.
> 
> By now, from the console, the only useful thing shown is
> 
> ```
> -[SPMySQLConnection(PrivateAPI) _disconnect]: Could not acquire connection lock within time limit (10s). Forcing unlock!
> ```

Very odd - that error message is coming from the _disconnect method in SPMySQLConnection, which I'm not sure why that's being triggered. Any ideas, @Sequel-Ace/all?
