### ISSUE TITLE
Modifying the font does not take effect in `Create syntax`

### ISSUE THREAD

**Issue by latesun** [Sequel-Ace/Sequel-Ace#976]
macOS: Big Sur 11.2.3
Sequel Ace: 3.2.3

After modified font, it works.
![image](https://user-images.githubusercontent.com/54241888/111725555-3b8b5a80-88a2-11eb-9edf-9ac71dac51b5.png)

But when I changed another table, the font change default.
![image](https://user-images.githubusercontent.com/54241888/111725672-71c8da00-88a2-11eb-9cd7-f90835f7f30e.png)

**Comment by yadgen** [comment]
Hello Jason, when will this bug be resolved?
@Jason-Morcos

**Comment by Jason-Morcos** [comment]
> Hello Jason, when will this bug be resolved?
> 
> @Jason-Morcos 

This is a low priority issue that is purely aesthetic. It will likely be resolved when someone from the community makes a pull request to fix it, or when someone on the core team has such extensive bandwidth so as to have extra time to take care of it. I'm happy to provide assistance if you'd like to be the one to take a look at debugging and providing a fix!

**Comment by djibarian** [comment]
Low priority but very annoying, I must say.
