### ISSUE TITLE
Ugly colors in dark mode

### ISSUE THREAD

**Issue by seanr** [Sequel-Ace/Sequel-Ace#982]
- Sequel Ace Version (including build number): 3.2.3 (build 3024)
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.2.2
- Processor Type (Intel/Apple): Intel
- MySQL Version: N/A
- macOS Localization: None/default

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

Gave it a try but it doesn't load any of my favorites - can this be fixed to facilitate testing?

**Description**
Generally just seeing funky colors/contrast in both light and (especially) dark mode, particularly the sidebar:

<img width="1612" alt="Screen Shot 2021-03-26 at 12 15 39 PM" src="https://user-images.githubusercontent.com/199713/112663070-ca621f00-8e2e-11eb-9c4b-bc14440d9198.png">

<img width="1612" alt="Screen Shot 2021-03-26 at 12 13 36 PM" src="https://user-images.githubusercontent.com/199713/112663073-cb934c00-8e2e-11eb-9bf7-b08c5a1b7867.png">

I'm not really sure what those are _supposed_ to be, but they don't really sit well with the rest of the UI right now.

**Comment by Kaspik** [comment]
They grey font is already reported, otherwise I'm not sure what you are seeing (from the screenshots).

For beta - you can use migration, or just export import. :)

**Comment by seanr** [comment]
The background color is off, too. For the dark mode, it shouldn't be that flat middle gray on the left. It looks like maybe it was supposed to be partially transparent but wasn't? I just noticed that when I took a screenshot of a Finder window for comparison, the sidebar in the screenshot ended up looking like the one above, but in the case of Sequel Ace, it wasn't just the screenshot. ;)

**Comment by Kaspik** [comment]
The sidebar has transparent blur, so it colored based on what's behind. :)

<img width="463" alt="Screenshot 2021-03-30 at 19 19 45" src="https://user-images.githubusercontent.com/7204168/113029602-e5b18f00-918c-11eb-9e6b-4b65fe3f86f0.png">

**Comment by seanr** [comment]
Perhaps that should be revisited, then, as this looks truly ugly:

<img width="789" alt="Screen Shot 2021-04-01 at 10 57 00 AM" src="https://user-images.githubusercontent.com/199713/113313229-0d157280-92d9-11eb-8e8c-090c7411c2fe.png">

**Comment by seanr** [comment]
For comparison, here's Finder under the same circumstance. There's no gap between sections, which I think helps a lot:

<img width="345" alt="Screen Shot 2021-04-01 at 10 58 24 AM" src="https://user-images.githubusercontent.com/199713/113313462-44841f00-92d9-11eb-87e3-7b24b9125314.png">

**Comment by Kaspik** [comment]
That can't happen now due to legacy setup and code behind this. Once we move forward with auto-layout and modern "true" sidebar (like Finder and other apps do), we will definitely improve this. :) Thanks for the feedback!

**Comment by wietsewarendorff** [comment]
> The sidebar has transparent blur, so it colored based on what's behind. :)

Even worse: it's only transparent when the window is active :)

**Comment by Kaspik** [comment]
The same as native windows. :)
