### ISSUE TITLE
Horizontal line within quick connect button

### ISSUE THREAD

**Issue by AdrianFahrbach** [Sequel-Ace/Sequel-Ace#984]
- Sequel Ace Version: Version 3.2.3 (Build 3024)
- Sequel Ace Source: App Store
- macOS Version: 11.0.1 
- Processor Type: Intel
- MySQL Version: 8.0.22
- macOS Localization: DE

**Description**
The separator line underneath the quick connect button is inside that button. 
<img width="305" alt="Bildschirmfoto 2021-03-29 um 11 13 09" src="https://user-images.githubusercontent.com/45072099/112815205-5e76f500-9080-11eb-9e89-b357f4b70c7d.png">

<img width="277" alt="Bildschirmfoto 2021-03-29 um 11 13 05" src="https://user-images.githubusercontent.com/45072099/112815200-5d45c800-9080-11eb-9511-2225e56acd2d.png">

**Comment by Kaspik** [comment]
Known issue, will be fixed with autolayout in the future. :)
