### ISSUE TITLE
Memory Leak Doing Export/Import

### ISSUE THREAD

**Issue by thomhickey** [Sequel-Ace/Sequel-Ace#985]
- Sequel Ace Version (including build number): Version 3.2.3 Build 3024
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: Catalina 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: MariaDB 10.3.11 (MySQL 5.5.5)
- macOS Localization: English/US

**Description**
Exporting/Importing seems to consume approximately 6X the amount of RAM as the size of the export/import.

**Steps To Reproduce**
1. connect to a >10GB db
2. choose export from the file menu
3. leave all settings as default
4. choose Export

**Expected Behaviour**
Sequel-Ace does not consume 6X the ram as the size of the export. 

**Additional Context**
In my case I generated a 13GB dump file, but Sequel-Ace was consuming 85GB of RAM. My Mac gave me the "out of application memory" error, so I force-quit some apps. The export was able to finish. I tried to import into the db I wanted to move the data to, but I quit Sequel-Ace when it started consuming tons of RAM again. Sequel-Pro does not exhibit this behavior, FYI. Sequel-Pro is happily importing the 13GB now and staying at a steady 194MB of memory.

**Comment by Kaspik** [comment]
Just to confirm - exporting `SQL`, not `CSV`, right? (I don't have that big tables, but I'm seeing export issue with SQL method). I know what is causing this and the fix is quite simple, the reason why SP works and SA does not is that SA has ARC enabled since 3.0.0.

**Comment by thomhickey** [comment]
Yes, export as SQL. Thanks for the quick response.

**Comment by Kaspik** [comment]
Got a PR open for 3.3.0 submit tomorrow.

Current AppStore:

<img width="994" alt="Screenshot 2021-03-31 at 23 54 02" src="https://user-images.githubusercontent.com/7204168/113216377-8c288d80-927c-11eb-84f3-d2396982bebc.png">


This PR:
<img width="997" alt="Screenshot 2021-03-31 at 23 55 03" src="https://user-images.githubusercontent.com/7204168/113216389-921e6e80-927c-11eb-9591-4f2da5fac7d9.png">


We are talking about 2.6GB vs 0.5GB at peak for 350MB export. Thanks for raising this issue.

**Comment by Kaspik** [comment]
Took a look at the import as well in https://github.com/Sequel-Ace/Sequel-Ace/pull/988/commits/1d59c1c21809d9e572a6f62bc63c1b311762b733, here is the result:

Current AppStore:
<img width="1019" alt="Screenshot 2021-04-01 at 0 08 35" src="https://user-images.githubusercontent.com/7204168/113217609-71571880-927e-11eb-93da-cdcf90ad3399.png">

This PR:
<img width="1000" alt="Screenshot 2021-04-01 at 0 06 39" src="https://user-images.githubusercontent.com/7204168/113217600-6dc39180-927e-11eb-976e-cd94aac1bc60.png">

**Comment by thomhickey** [comment]
Thanks for fixing so quickly!!

**Comment by thomhickey** [comment]
I’m wondering, though, should it consume more ram than it is exporting? .5GB for 350MB export? Again, I refer to the Sequel Pro which never seemed to consume more than 200MB even when importing 13GB.

**Comment by Kaspik** [comment]
It doesn't consume more, it consumes the same or less, the rest is in-app memory already used for the rest of the app I believe. :)

The ARC optimization will need to happen across the app in upcoming months.
