### ISSUE TITLE
[Question] Open connection via command line

### ISSUE THREAD

**Issue by pedrodurek** [Sequel-Ace/Sequel-Ace#986]
### Question
Is there a way to open a connection via command line? Something like:
```sh
$ open sequelace://{host}/{user}:{password}
```

Thanks!

**Comment by Jason-Morcos** [comment]
Support for opening URLs in the MySQL URL schema is supported by the App Store release of Sequel Ace.
We support URLs in the structure:
`mysql://[user[:password]@][host[:port]][/database]`

There isn't a way that I'm aware of to specifically target Sequel Ace, but these mysql:// links do open successfully in Ace :)

**Comment by pedrodurek** [comment]
Thanks @Jason-Morcos !
