### ISSUE TITLE
Dark Mode: "Binary as Hex" color is hard to read

### ISSUE THREAD

**Issue by marconett** [Sequel-Ace/Sequel-Ace#989]
Version 3.2.3 Build 3024

![Screen Shot 2021-04-01 at 11 59 48](https://user-images.githubusercontent.com/3315507/113278231-f7587b00-92e1-11eb-9e17-9f77c05a824d.png)

With the option "Display Binary Data as Hex" enabled,  blue text on dark background is hard to read. Should be a different color for dark mode.

**Comment by Kaspik** [comment]
Not able to verify as I have no table with binary data right now, but should be fixed for upcoming release / beta.
