### ISSUE TITLE
"Unknown or incorrect time zone: 'GMT'" error when attempting to connect to a favorite

### ISSUE THREAD

**Issue by mr-mmmmore** [Sequel-Ace/Sequel-Ace#991]
- Sequel Ace Version: 3.2.3+3024
- Sequel Ace Source: App Store
- macOS Version: 10.14.6 (Mojave)
- Processor Type: Intel
- MySQL Version: 10.2.14-MariaDB-10.2.14+maria~xenial-log
- macOS Localization: FR

**Description**
When opening a Favorite connection that has the "GMT" time zone set, I get this error message:

> Unknown or incorrect time zone: 'GMT'
> time_zone will be set to SYSTEM.

The problem has appeared right after upgrading to the 3.2.3 version. I don't know what version I had before this.

**Steps To Reproduce**
1. Create a favorite where the time zone is set to "GMT"
2. Try to connect

**Expected Behaviour**
No error message should show since the zone has been chosen in a list of available time zones.

**Comment by Jason-Morcos** [comment]
I believe what's happening is you're now seeing the error message instead of it failing silently. I think that was added in a recent release (#884).
The issue is #914
