### ISSUE TITLE
lost work in SQL tab if connection is lost

### ISSUE THREAD

**Issue by surrain** [Sequel-Ace/Sequel-Ace#992]
I'm using
Version 3.2.3
Build 3024
on MacOS 11.2.3

If an operation fails because the connection is closed, modal dialogues take over trying to restore the connection. If that fails, the only options are to try again or close the connection and the whole window. This often happens to me when I have unsaved work in my SQL tab which I have no way to recovering. Can you make a way to dismiss the modal even if the connection is closed so that I can access the SQL tab to either save or copy out that text before reopening the connection in another window?

Thanks,
Aaron

**Comment by Kaspik** [comment]
When the app closes, the SQL is saved into history, so next time you open the Query window, in history it should be saved. Isn't that the case?

We also made major changes in windows in recent beta and will release that soon.

**Comment by surrain** [comment]
Thanks for the quick reply.

What I'm talking about is not the app closing, but just the window of 
the connection. It does not restore for me. I need to open a new 
connection and the window that appears has no memory of the SQL from the 
window I had to close because the connection was lost.

**Comment by Jason-Morcos** [comment]
Closing in favor of #658
We know this id an issue but haven't been able to fix it. Help is welcome and wanted!
